import {describe,expect,it} from 'vitest';
import {attackRelease,equalPowerPan,smoothstep} from '../../src/3d/audio/audioCurveMath.ts';
import {AudioCueScheduler} from '../../src/3d/audio/audioCueScheduler.ts';
import {buildGpuPassBudgetPlan,createGpuPassBudgetController,recommendDynamicResolution,validateGpuPassBudgetPlan} from '../../src/3d/rendering/gpuPassBudget.ts';
import {createRenderMetricsCollector} from '../../src/3d/rendering/renderMetricsCollector.ts';
describe('strict production policy R19',()=>{
it('bounds audio curves and keeps deterministic math',()=>{expect(smoothstep(0,1,.5)).toBeCloseTo(.5);expect(equalPowerPan(-1).left).toBeCloseTo(1);expect(equalPowerPan(1).right).toBeCloseTo(1);expect(attackRelease(0,1,.1)).toBeGreaterThan(0);});
it('admits audio cues with bounded priority ordering and cooldowns',()=>{const scheduler=new AudioCueScheduler({maxQueue:8,maxHistory:8});expect(scheduler.enqueue({id:'a',kind:'ui',priority:20})).toBe(true);expect(scheduler.dequeue(1)[0]?.id).toBe('a');expect(scheduler.enqueue({id:'a',kind:'ui',priority:20})).toBe(false);scheduler.advance(.04);expect(scheduler.enqueue({id:'a',kind:'ui',priority:20})).toBe(true);scheduler.dispose();expect(scheduler.enqueue({id:'b'})).toBe(false);});
it('produces bounded GPU plans and adaptive scale recommendations',()=>{const plan=buildGpuPassBudgetPlan({estimatedGpuMs:20,pressure:.6});expect(validateGpuPassBudgetPlan(plan)).toBe(true);expect(plan.gpuBudgetMs).toBeGreaterThan(0);expect(plan.estimatedAfterSheddingMs).toBeLessThanOrEqual(plan.estimatedGpuMs);const rec=recommendDynamicResolution({currentScale:1,measuredGpuMs:20});expect(rec.recommendedScale).toBeLessThan(1);const controller=createGpuPassBudgetController();expect(controller.plan().frame).toBe(1);expect(controller.snapshot().history).toHaveLength(1);controller.dispose();});
it('keeps render telemetry bounded, normalized and disposable',()=>{const collector=createRenderMetricsCollector({policy:{maxFrames:2,maxEvents:2,maxSamples:3}});collector.recordFrame({frameMs:16,gpuMs:9,drawCalls:100,triangles:1000,backend:'webgpu'});collector.recordFrame({frameMs:18,gpuMs:12,drawCalls:120,triangles:1200});collector.recordFrame({frameMs:20,gpuMs:14,drawCalls:140,triangles:1400});collector.event('gpu',{lost:false},10);collector.event('gpu',{lost:true},20);collector.event('gpu',{lost:true},30);const snapshot=collector.snapshot();expect(snapshot.recentFrames).toHaveLength(2);expect(snapshot.events).toHaveLength(2);expect(snapshot.samples.frameMs.p95).toBeGreaterThan(0);collector.dispose();expect(collector.disposed).toBe(true);expect(collector.snapshot().disposed).toBe(true);});
});