import { clamp, distanceSq, stableSort, type Disposable, type EntityId, type Vec3 } from './primitives.js';

export type AudioBus = 'master' | 'music' | 'sfx' | 'ambient' | 'voice' | 'ui';
export interface AudioEmitter { readonly id: string; readonly entity: EntityId | null; readonly position: Vec3; readonly radius: number; readonly bus: AudioBus; readonly gain: number; readonly priority: number; readonly occlusion01: number; readonly loop: boolean; }
export interface AudioVoice { readonly id: string; readonly emitter: string | null; readonly clip: string; readonly startedTick: number; readonly durationTicks: number; readonly baseGain: number; readonly priority: number; }
export interface AudioMix { readonly master: number; readonly music: number; readonly sfx: number; readonly ambient: number; readonly voice: number; readonly ui: number; }
export interface AudioFrame { readonly tick: number; readonly listener: Vec3; readonly voices: readonly (AudioVoice & { readonly gain: number; readonly virtualized: boolean; readonly pan: number })[]; readonly digest: string; }

const DEFAULT_MIX: AudioMix = Object.freeze({ master: 1, music: .65, sfx: .85, ambient: .7, voice: 1, ui: .9 });
function attenuation(distance: number, radius: number): number { return distance >= radius ? 0 : 1 - clamp(distance / Math.max(.01, radius), 0, 1); }

export class SpatialAudioGraph implements Disposable {
  #emitters = new Map<string, AudioEmitter>(); #voices = new Map<string, AudioVoice>(); #listener: Vec3 = Object.freeze({ x: 0, y: 0, z: 0 }); #mix = DEFAULT_MIX; #tick = 0; #serial = 0; #disposed = false; #virtualized = 0;
  registerEmitter(input: Omit<AudioEmitter, 'id'> & { id: string }): boolean { if (this.#disposed || !input.id || this.#emitters.has(input.id)) return false; this.#emitters.set(input.id, Object.freeze({ ...input, id: input.id, radius: Math.max(.1, input.radius), gain: clamp(input.gain, 0, 1), priority: clamp(input.priority, -1000, 1000), occlusion01: clamp(input.occlusion01, 0, 1) })); return true; }
  removeEmitter(id: string): boolean { const removed = this.#emitters.delete(id); for (const [voiceId, voice] of this.#voices) if (voice.emitter === id) this.#voices.delete(voiceId); return removed; }
  setListener(position: Vec3): void { if (!this.#disposed) this.#listener = Object.freeze({ ...position }); }
  setMix(mix: Partial<AudioMix>): void { if (this.#disposed) return; this.#mix = Object.freeze({ ...this.#mix, ...Object.fromEntries(Object.entries(mix).map(([key, value]) => [key, clamp(Number(value), 0, 1)])) } as AudioMix); }
  play(emitter: string, clip: string, durationTicks = 300, baseGain = 1): string | null { const source = this.#emitters.get(emitter); if (!source || this.#disposed || !clip) return null; const id = `${emitter}:${this.#tick}:${++this.#serial}`; this.#voices.set(id, Object.freeze({ id, emitter, clip, startedTick: this.#tick, durationTicks: Math.max(1, Math.trunc(durationTicks)), baseGain: clamp(baseGain, 0, 1), priority: source.priority })); return id; }
  playDetached(clip: string, durationTicks = 300, baseGain = 1, priority = 0): string | null { if (this.#disposed || !clip) return null; const id = `detached:${this.#tick}:${++this.#serial}`; this.#voices.set(id, Object.freeze({ id, emitter: null, clip, startedTick: this.#tick, durationTicks: Math.max(1, Math.trunc(durationTicks)), baseGain: clamp(baseGain, 0, 1), priority })); return id; }
  stop(id: string): boolean { return this.#voices.delete(id); }
  update(tick: number): void { if (this.#disposed) return; this.#tick = Math.max(this.#tick, Math.trunc(tick)); for (const [id, voice] of this.#voices) if (this.#tick - voice.startedTick >= voice.durationTicks) this.#voices.delete(id); }
  frame(): AudioFrame { const voices = stableSort([...this.#voices.values()], (a, b) => b.priority - a.priority || a.startedTick - b.startedTick || a.id.localeCompare(b.id)).map((voice) => { const emitter = voice.emitter ? this.#emitters.get(voice.emitter) : undefined; const distance = emitter ? Math.sqrt(distanceSq(this.#listener, emitter.position)) : 0; const spatial = emitter ? attenuation(distance, emitter.radius) : 1; const bus = emitter ? this.#mix[emitter.bus] : this.#mix.master; const occlusion = emitter ? 1 - emitter.occlusion01 * .8 : 1; const gain = clamp(voice.baseGain * bus * this.#mix.master * spatial * occlusion * (emitter?.gain ?? 1), 0, 2); const pan = emitter ? clamp((emitter.position.x - this.#listener.x) / Math.max(1, distance), -1, 1) : 0; const virtualized = gain < .008; if (virtualized) this.#virtualized += 1; return Object.freeze({ ...voice, gain, virtualized, pan }); }); return Object.freeze({ tick: this.#tick, listener: this.#listener, voices: Object.freeze(voices), digest: `${this.#tick}:${voices.map((voice) => `${voice.id}:${voice.gain.toFixed(4)}:${voice.pan.toFixed(4)}`).join('|')}` }); }
  stats(): Readonly<{ emitters: number; voices: number; playing: number; virtualized: number }> { const frame = this.frame(); return Object.freeze({ emitters: this.#emitters.size, voices: this.#voices.size, playing: frame.voices.filter((voice) => !voice.virtualized).length, virtualized: frame.voices.filter((voice) => voice.virtualized).length }); }
  emitters(): readonly AudioEmitter[] { return Object.freeze(stableSort([...this.#emitters.values()], (a, b) => a.id.localeCompare(b.id))); }
  voices(): readonly AudioVoice[] { return Object.freeze(stableSort([...this.#voices.values()], (a, b) => a.id.localeCompare(b.id))); }
  dispose(): void { this.#disposed = true; this.#emitters.clear(); this.#voices.clear(); }
}
