import { clamp, integer, stableSort, type Disposable, type EntityId } from './primitives.js';

export type BehaviorStatus = 'idle' | 'running' | 'success' | 'failure';
export type BehaviorKind = 'sequence' | 'selector' | 'condition' | 'action' | 'cooldown' | 'repeat' | 'parallel';
export interface BehaviorContext { readonly actor: EntityId; readonly tick: number; readonly facts: ReadonlyMap<string, number | boolean | string>; readonly blackboard: Map<string, unknown>; }
export interface BehaviorNode { readonly id: string; readonly kind: BehaviorKind; readonly children?: readonly BehaviorNode[]; readonly condition?: (context: BehaviorContext) => boolean; readonly action?: (context: BehaviorContext) => BehaviorStatus; readonly cooldownTicks?: number; readonly repeatCount?: number; readonly successThreshold?: number; readonly failureThreshold?: number; }
export interface BehaviorNodeState { readonly status: BehaviorStatus; readonly childIndex: number; readonly cooldownUntil: number; readonly repeats: number; readonly visits: number; }
export interface BehaviorEvaluation { readonly actor: EntityId; readonly root: string; readonly status: BehaviorStatus; readonly visited: number; readonly actions: number; readonly transitions: number; }
export interface BehaviorStats { readonly actors: number; readonly ticks: number; readonly nodesVisited: number; readonly actions: number; readonly failures: number; readonly successes: number; readonly running: number; }

const idleState = (): BehaviorNodeState => Object.freeze({ status: 'idle', childIndex: 0, cooldownUntil: 0, repeats: 0, visits: 0 });

export class DeterministicBehaviorRuntime implements Disposable {
  #roots = new Map<EntityId, BehaviorNode>(); #states = new Map<EntityId, Map<string, BehaviorNodeState>>(); #facts = new Map<EntityId, Map<string, number | boolean | string>>(); #blackboards = new Map<EntityId, Map<string, unknown>>(); #disposed = false; #ticks = 0; #visited = 0; #actions = 0; #failures = 0; #successes = 0;
  register(actor: EntityId, root: BehaviorNode): boolean { if (this.#disposed || !root.id || this.#roots.has(actor) || !this.#validate(root, new Set())) return false; this.#roots.set(actor, root); this.#states.set(actor, new Map()); this.#facts.set(actor, new Map()); this.#blackboards.set(actor, new Map()); return true; }
  unregister(actor: EntityId): boolean { this.#states.delete(actor); this.#facts.delete(actor); this.#blackboards.delete(actor); return this.#roots.delete(actor); }
  setFact(actor: EntityId, key: string, value: number | boolean | string): boolean { const map = this.#facts.get(actor); if (!map || !key) return false; map.set(key, value); return true; }
  setFacts(actor: EntityId, facts: Readonly<Record<string, number | boolean | string>>): boolean { const map = this.#facts.get(actor); if (!map) return false; for (const [key, value] of Object.entries(facts)) this.setFact(actor, key, value); return true; }
  fact(actor: EntityId, key: string): number | boolean | string | undefined { return this.#facts.get(actor)?.get(key); }
  setBlackboard(actor: EntityId, key: string, value: unknown): boolean { const map = this.#blackboards.get(actor); if (!map || !key) return false; map.set(key, value); return true; }
  blackboard(actor: EntityId, key: string): unknown { return this.#blackboards.get(actor)?.get(key); }
  tick(actor: EntityId, tick: number): BehaviorEvaluation | null { const root = this.#roots.get(actor); if (!root || this.#disposed) return null; this.#ticks += 1; const context: BehaviorContext = Object.freeze({ actor, tick: integer(tick), facts: this.#facts.get(actor) ?? new Map(), blackboard: this.#blackboards.get(actor) ?? new Map() }); const before = this.#visited; const actionBefore = this.#actions; const state = this.#visit(root, context); const evaluation = Object.freeze({ actor, root: root.id, status: state.status, visited: this.#visited - before, actions: this.#actions - actionBefore, transitions: Number(state.status !== 'running') }); if (state.status === 'failure') this.#failures += 1; if (state.status === 'success') this.#successes += 1; return evaluation; }
  tickAll(tick: number, limit = 1024): readonly BehaviorEvaluation[] { if (this.#disposed) return []; const actors = stableSort([...this.#roots.keys()], (a, b) => String(a).localeCompare(String(b))).slice(0, clamp(integer(limit), 1, 8192)); const evaluations: BehaviorEvaluation[] = []; for (const actor of actors) { const result = this.tick(actor, tick); if (result) evaluations.push(result); } return Object.freeze(evaluations); }
  state(actor: EntityId, nodeId: string): BehaviorNodeState { return this.#states.get(actor)?.get(nodeId) ?? idleState(); }
  reset(actor?: EntityId): void { if (actor === undefined) for (const map of this.#states.values()) map.clear(); else this.#states.get(actor)?.clear(); }
  stats(): BehaviorStats { const running = [...this.#states.values()].reduce((sum, map) => sum + [...map.values()].filter((state) => state.status === 'running').length, 0); return Object.freeze({ actors: this.#roots.size, ticks: this.#ticks, nodesVisited: this.#visited, actions: this.#actions, failures: this.#failures, successes: this.#successes, running }); }
  dispose(): void { this.#disposed = true; this.#roots.clear(); this.#states.clear(); this.#facts.clear(); this.#blackboards.clear(); }
  #visit(node: BehaviorNode, context: BehaviorContext): BehaviorNodeState {
    this.#visited += 1; const states = this.#states.get(context.actor)!; const previous = states.get(node.id) ?? idleState(); const children = node.children ?? [];
    if (node.kind === 'condition') return this.#store(context.actor, node.id, { status: node.condition?.(context) ? 'success' : 'failure', childIndex: 0, cooldownUntil: 0, repeats: previous.repeats, visits: previous.visits + 1 });
    if (node.kind === 'action') { const status = node.action?.(context) ?? 'failure'; this.#actions += 1; return this.#store(context.actor, node.id, { status, childIndex: 0, cooldownUntil: 0, repeats: previous.repeats, visits: previous.visits + 1 }); }
    if (!children.length) return this.#store(context.actor, node.id, { status: 'failure', childIndex: 0, cooldownUntil: 0, repeats: previous.repeats, visits: previous.visits + 1 });
    if (node.kind === 'cooldown') { if (context.tick < previous.cooldownUntil) return previous; const child = this.#visit(children[0]!, context); const until = child.status === 'success' ? context.tick + clamp(integer(node.cooldownTicks ?? 1), 1, 100_000) : 0; return this.#store(context.actor, node.id, { ...child, cooldownUntil: until }); }
    if (node.kind === 'repeat') { const limit = clamp(integer(node.repeatCount ?? 1), 1, 128); const child = this.#visit(children[Math.min(previous.childIndex, children.length - 1)]!, context); let repeats = previous.repeats; if (child.status === 'success') repeats += 1; const done = repeats >= limit || child.status === 'failure'; return this.#store(context.actor, node.id, { status: done ? child.status : 'running', childIndex: 0, cooldownUntil: 0, repeats: done ? 0 : repeats, visits: previous.visits + 1 }); }
    if (node.kind === 'parallel') { let success = 0; let failure = 0; let visited = 0; for (const child of children) { const result = this.#visit(child, context); visited += 1; success += Number(result.status === 'success'); failure += Number(result.status === 'failure'); } const successThreshold = clamp(integer(node.successThreshold ?? children.length), 1, children.length); const failureThreshold = clamp(integer(node.failureThreshold ?? 1), 1, children.length); const status: BehaviorStatus = success >= successThreshold ? 'success' : failure >= failureThreshold ? 'failure' : 'running'; return this.#store(context.actor, node.id, { status, childIndex: visited, cooldownUntil: 0, repeats: previous.repeats, visits: previous.visits + 1 }); }
    const selector = node.kind === 'selector'; let index = Math.min(previous.childIndex, children.length - 1); let last: BehaviorNodeState = idleState(); for (; index < children.length; index += 1) { last = this.#visit(children[index]!, context); if (selector ? last.status !== 'failure' : last.status !== 'success') return this.#store(context.actor, node.id, { ...last, childIndex: index }); } return this.#store(context.actor, node.id, { status: selector ? 'failure' : 'success', childIndex: 0, cooldownUntil: 0, repeats: previous.repeats, visits: previous.visits + 1 });
  }
  #store(actor: EntityId, nodeId: string, state: BehaviorNodeState): BehaviorNodeState { const frozen = Object.freeze({ ...state, visits: integer(state.visits) }); this.#states.get(actor)!.set(nodeId, frozen); return frozen; }
  #validate(node: BehaviorNode, seen: Set<string>): boolean { if (!node.id || seen.has(node.id) || seen.size > 1024) return false; seen.add(node.id); if (node.kind === 'condition' && typeof node.condition !== 'function') return false; if (node.kind === 'action' && typeof node.action !== 'function') return false; return (node.children ?? []).every((child) => this.#validate(child, seen)); }
}
