import { clamp, digest, stableSort, type Disposable, type EntityId, type V7Result } from './primitives.js';

export type CombatPhase = 'idle' | 'windup' | 'active' | 'recovery' | 'stunned' | 'defeated';
export type CombatAction = 'light' | 'heavy' | 'ranged' | 'guard' | 'parry' | 'dodge';
export interface CombatActor { readonly id: EntityId; readonly health: number; readonly stamina: number; readonly poise: number; readonly phase: CombatPhase; readonly action: CombatAction | null; readonly progress: number; readonly revision: number; }
export interface CombatActionResult { readonly accepted: boolean; readonly action: CombatAction | null; readonly phase: CombatPhase; readonly staminaCost: number; readonly reason: string; readonly digest: string; }
export interface CombatImpact { readonly source: EntityId; readonly target: EntityId; readonly action: CombatAction; readonly damage: number; readonly poiseDamage: number; readonly blocked: boolean; readonly parried: boolean; readonly defeated: boolean; readonly serial: number; }
export interface CombatStats { readonly actors: number; readonly accepted: number; readonly rejected: number; readonly impacts: number; readonly defeats: number; }

const cost: Record<CombatAction, number> = { light: 8, heavy: 18, ranged: 5, guard: 1, parry: 3, dodge: 10 };
const duration: Record<CombatAction, number> = { light: 18, heavy: 34, ranged: 22, guard: 12, parry: 10, dodge: 14 };

export class DeterministicCombatRuntime implements Disposable {
  #actors = new Map<EntityId, CombatActor>(); #impacts: CombatImpact[] = []; #accepted = 0; #rejected = 0; #defeats = 0; #serial = 0; #disposed = false;
  register(actor: Omit<CombatActor, 'id' | 'revision'> & { id: string }): boolean { if (this.#disposed || this.#actors.has(actor.id)) return false; this.#actors.set(actor.id as EntityId, Object.freeze({ ...actor, id: actor.id as EntityId, health: clamp(actor.health, 0, 100), stamina: clamp(actor.stamina, 0, 100), poise: clamp(actor.poise, 0, 100), progress: clamp(actor.progress, 0, 1), revision: 0 })); return true; }
  request(id: EntityId, action: CombatAction): CombatActionResult { const actor = this.#actors.get(id); if (!actor || actor.phase === 'defeated') return Object.freeze({ accepted: false, action: null, phase: actor?.phase ?? 'defeated', staminaCost: 0, reason: 'actor-unavailable', digest: digest(id, action, 'actor-unavailable') }); const phaseAllowed = actor.phase === 'idle' || actor.phase === 'recovery'; const staminaCost = cost[action]; const accepted = phaseAllowed && actor.stamina >= staminaCost && actor.poise > 0; const reason = !phaseAllowed ? 'phase-locked' : actor.stamina < staminaCost ? 'stamina-low' : actor.poise <= 0 ? 'poise-broken' : 'accepted'; if (accepted) { this.#accepted += 1; this.#actors.set(id, Object.freeze({ ...actor, action, phase: 'windup', progress: 0, stamina: actor.stamina - staminaCost, revision: actor.revision + 1 })); } else this.#rejected += 1; return Object.freeze({ accepted, action: accepted ? action : null, phase: accepted ? 'windup' : actor.phase, staminaCost: accepted ? staminaCost : 0, reason, digest: digest(id, action, accepted, reason, actor.revision) }); }
  tick(): void { if (this.#disposed) return; for (const actor of this.actors()) { if (actor.phase === 'defeated') continue; const nextProgress = actor.action ? actor.progress + 1 / duration[actor.action] : 0; let phase = actor.phase; let action = actor.action; let progress = actor.progress; if (actor.action && nextProgress >= 1) { phase = 'recovery'; action = null; progress = 0; } else if (actor.action) progress = nextProgress; else if (actor.phase === 'recovery') phase = 'idle'; const stamina = clamp(actor.stamina + 2, 0, 100); this.#actors.set(actor.id, Object.freeze({ ...actor, phase, action, progress, stamina, revision: actor.revision + 1 })); } }
  impact(source: EntityId, target: EntityId, damage: number, poiseDamage: number): V7Result<CombatImpact> { const attacker = this.#actors.get(source); const defender = this.#actors.get(target); if (!attacker || !defender || !attacker.action || defender.phase === 'defeated') return { ok: false, code: 'IMPACT_INVALID', message: 'Combat impact prerequisites are not met', retryable: false }; const blocked = defender.phase === 'windup' && defender.action === 'guard'; const parried = defender.action === 'parry' && defender.phase === 'active'; const finalDamage = parried ? 0 : blocked ? Math.max(0, damage * .15) : Math.max(0, damage); const health = clamp(defender.health - finalDamage, 0, 100); const finalPoise = clamp(defender.poise - (parried ? 0 : Math.max(0, poiseDamage)), 0, 100); const defeated = health <= 0; const impact = Object.freeze({ source, target, action: attacker.action, damage: finalDamage, poiseDamage: Math.max(0, poiseDamage), blocked, parried, defeated, serial: ++this.#serial }); this.#actors.set(target, Object.freeze({ ...defender, health, poise: finalPoise, phase: defeated ? 'defeated' : finalPoise <= 0 ? 'stunned' : defender.phase, action: defeated ? null : defender.action, progress: defeated ? 0 : defender.progress, revision: defender.revision + 1 })); this.#impacts.push(impact); if (this.#impacts.length > 256) this.#impacts.shift(); if (defeated) this.#defeats += 1; return { ok: true, value: impact }; }
  actor(id: EntityId): CombatActor | undefined { return this.#actors.get(id); }
  actors(): readonly CombatActor[] { return Object.freeze(stableSort([...this.#actors.values()], (a, b) => String(a.id).localeCompare(String(b.id)))); }
  impacts(): readonly CombatImpact[] { return Object.freeze([...this.#impacts]); }
  stats(): CombatStats { return Object.freeze({ actors: this.#actors.size, accepted: this.#accepted, rejected: this.#rejected, impacts: this.#impacts.length, defeats: this.#defeats }); }
  dispose(): void { this.#disposed = true; this.#actors.clear(); this.#impacts.length = 0; }
}
