import { clamp, stableSort, type Disposable, type EntityId } from './primitives.js';

export type QuestState = 'locked' | 'available' | 'active' | 'completed' | 'failed' | 'abandoned';
export interface QuestObjective { readonly id: string; readonly kind: 'collect' | 'reach' | 'defeat' | 'interact' | 'survive' | 'escort'; readonly target: string | null; readonly required: number; readonly progress: number; readonly optional: boolean; }
export interface QuestDefinition { readonly id: string; readonly title: string; readonly prerequisites: readonly string[]; readonly objectives: readonly Omit<QuestObjective, 'progress'>[]; readonly reward: Readonly<Record<string, number>>; readonly expiresAtTick: number | null; }
export interface QuestRecord { readonly id: string; readonly state: QuestState; readonly objectives: readonly QuestObjective[]; readonly startedAt: number | null; readonly completedAt: number | null; readonly revision: number; }
export interface QuestEvent { readonly actor: EntityId; readonly quest: string; readonly objective: string; readonly amount: number; readonly tick: number; }

export class QuestRuntime implements Disposable {
  #defs = new Map<string, QuestDefinition>(); #quests = new Map<EntityId, Map<string, QuestRecord>>(); #events: QuestEvent[] = []; #disposed = false;
  register(definition: QuestDefinition): boolean { if (this.#disposed || !definition.id || this.#defs.has(definition.id) || definition.objectives.length > 128) return false; const objectives = definition.objectives.map((objective) => ({ ...objective, required: Math.max(1, Math.trunc(objective.required)) })); this.#defs.set(definition.id, Object.freeze({ ...definition, prerequisites: Object.freeze([...new Set(definition.prerequisites)]), objectives: Object.freeze(objectives), reward: Object.freeze({ ...definition.reward }) })); return true; }
  available(actor: EntityId): readonly QuestDefinition[] { const records = this.#quests.get(actor) ?? new Map(); return Object.freeze(stableSort([...this.#defs.values()].filter((definition) => !records.get(definition.id) || ['locked', 'available'].includes(records.get(definition.id)!.state)).filter((definition) => definition.prerequisites.every((id) => records.get(id)?.state === 'completed')), (a, b) => a.id.localeCompare(b.id))); }
  accept(actor: EntityId, questId: string, tick: number): boolean { if (this.#disposed) return false; const def = this.#defs.get(questId); if (!def) return false; const records = this.#quests.get(actor) ?? new Map(); const current = records.get(questId); if (current?.state === 'active' || current?.state === 'completed') return false; if (!def.prerequisites.every((id) => records.get(id)?.state === 'completed')) return false; const objectives = Object.freeze(def.objectives.map((objective) => Object.freeze({ ...objective, progress: 0 }))); records.set(questId, Object.freeze({ id: questId, state: 'active', objectives, startedAt: Math.trunc(tick), completedAt: null, revision: (current?.revision ?? 0) + 1 })); this.#quests.set(actor, records); return true; }
  progress(actor: EntityId, questId: string, objectiveId: string, amount: number, tick: number): QuestRecord | null { const record = this.#quests.get(actor)?.get(questId); const def = this.#defs.get(questId); if (!record || !def || record.state !== 'active') return null; if (def.expiresAtTick !== null && tick > def.expiresAtTick) { const failed = Object.freeze({ ...record, state: 'failed' as const, revision: record.revision + 1 }); this.#quests.get(actor)!.set(questId, failed); return failed; } const safeAmount = clamp(amount, 0, 1_000_000); let changed = false; const objectives = Object.freeze(record.objectives.map((objective) => { if (objective.id !== objectiveId) return objective; const progress = clamp(objective.progress + safeAmount, 0, objective.required); changed = true; return Object.freeze({ ...objective, progress }); })); if (!changed) return record; this.#events.push(Object.freeze({ actor, quest: questId, objective: objectiveId, amount: safeAmount, tick: Math.trunc(tick) })); if (this.#events.length > 2048) this.#events.shift(); const mandatoryComplete = objectives.every((objective) => objective.optional || objective.progress >= objective.required); const next = Object.freeze({ ...record, state: mandatoryComplete ? 'completed' as const : 'active' as const, objectives, completedAt: mandatoryComplete ? Math.trunc(tick) : null, revision: record.revision + 1 }); this.#quests.get(actor)!.set(questId, next); return next; }
  record(actor: EntityId, questId: string): QuestRecord | undefined { return this.#quests.get(actor)?.get(questId); }
  records(actor: EntityId): readonly QuestRecord[] { return Object.freeze(stableSort([...(this.#quests.get(actor)?.values() ?? [])], (a, b) => a.id.localeCompare(b.id))); }
  events(): readonly QuestEvent[] { return Object.freeze([...this.#events]); }
  abandon(actor: EntityId, questId: string): boolean { const record = this.record(actor, questId); if (!record || record.state !== 'active') return false; this.#quests.get(actor)!.set(questId, Object.freeze({ ...record, state: 'abandoned', revision: record.revision + 1 })); return true; }
  resetActor(actor: EntityId): void { this.#quests.delete(actor); }
  dispose(): void { this.#disposed = true; this.#defs.clear(); this.#quests.clear(); this.#events.length = 0; }
}
