import { clamp, integer, stableSort, type Disposable, type ResourceId } from './primitives.js';

export type StreamState = 'cold' | 'queued' | 'loading' | 'resident' | 'unloading' | 'evicted';
export interface StreamNode { readonly id: ResourceId; readonly priority: number; readonly bytes: number; readonly dependencies: readonly ResourceId[]; readonly state: StreamState; readonly lastUsedTick: number; readonly required: boolean; }
export interface StreamRequest { readonly id: ResourceId; readonly priority: number; readonly distance: number; readonly reason: 'visible' | 'nearby' | 'prefetch' | 'restore' | 'manual'; readonly requestedAt: number; }
export interface StreamPlan { readonly loads: readonly ResourceId[]; readonly evicts: readonly ResourceId[]; readonly deferred: readonly ResourceId[]; readonly budgetBytes: number; readonly estimatedBytes: number; }
export interface StreamStats { readonly nodes: number; readonly queued: number; readonly resident: number; readonly loading: number; readonly bytes: number; readonly evictions: number; readonly rejected: number; }

export class WorldStreamingDirector implements Disposable {
  readonly byteBudget: number; readonly concurrentLoads: number; readonly queueLimit: number;
  #nodes = new Map<ResourceId, StreamNode>(); #requests: StreamRequest[] = []; #active = new Set<ResourceId>(); #disposed = false; #evictions = 0; #rejected = 0;
  constructor(byteBudget = 256 * 1024 * 1024, concurrentLoads = 6, queueLimit = 512) { this.byteBudget = Math.max(4 * 1024 * 1024, Math.trunc(byteBudget)); this.concurrentLoads = clamp(integer(concurrentLoads), 1, 32); this.queueLimit = clamp(integer(queueLimit), 32, 4096); }
  register(node: Omit<StreamNode, 'id'> & { id: string }): boolean { if (this.#disposed || this.#nodes.has(node.id) || !node.id || node.bytes < 0) return false; this.#nodes.set(node.id as ResourceId, Object.freeze({ ...node, id: node.id as ResourceId, bytes: Math.trunc(node.bytes), priority: clamp(integer(node.priority), -1000, 1000), dependencies: Object.freeze([...new Set(node.dependencies)]) })); return true; }
  request(id: ResourceId, reason: StreamRequest['reason'], distance = 0, priorityBoost = 0): boolean { const node = this.#nodes.get(id); if (!node || this.#disposed || this.#active.has(id) || node.state === 'resident' || node.state === 'loading' || this.#requests.some((item) => item.id === id)) return false; if (this.#requests.length >= this.queueLimit) { this.#rejected += 1; return false; } const reasonScore = { visible: 400, nearby: 250, prefetch: 100, restore: 300, manual: 200 }[reason]; this.#requests.push(Object.freeze({ id, priority: node.priority + reasonScore + priorityBoost, distance: Math.max(0, distance), reason, requestedAt: this.#requests.length })); this.#nodes.set(id, Object.freeze({ ...node, state: 'queued' })); this.#sortQueue(); return true; }
  startNext(tick: number): ResourceId | null { if (this.#active.size >= this.concurrentLoads) return null; const request = this.#requests.shift(); if (!request) return null; const node = this.#nodes.get(request.id); if (!node) return null; if (node.dependencies.some((dependency) => this.#nodes.get(dependency)?.state !== 'resident')) { this.#requests.push(request); this.#sortQueue(); return null; } this.#active.add(request.id); this.#nodes.set(request.id, Object.freeze({ ...node, state: 'loading', lastUsedTick: integer(tick) })); return request.id; }
  complete(id: ResourceId, tick: number, success = true): boolean { const node = this.#nodes.get(id); if (!node || !this.#active.has(id)) return false; this.#active.delete(id); this.#nodes.set(id, Object.freeze({ ...node, state: success ? 'resident' : 'cold', lastUsedTick: integer(tick) })); return true; }
  touch(id: ResourceId, tick: number): boolean { const node = this.#nodes.get(id); if (!node || node.state !== 'resident') return false; this.#nodes.set(id, Object.freeze({ ...node, lastUsedTick: Math.max(node.lastUsedTick, integer(tick)) })); return true; }
  plan(targetBytes = this.byteBudget, reservedIds: readonly ResourceId[] = []): StreamPlan { const budget = clamp(targetBytes, 0, this.byteBudget); let estimated = 0; const loads: ResourceId[] = []; const deferred: ResourceId[] = []; for (const request of this.#orderedRequests()) { const node = this.#nodes.get(request.id); if (!node) continue; if (estimated + node.bytes <= budget && loads.length < this.concurrentLoads) { loads.push(node.id); estimated += node.bytes; } else deferred.push(node.id); } const reserved = new Set(reservedIds); let resident = this.residentBytes(); const evicts: ResourceId[] = []; const candidates = stableSort([...this.#nodes.values()].filter((node) => node.state === 'resident' && !node.required && !reserved.has(node.id)), (a, b) => a.lastUsedTick - b.lastUsedTick || a.priority - b.priority || String(a.id).localeCompare(String(b.id))); for (const node of candidates) { if (resident <= budget) break; resident -= node.bytes; evicts.push(node.id); } return Object.freeze({ loads: Object.freeze(loads), evicts: Object.freeze(evicts), deferred: Object.freeze(deferred), budgetBytes: budget, estimatedBytes: estimated }); }
  evict(id: ResourceId): boolean { const node = this.#nodes.get(id); if (!node || node.state !== 'resident' || node.required || this.#active.has(id)) return false; this.#nodes.set(id, Object.freeze({ ...node, state: 'evicted' })); this.#evictions += 1; return true; }
  residentBytes(): number { return [...this.#nodes.values()].filter((node) => node.state === 'resident').reduce((sum, node) => sum + node.bytes, 0); }
  records(): readonly StreamNode[] { return Object.freeze(stableSort([...this.#nodes.values()], (a, b) => String(a.id).localeCompare(String(b.id)))); }
  stats(): StreamStats { let queued = 0; let resident = 0; let loading = 0; for (const node of this.#nodes.values()) { queued += Number(node.state === 'queued'); resident += Number(node.state === 'resident'); loading += Number(node.state === 'loading'); } return Object.freeze({ nodes: this.#nodes.size, queued, resident, loading, bytes: this.residentBytes(), evictions: this.#evictions, rejected: this.#rejected }); }
  dispose(): void { this.#disposed = true; this.#nodes.clear(); this.#requests.length = 0; this.#active.clear(); }
  #orderedRequests(): readonly StreamRequest[] { return stableSort(this.#requests, (a, b) => b.priority - a.priority || a.distance - b.distance || a.requestedAt - b.requestedAt || String(a.id).localeCompare(String(b.id))); }
  #sortQueue(): void { this.#requests = [...this.#orderedRequests()]; }
}
