import { clamp, digest, integer, stableSort, type Disposable } from './primitives.js';

export type MetricKind = 'counter' | 'gauge' | 'histogram';
export interface MetricSample { readonly name: string; readonly kind: MetricKind; readonly value: number; readonly tick: number; readonly tags: Readonly<Record<string, string>>; }
export interface HistogramSummary { readonly count: number; readonly min: number; readonly max: number; readonly mean: number; readonly p50: number; readonly p95: number; readonly p99: number; }
export interface HealthReport { readonly score01: number; readonly frameP95: number; readonly errorRate01: number; readonly queuePressure01: number; readonly memoryPressure01: number; readonly networkPressure01: number; readonly warnings: readonly string[]; readonly blocking: readonly string[]; readonly digest: string; }
export interface SpanRecord { readonly name: string; readonly startMs: number; readonly endMs: number; readonly durationMs: number; readonly status: 'ok' | 'error'; readonly attributes: Readonly<Record<string, string | number | boolean>>; }
export interface TelemetryOptions { readonly sampleLimit?: number; readonly spanLimit?: number; readonly now?: () => number; }

function percentile(values: readonly number[], ratio: number): number { if (!values.length) return 0; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.min(sorted.length - 1, Math.max(0, Math.ceil(sorted.length * ratio) - 1))] ?? 0; }

export class RuntimeTelemetry implements Disposable {
  readonly sampleLimit: number; readonly spanLimit: number; #samples: MetricSample[] = []; #spans: SpanRecord[] = []; #counters = new Map<string, number>(); #gauges = new Map<string, number>(); #histograms = new Map<string, number[]>(); #now: () => number; #disposed = false;
  constructor(options: TelemetryOptions = {}) { this.sampleLimit = clamp(integer(options.sampleLimit ?? 4096), 64, 100_000); this.spanLimit = clamp(integer(options.spanLimit ?? 1024), 16, 20_000); this.#now = options.now ?? (() => typeof performance !== 'undefined' ? performance.now() : Date.now()); }
  counter(name: string, delta = 1, tags: Readonly<Record<string, string>> = {}): number { if (this.#disposed || !name) return 0; const value = (this.#counters.get(name) ?? 0) + delta; this.#counters.set(name, value); this.#record({ name, kind: 'counter', value, tick: 0, tags }); return value; }
  gauge(name: string, value: number, tags: Readonly<Record<string, string>> = {}): number { if (this.#disposed || !name) return 0; const next = Number.isFinite(value) ? value : 0; this.#gauges.set(name, next); this.#record({ name, kind: 'gauge', value: next, tick: 0, tags }); return next; }
  histogram(name: string, value: number, tags: Readonly<Record<string, string>> = {}): void { if (this.#disposed || !name || !Number.isFinite(value)) return; const values = this.#histograms.get(name) ?? []; values.push(value); if (values.length > this.sampleLimit) values.splice(0, values.length - this.sampleLimit); this.#histograms.set(name, values); this.#record({ name, kind: 'histogram', value, tick: 0, tags }); }
  observeFrame(frameMs: number, tick: number): void { this.histogram('frame.ms', Math.max(0, frameMs), { source: 'frame' }); this.gauge('runtime.tick', tick); }
  trace(name: string, startMs: number, endMs: number, status: SpanRecord['status'] = 'ok', attributes: Readonly<Record<string, string | number | boolean>> = {}): void { if (this.#disposed) return; const start = Number.isFinite(startMs) ? startMs : this.#now(); const end = Number.isFinite(endMs) ? endMs : this.#now(); this.#spans.push(Object.freeze({ name, startMs: start, endMs: end, durationMs: Math.max(0, end - start), status, attributes: Object.freeze({ ...attributes }) })); if (this.#spans.length > this.spanLimit) this.#spans.shift(); }
  time<T>(name: string, fn: () => T, attributes: Readonly<Record<string, string | number | boolean>> = {}): T { const start = this.#now(); try { const value = fn(); this.trace(name, start, this.#now(), 'ok', attributes); return value; } catch (error) { this.trace(name, start, this.#now(), 'error', { ...attributes, error: error instanceof Error ? error.message : String(error) }); throw error; } }
  histogramSummary(name: string): HistogramSummary { const values = this.#histograms.get(name) ?? []; const min = values.length ? Math.min(...values) : 0; const max = values.length ? Math.max(...values) : 0; const mean = values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; return Object.freeze({ count: values.length, min, max, mean, p50: percentile(values, .5), p95: percentile(values, .95), p99: percentile(values, .99) }); }
  health(budgets: { frameP95Ms?: number; errorRate01?: number; queuePressure01?: number; memoryPressure01?: number; networkPressure01?: number } = {}): HealthReport {
    const frame = this.histogramSummary('frame.ms'); const errorCount = this.#counters.get('runtime.errors') ?? 0; const operationCount = Math.max(1, this.#counters.get('runtime.operations') ?? 1); const errorRate = clamp(errorCount / operationCount, 0, 1); const queue = clamp(Number(this.#gauges.get('runtime.queuePressure01') ?? 0), 0, 1); const memory = clamp(Number(this.#gauges.get('runtime.memoryPressure01') ?? 0), 0, 1); const network = clamp(Number(this.#gauges.get('runtime.networkPressure01') ?? 0), 0, 1); const frameBudget = Math.max(1, budgets.frameP95Ms ?? 20); const framePressure = clamp(frame.p95 / frameBudget, 0, 2) / 2; const score = clamp(1 - (framePressure * .35 + errorRate * .25 + queue * .15 + memory * .15 + network * .10), 0, 1); const warnings = stableSort([frame.p95 > frameBudget ? 'frame-p95-high' : '', errorRate > (budgets.errorRate01 ?? .02) ? 'error-rate-high' : '', memory > (budgets.memoryPressure01 ?? .85) ? 'memory-pressure-high' : '', queue > (budgets.queuePressure01 ?? .85) ? 'queue-pressure-high' : ''].filter(Boolean), (a, b) => a.localeCompare(b)); const blocking = score < .35 ? ['runtime-health-low'] : []; return Object.freeze({ score01: score, frameP95: frame.p95, errorRate01: errorRate, queuePressure01: queue, memoryPressure01: memory, networkPressure01: network, warnings: Object.freeze(warnings), blocking: Object.freeze(blocking), digest: digest(score, frame, errorRate, queue, memory, network) });
  }
  samples(): readonly MetricSample[] { return Object.freeze([...this.#samples]); }
  spans(): readonly SpanRecord[] { return Object.freeze([...this.#spans]); }
  reset(): void { this.#samples.length = 0; this.#spans.length = 0; this.#counters.clear(); this.#gauges.clear(); this.#histograms.clear(); }
  dispose(): void { this.#disposed = true; this.reset(); }
  #record(sample: MetricSample): void { this.#samples.push(Object.freeze(sample)); if (this.#samples.length > this.sampleLimit) this.#samples.shift(); }
}
