/** Deterministic fauna habitat carrying-capacity balancer; owner delegates execution. */
import { normalizeEcologyContext, evaluateHabitat } from './livingWorldEcologyPolicy.js';
const f = Object.freeze, n = (v,d=0) => Number.isFinite(Number(v)) ? Number(v) : d, c = (v,a=0,b=1) => Math.max(a,Math.min(b,n(v,a))), s=(v,d='')=>v==null?d:String(v), id=(v,d='')=>s(v,d).trim()||d;
export const FAUNA_HABITAT_BALANCER_POLICY=f({id:'safak-kartali-fauna-habitat-balancer-2026-09-15-v1',deterministic:true,maxHabitats:64,maxSpecies:12,maxMovesPerTick:16,overloadThreshold:.78,criticalThreshold:.92,vacancyThreshold:.28,moveConfidenceFloor:.6,farMoveDistanceMeters:420,safeSettlementDistanceMeters:180});
const hash=v=>{let h=2166136261;for(const x of String(v)){h^=x.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}h^=h>>>16;h=Math.imul(h,2246822507)>>>0;h^=h>>>13;h=Math.imul(h,3266489909)>>>0;return(h^(h>>>16))>>>0};
const dg=v=>hash(JSON.stringify(v??null)).toString(16).padStart(8,'0');
const pos=v=>v&&Number.isFinite(Number(v.x))&&Number.isFinite(Number(v.z))?f({x:n(v.x),z:n(v.z),y:Number.isFinite(Number(v.y))?n(v.y):null}):null;
const dist=(a,b)=>a&&b?Math.hypot(n(a.x)-n(b.x),n(a.z)-n(b.z)):Infinity;
const hab=(r,i)=>{const ctx=normalizeEcologyContext({...r,biome:r?.canonicalBiome??r?.biome,distanceToSettlementMeters:r?.distanceToSettlementMeters??r?.settlementDistance,distanceToRoadMeters:r?.distanceToRoadMeters??r?.roadDistance});return f({id:id(r?.id,`habitat-${i}`),biome:s(ctx.biome,'grassland').toLowerCase(),position:pos(r?.position),groundValid:r?.groundValid!==false,navReachable:r?.navReachable!==false,food:c(r?.food),water:c(r?.water??ctx.waterAvailability),cover:c(r?.cover??ctx.cover),threat:c(r?.threat??ctx.threatLevel),settlementDistanceMeters:Math.max(0,n(ctx.distanceToSettlementMeters,9999)),context:ctx})};
const actor=(r,i)=>f({id:id(r?.id??r?.actorId,`fauna-${i}`),species:s(r?.species,'deer').toLowerCase(),habitatId:id(r?.habitatId),active:r?.active!==false});
const counts=as=>{const m=new Map();for(const a of as)if(a.active&&a.habitatId){const x=m.get(a.habitatId)||new Map();x.set(a.species,(x.get(a.species)||0)+1);m.set(a.habitatId,x)}return m};
const cap=(h,sp,p)=>{const e=evaluateHabitat(sp,{...h.context,biome:h.biome});if(!e.accepted)return 0;const rf=c(h.food*.52+h.water*.26+h.cover*.22,.05,1),tf=1-h.threat*.45,sf=h.settlementDistanceMeters<FAUNA_HABITAT_BALANCER_POLICY.safeSettlementDistanceMeters?.78:1,q=c(e.score??0);return Math.max(1,Math.floor(n(p?.maxGroupSize,12)*rf*tf*sf*(.55+q*.65)))};
const score=(h,sp,src=null)=>{const e=evaluateHabitat(sp,{...h.context,biome:h.biome});if(!h.groundValid||!h.navReachable||!e.accepted)return 0;let v=c(e.score??0);v=v*.72+(h.food+h.water+h.cover)/3*.28;if(src)v*=1-c(dist(src.position,h.position)/FAUNA_HABITAT_BALANCER_POLICY.farMoveDistanceMeters)*.18;if(h.threat>=FAUNA_HABITAT_BALANCER_POLICY.criticalThreshold)v*=.35;return c(v)};
export function planFaunaHabitatBalance(input={}){const seed=s(input.seed,'safak-kartali'),tick=Math.max(0,Math.floor(n(input.tick))),hs=(Array.isArray(input.habitats)?input.habitats:[]).slice(0,64).map(hab).sort((a,b)=>a.id.localeCompare(b.id)),as=(Array.isArray(input.actors)?input.actors:[]).slice(0,256).map(actor),sp=[...new Set((Array.isArray(input.species)&&input.species.length?input.species:['deer','wolf','horse','boar']).map(x=>s(x?.species??x).toLowerCase()).filter(Boolean))].sort().slice(0,12),hm=new Map(hs.map(h=>[h.id,h])),ct=counts(as),states=[],moves=[],diagnostics=[];for(const species of sp){const rows=hs.map(h=>{const count=ct.get(h.id)?.get(species)||0,capacity=cap(h,species,input.speciesProfiles?.[species]);const pressure=capacity?c(count/capacity*.72+(1-(h.food*.55+h.water*.45))*.2+h.threat*.08):1;return f({habitatId:h.id,species,count,capacity,pressure,vacancy:capacity?c((1-count/capacity)*.7+(h.food+h.water+h.cover)/3*.3):0,suitability:score(h,species),overloaded:pressure>=.78,critical:pressure>=.92})});states.push(...rows);for(const src of rows.filter(x=>x.overloaded).sort((a,b)=>b.pressure-a.pressure||a.habitatId.localeCompare(b.habitatId)).slice(0,8)){const sh=hm.get(src.habitatId),dest=rows.filter(x=>x.habitatId!==src.habitatId&&x.vacancy>=.28).map(x=>({...x,moveScore:x.suitability*.18+x.vacancy*.58})).sort((a,b)=>b.moveScore-a.moveScore||a.habitatId.localeCompare(b.habitatId))[0];if(!dest){diagnostics.push(f({species,habitatId:src.habitatId,status:'no-safe-destination'}));continue}const to=hm.get(dest.habitatId),d=dist(sh?.position,to?.position),risk=c((to?.threat??0)*.55+d/420*.3),conf=c(.55+dest.suitability*.32+dest.vacancy*.18-risk*.18);if(conf>=.6)moves.push(f({deterministicKey:`${seed}:${tick}:${species}:${src.habitatId}->${dest.habitatId}`,species,fromHabitatId:src.habitatId,toHabitatId:dest.habitatId,memberCount:Math.max(1,Math.min(1+Math.floor(src.pressure*3),Math.max(1,src.count-src.capacity))),distanceMeters:Number.isFinite(d)?Math.round(d*100)/100:null,confidence:Math.round(conf*1000)/1000,mode:d>420?'staged-relocation':'direct-relocation',reason:src.critical?'critical-overload':'overload-balance',executeViaOwner:true}))}}
const result=f({policy:FAUNA_HABITAT_BALANCER_POLICY.id,deterministic:true,seed,tick,species:sp,habitats:f(hs),states:f(states.sort((a,b)=>a.habitatId.localeCompare(b.habitatId)||a.species.localeCompare(b.species))),overloaded:f(states.filter(x=>x.overloaded)),critical:f(states.filter(x=>x.critical)),moves:f(moves.sort((a,b)=>a.deterministicKey.localeCompare(b.deterministicKey)).slice(0,16)),diagnostics:f(diagnostics),budget:f({habitats:hs.length,actors:as.length,states:states.length,moves:moves.length})});return f({...result,digest:dg(result)})}
export function faunaHabitatBalanceAcceptance(plan){const e=[];if(!plan||plan.deterministic!==true)e.push('non-deterministic-plan');if((plan?.moves||[]).length>16)e.push('move-budget-overflow');for(const m of plan?.moves||[]){if(m.memberCount<1)e.push(`zero-members:${m.deterministicKey}`);if(!m.executeViaOwner)e.push(`owner-bypass:${m.deterministicKey}`);if(m.confidence<.6)e.push(`low-confidence:${m.deterministicKey}`)}return f({ok:!e.length,errors:f(e),digest:dg(plan)})}
export const faunaHabitatBalanceDigest=input=>planFaunaHabitatBalance(input).digest;
export function createFaunaHabitatBalancer(defaults={}){let disposed=false;return{tick(input={}){if(disposed)return f({accepted:false,reason:'disposed'});const plan=planFaunaHabitatBalance({...defaults,...input});return f({accepted:true,plan,audit:faunaHabitatBalanceAcceptance(plan)})},read(){return f({disposed,policy:FAUNA_HABITAT_BALANCER_POLICY.id,deterministic:true})},dispose(){disposed=true}}}
