/** Şafak Kartalı — composition facade over existing living-world owners. */
import { createLivingWorldReactionIntegration, auditLivingWorldReactionIntegration, LIVING_WORLD_REACTION_INTEGRATION_POLICY } from './livingWorldReactionIntegrationAdapter.js';
import { normalizeThreatObservation, mergeThreatEvidence, ageThreatMemory, selectThreatTarget, summarizeThreatMemory, capThreatMemories, projectThreatForReaction, deterministicMemoryFingerprint, THREAT_MEMORY_POLICY } from './livingWorldThreatMemory.js';
import { normalizePopulationCollection, chooseFrameBudget, chooseSimulationSlice, rankSpawnCandidates, buildAmbientCandidates, ambientAdmission, summarizePopulation, clampSpawnBatch, clampAmbientBatch, auditPopulationBudget, deterministicPopulationFingerprint, POPULATION_BUDGET_POLICY } from './livingWorldPopulationBudget.js';
import { processCrimeBatch, normalizeWantedState, ageWantedScore, deterministicCrimeFingerprint, auditCrimeProjection, CRIME_REPUTATION_POLICY } from './livingWorldCrimeReputationPolicy.js';
import { inspectAssetMetadata, validateAssetSource, executePlacementContract, placementManifest, placementAudit, ASSET_PLACEMENT_POLICY } from './livingWorldAssetPlacementContract.js';
import { buildOccupationAffinity, choosePreferredSettlement, buildTravelDirective, roleNeedSummary, settlementPressure, auditSettlementAffinity, deterministicSettlementFingerprint } from './livingWorldSettlementAffinity.js';
import { createReplayLedger, canonicalFrame, fingerprint, buildReplaySeed, deterministicEventKey, sortEvents, summarizeLedger, auditReplay, buildDeterminismEvidence, REPLAY_POLICY } from './livingWorldReplay.js';
import { buildFaunaDirective, advanceFaunaNeeds, normalizeFaunaNeeds, threatPressure, deterministicFaunaFingerprint, auditFaunaNeeds, capFaunaAgents, FAUNA_NEEDS_POLICY } from './livingWorldFaunaNeedsPolicy.js';
import { buildFaunaGroupDirective } from './livingWorldFaunaNeedsPolicy.js';
import { buildGroupTacticalSnapshot, chooseTacticalIntent, buildFormationSlots, protectCivilianDecision, retreatDestination, combatReadiness, shouldBreakPursuit, auditTacticalSnapshot, deterministicGroupOrder, GROUP_TACTICS_POLICY } from './livingWorldGroupTacticsPolicy.js';
import { buildAmbientEvents, selectAmbientEvents, buildDistressEvent, buildMigrationEvent, buildStampedeEvent, auditAmbientEvents, deterministicAmbientFingerprint, AMBIENT_EVENT_POLICY } from './livingWorldAmbientEventPolicy.js';
import { validatePath, navigationIntent, buildFleePath, nearestSafePoint, evaluateStep, auditNavigation, deterministicNavigationFingerprint, NAVIGATION_SAFETY_POLICY } from './livingWorldNavigationSafetyPolicy.js';
import { admit as admitSpawn, rank as rankSpawnAdmission, buildSpawnIntent, habitatGate, auditSpawn, deterministicSpawnFingerprint, SPAWN_ADMISSION_POLICY } from './livingWorldSpawnAdmission.js';
import { buildRuntimeEvidence, auditRuntimeEvidence, deterministicPerformanceFingerprint, PERFORMANCE_EVIDENCE_POLICY } from './livingWorldPerformanceEvidence.js';

const freeze=Object.freeze;
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const str=(v,f='')=>v==null||v===''?f:String(v);
const arr=v=>Array.isArray(v)?v:[];
const MAX_ACTORS=Math.min(128,LIVING_WORLD_REACTION_INTEGRATION_POLICY.maxActors);

export const SAFAK_KARTALI_DIRECTOR_POLICY=freeze({
  id:'safak-kartali-living-world-director-2026-09-14-v5',deterministic:true,maxActors:MAX_ACTORS,maxDeltaSeconds:.25,
  maxMemoryActors:THREAT_MEMORY_POLICY.maxMemoriesPerActor,maxCrimeIncidents:CRIME_REPUTATION_POLICY.maxIncidentsPerTick,
  maxPlacementRequests:ASSET_PLACEMENT_POLICY.maxRequestsPerTick,replayFrames:REPLAY_POLICY.maxFrames,
  integrationPolicy:LIVING_WORLD_REACTION_INTEGRATION_POLICY.id,groupPolicy:GROUP_TACTICS_POLICY.id,faunaPolicy:FAUNA_NEEDS_POLICY.id,
  ambientPolicy:AMBIENT_EVENT_POLICY.id,navigationPolicy:NAVIGATION_SAFETY_POLICY.id,spawnPolicy:SPAWN_ADMISSION_POLICY.id,
  performancePolicy:PERFORMANCE_EVIDENCE_POLICY.id,sharedMaterial:ASSET_PLACEMENT_POLICY.sharedMaterialModule,
  sharedPlacement:ASSET_PLACEMENT_POLICY.sharedPlacementModule,ownsActorMembership:false,ownsCombatDamage:false,ownsFactionState:false,ownsSpawnLifecycle:false,
});

function actorId(actor,index=0){return str(actor?.id??actor?.actorId??actor?.object3D?.uuid,`actor-${index}`);}
function positionOf(value){const p=value?.object3D?.position??value?.position??value?.transform?.position;if(!p)return null;const x=num(p.x,NaN);const z=num(p.z,NaN);return Number.isFinite(x)&&Number.isFinite(z)?{x,z}:null;}
function flatten(collections={}){return ['npcs','animals','creatures','dragons'].flatMap(kind=>arr(collections[kind]).slice(0,MAX_ACTORS).map(actor=>({...actor,kind}))).slice(0,MAX_ACTORS);}
function worldContext(c={}){return {biome:str(c.biome,'temperate'),timeOfDay:num(c.timeOfDay,12),weather:str(c.weather,'clear'),season:str(c.season,'summer'),distanceToSettlementMeters:num(c.distanceToSettlementMeters,Infinity),insideSettlement:Boolean(c.insideSettlement),onRoad:Boolean(c.onRoad),habitatScore:num(c.habitatScore,1),requestedSpawn:num(c.requestedSpawn,4),requestedAmbient:num(c.requestedAmbient,6),populationCapacity:c.populationCapacity??{},populationDensity:num(c.populationDensity),danger:num(c.danger),weatherRisk:num(c.weatherRisk),mobile:Boolean(c.mobile),pwa:Boolean(c.pwa)};}
function placementCandidates(v){return arr(v).slice(0,ASSET_PLACEMENT_POLICY.maxRequestsPerTick).map((candidate,i)=>({...candidate,id:str(candidate?.id,`placement-${i}`),asset:candidate?.asset??candidate,context:candidate?.context??{},materialEvidence:candidate?.materialEvidence??{},paletteId:str(candidate?.paletteId)}));}
function groups(v){return arr(v).slice(0,GROUP_TACTICS_POLICY.maxGroups).map((group,i)=>({...group,id:str(group?.id,`group-${i}`),members:arr(group?.members).slice(0,GROUP_TACTICS_POLICY.maxMembers)}));}
function signalMap(v){const m=new Map();if(v instanceof Map)for(const [k,x] of v)m.set(String(k),arr(x));else if(v&&typeof v==='object')for(const [k,x] of Object.entries(v))m.set(String(k),arr(x));return m;}

export function createLivingWorldDirector(options={}){
  const seed=options.seed??0;
  const integration=createLivingWorldReactionIntegration({seed,clockSeconds:options.clockSeconds??0,services:options.services??{},directorOptions:options.directorOptions??{},lodThresholds:options.lodThresholds});
  const replaySeed=buildReplaySeed({worldSeed:seed,actorSeed:options.actorSeed??seed,eventSeed:options.eventSeed??seed});
  const replay=createReplayLedger(replaySeed), memories=new Map(), faunaNeeds=new Map(), wanted=new Map(), lastTick=new Map();
  let disposed=false,tickCount=0,clockSeconds=Math.max(0,num(options.clockSeconds)),lastSnapshot=null;

  function updateThreats(actors,signals,delta){
    const incoming=signalMap(signals),rows=[];
    for(let i=0;i<actors.length;i+=1){const actor=actors[i],id=actorId(actor,i),prior=memories.get(id)??[],current=[],touched=new Set();
      for(const raw of (incoming.get(id)??[]).slice(0,THREAT_MEMORY_POLICY.maxMemoriesPerActor)){const obs=normalizeThreatObservation({...raw,targetId:raw?.targetId??raw?.target?.id,nowSeconds:clockSeconds});if(!obs.targetId)continue;touched.add(obs.targetId);current.push(mergeThreatEvidence(prior.find(m=>m.targetId===obs.targetId),obs,clockSeconds));}
      for(const memory of prior)if(!touched.has(memory.targetId)){const aged=ageThreatMemory(memory,delta);if(aged.confidence||aged.suspicion)current.push(aged);}
      const bounded=capThreatMemories(current);memories.set(id,bounded);const top=selectThreatTarget(bounded,{position:positionOf(actor)});
      rows.push(freeze({actorId:id,memoryCount:bounded.length,topTargetId:top?.memory?.targetId??'',topScore:top?.score??0,summary:summarizeThreatMemory(bounded),fingerprint:deterministicMemoryFingerprint(bounded,seed)}));}
    return freeze(rows.sort((a,b)=>a.actorId.localeCompare(b.actorId)));
  }

  function updateFauna(actors,delta,context={}){
    const rows=[];
    for(const actor of capFaunaAgents(actors.filter(a=>['animal','creature','dragon'].includes(str(a.kind).toLowerCase())))){const id=actorId(actor),state=normalizeFaunaNeeds(faunaNeeds.get(id)??actor.needs??{energy:1}),threats=arr(context.faunaThreats?.[id]),pressure=threatPressure(threats,{position:actor.position,threatRadius:80}),next=advanceFaunaNeeds(state,delta,{predatorNearby:pressure.score>=.4,density:context.populationDensity,safe:pressure.score<.15,crowded:num(context.groupDensity)>1});
      faunaNeeds.set(id,next);rows.push(freeze({actorId:id,directive:buildFaunaDirective(actor,next,{species:actor.species,threats,position:actor.position,distanceToWaterMeters:context.distanceToWaterMeters?.[id],distanceToFoodMeters:context.distanceToFoodMeters?.[id],destination:context.faunaDestination?.[id],travelRequired:Boolean(context.faunaTravelRequired?.[id])}),groupDirective:actor.groupId?buildFaunaGroupDirective({id:actor.groupId,species:actor.species,memberIds:[id],population:1},{threats}):null,audit:auditFaunaNeeds(next),fingerprint:deterministicFaunaFingerprint(next,seed)}));}
    return freeze(rows.sort((a,b)=>a.actorId.localeCompare(b.actorId)));
  }

  function processCrime(incidents){const projection=processCrimeBatch(arr(incidents).slice(0,CRIME_REPUTATION_POLICY.maxIncidentsPerTick),{seed,wantedByActor:Object.fromEntries(wanted),witnessReputation:options.crimeContext?.witnessReputation??{},economyMultiplier:options.crimeContext?.economyMultiplier??1});for(const row of projection.rows){const id=row.incident.actorId,before=wanted.get(id)??normalizeWantedState();wanted.set(id,normalizeWantedState({wantedScore:row.projection.wantedAfter,bounty:before.bounty+row.projection.bountyDelta,lastCrimeSeconds:row.incident.timestamp,witnessCount:row.projection.witnessCount}));}return projection;}
  function decayCrime(delta){for(const [id,state] of wanted.entries()){const next=normalizeWantedState({...state,wantedScore:ageWantedScore(state.wantedScore,delta)});if(next.wantedScore<=0&&next.bounty<=0)wanted.delete(id);else wanted.set(id,next);}}

  function population(collections,player,context){const normalized=normalizePopulationCollection(collections),summary=summarizePopulation(normalized,player,{...context,lodThresholds:options.lodThresholds}),budget=chooseFrameBudget({actorCount:normalized.length,mobile:context.mobile||context.pwa,near:summary.counts.near,distant:summary.counts.distant,far:summary.counts.far,requestedSpawn:context.requestedSpawn,requestedAmbient:context.requestedAmbient}),slice=chooseSimulationSlice(normalized,{maxTicks:budget.nearTicks+budget.distantTicks+budget.farTicks,playerPosition:player,lodThresholds:options.lodThresholds},clockSeconds,lastTick);for(const row of slice.selected)lastTick.set(row.actor.id,clockSeconds);
    const spawn=rankSpawnCandidates(clampSpawnBatch(context.spawnCandidates??[],budget),normalized,{habitatScore:context.habitatScore,capacity:context.populationCapacity,blocked:context.spawnBlocked}),ambientPool=clampAmbientBatch(buildAmbientCandidates({biome:context.biome,timeOfDay:context.timeOfDay,weather:context.weather,settlementDistanceMeters:context.distanceToSettlementMeters,currentCount:normalized.length,species:context.ambientSpecies,seed}),budget),ambient=ambientPool.filter(c=>ambientAdmission(c,{density:c.density,distanceToSettlementMeters:context.distanceToSettlementMeters,insideSettlement:context.insideSettlement,onRoad:context.onRoad,waterTooDeep:context.waterTooDeep,slopeTooSteep:context.slopeTooSteep}).accepted).slice(0,budget.ambient);
    const spawnAdmission=rankSpawnAdmission(context.spawnCandidates??[],{kind:context.spawnKind??'animal',habitatScore:context.habitatScore,populationPressure:summary.pressure?.pressure?.[context.spawnKind??'animal']??0,distanceToPlayer:context.distanceToPlayer,currentCount:normalized.length,capacity:num(context.spawnCapacity,12),spawnBudget:budget.spawn,navReady:context.navReady!==false,slopeDegrees:context.slopeDegrees,insideSettlement:context.insideSettlement,onWater:context.onWater,waterDepth:context.waterDepth});
    return freeze({actorCount:normalized.length,summary,budget,slice:freeze({selected:slice.selected.length,skipped:slice.skipped.length}),spawn:freeze(spawn),spawnAdmission:freeze(spawnAdmission),ambient:freeze(ambient),pressure:summary.pressure,audit:auditPopulationBudget({actorCount:normalized.length,spawnCount:spawn.length,ambientCount:ambient.length})});}

  function groupsSnapshot(input,actors,context={}){const actorMap=new Map(actors.map((actor,i)=>[actorId(actor,i),actor])),rows=[];for(const group of groups(input)){const members=group.members.map(m=>typeof m==='string'?actorMap.get(m):m).filter(Boolean),tactical=buildGroupTacticalSnapshot({...group,members},{threats:arr(context.groupThreats?.[group.id]),civilianThreat:Boolean(context.civilianThreats?.[group.id]),rangedAdvantage:Boolean(context.rangedAdvantage?.[group.id])}),focus=chooseTacticalIntent({...group,members},{threats:arr(context.groupThreats?.[group.id])}),formation=buildFormationSlots({...group,members},group.origin??positionOf(members[0])??{x:0,z:0},num(group.headingRadians)),protection=context.civilianPositions?.[group.id]?protectCivilianDecision({...group,members},context.civilianPositions[group.id],arr(context.groupThreats?.[group.id])):null,retreat=retreatDestination({...group,members},arr(context.safePositions?.[group.id])),readiness=combatReadiness({...group,members});rows.push(freeze({...tactical,focusIntent:focus.intent,formation,protection,retreatDestination:retreat,readiness,breakPursuit:shouldBreakPursuit({...group,members},context.groupRuntime?.[group.id]??{}),audit:auditTacticalSnapshot(tactical)}));}return freeze({groups:freeze(rows),count:rows.length,order:deterministicGroupOrder(rows,seed),fingerprint:fingerprint(rows,seed)});}
  function ambientSnapshot(context={},types=[]){const selected=selectAmbientEvents({...context,populationDensity:num(context.populationDensity),danger:num(context.danger)},types,seed,context.lastIssued??{},clockSeconds),built=buildAmbientEvents(context,types,seed);return freeze({candidates:built,selected,migration:buildMigrationEvent({species:context.migrationSpecies??'deer',season:context.season,biome:context.biome,pressure:context.populationPressure,seed}),stampede:buildStampedeEvent({species:context.stampedeSpecies??'deer',groupCount:context.groupCount,predatorThreat:context.predatorThreat,noise:context.noise,seed}),distress:buildDistressEvent({actorId:context.distressActorId,targetId:context.distressTargetId,locationId:context.locationId,severity:context.distressSeverity,seed,tick:tickCount}),audit:auditAmbientEvents(selected),fingerprint:deterministicAmbientFingerprint(selected,seed)});}
  function navigationSnapshot(actors,context={}){const rows=actors.slice(0,NAVIGATION_SAFETY_POLICY.maxWaypoints).map((actor,i)=>{const id=actorId(actor,i),path=arr(context.paths?.[id]),validation=validatePath(path,actor),nav=navigationIntent(actor,context.navigationByActor?.[id]??{}),step=path.length?evaluateStep(path[0],actor):{ok:true,reasons:[]},flee=context.threatByActor?.[id]?buildFleePath(positionOf(actor),context.threatByActor[id],arr(context.safePositions)):null;return freeze({actorId:id,validation,intent:nav,firstStep:step,flee,nearestSafe:nearestSafePoint(arr(context.safePositions),arr(context.hazards)),audit:auditNavigation(validation)});});return freeze({rows,count:rows.length,fingerprint:deterministicNavigationFingerprint(rows,seed)});}
  function placementSnapshot(input){const audits=[],accepted=[];for(const candidate of placementCandidates(input)){const source=validateAssetSource(candidate.asset),meta=inspectAssetMetadata(candidate.asset);if(!source.ok){audits.push(freeze({id:candidate.id,accepted:false,stage:'source',family:meta.family,reasons:source.reasons}));continue;}const result=executePlacementContract({asset:candidate.asset,materialCore:options.materialCore,placementPipeline:options.placementPipeline,materialEvidence:candidate.materialEvidence,paletteId:candidate.paletteId,context:candidate.context});audits.push(freeze({id:candidate.id,accepted:result.ok===true,family:meta.family,...placementAudit(result)}));if(result.ok)accepted.push(freeze({id:candidate.id,result,manifest:placementManifest(result)}));}return freeze({requested:accepted.length,rejected:audits.filter(a=>!a.accepted).length,requests:freeze(accepted),audits:freeze(audits),contract:ASSET_PLACEMENT_POLICY.id});}
  function settlementSnapshot(actors,settlements,context){const rows=arr(actors).slice(0,24).map(actor=>{const affinity=buildOccupationAffinity(actor,settlements),preferred=choosePreferredSettlement(actor,settlements);return freeze({actorId:actorId(actor),affinity,preferred,travel:buildTravelDirective(actor,preferred)});});return freeze({rows:freeze(rows),needs:roleNeedSummary(context),pressure:settlementPressure(context),audit:auditSettlementAffinity(rows.flatMap(r=>r.affinity)),fingerprint:deterministicSettlementFingerprint(rows,seed)});}
  function events(input){return freeze(sortEvents(arr(input).map(event=>({...event,deterministicKey:deterministicEventKey(event,replaySeed)}))));}

  function tick(input={}){if(disposed)return freeze({accepted:false,reason:'disposed',tick:tickCount});const delta=Math.max(0,Math.min(SAFAK_KARTALI_DIRECTOR_POLICY.maxDeltaSeconds,num(input.deltaSeconds)));clockSeconds+=delta;const collections=input.collections??{},actors=flatten(collections),context=worldContext({...input.worldContext,mobile:input.mobile??input.worldContext?.mobile,pwa:input.pwa??input.worldContext?.pwa,spawnCandidates:input.spawnCandidates??input.worldContext?.spawnCandidates});
    const integrationResult=integration.tick({deltaSeconds:delta,collections,occupations:input.occupations,faunaRequests:input.faunaRequests,eventContext:input.eventContext??context,eventTypes:input.eventTypes,groups:input.groups,companions:input.companions,playerPosition:input.playerPosition,reactionOptions:input.reactionOptions});
    const memory=updateThreats(actors,input.perceptionSignals,delta),fauna=updateFauna(actors,delta,{...context,...input.faunaContext}),crime=processCrime(input.crimeIncidents);decayCrime(delta);
    const pop=population(collections,input.playerPosition,{...context,...(input.worldContext??{})}),groupState=groupsSnapshot(input.groups,actors,input.groupContext??{}),ambient=ambientSnapshot({...context,...(input.ambientContext??{})},input.eventTypes),navigation=navigationSnapshot(actors,input.navigationContext??{}),placement=placementSnapshot(input.placementCandidates),settlement=settlementSnapshot(actors,input.settlements,context),eventState=events([...(integrationResult?.reaction?.events??[]),...arr(input.worldEvents)]);
    const performance=buildRuntimeEvidence({population:pop,memory,tick:tickCount+1,fingerprints:true});tickCount+=1;
    const frame=canonicalFrame({tick:tickCount,timeSeconds:clockSeconds,director:{accepted:integrationResult.accepted!==false,policyId:SAFAK_KARTALI_DIRECTOR_POLICY.id},population:pop,threats:memory,crime,fauna,groups:groupState,ambient,navigation:navigation,events:eventState});const replayFrame=replay.append(frame);
    lastSnapshot=freeze({accepted:integrationResult.accepted!==false,tick:tickCount,clockSeconds,integration:integrationResult,memory,fauna,targets:freeze(memory.flatMap(row=>{const list=memories.get(row.actorId)??[],selected=list.length?selectThreatTarget(list)?.memory:null;return selected?[{actorId:row.actorId,target:projectThreatForReaction(selected)}]:[];})),crime,population:pop,groups:groupState,ambient,navigation,placement,settlement,wanted:freeze([...wanted.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([actorId,state])=>freeze({actorId,...state}))),events:eventState,performance,replay:freeze({frame:replayFrame,digest:replay.digest(),size:replay.size}),fingerprints:freeze({director:fingerprint(frame,seed),population:deterministicPopulationFingerprint(pop,seed),memory:deterministicMemoryFingerprint(memory,seed),fauna:deterministicFaunaFingerprint(fauna,seed),crime:deterministicCrimeFingerprint(crime,seed),ambient:deterministicAmbientFingerprint(ambient,seed),navigation:deterministicNavigationFingerprint(navigation,seed),performance:deterministicPerformanceFingerprint(performance,seed)}),policyId:SAFAK_KARTALI_DIRECTOR_POLICY.id});return lastSnapshot;}

  function audit(){const a=auditLivingWorldReactionIntegration(integration),p=auditPopulationBudget(lastSnapshot?.population??{actorCount:0,spawnCount:0,ambientCount:0}),c=auditCrimeProjection(lastSnapshot?.crime??{rows:[]}),r=auditReplay(replay.read()),perf=auditRuntimeEvidence(lastSnapshot?.performance??{}),ambient=auditAmbientEvents(lastSnapshot?.ambient?.selected??[]),placementErrors=arr(lastSnapshot?.placement?.audits).filter(x=>!x.accepted).map(x=>`placement:${x.id}`),faunaErrors=arr(lastSnapshot?.fauna).flatMap(x=>x.audit?.errors??[]),navErrors=arr(lastSnapshot?.navigation?.rows).flatMap(x=>x.audit?.errors??[]),errors=[...(a.errors??[]),...(p.errors??[]),...(c.errors??[]),...(r.errors??[]),...(perf.errors??[]),...(ambient.errors??[]),...placementErrors,...faunaErrors,...navErrors];return freeze({ok:a.ok&&p.ok&&c.ok&&r.ok&&perf.ok&&ambient.ok&&!errors.length,errors:freeze([...new Set(errors)]),tick:tickCount,replay:summarizeLedger(replay.read()),policyId:SAFAK_KARTALI_DIRECTOR_POLICY.id});}
  function snapshot(){return freeze(lastSnapshot??{accepted:true,tick:0,clockSeconds,policyId:SAFAK_KARTALI_DIRECTOR_POLICY.id});}
  function readThreats(id){return freeze((memories.get(String(id))??[]).map(projectThreatForReaction));}
  function readWanted(id){return freeze({...wanted.get(String(id)??'')??normalizeWantedState()});}
  function readFauna(id){return freeze({...faunaNeeds.get(String(id)??'')??normalizeFaunaNeeds()});}
  function compareReplay(left,right){return buildDeterminismEvidence(left,right);}
  function reset(){memories.clear();faunaNeeds.clear();wanted.clear();lastTick.clear();replay.clear();tickCount=0;clockSeconds=Math.max(0,num(options.clockSeconds));lastSnapshot=null;return integration.snapshot?.()??true;}
  function dispose(){disposed=true;integration.dispose();memories.clear();faunaNeeds.clear();wanted.clear();return true;}
  return freeze({tick,audit,snapshot,readThreats,readWanted,readFauna,compareReplay,reset,dispose,get replaySeed(){return replaySeed;},get disposed(){return disposed;},manifest:freeze({policy:SAFAK_KARTALI_DIRECTOR_POLICY.id,authority:['livingWorldReactionIntegrationAdapter','livingWorldReactionRuntime','livingWorldReactionPolicy','livingWorldDirectorRuntimeAdapter','livingWorldGroupDirectorAdapter','livingWorldOccupationSchedule','livingWorldEcologyPolicy','livingWorldEventDirectorAdapter'],sharedPlacement:[ASSET_PLACEMENT_POLICY.sharedMaterialModule,ASSET_PLACEMENT_POLICY.sharedPlacementModule],deterministic:true,replayFrames:REPLAY_POLICY.maxFrames,noDuplicateFramework:true})});
}

export function auditLivingWorldDirector(result){const errors=[];if(!result||result.accepted!==true)errors.push('not-accepted');if(result?.policyId!==SAFAK_KARTALI_DIRECTOR_POLICY.id&&result?.policyId!=null)errors.push('policy-id');if(result?.integration)errors.push(...(auditLivingWorldReactionIntegration(result.integration).errors??[]));if(result?.population)errors.push(...(auditPopulationBudget(result.population).errors??[]));if(result?.crime)errors.push(...(auditCrimeProjection(result.crime).errors??[]));if(result?.performance)errors.push(...(auditRuntimeEvidence(result.performance).errors??[]));return freeze({ok:!errors.length,errors:freeze([...new Set(errors)]),fingerprint:fingerprint(result,0)});}
