/**
 * Deterministic settlement/occupation affinity projection for the existing SettlementManager and
 * occupation schedule owners. This module only scores fit; it never chooses spawn locations or moves NPCs.
 */
const freeze = (v) => Object.freeze(v);
const n = (v, f = 0) => Number.isFinite(Number(v)) ? Number(v) : f;
const s = (v, f = '') => v == null || v === '' ? f : String(v);
const c = (v, a = 0, b = 1) => Math.max(a, Math.min(b, n(v, a)));
export const SETTLEMENT_AFFINITY_POLICY = freeze({ id: 'safak-kartali-settlement-affinity-2026-09-14-v1', deterministic: true, maxCandidates: 32, settlementBufferMeters: 200, roadTravelMetersPerHour: 5 });
const ROLES = freeze({ farmer: ['farm', 'field', 'market'], guard: ['gate', 'wall', 'watch'], merchant: ['market', 'road', 'inn'], smith: ['forge', 'market'], healer: ['clinic', 'temple'], hunter: ['forest', 'road', 'market'], fisher: ['water', 'market'], innkeeper: ['inn', 'market'], scholar: ['library', 'temple'], noble: ['hall', 'garden', 'market'] });
function hash(v) { let h = 2166136261; for (const ch of String(v)) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619) >>> 0; } return h >>> 0; }
export function normalizeSettlementContext(context = {}) { return freeze({ settlementId: s(context.settlementId), settlementType: s(context.settlementType, 'village'), biome: s(context.biome, 'temperate'), population: Math.max(0, n(context.population)), capacity: Math.max(1, n(context.capacity, 1)), market: c(context.market), waterAccess: c(context.waterAccess), farmland: c(context.farmland), security: c(context.security), roadAccess: c(context.roadAccess), services: Array.isArray(context.services) ? [...new Set(context.services.map(String))].sort() : [], distanceMeters: Math.max(0, n(context.distanceMeters, 0)), travelMinutes: Math.max(0, n(context.travelMinutes)) }); }
export function occupationFit(role, context = {}) { const r = s(role, 'citizen').toLowerCase(); const x = normalizeSettlementContext(context); const preferences = ROLES[r] ?? ['market']; let score = .35; for (const pref of preferences) { if (pref === 'market') score += x.market * .15; if (pref === 'farm') score += x.farmland * .15; if (pref === 'field') score += x.farmland * .1; if (pref === 'water') score += x.waterAccess * .14; if (pref === 'road') score += x.roadAccess * .1; if (pref === 'forest') score += (x.biome === 'forest' ? .18 : .04); if (pref === 'forge') score += x.security * .07; if (pref === 'gate' || pref === 'wall' || pref === 'watch') score += x.security * .18; if (pref === 'clinic' || pref === 'temple' || pref === 'library' || pref === 'inn' || pref === 'hall' || pref === 'garden') score += x.services.includes(pref) ? .12 : -.04; } return freeze({ role: r, score: c(score), accepted: score >= .45, preferences: freeze(preferences) }); }
export function scheduleTravelEstimate(distanceMeters, speedMetersPerMinute = 5) { return Math.max(0, n(distanceMeters) / Math.max(.1, n(speedMetersPerMinute, 5))); }
export function buildOccupationAffinity(actor, settlements = []) { const role = s(actor?.occupation ?? actor?.role, 'citizen'); const origin = actor?.position; const rows = (Array.isArray(settlements) ? settlements : []).slice(0, SETTLEMENT_AFFINITY_POLICY.maxCandidates).map((settlement, index) => { const context = normalizeSettlementContext(settlement); const position = settlement?.position; const distance = origin && position ? Math.hypot(n(origin.x) - n(position.x), n(origin.z) - n(position.z)) : context.distanceMeters; const fit = occupationFit(role, context); return freeze({ index, settlementId: context.settlementId || `settlement-${index}`, distanceMeters: distance, travelMinutes: scheduleTravelEstimate(distance), fit, score: c(fit.score - Math.min(.2, distance / SETTLEMENT_AFFINITY_POLICY.settlementBufferMeters * .2)) }); }).sort((a, b) => b.score - a.score || a.travelMinutes - b.travelMinutes || a.settlementId.localeCompare(b.settlementId)); return freeze(rows); }
export function choosePreferredSettlement(actor, settlements = []) { return buildOccupationAffinity(actor, settlements)[0] ?? null; }
export function buildTravelDirective(actor, preferred) { if (!preferred) return freeze({ accepted: false, reason: 'no-settlement' }); return freeze({ accepted: preferred.fit.accepted, actorId: s(actor?.id), settlementId: preferred.settlementId, destination: preferred.position ?? null, travelMinutes: preferred.travelMinutes, mode: preferred.travelMinutes > 30 ? 'road' : 'walk' }); }
export function settlementPressure(context = {}) { const x = normalizeSettlementContext(context); return freeze({ populationPressure: c(x.population / x.capacity, 0, 2), securityNeed: c(1 - x.security), marketNeed: c(1 - x.market), waterNeed: c(1 - x.waterAccess), farmlandNeed: c(1 - x.farmland), roadNeed: c(1 - x.roadAccess) }); }
export function roleNeedSummary(context = {}) { const p = settlementPressure(context); const needs = [ ['guard', p.securityNeed], ['merchant', p.marketNeed], ['farmer', p.farmlandNeed], ['fisher', p.waterNeed], ['hunter', p.roadNeed] ].sort((a, b) => b[1] - a[1]); return freeze(needs.map(([role, score]) => freeze({ role, score: c(score), priority: score >= .65 ? 'high' : score >= .35 ? 'medium' : 'low' }))); }
export function deterministicSettlementFingerprint(value, seed = 0) { return hash(`${seed}|${JSON.stringify(value ?? null)}`).toString(16).padStart(8, '0'); }
export function auditSettlementAffinity(rows) { const errors = []; for (const row of rows ?? []) { if (!row?.settlementId) errors.push('missing-settlement'); if (!Number.isFinite(row?.score)) errors.push('invalid-score'); if (row?.score < 0 || row?.score > 1) errors.push('score-range'); } return freeze({ ok: !errors.length, errors: freeze([...new Set(errors)]), fingerprint: deterministicSettlementFingerprint(rows) }); }
