/**
 * Şafak Kartalı — faction/diplomacy projection over the existing faction and diplomacy owners.
 */
const freeze=Object.freeze;
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,num(v,a)));
const str=(v,f='')=>v==null||v===''?f:String(v);
export const FACTION_DIPLOMACY_POLICY=freeze({id:'safak-kartali-faction-diplomacy-2026-09-14-v1',deterministic:true,maxFactions:32,maxRelations:256,hostileThreshold:-60,allyThreshold:45,warPressure:.7});
export const RELATION_STATES=freeze(['allied','friendly','neutral','suspicious','hostile','war']);
function hash(v){let h=2166136261;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;}
export function normalizeFaction(faction={},index=0){return freeze({id:str(faction.id,`faction-${index}`),name:str(faction.name),power:clamp(faction.power),stability:clamp(faction.stability),military:clamp(faction.military),economy:clamp(faction.economy),honor:clamp(faction.honor),aggression:clamp(faction.aggression),population:Math.max(0,Math.floor(num(faction.population))),isPlayer:Boolean(faction.isPlayer)});}
export function normalizeRelation(relation={}){return freeze({from:str(relation.from),to:str(relation.to),score:Math.max(-100,Math.min(100,num(relation.score))),state:str(relation.state,'neutral'),trade:num(relation.trade),borderTension:clamp(relation.borderTension),recentConflict:num(relation.recentConflict),trust:clamp(relation.trust,.0,1)});}
export function relationState(score,diplomacy='neutral',warPressure=0){const s=num(score);if(str(diplomacy).toLowerCase()==='war'||num(warPressure)>=FACTION_DIPLOMACY_POLICY.warPressure||s<=FACTION_DIPLOMACY_POLICY.hostileThreshold)return'hostile';if(str(diplomacy).toLowerCase()==='allied'&&s>=FACTION_DIPLOMACY_POLICY.allyThreshold)return'allied';if(s>=25)return'friendly';if(s<=-20)return'suspicious';return'neutral';}
export function updateRelationScore(relation={},event={}){const r=normalizeRelation(relation);const severity=clamp(event.severity);const type=str(event.type,'');let delta=0;if(type==='trade')delta=severity*5;if(type==='aid')delta=severity*10;if(type==='insult')delta=-severity*7;if(type==='crime')delta=-severity*12;if(type==='border-violation')delta=-severity*15;if(type==='war')delta=-severity*35;if(type==='peace')delta=severity*20;if(type==='marriage')delta=severity*8;return Math.max(-100,Math.min(100,r.score+delta));}
export function diplomacyIntent(relation={},context={}){const r=normalizeRelation(relation);const state=relationState(r.score,context.diplomacy,r.borderTension*.7+r.recentConflict*.3);if(state==='war'||state==='hostile')return'contain';if(state==='suspicious')return'negotiate';if(state==='allied')return'support';if(context.tradeOpportunity&&state==='friendly')return'trade';if(context.borderTension>.7)return'negotiate';return'observe';}
export function factionPriority(faction={},context={}){const f=normalizeFaction(faction);const danger=clamp(context.danger);return clamp(f.power*.2+f.military*.25+f.aggression*.2+danger*.2+(1-f.stability)*.15);}
export function buildFactionSnapshot(factions=[],relations=[],context={}){const fs=(Array.isArray(factions)?factions:[]).slice(0,FACTION_DIPLOMACY_POLICY.maxFactions).map(normalizeFaction);const rs=(Array.isArray(relations)?relations:[]).slice(0,FACTION_DIPLOMACY_POLICY.maxRelations).map(normalizeRelation).map(r=>freeze({...r,state:relationState(r.score,context.diplomacyByPair?.[`${r.from}:${r.to}`],r.borderTension),intent:diplomacyIntent(r,context)}));return freeze({factions:freeze(fs),relations:freeze(rs.sort((a,b)=>`${a.from}:${a.to}`.localeCompare(`${b.from}:${b.to}`))),priority:freeze(fs.map(f=>({id:f.id,priority:factionPriority(f,context)})).sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id)))});}
export function diplomacyPressure(relation={},context={}){const r=normalizeRelation(relation);return clamp(r.borderTension*.35+r.recentConflict*.4+(1-r.trust)*.25+num(context.patrolPressure)*.1);}
export function shouldEscalate(relation={},context={}){return diplomacyPressure(relation,context)>=.72||num(relation.score)<=-75;}
export function shouldOfferAid(relation={},faction={},context={}){const r=normalizeRelation(relation),f=normalizeFaction(faction);return relationState(r.score,context.diplomacy)>= 'friendly'&&f.stability<.45&&f.economy>.3;}
export function borderIncident(relation={},severity=.5){const r=normalizeRelation(relation);return freeze({from:r.from,to:r.to,severity:clamp(severity),scoreDelta:-clamp(severity)*15,escalates:clamp(severity)>.6});}
export function deterministicFactionFingerprint(value,seed=0){return hash(`${seed}|${JSON.stringify(value??null)}`).toString(16).padStart(8,'0');}
export function auditFactionSnapshot(snapshot){const errors=[];if((snapshot?.factions?.length??0)>FACTION_DIPLOMACY_POLICY.maxFactions)errors.push('faction-overflow');if((snapshot?.relations?.length??0)>FACTION_DIPLOMACY_POLICY.maxRelations)errors.push('relation-overflow');for(const relation of snapshot?.relations??[])if(!RELATION_STATES.includes(relation.state))errors.push('relation-state');return freeze({ok:!errors.length,errors:freeze([...new Set(errors)]),fingerprint:deterministicFactionFingerprint(snapshot)});}
export function relationMatrix(relations=[]){const matrix={};for(const relation of relations??[]){const r=normalizeRelation(relation);if(!matrix[r.from])matrix[r.from]={};matrix[r.from][r.to]=r.score;}return freeze(matrix);}
export function sortDiplomaticActions(actions=[]){return freeze((Array.isArray(actions)?actions:[]).map((action,index)=>({...action,index,priority:clamp(action.priority)})).sort((a,b)=>b.priority-a.priority||str(a.type).localeCompare(str(b.type))||a.index-b.index));}
export function buildDiplomaticEvent(relation={},event={},seed=0){const r=normalizeRelation(relation);const score=updateRelationScore(r,event);return freeze({type:'faction-relation-update',from:r.from,to:r.to,previousScore:r.score,nextScore:score,state:relationState(score),eventType:str(event.type),key:hash(`${seed}|${r.from}|${r.to}|${event.type}|${score}`).toString(16)});}
export function clampFactionList(factions=[]){return freeze((Array.isArray(factions)?factions:[]).slice(0,FACTION_DIPLOMACY_POLICY.maxFactions));}
