/** Şafak Kartalı — navigation safety projection; canonical navigation/terrain remains authoritative. */
const F=Object.freeze;const N=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;const S=(v,f='')=>v==null?f:String(v);const C=(v,a=0,b=1)=>Math.max(a,Math.min(b,N(v,a)));
export const NAVIGATION_SAFETY_POLICY=F({id:'safak-kartali-navigation-safety-2026-09-14-v1',deterministic:true,maxWaypoints:32,maxHazards:24,maxSlopeDegrees:38,minWaterClearanceMeters:2,settlementBufferMeters:3});
export function normalizeSurfaceSample(sample={}){return F({x:N(sample.x),z:N(sample.z),groundY:Number.isFinite(Number(sample.groundY))?Number(sample.groundY):null,slopeDegrees:Math.abs(N(sample.slopeDegrees)),waterDepth:Math.max(0,N(sample.waterDepth)),distanceToRoad:Number.isFinite(Number(sample.distanceToRoad))?Number(sample.distanceToRoad):null,distanceToSettlement:Number.isFinite(Number(sample.distanceToSettlement))?Number(sample.distanceToSettlement):null,insideSettlement:Boolean(sample.insideSettlement),walkable:sample.walkable!==false,navTagged:Boolean(sample.navTagged)});}
export function evaluateStep(sample={},actor={}){const s=normalizeSurfaceSample(sample);const kind=S(actor.kind,'npc');const reasons=[];if(!s.walkable)reasons.push('not-walkable');if(s.slopeDegrees>NAVIGATION_SAFETY_POLICY.maxSlopeDegrees&&(kind!=='goat'&&kind!=='dragon'))reasons.push('slope');if(s.waterDepth>0&&kind!=='bird'&&kind!=='dragon')reasons.push('water');if(kind==='npc'&&s.insideSettlement===false&&actor.requiresSettlement)reasons.push('settlement');return F({ok:!reasons.length,s,reasons:F(reasons)});}
export function validatePath(samples=[],actor={}){const rows=(Array.isArray(samples)?samples:[]).slice(0,NAVIGATION_SAFETY_POLICY.maxWaypoints).map((sample)=>evaluateStep(sample,actor));const blocked=rows.findIndex((row)=>!row.ok);return F({ok:blocked<0,blockedIndex:blocked,steps:rows.length,reasons:F(rows.filter(r=>!r.ok).flatMap(r=>r.reasons))});}
export function nearestSafePoint(points=[],hazards=[]){const safe=(Array.isArray(points)?points:[]).filter((point)=>!hazardAt(point,hazards));return safe[0]??null;}
function hazardAt(point,hazards){const p={x:N(point?.x),z:N(point?.z)};return (Array.isArray(hazards)?hazards:[]).some((hazard)=>{const r=Math.max(0,N(hazard?.radius,4));const h={x:N(hazard?.x),z:N(hazard?.z)};return Math.hypot(p.x-h.x,p.z-h.z)<=r;});}
export function buildFleePath(origin,threat,safePoints=[]){const o={x:N(origin?.x),z:N(origin?.z)};const t={x:N(threat?.x),z:N(threat?.z)};const away={x:o.x+(o.x-t.x),z:o.z+(o.z-t.z)};const selected=nearestSafePoint([...(safePoints??[]),away],[]);return F({origin:o,threat:t,destination:selected,mode:'flee'});}
export function roadPreference(actor={},surface={}){const kind=S(actor.kind,'npc');if(kind==='npc'||kind==='horse')return surface.distanceToRoad!=null&&surface.distanceToRoad<10?.9:.45;return .2;}
export function settlementSafety(actor={},surface={}){const kind=S(actor.kind,'npc');const distance=N(surface.distanceToSettlement,Infinity);if(kind==='npc')return Math.min(1,distance/Math.max(1,NAVIGATION_SAFETY_POLICY.settlementBufferMeters));if(['wolf','animal','creature'].includes(kind))return distance>=NAVIGATION_SAFETY_POLICY.settlementBufferMeters?1:0;return 1;}
export function navigationIntent(actor={},context={}){const safety=validatePath(context.pathSamples??[],actor);if(!safety.ok)return F({intent:'repath',reason:safety.reasons[0]??'blocked'});if(context.threatPosition)return F({intent:'chase',reason:'threat'});if(context.fleePosition)return F({intent:'flee',reason:'danger'});if(context.returnHome)return F({intent:'return',reason:'home'});return F({intent:'follow-schedule',reason:'occupation'});}
export function deterministicNavigationFingerprint(value,seed=0){let h=2166136261;for(const c of `${seed}|${JSON.stringify(value??null)}`){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h.toString(16).padStart(8,'0');}
export function auditNavigation(result){const errors=[];if(result?.steps>NAVIGATION_SAFETY_POLICY.maxWaypoints)errors.push('waypoint-overflow');if(result?.blockedIndex<-1)errors.push('blocked-index');return F({ok:!errors.length,errors:F(errors),fingerprint:deterministicNavigationFingerprint(result)});}
