/** Şafak Kartalı — lightweight performance evidence helpers; no rendering ownership. */
const F=Object.freeze;const N=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
export const PERFORMANCE_EVIDENCE_POLICY=F({id:'safak-kartali-performance-evidence-2026-09-14-v1',deterministic:true,maxSamples:120,maxBudgetMs:8});
export function percentile(values,p=50){const a=(Array.isArray(values)?values:[]).map(Number).filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const i=Math.max(0,Math.min(a.length-1,Math.ceil(p/100*a.length)-1));return a[i];}
export function summarizeFrameTimes(frameTimes=[]){return F({samples:Math.min(PERFORMANCE_EVIDENCE_POLICY.maxSamples,frameTimes.length),p50:percentile(frameTimes,50),p90:percentile(frameTimes,90),p95:percentile(frameTimes,95),max:Math.max(0,...(frameTimes.length?frameTimes:[0])),budgetMs:PERFORMANCE_EVIDENCE_POLICY.maxBudgetMs,withinBudget:percentile(frameTimes,95)<=PERFORMANCE_EVIDENCE_POLICY.maxBudgetMs});}
export function tickWorkEstimate({near=0,distant=0,far=0,sensing=0,spawn=0,ambient=0}={}){return N(near)*1+N(distant)*.45+N(far)*.2+N(sensing)*.35+N(spawn)*.6+N(ambient)*.15;}
export function budgetVerdict(estimate,budgetMs=8){const e=Math.max(0,N(estimate));const b=Math.max(.1,N(budgetMs,8));return F({estimate:e,budgetMs:b,ratio:e/b,ok:e<=b});}
export function buildRuntimeEvidence(snapshot={},frameTimes=[]){const frame=summarizeFrameTimes(frameTimes);const estimate=tickWorkEstimate({near:snapshot?.population?.summary?.counts?.near,distant:snapshot?.population?.summary?.counts?.distant,far:snapshot?.population?.summary?.counts?.far,sensing:snapshot?.memory?.length,spawn:snapshot?.population?.spawn?.length,ambient:snapshot?.population?.ambient?.length});return F({frame,work:budgetVerdict(estimate),actorCount:N(snapshot?.population?.actorCount),tick:N(snapshot?.tick),lod:snapshot?.population?.summary?.counts??{},deterministic:Boolean(snapshot?.fingerprints),pwaSafe:estimate<=12});}
export function auditRuntimeEvidence(evidence={}){const errors=[];if(evidence?.frame?.withinBudget===false)errors.push('frame-budget');if(evidence?.work?.ok===false)errors.push('tick-work-budget');if(N(evidence?.actorCount)>128)errors.push('actor-overflow');return F({ok:!errors.length,errors:F(errors)});}
export function deterministicPerformanceFingerprint(value,seed=0){let h=2166136261;for(const c of `${seed}|${JSON.stringify(value??null)}`){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h.toString(16).padStart(8,'0');}
export function capFrameSamples(samples=[]){return F((Array.isArray(samples)?samples:[]).slice(-PERFORMANCE_EVIDENCE_POLICY.maxSamples));}
