/** Ambient event planning adapter. WorldEventSystem remains authoritative for persistence/publish. */
const freeze=Object.freeze; const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f; const str=(v,f='')=>v==null?f:String(v);
export const AMBIENT_EVENT_POLICY=freeze({id:'safak-kartali-ambient-events-2026-09-14-v1',deterministic:true,maxCandidates:12,maxPerTick:3});
function hash(v){let h=2166136261;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;}
export function eligibleAmbientEvent(type,context={}){const t=str(type,'ambient');const h=num(context.timeOfDay,12);const d=num(context.danger);const p=num(context.populationDensity);if(t==='migration')return ['spring','autumn'].includes(str(context.season))&&p>.35;if(t==='stampede')return d>.5&&p>.3;if(t==='ambush')return d>.62&&['forest','marsh','mountain'].includes(str(context.biome));if(t==='festival')return d<.35&&p>.25&&h>17&&h<23;if(t==='storm')return num(context.weatherRisk)>.55;return false;}
export function eventScore(type,context={}){return eligibleAmbientEvent(type,context)?Math.max(0,Math.min(1,.9+num(context.eventBias)*.1-num(context.danger)*.25)):.0;}
export function buildAmbientEvent(type,context={},seed=0,index=0){return freeze({id:`ambient-${str(type)}-${hash(`${seed}|${type}|${index}`).toString(16)}`,type:str(type),eligible:eligibleAmbientEvent(type,context),score:eventScore(type,context),locationId:str(context.locationId),tick:num(context.tick),seed});}
export function buildAmbientEvents(context={},types=[],seed=0){const source=Array.isArray(types)&&types.length?types:['migration','stampede','ambush','festival','storm'];return freeze(source.map((t,i)=>buildAmbientEvent(t,context,seed,i)).filter(e=>e.eligible).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,AMBIENT_EVENT_POLICY.maxPerTick));}
export function cooldownAllows(type,lastIssued={},now=0,cooldown=60){return now-num(lastIssued?.[type],-Infinity)>=cooldown;}
export function selectAmbientEvents(context={},types=[],seed=0,lastIssued={},now=0){return freeze(buildAmbientEvents(context,types,seed).filter(e=>cooldownAllows(e.type,lastIssued,now,num(context.cooldowns?.[e.type],60))));}
export function buildDistressEvent({actorId,targetId='',locationId='',severity=.5,seed=0,tick=0}={}){return freeze({type:'distress',actorId:str(actorId),targetId:str(targetId),locationId:str(locationId),severity:Math.max(0,Math.min(1,num(severity))),key:hash(`${seed}|distress|${actorId}|${tick}`).toString(16)});}
export function buildMigrationEvent({species='deer',season='summer',biome='forest',pressure=.2,seed=0}={}){const eligible=['spring','autumn'].includes(season)&&pressure>.3;return freeze({type:'migration',species,season,biome,pressure,eligible,key:hash(`${seed}|migration|${species}|${season}|${biome}`).toString(16)});}
export function buildStampedeEvent({species='deer',groupCount=0,predatorThreat=0,noise=0,seed=0}={}){const score=Math.max(0,Math.min(1,num(groupCount)/8*.35+num(predatorThreat)*.45+num(noise)*.2));return freeze({type:'stampede',species,score,eligible:score>=.62,key:hash(`${seed}|stampede|${species}`).toString(16)});}
export function auditAmbientEvents(rows=[]){const errors=[];if(rows.length>AMBIENT_EVENT_POLICY.maxPerTick)errors.push('event-overflow');for(const row of rows){if(!row.id)errors.push('missing-id');if(row.score<0||row.score>1)errors.push('score-range');}return freeze({ok:!errors.length,errors:freeze([...new Set(errors)])});}
export function deterministicAmbientFingerprint(value,seed=0){return hash(`${seed}|${JSON.stringify(value??null)}`).toString(16).padStart(8,'0');}
