/** Şafak Kartalı — spawn admission projection over existing spawn owners. */
const F=Object.freeze;const N=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;const S=(v,f='')=>v==null?f:String(v);const C=(v,a=0,b=1)=>Math.max(a,Math.min(b,N(v,a)));
export const SPAWN_ADMISSION_POLICY=F({id:'safak-kartali-spawn-admission-2026-09-14-v1',deterministic:true,maxRequests:16,maxGroupSize:12});
export function habitatGate(context={}){const reasons=[];if(context.insideSettlement&&context.kind!=='npc'&&context.kind!=='horse')reasons.push('wildlife-settlement');if(context.onWater&&context.kind!=='bird'&&N(context.waterDepth)>2)reasons.push('deep-water');if(N(context.slopeDegrees)>38&&context.kind!=='goat'&&context.kind!=='dragon')reasons.push('slope');if(context.navReady===false)reasons.push('navigation');return F({ok:!reasons.length,reasons:F(reasons)});}
export function computeSpawnScore(candidate={},context={}){const habitat=C(context.habitatScore);const pressure=C(1-N(context.populationPressure));const player=Number.isFinite(Number(context.distanceToPlayer))?C(N(context.distanceToPlayer)/80):1;const quest=context.questRelevant?.25:0;const rare=context.rare?.2:0;return C(habitat*.45+pressure*.25+player*.1+quest+rare+N(candidate.priority)*.2);}
export function admit(candidate={},context={}){const gate=habitatGate({...context,kind:candidate.kind});const score=computeSpawnScore(candidate,context);const within=N(context.currentCount)<Math.max(1,N(context.capacity,1));return F({accepted:gate.ok&&within&&score>=.3,score,reason:!gate.ok?gate.reasons[0]??'habitat':!within?'capacity':score>=.3?'admitted':'low-score'});}
export function rank(candidates=[],context={}){return F((Array.isArray(candidates)?candidates:[]).slice(0,SPAWN_ADMISSION_POLICY.maxRequests).map((candidate,index)=>({candidate,index,decision:admit(candidate,context)})).sort((a,b)=>Number(b.decision.accepted)-Number(a.decision.accepted)||b.decision.score-a.decision.score||S(a.candidate.id,`${a.index}`).localeCompare(S(b.candidate.id,`${b.index}`))));}
export function batch(candidates=[],context={}){const cap=Math.max(0,Math.min(SPAWN_ADMISSION_POLICY.maxRequests,Math.floor(N(context.spawnBudget,SPAWN_ADMISSION_POLICY.maxRequests))));return F(rank(candidates,context).filter(r=>r.decision.accepted).slice(0,cap));}
export function groupSize(kind='animal',pressure=0){const base={npc:6,animal:6,creature:4,dragon:1}[kind]??3;return Math.max(1,Math.min(SPAWN_ADMISSION_POLICY.maxGroupSize,Math.floor(base*(1-C(pressure)*.5))));}
export function buildSpawnIntent(candidate,context={}){const decision=admit(candidate,context);return F({id:S(candidate.id),kind:S(candidate.kind,'animal'),species:S(candidate.species),accepted:decision.accepted,score:decision.score,reason:decision.reason,groupSize:groupSize(S(candidate.kind,'animal'),context.populationPressure),position:context.position??null});}
export function deterministicSpawnFingerprint(value,seed=0){let h=2166136261;for(const c of `${seed}|${JSON.stringify(value??null)}`){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h.toString(16).padStart(8,'0');}
export function auditSpawn(result){const errors=[];if((result?.length??0)>SPAWN_ADMISSION_POLICY.maxRequests)errors.push('request-overflow');for(const row of result??[])if(row?.decision?.score<0||row?.decision?.score>1)errors.push('score-range');return F({ok:!errors.length,errors:F([...new Set(errors)]),fingerprint:deterministicSpawnFingerprint(result)});}
