/** Companion bond/command projection. Existing companion integration owns lifecycle and persistence. */
const freeze=Object.freeze;
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const c=(v,a=0,b=1)=>Math.max(a,Math.min(b,n(v,a)));
const s=(v,f='')=>v==null||v===''?f:String(v);
export const COMPANION_POLICY=freeze({id:'safak-kartali-companion-2026-09-14-v1',deterministic:true,maxCompanions:12,loyaltyDangerThreshold:.42,moraleRestThreshold:.3,followDistanceMeters:8,holdDistanceMeters:18,assistDistanceMeters:24});
export const COMPANION_INTENTS=freeze(['follow','hold','assist','scout','flee','rest','regroup','dismiss']);
function h(v){let h=2166136261;for(const x of String(v)){h^=x.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;}
export function normalizeCompanion(x={},index=0){return freeze({id:s(x.id??x.actorId,`companion-${index}`),ownerId:s(x.ownerId??x.playerId),role:s(x.role,'companion'),loyalty:c(x.loyalty),morale:c(x.morale),health:c(n(x.health,100)/100),energy:c(x.energy),distanceMeters:Math.max(0,n(x.distanceMeters)),threatScore:c(x.threatScore),command:s(x.command,'follow'),bonded:x.bonded!==false,dismissed:Boolean(x.dismissed)});}
export function loyaltyPressure(companion,context={}){const x=normalizeCompanion(companion),danger=c(context.danger),separation=c(x.distanceMeters/40),health=1-x.health,morale=1-x.morale;return c(danger*.35+separation*.2+health*.2+morale*.25);}
export function commandPriority(companion,context={}){const x=normalizeCompanion(companion);return c(Math.max(x.threatScore,loyaltyPressure(x,context))*.7+(['assist','scout','hold'].includes(x.command)?.12:0)+(x.bonded?.08:-.1)+(1-x.energy)*.12);}
export function normalizeCommand(command){const x=s(command,'follow').toLowerCase();return COMPANION_INTENTS.includes(x)?x:'follow';}
export function chooseCompanionIntent(companion,context={}){const x=normalizeCompanion({...companion,command:normalizeCommand(companion?.command)}),p=loyaltyPressure(x,context);if(x.dismissed)return'dismiss';if(x.energy<=.2||x.morale<=COMPANION_POLICY.moraleRestThreshold)return'rest';if(p>=COMPANION_POLICY.loyaltyDangerThreshold&&x.health<.45)return'flee';if(x.command==='scout')return'scout';if(x.command==='assist'||x.threatScore>=.45)return'assist';if(x.command==='hold'||x.distanceMeters>COMPANION_POLICY.holdDistanceMeters)return'hold';if(context.regroupRequired)return'regroup';return'follow';}
export function buildCompanionDirective(companion,context={}){const x=normalizeCompanion(companion),intent=chooseCompanionIntent(x,context);return freeze({companionId:x.id,ownerId:x.ownerId,role:x.role,intent,loyalty:x.loyalty,morale:x.morale,health:x.health,energy:x.energy,distanceMeters:x.distanceMeters,threatScore:x.threatScore,priority:commandPriority(x,context),destination:context.destinations?.[x.id]??null});}
export function buildCompanionSnapshot(companions=[],context={}){const rows=(Array.isArray(companions)?companions:[]).slice(0,COMPANION_POLICY.maxCompanions).map((x,i)=>buildCompanionDirective(x,context)).sort((a,b)=>b.priority-a.priority||a.companionId.localeCompare(b.companionId));return freeze({companions:freeze(rows),count:rows.length,active:rows.filter(x=>x.intent!=='dismiss').length,priorityOrder:freeze(rows.map(x=>x.companionId))});}
export function assistTarget(companion,targets=[]){const x=normalizeCompanion(companion),rows=(Array.isArray(targets)?targets:[]).map((t,i)=>({t,i,distance:Math.max(0,n(t?.distanceMeters,Infinity)),threat:c(t?.threatScore)})).sort((a,b)=>b.threat-a.threat||a.distance-b.distance||a.i-b.i),selected=rows.find(r=>r.distance<=COMPANION_POLICY.assistDistanceMeters);return freeze({companionId:x.id,targetId:s(selected?.t?.id),accepted:Boolean(selected),reason:selected?'threat-proximity':'no-assist-target'});}
export function companionFormationSlot(companion,ownerPosition,index=0){const x=normalizeCompanion(companion),lateral=(index%3-1)*4,longitudinal=Math.floor(index/3)*4+COMPANION_POLICY.followDistanceMeters;return freeze({companionId:x.id,x:n(ownerPosition?.x)+lateral,z:n(ownerPosition?.z)+longitudinal});}
export function loyaltyAfterEvent(companion,event={}){const x=normalizeCompanion(companion),severity=c(event.severity),positive=['victory','rescue'].includes(event.type),negative=['betrayal','friendly-fire'].includes(event.type);return c(x.loyalty+(positive?severity*.12:negative?-severity*.2:-severity*.04));}
export function moraleAfterEvent(companion,event={}){const x=normalizeCompanion(companion),severity=c(event.severity),positive=['victory','rest','meal'].includes(event.type),negative=['defeat','panic','betrayal'].includes(event.type);return c(x.morale+(positive?severity*.14:negative?-severity*.18:0));}
export function shouldReturnToOwner(companion,context={}){const x=normalizeCompanion(companion);if(x.dismissed||context.ownerDown)return false;return x.distanceMeters>Math.max(COMPANION_POLICY.holdDistanceMeters,n(context.returnDistanceMeters,22));}
export function buildCompanionEvent(companion,event,context={}){const x=normalizeCompanion(companion);return freeze({companionId:x.id,ownerId:x.ownerId,eventType:s(event?.type,'unknown'),loyaltyBefore:x.loyalty,loyaltyAfter:loyaltyAfterEvent(x,event),moraleBefore:x.morale,moraleAfter:moraleAfterEvent(x,event),returnToOwner:shouldReturnToOwner(x,context)});}
export function deterministicCompanionFingerprint(value,seed=0){return h(`${seed}|${JSON.stringify(value??null)}`).toString(16).padStart(8,'0');}
export function auditCompanionSnapshot(snapshot){const errors=[];if(n(snapshot?.count)>COMPANION_POLICY.maxCompanions)errors.push('companion-overflow');for(const row of snapshot?.companions??[]){if(!COMPANION_INTENTS.includes(row.intent))errors.push('invalid-intent');if(row.loyalty<0||row.loyalty>1)errors.push('loyalty-range');if(row.morale<0||row.morale>1)errors.push('morale-range');}return freeze({ok:!errors.length,errors:freeze([...new Set(errors)]),fingerprint:deterministicCompanionFingerprint(snapshot)});}
export function stableCompanionOrder(companions=[],seed=0){return freeze((Array.isArray(companions)?companions:[]).slice(0,COMPANION_POLICY.maxCompanions).map((x,i)=>({id:normalizeCompanion(x,i).id,key:h(`${seed}|${x?.id??i}`)})).sort((a,b)=>a.key-b.key||a.id.localeCompare(b.id)).map(x=>x.id));}
