/** Contact/landing presentation policy for traversal. */
export const PLAYER_TRAVERSAL_CONTACT_PRESENTATION_VERSION='2026-09-15-v1';
const CONTACT_BANDS=Object.freeze({none:Object.freeze({min:0,max:1.19,weight:0,label:'none'}),soft:Object.freeze({min:1.2,max:4.49,weight:.55,label:'soft'}),hard:Object.freeze({min:4.5,max:9,weight:1,label:'hard'})});
function finite(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d;}function clamp01(v){return Math.max(0,Math.min(1,finite(v)));}function round(v,d=4){const f=10**d;return Math.round(finite(v)*f)/f;}function freeze(v){return Object.freeze(v);}
export function resolveTraversalContactBand(impact=0){const value=Math.max(0,Math.min(9,finite(impact)));if(value>=4.5)return CONTACT_BANDS.hard;if(value>=1.2)return CONTACT_BANDS.soft;return CONTACT_BANDS.none;}
export function resolveTraversalContactPresentation(presentation={}){const impact=Math.max(0,finite(presentation.metrics?.impact));const band=resolveTraversalContactBand(impact);const grounded=presentation.state==='land'||presentation.metrics?.footContactConfidence>0;const contact=clamp01(presentation.channels?.contact);return freeze({version:PLAYER_TRAVERSAL_CONTACT_PRESENTATION_VERSION,band:band.label,grounded,impact:round(impact),weight:round(Math.max(contact,band.weight)),softWeight:round(band.label==='soft'?band.weight:0),hardWeight:round(band.label==='hard'?band.weight:0),event:presentation.event??'none'});}
export function resolveTraversalContactAnimationEmphasis(contact={}){return freeze({squash:round(clamp01(contact.softWeight*.5+contact.hardWeight)),recoil:round(clamp01(contact.impact/1.2)),footPlant:round(clamp01(contact.weight))});}
export function resolveTraversalContactAudioEmphasis(contact={}){return freeze({intensity:round(clamp01(contact.impact/4.5)),oneShot:Boolean(contact.band!=='none'),materialHint:contact.band==='hard'?'heavy':contact.band==='soft'?'light':'none'});}
export function resolveTraversalContactVfxEmphasis(contact={}){return freeze({dust:round(clamp01(contact.softWeight*.75+contact.hardWeight)),ring:round(clamp01(contact.hardWeight*.65)),burst:contact.band==='hard'});}
export function compareTraversalContactOutputs(a,b){return JSON.stringify(a)===JSON.stringify(b);}
export function validateTraversalContactPresentation(contact={}){const errors=[];if(!['none','soft','hard'].includes(contact.band))errors.push('band');if(contact.weight<0||contact.weight>1)errors.push('weight');if(contact.impact<0||contact.impact>9)errors.push('impact');return freeze({valid:errors.length===0,errors:freeze(errors)});}
