/** Presentation-only foot contact phase resolver for locomotion anticipation. */
import { normalizePlayerDirectionalPhase } from './playerDirectionalLocomotionPolicy.js';

export const PLAYER_LOCOMOTION_FOOT_CONTACT_VERSION='2026-09-15-v1';
export const PLAYER_LOCOMOTION_FOOT_CONTACT_PHASES=Object.freeze(['left-contact','left-release','right-contact','right-release','airborne','recovery']);
export const PLAYER_LOCOMOTION_FOOT_CONTACT_LIMITS=Object.freeze({contactStart:0.08,releaseStart:0.42,secondContact:0.58,secondRelease:0.92,maxBlend:1});
function finite(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function round(value,digits=4){const f=10**digits;return Math.round(finite(value)*f)/f;}
function freeze(value){return Object.freeze(value);}

export function resolvePlayerLocomotionFootPhase(phase=0){const p=normalizePlayerDirectionalPhase(phase);if(p<0.08)return 'left-contact';if(p<0.42)return 'left-release';if(p<0.58)return 'right-contact';if(p<0.92)return 'right-release';return 'airborne';}
export function resolvePlayerLocomotionFootContactWeights(phase=0,{surfaceConfidence=1,surfaceSlip=0,grounded=true}={}){const p=normalizePlayerDirectionalPhase(phase);const confidence=clamp(finite(surfaceConfidence,1),0,1);const slip=clamp(finite(surfaceSlip),0,1);const ground=grounded===true?1:0;const leftContact=clamp((p<0.25?1-Math.abs(p-0.08)/0.17:0)*confidence*ground,0,1);const rightContact=clamp((p>=0.5&&p<0.75?1-Math.abs(p-0.58)/0.17:0)*confidence*ground,0,1);const total=leftContact+rightContact;const damping=clamp(1-slip*0.35,0.55,1);return freeze({left:round(leftContact*damping),right:round(rightContact*damping),heel:round(total*damping),toe:round(clamp((1-total)*0.7+damping*0.2,0,1)),confidence:round(confidence),slip:round(slip)});}
export function resolvePlayerLocomotionFootEventWindow(previousPhase=0,nextPhase=0){const previous=normalizePlayerDirectionalPhase(previousPhase);const next=normalizePlayerDirectionalPhase(nextPhase);const wrapped=next<previous;const crossings=[];if(wrapped){crossings.push({phase:'left-contact',foot:'left'});}if(!wrapped){if(previous<0.08&&next>=0.08)crossings.push({phase:'left-contact',foot:'left'});if(previous<0.58&&next>=0.58)crossings.push({phase:'right-contact',foot:'right'});}return freeze({wrapped,events:freeze(crossings.map(freeze)),emitted:crossings.length>0});}
export function resolvePlayerLocomotionFootCadence({speedMps=0,playbackRate=1,cadenceScale=1,surfaceSlip=0}={}){const speed=clamp(finite(speedMps),0,12);const rate=clamp(finite(playbackRate,1),0.72,1.35);const cadence=clamp(finite(cadenceScale,1),0.68,1.22);const slip=clamp(finite(surfaceSlip),0,1);return round(clamp((0.38+speed/12*0.62)*rate*cadence*(1-slip*0.12),0,1.5));}
export function resolvePlayerLocomotionFootContactConfidence({phase=0,surfaceConfidence=1,groundedConfidence=1,surfaceSlip=0}={}){const weights=resolvePlayerLocomotionFootContactWeights(phase,{surfaceConfidence, surfaceSlip});return round(clamp(weights.confidence*clamp(finite(groundedConfidence,1),0,1)*(1-clamp(finite(surfaceSlip),0,1)*0.24),0,1));}
export function resolvePlayerLocomotionFootContactPresentation({phase=0,speedMps=0,playbackRate=1,cadenceScale=1,surfaceConfidence=1,groundedConfidence=1,surfaceSlip=0}={}){const phaseName=resolvePlayerLocomotionFootPhase(phase);const weights=resolvePlayerLocomotionFootContactWeights(phase,{surfaceConfidence,surfaceSlip});const confidence=resolvePlayerLocomotionFootContactConfidence({phase,surfaceConfidence,groundedConfidence,surfaceSlip});return freeze({version:PLAYER_LOCOMOTION_FOOT_CONTACT_VERSION,phase:normalizePlayerDirectionalPhase(phase),phaseName,weights,cadence:resolvePlayerLocomotionFootCadence({speedMps,playbackRate,cadenceScale,surfaceSlip}),confidence,groundedConfidence:clamp(finite(groundedConfidence,1),0,1),airborne:phaseName==='airborne'});}
export function validatePlayerLocomotionFootContactPresentation(value={}){const phaseOk=Number.isFinite(value.phase)&&value.phase>=0&&value.phase<1;const phaseNameOk=PLAYER_LOCOMOTION_FOOT_CONTACT_PHASES.includes(value.phaseName)||value.phaseName==='airborne';const weights=value.weights??{};const weightOk=[weights.left,weights.right,weights.heel,weights.toe].every((v)=>Number.isFinite(v)&&v>=0&&v<=1);const confidenceOk=Number.isFinite(value.confidence)&&value.confidence>=0&&value.confidence<=1;return freeze({ok:phaseOk&&phaseNameOk&&weightOk&&confidenceOk,phaseOk,phaseNameOk,weightOk,confidenceOk});}
export function createPlayerLocomotionFootContactController(){let phase=0;let previousPhase=0;return freeze({update(nextPhase){previousPhase=phase;phase=normalizePlayerDirectionalPhase(nextPhase);return freeze({presentation:resolvePlayerLocomotionFootContactPresentation({phase}),events:resolvePlayerLocomotionFootEventWindow(previousPhase,phase)});},read(){return freeze({phase,previousPhase});},reset(){phase=0;previousPhase=0;}});}
export function auditPlayerLocomotionFootContact(){const presentation=resolvePlayerLocomotionFootContactPresentation({phase:0.1,speedMps:5,surfaceConfidence:0.9,groundedConfidence:0.95,surfaceSlip:0.1});return freeze({version:PLAYER_LOCOMOTION_FOOT_CONTACT_VERSION,valid:validatePlayerLocomotionFootContactPresentation(presentation).ok,immutable:Object.isFrozen(presentation),phases:PLAYER_LOCOMOTION_FOOT_CONTACT_PHASES.length});}
