/** Observation-only combat feedback projection for the shipped player combat runtime. */
// @ts-nocheck
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):min));
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const OUTCOMES=new Set(['none','hit','blocked','parried','guard-break','dodged','miss','staggered']);
const normalizeOutcome=v=>{const o=String(v??'none').trim().toLowerCase();return OUTCOMES.has(o)?o:'none';};
const cueFor=(o,r)=>o==='hit'?{vfx:r?'projectile-impact':'melee-spark',sfx:r?'impact-projectile':'impact-metal'}:o==='blocked'?{vfx:'guard-flash',sfx:'guard-block'}:o==='parried'?{vfx:'parry-ring',sfx:'parry'}:o==='guard-break'?{vfx:'guard-break-burst',sfx:'guard-break'}:o==='dodged'?{vfx:'dodge-trail',sfx:'dodge-whoosh'}:o==='staggered'?{vfx:'stagger-burst',sfx:'stagger'}:o==='miss'?{vfx:'none',sfx:'swing-air'}:{vfx:'none',sfx:'none'};
export function projectPlayerCombatFeedback(frame={}){const outcome=normalizeOutcome(frame?.outcome?.outcome);const ranged=Boolean(frame?.attack?.ranged||frame?.equipment?.ranged);const rawAmount=Math.max(0,finite(frame?.outcome?.rawAmount));const appliedAmount=Math.max(0,finite(frame?.outcome?.appliedAmount));const blockedAmount=Math.max(0,finite(frame?.outcome?.blockedAmount));const staminaRatio=clamp(frame?.movement?.staminaRatio,0,1);const poiseRatio=clamp(frame?.movement?.poiseRatio,0,1);const intensity=clamp(outcome==='none'?0:.35+Math.min(.4,appliedAmount/100)+Math.min(.25,blockedAmount/120),0,1);const cue=cueFor(outcome,ranged);return Object.freeze({version:1,outcome,phase:String(frame?.phase||'idle'),attackKind:String(frame?.attack?.kind||'none'),comboStep:clamp(frame?.attack?.comboStep,0,3),ranged,cue:Object.freeze(cue),intensity:Number(intensity.toFixed(4)),cameraKick:Number(clamp(intensity*(outcome==='guard-break'?.9:.45),0,1).toFixed(4)),rumble:Number(clamp(intensity*(outcome==='parried'?.7:.4),0,1).toFixed(4)),flashMs:Math.round(clamp(80+intensity*180,0,320)),staminaRatio:Number(staminaRatio.toFixed(4)),poiseRatio:Number(poiseRatio.toFixed(4)),appliedAmount:Number(appliedAmount.toFixed(4)),blockedAmount:Number(blockedAmount.toFixed(4)),rawAmount:Number(rawAmount.toFixed(4)),sourceRevision:Math.max(0,Math.floor(finite(frame?.revision))),sourceSignature:[frame?.revision??0,outcome,frame?.attack?.kind??'none',frame?.attack?.comboStep??0,appliedAmount,blockedAmount].join('|')});}
export function validatePlayerCombatFeedbackProjection(value){const errors=[];if(!value||typeof value!=='object')errors.push('missing-projection');if(!OUTCOMES.has(String(value?.outcome)))errors.push('invalid-outcome');if(!value?.cue||typeof value.cue.vfx!=='string'||typeof value.cue.sfx!=='string')errors.push('invalid-cue');if(value?.intensity<0||value?.intensity>1)errors.push('invalid-intensity');if(value?.cameraKick<0||value?.cameraKick>1)errors.push('invalid-camera-kick');if(value?.rumble<0||value?.rumble>1)errors.push('invalid-rumble');return Object.freeze({ok:errors.length===0,errors:Object.freeze(errors)});}
