/** Bounded, deterministic velocity history used to stabilize temporal locomotion anticipation. */
export const PLAYER_LOCOMOTION_VELOCITY_HISTORY_VERSION = '2026-09-15-v1';
export const PLAYER_LOCOMOTION_VELOCITY_HISTORY_LIMITS = Object.freeze({ maxSamples: 24, maxDeltaSeconds: 0.1, maxSpeedMps: 12, maxTurnRate: 540, smoothing: 0.32 });
function finite(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function round(value,digits=4){const f=10**digits;return Math.round(finite(value)*f)/f;}
function freeze(value){return Object.freeze(value);}
function normalizeVector(vector={}){const x=finite(vector.x),y=finite(vector.y);const magnitude=Math.hypot(x,y);if(magnitude<0.0001)return{x:0,y:0,magnitude:0};return{x:round(x/magnitude,5),y:round(y/magnitude,5),magnitude:round(magnitude,5)};}
function angle(vector){return Math.atan2(vector.x,vector.y);}
function angleDelta(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b));}

export function createPlayerLocomotionVelocityHistory(){return freeze({samples:freeze([]),lastSpeed:0,lastAngle:0,smoothedSpeed:0,smoothedAcceleration:0,smoothedTurnRate:0,frameCount:0});}
export function normalizePlayerLocomotionVelocitySample(sample={}){const velocity=normalizeVector(sample.velocity??{});return freeze({velocity,planarSpeedMps:clamp(Math.max(0,finite(sample.planarSpeedMps,velocity.magnitude)),0,12),deltaSeconds:clamp(Math.max(0,finite(sample.deltaSeconds,1/60)),0,0.1),surfaceConfidence:clamp(finite(sample.surfaceConfidence,1),0,1),surfaceSlip:clamp(finite(sample.surfaceSlip),0,1)});}
export function resolvePlayerLocomotionVelocityDerivative(previous,current){const prior=normalizePlayerLocomotionVelocitySample(previous??{});const next=normalizePlayerLocomotionVelocitySample(current??{});const dt=Math.max(next.deltaSeconds,0.001);const acceleration=(next.planarSpeedMps-prior.planarSpeedMps)/dt;const turnRate=Math.abs(angleDelta(angle(next.velocity),angle(prior.velocity)))*180/Math.PI/dt;return freeze({speedDeltaMps:round(next.planarSpeedMps-prior.planarSpeedMps,4),accelerationMps2:round(clamp(acceleration,-80,80),4),turnRateDegreesPerSecond:round(clamp(turnRate,0,540),3)});}
export function resolvePlayerLocomotionHistoryBlend(history=[]){const list=Array.isArray(history)?history:[];if(!list.length)return freeze({speed:0,acceleration:0,turnRate:0,confidence:0});const weights=list.map((_,i)=>Math.pow(1-PLAYER_LOCOMOTION_VELOCITY_HISTORY_LIMITS.smoothing,list.length-1-i));const total=weights.reduce((a,b)=>a+b,0);const weighted=(key)=>list.reduce((sum,sample,i)=>sum+finite(sample[key])*weights[i],0)/Math.max(total,0.0001);return freeze({speed:round(weighted('planarSpeedMps')),acceleration:round(weighted('accelerationMps2')),turnRate:round(weighted('turnRateDegreesPerSecond')),confidence:round(weighted('surfaceConfidence'))});}
export function pushPlayerLocomotionVelocityHistory(state=createPlayerLocomotionVelocityHistory(),sample={}){const prior=state??createPlayerLocomotionVelocityHistory();const normalized=normalizePlayerLocomotionVelocitySample(sample);const previous=prior.samples.at(-1);const derivative=previous?resolvePlayerLocomotionVelocityDerivative(previous,normalized):freeze({speedDeltaMps:0,accelerationMps2:0,turnRateDegreesPerSecond:0});const entry=freeze({...normalized,...derivative});const samples=[...(prior.samples??[]),entry].slice(-24);const blend=resolvePlayerLocomotionHistoryBlend(samples);return freeze({samples:freeze(samples),lastSpeed:normalized.planarSpeedMps,lastAngle:angle(normalized.velocity),smoothedSpeed:blend.speed,smoothedAcceleration:blend.acceleration,smoothedTurnRate:blend.turnRate,frameCount:prior.frameCount+1});}
export function resolvePlayerLocomotionHistoryPrediction(state=createPlayerLocomotionVelocityHistory(),lookAheadSeconds=0.15){const history=state??createPlayerLocomotionVelocityHistory();const horizon=clamp(finite(lookAheadSeconds,0.15),0.05,0.35);const speed=clamp(history.smoothedSpeed+history.smoothedAcceleration*horizon,0,12);const angleValue=history.lastAngle+(history.smoothedTurnRate*Math.PI/180)*horizon;return freeze({speedMps:round(speed),directionAngleRadians:round(angleValue,5),distanceMeters:round(speed*horizon,4),lookAheadSeconds:round(horizon),confidence:round(clamp(history.smoothedSpeed>0?history.smoothedSpeed/12:history.frameCount>0?0.25:0,0,1))});}
export function resolvePlayerLocomotionHistoryStability(state=createPlayerLocomotionVelocityHistory()){const history=state??createPlayerLocomotionVelocityHistory();const accelerationRisk=clamp(Math.abs(history.smoothedAcceleration)/40,0,1);const turnRisk=clamp(history.smoothedTurnRate/540,0,1);const countConfidence=clamp(history.frameCount/8,0,1);return freeze({score:round(clamp(1-accelerationRisk*0.45-turnRisk*0.35+(countConfidence-1)*0.2,0,1)),accelerationRisk:round(accelerationRisk),turnRisk:round(turnRisk),sampleConfidence:round(countConfidence)});}
export function validatePlayerLocomotionVelocityHistory(state={}){const samplesOk=Array.isArray(state.samples)&&state.samples.length<=24;const frameOk=Number.isInteger(state.frameCount)&&state.frameCount>=0;const finiteOk=[state.lastSpeed,state.lastAngle,state.smoothedSpeed,state.smoothedAcceleration,state.smoothedTurnRate].every(Number.isFinite);return freeze({ok:samplesOk&&frameOk&&finiteOk,samplesOk,frameOk,finiteOk});}
export function createPlayerLocomotionVelocityHistoryController(){let state=createPlayerLocomotionVelocityHistory();return freeze({update(sample){state=pushPlayerLocomotionVelocityHistory(state,sample);return freeze({state,prediction:resolvePlayerLocomotionHistoryPrediction(state),stability:resolvePlayerLocomotionHistoryStability(state)});},read(){return state;},reset(){state=createPlayerLocomotionVelocityHistory();}});}
export function auditPlayerLocomotionVelocityHistory(){const controller=createPlayerLocomotionVelocityHistoryController();controller.update({velocity:{x:0,y:1},planarSpeedMps:3,deltaSeconds:1/60});const state=controller.read();return freeze({version:PLAYER_LOCOMOTION_VELOCITY_HISTORY_VERSION,valid:validatePlayerLocomotionVelocityHistory(state).ok,historyLimit:24,immutable:Object.isFrozen(state)});}
