/** Deterministic derived metrics for evaluating temporal locomotion presentation quality. */
export const PLAYER_LOCOMOTION_ANTICIPATION_METRICS_VERSION='2026-09-15-v1';
function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function round(v,d=4){const f=10**d;return Math.round(finite(v)*f)/f;}
function freeze(v){return Object.freeze(v);}
export function resolvePlayerLocomotionAnticipationMetrics(profile={},previous=null){const speed=clamp(finite(profile.speedMps),0,12);const delta=finite(profile.speedDeltaMps);const accel=finite(profile.accelerationMps2);const turn=clamp(finite(profile.directionShiftDegrees),-180,180);const start=clamp(finite(profile.startWeight),0,1);const brake=clamp(finite(profile.brakeWeight),0,1);const pivot=clamp(finite(profile.pivotWeight),0,1);const confidence=clamp(finite(profile.confidence),0,1);const groundRisk=clamp(finite(profile.groundRisk),0,1);const previousSpeed=clamp(finite(previous?.speedMps),0,12);return freeze({speedMps:round(speed),speedChange:round(delta),acceleration:round(accel),directionShiftDegrees:round(turn),startIntent:round(start),brakeIntent:round(brake),pivotIntent:round(pivot),confidence:round(confidence),groundRisk:round(groundRisk),speedContinuity:round(clamp(1-Math.abs(speed-previousSpeed)/6,0,1)),intentSeparation:round(clamp(Math.abs(start-brake)+Math.abs(pivot-.5),0,1))});}
export function resolvePlayerLocomotionAnticipationQuality(metrics={}){const continuity=clamp(finite(metrics.speedContinuity),0,1);const confidence=clamp(finite(metrics.confidence),0,1);const risk=clamp(finite(metrics.groundRisk),0,1);const separation=clamp(finite(metrics.intentSeparation),0,1);const score=clamp(continuity*.32+confidence*.36+(1-risk)*.18+separation*.14,0,1);const grade=score>=.95?'A':score>=.85?'B':score>=.7?'C':score>=.5?'D':'E';return freeze({score:round(score),grade,continuity:round(continuity),confidence:round(confidence),risk:round(risk),separation:round(separation)});}
export function resolvePlayerLocomotionAnticipationRiskFlags(profile={}){const flags=[];if(finite(profile.confidence)<.35)flags.push('low-confidence');if(finite(profile.groundRisk)>.7)flags.push('high-ground-risk');if(Math.abs(finite(profile.accelerationMps2))>35)flags.push('high-acceleration');if(Math.abs(finite(profile.directionShiftDegrees))>150)flags.push('hard-redirect');if(finite(profile.brakeWeight)>.85&&finite(profile.startWeight)>.85)flags.push('competing-intents');return freeze(flags);}
export function resolvePlayerLocomotionAnticipationStabilityWindow(frames=[]){const list=Array.isArray(frames)?frames:[];if(list.length<2)return freeze({samples:list.length,stable:false,score:0});let continuity=0;let confidence=0;for(let i=1;i<list.length;i+=1){const a=list[i-1],b=list[i];continuity+=clamp(1-Math.abs(finite(a.speedMps)-finite(b.speedMps))/8,0,1);confidence+=clamp(finite(b.confidence),0,1);}const count=list.length-1;return freeze({samples:list.length,stable:continuity/count>=.72&&confidence/count>=.55,score:round((continuity/count*.55+confidence/count*.45))});}
export function summarizePlayerLocomotionAnticipationProfiles(profiles=[]){const list=Array.isArray(profiles)?profiles:[];const modes={};let totalConfidence=0;let totalRisk=0;let pivots=0;let brakes=0;for(const profile of list){modes[profile.mode]=(modes[profile.mode]??0)+1;totalConfidence+=clamp(finite(profile.confidence),0,1);totalRisk+=clamp(finite(profile.groundRisk),0,1);pivots+=profile.pivotWeight>.5?1:0;brakes+=profile.brakeWeight>.5?1:0;}const count=list.length;return freeze({count,modeHistogram:freeze(modes),meanConfidence:round(count?totalConfidence/count:0),meanGroundRisk:round(count?totalRisk/count:0),pivotRatio:round(count? pivots/count:0),brakeRatio:round(count?brakes/count:0)});}
export function comparePlayerLocomotionAnticipationMetricRuns(first=[],second=[]){const a=Array.isArray(first)?first:[];const b=Array.isArray(second)?second:[];const differences=[];for(let i=0;i<Math.max(a.length,b.length)&&differences.length<128;i+=1){if(JSON.stringify(a[i])!==JSON.stringify(b[i]))differences.push(i);}return freeze({equal:a.length===b.length&&differences.length===0,differences:freeze(differences),firstCount:a.length,secondCount:b.length});}
export function createPlayerLocomotionAnticipationMetricController(){let history=[];return freeze({update(profile,previous=null){const metrics=resolvePlayerLocomotionAnticipationMetrics(profile,previous);history=[...history,metrics].slice(-48);return freeze({metrics,quality:resolvePlayerLocomotionAnticipationQuality(metrics),riskFlags:resolvePlayerLocomotionAnticipationRiskFlags(profile),stability:resolvePlayerLocomotionAnticipationStabilityWindow(history)});},read(){return freeze(history);},reset(){history=[];}});}
export function auditPlayerLocomotionAnticipationMetrics(){const sample=resolvePlayerLocomotionAnticipationMetrics({speedMps:4,speedDeltaMps:.2,accelerationMps2:1,directionShiftDegrees:15,startWeight:.2,brakeWeight:.1,pivotWeight:.1,confidence:.9,groundRisk:.1},{speedMps:3.8});return freeze({version:PLAYER_LOCOMOTION_ANTICIPATION_METRICS_VERSION,score:resolvePlayerLocomotionAnticipationQuality(sample).score,immutable:Object.isFrozen(sample),finite:Object.values(sample).every(Number.isFinite)});}
