/**
 * Settlement campaign rules adapter.
 * Pure policy helpers over authoritative RPG snapshots; no mutable RPG owner.
 */
import { getSettlementItem, getSettlementRecipe, getSettlementRoute, getSettlementPerk, getSettlementQuestObjective, getSettlementDialogueCondition, resolveCraftingRecipe, resolveTradeQuote, resolveTravelCost } from './settlementCampaignContent.js';
export const SETTLEMENT_CAMPAIGN_RULES_VERSION = 1;
const number = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const integer = (value, min, max, fallback = min) => Math.max(min, Math.min(max, Math.trunc(number(value, fallback))));
const text = (value, fallback = '') => { const v = String(value ?? '').trim(); return v ? v.slice(0, 160) : fallback; };
const clone = value => value == null ? value : JSON.parse(JSON.stringify(value));
export function normalizeRpgSnapshot(raw = {}) {
  const s = raw && typeof raw === 'object' ? raw : {};
  const map = (value, limit, mapper) => Object.fromEntries(Object.entries(value && typeof value === 'object' ? value : {}).slice(0, limit).map(([k, v]) => [text(k), mapper(v)]));
  const quests = Object.fromEntries(Object.entries(s.quests ?? {}).slice(0, 64).map(([k, v]) => { const q = v && typeof v === 'object' ? v : {}; return [text(k), { state:text(q.state,'unknown'), step:integer(q.step,0,999,0), completed:Boolean(q.completed), rewardClaimed:Boolean(q.rewardClaimed) }]; }));
  return { copper:integer(s.copper,0,999999,0), fatigue:Math.max(0,Math.min(100,number(s.fatigue))), health:Math.max(0,Math.min(100,number(s.health,100))), maxHealth:Math.max(1,number(s.maxHealth,100)), carryWeight:Math.max(0,number(s.carryWeight)), maxCarryWeight:Math.max(1,number(s.maxCarryWeight,24)), reputation:integer(s.reputation,-9999,9999,0), locationId:text(s.locationId), settlementId:text(s.settlementId,'settlement'), inventory:map(s.inventory,96,v=>integer(v,0,9999,0)), equipment:map(s.equipment,24,v=>text(v)), quests, skills:map(s.skills,24,v=>integer(v,0,999,0)), flags:map(s.flags,64,v=>Boolean(v)), perks:Array.isArray(s.perks)?[...new Set(s.perks.map(text).filter(Boolean))].slice(0,24):[], survival:{ hunger:Math.max(0,Math.min(100,number(s.survival?.hunger))), exposure:Math.max(0,Math.min(100,number(s.survival?.exposure))), morale:Math.max(-100,Math.min(100,number(s.survival?.morale))) } };
}
export function evaluateFlagRule(flag,snapshot,expected=true){const s=normalizeRpgSnapshot(snapshot);const key=text(flag);return key&&s.flags[key]===expected?{ok:true,reason:''}:{ok:false,reason:'flag-required',key};}
export function evaluateReputationRule(minimum,snapshot){const s=normalizeRpgSnapshot(snapshot);const required=integer(minimum,-9999,9999,0);return s.reputation>=required?{ok:true,reason:'',current:s.reputation,required}:{ok:false,reason:'reputation-too-low',current:s.reputation,required};}
export function evaluateItemRule(itemId,quantity,snapshot){const s=normalizeRpgSnapshot(snapshot);const item=getSettlementItem(text(itemId));const required=integer(quantity,1,9999,1);if(!item)return{ok:false,reason:'unknown-item'};const current=s.inventory[item.id]||0;return current>=required?{ok:true,reason:'',current,required}:{ok:false,reason:'item-required',current,required};}
export function evaluateQuestRule(questId,states,snapshot){const s=normalizeRpgSnapshot(snapshot);const q=s.quests[text(questId)];const accepted=Array.isArray(states)&&states.length?states.map(text):['completed'];const pass=Boolean(q)&&(accepted.includes(q.state)||(accepted.includes('completed')&&q.completed));return pass?{ok:true,reason:'',questId:text(questId),state:q.state}:{ok:false,reason:'quest-required',questId:text(questId)};}
export function evaluateSkillRule(skillId,minimum,snapshot){const s=normalizeRpgSnapshot(snapshot);const required=integer(minimum,0,999,0);const current=s.skills[text(skillId)]||0;return current>=required?{ok:true,reason:'',current,required}:{ok:false,reason:'skill-required',current,required};}
export function evaluateCapabilityRule(capability,capabilities={}){const key=text(capability);return capabilities?.[key]===true?{ok:true,reason:''}:{ok:false,reason:'capability-unavailable',capability:key};}
export function evaluateProximityRule(distance,maximum=4){const actual=Math.max(0,number(distance,Infinity));const limit=Math.max(0,number(maximum,4));return actual<=limit?{ok:true,reason:'',distance:actual,maximum:limit}:{ok:false,reason:'too-far',distance:actual,maximum:limit};}
export function evaluateDialogueCondition(conditionId,snapshot){const c=getSettlementDialogueCondition(text(conditionId));if(!c)return{ok:false,reason:'unknown-condition'};if(c.type==='flag')return evaluateFlagRule(c.target,snapshot);if(c.type==='reputation')return evaluateReputationRule(c.threshold,snapshot);if(c.type==='item')return evaluateItemRule(c.target,c.threshold,snapshot);if(c.type==='skill')return evaluateSkillRule(c.target,c.threshold,snapshot);if(c.type==='quest')return evaluateQuestRule(c.target,['completed'],snapshot);return{ok:false,reason:'unsupported-condition'};}
export function evaluateDialogueConditions(conditionIds=[],snapshot={}){const checks=(Array.isArray(conditionIds)?conditionIds:[]).slice(0,8).map(id=>({id,...evaluateDialogueCondition(id,snapshot)}));return{ok:checks.every(v=>v.ok),checks};}
export function evaluateCraftingRule(recipeId,snapshot){const recipe=getSettlementRecipe(text(recipeId));if(!recipe)return{ok:false,reason:'unknown-recipe'};const check=resolveCraftingRecipe(recipe.id,normalizeRpgSnapshot(snapshot));return{ok:check.ok,reason:check.ok?'':check.reason,recipe:clone(recipe),missing:clone(check.missing??[]),station:recipe.station};}
export function evaluateTradeRule(itemId,quantity,direction,snapshot){const s=normalizeRpgSnapshot(snapshot);const item=getSettlementItem(text(itemId));if(!item)return{ok:false,reason:'unknown-item'};const quote=resolveTradeQuote(item.id,quantity,direction);if(!quote.ok)return quote;if(quote.direction==='buy'&&s.copper<quote.total)return{ok:false,reason:'insufficient-copper',quote};if(quote.direction==='sell'&&(s.inventory[item.id]||0)<quote.quantity)return{ok:false,reason:'insufficient-stock',quote};return{ok:true,reason:'',quote};}
export function evaluateTravelRule(routeId,snapshot,modifiers={}){const s=normalizeRpgSnapshot(snapshot);const route=getSettlementRoute(text(routeId));if(!route)return{ok:false,reason:'unknown-route'};const quote=resolveTravelCost(route.id,modifiers);if(!quote.ok)return quote;if(s.copper<quote.cost)return{ok:false,reason:'insufficient-copper',quote};if(s.fatigue+quote.fatigue>100)return{ok:false,reason:'fatigue-limit',quote,fatigue:s.fatigue};return{ok:true,reason:'',quote};}
export function evaluateEncumbrance(snapshot,incomingWeight=0,tolerance=0){const s=normalizeRpgSnapshot(snapshot);const projected=s.carryWeight+Math.max(0,number(incomingWeight));const allowed=s.maxCarryWeight+Math.max(0,number(tolerance));return projected<=allowed?{ok:true,projected,allowed}:{ok:false,reason:'over-encumbered',projected,allowed};}
export function evaluateSurvivalThresholds(snapshot,thresholds={}){const s=normalizeRpgSnapshot(snapshot);const checks=[['health',s.health,number(thresholds.health,0),'health-low'],['rested',100-s.fatigue,number(thresholds.minimumRested,0),'fatigue-high'],['fed',100-s.survival.hunger,number(thresholds.minimumFed,0),'hunger-high'],['protected',100-s.survival.exposure,number(thresholds.minimumProtected,0),'exposure-high'],['morale',s.survival.morale,number(thresholds.minimumMorale,-100),'morale-low']].map(([key,current,minimum,reason])=>({key,current,minimum,ok:current>=minimum,reason:current>=minimum?'':reason}));return{ok:checks.every(v=>v.ok),checks};}
export function evaluateEquipmentRule(itemId,slot,snapshot){const s=normalizeRpgSnapshot(snapshot);const item=getSettlementItem(text(itemId));if(!item)return{ok:false,reason:'unknown-item'};const target=text(slot,'weapon');const owned=(s.inventory[item.id]||0)>0;return owned||s.equipment[target]===item.id?{ok:true,reason:'',slot:target,itemId:item.id}:{ok:false,reason:'item-required',slot:target,itemId:item.id};}
export function evaluateRestRule(snapshot,serviceId='tavern'){const s=normalizeRpgSnapshot(snapshot);if(!['tavern','house','farm','stable'].includes(text(serviceId)))return{ok:false,reason:'rest-service-required'};return{ok:true,reason:'',serviceId:text(serviceId),recovery:s.perks.includes('steady_rest')?24:20};}
export function evaluatePerkUnlock(perkId,snapshot){const perk=getSettlementPerk(text(perkId));if(!perk)return{ok:false,reason:'unknown-perk'};const s=normalizeRpgSnapshot(snapshot);const skill=s.skills[perk.skill]||0;const required=Number(perk.effect.unlockTier)||0;return skill>=required?{ok:true,reason:'',perkId:perk.id,skill}:{ok:false,reason:'skill-required',perkId:perk.id,skill,required};}
export function evaluateObjectiveRule(objectiveId,snapshot){const objective=getSettlementQuestObjective(text(objectiveId));if(!objective)return{ok:false,reason:'unknown-objective'};const s=normalizeRpgSnapshot(snapshot);if(['collect','deliver','equip','craft'].includes(objective.type)){const progress=s.inventory[objective.target]||0;return progress>=objective.quantity?{ok:true,reason:'',progress:objective.quantity}:{ok:false,reason:'objective-incomplete',progress,required:objective.quantity};}if(objective.type==='travel'){const route=getSettlementRoute(objective.target);return s.locationId===route?.destination?{ok:true,reason:'',progress:1}:{ok:false,reason:'objective-incomplete',progress:0,required:1};}if(objective.type==='rest')return s.fatigue<=25?{ok:true,reason:'',progress:1}:{ok:false,reason:'objective-incomplete',progress:0,required:1};return{ok:false,reason:'objective-observer-required',progress:0};}
export function evaluateActionRule(action,context={}){const key=text(action);const s=normalizeRpgSnapshot(context.snapshot);if(key==='craft')return evaluateCraftingRule(context.recipeId,s);if(['buy','sell','trade'].includes(key))return evaluateTradeRule(context.itemId,context.quantity,context.direction??(key==='sell'?'sell':'buy'),s);if(key==='travel')return evaluateTravelRule(context.routeId,s,context.modifiers);if(key==='equip')return evaluateEquipmentRule(context.itemId,context.slot,s);if(key==='rest')return evaluateRestRule(s,context.serviceId);if(key==='talk')return evaluateDialogueConditions(context.conditions??[],s);if(['acceptQuest','advanceQuest'].includes(key))return context.questId?{ok:true,reason:'',questId:text(context.questId)}:{ok:false,reason:'quest-required'};return{ok:true,reason:''};}
export function summarizeRuleResult(result){const value=result&&typeof result==='object'?result:{};return{ok:value.ok===true,reason:text(value.reason),progress:Number.isFinite(Number(value.progress))?Number(value.progress):null,required:Number.isFinite(Number(value.required))?Number(value.required):null,quote:clone(value.quote)};}
''