/** Read-only accessibility projection for traversal cues. */
import { createSettlementWorldCoverageTraversalSignals } from './settlementWorldCoverageTraversalSignals.js';
import { createSettlementWorldCoverageTraversalPacing } from './settlementWorldCoverageTraversalPacing.js';
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_VERSION=1;
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_MODES=Object.freeze(['standard','high-contrast','low-motion','screen-reader','compact']);
const c=v=>Math.max(0,Math.min(1,Number.isFinite(Number(v))?Number(v):0));
const freeze=(v,s=new Set())=>{if(!v||typeof v!=='object'||s.has(v))return v;s.add(v);Object.freeze(v);for(const x of Object.values(v))freeze(x,s);return v;};
const stable=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(stable).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;
const digest=v=>{let h=2166136261,s=stable(v);for(let i=0;i<s.length;i+=1){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');};
function modeOptions(mode,signals,pacing){const selected=SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_MODES.includes(mode)?mode:'standard';const lowMotion=selected==='low-motion';const screen=selected==='screen-reader';const compact=selected==='compact';return{mode:selected,announceAll:screen,animate:!lowMotion,emphasizeType:selected==='high-contrast',maxVisibleSignals:compact?3:screen?12:6,repeatSeconds:lowMotion?8:compact?10:5,pace:pacing.state,primaryTypes:signals.primary.slice(0,screen?4:compact?2:3).map(x=>x.type)};}
export function createSettlementWorldCoverageTraversalAccessibility(options={},mode='standard'){const signals=createSettlementWorldCoverageTraversalSignals(options);const pacing=createSettlementWorldCoverageTraversalPacing(options);const ui=modeOptions(mode,signals,pacing);const payload={version:1,settlementId:signals.settlementId,stage:signals.stage,ui,signalCount:signals.signals.length,ownership:{readOnly:true,noUiMutation:true,noGameplayMutation:true}};return freeze({...payload,fingerprint:digest(payload)});}
export function validateSettlementWorldCoverageTraversalAccessibility(value){const s=value&&typeof value==='object'?value:{};const e=[];if(!s.settlementId)e.push('settlement-id');if(!SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_MODES.includes(s.ui?.mode))e.push('mode');if(s.ui?.maxVisibleSignals<1||s.ui?.maxVisibleSignals>12)e.push('signal-cap');if(!s.ownership?.readOnly||!s.ownership?.noUiMutation)e.push('ownership');return freeze({ok:e.length===0,errors:e,mode:s.ui?.mode??'standard',fingerprint:s.fingerprint??digest(s)});}
export function summarizeSettlementWorldCoverageTraversalAccessibility(options={},mode='standard'){const a=createSettlementWorldCoverageTraversalAccessibility(options,mode);return freeze({settlementId:a.settlementId,stage:a.stage,mode:a.ui.mode,animate:a.ui.animate,maxVisibleSignals:a.ui.maxVisibleSignals,pace:a.ui.pace,primaryTypes:a.ui.primaryTypes,fingerprint:a.fingerprint});}
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_API=Object.freeze({version:1,modes:[...SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_MODES],create:'createSettlementWorldCoverageTraversalAccessibility',validate:'validateSettlementWorldCoverageTraversalAccessibility',summary:'summarizeSettlementWorldCoverageTraversalAccessibility'});
