const S=new Set(['approach','inside','service','departure','resume']);
const A=new Set(['enter','talk','craft','repair','rest','trade','gather','train','travel','save','equip','collect','buy','sell','interact']);
const R=new Set(['ready','quest-complete','condition-blocked','stage-blocked','invalid-input']);
const id=v=>{const s=String(v??'').trim();return s?s.slice(0,96):''};
const ids=v=>[...new Set(Array.isArray(v)?v.map(id).filter(Boolean):[])].sort();
const freeze=v=>{if(!v||typeof v!=='object'||Object.isFrozen(v))return v;Object.freeze(v);for(const c of Object.values(v))freeze(c);return v};
const key=p=>{let h=2166136261;for(const c of p.join('|')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')};
export function createSettlementQuestResume(i={}){try{const settlementId=id(i.settlementId),chainId=id(i.chainId),stepId=id(i.stepId),serviceId=id(i.serviceId),stage=S.has(i.stage)?i.stage:null,action=A.has(i.action)?i.action:null,completedStepIds=ids(i.completedStepIds),requiredConditionIds=ids(i.requiredConditionIds),missingConditionIds=ids(i.missingConditionIds),completed=i.chainComplete===true||(chainId&&stepId===''),conditionReady=i.conditionsSatisfied!==false&&!missingConditionIds.length,stageReady=stage==='resume'||stage==='service'||stage==='inside',reason=!chainId||!settlementId||!serviceId||!action?'invalid-input':completed?'quest-complete':!conditionReady?'condition-blocked':!stageReady?'stage-blocked':'ready',v={settlementId,chainId,stepId,serviceId,stage,action,completedStepIds,requiredConditionIds,missingConditionIds,completed,conditionReady,stageReady,ready:reason==='ready',reason,completedCount:completedStepIds.length,progressRevision:Number.isFinite(Number(i.progressRevision))?Math.max(0,Math.min(999999,Math.trunc(Number(i.progressRevision)))):0};v.resumeKey=key([settlementId,chainId,stepId,serviceId,stage??'null',action??'null',completedStepIds.join(','),requiredConditionIds.join(','),missingConditionIds.join(','),String(completed),String(conditionReady),String(stageReady),reason,String(v.progressRevision)]);return freeze(v)}catch{return freeze({settlementId:'',chainId:'',stepId:'',serviceId:'',stage:null,action:null,completedStepIds:[],requiredConditionIds:[],missingConditionIds:[],completed:false,conditionReady:false,stageReady:false,ready:false,reason:'invalid-input',completedCount:0,progressRevision:0,resumeKey:'00000000'})}}
export function isSettlementQuestResume(v){try{if(!v||typeof v!=='object'||!Object.isFrozen(v))return false;if(![v.settlementId,v.chainId,v.stepId,v.serviceId].every(x=>typeof x==='string'))return false;if(v.stage!==null&&!S.has(v.stage)||v.action!==null&&!A.has(v.action))return false;if(!Array.isArray(v.completedStepIds)||!Array.isArray(v.requiredConditionIds)||!Array.isArray(v.missingConditionIds))return false;for(const list of [v.completedStepIds,v.requiredConditionIds,v.missingConditionIds])if(list.some((x,n,a)=>typeof x!=='string'||n>0&&a[n-1]>=x))return false;if(!R.has(v.reason)||typeof v.resumeKey!=='string')return false;if(typeof v.completed!=='boolean'||typeof v.conditionReady!=='boolean'||typeof v.stageReady!=='boolean'||typeof v.ready!=='boolean')return false;if(v.ready!==(v.reason==='ready')||v.completed!==(v.reason==='quest-complete'))return false;const e=createSettlementQuestResume(v);return e.resumeKey===v.resumeKey&&e.reason===v.reason}catch{return false}}
