/**
 * Settlement survival adapter.
 * Computes rest/travel/resource outcomes without mutating authoritative state.
 */
import { getSettlementRoute } from './settlementCampaignContent.js';
export const SETTLEMENT_SURVIVAL_VERSION=1;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
const int=(value,min=0,max=9999)=>Math.max(min,Math.min(max,Math.trunc(Number(value)||0)));
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,160):fallback;};
export function normalizeSurvivalSnapshot(raw={}){const s=raw&&typeof raw==='object'?raw:{};return{health:clamp(s.health,0,100),maxHealth:Math.max(1,clamp(s.maxHealth,1,999)),fatigue:clamp(s.fatigue,0,100),hunger:clamp(s.survival?.hunger,0,100),exposure:clamp(s.survival?.exposure,0,100),morale:clamp(s.survival?.morale,-100,100),copper:int(s.copper),inventory:Object.fromEntries(Object.entries(s.inventory&&typeof s.inventory==='object'?s.inventory:{}).slice(0,96).map(([id,v])=>[text(id),int(v)])),perks:Array.isArray(s.perks)?[...new Set(s.perks.map(text).filter(Boolean))].slice(0,24):[]};}
export function calculateRestOutcome(snapshot={},serviceId='tavern'){const s=normalizeSurvivalSnapshot(snapshot);const service=text(serviceId);if(!['tavern','house','farm','stable'].includes(service))return{ok:false,reason:'rest-service-required'};const base=service==='house'?28:service==='tavern'?24:20;const bonus=s.perks.includes('steady_rest')?6:0;const morale=s.perks.includes('night_rest')?4:0;const fatigue=clamp(s.fatigue-base-bonus,0,100);return{ok:true,serviceId:service,fatigueBefore:s.fatigue,fatigueAfter:fatigue,recovery:s.fatigue-fatigue,moraleBefore:s.morale,moraleAfter:clamp(s.morale+morale,-100,100)};}
export function calculateFoodNeed(snapshot={},days=1){const s=normalizeSurvivalSnapshot(snapshot);const span=Math.max(1,Math.min(14,int(days,1,14)));return{days:span,requiredRations:Math.max(1,span-(s.perks.includes('field_cook')?1:0)),reserveCapacity:4+(s.perks.includes('quartermaster')?2:0)};}
export function calculateTravelSurvival(snapshot={},routeId,quote={}){const s=normalizeSurvivalSnapshot(snapshot);const route=getSettlementRoute(text(routeId));if(!route)return{ok:false,reason:'unknown-route'};const fatigue=Math.max(0,Number(quote.fatigue)||route.fatigue);const hungerGain=Math.max(1,Math.ceil(fatigue/8));const exposureGain=route.risk==='high'?12:route.risk==='medium'?8:4;const moraleLoss=route.risk==='high'?8:route.risk==='medium'?4:1;const food=s.inventory.travel_rations||0;const rationUsed=Math.min(food,Math.max(1,Math.ceil(hungerGain/2)));return{ok:true,routeId:route.id,fatigueBefore:s.fatigue,fatigueAfter:clamp(s.fatigue+fatigue,0,100),hungerBefore:s.hunger,hungerAfter:clamp(s.hunger+hungerGain-rationUsed*4,0,100),exposureBefore:s.exposure,exposureAfter:clamp(s.exposure+exposureGain,0,100),moraleBefore:s.morale,moraleAfter:clamp(s.morale-moraleLoss,-100,100),rationUsed,survivalRisk:route.risk};}
export function calculateExposureMitigation(snapshot={},context={}){const s=normalizeSurvivalSnapshot(snapshot);let mitigation=0;if(s.perks.includes('roadwise'))mitigation+=2;if(s.perks.includes('watchful'))mitigation+=3;if(context.shelter===true)mitigation+=8;if(context.fire===true)mitigation+=4;return{exposureMitigation:mitigation,effectiveExposure:clamp(s.exposure-mitigation,0,100)};}
export function calculateHungerMitigation(snapshot={},context={}){const s=normalizeSurvivalSnapshot(snapshot);let mitigation=0;if(s.perks.includes('field_cook'))mitigation+=4;if(context.meal===true)mitigation+=8;if(context.ration===true)mitigation+=6;return{hungerMitigation:mitigation,effectiveHunger:clamp(s.hunger-mitigation,0,100)};}
export function buildSurvivalReport(snapshot={},context={}){const s=normalizeSurvivalSnapshot(snapshot);const exposure=calculateExposureMitigation(s,context);const hunger=calculateHungerMitigation(s,context);const rest=calculateRestOutcome(s,context.restService||'tavern');const danger=[['health',s.health<25],['fatigue',s.fatigue>75],['hunger',hunger.effectiveHunger>75],['exposure',exposure.effectiveExposure>75],['morale',s.morale<-50]].filter(v=>v[1]).map(v=>v[0]);return{version:1,healthy:danger.length===0,danger,rest,exposure,hunger,recommendedAction:danger.includes('fatigue')||danger.includes('health')?'rest':danger.includes('hunger')?'eat':danger.includes('exposure')?'seek-shelter':'continue'};}
export function buildTravelSurvivalEnvelope(snapshot,routeId,quote={},context={}){return{version:1,routeId:text(routeId),travel:calculateTravelSurvival(snapshot,routeId,quote),food:calculateFoodNeed(snapshot,context.days??1),report:buildSurvivalReport(snapshot,context),authoritativeCommitRequired:true};}
export function validateSurvivalEnvelope(envelope){const errors=[];if(envelope?.version!==1)errors.push('version');if(!text(envelope?.routeId))errors.push('route');if(!envelope?.travel||envelope.travel.ok!==true)errors.push('travel');return{ok:errors.length===0,errors};}
