/**
 * Settlement progression adapter. Pure XP/skill/perk calculations.
 */
import { getSettlementPerk } from './settlementCampaignContent.js';
export const SETTLEMENT_PROGRESSION_VERSION = 1;
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,160):fallback;};
const number=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const integer=(value,min,max,fallback=min)=>Math.max(min,Math.min(max,Math.trunc(number(value,fallback))));
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
export const SETTLEMENT_SKILLS=Object.freeze(['smithing','commerce','travel','survival','dialogue','logistics','questing','persistence']);
export const SETTLEMENT_XP_CURVE=Object.freeze([0,100,240,420,640,900,1200,1540,1920,2340,2800,3300,3850,4450,5100,5800,6550,7350,8200,9100,10050]);
const BASE_AWARDS=Object.freeze({craft:40,trade:12,talk:15,acceptQuest:18,advanceQuest:28,travel:22,rest:8,train:32,save:2});
export function listSettlementSkills(){return[...SETTLEMENT_SKILLS];}
export function getSettlementSkillLevel(skillId,snapshot={}){return integer(snapshot?.skills?.[text(skillId)],0,999,0);}
export function getSettlementXpForLevel(level){return SETTLEMENT_XP_CURVE[integer(level,0,SETTLEMENT_XP_CURVE.length-1,0)];}
export function getSettlementXpToNextLevel(level,totalXp){const current=integer(level,0,SETTLEMENT_XP_CURVE.length-1,0);if(current>=SETTLEMENT_XP_CURVE.length-1)return 0;return Math.max(0,getSettlementXpForLevel(current+1)-integer(totalXp,0,9999999,0));}
export function calculateSettlementLevel(totalXp){const xp=integer(totalXp,0,9999999,0);let level=0;for(let i=0;i<SETTLEMENT_XP_CURVE.length;i+=1){if(xp<SETTLEMENT_XP_CURVE[i])break;level=i;}return level;}
export function calculateSkillProgress(skillId,snapshot={}){const skill=text(skillId);const level=getSettlementSkillLevel(skill,snapshot);const xp=integer(snapshot.skillXp?.[skill],0,9999999,0);return{skill,level,xp,nextLevelXp:getSettlementXpForLevel(Math.min(level+1,SETTLEMENT_XP_CURVE.length-1)),remaining:getSettlementXpToNextLevel(level,xp),capped:level>=SETTLEMENT_XP_CURVE.length-1};}
export function calculateActionXp(action,context={}){const base=BASE_AWARDS[text(action)]??5;const quality=Math.max(0,Math.min(2,number(context.quality)));const difficulty=Math.max(0,Math.min(3,number(context.difficulty)));const chain=Math.max(0,Math.min(4,number(context.chain)));return Math.max(1,Math.round(base*(1+quality*0.1+difficulty*0.05+chain*0.03)));}
export function calculateCraftXp(recipe,context={}){const base=integer(recipe?.xp,1,9999,1);const quality=Math.max(0,Math.min(1,number(context.quality,recipe?.qualityBase??0)));const bonus=context.perks?.includes('smithing_ledger')?0.05:0;return Math.max(1,Math.round(base*(1+Math.max(0,quality-0.5)*0.2+bonus)));}
export function calculateQuestObjectiveXp(objective,context={}){const base=integer(objective?.rewardXp,1,9999,1);const chain=Math.max(0,Math.min(4,integer(context.chain,0,4,0)));const bonus=context.perks?.includes('scribe')?0.05:0;return Math.max(1,Math.round(base*(1+chain*0.04+bonus)));}
export function calculatePerkEffects(perkIds=[]){const effects={};for(const id of Array.isArray(perkIds)?perkIds.slice(0,24):[]){const perk=getSettlementPerk(id);if(!perk)continue;for(const[key,value]of Object.entries(perk.effect??{})){if(typeof value==='number')effects[key]=(effects[key]??0)+value;else if(value===true)effects[key]=true;}}return effects;}
export function projectSettlementSkillAward(skillId,currentXp,awardXp){const skill=text(skillId);const before=integer(currentXp,0,9999999,0);const award=integer(awardXp,0,9999999,0);const after=before+award;const beforeLevel=calculateSettlementLevel(before);const afterLevel=calculateSettlementLevel(after);return{skill,awardedXp:award,beforeXp:before,afterXp:after,beforeLevel,afterLevel,levelsGained:Math.max(0,afterLevel-beforeLevel)};}
export function buildSettlementProgressionEnvelope(input={}){const action=text(input.action);const snapshot=input.snapshot??{};const skill=text(input.skill,action==='craft'?'smithing':action==='trade'?'commerce':action==='travel'?'travel':action==='talk'?'dialogue':'questing');const award=calculateActionXp(action,input);const currentXp=integer(snapshot.skillXp?.[skill],0,9999999,0);return{version:1,action,skill,projection:projectSettlementSkillAward(skill,currentXp,award),effects:calculatePerkEffects(snapshot.perks),authoritativeCommitRequired:true};}
export function validateSettlementProgressionEnvelope(envelope){const errors=[];if(envelope?.version!==1)errors.push('version');if(!text(envelope?.action))errors.push('action');if(!text(envelope?.skill))errors.push('skill');if(!envelope?.projection)errors.push('projection');return{ok:errors.length===0,errors};}
export function summarizeSettlementProgression(envelope){const check=validateSettlementProgressionEnvelope(envelope);if(!check.ok)return check;return{ok:true,action:envelope.action,skill:envelope.skill,awardedXp:envelope.projection.awardedXp,levelBefore:envelope.projection.beforeLevel,levelAfter:envelope.projection.afterLevel,levelsGained:envelope.projection.levelsGained,effects:clone(envelope.effects)};}
export function buildProgressionCheckpoint(snapshot={}){return{version:1,skills:SETTLEMENT_SKILLS.map(skill=>({skill,level:getSettlementSkillLevel(skill,snapshot),xp:integer(snapshot.skillXp?.[skill],0,9999999,0),progress:calculateSkillProgress(skill,snapshot)})),perks:(snapshot.perks??[]).slice(0,24)};}
export function compareProgressionCheckpoints(a,b){const left=buildProgressionCheckpoint(a);const right=buildProgressionCheckpoint(b);const changes=[];for(const skill of SETTLEMENT_SKILLS){const l=left.skills.find(v=>v.skill===skill);const r=right.skills.find(v=>v.skill===skill);if(l&&r&&(l.level!==r.level||l.xp!==r.xp))changes.push({skill,levelBefore:l.level,levelAfter:r.level,xpBefore:l.xp,xpAfter:r.xp});}return{changed:changes.length>0,changes,perksBefore:[...left.perks],perksAfter:[...right.perks]};}
