/**
 * Settlement campaign ownership and contract assertions.
 * CI/test-facing helpers; runtime remains adapter-only.
 */
export const SETTLEMENT_CAMPAIGN_CONTRACT_VERSION=1;
const MAX=Object.freeze({nodes:24,actions:16,history:64,requests:64,text:160});
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,MAX.text):fallback;};
const bool=value=>value===true;
export const FORBIDDEN_RUNTIME_TOKENS=Object.freeze(['EditorMaterialStudio','GeographicSettlementManager','class SettlementManager','class QuestSystem','new QuestSystem','class InventorySystem','new Inventory','new Economy']);
export const AUTHORIZED_RUNTIME_OWNERS=Object.freeze(['SettlementVerticalSlice','QuestSystem','Inventory','Equipment','Economy','Crafting','Travel','Survival','SaveLoad','EventBus']);
export function validateRuntimeOwnershipSource(source=''){const content=String(source??'');const violations=FORBIDDEN_RUNTIME_TOKENS.filter(token=>content.includes(token));return{ok:violations.length===0,violations,editorImport:content.includes('EditorMaterialStudio')};}
export function validateInjectedOwners(handlers={}){const source=handlers&&typeof handlers==='object'?handlers:{};const accepted=['enterSettlement','exitSettlement','interact','talk','trade','craft','acceptQuest','advanceQuest','travel','save','rest','equip','buy','sell'];const provided=accepted.filter(name=>typeof source[name]==='function');return{ok:true,provided,missing:accepted.filter(name=>!provided.includes(name))};}
export function validateRuntimeViewModel(view={}){const errors=[];if(view.version==null)errors.push('version');if(view.contentVersion==null)errors.push('content-version');if(!Number.isInteger(view.revision)||view.revision<0)errors.push('revision');if(!Array.isArray(view.availableActions))errors.push('actions');if(view.history&&!Array.isArray(view.history))errors.push('history');if((view.history?.length??0)>MAX.history)errors.push('history-limit');if((view.route?.length??0)>MAX.nodes)errors.push('route-limit');return{ok:errors.length===0,errors};}
export function validateRuntimeEvent(event={}){const errors=[];if(!text(event.name))errors.push('name');if(!Number.isFinite(Number(event.at)))errors.push('timestamp');if(!Number.isInteger(event.revision))errors.push('revision');if(event.requestId!=null&&!text(event.requestId))errors.push('request-id');return{ok:errors.length===0,errors};}
export function validateRequestContract(request={}){const errors=[];if(request.version!==1)errors.push('version');if(!text(request.requestId))errors.push('request-id');if(!text(request.type))errors.push('type');if(request.input!=null&&typeof request.input!=='object')errors.push('input');return{ok:errors.length===0,errors};}
export function validateResponseContract(response={}){const errors=[];if(response.version!==1)errors.push('version');if(!text(response.requestId))errors.push('request-id');if(typeof response.ok!=='boolean')errors.push('ok');if(!text(response.type))errors.push('type');return{ok:errors.length===0,errors};}
export function validateSaveBoundary(payload={}){const errors=[];if(payload.schema!==1)errors.push('schema');if(payload.runtimeVersion!==1)errors.push('runtime-version');if(payload.contentVersion!==2)errors.push('content-version');if(!payload.session||typeof payload.session!=='object')errors.push('session');if((payload.session?.history?.length??0)>MAX.history)errors.push('history');if((payload.session?.route?.length??0)>MAX.nodes)errors.push('route');if((payload.session?.requestIds?.length??0)>MAX.requests)errors.push('requests');return{ok:errors.length===0,errors};}
export function validatePlacementBoundary(evidence={}){const errors=[];if(!text(evidence.sourceAsset))errors.push('source-asset');if(evidence.material?.validated!==true)errors.push('material-validation');if(!text(evidence.material?.manifestId))errors.push('material-manifest');if(evidence.placement?.groundAligned!==true)errors.push('ground-alignment');if(evidence.evidence?.manifestProduced!==true)errors.push('placement-manifest');return{ok:errors.length===0,errors};}
export function buildContractManifest(){return{version:1,limits:{...MAX},owners:[...AUTHORIZED_RUNTIME_OWNERS],forbiddenRuntimeTokens:[...FORBIDDEN_RUNTIME_TOKENS],requiredPlacementOrder:['source-asset','material-assignment','placement-validation','ground-alignment','manifest','scene-attachment'],checks:['freshness','determinism','shared-material-placement','runtime-ownership','save-boundary','browser-proof','pwa-cache']};}
export function validateContractManifest(manifest=buildContractManifest()){const errors=[];if(manifest.version!==1)errors.push('version');for(const owner of ['SettlementVerticalSlice','QuestSystem','Inventory','Economy','Crafting','Travel','SaveLoad'])if(!manifest.owners.includes(owner))errors.push(owner);if(manifest.requiredPlacementOrder?.at(-1)!=='scene-attachment')errors.push('placement-order');return{ok:errors.length===0,errors};}
export function assertSettlementContract(surface={}){const view=validateRuntimeViewModel(surface.view??{});const save=validateSaveBoundary(surface.save??{});const placement=validatePlacementBoundary(surface.placement??{});const contract=validateContractManifest(surface.contract??buildContractManifest());return{ok:view.ok&&save.ok&&placement.ok&&contract.ok,view,save,placement,contract};}
export function freezeContractSnapshot(snapshot={}){return Object.freeze({version:1,data:Object.freeze({runtimeVersion:snapshot.runtimeVersion??null,contentVersion:snapshot.contentVersion??null,activeService:text(snapshot.activeService),revision:Number.isInteger(snapshot.revision)?snapshot.revision:0,healthy:bool(snapshot.healthy)})});}
