/**
 * Settlement quest-flow adapter.
 * It bridges authored objectives to existing QuestSystem callbacks.
 */
import { getSettlementQuestObjective, listSettlementQuestObjectives } from './settlementCampaignContent.js';
import { evaluateObjectiveRule, normalizeRpgSnapshot } from './settlementCampaignRules.js';
export const SETTLEMENT_QUEST_FLOW_VERSION=1;
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,160):fallback;};
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
function objectiveRecord(id){return getSettlementQuestObjective(id);}
function normalizeQuestRecord(value){const v=value&&typeof value==='object'?value:{};return{state:text(v.state,'unknown'),step:Math.max(0,Math.min(999,Math.trunc(Number(v.step)||0))),completed:Boolean(v.completed),rewardClaimed:Boolean(v.rewardClaimed)};}
export function buildQuestObjectiveEnvelope(objectiveId,snapshot={},context={}){const objective=objectiveRecord(objectiveId);if(!objective)return{ok:false,reason:'unknown-objective'};const state=normalizeRpgSnapshot(snapshot);const evaluation=evaluateObjectiveRule(objective.id,state);return{version:1,objective:clone(objective),evaluation,questId:text(context.questId),requestId:text(context.requestId),authoritativeCommitRequired:evaluation.ok};}
export function evaluateQuestObjectiveChain(objectiveIds=[],snapshot={}){const state=normalizeRpgSnapshot(snapshot);const ids=Array.isArray(objectiveIds)?objectiveIds.slice(0,32):[];const results=ids.map(id=>({objectiveId:id,...evaluateObjectiveRule(id,state)}));return{version:1,complete:results.length>0&&results.every(result=>result.ok),results};}
export function getNextIncompleteObjective(objectiveIds=[],snapshot={}){const state=normalizeRpgSnapshot(snapshot);for(const id of Array.isArray(objectiveIds)?objectiveIds:[]){const objective=objectiveRecord(id);if(!objective)continue;const evaluation=evaluateObjectiveRule(objective.id,state);if(!evaluation.ok)return{ok:true,objective:clone(objective),evaluation};}return{ok:false,reason:'quest-chain-complete'};}
export function buildQuestStepPlan(objectiveIds=[],snapshot={},options={}){const state=normalizeRpgSnapshot(snapshot);const ids=Array.isArray(objectiveIds)?objectiveIds.slice(0,32):[];const active=Number.isInteger(options.activeIndex)?options.activeIndex:0;const plan=ids.map((objectiveId,index)=>{const objective=objectiveRecord(objectiveId);if(!objective)return{index,objectiveId,status:'invalid'};const evaluation=evaluateObjectiveRule(objective.id,state);return{index,objectiveId:objective.id,label:objective.label,type:objective.type,target:objective.target,quantity:objective.quantity,rewardXp:objective.rewardXp,status:evaluation.ok?'complete':index===active?'active':'locked',evaluation};});return{version:1,activeIndex:active,plan};}
export function createQuestProgressController(runtime,options={}){if(!runtime||typeof runtime.getViewModel!=='function')throw new TypeError('Runtime is required.');const objectiveIds=Array.isArray(options.objectiveIds)?options.objectiveIds.slice(0,32):listSettlementQuestObjectives();let activeIndex=Math.max(0,Math.min(Math.max(0,objectiveIds.length-1),Number(options.activeIndex)||0));let history=[];const record=entry=>{history=[...history,{at:Date.now(),activeIndex,...clone(entry)}].slice(-64);};const state=()=>buildQuestStepPlan(objectiveIds,runtime.getViewModel().player,{activeIndex});const current=()=>objectiveIds[activeIndex]?buildQuestObjectiveEnvelope(objectiveIds[activeIndex],runtime.getViewModel().player):null;const advance=async(input={})=>{const objectiveId=objectiveIds[activeIndex];if(!objectiveId)return{ok:false,reason:'quest-chain-complete'};const currentStep=current();if(!currentStep?.evaluation?.ok)return{ok:false,reason:'objective-incomplete',objective:clone(currentStep?.objective),evaluation:clone(currentStep?.evaluation)};const result=await runtime.execute('advanceQuest',{...input,objectiveId,questId:text(input.questId),step:activeIndex});record({type:'advance',objectiveId,ok:result.ok,reason:result.reason});if(result.ok&&activeIndex<objectiveIds.length-1){activeIndex+=1;record({type:'activate-next',objectiveId:objectiveIds[activeIndex]});}return result;};const setActiveIndex=index=>{if(!Number.isInteger(index)||index<0||index>=objectiveIds.length)return{ok:false,reason:'invalid-objective-index'};activeIndex=index;record({type:'set-active-index',objectiveId:objectiveIds[index]});return{ok:true,activeIndex,objectiveId:objectiveIds[index]};};const reset=()=>{activeIndex=0;record({type:'reset'});return state();};return Object.freeze({current,state,advance,setActiveIndex,reset,history:()=>clone(history)});}
export function summarizeQuestRecord(questId,rawRecord){const objective=objectiveRecord(questId);const record=normalizeQuestRecord(rawRecord);return{questId:text(questId),objective:objective?clone(objective):null,state:record.state,step:record.step,completed:record.completed,rewardClaimed:record.rewardClaimed};}
