/** Declarative traversal scenario catalogue for regression and tuning tools. */
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIO_VERSION=1;
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS=Object.freeze([
  {id:'far-gateway-clear',stage:'far',lane:'gateway',weather:'clear',expected:'orient',risk:'normal'},
  {id:'far-market-clear',stage:'far',lane:'market',weather:'clear',expected:'orient',risk:'normal'},
  {id:'far-tavern-rain',stage:'far',lane:'tavern',weather:'rain',expected:'orient',risk:'warning'},
  {id:'far-craft-wind',stage:'far',lane:'craft',weather:'wind',expected:'orient',risk:'normal'},
  {id:'far-farm-moor',stage:'far',lane:'farm',weather:'clear',expected:'orient',risk:'normal'},
  {id:'far-military-fog',stage:'far',lane:'military',weather:'fog',expected:'orient',risk:'warning'},
  {id:'far-stable-snow',stage:'far',lane:'stable',weather:'snow',expected:'orient',risk:'warning'},
  {id:'far-home-clear',stage:'far',lane:'home',weather:'clear',expected:'orient',risk:'normal'},
  {id:'far-river-rain',stage:'far',lane:'river',weather:'rain',expected:'orient',risk:'warning'},
  {id:'far-ridge-wind',stage:'far',lane:'ridge',weather:'wind',expected:'orient',risk:'normal'},
  {id:'approach-gateway-clear',stage:'approach',lane:'gateway',weather:'clear',expected:'commit',risk:'normal'},
  {id:'approach-market-clear',stage:'approach',lane:'market',weather:'clear',expected:'commit',risk:'normal'},
  {id:'approach-tavern-rain',stage:'approach',lane:'tavern',weather:'rain',expected:'commit',risk:'warning'},
  {id:'approach-craft-wind',stage:'approach',lane:'craft',weather:'wind',expected:'commit',risk:'normal'},
  {id:'approach-farm-moor',stage:'approach',lane:'farm',weather:'clear',expected:'commit',risk:'normal'},
  {id:'approach-military-fog',stage:'approach',lane:'military',weather:'fog',expected:'commit',risk:'warning'},
  {id:'approach-stable-snow',stage:'approach',lane:'stable',weather:'snow',expected:'commit',risk:'warning'},
  {id:'approach-home-clear',stage:'approach',lane:'home',weather:'clear',expected:'commit',risk:'normal'},
  {id:'approach-river-rain',stage:'approach',lane:'river',weather:'rain',expected:'commit',risk:'warning'},
  {id:'approach-ridge-wind',stage:'approach',lane:'ridge',weather:'wind',expected:'commit',risk:'normal'},
  {id:'threshold-gateway-clear',stage:'threshold',lane:'gateway',weather:'clear',expected:'arrive',risk:'normal'},
  {id:'threshold-market-clear',stage:'threshold',lane:'market',weather:'clear',expected:'arrive',risk:'normal'},
  {id:'threshold-tavern-rain',stage:'threshold',lane:'tavern',weather:'rain',expected:'arrive',risk:'warning'},
  {id:'threshold-craft-wind',stage:'threshold',lane:'craft',weather:'wind',expected:'arrive',risk:'normal'},
  {id:'threshold-farm-moor',stage:'threshold',lane:'farm',weather:'clear',expected:'arrive',risk:'normal'},
  {id:'threshold-military-fog',stage:'threshold',lane:'military',weather:'fog',expected:'arrive',risk:'warning'},
  {id:'threshold-stable-snow',stage:'threshold',lane:'stable',weather:'snow',expected:'arrive',risk:'warning'},
  {id:'threshold-home-clear',stage:'threshold',lane:'home',weather:'clear',expected:'arrive',risk:'normal'},
  {id:'threshold-river-rain',stage:'threshold',lane:'river',weather:'rain',expected:'arrive',risk:'warning'},
  {id:'threshold-ridge-wind',stage:'threshold',lane:'ridge',weather:'wind',expected:'arrive',risk:'normal'},
  {id:'inside-gateway-clear',stage:'inside',lane:'gateway',weather:'clear',expected:'linger',risk:'normal'},
  {id:'inside-market-clear',stage:'inside',lane:'market',weather:'clear',expected:'linger',risk:'normal'},
  {id:'inside-tavern-rain',stage:'inside',lane:'tavern',weather:'rain',expected:'linger',risk:'warning'},
  {id:'inside-craft-wind',stage:'inside',lane:'craft',weather:'wind',expected:'linger',risk:'normal'},
  {id:'inside-farm-moor',stage:'inside',lane:'farm',weather:'clear',expected:'linger',risk:'normal'},
  {id:'inside-military-fog',stage:'inside',lane:'military',weather:'fog',expected:'linger',risk:'warning'},
  {id:'inside-stable-snow',stage:'inside',lane:'stable',weather:'snow',expected:'linger',risk:'warning'},
  {id:'inside-home-clear',stage:'inside',lane:'home',weather:'clear',expected:'linger',risk:'normal'},
  {id:'inside-river-rain',stage:'inside',lane:'river',weather:'rain',expected:'linger',risk:'warning'},
  {id:'inside-ridge-wind',stage:'inside',lane:'ridge',weather:'wind',expected:'linger',risk:'normal'},
  {id:'service-gateway-clear',stage:'service',lane:'gateway',weather:'clear',expected:'linger',risk:'normal'},
  {id:'service-market-clear',stage:'service',lane:'market',weather:'clear',expected:'linger',risk:'normal'},
  {id:'service-tavern-rain',stage:'service',lane:'tavern',weather:'rain',expected:'linger',risk:'warning'},
  {id:'service-craft-wind',stage:'service',lane:'craft',weather:'wind',expected:'linger',risk:'normal'},
  {id:'service-farm-moor',stage:'service',lane:'farm',weather:'clear',expected:'linger',risk:'normal'},
  {id:'service-military-fog',stage:'service',lane:'military',weather:'fog',expected:'linger',risk:'warning'},
  {id:'service-stable-snow',stage:'service',lane:'stable',weather:'snow',expected:'linger',risk:'warning'},
  {id:'service-home-clear',stage:'service',lane:'home',weather:'clear',expected:'linger',risk:'normal'},
  {id:'service-river-rain',stage:'service',lane:'river',weather:'rain',expected:'linger',risk:'warning'},
  {id:'service-ridge-wind',stage:'service',lane:'ridge',weather:'wind',expected:'linger',risk:'normal'},
  {id:'departure-gateway-clear',stage:'departure',lane:'gateway',weather:'clear',expected:'return',risk:'normal'},
  {id:'departure-market-clear',stage:'departure',lane:'market',weather:'clear',expected:'return',risk:'normal'},
  {id:'departure-tavern-rain',stage:'departure',lane:'tavern',weather:'rain',expected:'return',risk:'warning'},
  {id:'departure-craft-wind',stage:'departure',lane:'craft',weather:'wind',expected:'return',risk:'normal'},
  {id:'departure-farm-moor',stage:'departure',lane:'farm',weather:'clear',expected:'return',risk:'normal'},
  {id:'departure-military-fog',stage:'departure',lane:'military',weather:'fog',expected:'return',risk:'warning'},
  {id:'departure-stable-snow',stage:'departure',lane:'stable',weather:'snow',expected:'return',risk:'warning'},
  {id:'departure-home-clear',stage:'departure',lane:'home',weather:'clear',expected:'return',risk:'normal'},
  {id:'departure-river-rain',stage:'departure',lane:'river',weather:'rain',expected:'return',risk:'warning'},
  {id:'departure-ridge-wind',stage:'departure',lane:'ridge',weather:'wind',expected:'return',risk:'normal'},
  {id:'resume-gateway-clear',stage:'resume',lane:'gateway',weather:'clear',expected:'traverse',risk:'normal'},
  {id:'resume-market-clear',stage:'resume',lane:'market',weather:'clear',expected:'traverse',risk:'normal'},
  {id:'resume-tavern-rain',stage:'resume',lane:'tavern',weather:'rain',expected:'traverse',risk:'warning'},
  {id:'resume-craft-wind',stage:'resume',lane:'craft',weather:'wind',expected:'traverse',risk:'normal'},
  {id:'resume-farm-moor',stage:'resume',lane:'farm',weather:'clear',expected:'traverse',risk:'normal'},
  {id:'resume-military-fog',stage:'resume',lane:'military',weather:'fog',expected:'traverse',risk:'warning'},
  {id:'resume-stable-snow',stage:'resume',lane:'stable',weather:'snow',expected:'traverse',risk:'warning'},
  {id:'resume-home-clear',stage:'resume',lane:'home',weather:'clear',expected:'traverse',risk:'normal'},
  {id:'resume-river-rain',stage:'resume',lane:'river',weather:'rain',expected:'traverse',risk:'warning'},
  {id:'resume-ridge-wind',stage:'resume',lane:'ridge',weather:'wind',expected:'traverse',risk:'normal'},
]);
const freeze=(v,s=new Set())=>{if(!v||typeof v!=='object'||s.has(v))return v;s.add(v);Object.freeze(v);for(const x of Object.values(v))freeze(x,s);return v;};
const stable=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(stable).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;
const digest=v=>{let h=2166136261,s=stable(v);for(let i=0;i<s.length;i+=1){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');};
export function findSettlementWorldCoverageTraversalScenarios(filter={}){const keys=Object.keys(filter);return freeze(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS.filter(row=>keys.every(k=>filter[k]==null||row[k]===filter[k])));}
export function validateSettlementWorldCoverageTraversalScenarios(){const e=[];if(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS.length!==70)e.push('count');const ids=SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS.map(x=>x.id);if(new Set(ids).size!==ids.length)e.push('duplicate-id');if(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS.some(x=>!x.id||!x.stage||!x.lane||!x.weather||!x.expected||!x.risk))e.push('shape');return freeze({ok:e.length===0,errors:e,count:SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS.length,fingerprint:digest(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS)});}
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIO_API=Object.freeze({version:1,count:70,find:'findSettlementWorldCoverageTraversalScenarios',validate:'validateSettlementWorldCoverageTraversalScenarios'});
