/**
 * Settlement equipment adapter.
 * Supports equipment semantics and repair quotes without becoming the inventory owner.
 */
import { getSettlementItem } from './settlementCampaignContent.js';
import { normalizeRpgSnapshot, evaluateEquipmentRule } from './settlementCampaignRules.js';
export const SETTLEMENT_EQUIPMENT_VERSION=1;
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,160):fallback;};
const number=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const integer=(value,min=0,max=999999)=>Math.max(min,Math.min(max,Math.trunc(number(value))));
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
const SLOTS=Object.freeze({weapon:['weapon'],'armour':['chest','body'],'utility':['utility','offhand']});
export function resolveEquipmentSlot(itemId,preferredSlot=''){const item=getSettlementItem(text(itemId));if(!item)return{ok:false,reason:'unknown-item'};if(text(preferredSlot))return{ok:true,itemId:item.id,slot:text(preferredSlot),source:'preferred'};if(item.category==='weapon')return{ok:true,itemId:item.id,slot:'weapon',source:'category'};if(item.category==='armour')return{ok:true,itemId:item.id,slot:'chest',source:'category'};return{ok:true,itemId:item.id,slot:'utility',source:'fallback'};}
export function buildEquipmentCatalog(snapshot={},options={}){const state=normalizeRpgSnapshot(snapshot);const ids=Array.isArray(options.itemIds)?options.itemIds:Object.keys(state.inventory);return ids.slice(0,24).map(id=>{const item=getSettlementItem(id);if(!item)return null;const slot=resolveEquipmentSlot(id);return{...clone(item),slot:slot.slot,owned:state.inventory[id]||0,equipped:Object.values(state.equipment).includes(id),canEquip:(state.inventory[id]||0)>0||Object.values(state.equipment).includes(id)};}).filter(Boolean);}
export function evaluateEquipmentAction(itemId,slot,snapshot={}){const state=normalizeRpgSnapshot(snapshot);const resolved=resolveEquipmentSlot(itemId,slot);if(!resolved.ok)return resolved;const rule=evaluateEquipmentRule(itemId,resolved.slot,state);return{ok:rule.ok,reason:rule.reason,itemId:resolved.itemId,slot:resolved.slot,owned:state.inventory[resolved.itemId]||0,equipped:Object.values(state.equipment).includes(resolved.itemId)};}
export function calculateDurability(itemId,condition=1){const item=getSettlementItem(text(itemId));if(!item)return{ok:false,reason:'unknown-item'};const value=Math.max(0,Math.min(1,number(condition,1)));const base=item.category==='weapon'?100:item.category==='armour'?120:80;return{ok:true,itemId:item.id,maxDurability:base,durability:Math.round(base*value),condition:value,worn:value<0.25,broken:value<=0};}
export function calculateRepairQuote(itemId,condition=1,modifiers={}){const durability=calculateDurability(itemId,condition);if(!durability.ok)return durability;const item=getSettlementItem(itemId);const missingRatio=1-durability.condition;const materialFactor=item.category==='weapon'?1.2:item.category==='armour'?1.1:0.7;const discount=Math.max(-0.3,Math.min(0.3,number(modifiers.repairRate)));const cost=Math.max(1,Math.round((item.buy*missingRatio*materialFactor)*(1+discount)));return{ok:true,itemId:item.id,durability,unitCost:cost,missingRatio:Math.round(missingRatio*100)/100};}
export function evaluateRepair(itemId,condition,snapshot={},modifiers={}){const state=normalizeRpgSnapshot(snapshot);const quote=calculateRepairQuote(itemId,condition,modifiers);if(!quote.ok)return quote;return state.copper>=quote.unitCost?{ok:true,reason:'',quote,remainingCopper:state.copper-quote.unitCost}:{ok:false,reason:'insufficient-copper',quote,remainingCopper:state.copper};}
export function buildEquipmentCommit(itemId,slot,snapshot={},context={}){const state=normalizeRpgSnapshot(snapshot);const action=evaluateEquipmentAction(itemId,slot,state);if(!action.ok)return action;return{version:1,type:'equip',itemId:action.itemId,slot:action.slot,requestId:text(context.requestId),source:text(context.source,'settlement-blacksmith'),before:clone(state.equipment),requiresAuthoritativeCommit:true};}
export function buildRepairCommit(itemId,condition,snapshot={},context={}){const rule=evaluateRepair(itemId,condition,snapshot,context.modifiers);if(!rule.ok)return rule;return{version:1,type:'repair',itemId:text(itemId),cost:rule.quote.unitCost,requestId:text(context.requestId),source:text(context.source,'settlement-blacksmith'),requiresAuthoritativeCommit:true};}
export function validateEquipmentCommit(commit){const errors=[];if(commit?.version!==1)errors.push('version');if(commit?.type!=='equip')errors.push('type');if(!text(commit?.itemId))errors.push('item');if(!text(commit?.slot))errors.push('slot');return{ok:errors.length===0,errors};}
export function validateRepairCommit(commit){const errors=[];if(commit?.version!==1)errors.push('version');if(commit?.type!=='repair')errors.push('type');if(!text(commit?.itemId))errors.push('item');if(integer(commit?.cost)<1)errors.push('cost');return{ok:errors.length===0,errors};}
export function summarizeEquipment(snapshot={},options={}){const state=normalizeRpgSnapshot(snapshot);const slots=options.slots??Object.keys(state.equipment);return{version:1,slots:slots.map(slot=>({slot,itemId:text(state.equipment[slot]),item:state.equipment[slot]?getSettlementItem(state.equipment[slot]):null})),capacity:{carryWeight:state.carryWeight,maxCarryWeight:state.maxCarryWeight},weapon:text(state.equipment.weapon),armour:text(state.equipment.chest??state.equipment.body)};}
export function buildRepairPreview(snapshot={},items=[]){return(items.length?items:['iron_sword','leather_gloves','linen_tunic']).slice(0,12).map(itemId=>({itemId,quote:calculateRepairQuote(itemId,0.6,{})})).filter(v=>v.quote?.ok);}
