/** Settlement UX content registry. */
export const SETTLEMENT_UX_CONTENT_VERSION=1;
export const SETTLEMENT_UX_ROLE_KEYS=Object.freeze(['blacksmith','tavern','market','farm','barracks','stable','house','gate']);
const ROLES=Object.freeze({blacksmith:{label:'Demirci',kind:'crafting',primary:['craft','trade'],secondary:['back'],beats:['arrival','commerce','progression','recovery']},tavern:{label:'Han',kind:'interior',primary:['talk','interact'],secondary:['back'],beats:['arrival','progression','recovery']},market:{label:'Pazar',kind:'vendor',primary:['trade'],secondary:['back'],beats:['arrival','commerce','recovery']},farm:{label:'Çiftlik',kind:'interior',primary:['interact','trade','travel'],secondary:['back'],beats:['arrival','commerce','departure']},barracks:{label:'Kışla',kind:'interior',primary:['talk','interact'],secondary:['back'],beats:['arrival','progression','departure']},stable:{label:'Ahır',kind:'interior',primary:['interact','travel'],secondary:['back'],beats:['arrival','departure','recovery']},house:{label:'Ev',kind:'interior',primary:['interact','talk','save'],secondary:['back'],beats:['arrival','recovery']},gate:{label:'Kale kapısı',kind:'door',primary:['enter','exit','travel'],secondary:['back'],beats:['arrival','departure']}});
const COPY=Object.freeze({settlement:['Yerleşim','Yakındaki hizmetleri incele.'],interior:['İç mekân','İçerideki etkileşimleri seç.'],door:['Kapı','İçeri girmek veya dışarı çıkmak için kullan.'],npc:['Karakter','Konuşma ve görev bağlantılarını aç.'],vendor:['Satıcı','Al ve sat işlemlerini yönet.'],crafting:['Üretim','Malzeme gereksinimlerini kontrol et.'],quest:['Görev','Koşulları ve sonraki adımı incele.'],travel:['Seyahat','Maliyet ve yorgunluğu onayla.'],save:['Kayıt','İlerlemeyi güvenli biçimde kaydet.']});
const ACTIONS=Object.freeze({enter:'İçeri gir',exit:'Dışarı çık',interact:'Etkileş',talk:'Konuş',trade:'Takas',craft:'Üret',acceptQuest:'Görevi kabul et',advanceQuest:'Görevi ilerlet',travel:'Yola çık',save:'Oyunu kaydet',back:'Geri dön'});
const BEATS=Object.freeze({arrival:['Varış','Yerleşime giriş ve ilk yönlendirme.'],commerce:['Alışveriş','Pazar, satıcı ve malzeme akışı.'],progression:['İlerleme','Görev, beceri ve üretim zinciri.'],departure:['Ayrılış','Kapı, ahır ve seyahat onayı.'],recovery:['Kurtarma','Kayıt, geri dönüş ve güvenli toparlanma.']});
const text=(v,f='')=>String(v??f).trim().slice(0,160);
export function listSettlementUxRoles(){return [...SETTLEMENT_UX_ROLE_KEYS];}
export function getSettlementUxRole(role){const v=ROLES[role];return v?{...v,primary:[...v.primary],secondary:[...v.secondary],beats:[...v.beats]}:null;}
export function getSettlementUxCopy(kind){const v=COPY[kind]??COPY.settlement;return {title:v[0],hint:v[1]};}
export function getSettlementUxActionLabel(action){return ACTIONS[action]??text(action,'Etkileş');}
export function getSettlementUxBeat(beat){const v=BEATS[beat]??BEATS.arrival;return {label:v[0],description:v[1]};}
export function getSettlementUxServiceCard(role,overrides={}){const v=getSettlementUxRole(role);if(!v)return null;return {id:text(overrides.id,`role:${role}`),role,label:text(overrides.label,v.label),kind:v.kind,primaryActions:v.primary.map(getSettlementUxActionLabel),secondaryActions:v.secondary.map(getSettlementUxActionLabel),beats:v.beats.map(getSettlementUxBeat),hint:text(overrides.hint,`Bu ${v.label.toLocaleLowerCase('tr-TR')} hizmetini aç.`),riskHint:text(overrides.riskHint,'Koşullar işlem öncesi tekrar doğrulanır.')};}
export function buildSettlementUxJourney(role,context={}){const v=getSettlementUxRole(role);if(!v)return null;const available=new Set(context.availableBeats??v.beats);return {role,label:v.label,steps:v.beats.map((beat,index)=>({id:`${role}:${beat}`,index,beat,label:getSettlementUxBeat(beat).label,description:getSettlementUxBeat(beat).description,state:available.has(beat)?'available':'locked',prerequisite:index?`${role}:${v.beats[index-1]}`:null}))};}
export function localizeSettlementUxFeedback(input={}){return {title:input.status==='ok'?'Kész':input.status==='blocked'?'Bloke':'Bilgi',action:getSettlementUxActionLabel(input.action),message:text(input.message,'İşlem sonucu güncellendi.'),status:text(input.status,'ok')};}
export function buildSettlementUxNodeCopy(node={}){const kind=text(node.kind,'settlement');const c=getSettlementUxCopy(kind);return {title:text(node.label,c.title),subtitle:text(node.subtitle,c.hint),kind};}
export function serializeSettlementUxContent(){return {version:1,roles:ROLES,beats:BEATS,actions:ACTIONS};}
export function validateSettlementUxContent(payload){const errors=[];if(payload?.version!==1)errors.push('version');for(const r of SETTLEMENT_UX_ROLE_KEYS)if(!payload?.roles?.[r])errors.push(`role:${r}`);for(const b of Object.keys(BEATS))if(!payload?.beats?.[b])errors.push(`beat:${b}`);return {ok:!errors.length,errors};}
