/** Deterministic pacing guidance for settlement traversal presentation. */
import { createSettlementWorldCoverageContinuityExperience } from './settlementWorldCoverageContinuityExperience.js';
import { createSettlementWorldCoverageTraversalPlan } from './settlementWorldCoverageTraversal.js';
import { createSettlementWorldCoverageTraversalRisk } from './settlementWorldCoverageTraversalRisk.js';
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_VERSION=1;
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_STATES=Object.freeze(['pause','crawl','walk','steady','rush','recover']);
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const c=v=>Math.max(0,Math.min(1,n(v)));
const freeze=(v,s=new Set())=>{if(!v||typeof v!=='object'||s.has(v))return v;s.add(v);Object.freeze(v);for(const x of Object.values(v))freeze(x,s);return v;};
const stable=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(stable).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;
const digest=v=>{let h=2166136261,s=stable(v);for(let i=0;i<s.length;i+=1){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');};
function chooseState(stage,risk,fatigue,weather){if(risk>=.82||weather<.25)return 'pause';if(risk>=.66)return 'crawl';if(fatigue>.82)return 'recover';if(stage==='threshold')return 'walk';if(stage==='departure'&&risk<.4)return 'rush';return 'steady';}
function rate(state){return {pause:0,crawl:.28,walk:.52,steady:.72,rush:1,recover:.38}[state]??.5;}
function intervals(state,mobile){const base={pause:0,crawl:2,walk:5,steady:8,rush:12,recover:6}[state]??5;const scale=mobile?.62:1;return {lookAheadMeters:Math.round(base*scale*10),cueIntervalSeconds:Math.max(1,Math.round(base/2*scale)),movementHint:state};}
function reasons(stage,risk,fatigue,weather){const out=[];if(risk>.58)out.push('risk');if(fatigue>.55)out.push('fatigue');if(weather<.55)out.push('weather');if(stage==='threshold')out.push('entry');if(stage==='departure')out.push('return');return [...new Set(out)];}
export function createSettlementWorldCoverageTraversalPacing(options={}){const experience=createSettlementWorldCoverageContinuityExperience(options);const plan=createSettlementWorldCoverageTraversalPlan(options);const risk=createSettlementWorldCoverageTraversalRisk(options);const fatigue=c(n(options.player?.fatigue,0)/100);const weather=c(n(experience.atmosphere?.weather?.visibility,.7));const state=chooseState(plan.stage,risk.risk,fatigue,weather);const payload={version:1,settlementId:plan.settlementId,stage:plan.stage,phase:plan.phase,state,rate:rate(state),intervals:intervals(state,options.mobile),reasons:reasons(plan.stage,risk.risk,fatigue,weather),risk:risk.risk,fatigue,weatherVisibility:weather,mobile:Boolean(options.mobile),ownership:{readOnly:true,noMovementMutation:true,noTimeMutation:true,noGameplayMutation:true}};return freeze({...payload,fingerprint:digest(payload)});}
export function validateSettlementWorldCoverageTraversalPacing(value){const s=value&&typeof value==='object'?value:{};const e=[];if(!SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_STATES.includes(s.state))e.push('state');if(s.rate<0||s.rate>1)e.push('rate');if(s.fatigue<0||s.fatigue>1)e.push('fatigue');if(s.weatherVisibility<0||s.weatherVisibility>1)e.push('weather');if(!s.ownership?.readOnly||!s.ownership?.noMovementMutation)e.push('ownership');return freeze({ok:e.length===0,errors:e,state:s.state??'pause',fingerprint:s.fingerprint??digest(s)});}
export function summarizeSettlementWorldCoverageTraversalPacing(options={}){const p=createSettlementWorldCoverageTraversalPacing(options);return freeze({settlementId:p.settlementId,stage:p.stage,state:p.state,rate:p.rate,reasons:p.reasons,lookAheadMeters:p.intervals.lookAheadMeters,cueIntervalSeconds:p.intervals.cueIntervalSeconds,fingerprint:p.fingerprint});}
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_API=Object.freeze({version:1,states:[...SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_STATES],create:'createSettlementWorldCoverageTraversalPacing',validate:'validateSettlementWorldCoverageTraversalPacing',summary:'summarizeSettlementWorldCoverageTraversalPacing'});
