/**
 * Authored settlement dialogue content.
 * Pure narrative/choice data. State mutation stays with the existing runtime,
 * QuestSystem and their authoritative handlers.
 */
export const SETTLEMENT_EPISODE_DIALOGUE_VERSION = 1;
export const SETTLEMENT_EPISODE_DIALOGUE_LIMITS = Object.freeze({ scenes: 48, choices: 3, text: 220, tags: 6 });

const SCENES = Object.freeze({
  iron_and_oath:Object.freeze([
    Object.freeze({stepId:'iron-01',action:'talk',speaker:'Usta Boran',speakerRole:'demirhane',line:'Demirin yolu kesildi. Kervanlar boş geliyor; ocağı yeniden yürütmek için sana ihtiyacım var.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','iron_and_oath','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'iron-02',action:'talk',speaker:'Usta Boran',speakerRole:'demirhane',line:'İtibarın kapıyı açar. Burada söz, terazinin öteki kefesidir.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','iron_and_oath','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'iron-03',action:'collect',speaker:'Çırak Eren',speakerRole:'demirhane',line:'Dört cevher olmadan ocak ateşi yalnızca duman çıkarır.',intent:'collect',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'confirm',label:'Stoku tamamla.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','iron_and_oath','collect','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'iron-04',action:'collect',speaker:'Çırak Eren',speakerRole:'demirhane',line:'Kömürü de tamamla. Cevher var, yakıt yoksa hiçbir çekiç konuşmaz.',intent:'collect',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'confirm',label:'Stoku tamamla.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','iron_and_oath','collect','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'iron-05',action:'craft',speaker:'Usta Boran',speakerRole:'demirhane',line:'Şimdi işin özü burada: demiri ateşe değil, doğru ölçüye teslim et.',intent:'craft',choices:Object.freeze([Object.freeze({id:'inspect',label:'Tarifi incele.',tone:'neutral'}),Object.freeze({id:'craft',label:'Üretimi başlat.',tone:'neutral'}),Object.freeze({id:'back',label:'Ocağı kapat.',tone:'neutral'})]),tags:Object.freeze(['settlement','iron_and_oath','craft','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'iron-06',action:'equip',speaker:'Usta Boran',speakerRole:'demirhane',line:'Kılıcı eline aldığında bu yalnız eşya değil; verdiğin sözün ağırlığıdır.',intent:'equip',choices:Object.freeze([Object.freeze({id:'equip',label:'Kılıcı kuşan.',tone:'neutral'}),Object.freeze({id:'inspect',label:'Ekipmanı incele.',tone:'neutral'}),Object.freeze({id:'back',label:'Geri bırak.',tone:'neutral'})]),tags:Object.freeze(['settlement','iron_and_oath','equip','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'iron-07',action:'rest',speaker:'Usta Boran',speakerRole:'demirhane',line:'Dövmeden sonra dinlen. Yorgun demir kırılır; yorgun insan da.',intent:'rest',choices:Object.freeze([Object.freeze({id:'rest',label:'Dinlen.',tone:'neutral'}),Object.freeze({id:'status',label:'Durumu kontrol et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Devam et.',tone:'neutral'})]),tags:Object.freeze(['settlement','iron_and_oath','rest','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'iron-08',action:'talk',speaker:'Usta Boran',speakerRole:'demirhane',line:'Yeminini tuttun. Bu çekiç artık sana yabancı değil.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kapat.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','iron_and_oath','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
  ]),
  market_routes:Object.freeze([
    Object.freeze({stepId:'market-01',action:'talk',speaker:'Pazar Kâtibi Mira',speakerRole:'pazar',line:'Fiyatlar oynuyor. Kervan açığı kapanmazsa şehirde ekmek bile lüks olacak.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','market_routes','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'market-02',action:'buy',speaker:'Pazar Kâtibi Mira',speakerRole:'pazar',line:'Önce erzağını tamamla; yolculukta bakır kadar ekmek de hesabın parçasıdır.',intent:'buy',choices:Object.freeze([Object.freeze({id:'inspect',label:'Stoku incele.',tone:'neutral'}),Object.freeze({id:'confirm',label:'İşlemi onayla.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','market_routes','buy','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'market-03',action:'sell',speaker:'Tüccar Salim',speakerRole:'pazar',line:'Cevheri getir. Bugünkü kurdan alırım; teraziyi birlikte görelim.',intent:'sell',choices:Object.freeze([Object.freeze({id:'inspect',label:'Stoku incele.',tone:'neutral'}),Object.freeze({id:'confirm',label:'İşlemi onayla.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','market_routes','sell','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'market-04',action:'trade',speaker:'Tüccar Salim',speakerRole:'pazar',line:'Yol azığını hazırla. Kervanla aynı hesabı kullanırsan kaybın azalır.',intent:'trade',choices:Object.freeze([Object.freeze({id:'inspect',label:'Stoku incele.',tone:'neutral'}),Object.freeze({id:'confirm',label:'İşlemi onayla.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','market_routes','trade','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'market-05',action:'talk',speaker:'Pazar Kâtibi Mira',speakerRole:'pazar',line:'Nehir pazarı bağlantısı güven ister. Aldığın sözü orada yerine getir.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','market_routes','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'market-06',action:'travel',speaker:'Kapı Görevlisi',speakerRole:'pazar',line:'Nehir yolunda ücret ve yorgunluk birlikte işler; kapıdan çıkarken ikisini de gör.',intent:'travel',choices:Object.freeze([Object.freeze({id:'route',label:'Rotayı onayla.',tone:'neutral'}),Object.freeze({id:'cost',label:'Maliyeti göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','market_routes','travel','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'market-07',action:'sell',speaker:'Tüccar Salim',speakerRole:'pazar',line:'Deri fazlası burada değer bulur. Son açığı kapat, hesabı temizle.',intent:'sell',choices:Object.freeze([Object.freeze({id:'inspect',label:'Stoku incele.',tone:'neutral'}),Object.freeze({id:'confirm',label:'İşlemi onayla.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','market_routes','sell','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'market-08',action:'talk',speaker:'Pazar Kâtibi Mira',speakerRole:'pazar',line:'Kervan kaydını kapattık. Bir sonraki pazarda adın zaten bilinecek.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kapat.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','market_routes','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
  ]),
  road_watch:Object.freeze([
    Object.freeze({stepId:'watch-01',action:'talk',speaker:'Yüzbaşı Varek',speakerRole:'kışla',line:'Yol güvenliği düştü. Nöbet emrini al ve kapının hesabını üstlen.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','road_watch','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'watch-02',action:'train',speaker:'Yüzbaşı Varek',speakerRole:'kışla',line:'Kısa talim. Güç gösterisi değil, doğru hareket istiyorum.',intent:'train',choices:Object.freeze([Object.freeze({id:'train',label:'Talime gir.',tone:'neutral'}),Object.freeze({id:'status',label:'Beceri durumunu gör.',tone:'neutral'}),Object.freeze({id:'back',label:'Çık.',tone:'neutral'})]),tags:Object.freeze(['settlement','road_watch','train','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'watch-03',action:'equip',speaker:'Silah Ustası Heda',speakerRole:'kışla',line:'Kılıcı kuşan; nöbetçinin eli boş kalırsa emir yalnız kâğıttır.',intent:'equip',choices:Object.freeze([Object.freeze({id:'equip',label:'Kılıcı kuşan.',tone:'neutral'}),Object.freeze({id:'inspect',label:'Ekipmanı incele.',tone:'neutral'}),Object.freeze({id:'back',label:'Geri bırak.',tone:'neutral'})]),tags:Object.freeze(['settlement','road_watch','equip','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'watch-04',action:'talk',speaker:'Yüzbaşı Varek',speakerRole:'kışla',line:'Kapı emri doğrulanmadan devriyeye çıkma.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','road_watch','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'watch-05',action:'travel',speaker:'Kapı Görevlisi',speakerRole:'kışla',line:'Tepe karakolu orta riskli. Masrafı ve yorgunluğu bilerek seç.',intent:'travel',choices:Object.freeze([Object.freeze({id:'route',label:'Rotayı onayla.',tone:'neutral'}),Object.freeze({id:'cost',label:'Maliyeti göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','road_watch','travel','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'watch-06',action:'travel',speaker:'Kapı Görevlisi',speakerRole:'kışla',line:'Kuzey geçidi daha sakin ama dönüş hesabını unutma.',intent:'travel',choices:Object.freeze([Object.freeze({id:'route',label:'Rotayı onayla.',tone:'neutral'}),Object.freeze({id:'cost',label:'Maliyeti göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','road_watch','travel','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'watch-07',action:'talk',speaker:'Yüzbaşı Varek',speakerRole:'kışla',line:'Raporu getir; yol güvenliğini sayı ile değil, sonuç ile ölçeriz.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','road_watch','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'watch-08',action:'travel',speaker:'Kapı Görevlisi',speakerRole:'kışla',line:'Son devriyeyi tamamla. Güvenli bir yol, yeni görevlerin başlangıcıdır.',intent:'travel',choices:Object.freeze([Object.freeze({id:'route',label:'Rotayı onayla.',tone:'neutral'}),Object.freeze({id:'cost',label:'Maliyeti göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','road_watch','travel','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
  ]),
  hearth_and_home:Object.freeze([
    Object.freeze({stepId:'home-01',action:'rest',speaker:'Komşu Elif',speakerRole:'ev',line:'İlk geceyi burada geçir. Güvenli bir çatı, maceranın da parçasıdır.',intent:'rest',choices:Object.freeze([Object.freeze({id:'rest',label:'Dinlen.',tone:'neutral'}),Object.freeze({id:'status',label:'Durumu kontrol et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Devam et.',tone:'neutral'})]),tags:Object.freeze(['settlement','hearth_and_home','rest','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'home-02',action:'save',speaker:'Komşu Elif',speakerRole:'ev',line:'Şimdi kayıt al. Yarın her şeyi baştan yapmak zorunda kalma.',intent:'save',choices:Object.freeze([Object.freeze({id:'save',label:'Kaydet.',tone:'neutral'}),Object.freeze({id:'inspect',label:'Kayıt durumunu göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','hearth_and_home','save','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'home-03',action:'interact',speaker:'Ev Sandığı',speakerRole:'ev',line:'Kapak açıldı. Eşyalarını burada düzenlemek yolculuğun yükünü de hafifletir.',intent:'interact',choices:Object.freeze([Object.freeze({id:'interact',label:'Etkileş.',tone:'neutral'}),Object.freeze({id:'inspect',label:'İncele.',tone:'neutral'}),Object.freeze({id:'back',label:'Geri dön.',tone:'neutral'})]),tags:Object.freeze(['settlement','hearth_and_home','interact','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'home-04',action:'talk',speaker:'Komşu Elif',speakerRole:'ev',line:'Bu evdeki sözler de eşyalar kadar kalıcı olabilir; dinle.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','hearth_and_home','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'home-05',action:'rest',speaker:'Komşu Elif',speakerRole:'ev',line:'Bir kez daha dinlen. Yorgunluk görünmese de kararlarını etkiler.',intent:'rest',choices:Object.freeze([Object.freeze({id:'rest',label:'Dinlen.',tone:'neutral'}),Object.freeze({id:'status',label:'Durumu kontrol et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Devam et.',tone:'neutral'})]),tags:Object.freeze(['settlement','hearth_and_home','rest','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'home-06',action:'save',speaker:'Komşu Elif',speakerRole:'ev',line:'İkinci kaydı da al. Bu kez ilerlemen daha net bir iz bırakacak.',intent:'save',choices:Object.freeze([Object.freeze({id:'save',label:'Kaydet.',tone:'neutral'}),Object.freeze({id:'inspect',label:'Kayıt durumunu göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','hearth_and_home','save','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'home-07',action:'interact',speaker:'Ev Sandığı',speakerRole:'ev',line:'Hatıranı burada tut. Kaybolmayan eşya, döndüğünde seni karşılar.',intent:'interact',choices:Object.freeze([Object.freeze({id:'interact',label:'Etkileş.',tone:'neutral'}),Object.freeze({id:'inspect',label:'İncele.',tone:'neutral'}),Object.freeze({id:'back',label:'Geri dön.',tone:'neutral'})]),tags:Object.freeze(['settlement','hearth_and_home','interact','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'home-08',action:'talk',speaker:'Komşu Elif',speakerRole:'ev',line:'Ocak yandı, kapı kapandı. Ev artık haritada değil, hikâyende.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kapat.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','hearth_and_home','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
  ]),
  winter_supply:Object.freeze([
    Object.freeze({stepId:'winter-01',action:'talk',speaker:'Çiftlik Sahibi Narin',speakerRole:'çiftlik',line:'Kış erken geliyor. Depoyu doldurmazsak yollar kapandığında geç kalmış oluruz.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','winter_supply','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'winter-02',action:'collect',speaker:'Çiftlik Sahibi Narin',speakerRole:'çiftlik',line:'Otları ayır; küçük bir şişe bile seferde büyük fark yaratır.',intent:'collect',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'confirm',label:'Stoku tamamla.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','winter_supply','collect','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'winter-03',action:'collect',speaker:'Çiftlik Sahibi Narin',speakerRole:'çiftlik',line:'Ekmeği say. Dört eksikse mutfak planı aksar.',intent:'collect',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'confirm',label:'Stoku tamamla.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','winter_supply','collect','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'winter-04',action:'craft',speaker:'Çiftlik Aşçısı Toma',speakerRole:'çiftlik',line:'Yol azığını şimdi hazırla. Malzemeyi doğru kullanırsan yol uzar, açlık kısalır.',intent:'craft',choices:Object.freeze([Object.freeze({id:'inspect',label:'Tarifi incele.',tone:'neutral'}),Object.freeze({id:'craft',label:'Üretimi başlat.',tone:'neutral'}),Object.freeze({id:'back',label:'Ocağı kapat.',tone:'neutral'})]),tags:Object.freeze(['settlement','winter_supply','craft','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'winter-05',action:'trade',speaker:'Ahır Ustası Cem',speakerRole:'çiftlik',line:'At yemi eksik olursa binek hız değil yük olur. Bir payı şimdi al.',intent:'trade',choices:Object.freeze([Object.freeze({id:'inspect',label:'Stoku incele.',tone:'neutral'}),Object.freeze({id:'confirm',label:'İşlemi onayla.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','winter_supply','trade','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'winter-06',action:'rest',speaker:'Çiftlik Sahibi Narin',speakerRole:'çiftlik',line:'Dinlen. Soğukta acele, kaynağı da insanı da tüketir.',intent:'rest',choices:Object.freeze([Object.freeze({id:'rest',label:'Dinlen.',tone:'neutral'}),Object.freeze({id:'status',label:'Durumu kontrol et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Devam et.',tone:'neutral'})]),tags:Object.freeze(['settlement','winter_supply','rest','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'winter-07',action:'travel',speaker:'Kapı Görevlisi',speakerRole:'çiftlik',line:'Kış geçidi yüksek riskli. Çıkmadan maliyet ve yorgunluğu gör.',intent:'travel',choices:Object.freeze([Object.freeze({id:'route',label:'Rotayı onayla.',tone:'neutral'}),Object.freeze({id:'cost',label:'Maliyeti göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','winter_supply','travel','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'winter-08',action:'talk',speaker:'Çiftlik Sahibi Narin',speakerRole:'çiftlik',line:'İkmal raporun tamam. Kışın kendisi değil, hazırlıksızlık düşmandır.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kapat.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','winter_supply','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
  ]),
  stable_master:Object.freeze([
    Object.freeze({stepId:'stable-01',action:'talk',speaker:'Ahır Ustası Cem',speakerRole:'ahır',line:'Bineğin hazırsa yolun yarısı hazırdır. Ama yem ve dinlenme olmadan çıkma.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','stable_master','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'stable-02',action:'trade',speaker:'Ahır Ustası Cem',speakerRole:'ahır',line:'İki yem al. Fiyatı kontrol et; acele alışveriş yol maliyetini büyütür.',intent:'trade',choices:Object.freeze([Object.freeze({id:'inspect',label:'Stoku incele.',tone:'neutral'}),Object.freeze({id:'confirm',label:'İşlemi onayla.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','stable_master','trade','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'stable-03',action:'rest',speaker:'Ahır Ustası Cem',speakerRole:'ahır',line:'Bineği dinlendir. Yorgun at, uzun yolda güvenilmez bir ortak olur.',intent:'rest',choices:Object.freeze([Object.freeze({id:'rest',label:'Dinlen.',tone:'neutral'}),Object.freeze({id:'status',label:'Durumu kontrol et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Devam et.',tone:'neutral'})]),tags:Object.freeze(['settlement','stable_master','rest','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'stable-04',action:'talk',speaker:'Ahır Ustası Cem',speakerRole:'ahır',line:'Rota konuşalım. Kısa yol her zaman ucuz yol değildir.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kabul et.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','stable_master','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'stable-05',action:'travel',speaker:'Kapı Görevlisi',speakerRole:'ahır',line:'Eski değirmen yakın ve düşük riskli. İlk kontrol için iyi seçim.',intent:'travel',choices:Object.freeze([Object.freeze({id:'route',label:'Rotayı onayla.',tone:'neutral'}),Object.freeze({id:'cost',label:'Maliyeti göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','stable_master','travel','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'stable-06',action:'travel',speaker:'Kapı Görevlisi',speakerRole:'ahır',line:'Nehir pazarı daha canlı. Yol maliyetini yeniden hesapla.',intent:'travel',choices:Object.freeze([Object.freeze({id:'route',label:'Rotayı onayla.',tone:'neutral'}),Object.freeze({id:'cost',label:'Maliyeti göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','stable_master','travel','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'stable-07',action:'talk',speaker:'Ahır Ustası Cem',speakerRole:'ahır',line:'Raporu bırak. Atın durumu kadar yolun hesabı da kayda geçti.',intent:'talk',choices:Object.freeze([Object.freeze({id:'ask',label:'Ayrıntıyı sor.',tone:'neutral'}),Object.freeze({id:'accept',label:'Görevi kapat.',tone:'neutral'}),Object.freeze({id:'leave',label:'Şimdilik ayrıl.',tone:'neutral'})]),tags:Object.freeze(['settlement','stable_master','talk','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
    Object.freeze({stepId:'stable-08',action:'travel',speaker:'Kapı Görevlisi',speakerRole:'ahır',line:'Doğu yolu orta riskli. Hazırsan geçit seni bekliyor.',intent:'travel',choices:Object.freeze([Object.freeze({id:'route',label:'Rotayı onayla.',tone:'neutral'}),Object.freeze({id:'cost',label:'Maliyeti göster.',tone:'neutral'}),Object.freeze({id:'back',label:'Vazgeç.',tone:'neutral'})]),tags:Object.freeze(['settlement','stable_master','travel','dialogue']),ux:Object.freeze({showSpeaker:true,showChoices:true,showHistory:true,allowCancel:true})}),
  ]),
});

const clone=(value)=>value==null?value:JSON.parse(JSON.stringify(value));
const freeze=(value)=>{if(!value||typeof value!=='object'||Object.isFrozen(value))return value;Object.freeze(value);for(const nested of Object.values(value))freeze(nested);return value;};
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,220):fallback;};

export function listSettlementEpisodeDialogue(){return Object.keys(SCENES);}
export function getSettlementEpisodeDialogue(episodeId){return SCENES[episodeId]?clone(SCENES[episodeId]):null;}
export function getSettlementEpisodeDialogueScene(episodeId,stepId){const scenes=SCENES[episodeId]??[];const scene=scenes.find((entry)=>entry.stepId===stepId);return scene?clone(scene):null;}
export function validateSettlementEpisodeDialogue(){const errors=[];const warnings=[];const seen=new Set();for(const [episodeId,scenes] of Object.entries(SCENES)){if(scenes.length!==8)errors.push(`scene-count:${episodeId}`);for(const scene of scenes){if(seen.has(scene.stepId))errors.push(`duplicate:${scene.stepId}`);seen.add(scene.stepId);if(!text(scene.speaker))errors.push(`speaker:${scene.stepId}`);if(!text(scene.line))errors.push(`line:${scene.stepId}`);if(!['talk','collect','deliver','craft','travel','trade','buy','sell','equip','rest','train','save','interact'].includes(scene.action))errors.push(`action:${scene.stepId}`);if(scene.choices.length!==3)errors.push(`choice-count:${scene.stepId}`);if(new Set(scene.choices.map((choice)=>choice.id)).size!==scene.choices.length)errors.push(`choice-ids:${scene.stepId}`);if(scene.choices.some((choice)=>!text(choice.label)))errors.push(`choice-label:${scene.stepId}`);if(scene.tags.length<4)warnings.push(`tag-depth:${scene.stepId}`);}}return{ok:errors.length===0,errors,warnings};}
export function buildSettlementEpisodeDialogueManifest(){return freeze({version:SETTLEMENT_EPISODE_DIALOGUE_VERSION,sceneCount:Object.values(SCENES).reduce((sum,scenes)=>sum+scenes.length,0),episodes:listSettlementEpisodeDialogue(),validation:validateSettlementEpisodeDialogue()});}
export function resolveSettlementEpisodeDialogueChoice(episodeId,stepId,choiceId){const scene=getSettlementEpisodeDialogueScene(episodeId,stepId);if(!scene)return{ok:false,reason:'unknown-scene'};const choice=scene.choices.find((entry)=>entry.id===choiceId);if(!choice)return{ok:false,reason:'unknown-choice'};return freeze({ok:true,episodeId,stepId,choiceId,action:scene.action,speaker:scene.speaker,label:choice.label,tone:choice.tone,dispatch:{action:scene.action,episodeId,episodeStepId:stepId,dialogueChoiceId:choiceId}});}
export function createSettlementEpisodeDialogueResolver(){const validation=validateSettlementEpisodeDialogue();return Object.freeze({version:SETTLEMENT_EPISODE_DIALOGUE_VERSION,valid:validation.ok,validation:clone(validation),list:listSettlementEpisodeDialogue,get:getSettlementEpisodeDialogue,getScene:getSettlementEpisodeDialogueScene,resolveChoice:resolveSettlementEpisodeDialogueChoice,manifest:buildSettlementEpisodeDialogueManifest});}
