/** Deterministic replay envelope for traversal planning; no authoritative state is stored. */
import { createSettlementWorldCoverageTraversalPlan } from './settlementWorldCoverageTraversal.js';
import { createSettlementWorldCoverageTraversalRisk } from './settlementWorldCoverageTraversalRisk.js';
import { createSettlementWorldCoverageTraversalRoute } from './settlementWorldCoverageTraversalRoute.js';
import { createSettlementWorldCoverageTraversalMilestones } from './settlementWorldCoverageTraversalMilestones.js';
import { createSettlementWorldCoverageTraversalPacing } from './settlementWorldCoverageTraversalPacing.js';
import { createSettlementWorldCoverageTraversalSignals } from './settlementWorldCoverageTraversalSignals.js';
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_REPLAY_VERSION=1;
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_REPLAY_LIMITS=Object.freeze({maxFrames:16,maxInputKeys:20});
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const freeze=(v,s=new Set())=>{if(!v||typeof v!=='object'||s.has(v))return v;s.add(v);Object.freeze(v);for(const x of Object.values(v))freeze(x,s);return v;};
const stable=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(stable).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;
const digest=v=>{let h=2166136261,s=stable(v);for(let i=0;i<s.length;i+=1){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');};
function normalizeInput(input={}){const out={};for(const [k,v] of Object.entries(input??{}).slice(0,20)){if(['number','string','boolean'].includes(typeof v)||v===null)out[k]=v;}return out;}
function frameFromOptions(options,index){const plan=createSettlementWorldCoverageTraversalPlan(options);const risk=createSettlementWorldCoverageTraversalRisk(options);const route=createSettlementWorldCoverageTraversalRoute(options,options.routeMode??'safe');const milestones=createSettlementWorldCoverageTraversalMilestones(options);const pacing=createSettlementWorldCoverageTraversalPacing(options);const signals=createSettlementWorldCoverageTraversalSignals(options);return{index,stage:plan.stage,mode:plan.mode??plan.phase,phase:plan.phase,lane:route.chosenLane,risk:risk.risk,riskSeverity:risk.severity,milestone:milestones.active.name,pacing:pacing.state,primarySignals:signals.primary.map(s=>s.type),readiness:n(plan.readiness,.5)};}
export function createSettlementWorldCoverageTraversalReplay(options={},frames=[]){const base=normalizeInput(options);const input=Array.isArray(frames)?frames.slice(-SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_REPLAY_LIMITS.maxFrames):[];const normalized=input.map((frame,index)=>({...frame,index}));normalized.push(frameFromOptions(options,normalized.length));const payload={version:1,settlementId:options.settlement?.id??'settlement',seed:n(options.seed,0),input:base,frameCount:normalized.length,frames:normalized,latest:normalized.at(-1),ownership:{readOnly:true,noSaveMutation:true,noReplayStateMutation:true}};return freeze({...payload,fingerprint:digest(payload)});}
export function validateSettlementWorldCoverageTraversalReplay(value){const s=value&&typeof value==='object'?value:{};const e=[];if(!s.settlementId)e.push('settlement-id');if(s.frameCount>16)e.push('frame-cap');if(!Array.isArray(s.frames))e.push('frames');if(s.frames?.some(x=>!Number.isFinite(x.index)))e.push('index');if(s.frames?.some(x=>x.risk<0||x.risk>1))e.push('risk');if(!s.ownership?.readOnly||!s.ownership?.noSaveMutation)e.push('ownership');return freeze({ok:e.length===0,errors:e,frameCount:s.frameCount??0,fingerprint:s.fingerprint??digest(s)});}
export function replaySettlementWorldCoverageTraversal(options={},frames=[]){const first=createSettlementWorldCoverageTraversalReplay(options,frames);const second=createSettlementWorldCoverageTraversalReplay(JSON.parse(JSON.stringify(options)),JSON.parse(JSON.stringify(frames)));return freeze({ok:first.fingerprint===second.fingerprint,firstFingerprint:first.fingerprint,secondFingerprint:second.fingerprint});}
export function summarizeSettlementWorldCoverageTraversalReplay(options={},frames=[]){const r=createSettlementWorldCoverageTraversalReplay(options,frames);return freeze({settlementId:r.settlementId,frameCount:r.frameCount,latestStage:r.latest?.stage??null,latestLane:r.latest?.lane??null,latestRisk:r.latest?.risk??0,latestPacing:r.latest?.pacing??null,fingerprint:r.fingerprint});}
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_REPLAY_API=Object.freeze({version:1,maxFrames:16,create:'createSettlementWorldCoverageTraversalReplay',validate:'validateSettlementWorldCoverageTraversalReplay',replay:'replaySettlementWorldCoverageTraversal',summary:'summarizeSettlementWorldCoverageTraversalReplay'});
