/**
 * Settlement navigation and POI selection adapter.
 * Uses authored route IDs and existing map/travel ownership.
 */
import { getSettlementRoute, getSettlementService, listSettlementServices } from './settlementCampaignContent.js';
import { evaluateTravelRule, normalizeRpgSnapshot } from './settlementCampaignRules.js';
export const SETTLEMENT_NAVIGATION_VERSION=1;
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,160):fallback;};
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
export function buildSettlementPoiMenu(snapshot={},options={}){const state=normalizeRpgSnapshot(snapshot);const roles=Array.isArray(options.roles)?options.roles:listSettlementServices();return roles.map(role=>{const service=getSettlementService(role);return service?{id:service.id,label:service.label,kind:service.kind,domain:service.domain,prompt:service.prompt,selected:service.id===options.selected}:null;}).filter(Boolean);}
export function buildSettlementRouteMenu(snapshot={},routeIds=['north_gate','river_market','hill_fort','old_mill','east_road','winter_pass']){const state=normalizeRpgSnapshot(snapshot);return routeIds.map(routeId=>{const route=getSettlementRoute(routeId);if(!route)return null;const rule=evaluateTravelRule(route.id,state,{costRate:state.perks.includes('roadwise')?-0.07:0,fatigueRate:state.perks.includes('roadwise')?-0.07:0});return{...clone(route),available:rule.ok,reason:rule.reason,quote:clone(rule.quote)};}).filter(Boolean);}
export function selectNearestSettlementService(pois=[],preferredDomain=''){const list=Array.isArray(pois)?pois:[];return list.find(p=>text(p.domain)===text(preferredDomain))??list[0]??null;}
export function buildFastTravelRequest(routeId,snapshot={},requestId=''){const route=getSettlementRoute(text(routeId));if(!route)return{ok:false,reason:'unknown-route'};const state=normalizeRpgSnapshot(snapshot);const rule=evaluateTravelRule(route.id,state,{costRate:state.perks.includes('roadwise')?-0.07:0,fatigueRate:state.perks.includes('roadwise')?-0.07:0});if(!rule.ok)return{ok:false,reason:rule.reason,route:clone(route),quote:clone(rule.quote)};return{ok:true,request:{version:1,requestId:text(requestId),action:'travel',routeId:route.id,destination:route.destination,cost:rule.quote.cost,fatigue:rule.quote.fatigue,risk:route.risk,requiresAuthoritativeCommit:true}};}
export function validateFastTravelRequest(request){const errors=[];if(request?.version!==1)errors.push('version');if(!text(request?.requestId))errors.push('request-id');if(request?.action!=='travel')errors.push('action');if(!text(request?.routeId))errors.push('route');if(!text(request?.destination))errors.push('destination');if(Number(request?.cost)<0)errors.push('cost');if(Number(request?.fatigue)<0)errors.push('fatigue');return{ok:errors.length===0,errors};}
export function buildNavigationBreadcrumb(route=[],current=''){const path=(Array.isArray(route)?route:[]).map(text).filter(Boolean).slice(-24);const currentId=text(current);if(currentId&&path.at(-1)!==currentId)path.push(currentId);return path.map((id,index)=>({id,index,active:id===currentId}));}
export function summarizeNavigationState(snapshot={},runtimeView={}){const state=normalizeRpgSnapshot(snapshot);return{version:1,settlementId:state.settlementId,locationId:state.locationId,activeService:runtimeView.activeService?.id??null,panel:runtimeView.panel??'overview',canTravel:state.fatigue<90,copper:state.copper,loadRatio:state.maxCarryWeight?state.carryWeight/state.maxCarryWeight:1};}
export function resolvePoiInteractionTarget(poiId,services=listSettlementServices()){const id=text(poiId);if(!id)return{ok:false,reason:'missing-poi'};if(!services.includes(id))return{ok:false,reason:'unknown-poi'};return{ok:true,poiId:id,service:getSettlementService(id)};}
export function validateNavigationMenu(menu=[]){const errors=[];const ids=new Set();for(const entry of Array.isArray(menu)?menu:[]){if(!entry?.id)errors.push('missing-id');if(ids.has(entry.id))errors.push(`duplicate:${entry.id}`);ids.add(entry.id);if(!entry.label)errors.push(`label:${entry.id}`);}return{ok:errors.length===0,errors};}
