/**
 * Asset-first evidence helpers for settlement placement.
 * This module never loads editor/runtime UI and never fabricates source assets.
 */
export const SETTLEMENT_ASSET_EVIDENCE_VERSION=1;
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,220):fallback;};
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
const ASSET_ROOTS=Object.freeze(['assets/models/settlements','assets/models/houses','assets/models/props','assets/models/fbx','assets/textures','assets/audio','assets/particles','assets/shaders']);
const PLACEMENT_ORDER=Object.freeze(['source-asset','material-assignment','material-validation','placement-validation','ground-alignment','manifest','scene-attachment']);
export function listSettlementAssetRoots(){return[...ASSET_ROOTS];}
export function getSettlementPlacementOrder(){return[...PLACEMENT_ORDER];}
export function classifySettlementAssetPath(assetPath){const path=text(assetPath).replaceAll('\\','/');const root=ASSET_ROOTS.find(value=>path.startsWith(`${value}/`));return{path,root:root??null,valid:Boolean(root),kind:root?.includes('textures')?'texture':root?.includes('audio')?'audio':root?.includes('particles')?'particle':root?.includes('shaders')?'shader':'model'};}
export function buildAssetSourceEvidence(input={}){const classification=classifySettlementAssetPath(input.assetPath);if(!classification.valid)return{ok:false,reason:'unsupported-asset-root',classification};if(text(input.lfsPointer) && text(input.lfsHydrationStatus)!=='hydrated')return{ok:false,reason:'lfs-pointer-not-hydrated',classification};return{ok:true,version:1,sourceAsset:classification.path,root:classification.root,kind:classification.kind,sourcePreserved:true,selectiveHydration:Boolean(input.selectiveHydration),derivedAsset:text(input.derivedAsset),originalAssetOverwritten:false};}
export function buildMaterialPlacementEvidence(input={}){const source=buildAssetSourceEvidence(input);if(!source.ok)return source;const material={slotCount:Math.max(0,Math.trunc(Number(input.slotCount)||0)),palette:[...(Array.isArray(input.palette)?input.palette:[])].slice(0,16).map(text).filter(Boolean),pbr:Boolean(input.pbr),textureSizes:[...(Array.isArray(input.textureSizes)?input.textureSizes:[])].slice(0,16).map(value=>Math.max(1,Math.trunc(Number(value)||1)))};const placement={groundAligned:Boolean(input.groundAligned),slopeCompatible:Boolean(input.slopeCompatible),naturalScale:Boolean(input.naturalScale),orientation:text(input.orientation,'canonical'),spacingValid:Boolean(input.spacingValid)};return{ok:true,version:1,source,...clone({material,placement}),materialContract:'MaterialAssignmentCore',placementContract:'WorldAssetPlacementPipeline',manifestId:text(input.manifestId),sceneAttached:Boolean(input.sceneAttached)};}
export function validateSettlementAssetEvidence(evidence){const errors=[];if(evidence?.ok!==true)errors.push('source');if(!evidence?.source?.sourceAsset)errors.push('source-asset');if(evidence?.source?.sourcePreserved!==true)errors.push('source-overwrite');if(evidence?.source?.originalAssetOverwritten!==false)errors.push('overwrite');if(evidence?.material?.pbr!==true)errors.push('pbr');if(!evidence?.material?.palette?.length)errors.push('palette');if(evidence?.placement?.groundAligned!==true)errors.push('ground');if(evidence?.placement?.naturalScale!==true)errors.push('scale');if(evidence?.placement?.slopeCompatible!==true)errors.push('slope');if(evidence?.placement?.spacingValid!==true)errors.push('spacing');if(evidence?.materialContract!=='MaterialAssignmentCore')errors.push('material-contract');if(evidence?.placementContract!=='WorldAssetPlacementPipeline')errors.push('placement-contract');if(!evidence?.manifestId)errors.push('manifest');return{ok:errors.length===0,errors};}
export function createSettlementAssetPlacementManifest(evidence,context={}){const validation=validateSettlementAssetEvidence(evidence);if(!validation.ok)return{ok:false,errors:validation.errors};return{ok:true,version:1,id:text(context.id,`settlement-asset-${Date.now()}`),source:evidence.source.sourceAsset,derivedAsset:evidence.source.derivedAsset||null,material:{contract:evidence.materialContract,palette:[...evidence.material.palette],slotCount:evidence.material.slotCount,pbr:evidence.material.pbr,textureSizes:[...evidence.material.textureSizes]},placement:{contract:evidence.placementContract,groundAligned:evidence.placement.groundAligned,slopeCompatible:evidence.placement.slopeCompatible,naturalScale:evidence.placement.naturalScale,orientation:evidence.placement.orientation,spacingValid:evidence.placement.spacingValid},manifestProduced:true,sceneAttached:evidence.sceneAttached,order:[...PLACEMENT_ORDER]};}
export function summarizeAssetPlacementManifest(manifest){if(!manifest?.ok)return{ok:false,reason:'invalid-manifest'};return{ok:true,id:text(manifest.id),source:text(manifest.source),paletteCount:manifest.material?.palette?.length??0,slotCount:manifest.material?.slotCount??0,pbr:manifest.material?.pbr===true,groundAligned:manifest.placement?.groundAligned===true,slopeCompatible:manifest.placement?.slopeCompatible===true,naturalScale:manifest.placement?.naturalScale===true,sceneAttached:manifest.sceneAttached===true};}
