/**
 * Read-only dashboard projection for the existing settlement runtime.
 * It turns the current view model into a compact, deterministic service board
 * for HUD, controller and save/load UX without executing actions or mutating state.
 */
export const SETTLEMENT_SERVICE_DASHBOARD_VERSION = 1;
const SERVICE_ORDER = Object.freeze(['gate','tavern','market','blacksmith','farm','barracks','stable','house']);
const text=(v,fallback='')=>{const s=String(v??'').trim();return s?s.slice(0,160):fallback;};
const finite=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f;};
const integer=(v,min,max,f=min)=>Math.max(min,Math.min(max,Math.trunc(finite(v,f))));
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;}
function digest(v){let h=2166136261;const s=stable(v);for(let i=0;i<s.length;i+=1){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;Object.freeze(v);for(const value of Object.values(v))freeze(value);return v;}
function normalizeService(raw,id){const s=raw&&typeof raw==='object'?raw:{};const actions=Array.isArray(s.actions)?[...new Set(s.actions.map(v=>text(v)).filter(Boolean))].slice(0,12):[];return {id,label:text(s.label,id),kind:text(s.kind,'service'),unlocked:Boolean(s.unlocked??s.enabled??true),enabled:Boolean(s.enabled??true),completed:Boolean(s.completed),actions,primaryAction:text(s.primaryAction,actions[0]??'interact'),reason:text(s.reason)};}
export function buildSettlementServiceDashboard(runtimeOrView={},options={}){const view=typeof runtimeOrView?.getViewModel==='function'?runtimeOrView.getViewModel():runtimeOrView;const source=view&&typeof view==='object'?view:{};const rawServices=Array.isArray(source.services)?source.services:Array.isArray(source.serviceBoard)?source.serviceBoard:[];const byId=new Map(rawServices.map(v=>[text(v?.id),v]));const selected=text(options.selectedService??source.activeService?.id);const rows=SERVICE_ORDER.map(id=>{const row=normalizeService(byId.get(id),id);const blocked=!row.unlocked||!row.enabled;return {...row,status:blocked?'blocked':row.completed?'complete':'ready',selected:id===selected,canInteract:!blocked,reason:blocked?(row.reason||(!row.unlocked?'locked':'disabled')):row.reason};});const ready=rows.filter(v=>v.status==='ready').length;const blocked=rows.filter(v=>v.status==='blocked').length;const complete=rows.filter(v=>v.status==='complete').length;const next=rows.find(v=>v.status==='ready')??rows.find(v=>v.status==='blocked')??rows[0];const model={version:SETTLEMENT_SERVICE_DASHBOARD_VERSION,revision:integer(source.revision,0,999999,0),locationId:text(source.locationId||source.nodeId,'settlement'),activeService:selected,rows,summary:{ready,blocked,complete,total:rows.length,focus:next?.id??null},context:{insideSettlement:Boolean(source.insideSettlement??true),defeated:Boolean(source.defeated??false),fatigueBand:text(source.fatigueBand),copper:integer(source.copper,0,999999,0),questCount:integer(source.quests?.length??source.questCount,0,999,0)},digest:''};model.digest=digest({...model,digest:undefined});return freeze(model);}
export function serializeSettlementServiceDashboard(model){return JSON.stringify(model&&typeof model==='object'?model:buildSettlementServiceDashboard());}
export function validateSettlementServiceDashboard(model){const errors=[];if(model?.version!==SETTLEMENT_SERVICE_DASHBOARD_VERSION)errors.push('version');if(!Array.isArray(model?.rows)||model.rows.length!==SERVICE_ORDER.length)errors.push('rows');if(!model?.summary||model.summary.total!==SERVICE_ORDER.length)errors.push('summary');if(typeof model?.digest!=='string'||model.digest.length!==8)errors.push('digest');for(const row of model?.rows??[]){if(!SERVICE_ORDER.includes(row.id))errors.push(`unknown:${row.id}`);if(!['ready','blocked','complete'].includes(row.status))errors.push(`status:${row.id}`);}return {ok:errors.length===0,errors};}
export function buildSettlementServiceDashboardEvidence(runtimeOrView,options={}){const model=buildSettlementServiceDashboard(runtimeOrView,options);return {version:model.version,digest:model.digest,focus:model.summary.focus,ready:model.summary.ready,blocked:model.summary.blocked,complete:model.summary.complete,contract:{readOnly:true,usesExistingRuntime:true,materialPlacementAuthority:'MaterialAssignmentCore+WorldAssetPlacementPipeline',editorStudioRuntimeImport:false}};}
export {SERVICE_ORDER};
