/**
 * Settlement interaction matrix: authored service UX, not a second gameplay owner.
 */
import { getSettlementService, listSettlementServices } from './settlementCampaignContent.js';
import { evaluateActionRule, normalizeRpgSnapshot } from './settlementCampaignRules.js';
export const SETTLEMENT_INTERACTION_MATRIX_VERSION=1;
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,160):fallback;};
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
const OWNERS=Object.freeze({gate:'Travel',blacksmith:'Crafting',tavern:'QuestSystem',market:'Economy',farm:'Survival',barracks:'Progression',stable:'Travel',house:'SaveLoad'});
const ACTIONS=Object.freeze({gate:['enter','exit','travel'],blacksmith:['talk','trade','craft','equip'],tavern:['talk','acceptQuest','advanceQuest','rest'],market:['talk','trade','buy','sell'],farm:['interact','trade','rest','travel'],barracks:['talk','train','acceptQuest','equip'],stable:['talk','trade','travel','rest'],house:['interact','talk','save','rest']});
const EVENT_BY_ACTION=Object.freeze({enter:'settlement:enter',exit:'settlement:exit',travel:'settlement:travel',talk:'settlement:dialogue',trade:'settlement:trade',buy:'settlement:trade',sell:'settlement:trade',craft:'settlement:craft',equip:'settlement:equip',acceptQuest:'settlement:quest',advanceQuest:'settlement:quest',rest:'settlement:rest',train:'settlement:train',interact:'settlement:interact',save:'settlement:save'});
export function listSettlementInteractionRoles(){return listSettlementServices();}
export function getSettlementInteractionRole(role){const service=getSettlementService(text(role));if(!service)return null;return{role:service.id,label:service.label,owner:OWNERS[service.id]??'SettlementVerticalSlice',actions:[...(ACTIONS[service.id]??service.actions)],domain:service.domain,kind:service.kind};}
export function buildSettlementInteractionMatrix(){return{version:1,roles:listSettlementServices().map(getSettlementInteractionRole),events:{...EVENT_BY_ACTION},ownership:{...OWNERS}};}
export function resolveSettlementInteraction(role,action,context={}){const value=getSettlementInteractionRole(role);if(!value)return{ok:false,reason:'unknown-role'};if(!value.actions.includes(action))return{ok:false,reason:'action-not-supported',role,action};const rule=evaluateActionRule(action,{...context,snapshot:normalizeRpgSnapshot(context.snapshot)});return{ok:rule.ok,reason:rule.reason,role,action,owner:value.owner,event:EVENT_BY_ACTION[action],rule:clone(rule)};}
export function validateSettlementInteractionMatrix(matrix=buildSettlementInteractionMatrix()){const errors=[];if(matrix.version!==1)errors.push('version');const seen=new Set();for(const role of matrix.roles??[]){if(!role?.role)errors.push('role-id');if(seen.has(role.role))errors.push(`duplicate-role:${role.role}`);seen.add(role.role);if(!matrix.ownership?.[role.role])errors.push(`owner:${role.role}`);if(!Array.isArray(role.actions)||!role.actions.length)errors.push(`actions:${role.role}`);for(const action of role.actions??[])if(!matrix.events?.[action])errors.push(`event:${action}`);}return{ok:errors.length===0,errors};}
export function buildInteractionPrompt(role,action,context={}){const resolved=resolveSettlementInteraction(role,action,context);if(!resolved.ok)return{ok:false,...resolved};const service=getSettlementService(role);return{ok:true,role,action,title:`${service?.label??role} · ${action}`,owner:resolved.owner,event:resolved.event,ready:true,message:service?.prompt??'Yerleşim işlemini tamamla.'};}
export function createInteractionRequest(role,action,input={},requestId=''){const resolved=getSettlementInteractionRole(role);return{version:1,requestId:text(requestId),role:text(role),action:text(action),owner:resolved?.owner??'',event:EVENT_BY_ACTION[action]??'',input:clone(input),requiresAuthoritativeCommit:true};}
export function validateInteractionRequest(request){const errors=[];if(request?.version!==1)errors.push('version');if(!text(request?.requestId))errors.push('request-id');if(!text(request?.role))errors.push('role');if(!text(request?.action))errors.push('action');if(!request?.owner)errors.push('owner');if(!request?.event)errors.push('event');return{ok:errors.length===0,errors};}
export function summarizeSettlementInteractionHistory(history=[]){const list=Array.isArray(history)?history.slice(-64):[];const byOwner={};for(const entry of list){const owner=text(entry.owner,'unknown');byOwner[owner]=(byOwner[owner]??0)+1;}return{count:list.length,successful:list.filter(v=>v?.ok===true).length,blocked:list.filter(v=>v?.ok===false).length,byOwner};}
