/** Read-only arbitration of traversal signals into bounded player cues. */
import { createSettlementWorldCoverageTraversalPlan } from './settlementWorldCoverageTraversal.js';
import { createSettlementWorldCoverageTraversalRisk } from './settlementWorldCoverageTraversalRisk.js';
import { createSettlementWorldCoverageTraversalRoute } from './settlementWorldCoverageTraversalRoute.js';
import { createSettlementWorldCoverageTraversalPacing } from './settlementWorldCoverageTraversalPacing.js';
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNALS_VERSION=1;
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNAL_TYPES=Object.freeze(['navigate','slow','stop','enter','service','return','observe','resume','weather']);
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNAL_LIMITS=Object.freeze({maxSignals:12,maxPrimary:4});
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const c=v=>Math.max(0,Math.min(1,n(v)));
const freeze=(v,s=new Set())=>{if(!v||typeof v!=='object'||s.has(v))return v;s.add(v);Object.freeze(v);for(const x of Object.values(v))freeze(x,s);return v;};
const stable=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(stable).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;
const digest=v=>{let h=2166136261,s=stable(v);for(let i=0;i<s.length;i+=1){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');};
function signal(type,score,copy,source){return{id:`signal:${type}:${source}`,type,score:Math.round(c(score)*1000)/1000,copy,source};}
function buildSignals(plan,risk,route,pacing){const out=[];out.push(signal('navigate',plan.summary.topScore,'Follow the clearest traversal lane',plan.summary.topLane??'default'));if(risk.severity!=='normal')out.push(signal(risk.risk>.78?'stop':'slow',risk.risk,'Traversal risk requires pacing adjustment',risk.severity));if(route.destination==='gateway'||plan.stage==='departure')out.push(signal('return',.82,'Return toward the settlement gateway','gateway'));if(route.destination&&plan.recommendedService?.serviceId===route.destination)out.push(signal('service',.9,'Continue toward the recommended service',route.destination));if(plan.gatewayState==='available')out.push(signal('enter',.96,'Settlement entry is currently available','gateway'));if(plan.gatewayState==='blocked')out.push(signal('observe',.72,'Observe the boundary before committing','blocked'));if(pacing.state==='recover')out.push(signal('resume',.64,'Recover before continuing the traversal','pacing'));if(pacing.state==='pause')out.push(signal('stop',.88,'Pause until visibility or risk improves','pacing'));if(plan.atmosphere?.weather?.type)out.push(signal('weather',.5,`Current weather: ${plan.atmosphere.weather.type}`,'weather'));return out.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNAL_LIMITS.maxSignals);}
export function createSettlementWorldCoverageTraversalSignals(options={}){const plan=createSettlementWorldCoverageTraversalPlan(options);const risk=createSettlementWorldCoverageTraversalRisk(options);const route=createSettlementWorldCoverageTraversalRoute(options,options.routeMode??'safe');const pacing=createSettlementWorldCoverageTraversalPacing(options);const signals=buildSignals(plan,risk,route,pacing);const payload={version:1,settlementId:plan.settlementId,stage:plan.stage,signals,primary:signals.slice(0,SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNAL_LIMITS.maxPrimary),routeMode:route.mode,topLane:route.chosenLane,pacing:pacing.state,risk:risk.risk,ownership:{readOnly:true,noCueMutation:true,noGameplayMutation:true}};return freeze({...payload,fingerprint:digest(payload)});}
export function validateSettlementWorldCoverageTraversalSignals(value){const s=value&&typeof value==='object'?value:{};const e=[];if(!s.settlementId)e.push('settlement-id');if(!Array.isArray(s.signals)||s.signals.length>SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNAL_LIMITS.maxSignals)e.push('signal-cap');if(s.primary?.length>SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNAL_LIMITS.maxPrimary)e.push('primary-cap');if(s.signals?.some(x=>!SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNAL_TYPES.includes(x.type)))e.push('type');if(s.signals?.some(x=>x.score<0||x.score>1))e.push('score');if(!s.ownership?.readOnly||!s.ownership?.noCueMutation)e.push('ownership');return freeze({ok:e.length===0,errors:e,primaryCount:s.primary?.length??0,fingerprint:s.fingerprint??digest(s)});}
export function summarizeSettlementWorldCoverageTraversalSignals(options={}){const s=createSettlementWorldCoverageTraversalSignals(options);return freeze({settlementId:s.settlementId,stage:s.stage,primary:s.primary.map(x=>x.type),signalCount:s.signals.length,topLane:s.topLane,pacing:s.pacing,risk:s.risk,fingerprint:s.fingerprint});}
export const SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNALS_API=Object.freeze({version:1,types:[...SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNAL_TYPES],maxSignals:12,maxPrimary:4,create:'createSettlementWorldCoverageTraversalSignals',validate:'validateSettlementWorldCoverageTraversalSignals',summary:'summarizeSettlementWorldCoverageTraversalSignals'});
