/**
 * Authored journey metadata for the six settlement episodes.
 * It is a UX/content contract only; interaction is still executed by the
 * existing SettlementCampaignRuntime and existing world/owner systems.
 */
import { getSettlementEpisode } from './settlementEpisodeContent.js';
import { getSettlementService,getSettlementRoute,getSettlementRecipe,getSettlementItem } from './settlementCampaignContent.js';

export const SETTLEMENT_EPISODE_JOURNEY_VERSION=1;
export const SETTLEMENT_EPISODE_JOURNEY_LIMITS=Object.freeze({episodes:6,beats:8,stages:5,text:180});
const DEFINITIONS=Object.freeze({
 iron_and_oath:Object.freeze({entry:Object.freeze({node:'blacksmith',interaction:'enter',panel:'quests',label:'Demirhane'}),npc:Object.freeze({node:'blacksmith',role:'smith',interaction:'talk'}),service:Object.freeze({node:'blacksmith',primary:'craft',secondary:['trade','rest'],panel:'craft'}),world:Object.freeze({node:'gate',route:'east_road',panel:'travel'}),exit:Object.freeze({event:'episode-complete',saveSuggested:true})}),
 market_routes:Object.freeze({entry:Object.freeze({node:'market',interaction:'enter',panel:'trade',label:'Pazar'}),npc:Object.freeze({node:'market',role:'vendor',interaction:'talk'}),service:Object.freeze({node:'market',primary:'trade',secondary:['buy','sell'],panel:'trade'}),world:Object.freeze({node:'gate',route:'river_market',panel:'travel'}),exit:Object.freeze({event:'episode-complete',saveSuggested:true})}),
 road_watch:Object.freeze({entry:Object.freeze({node:'barracks',interaction:'enter',panel:'quests',label:'Kışla'}),npc:Object.freeze({node:'barracks',role:'captain',interaction:'talk'}),service:Object.freeze({node:'barracks',primary:'train',secondary:['equip','talk'],panel:'overview'}),world:Object.freeze({node:'gate',route:'hill_fort',panel:'travel'}),exit:Object.freeze({event:'episode-complete',saveSuggested:true})}),
 hearth_and_home:Object.freeze({entry:Object.freeze({node:'house',interaction:'enter',panel:'overview',label:'Ev'}),npc:Object.freeze({node:'house',role:'resident',interaction:'talk'}),service:Object.freeze({node:'house',primary:'rest',secondary:['save','interact'],panel:'overview'}),world:Object.freeze({node:'gate',route:'north_gate',panel:'travel'}),exit:Object.freeze({event:'episode-complete',saveSuggested:true})}),
 winter_supply:Object.freeze({entry:Object.freeze({node:'farm',interaction:'enter',panel:'overview',label:'Çiftlik'}),npc:Object.freeze({node:'farm',role:'farmer',interaction:'talk'}),service:Object.freeze({node:'farm',primary:'craft',secondary:['trade','rest'],panel:'craft'}),world:Object.freeze({node:'gate',route:'winter_pass',panel:'travel'}),exit:Object.freeze({event:'episode-complete',saveSuggested:true})}),
 stable_master:Object.freeze({entry:Object.freeze({node:'stable',interaction:'enter',panel:'overview',label:'Ahır'}),npc:Object.freeze({node:'stable',role:'stable-master',interaction:'talk'}),service:Object.freeze({node:'stable',primary:'trade',secondary:['rest','talk'],panel:'trade'}),world:Object.freeze({node:'gate',route:'east_road',panel:'travel'}),exit:Object.freeze({event:'episode-complete',saveSuggested:true})}),
});
const clone=(value)=>value==null?value:JSON.parse(JSON.stringify(value));
const freeze=(value)=>{if(!value||typeof value!=='object'||Object.isFrozen(value))return value;Object.freeze(value);for(const nested of Object.values(value))freeze(nested);return value;};
const text=(value,fallback='')=>{const v=String(value??'').trim();return v?v.slice(0,180):fallback;};
const STAGES=Object.freeze(['entry','npc','service','world','exit']);
export function listSettlementEpisodeJourneys(){return Object.keys(DEFINITIONS);}
export function getSettlementEpisodeJourney(episodeId){const definition=DEFINITIONS[episodeId];if(!definition)return null;const episode=getSettlementEpisode(episodeId);return freeze({version:SETTLEMENT_EPISODE_JOURNEY_VERSION,episodeId,title:text(episode?.title,episodeId),summary:text(episode?.summary),contract:'settlement-episode-journey-v1',stages:STAGES.map((stage,index)=>({index,stage,...clone(definition[stage])}))});}
export function getSettlementEpisodeJourneyStage(episodeId,stage){const journey=getSettlementEpisodeJourney(episodeId);if(!journey)return null;return journey.stages.find((entry)=>entry.stage===stage)||null;}
export function buildSettlementEpisodeJourneyCard(episodeId){const journey=getSettlementEpisodeJourney(episodeId);if(!journey)return{ok:false,reason:'unknown-episode'};return freeze({ok:true,episodeId,title:journey.title,summary:journey.summary,stages:journey.stages.map((stage)=>({id:stage.stage,index:stage.index,label:stage.label??text(stage.node),node:stage.node,route:stage.route??null,panel:stage.panel??'overview',interaction:stage.interaction??stage.event??'interact',saveSuggested:Boolean(stage.saveSuggested)}))});}
export function buildSettlementEpisodeJourneyManifest(){return freeze({version:SETTLEMENT_EPISODE_JOURNEY_VERSION,contract:'settlement-episode-journey-v1',episodes:listSettlementEpisodeJourneys().map((id)=>getSettlementEpisodeJourney(id))});}
export function validateSettlementEpisodeJourney(){const errors=[];const required=['entry','npc','service','world','exit'];for(const id of listSettlementEpisodeJourneys()){const definition=DEFINITIONS[id];if(!getSettlementEpisode(id))errors.push(`episode:${id}`);for(const stage of required){if(!definition[stage])errors.push(`stage:${id}:${stage}`);if(!text(definition[stage].node)&&stage!=='exit')errors.push(`node:${id}:${stage}`);}if(!getSettlementService(definition.service.node))errors.push(`service:${id}:${definition.service.node}`);if(!getSettlementRoute(definition.world.route))errors.push(`route:${id}:${definition.world.route}`);if(definition.service.primary==='craft'&&!getSettlementRecipe(id==='iron_and_oath'?'iron_sword':'travel_rations'))errors.push(`recipe:${id}`);if(id==='market_routes'&&!getSettlementItem('bread'))errors.push('market-item');if(id==='stable_master'&&!getSettlementItem('horse_feed'))errors.push('stable-item');}
return{ok:errors.length===0,errors,episodeCount:listSettlementEpisodeJourneys().length};}
export function createSettlementEpisodeJourneyResolver(){const validation=validateSettlementEpisodeJourney();return Object.freeze({version:SETTLEMENT_EPISODE_JOURNEY_VERSION,valid:validation.ok,validation:clone(validation),list:listSettlementEpisodeJourneys,get:getSettlementEpisodeJourney,getStage:getSettlementEpisodeJourneyStage,card:buildSettlementEpisodeJourneyCard,manifest:buildSettlementEpisodeJourneyManifest});}
