/** Deterministic, read-only environment activity context. */
import { createSettlementWorldCoverageTraversalPlan } from './settlementWorldCoverageTraversal.js';
export const WORLD_ACTIVITY_CONTEXT_VERSION=1;
export const WORLD_ACTIVITY_CONTEXT_LIMITS=Object.freeze({maxActivities:12,maxSignals:10,maxDistanceMeters:240,mobileScale:.62});
export const WORLD_ACTIVITY_TYPES=Object.freeze(['travel','camp','trade','craft','guard','farm','gather','observe','rest','social','warning','quiet']);
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const c=v=>Math.max(0,Math.min(1,n(v)));
const t=(v,d='')=>{const s=String(v??'').trim();return s?s.slice(0,120):d;};
const freeze=(v,s=new Set())=>{if(!v||typeof v!=='object'||s.has(v))return v;s.add(v);Object.freeze(v);for(const x of Object.values(v))freeze(x,s);return v;};
const stable=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(stable).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;
const digest=v=>{let h=2166136261,s=stable(v);for(let i=0;i<s.length;i+=1){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');};
const STAGE_ACTIVITY=Object.freeze({far:['travel','observe','gather','quiet'],approach:['travel','observe','guard','gather'],threshold:['travel','guard','social','warning'],inside:['trade','craft','farm','social'],service:['trade','craft','social','rest'],departure:['travel','guard','gather','observe'],resume:['travel','rest','observe','quiet']});
const WEATHER_ACTIVITY=Object.freeze({clear:{travel:1,observe:1,gather:.92,rest:.72},cloud:{travel:.98,observe:.92,gather:.9,rest:.74},fog:{travel:.56,observe:.28,gather:.48,rest:.82},rain:{travel:.62,observe:.52,gather:.58,rest:.9},snow:{travel:.46,observe:.62,gather:.3,rest:.96},storm:{travel:.18,observe:.2,gather:.12,rest:1,warning:1},wind:{travel:.76,observe:.72,gather:.7,rest:.64},sleet:{travel:.42,observe:.48,gather:.24,rest:.94}});
const LANE_ACTIVITY=Object.freeze({gateway:['travel','guard'],market:['trade','social'],tavern:['rest','social'],craft:['craft','trade'],farm:['farm','gather'],military:['guard'],stable:['travel','rest'],home:['rest','social'],river:['gather','observe'],ridge:['observe','travel']});
const weatherType=(options={})=>t(options.weather?.type,'clear').toLowerCase();
const weatherFactor=(w,a)=>WEATHER_ACTIVITY[w]?.[a]??.68;
function weight(a,p,l,w){const s=(STAGE_ACTIVITY[p.stage]??['travel']).includes(a)?.18:0;const b=(LANE_ACTIVITY[l]??[]).includes(a)?.14:0;const risk=c(p.risk?.risk??0);const rp=['travel','gather','observe'].includes(a)?risk*.12:0;return c(.48+s+b-rp+(p.recommendedService?.serviceId==='market'&&a==='trade'?.12:0))*weatherFactor(w,a);}
function activity(type,i,p,l,w,m){const score=Math.round(weight(type,p,l,w)*1000)/1000;const max=Math.max(18,Math.min(240,n(p.player?.distanceMeters,0)+36));const d=Math.round(max*(.25+i*.11)*(m?.62:1)*100)/100;return{id:`${p.settlementId}:activity:${type}:${i+1}`,type,lane:l,score,priority:Math.round((score+(type==='warning'&&w==='storm'?.18:0))*1000)/1000,distanceMeters:Math.min(240,d),weather:w,semantic:p.stage,mobile:m};}
function signals(p,a,w){const s=[];if(p.gatewayState==='available')s.push({type:'entry',score:.96,copy:'Settlement entry is available'});if(p.gatewayState==='blocked')s.push({type:'warning',score:.82,copy:'Boundary access requires caution'});if(w!=='clear')s.push({type:'weather',score:w==='storm'?1:.64,copy:`Weather: ${w}`});for(const x of a.slice(0,4))s.push({type:x.type,score:x.priority,copy:`Suggested activity: ${x.type}`});return s.sort((a,b)=>b.score-a.score||a.type.localeCompare(b.type)).slice(0,10);}
export function createWorldActivityContext(options={}){const mobile=Boolean(options.mobile);const plan=createSettlementWorldCoverageTraversalPlan(options);const lane=plan.lanes.find(x=>x.eligible)?.lane??'gateway';const w=weatherType(options);const types=[...(LANE_ACTIVITY[lane]??[]),...(STAGE_ACTIVITY[plan.stage]??[])];if(w==='storm')types.push('warning');if(w==='snow'||w==='sleet')types.push('rest');const acts=[...new Set(types)].filter(WORLD_ACTIVITY_TYPES.includes).map((x,i)=>activity(x,i,plan,lane,w,mobile)).sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id)).slice(0,mobile?8:12);const sig=signals(plan,acts,w);const p={version:1,settlementId:plan.settlementId,stage:plan.stage,phase:plan.phase,lane,weather:w,mobile,activityCount:acts.length,activities:acts,signals:sig,topActivity:acts[0]?.type??'quiet',readiness:plan.summary.topScore,ownership:{readOnly:true,noActorSpawn:true,noWorldMutation:true,noSaveMutation:true,noTerrainMutation:true,noRoadMutation:true}};return freeze({...p,fingerprint:digest(p)});}
export function validateWorldActivityContext(v){const s=v&&typeof v==='object'?v:{};const e=[];if(!s.settlementId)e.push('settlement-id');if(!WORLD_ACTIVITY_TYPES.includes(s.topActivity))e.push('top-activity');if(!Array.isArray(s.activities)||s.activities.length>12)e.push('activity-cap');if(!Array.isArray(s.signals)||s.signals.length>10)e.push('signal-cap');if(s.activities?.some(a=>a.score<0||a.score>1))e.push('score-range');if(s.activities?.some(a=>a.distanceMeters<0||a.distanceMeters>240))e.push('distance-range');if(!s.ownership?.readOnly||!s.ownership?.noWorldMutation||!s.ownership?.noActorSpawn)e.push('ownership');return freeze({ok:e.length===0,errors:e,fingerprint:s.fingerprint??digest(s),activityCount:s.activities?.length??0});}
export function summarizeWorldActivityContext(o={}){const x=createWorldActivityContext(o);return freeze({settlementId:x.settlementId,stage:x.stage,phase:x.phase,lane:x.lane,weather:x.weather,topActivity:x.topActivity,activityCount:x.activityCount,signalCount:x.signals.length,readiness:x.readiness,fingerprint:x.fingerprint});}
export function replayWorldActivityContext(o={}){const a=createWorldActivityContext(o);const b=createWorldActivityContext(JSON.parse(JSON.stringify(o)));return freeze({ok:a.fingerprint===b.fingerprint,firstFingerprint:a.fingerprint,secondFingerprint:b.fingerprint});}
export const WORLD_ACTIVITY_CONTEXT_API=Object.freeze({version:1,types:[...WORLD_ACTIVITY_TYPES],maxActivities:12,maxSignals:10,create:'createWorldActivityContext',validate:'validateWorldActivityContext',summary:'summarizeWorldActivityContext',replay:'replayWorldActivityContext'});
