// @ts-nocheck
/**
 * Evidence reducer for world opportunities.
 * Keeps proof explainable and stable for debug overlays, QA, and replay review.
 */
import { buildOpportunitySignal, normalizeOpportunityContext, stableHash } from './worldOpportunityPolicy.js';
import { planWorldOpportunitySteps } from './worldOpportunityPlanner.js';
const freeze=(v)=>{if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const x of Object.values(v))freeze(x);return Object.freeze(v);};
export function buildWorldOpportunityEvidence(input={},options={}){const context=normalizeOpportunityContext(input);const plan=planWorldOpportunitySteps({...context,mode:options.mode??'discover'});const evidence=plan.steps.map((step)=>{const signal=buildOpportunitySignal({type:step.opportunityType,rank:step.rank,score:step.utility,access:step.action},context);return freeze({id:signal.id,type:step.opportunityType,rank:step.rank,measurements:freeze({...signal.evidence}),decision:freeze({utility:step.utility,confidence:step.confidence,safetyScore:Number((1-step.costs.risk).toFixed(4)),reachableScore:Number((1-step.costs.distance).toFixed(4))}),ownership:'opportunity-context',deterministic:true});});const checksum=stableHash(JSON.stringify(evidence)).toString(16);return freeze({version:1,count:evidence.length,mode:plan.mode,phase:plan.phase,evidence,checksum});}
export function summarizeOpportunityEvidence(report){const items=Array.isArray(report?.evidence)?report.evidence:[];const mean=items.length?items.reduce((s,x)=>s+x.decision.confidence,0)/items.length:0;const strongest=items.reduce((a,b)=>!a||b.decision.utility>a.decision.utility?b:a,null);return freeze({count:items.length,meanConfidence:Number(mean.toFixed(4)),strongest:strongest?freeze({type:strongest.type,rank:strongest.rank,utility:strongest.decision.utility}):null,deterministic:true});}
export function validateOpportunityEvidence(report){const errors=[];if(!report||report.version!==1)errors.push('invalid-version');if(!Array.isArray(report?.evidence))errors.push('missing-evidence');const seen=new Set();for(const item of report?.evidence??[]){if(seen.has(item.id))errors.push(`duplicate:${item.id}`);seen.add(item.id);for(const value of [item.decision.utility,item.decision.confidence,item.decision.safetyScore,item.decision.reachableScore])if(!(Number.isFinite(value)&&value>=0&&value<=1))errors.push(`out-of-range:${item.id}`);if(item.ownership!=='opportunity-context')errors.push(`ownership:${item.id}`);if(item.deterministic!==true)errors.push(`nondeterministic:${item.id}`);}return freeze({valid:errors.length===0,errors});}
export function buildOpportunityProof(input={},options={}){const report=buildWorldOpportunityEvidence(input,options);const validation=validateOpportunityEvidence(report);const summary=summarizeOpportunityEvidence(report);return freeze({version:1,proofId:`proof-${stableHash(report.checksum).toString(16)}`,valid:validation.valid,errors:validation.errors,summary,checksum:report.checksum});}
