/**
 * World opportunity planner: turns policy scores into deterministic contextual
 * plans. It consumes data only and delegates all mutation to owner systems.
 */
import { buildWorldOpportunitySnapshot, normalizeOpportunityContext, stableHash } from './worldOpportunityPolicy.js';
const freeze=(v)=>{if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const x of Object.values(v))freeze(x);return Object.freeze(v);};
const clamp01=(n)=>Math.max(0,Math.min(1,Number.isFinite(n)?n:0));
const text=(v,d='unknown')=>String(v??d).trim()||d;
export const WORLD_OPPORTUNITY_PLANNER_POLICY=freeze({version:1,maxSteps:8,maxAlternatives:3,modes:['discover','approach','compare','retreat','shelter','observe'],costs:['distance','risk','friction','visibility','weather']});
function normalize(input={}){const c=normalizeOpportunityContext(input);return {...c,mode:text(input.mode,'discover'),energy:clamp01(input.energy??1),urgency:clamp01(input.urgency),confidenceFloor:clamp01(input.confidenceFloor??.25)};}
function modeMultiplier(type,mode){if(mode==='retreat')return ['shelter','rest_window','weather_break'].includes(type)?1.2:.65;if(mode==='shelter')return ['shelter','weather_break','rest_window','quiet_space'].includes(type)?1.25:.6;if(mode==='observe')return ['landmark','watch_point','quiet_space'].includes(type)?1.2:.82;if(mode==='compare')return type==='route_choice'?1.12:.96;if(mode==='approach')return ['landmark','trade_window','resource_patch','shelter'].includes(type)?1.1:.9;return 1;}
function safetyCost(candidate,c){const risk=(c.threatLevel*.55+c.patrolPressure*.25+c.routeFriction*.2);return clamp01(risk*(candidate.type==='danger_edge'?.45:1));}
function stepFor(candidate,c,seed){const risk=safetyCost(candidate,c);const mode=modeMultiplier(candidate.type,c.mode);const distance=Math.min(1,c.distanceMeters/360);const confidence=clamp01(candidate.score*(.7+.3*c.visibility));const utility=clamp01(candidate.score*mode*(1-.32*risk)*(1-.18*distance));return freeze({id:`step-${stableHash(`${seed}:${candidate.type}:${candidate.rank}`)}`,opportunityType:candidate.type,rank:candidate.rank,phase:candidate.phase,utility:Number(utility.toFixed(4)),confidence:Number(confidence.toFixed(4)),costs:freeze({distance:Number(distance.toFixed(4)),risk:Number(risk.toFixed(4)),friction:Number(c.routeFriction.toFixed(4)),visibility:Number((1-c.visibility).toFixed(4))}),action:candidate.access==='weather_gated'?'wait_for_window':candidate.access==='approach'?'approach':'evaluate',rationale:candidate.reason});}
export function planWorldOpportunitySteps(input={},options={}){const c=normalize(input);const snapshot=buildWorldOpportunitySnapshot(c,{maxCandidates:14});const steps=snapshot.candidates.map(x=>stepFor(x,c,c.seed)).filter(x=>x.confidence>=c.confidenceFloor).sort((a,b)=>b.utility-a.utility||a.id.localeCompare(b.id)).slice(0,WORLD_OPPORTUNITY_PLANNER_POLICY.maxSteps);const alternatives=steps.slice(0,3).map((x,i)=>freeze({...x,alternativeRank:i+1}));return freeze({version:1,mode:c.mode,phase:snapshot.phase,steps,alternatives,count:steps.length,deterministicKey:stableHash(JSON.stringify({seed:c.seed,mode:c.mode,phase:snapshot.phase})).toString(16)});}
export function compareOpportunityRoutes(primary={},secondary={}){const a=planWorldOpportunitySteps(primary),b=planWorldOpportunitySteps(secondary);const score=(x)=>x.steps.reduce((sum,s)=>sum+s.utility,0);const pa=score(a),pb=score(b),delta=Number((pa-pb).toFixed(4));return freeze({winner:delta>0?'primary':delta<0?'secondary':'tie',primaryScore:Number(pa.toFixed(4)),secondaryScore:Number(pb.toFixed(4)),delta,comparable:true});}
export function buildOpportunityIntent(input={},selection={}){const c=normalize(input);const snapshot=buildWorldOpportunitySnapshot(c);const candidate=snapshot.candidates.find(x=>x.type===selection.type)??snapshot.candidates[0]??null;if(!candidate)return freeze({accepted:false,reason:'no-candidate'});return freeze({accepted:true,type:candidate.type,rank:candidate.rank,score:candidate.score,mode:c.mode,phase:candidate.phase,intentId:`intent-${stableHash(`${c.seed}:${c.mode}:${candidate.type}:${candidate.rank}`)}`,mutationOwner:'external-authoritative-system',requiresExecution:false});}
