import {R50_DEFAULT_CONFIG,asTick,stableHash} from './contracts.ts';
import type {AssetDescriptor,AssetId,LifecyclePhase,RuntimeConfigR50,RuntimeDiagnostics,RuntimeEvent,RuntimeEventMap,RuntimeMode,RuntimeVersion} from './contracts.ts';

export interface R50ApplicationState{readonly mode:RuntimeMode;readonly lifecycle:LifecyclePhase;readonly player:{readonly id:string;readonly position:{readonly x:number;readonly y:number;readonly z:number};readonly health:number;readonly stamina:number;};readonly world:{readonly loadedChunks:number;readonly timeOfDay:number;readonly weather:string;};readonly session:{readonly id:string;readonly connected:boolean;readonly lastSequence:number;};readonly flags:Readonly<Record<string,boolean>>;}
export interface R50ApplicationOptions{readonly config?:RuntimeConfigR50;readonly browser?:BrowserRuntimeBridge;readonly now?:()=>number;readonly initialState?:R50ApplicationState;}
const DEFAULT_STATE:R50ApplicationState={mode:'booting',lifecycle:'construct',player:{id:'player',position:{x:0,y:0,z:0},health:100,stamina:100},world:{loadedChunks:0,timeOfDay:12,weather:'clear'},session:{id:'offline',connected:false,lastSequence:0},flags:{}};
export class R50Application{
  readonly version:RuntimeVersion=R50_DEFAULT_CONFIG.version;readonly config:RuntimeConfigR50;readonly commandBus:CommandBus;readonly state:StateStore<R50ApplicationState>;readonly scheduler:DeterministicScheduler;readonly assets:AssetRuntime<unknown>;readonly observability:RuntimeObservability;readonly boundary:LegacyBoundaryRegistry;readonly browser:BrowserRuntimeBridge;#running=false;#accumulator=0;#simulated=0;#frames:number[]=[];#disposers:(()=>void)[]=[];
  constructor(options:R50ApplicationOptions={}){this.config=options.config??R50_DEFAULT_CONFIG;const valid=validateConfig(this.config);if(!valid.valid)throw new Error(valid.issues.map(v=>v.path+': '+v.message).join('; '));const clock=options.now??(()=>performance.now());this.commandBus=new CommandBus({execution:this.config.command,clock});this.state=new StateStore({initialState:options.initialState??DEFAULT_STATE,historyLimit:this.config.stateHistoryLimit,freezeState:true,hash:stableHash});this.scheduler=new DeterministicScheduler(this.config.budgets,{clock});this.assets=new AssetRuntime(this.config.assets);this.observability=new RuntimeObservability({clock});this.boundary=new LegacyBoundaryRegistry(undefined,clock);this.browser=options.browser??new BrowserRuntimeBridge();this.#register();}
  get running():boolean{return this.#running;}
  start():void{if(this.#running)return;this.#running=true;this.browser.attach();this.#setLifecycle('prepare','booting');this.#setLifecycle('activate','booting');this.#setLifecycle('running','running');}
  pause():void{if(!this.#running)return;this.state.update(s=>({...s,mode:'paused',lifecycle:'pause'}),'pause');this.#emitLifecycle('pause','paused');}
  resume():void{if(!this.#running)return;this.state.update(s=>({...s,mode:'running',lifecycle:'running'}),'resume');this.#emitLifecycle('running','running');}
  tick(deltaSeconds:number):RuntimeDiagnostics{if(!this.#running)return this.diagnostics();const start=performance.now();this.#accumulator+=Math.max(0,Math.min(.25,deltaSeconds));let steps=0;while(this.#accumulator>=this.config.fixedStepSeconds&&steps<this.config.maxCatchUpSteps){this.#accumulator-=this.config.fixedStepSeconds;this.#simulated+=this.config.fixedStepSeconds;this.state.setTick(asTick(this.scheduler.tick));this.scheduler.runFrame(this.config.fixedStepSeconds,this.state.state.mode);steps+=1;}const frameMs=Math.max(0,performance.now()-start);this.#frames.push(frameMs);while(this.#frames.length>120)this.#frames.shift();this.observability.setGauge('runtime.frameMs',frameMs);this.observability.increment('runtime.frames');return this.diagnostics();}
  shutdown():void{if(!this.#running)return;this.#running=false;this.#setLifecycle('shutdown','stopped');this.state.update(s=>({...s,mode:'stopped',lifecycle:'shutdown'}),'shutdown');for(const dispose of this.#disposers.splice(0))dispose();this.browser.detach();}
  diagnostics():RuntimeDiagnostics{const asset=this.assets.stats();return{mode:this.state.state.mode,clock:{tick:asTick(this.scheduler.tick),frame:this.scheduler.frame,stepSeconds:this.config.fixedStepSeconds,accumulatorSeconds:this.#accumulator,simulatedSeconds:this.#simulated},health:this.observability.health(this.#frames,this.browser.snapshot.width*this.browser.snapshot.height*4,asset.failed,this.observability.counter('network.drops'),this.scheduler.lastReport()?.droppedTasks??0),pendingTasks:this.scheduler.getTaskStats().filter(t=>t.nextDueTick<=this.scheduler.tick).length,queuedCommands:this.commandBus.stats().pending,loadedAssets:asset.ready,bytesInAssets:asset.bytes,networkInFlight:0};}
  registerAsset<T>(descriptor:AssetDescriptor,loader:import('./contracts.ts').AssetLoader<T>):void{validateAssetDescriptor(descriptor);this.assets.register(descriptor);this.assets.registerLoader(descriptor.kind,loader as import('./contracts.ts').AssetLoader<unknown>);}
  async loadAsset<T>(id:AssetId):Promise<T|undefined>{await this.assets.request(id,this.scheduler.tick);return this.assets.get(id)?.value as T|undefined;}
  async invokeLegacy<A,R>(id:string,args:A):Promise<R>{return(await this.boundary.invoke<A,R>(id,args)).result;}
  on<K extends keyof RuntimeEventMap>(type:K,listener:(event:RuntimeEvent<K>)=>void):()=>void{return this.observability.on(type,listener);}
  #register():void{this.#disposers.push(this.commandBus.register('runtime:set-mode',{handle:async command=>{const mode=command.payload as RuntimeMode;this.state.update(s=>({...s,mode,lifecycle:this.#phase(mode)}),'command:runtime:set-mode');return mode;}}));this.#disposers.push(this.commandBus.register('player:set-transform',{handle:async command=>{const p=command.payload as {readonly x:number;readonly y:number;readonly z:number};this.state.update(s=>({...s,player:{...s.player,position:p}}),'command:player:set-transform',['player.position']);return p;}}));const task=this.scheduler.schedule({id:'r50-world-clock',lane:'simulation',priority:'critical',intervalTicks:1,maxRunsPerFrame:1,workEstimate:1,run:context=>{const next=(this.state.state.world.timeOfDay+context.deltaSeconds/60)%24;this.state.update(s=>({...s,world:{...s.world,timeOfDay:next}}),'system:world-clock',['world.timeOfDay']);return{completed:true,cost:{milliseconds:0,workUnits:1},yielded:false};}});this.#disposers.push(()=>this.scheduler.cancel(task));this.#disposers.push(this.boundary.register({descriptor:R50_LEGACY_BOUNDARY_MANIFEST[0]!,invoke:async args=>args}));}
  #phase(mode:RuntimeMode):LifecyclePhase{return mode==='running'?'running':mode==='paused'?'pause':mode==='recovering'?'recover':mode==='stopped'||mode==='stopping'?'shutdown':'construct';}
  #setLifecycle(phase:LifecyclePhase,mode:RuntimeMode):void{this.state.update(s=>({...s,mode,lifecycle:phase}),'lifecycle:'+phase,['mode','lifecycle']);this.#emitLifecycle(phase,mode);}
  #emitLifecycle(phase:LifecyclePhase,mode:RuntimeMode):void{this.observability.emit({type:'lifecycle',tick:asTick(this.scheduler.tick),payload:{phase,mode}});}
}
