import {RuntimeError} from './contracts.ts';
import type {AssetDescriptor,AssetId,AssetLoader,AssetRecord,AssetRequestReceipt,AssetRuntimeOptions,AssetState,TaskPriority,Tick} from './contracts.ts';

interface Entry<T>{descriptor:AssetDescriptor;state:AssetState;value?:T;bytes:number;accessCount:number;lastAccessTick:Tick;errorMessage?:string;inFlight?:Promise<AssetRequestReceipt>;controller?:AbortController;}
export interface AssetRuntimeStats{readonly records:number;readonly ready:number;readonly loading:number;readonly failed:number;readonly stale:number;readonly evicted:number;readonly bytes:number;readonly budgetBytes:number;}
const SCORE:Record<TaskPriority,number>={critical:5,high:4,normal:3,low:2,background:1};
export class AssetRuntime<T>{
  readonly #entries=new Map<AssetId,Entry<T>>();readonly #loaders=new Map<string,AssetLoader<T>>();readonly #options:AssetRuntimeOptions;#currentBytes=0;
  constructor(options:AssetRuntimeOptions){this.#options=options;}
  registerLoader(kind:string,loader:AssetLoader<T>):()=>void{if(this.#loaders.has(kind))throw new RuntimeError({code:'R50_ASSET_LOADER_DUPLICATE',message:'Asset loader already registered: '+kind});this.#loaders.set(kind,loader);return()=>this.#loaders.delete(kind);}
  register(d:AssetDescriptor):void{if(d.maxBytes<=0)throw new RuntimeError({code:'R50_ASSET_LIMIT',message:'Asset maxBytes must be positive'});if(/^(javascript:|data:text\/html)/i.test(d.url))throw new RuntimeError({code:'R50_ASSET_URL',message:'Unsafe asset URL',recoverable:false});const old=this.#entries.get(d.id);if(old&&old.descriptor.version>d.version)throw new RuntimeError({code:'R50_ASSET_VERSION',message:'Cannot register an older asset version'});this.#entries.set(d.id,{descriptor:d,state:old?.value===undefined?'idle':'stale',value:old?.value,bytes:old?.bytes??0,accessCount:old?.accessCount??0,lastAccessTick:old?.lastAccessTick??(0 as Tick)});}
  async request(id:AssetId,tick:Tick,signal?:AbortSignal):Promise<AssetRequestReceipt>{const e=this.#entries.get(id);if(!e)throw new RuntimeError({code:'R50_ASSET_UNKNOWN',message:'Unknown asset: '+String(id)});e.lastAccessTick=tick;e.accessCount+=1;if(e.state==='ready'&&e.value!==undefined)return{assetId:id,state:'ready',deduplicated:false,bytes:e.bytes};if(e.inFlight)return e.inFlight;const loader=this.#loaders.get(e.descriptor.kind);if(!loader){e.state='failed';e.errorMessage='No loader registered for kind '+e.descriptor.kind;throw new RuntimeError({code:'R50_ASSET_LOADER_MISSING',message:e.errorMessage});}e.state='loading';const c=new AbortController();e.controller=c;if(signal){if(signal.aborted)c.abort(signal.reason);else signal.addEventListener('abort',()=>c.abort(signal.reason),{once:true});}const promise=this.#load(e,loader,c.signal,tick);e.inFlight=promise;try{return await promise;}finally{e.inFlight=undefined;e.controller=undefined;}}
  get(id:AssetId):AssetRecord<T>|null{const e=this.#entries.get(id);if(!e)return null;return{descriptor:e.descriptor,state:e.state,...(e.value===undefined?{}:{value:e.value}),bytes:e.bytes,accessCount:e.accessCount,lastAccessTick:e.lastAccessTick,...(e.errorMessage===undefined?{}:{errorMessage:e.errorMessage})};}
  markStale(id:AssetId):boolean{const e=this.#entries.get(id);if(!e)return false;e.controller?.abort();if(e.value!==undefined)e.state='stale';return true;}
  evict(id:AssetId):boolean{const e=this.#entries.get(id);if(!e||e.state==='loading')return false;this.#dispose(e);this.#entries.delete(id);return true;}
  collect(tick:Tick):readonly AssetId[]{const evicted:AssetId[]=[];const candidates=[...this.#entries.values()].filter(e=>e.state!=='loading'&&e.state!=='idle').sort((a,b)=>this.#score(b,tick)-this.#score(a,tick));while(this.#currentBytes>this.#options.byteBudget&&candidates.length){const e=candidates.shift();if(!e)break;this.#dispose(e);this.#entries.delete(e.descriptor.id);evicted.push(e.descriptor.id);}while(this.#entries.size>this.#options.recordLimit){const e=[...this.#entries.values()].filter(v=>v.state!=='loading').sort((a,b)=>this.#score(b,tick)-this.#score(a,tick))[0];if(!e)break;this.#dispose(e);this.#entries.delete(e.descriptor.id);evicted.push(e.descriptor.id);}return evicted;}
  cancel(id:AssetId):boolean{const e=this.#entries.get(id);if(!e?.controller)return false;e.controller.abort(new RuntimeError({code:'R50_ASSET_CANCELLED',message:'Asset request cancelled'}));return true;}
  stats():AssetRuntimeStats{let ready=0,loading=0,failed=0,stale=0,evicted=0;for(const e of this.#entries.values()){ready+=Number(e.state==='ready');loading+=Number(e.state==='loading');failed+=Number(e.state==='failed');stale+=Number(e.state==='stale');evicted+=Number(e.state==='evicted');}return{records:this.#entries.size,ready,loading,failed,stale,evicted,bytes:this.#currentBytes,budgetBytes:this.#options.byteBudget};}
  #score(e:Entry<T>,tick:Tick):number{const age=Math.max(0,tick-e.lastAccessTick);return age*2+(e.state==='stale'?5:0)+Math.max(1,e.bytes/1048576)-SCORE[e.descriptor.priority]*3-e.accessCount*.1;}
  async #load(e:Entry<T>,loader:AssetLoader<T>,signal:AbortSignal,tick:Tick):Promise<AssetRequestReceipt>{try{const result=await loader.load(e.descriptor,signal);if(result.bytes>e.descriptor.maxBytes)throw new RuntimeError({code:'R50_ASSET_TOO_LARGE',message:'Asset exceeded declared limit',recoverable:false});const prev=e.bytes;e.value=result.value;e.bytes=Math.max(0,result.bytes);e.lastAccessTick=tick;e.state='ready';e.errorMessage=undefined;this.#currentBytes+=e.bytes-prev;if(this.#currentBytes>this.#options.byteBudget)this.collect(tick);return{assetId:e.descriptor.id,state:'ready',deduplicated:false,bytes:e.bytes};}catch(error){e.state='failed';e.errorMessage=error instanceof Error?error.message:String(error);throw error;}}
  #dispose(e:Entry<T>):void{this.#loaders.get(e.descriptor.kind)?.dispose?.(e.value as T);this.#currentBytes=Math.max(0,this.#currentBytes-e.bytes);e.value=undefined;e.bytes=0;e.state='evicted';}
}
