import {RuntimeError,asSequence,asSessionId} from './contracts.ts';
import type {NetworkAckWindow,NetworkChannel,NetworkPacket,NetworkReceipt,NetworkSessionOptions,NetworkTransport,PredictionFrame,ReconciliationResult,Sequence,SessionId,Tick} from './contracts.ts';

interface Sent<T>{readonly packet:NetworkPacket<T>;lastSentTick:Tick;attempts:number;}
export interface NetworkStats{readonly sent:number;readonly received:number;readonly dropped:number;readonly retransmits:number;readonly inFlight:number;readonly bufferedInputs:number;readonly highestReceived:Sequence;}
export interface ReconciliationAdapter<TState>{readonly hash:(state:TState)=>string;readonly simulate:(state:TState,input:unknown)=>TState;}
export class NetworkSessionRuntime<TPayload,TInput,TState>{
  readonly #sessionId:SessionId;readonly #options:NetworkSessionOptions;readonly #transport:NetworkTransport<TPayload>;readonly #sent=new Map<Sequence,Sent<TPayload>>();readonly #received=new Set<Sequence>();readonly #predictions:PredictionFrame<TInput,TState>[]=[];
  #next:Sequence=asSequence(1);#highest:Sequence=asSequence(0);#sentCount=0;#receivedCount=0;#dropped=0;#retransmits=0;#inputs=0;
  constructor(sessionId:SessionId,options:NetworkSessionOptions,transport:NetworkTransport<TPayload>){this.#sessionId=sessionId;this.#options=options;this.#transport=transport;}
  get sessionId():SessionId{return this.#sessionId;}
  send(channel:NetworkChannel,payload:TPayload,tick:Tick):NetworkReceipt{if(this.#sent.size>=this.#options.maxInFlight){this.#dropped+=1;return{accepted:false,dropped:true,reason:'in-flight-limit'};}const bytes=this.#bytes(payload);if(bytes>this.#options.maxPacketBytes){this.#dropped+=1;return{accepted:false,dropped:true,reason:'packet-size-limit'};}const packet:NetworkPacket<TPayload>={sessionId:this.#sessionId,sequence:this.#next,channel,tick,payload,acknowledgedSequence:this.#highest};this.#next=asSequence(this.#next+1);this.#sent.set(packet.sequence,{packet,lastSentTick:tick,attempts:1});this.#transport.send(packet);this.#sentCount+=1;return{accepted:true,dropped:false,sequence:packet.sequence};}
  receive(packet:NetworkPacket<TPayload>,tick:Tick):NetworkReceipt{void tick;if(packet.sessionId!==this.#sessionId){this.#dropped+=1;return{accepted:false,dropped:true,reason:'session-mismatch'};}if(this.#bytes(packet.payload)>this.#options.maxPacketBytes){this.#dropped+=1;return{accepted:false,dropped:true,reason:'packet-size-limit'};}if(this.#received.has(packet.sequence))return{accepted:true,dropped:false,sequence:packet.sequence};this.#received.add(packet.sequence);if(packet.sequence>this.#highest)this.#highest=packet.sequence;this.#receivedCount+=1;if(packet.acknowledgedSequence!==undefined)this.acknowledgeThrough(packet.acknowledgedSequence);this.#trimReceived();return{accepted:true,dropped:false,sequence:packet.sequence};}
  acknowledgeThrough(sequence:Sequence):void{for(const key of this.#sent.keys())if(key<=sequence)this.#sent.delete(key);}
  pump(tick:Tick):number{let count=0;for(const entry of this.#sent.values())if(tick-entry.lastSentTick>=this.#options.resendAfterTicks&&entry.attempts<4){this.#transport.send(entry.packet);entry.lastSentTick=tick;entry.attempts+=1;this.#retransmits+=1;count+=1;}return count;}
  recordPrediction(sequence:Sequence,tick:Tick,input:TInput,before:TState,after:TState,stateHash:string):void{this.#predictions.push({sequence,tick,input,stateBefore:before,stateAfter:after,stateHash});while(this.#predictions.length>this.#options.inputBufferLimit)this.#predictions.shift();}
  input(input:TInput,tick:Tick):Sequence{const seq=this.#next;this.#next=asSequence(this.#next+1);this.#inputs=Math.min(this.#options.inputBufferLimit,this.#inputs+1);void input;void tick;return seq;}
  reconcile(authoritative:TState,sequence:Sequence,adapter:ReconciliationAdapter<TState>):ReconciliationResult<TState>{const anchor=this.#predictions.find(v=>v.sequence===sequence);if(!anchor)return{reconciled:false,rollbackFrames:0,authoritative,predicted:authoritative};if(adapter.hash(anchor.stateAfter)===adapter.hash(authoritative))return{reconciled:false,rollbackFrames:0,authoritative,predicted:anchor.stateAfter};let predicted=authoritative,rollbackFrames=0;for(const frame of this.#predictions)if(frame.sequence>sequence){predicted=adapter.simulate(predicted,frame.input);rollbackFrames+=1;}return{reconciled:true,rollbackFrames,authoritative,predicted};}
  ackWindow(size=32):NetworkAckWindow{const recent:Sequence[]=[];const missing:Sequence[]=[];const start=Math.max(1,this.#highest-size+1);for(let n=start;n<=this.#highest;n+=1){const seq=asSequence(n);if(this.#received.has(seq))recent.push(seq);else missing.push(seq);}return{highestReceived:this.#highest,recent,missing};}
  stats():NetworkStats{return{sent:this.#sentCount,received:this.#receivedCount,dropped:this.#dropped,retransmits:this.#retransmits,inFlight:this.#sent.size,bufferedInputs:this.#inputs,highestReceived:this.#highest};}
  close():void{this.#transport.close?.();this.#sent.clear();this.#predictions.length=0;this.#inputs=0;}
  #trimReceived():void{const min=Math.max(1,this.#highest-256);for(const seq of this.#received)if(seq<min)this.#received.delete(seq);}
  #bytes(payload:unknown):number{try{const json=JSON.stringify(payload);return json===undefined?0:new TextEncoder().encode(json).byteLength;}catch(error){throw new RuntimeError({code:'R50_NETWORK_SERIALIZE',message:'Network payload is not serializable',cause:error});}}
}
export class LoopbackTransport<T> implements NetworkTransport<T>{#closed=false;constructor(readonly receive:(packet:NetworkPacket<T>)=>void){}send(packet:NetworkPacket<T>):void{if(!this.#closed)this.receive(packet);}close():void{this.#closed=true;}}
export function createSessionId(seed:string):SessionId{const value=seed.trim().replace(/[^a-zA-Z0-9._-]/g,'-').slice(0,64);if(!value)throw new RuntimeError({code:'R50_SESSION_ID',message:'Session seed cannot be empty'});return asSessionId('r50:'+value);}
