import type { EntityId, FrameId, TickId, Vec3 } from './liveCoreTypes.ts';
import { clamp, frameId, stableHash, tickId } from './liveCoreTypes.ts';

export type StreamZone='critical'|'near'|'mid'|'far';
export type StreamState='unloaded'|'queued'|'loading'|'resident'|'hibernating'|'unloading'|'failed';
export interface StreamRegion { readonly key:string; readonly x:number; readonly z:number; readonly radius:number; readonly zone:StreamZone; readonly priority:number; }
export interface StreamRecord { readonly key:string; readonly region:StreamRegion; readonly state:StreamState; readonly lastTouchedTick:TickId; readonly residentBytes:number; readonly version:number; readonly owner?:EntityId; readonly failures:number; }
export interface StreamPolicy { readonly criticalRadius:number; readonly nearRadius:number; readonly midRadius:number; readonly farRadius:number; readonly hysteresis:number; readonly maxResidentRegions:number; readonly maxConcurrentLoads:number; readonly maxResidentBytes:number; readonly staleTicks:number; }
export interface StreamPlan { readonly frame:FrameId; readonly center:Vec3; readonly desired:readonly StreamRegion[]; readonly loads:readonly StreamRegion[]; readonly unloads:readonly string[]; readonly digest:string; }
export const DEFAULT_STREAM_POLICY:StreamPolicy=Object.freeze({criticalRadius:1,nearRadius:2,midRadius:4,farRadius:7,hysteresis:.75,maxResidentRegions:128,maxConcurrentLoads:8,maxResidentBytes:512*1024*1024,staleTicks:300});

const key=(x:number,z:number)=>x+':'+z;
const zoneFor=(distance:number,p:StreamPolicy):StreamZone=>distance<=p.criticalRadius?'critical':distance<=p.nearRadius?'near':distance<=p.midRadius?'mid':'far';
const zonePriority=(zone:StreamZone)=>zone==='critical'?1000:zone==='near'?600:zone==='mid'?250:80;

export const buildStreamRegions=(center:Vec3,regionSize:number,policy:StreamPolicy=DEFAULT_STREAM_POLICY):readonly StreamRegion[]=>{const max=Math.ceil(policy.farRadius),cx=Math.floor(center.x/regionSize),cz=Math.floor(center.z/regionSize),regions:StreamRegion[]=[];for(let x=cx-max;x<=cx+max;x++){for(let z=cz-max;z<=cz+max;z++){const dx=x-cx,dz=z-cz,distance=Math.hypot(dx,dz);if(distance>policy.farRadius)continue;const zone=zoneFor(distance,policy);regions.push(Object.freeze({key:key(x,z),x,z,radius:regionSize,zone,priority:zonePriority(zone)-distance*10}));}}return Object.freeze(regions.sort((a,b)=>b.priority-a.priority||a.key.localeCompare(b.key)));};

export class StrictStreamingRuntime {
  #policy:StreamPolicy; #regionSize:number; #records=new Map<string,StreamRecord>(); #loadsInFlight=0; #residentBytes=0; #disposed=false;
  constructor(regionSize=256,policy:StreamPolicy=DEFAULT_STREAM_POLICY){this.#regionSize=Math.max(1,regionSize);this.#policy=Object.freeze({...policy});}
  plan(frame:number,center:Vec3,velocity:Vec3,owner?:EntityId):StreamPlan{if(this.#disposed)return Object.freeze({frame:frameId(frame),center,desired:[],loads:[],unloads:[],digest:stableHash({disposed:true})});const predictive={x:center.x+velocity.x*.5,z:center.z+velocity.z*.5,y:center.y};const desired=buildStreamRegions(predictive,this.#regionSize,this.#policy);const desiredKeys=new Set(desired.map(r=>r.key));const loads=desired.filter(r=>{const record=this.#records.get(r.key);return !record||record.state==='unloaded'||record.state==='failed';});const resident=[...this.#records.values()].filter(r=>r.state==='resident'||r.state==='loading');const unloads=resident.filter(r=>!desiredKeys.has(r.key)&&Number(tickId(frame))-Number(r.lastTouchedTick)>this.#policy.staleTicks).sort((a,b)=>a.region.priority-b.region.priority||a.key.localeCompare(b.key)).map(r=>r.key);const limitedLoads=loads.slice(0,Math.max(0,this.#policy.maxConcurrentLoads-this.#loadsInFlight));return Object.freeze({frame:frameId(frame),center,desired,loads:Object.freeze(limitedLoads),unloads:Object.freeze(unloads),digest:stableHash({frame,center,desired:desired.map(r=>r.key),loads:limitedLoads.map(r=>r.key),unloads})});}
  enqueue(region:StreamRegion,tick:number,owner?:EntityId):boolean{if(this.#disposed)return false;const existing=this.#records.get(region.key);if(existing&&(existing.state==='resident'||existing.state==='loading'))return false;if(this.#loadsInFlight>=this.#policy.maxConcurrentLoads)return false;this.#loadsInFlight++;this.#records.set(region.key,Object.freeze({key:region.key,region,state:'loading',lastTouchedTick:tickId(tick),residentBytes:0,version:(existing?.version??0)+1,failures:existing?.failures??0,...(owner?{owner}:{} )}));return true;}
  complete(regionKey:string,residentBytes:number,tick:number):boolean{const record=this.#records.get(regionKey);if(!record||record.state!=='loading')return false;this.#loadsInFlight=Math.max(0,this.#loadsInFlight-1);const bytes=Math.max(0,Math.floor(residentBytes));if(this.#residentBytes+bytes>this.#policy.maxResidentBytes){this.fail(regionKey,'resident-budget',tick);return false;}this.#residentBytes+=bytes;this.#records.set(regionKey,Object.freeze({...record,state:'resident',lastTouchedTick:tickId(tick),residentBytes:bytes}));return true;}
  fail(regionKey:string,message:string,tick:number):boolean{const record=this.#records.get(regionKey);if(!record)return false;this.#loadsInFlight=record.state==='loading'?Math.max(0,this.#loadsInFlight-1):this.#loadsInFlight;this.#records.set(regionKey,Object.freeze({...record,state:'failed',lastTouchedTick:tickId(tick),failures:record.failures+1}));void message;return true;}
  touch(regionKey:string,tick:number){const record=this.#records.get(regionKey);if(!record)return;this.#records.set(regionKey,Object.freeze({...record,lastTouchedTick:tickId(tick)}));}
  unload(regionKey:string,tick:number):boolean{const record=this.#records.get(regionKey);if(!record)return false;this.#residentBytes=Math.max(0,this.#residentBytes-record.residentBytes);this.#records.set(regionKey,Object.freeze({...record,state:'unloaded',lastTouchedTick:tickId(tick),residentBytes:0}));return true;}
  record(regionKey:string):StreamRecord|null{return this.#records.get(regionKey)??null;}
  records():readonly StreamRecord[]{return Object.freeze([...this.#records.values()].sort((a,b)=>a.key.localeCompare(b.key)));}
  diagnostics(){return Object.freeze({residentBytes:this.#residentBytes,loadsInFlight:this.#loadsInFlight,resident:[...this.#records.values()].filter(r=>r.state==='resident').length,loading:[...this.#records.values()].filter(r=>r.state==='loading').length,failed:[...this.#records.values()].filter(r=>r.state==='failed').length,digest:stableHash(this.records().map(r=>({key:r.key,state:r.state,bytes:r.residentBytes,version:r.version})))});}
  dispose(){this.#disposed=true;this.#records.clear();this.#loadsInFlight=0;this.#residentBytes=0;}
}