import type{AiDecision,AiStimulus}from'./contracts';
export interface UtilityAction{readonly id:string;readonly baseScore:number;readonly urgencyWeight:number;readonly threatWeight:number;readonly confidenceWeight:number;readonly cooldownTicks:number;}
interface Actor{readonly id:string;lastDecisionTick:number;cooldowns:Map<string,number>;stimuli:Map<string,AiStimulus>;}
export class BoundedAiDirector{
 readonly maxActors:number;readonly maxStimuliPerActor:number;readonly maxDecisionsPerTick:number;readonly retentionTicks:number;#actors=new Map<string,Actor>();#actions=new Map<string,UtilityAction>();
 constructor(options:{readonly maxActors?:number;readonly maxStimuliPerActor?:number;readonly maxDecisionsPerTick?:number;readonly retentionTicks?:number}={}){this.maxActors=Math.max(1,Math.trunc(options.maxActors??4096));this.maxStimuliPerActor=Math.max(8,Math.trunc(options.maxStimuliPerActor??64));this.maxDecisionsPerTick=Math.max(1,Math.trunc(options.maxDecisionsPerTick??128));this.retentionTicks=Math.max(1,Math.trunc(options.retentionTicks??300));}
 registerAction(a:UtilityAction){if(!a.id||this.#actions.has(a.id))return false;this.#actions.set(a.id,Object.freeze({...a,baseScore:clamp(a.baseScore,-1,1)}));return true;}
 ensureActor(id:string){if(this.#actors.has(id))return true;if(this.#actors.size>=this.maxActors)return false;this.#actors.set(id,{id,lastDecisionTick:-1,cooldowns:new Map(),stimuli:new Map()});return true;}
 ingest(actorId:string,stimulus:AiStimulus){if(!this.ensureActor(actorId))return false;const actor=this.#actors.get(actorId)!;if(actor.stimuli.size>=this.maxStimuliPerActor&&!actor.stimuli.has(stimulus.id)){const oldest=[...actor.stimuli.values()].sort((a,b)=>a.tick-b.tick||a.id.localeCompare(b.id))[0];if(oldest)actor.stimuli.delete(oldest.id);}actor.stimuli.set(stimulus.id,Object.freeze({...stimulus,confidence:clamp(stimulus.confidence,0,1),urgency:clamp(stimulus.urgency,0,1)}));return true;}
 decide(tick:number):readonly AiDecision[]{const out:AiDecision[]=[];for(const actor of[...this.#actors.values()].sort((a,b)=>a.id.localeCompare(b.id))){if(out.length>=this.maxDecisionsPerTick)break;this.prune(actor,tick);const stimuli=[...actor.stimuli.values()];let best:{action:UtilityAction;score:number;ids:string[]}|null=null;for(const action of this.#actions.values()){if((actor.cooldowns.get(action.id)??-1)>tick)continue;const score=this.score(action,stimuli);if(!best||score>best.score||(score===best.score&&action.id<best.action.id))best={action,score,ids:stimuli.map(s=>s.id).sort()};}if(best){const decision=Object.freeze({actorId:actor.id,action:best.action.id,score:best.score,expiresTick:tick+Math.max(1,best.action.cooldownTicks),stimulusIds:Object.freeze(best.ids)});actor.lastDecisionTick=tick;actor.cooldowns.set(best.action.id,decision.expiresTick);out.push(decision);}}return Object.freeze(out);}
 actorCount(){return this.#actors.size;}actionCount(){return this.#actions.size;}
 private score(a:UtilityAction,s:readonly AiStimulus[]){let urgency=0,threat=0,confidence=0;for(const x of s){urgency=Math.max(urgency,x.urgency);confidence=Math.max(confidence,x.confidence);if(x.kind==='threat'||x.kind==='damage')threat=Math.max(threat,x.urgency);}return a.baseScore+urgency*a.urgencyWeight+threat*a.threatWeight+confidence*a.confidenceWeight;}
 private prune(a:Actor,tick:number){for(const s of a.stimuli.values())if(tick-s.tick>this.retentionTicks)a.stimuli.delete(s.id);for(const[id,expires]of a.cooldowns)if(expires<=tick)a.cooldowns.delete(id);}
}
function clamp(v:number,min:number,max:number){return Number.isFinite(v)?Math.max(min,Math.min(max,v)):min;}
