import type{AssetRequest,AssetResident}from'./contracts';
interface Node extends AssetRequest{state:'queued'|'loading'|'resident'|'failed';dependents:Set<string>;remaining:number;requestedTick:number;}
export class BoundedAssetGraph{
 readonly maxResidentBytes:number;readonly maxRequests:number;readonly maxLoadsPerTick:number;#nodes=new Map<string,Node>();#resident=new Map<string,AssetResident>();#bytes=0;
 constructor(options:{readonly maxResidentBytes?:number;readonly maxRequests?:number;readonly maxLoadsPerTick?:number}={}){this.maxResidentBytes=Math.max(16*1024*1024,Math.trunc(options.maxResidentBytes??512*1024*1024));this.maxRequests=Math.max(64,Math.trunc(options.maxRequests??8192));this.maxLoadsPerTick=Math.max(1,Math.trunc(options.maxLoadsPerTick??8));}
 register(request:AssetRequest,tick:number){if(!request.id||request.bytes<=0||this.#nodes.size>=this.maxRequests&&!this.#nodes.has(request.id)||request.dependencies.includes(request.id))return false;const existing=this.#nodes.get(request.id);if(existing)return existing.bytes===request.bytes&&existing.cacheKey===request.cacheKey;const node:Node={...request,state:'queued',dependents:new Set(),remaining:0,requestedTick:tick};this.#nodes.set(request.id,node);for(const depId of request.dependencies){const dep=this.#nodes.get(depId);if(dep)dep.dependents.add(request.id);node.remaining+=dep?.state==='resident'?0:1;}if(!this.acyclic(request.id)){this.#nodes.delete(request.id);return false;}return true;}
 plan(){const candidates=[...this.#nodes.values()].filter(n=>n.state==='queued'&&n.remaining===0).sort((a,b)=>priority(b.priority)-priority(a.priority)||a.requestedTick-b.requestedTick||a.id.localeCompare(b.id)).slice(0,this.maxLoadsPerTick);for(const n of candidates)n.state='loading';return Object.freeze(candidates.map(n=>Object.freeze({id:n.id,url:n.url,bytes:n.bytes,priority:n.priority,dependencies:Object.freeze([...n.dependencies]),required:n.required,cacheKey:n.cacheKey})));}
 markResident(id:string,version:string,bytes:number,tick:number){const node=this.#nodes.get(id);if(!node||node.state!=='loading'||bytes!==node.bytes)return false;this.#resident.set(id,Object.freeze({id,bytes,lastUsedTick:tick,pinned:node.required,version}));this.#bytes+=bytes;node.state='resident';for(const dep of node.dependents)this.#nodes.get(dep)!.remaining=Math.max(0,this.#nodes.get(dep)!.remaining-1);this.evict();return this.#resident.has(id);}
 touch(id:string,tick:number){const r=this.#resident.get(id);if(r)this.#resident.set(id,Object.freeze({...r,lastUsedTick:tick}));}
 remove(id:string){const r=this.#resident.get(id);if(r?.pinned)return false;if(r){this.#bytes-=r.bytes;this.#resident.delete(id);}return this.#nodes.delete(id);}
 pending(){return[...this.#nodes.values()].filter(n=>n.state==='queued'||n.state==='loading').length;}residentBytes(){return this.#bytes;}snapshot(){return Object.freeze([...this.#resident.values()].sort((a,b)=>a.id.localeCompare(b.id)));}
 private evict(){while(this.#bytes>this.maxResidentBytes){const victim=[...this.#resident.values()].filter(r=>!r.pinned).sort((a,b)=>a.lastUsedTick-b.lastUsedTick||a.id.localeCompare(b.id))[0];if(!victim)break;this.#bytes-=victim.bytes;this.#resident.delete(victim.id);const n=this.#nodes.get(victim.id);if(n)n.state='queued';}}
 private acyclic(root:string){const visiting=new Set<string>();const visited=new Set<string>();const visit=(id:string):boolean=>{if(visiting.has(id))return false;if(visited.has(id))return true;visiting.add(id);const n=this.#nodes.get(id);if(n)for(const dep of n.dependencies)if(!visit(dep))return false;visiting.delete(id);visited.add(id);return true;};return visit(root);}
}
function priority(p:AssetRequest['priority']){return p==='critical'?5:p==='high'?4:p==='normal'?3:p==='low'?2:1;}
