import type{QualityDecision,QualityTier}from'./contracts';
const ORDER:readonly QualityTier[]=['minimal','balanced','high','cinematic'];
export class AdaptiveQualityGovernor{
 #tier:QualityTier;#bad=0;#good=0;#change=-Infinity;readonly targetFrameMs:number;readonly downgradeAfter:number;readonly upgradeAfter:number;readonly cooldownTicks:number;
 constructor(initial:QualityTier='high',options:{readonly targetFrameMs?:number;readonly downgradeAfter?:number;readonly upgradeAfter?:number;readonly cooldownTicks?:number}={}){this.#tier=initial;this.targetFrameMs=Math.max(8,options.targetFrameMs??16.6);this.downgradeAfter=Math.max(1,Math.trunc(options.downgradeAfter??4));this.upgradeAfter=Math.max(1,Math.trunc(options.upgradeAfter??90));this.cooldownTicks=Math.max(1,Math.trunc(options.cooldownTicks??30));}
 sample(input:{readonly frameMs:number;readonly gpuMs:number;readonly cpuMs:number;readonly memoryPressure:number;readonly visibleEntities:number},tick:number):QualityDecision|null{const pressure=this.pressure(input);this.#bad=pressure>.72?this.#bad+1:0;this.#good=pressure<.38?this.#good+1:0;if(tick-this.#change<this.cooldownTicks)return null;const i=ORDER.indexOf(this.#tier);let next=this.#tier;let reason='stable';if(this.#bad>=this.downgradeAfter){next=ORDER[Math.max(0,i-1)]!;reason='sustained-pressure';}else if(this.#good>=this.upgradeAfter){next=ORDER[Math.min(ORDER.length-1,i+1)]!;reason='sustained-headroom';}if(next===this.#tier)return null;const d=Object.freeze({previous:this.#tier,next,reason,score:pressure,tick});this.#tier=next;this.#change=tick;this.#bad=0;this.#good=0;return d;}
 pressure(input:{readonly frameMs:number;readonly gpuMs:number;readonly cpuMs:number;readonly memoryPressure:number;readonly visibleEntities:number}){return clamp(input.frameMs/this.targetFrameMs*.45+input.gpuMs/this.targetFrameMs*.25+input.cpuMs/this.targetFrameMs*.15+clamp(input.memoryPressure,0,1)*.1+clamp(input.visibleEntities/4000,0,1)*.05,0,1);}
 tier(){return this.#tier;}profile(){switch(this.#tier){case'minimal':return{pixelRatio:.7,shadowMap:512,postFx:0,particles:.35};case'balanced':return{pixelRatio:.85,shadowMap:1024,postFx:.5,particles:.65};case'high':return{pixelRatio:1,shadowMap:2048,postFx:1,particles:1};case'cinematic':return{pixelRatio:1.15,shadowMap:4096,postFx:1.25,particles:1.2};}}
}
function clamp(v:number,min:number,max:number){return Number.isFinite(v)?Math.max(min,Math.min(max,v)):min;}
