import{DeterministicClock}from'./deterministicClock';import{TypedCommandBus,createCommand}from'./commandBus';import{BoundedEventStream}from'./eventStream';import{DeterministicWorkScheduler}from'./scheduler';import{ImmutableStateGraph}from'./stateGraph';import{RuntimeTelemetry}from'./telemetry';import{SafeBrowserHost}from'./browserHost';import{R41SecurityBoundary}from'./security';import{AdaptiveQualityGovernor}from'./qualityGovernor';import type{BudgetProfile,CommandEnvelope,RuntimeHealth,RuntimePhase,Tick}from'./contracts';
export interface KernelState extends Record<string,unknown>{phase:RuntimePhase;tick:number;quality:string;player:{x:number;y:number;z:number};world:{activeEntities:number};networkConnected:boolean;}
export const DEFAULT_BUDGET:BudgetProfile=Object.freeze({frameMs:16.6,laneBudgets:Object.freeze({input:1,simulation:5,world:3,asset:2,render:4,network:1,persistence:.5,telemetry:.5}),maxWorkPerTick:256,maxAssetsPerTick:8,maxNetworkOpsPerTick:32});
export class R41RuntimeKernel{
 readonly clock=new DeterministicClock();readonly bus=new TypedCommandBus();readonly events=new BoundedEventStream();readonly scheduler=new DeterministicWorkScheduler();readonly telemetry=new RuntimeTelemetry();readonly browser=new SafeBrowserHost();readonly security=new R41SecurityBoundary();readonly quality=new AdaptiveQualityGovernor('high');readonly state=new ImmutableStateGraph<KernelState>({schema:'aapw.r41.kernel',initial:{phase:'cold',tick:0,quality:'high',player:{x:0,y:0,z:0},world:{activeEntities:0},networkConnected:false}});readonly budgets=DEFAULT_BUDGET;#phase:RuntimePhase='cold';#started=false;
 constructor(){this.bus.register('player.setPosition',(payload:unknown,context)=>{const value=payload as{x:number;y:number;z:number};if(![value.x,value.y,value.z].every(Number.isFinite))throw new Error('PLAYER_POSITION_INVALID');const tx=this.state.begin(context.tick.index);tx.set(s=>{s.player={x:value.x,y:value.y,z:value.z};},'ui');tx.commit();});}
 boot(){if(this.#phase!=='cold'&&this.#phase!=='stopped')return;this.#phase='booting';this.publishPhase();this.#phase='ready';this.publishPhase();}
 start(){if(this.#phase==='cold')this.boot();if(this.#phase!=='ready'&&this.#phase!=='paused')throw new Error('R41_START_INVALID');this.#started=true;this.#phase='running';this.publishPhase();}
 pause(){if(this.#phase==='running'){this.#phase='paused';this.publishPhase();}}resume(){if(this.#phase==='paused'){this.#phase='running';this.publishPhase();}}stop(){this.#started=false;this.#phase='stopped';this.scheduler.clear();this.publishPhase();}
 frame(deltaMs:number){if(!this.#started)return this.clock.tick();return this.clock.advance(deltaMs,tick=>this.runTick(tick));}
 dispatch<T>(command:CommandEnvelope<T>){const tick=this.clock.tick();const valid=this.security.inspectPayload(command.payload);if(!valid.accepted)return Promise.resolve({accepted:false,errorCode:'SECURITY_REJECTED',completedTick:tick.index});if(!this.security.consumeRate(command.source,tick.index))return Promise.resolve({accepted:false,errorCode:'RATE_LIMITED',completedTick:tick.index});return this.bus.dispatch(command,{tick,signal:new AbortController().signal});}
 health():RuntimeHealth{return this.telemetry.snapshot(this.#phase,this.clock.tick().index,this.scheduler.pending(),this.scheduler.dropped()+this.events.dropped,0);}
 private runTick(tick:Tick){this.security.prune(tick.index);this.scheduler.execute(tick,this.budgets);const tx=this.state.begin(tick.index);tx.set(s=>{s.phase=this.#phase;s.tick=tick.index;s.quality=this.quality.tier();},'system');tx.commit();this.telemetry.metric('runtime.tick',tick.deltaMs,tick.simulationMs,{phase:this.#phase});if(tick.index%30===0)this.events.publish('health',this.health(),{tick:tick.index,source:'kernel',coalescible:true});}
 private publishPhase(){const tx=this.state.begin(this.clock.tick().index);tx.set(s=>{s.phase=this.#phase;},'system');tx.commit();this.events.publish('phase',{phase:this.#phase},{tick:this.clock.tick().index,source:'kernel',coalescible:true});}
 playerPositionCommand(x:number,y:number,z:number):CommandEnvelope<{x:number;y:number;z:number}>{return createCommand('player-position-'+this.clock.tick().index,'player.setPosition',{x,y,z},this.clock.tick().index,'high','ui');}
 started(){return this.#started;}
}
