import{stableHash}from'./hash';
export type Capability='read-world'|'write-world'|'network'|'assets'|'telemetry'|'save';
export class R41SecurityBoundary{
 readonly maxPayloadBytes:number;readonly maxDepth:number;readonly maxArrayLength:number;readonly maxKeys:number;readonly maxStringLength:number;readonly maxCommandsPerTick:number;#tokens=new Map<string,{subject:string;capabilities:ReadonlySet<Capability>;expiresTick:number}>();#rates=new Map<string,{tick:number;count:number}>();
 constructor(options:{readonly maxPayloadBytes?:number;readonly maxDepth?:number;readonly maxArrayLength?:number;readonly maxKeys?:number;readonly maxStringLength?:number;readonly maxCommandsPerTick?:number}={}){this.maxPayloadBytes=Math.max(1024,Math.trunc(options.maxPayloadBytes??512*1024));this.maxDepth=Math.max(2,Math.trunc(options.maxDepth??10));this.maxArrayLength=Math.max(8,Math.trunc(options.maxArrayLength??4096));this.maxKeys=Math.max(8,Math.trunc(options.maxKeys??1024));this.maxStringLength=Math.max(64,Math.trunc(options.maxStringLength??16384));this.maxCommandsPerTick=Math.max(1,Math.trunc(options.maxCommandsPerTick??256));}
 inspectPayload(value:unknown){try{const bytes=new TextEncoder().encode(JSON.stringify(value)).byteLength;if(bytes>this.maxPayloadBytes)return Object.freeze({accepted:false,bytes,reason:'payload-bytes'});walk(value,0,this);return Object.freeze({accepted:true,bytes,reason:'ok'});}catch(error){return Object.freeze({accepted:false,bytes:0,reason:error instanceof Error?error.message:'payload-invalid'});}}
 checkUrl(raw:string):Readonly<{accepted:boolean;normalized:string|null;reason:string}>{try{const url=new URL(raw,'https://aapw.invalid');if(url.username||url.password)return{accepted:false,normalized:null,reason:'credentials'};if(!['https:','wss:'].includes(url.protocol))return{accepted:false,normalized:null,reason:'protocol'};return{accepted:true,normalized:url.href,reason:'ok'};}catch{return{accepted:false,normalized:null,reason:'invalid-url'};}}
 issue(subject:string,capabilities:readonly Capability[],expiresTick:number):string{const token=stableHash(subject+':'+expiresTick+':'+Date.now()+':'+Math.random());this.#tokens.set(token,{subject,capabilities:new Set(capabilities),expiresTick});return token;}
 allow(subject:string,capability:Capability,token:string,tick:number):boolean{const entry=this.#tokens.get(token);return Boolean(entry&&entry.subject===subject&&entry.expiresTick>=tick&&entry.capabilities.has(capability));}
 consumeRate(subject:string,tick:number):boolean{const current=this.#rates.get(subject);const next=current?.tick===tick?{tick,count:current.count+1}:{tick,count:1};if(next.count>this.maxCommandsPerTick)return false;this.#rates.set(subject,next);return true;}
 prune(tick:number):void{for(const[token,entry]of this.#tokens)if(entry.expiresTick<tick)this.#tokens.delete(token);for(const[subject,rate]of this.#rates)if(tick-rate.tick>2)this.#rates.delete(subject);}
 clear():void{this.#tokens.clear();this.#rates.clear();}
}
function walk(value:unknown,depth:number,owner:R41SecurityBoundary,seen=new Set<object>()):void{if(depth>owner.maxDepth)throw new Error('PAYLOAD_DEPTH');if(value===null||typeof value!=='object'){if(typeof value==='string'&&value.length>owner.maxStringLength)throw new Error('PAYLOAD_STRING');return;}if(seen.has(value))throw new Error('PAYLOAD_CYCLE');seen.add(value);if(Array.isArray(value)){if(value.length>owner.maxArrayLength)throw new Error('PAYLOAD_ARRAY');for(const item of value)walk(item,depth+1,owner,seen);}else{const entries=Object.entries(value);if(entries.length>owner.maxKeys)throw new Error('PAYLOAD_KEYS');for(const[key,item]of entries){if(key.length>owner.maxStringLength)throw new Error('PAYLOAD_KEY');walk(item,depth+1,owner,seen);}}seen.delete(value);}
