import{stableHash}from'./hash';import type{MutationSource,SnapshotEnvelope,StateCommit,StatePatch}from'./contracts';
export class ImmutableStateGraph<T extends Record<string,unknown>>{
 readonly schema:string;readonly maxDepth:number;readonly maxPatches:number;#state:T;#revision=0;#history:StateCommit[]=[];#listeners=new Set<(commit:StateCommit,state:Readonly<T>)=>void>();
 constructor(options:{readonly schema:string;readonly initial:T;readonly maxDepth?:number;readonly maxHistory?:number;readonly maxPatches?:number}){this.schema=options.schema;this.maxDepth=Math.max(1,Math.trunc(options.maxDepth??12));this.maxPatches=Math.max(1,Math.trunc(options.maxPatches??256));this.#state=freeze(clone(options.initial));this.#history=[];this.maxHistory=Math.max(16,Math.trunc(options.maxHistory??256));validate(this.#state,this.maxDepth);}
 readonly maxHistory:number;
 begin(tick:number){let draft=clone(this.#state);const patches:StatePatch[]=[];let closed=false;const assert=()=>{if(closed)throw new Error('STATE_TX_CLOSED');};const set=(mutator:(state:T)=>void,source:MutationSource='engine')=>{assert();const before=clone(draft);mutator(draft);validate(draft,this.maxDepth);patches.push(...diff(before,draft,'',source));if(patches.length>this.maxPatches)throw new Error('STATE_PATCH_LIMIT');};const commit=():StateCommit=>{assert();closed=true;this.#revision+=1;this.#state=freeze(clone(draft));const result=Object.freeze({revision:this.#revision,tick,patches:Object.freeze(patches),digest:stableHash(this.#state)});this.#history.push(result);while(this.#history.length>this.maxHistory)this.#history.shift();for(const listener of this.#listeners)listener(result,this.#state);return result;};const rollback=()=>{assert();closed=true;};return Object.freeze({get:()=>freeze(clone(draft)),set,replace:(next:T,source:MutationSource='engine')=>{assert();const before=clone(draft);validate(next,this.maxDepth);draft=clone(next);patches.push(...diff(before,draft,'',source));},commit,rollback});}
 snapshot(tick:number):SnapshotEnvelope<T>{const state=freeze(clone(this.#state));return Object.freeze({schema:this.schema,revision:this.#revision,tick,digest:stableHash(state),state});}
 restore(snapshot:SnapshotEnvelope<T>):void{if(snapshot.schema!==this.schema||stableHash(snapshot.state)!==snapshot.digest)throw new Error('STATE_SNAPSHOT_INVALID');validate(snapshot.state,this.maxDepth);this.#revision=snapshot.revision;this.#state=freeze(clone(snapshot.state));}
 read():Readonly<T>{return freeze(clone(this.#state));}revision():number{return this.#revision;}history():readonly StateCommit[]{return Object.freeze([...this.#history]);}subscribe(listener:(commit:StateCommit,state:Readonly<T>)=>void):()=>void{this.#listeners.add(listener);return()=>this.#listeners.delete(listener);}
}
function clone<T>(v:T):T{if(typeof structuredClone==='function')return structuredClone(v);return JSON.parse(JSON.stringify(v))as T;}
function freeze<T>(v:T,depth=0):T{if(v===null||typeof v!=='object'||depth>20)return v;for(const child of Object.values(v as Record<string,unknown>))freeze(child,depth+1);return Object.freeze(v);}
function validate(v:unknown,max:number,depth=0,seen=new Set<object>()):void{if(v===null||typeof v!=='object')return;if(depth>max)throw new Error('STATE_DEPTH_LIMIT');if(seen.has(v))throw new Error('STATE_CYCLE');seen.add(v);for(const child of Object.values(v as Record<string,unknown>))validate(child,max,depth+1,seen);seen.delete(v);}
function diff(a:unknown,b:unknown,path:string,source:MutationSource):StatePatch[]{if(Object.is(a,b))return[];if(a===null||b===null||typeof a!=='object'||typeof b!=='object')return[{path:path||'$',from:a,to:b,source}];const aa=a as Record<string,unknown>,bb=b as Record<string,unknown>,keys=new Set([...Object.keys(aa),...Object.keys(bb)]);const out:StatePatch[]=[];for(const key of[...keys].sort())out.push(...diff(aa[key],bb[key],path?path+'.'+key:key,source));return out;}
