import type{InterestEntity,InterestDecision}from'./contracts';
interface Cell{readonly key:string;readonly ids:Set<string>;}
export class SpatialInterestManager{
 readonly cellSize:number;readonly maxEntities:number;readonly nearRadius:number;readonly midRadius:number;readonly farRadius:number;#entities=new Map<string,InterestEntity>();#cells=new Map<string,Cell>();
 constructor(options:{readonly cellSize?:number;readonly maxEntities?:number;readonly nearRadius?:number;readonly midRadius?:number;readonly farRadius?:number}={}){this.cellSize=Math.max(1,options.cellSize??32);this.maxEntities=Math.max(64,Math.trunc(options.maxEntities??50000));this.nearRadius=Math.max(1,options.nearRadius??40);this.midRadius=Math.max(this.nearRadius,options.midRadius??120);this.farRadius=Math.max(this.midRadius,options.farRadius??280);}
 upsert(entity:InterestEntity){if(!entity.id||![entity.x,entity.y,entity.z].every(Number.isFinite))return false;if(!this.#entities.has(entity.id)&&this.#entities.size>=this.maxEntities)return false;const old=this.#entities.get(entity.id);if(old)this.removeCell(old);const next=Object.freeze({...entity,importance:clamp(entity.importance,0,1),radius:clamp(entity.radius,0,1000)});this.#entities.set(next.id,next);const key=this.cellKey(next.x,next.z);const cell=this.#cells.get(key)??{key,ids:new Set<string>()};cell.ids.add(next.id);this.#cells.set(key,cell);return true;}
 query(x:number,y:number,z:number,radius:number){const r=clamp(radius,0,this.farRadius*2);const minX=Math.floor((x-r)/this.cellSize),maxX=Math.floor((x+r)/this.cellSize),minZ=Math.floor((z-r)/this.cellSize),maxZ=Math.floor((z+r)/this.cellSize);const out:InterestEntity[]=[];for(let cx=minX;cx<=maxX;cx+=1)for(let cz=minZ;cz<=maxZ;cz+=1){const cell=this.#cells.get(cx+':'+cz);if(!cell)continue;for(const id of cell.ids){const e=this.#entities.get(id);if(!e)continue;const dx=e.x-x,dy=e.y-y,dz=e.z-z;if(dx*dx+dy*dy+dz*dz<=r*r)out.push(e);}}return Object.freeze(out.sort((a,b)=>a.id.localeCompare(b.id)));}
 evaluate(x:number,y:number,z:number){return Object.freeze(this.query(x,y,z,this.farRadius).map(e=>{const dx=e.x-x,dy=e.y-y,dz=e.z-z;const distanceSq=dx*dx+dy*dy+dz*dz;const d=Math.sqrt(distanceSq);const tier=d<=this.nearRadius?'near':d<=this.midRadius?'mid':d<=this.farRadius?'far':'sleep';const base=tier==='near'?60:tier==='mid'?20:tier==='far'?5:1;return Object.freeze({id:e.id,tier,distanceSq,updateHz:Math.max(1,Math.round(base*(.5+e.importance*.5))),visible:tier!=='sleep'} as InterestDecision);}));}
 remove(id:string){const e=this.#entities.get(id);if(!e)return false;this.removeCell(e);return this.#entities.delete(id);}
 size(){return this.#entities.size;}
 private removeCell(e:InterestEntity){const cell=this.#cells.get(this.cellKey(e.x,e.z));if(!cell)return;cell.ids.delete(e.id);if(!cell.ids.size)this.#cells.delete(cell.key);}
 private cellKey(x:number,z:number){return Math.floor(x/this.cellSize)+':'+Math.floor(z/this.cellSize);}
}
function clamp(v:number,min:number,max:number){return Number.isFinite(v)?Math.max(min,Math.min(max,v)):min;}
