
import { clamp, fail, ok, type R35Id, type R35InventoryState, type R35ItemDefinition, type R35ItemStack, type R35Result } from './contracts';

export class InventoryRuntimeR35 {
  #defs=new Map<R35Id,R35ItemDefinition>(); #stacks=new Map<R35Id,R35ItemStack>(); #equipped=new Map<string,R35Id|null>(); #capacity:number; #revision=0;
  constructor(capacity=24){this.#capacity=clamp(Math.trunc(capacity),1,512);}
  registerItem(def:R35ItemDefinition):R35Result<R35ItemDefinition>{if(this.#defs.has(def.id))return fail('ITEM_EXISTS','Item already registered');if(!def.id||def.stackLimit<1||def.stackLimit>9999||def.weight<0)return fail('ITEM_INVALID','Invalid item definition');this.#defs.set(def.id,Object.freeze({...def,slots:Object.freeze([...def.slots]),tags:Object.freeze([...def.tags])}));return ok(def);}
  add(itemId:R35Id,quantity:number,durability?:number):R35Result<{added:number;remaining:number}>{const def=this.#defs.get(itemId);const q=Math.trunc(quantity);if(!def)return fail('ITEM_UNKNOWN','Item definition not found');if(q<=0)return ok({added:0,remaining:0});let remaining=q;let stack=this.#stacks.get(itemId);if(stack){const room=def.stackLimit-stack.quantity;const take=Math.min(room,remaining);const next=durability===undefined?Object.freeze({...stack,quantity:stack.quantity+take}):Object.freeze({...stack,quantity:stack.quantity+take,durability:clamp(durability,0,1)});this.#stacks.set(itemId,next);remaining-=take;}
    if(remaining>0){const slots=[...this.#stacks.values()].length;if(slots>=this.#capacity)return ok({added:q-remaining,remaining});const take=Math.min(def.stackLimit,remaining);this.#stacks.set(itemId,Object.freeze({itemId,quantity:take,...(durability===undefined?{}:{durability:clamp(durability,0,1)})}));remaining-=take;}this.#revision++;return ok({added:q-remaining,remaining});}
  remove(itemId:R35Id,quantity:number):R35Result<number>{const s=this.#stacks.get(itemId);const q=Math.trunc(quantity);if(!s||q<=0)return fail('ITEM_REMOVE_INVALID','Cannot remove requested quantity');if(q>s.quantity)return fail('ITEM_INSUFFICIENT','Not enough items');if(q===s.quantity)this.#stacks.delete(itemId);else this.#stacks.set(itemId,Object.freeze({...s,quantity:s.quantity-q}));this.#revision++;return ok(q);}
  equip(slot:string,itemId:R35Id):R35Result<R35InventoryState>{const def=this.#defs.get(itemId);const s=this.#stacks.get(itemId);if(!def||!s)return fail('EQUIP_INVALID','Item is not owned');if(!def.slots.includes(slot))return fail('SLOT_INVALID','Item cannot use that slot');this.#equipped.set(slot,itemId);this.#revision++;return ok(this.snapshot());}
  unequip(slot:string):void{if(this.#equipped.has(slot)){this.#equipped.set(slot,null);this.#revision++;}}
  weight():number{return [...this.#stacks.values()].reduce((sum,s)=>sum+(this.#defs.get(s.itemId)?.weight??0)*s.quantity,0);}
  availableSlots():number{return Math.max(0,this.#capacity-this.#stacks.size);}
  has(itemId:R35Id,quantity=1):boolean{return (this.#stacks.get(itemId)?.quantity??0)>=quantity;}
  stateOf(itemId:R35Id):R35ItemStack|null{return this.#stacks.get(itemId)??null;}
  snapshot():R35InventoryState{const slots=[...this.#stacks.values()].sort((a,b)=>a.itemId.localeCompare(b.itemId));const equipped=Object.fromEntries([...this.#equipped.entries()].sort(([a],[b])=>a.localeCompare(b)));return Object.freeze({revision:this.#revision,capacity:this.#capacity,weight:this.weight(),slots:Object.freeze(slots),equipped:Object.freeze(equipped)});}
  restore(state:R35InventoryState):R35Result<R35InventoryState>{if(state.slots.length>this.#capacity)return fail('INVENTORY_OVERFLOW','Saved inventory exceeds capacity');this.#stacks.clear();for(const s of state.slots){const d=this.#defs.get(s.itemId);if(!d||s.quantity<1||s.quantity>d.stackLimit)return fail('INVENTORY_ITEM_INVALID','Saved item is invalid');this.#stacks.set(s.itemId,Object.freeze({...s}));}this.#equipped.clear();for(const [slot,id] of Object.entries(state.equipped)){if(id!==null&&!this.has(id))return fail('INVENTORY_EQUIP_INVALID','Saved equipment references missing item');this.#equipped.set(slot,id);}this.#revision=Math.max(this.#revision,state.revision)+1;return ok(this.snapshot());}
}
