
import { fail, ok, stableHash, stableStringify, type R35Result, type R35SaveEnvelope } from './contracts';

export interface SaveCodec { readonly encode:(value:unknown)=>string; readonly decode:(value:string)=>unknown; }
export interface SaveMigration { readonly from:number; readonly to:number; readonly migrate:(value:unknown)=>unknown; }
export interface SaveRecord { readonly slot:string; readonly schema:number; readonly tick:number; readonly digest:string; readonly payload:unknown; readonly bytes:number; }
const JSON_CODEC:SaveCodec={encode:stableStringify,decode:JSON.parse};
export class SaveRuntimeR35 {
  #schema:number; #maxBytes:number; #codec:SaveCodec; #migrations:SaveMigration[]=[]; #slots=new Map<string,R35SaveEnvelope>();
  constructor(schema=1,maxBytes=4*1024*1024,codec=JSON_CODEC){this.#schema=Math.max(1,Math.trunc(schema));this.#maxBytes=Math.max(1024,this.#toSafeInt(maxBytes));this.#codec=codec;}
  registerMigration(m:SaveMigration):R35Result<void>{if(m.to!==m.from+1||m.from<1||m.to>this.#schema)return fail('MIGRATION_INVALID','Migrations must advance one schema version');if(this.#migrations.some(x=>x.from===m.from))return fail('MIGRATION_DUPLICATE','Migration already registered');this.#migrations.push(m);this.#migrations.sort((a,b)=>a.from-b.from);return ok(undefined);}
  write(slot:string,tick:number,payload:unknown):R35Result<SaveRecord>{const data=this.#codec.encode(payload);const bytes=new TextEncoder().encode(data).byteLength;if(!slot||slot.length>64||bytes>this.#maxBytes)return fail('SAVE_TOO_LARGE','Save slot or payload exceeds limits');const envelope: R35SaveEnvelope=Object.freeze({schema:this.#schema,slot,tick:Math.max(0,Math.trunc(tick)),payload,digest:stableHash({schema:this.#schema,slot,tick,payload}),createdAt:0});this.#slots.set(slot,envelope);return ok(this.#record(envelope,bytes));}
  read(slot:string):R35Result<SaveRecord>{const e=this.#slots.get(slot);if(!e)return fail('SAVE_MISSING','Save slot is empty',true);const digest=stableHash({schema:e.schema,slot:e.slot,tick:e.tick,payload:e.payload});if(digest!==e.digest)return fail('SAVE_CORRUPT','Save digest mismatch');const migrated=this.#migrate(e.schema,e.payload);if(!migrated.ok)return migrated;const payload=migrated.value;return ok(this.#record(Object.freeze({...e,schema:this.#schema,payload,digest:stableHash({schema:this.#schema,slot:e.slot,tick:e.tick,payload})}),this.#codec.encode(payload).length));}
  delete(slot:string):boolean{return this.#slots.delete(slot);}
  list():ReadonlyArray<SaveRecord>{return Object.freeze([...this.#slots.values()].sort((a,b)=>a.slot.localeCompare(b.slot)).map(e=>this.#record(e,this.#codec.encode(e.payload).length)));}
  exportSlot(slot:string):R35Result<string>{const r=this.read(slot);if(!r.ok)return r;return ok(this.#codec.encode(r.value));}
  importSlot(raw:string):R35Result<SaveRecord>{if(new TextEncoder().encode(raw).byteLength>this.#maxBytes)return fail('SAVE_IMPORT_TOO_LARGE','Imported save exceeds limits');let parsed:unknown;try{parsed=this.#codec.decode(raw);}catch{return fail('SAVE_IMPORT_INVALID','Imported save is not valid JSON');}if(typeof parsed!=='object'||parsed===null)return fail('SAVE_IMPORT_INVALID','Imported save must be an object');const p=parsed as Partial<R35SaveEnvelope>;if(typeof p.slot!=='string'||typeof p.schema!=='number'||typeof p.tick!=='number'||p.payload===undefined||typeof p.digest!=='string')return fail('SAVE_IMPORT_INVALID','Imported save envelope is incomplete');const digest=stableHash({schema:p.schema,slot:p.slot,tick:p.tick,payload:p.payload});if(digest!==p.digest)return fail('SAVE_IMPORT_CORRUPT','Imported save digest mismatch');const e=Object.freeze({schema:Math.trunc(p.schema),slot:p.slot,tick:Math.trunc(p.tick),payload:p.payload,digest:p.digest,createdAt:0}) as R35SaveEnvelope;this.#slots.set(e.slot,e);return ok(this.#record(e,raw.length));}
  #toSafeInt(v:number):number{return Number.isSafeInteger(v)?v:4*1024*1024;}
  #record(e:R35SaveEnvelope,bytes:number):SaveRecord{return Object.freeze({slot:e.slot,schema:e.schema,tick:e.tick,digest:e.digest,payload:e.payload,bytes});}
  #migrate(schema:number,payload:unknown):R35Result<unknown>{let value=payload;for(let v=schema;v<this.#schema;v++){const m=this.#migrations.find(x=>x.from===v);if(!m)return fail('MIGRATION_MISSING',`No migration registered for schema ${v}`);try{value=m.migrate(value);}catch{return fail('MIGRATION_FAILED',`Migration ${v}->${m.to} failed`);}}return ok(value);}
}
