/** Strict deterministic bounded audio cue admission and ordering. */
export type AudioCuePayloadValue=string|number|boolean;
export type AudioCuePayload=Readonly<Record<string,AudioCuePayloadValue>>;
export interface AudioCueEntry{readonly version:1;readonly sequence:number;readonly id:string;readonly kind:string;readonly priority:number;readonly gain:number;readonly distance:number;readonly sourceId:string|null;readonly payload:AudioCuePayload;}
export interface PlayedAudioCueEntry extends AudioCueEntry{readonly playedAt:number;}
export interface AudioCueSchedulerOptions{readonly maxQueue?:number;readonly maxHistory?:number;readonly cooldowns?:Readonly<Record<string,number>>;}
export interface AudioCueSchedulerStats{readonly queued:number;readonly history:number;readonly cooldownKeys:number;readonly now:number;}
export interface AudioCueSchedulerSnapshot extends AudioCueSchedulerStats{readonly version:1;readonly disposed:boolean;readonly sequence:number;readonly queue:readonly AudioCueEntry[];readonly recentHistory:readonly PlayedAudioCueEntry[];}
const DEFAULT_MAX_QUEUE=64,DEFAULT_MAX_HISTORY=128;
export const DEFAULT_AUDIO_CUE_COOLDOWNS=Object.freeze({footstep:0.08,combat:0.12,dragon:0.4,storm:0.8,ui:0.03,ambience:0.25});
const freeze=(value:object)=>Object.freeze(value);
const clamp=(value:number,min:number,max:number):number=>Math.min(max,Math.max(min,value));
const finiteOr=(value:number|undefined,fallback:number):number=>Number.isFinite(value)?value as number:fallback;
const safeKey=(value:unknown,maxLength:number,fallback:string):string=>String(value??fallback).slice(0,maxLength);
function sanitizePayload(payload:unknown):AudioCuePayload{if(!payload||typeof payload!=='object'||Array.isArray(payload))return {};const source=payload as Record<string,unknown>;const output:Record<string,AudioCuePayloadValue>={};for(const key of Object.keys(source).slice(0,8)){const safeName=key.replace(/[^a-zA-Z0-9_.-]/g,'_').slice(0,48),value=source[key];if(typeof value==='string')output[safeName]=value.slice(0,96);else if(typeof value==='number'&&Number.isFinite(value))output[safeName]=Number(value.toFixed(4));else if(typeof value==='boolean')output[safeName]=value;}return freeze(output) as AudioCuePayload;}
export class AudioCueScheduler{readonly maxQueue:number;readonly maxHistory:number;readonly cooldowns:Readonly<Record<string,number>>;private now=0;private sequence=0;private queue:AudioCueEntry[]=[];private history:PlayedAudioCueEntry[]=[];private readonly lastPlayed=new Map<string,number>();private disposed=false;
constructor({maxQueue=DEFAULT_MAX_QUEUE,maxHistory=DEFAULT_MAX_HISTORY,cooldowns=DEFAULT_AUDIO_CUE_COOLDOWNS}:AudioCueSchedulerOptions={}){this.maxQueue=clamp(Math.round(finiteOr(maxQueue,DEFAULT_MAX_QUEUE)),8,256);this.maxHistory=clamp(Math.round(finiteOr(maxHistory,DEFAULT_MAX_HISTORY)),16,512);this.cooldowns=freeze({...DEFAULT_AUDIO_CUE_COOLDOWNS,...cooldowns}) as Readonly<Record<string,number>>;}
advance(deltaSeconds=0.016):AudioCueSchedulerSnapshot{if(this.disposed)return this.snapshot();this.now+=clamp(finiteOr(deltaSeconds,0),0,0.25);return this.snapshot();}
enqueue({id,kind='ambience',priority=30,gain=0.2,distance=0,sourceId=null,payload={}}:Readonly<{id?:string;kind?:string;priority?:number;gain?:number;distance?:number;sourceId?:string|null;payload?:unknown}>={}):boolean{if(this.disposed)return false;const safeId=safeKey(id,96,String(kind)+'-'+String(this.sequence+1)),safeKind=safeKey(kind,48,'ambience'),cooldown=clamp(finiteOr(this.cooldowns[safeKind],0),0,10),previous=this.lastPlayed.get(safeId);if(previous!==undefined&&this.now-previous<cooldown)return false;if(this.queue.length>=this.maxQueue){let weakestIndex=0;for(let i=1;i<this.queue.length;i+=1){const current=this.queue[i];const weakest=this.queue[weakestIndex];if(current && weakest&&(current.priority<weakest.priority||(current.priority===weakest.priority&&current.sequence>weakest.sequence)))weakestIndex=i;}const weakest=this.queue[weakestIndex];if(!weakest||priority<=weakest.priority)return false;this.queue.splice(weakestIndex,1);}const entry:AudioCueEntry=freeze({version:1 as const,sequence:++this.sequence,id:safeId,kind:safeKind,priority:clamp(Math.round(finiteOr(priority,30)),0,100),gain:clamp(finiteOr(gain,0.2),0,1),distance:Math.max(0,finiteOr(distance,0)),sourceId:sourceId==null?null:String(sourceId).slice(0,96),payload:sanitizePayload(payload)}) as AudioCueEntry;this.queue.push(entry);return true;}
dequeue(limit=8):readonly AudioCueEntry[]{const count=clamp(Math.round(finiteOr(limit,8)),1,Math.max(1,this.queue.length));this.queue.sort((a,b)=>b.priority-a.priority||a.distance-b.distance||a.sequence-b.sequence);const selected=this.queue.splice(0,count);for(const entry of selected){this.lastPlayed.set(entry.id,this.now);this.history=[...this.history.slice(-(this.maxHistory-1)),freeze({...entry,playedAt:this.now}) as PlayedAudioCueEntry];}return Object.freeze([...selected]);}
clear():void{this.queue=[];this.sequence+=1;}
stats():AudioCueSchedulerStats{return freeze({queued:this.queue.length,history:this.history.length,cooldownKeys:this.lastPlayed.size,now:Number(this.now.toFixed(4))});}
snapshot():AudioCueSchedulerSnapshot{const stats=this.stats();return freeze({version:1 as const,disposed:this.disposed,sequence:this.sequence,...stats,queue:Object.freeze([...this.queue]),recentHistory:Object.freeze(this.history.slice(-16))}) as AudioCueSchedulerSnapshot;}
dispose():void{this.disposed=true;this.queue=[];this.history=[];this.lastPlayed.clear();}}
export function createAudioCueScheduler(options:AudioCueSchedulerOptions={}):AudioCueScheduler{return new AudioCueScheduler(options);}
export function audioCueSchedulerConstants(){return freeze({defaults:DEFAULT_AUDIO_CUE_COOLDOWNS});}
