import {RuntimeError} from './contracts.ts';
import type {HealthGrade,HealthSnapshot,MetricSummary,RuntimeEvent,RuntimeEventMap,TaskLane,TelemetrySample,Tick} from './contracts.ts';

class Ring<T>{readonly #values:T[]=[];constructor(readonly limit:number){}push(value:T):void{this.#values.push(value);while(this.#values.length>this.limit)this.#values.shift();}values():readonly T[]{return this.#values.slice();}}
export interface Span{readonly id:string;readonly name:string;readonly tick:Tick;readonly startedAt:number;readonly attributes:Readonly<Record<string,string|number|boolean>>;readonly durationMilliseconds?:number;readonly error?:string;}
export interface ObservabilityOptions{readonly sampleLimit:number;readonly spanLimit:number;readonly eventLimit:number;readonly clock:()=>number;}
const DEFAULT:ObservabilityOptions={sampleLimit:1024,spanLimit:512,eventLimit:1024,clock:()=>performance.now()};
export function summarize(values:readonly number[]):MetricSummary{if(!values.length)return{count:0,sum:0,min:0,max:0,average:0,p95:0};const sorted=[...values].sort((a,b)=>a-b);const sum=values.reduce((a,b)=>a+b,0);const p95=sorted[Math.min(sorted.length-1,Math.ceil(sorted.length*.95)-1)]??0;return{count:values.length,sum,min:sorted[0]??0,max:sorted.at(-1)??0,average:sum/values.length,p95};}
export class RuntimeObservability{
  readonly #options:ObservabilityOptions;readonly #samples;readonly #spans;readonly #events;readonly #listeners=new Map<string,Set<(event:unknown)=>void>>();readonly #counters=new Map<string,number>();readonly #gauges=new Map<string,number>();#spanSequence=0;
  constructor(options:Partial<ObservabilityOptions>={}){this.#options={...DEFAULT,...options};this.#samples=new Ring<TelemetrySample>(this.#options.sampleLimit);this.#spans=new Ring<Span>(this.#options.spanLimit);this.#events=new Ring<RuntimeEvent<keyof RuntimeEventMap>>(this.#options.eventLimit);}
  on<K extends keyof RuntimeEventMap>(type:K,listener:(event:RuntimeEvent<K>)=>void):()=>void{const bucket=this.#listeners.get(type as string)??new Set();bucket.add(listener as (event:unknown)=>void);this.#listeners.set(type as string,bucket);return()=>bucket.delete(listener as (event:unknown)=>void);}
  emit<K extends keyof RuntimeEventMap>(event:RuntimeEvent<K>):void{this.#events.push(event as RuntimeEvent<keyof RuntimeEventMap>);for(const listener of this.#listeners.get(event.type as string)??[])listener(event);}
  record(sample:TelemetrySample):void{this.#samples.push(sample);}
  increment(name:string,amount=1):number{const value=(this.#counters.get(name)??0)+amount;this.#counters.set(name,value);return value;}
  setGauge(name:string,value:number):void{if(!Number.isFinite(value))throw new RuntimeError({code:'R32_GAUGE_NONFINITE',message:'Gauge must be finite'});this.#gauges.set(name,value);}
  counter(name:string):number{return this.#counters.get(name)??0;}gauge(name:string):number{return this.#gauges.get(name)??0;}
  startSpan(name:string,tick:Tick,attributes:Readonly<Record<string,string|number|boolean>>={}):{id:string;end:(error?:unknown)=>Span}{const id='r32-span-'+String(++this.#spanSequence);const start=this.#options.clock();return{id,end:(error)=>{const end=this.#options.clock();const span:Span={id,name,tick,startedAt:start,durationMilliseconds:Math.max(0,end-start),...(error===undefined?{}:{error:error instanceof Error?error.message:String(error)}),attributes};this.#spans.push(span);if(error!==undefined)this.increment('errors.total');return span;}};}
  health(frameMilliseconds:readonly number[],memoryBytes:number,failedAssets:number,networkDrops:number,droppedTasks:number):HealthSnapshot{const frame=summarize(frameMilliseconds);const tasks=summarize(this.#samples.values().map(v=>v.durationMilliseconds));let score=100;score-=Math.min(40,Math.max(0,frame.p95-8)*3);score-=Math.min(15,droppedTasks);score-=Math.min(20,failedAssets*2);score-=Math.min(15,networkDrops);if(memoryBytes>512*1024*1024)score-=10;score=Math.max(0,Math.round(score));const grade:HealthGrade=score>=90?'excellent':score>=75?'healthy':score>=55?'degraded':'critical';const recommendations:string[]=[];if(frame.p95>16.7)recommendations.push('Reduce render/world pressure.');if(droppedTasks)recommendations.push('Adjust task cadence or lane budgets.');if(failedAssets)recommendations.push('Inspect asset integrity and eviction.');if(networkDrops)recommendations.push('Inspect packet limits and retransmission pressure.');return{score,grade,frameMilliseconds:frame,taskMilliseconds:tasks,droppedTasks,failedAssets,networkDrops,memoryBytes,recommendations};}
  samples():readonly TelemetrySample[]{return this.#samples.values();}spans():readonly Span[]{return this.#spans.values();}events():readonly RuntimeEvent<keyof RuntimeEventMap>[] {return this.#events.values();}
}
