const SCHEMA='aapw.gameplay-snapshot'; const VERSION=2; const LIMITS=Object.freeze({events:32,inventory:128,quests:128,equipment:32,flags:256,string:256});
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f} function i(v,f=0){return Math.round(n(v,f))} function c(v,a,b){return Math.min(b,Math.max(a,n(v,a)))} function t(v,f=''){return typeof v==='string'?v.slice(0,LIMITS.string):f} function arr(v,m){return Array.isArray(v)?v.slice(0,m):[]}
function pos(p={}){return{x:Number(n(p.x).toFixed(3)),y:Number(n(p.y).toFixed(3)),z:Number(n(p.z).toFixed(3))}}
function inventory(v){return arr(v,LIMITS.inventory).map(x=>({id:t(x?.id??x?.itemId),quantity:c(i(x?.quantity,1),0,9999)})).filter(x=>x.id&&x.quantity>0)}
function quests(v){return arr(v,LIMITS.quests).map(x=>({id:t(x?.id??x?.questId),state:t(x?.state,'unknown'),progress:c(x?.progress,0,1)})).filter(x=>x.id)}
function equipment(v){const o={}; const s=v&&typeof v==='object'?v:{}; for(const k of Object.keys(s).slice(0,LIMITS.equipment)){const x=s[k]; if(['string','number','boolean'].includes(typeof x)||x===null)o[t(k)]=x; else if(x&&typeof x==='object')o[t(k)]=t(x.id??x.itemId)} return o}
function flags(v){const o={}; const s=v&&typeof v==='object'?v:{}; for(const k of Object.keys(s).sort().slice(0,LIMITS.flags)){const x=s[k]; if(['string','number','boolean'].includes(typeof x)||x===null)o[t(k)]=x} return o}
function events(v){return arr(v,LIMITS.events).map((x,j)=>({id:t(x?.id??`event-${j}`),type:t(x?.type,'unknown'),at:Math.max(0,i(x?.at,0))}))}
export function buildGameplaySnapshot(source={},options={}){const p=source.player??{},w=source.world??{};return Object.freeze({schema:SCHEMA,version:VERSION,capturedAtMs:Math.max(0,i(options.capturedAtMs)),seed:i(source.seed),player:{id:t(p.id,'player'),position:pos(p.position),health:c(p.health,0,100000),stamina:c(p.stamina,0,100000),poise:c(p.poise,0,100000),level:c(i(p.level,1),1,999),experience:c(i(p.experience),0,1000000000),inventory:inventory(p.inventory),equipment:equipment(p.equipment)},world:{day:c(i(w.day),0,100000),timeOfDayMinutes:c(i(w.timeOfDayMinutes,720),0,1439),currentSettlementId:t(w.currentSettlementId??w.settlementId),visitedSettlementIds:arr(w.visitedSettlementIds,LIMITS.flags).map(t).filter(Boolean),flags:flags(w.flags)},quests:quests(source.quests),recentEvents:events(source.recentEvents)})}
export function validateGameplaySnapshot(s,{expectedSeed=null}={}){if(!s||s.schema!==SCHEMA)return{valid:false,reason:'SCHEMA'};if(s.version!==VERSION)return{valid:false,reason:'VERSION',version:s.version};if(expectedSeed!==null&&i(s.seed)!==i(expectedSeed))return{valid:false,reason:'SEED'};if(!s.player||!s.world)return{valid:false,reason:'ROOT_FIELDS'};if(!s.player.position||!Number.isFinite(s.player.position.x)||!Number.isFinite(s.player.position.z))return{valid:false,reason:'POSITION'};if(!Array.isArray(s.player.inventory)||s.player.inventory.length>LIMITS.inventory)return{valid:false,reason:'INVENTORY_LIMIT'};if(!Array.isArray(s.quests)||s.quests.length>LIMITS.quests)return{valid:false,reason:'QUEST_LIMIT'};if(!Array.isArray(s.recentEvents)||s.recentEvents.length>LIMITS.events)return{valid:false,reason:'EVENT_LIMIT'};return{valid:true,reason:'OK',version:VERSION}}
export function createRestorePlan(s,o={}){const v=validateGameplaySnapshot(s,o);if(!v.valid)return Object.freeze({ok:false,reason:v.reason,validation:v});return Object.freeze({ok:true,seed:i(s.seed),version:VERSION,restore:Object.freeze({player:{position:pos(s.player.position),health:c(s.player.health,0,100000),stamina:c(s.player.stamina,0,100000),poise:c(s.player.poise,0,100000),level:c(s.player.level,1,999),experience:c(s.player.experience,0,1000000000),inventory:inventory(s.player.inventory),equipment:equipment(s.player.equipment)},world:{day:c(s.world.day,0,100000),timeOfDayMinutes:c(s.world.timeOfDayMinutes,0,1439),currentSettlementId:t(s.world.currentSettlementId),visitedSettlementIds:arr(s.world.visitedSettlementIds,LIMITS.flags).map(t).filter(Boolean),flags:flags(s.world.flags)},quests:quests(s.quests),recentEvents:events(s.recentEvents)}),validation:v})}
export function applyRestorePlan(plan,h={}){if(!plan?.ok)return{ok:false,reason:plan?.reason??'INVALID_PLAN'};let applied=0;try{if(typeof h.player==='function'){h.player(plan.restore.player,plan.seed);applied++}if(typeof h.world==='function'){h.world(plan.restore.world,plan.seed);applied++}if(typeof h.quests==='function'){h.quests(plan.restore.quests,plan.seed);applied++}if(typeof h.recentEvents==='function'){h.recentEvents(plan.restore.recentEvents,plan.seed);applied++}return Object.freeze({ok:true,applied,seed:plan.seed,version:plan.version})}catch(e){return{ok:false,reason:e?.message??'RESTORE_HANDLER_ERROR',applied}}}
export function summarizeGameplaySnapshot(s={}){const v=validateGameplaySnapshot(s);if(!v.valid)return Object.freeze({valid:false,reason:v.reason});return Object.freeze({valid:true,seed:i(s.seed),level:i(s.player.level),inventoryItems:s.player.inventory.length,questCount:s.quests.length,visitedSettlements:s.world.visitedSettlementIds.length,recentEvents:s.recentEvents.length})}
export const GAMEPLAY_SNAPSHOT_SCHEMA=SCHEMA; export const GAMEPLAY_SNAPSHOT_VERSION=VERSION; export const GAMEPLAY_SNAPSHOT_LIMITS=LIMITS;
