/** Strictly typed GPU pass budget and dynamic-resolution planner. */
export const GPU_PASS_ORDER=['base','shadow','water','foliage','effects','post','debug'] as const;
export type GpuPassName=typeof GPU_PASS_ORDER[number];
export type GpuPassWeights=Readonly<Partial<Record<GpuPassName,number>>>;
export type GpuPassAllocations=Readonly<Record<GpuPassName,number>>;
export const GPU_PASS_DEFAULT_WEIGHTS:Readonly<Record<GpuPassName,number>>=Object.freeze({base:1,shadow:0.8,water:0.5,foliage:0.7,effects:0.5,post:0.7,debug:0.1});
const n=(value:unknown,fallback=0):number=>Number.isFinite(Number(value))?Number(value):fallback;
const clamp=(value:unknown,low:number,high:number):number=>Math.min(high,Math.max(low,n(value,low)));
export function allocateGpuPassBudget(totalMs:number,weights:GpuPassWeights=GPU_PASS_DEFAULT_WEIGHTS):GpuPassAllocations{const total=Math.max(0,n(totalMs));const entries=GPU_PASS_ORDER.map(name=>[name,Math.max(0,n(weights[name],0))] as const).filter(([,weight])=>weight>0);const denominator=entries.reduce((sum,[,weight])=>sum+weight,0)||1;const result={} as Record<GpuPassName,number>;for(const [name,weight] of entries)result[name]=Number((total*weight/denominator).toFixed(4));for(const name of GPU_PASS_ORDER)if(result[name]===undefined)result[name]=0;return Object.freeze(result);}
export interface DynamicResolutionInput{readonly currentScale?:number;readonly measuredGpuMs?:number;readonly targetGpuMs?:number;readonly minScale?:number;readonly maxScale?:number;readonly maxStep?:number;}
export interface DynamicResolutionRecommendation{readonly currentScale:number;readonly recommendedScale:number;readonly measuredGpuMs:number;readonly targetGpuMs:number;readonly direction:'up'|'down'|'hold';}
export function recommendDynamicResolution({currentScale=1,measuredGpuMs=0,targetGpuMs=11.5,minScale=0.55,maxScale=1,maxStep=0.06}:DynamicResolutionInput={}):DynamicResolutionRecommendation{const scale=clamp(currentScale,minScale,maxScale),measured=Math.max(0.1,n(measuredGpuMs,targetGpuMs)),target=Math.max(0.1,n(targetGpuMs,11.5)),ratio=clamp(target/measured,0.65,1.25),ideal=clamp(scale*Math.sqrt(ratio),minScale,maxScale),step=clamp(ideal-scale,-Math.abs(maxStep),Math.abs(maxStep)),recommended=clamp(scale+step,minScale,maxScale);return Object.freeze({currentScale:Number(scale.toFixed(4)),recommendedScale:Number(recommended.toFixed(4)),measuredGpuMs:Number(measured.toFixed(3)),targetGpuMs:Number(target.toFixed(3)),direction:step>0.001?'up':step<-0.001?'down':'hold'});}
export interface GpuPassBudgetPlanInput{readonly targetFrameMs?:number;readonly estimatedGpuMs?:number;readonly qualityScale?:number;readonly activePasses?:readonly string[];readonly pressure?:number;readonly weights?:GpuPassWeights;}
export interface GpuPassBudgetPlan{readonly gpuBudgetMs:number;readonly estimatedGpuMs:number;readonly estimatedAfterSheddingMs:number;readonly overBudget:boolean;readonly allocations:GpuPassAllocations;readonly enabled:readonly GpuPassName[];readonly shed:readonly GpuPassName[];}
export function buildGpuPassBudgetPlan({targetFrameMs=16.67,estimatedGpuMs=9,qualityScale=1,activePasses=GPU_PASS_ORDER,pressure=0,weights=GPU_PASS_DEFAULT_WEIGHTS}:GpuPassBudgetPlanInput={}):GpuPassBudgetPlan{const pressureFactor=1-clamp(pressure,0,1)*0.55,gpuBudget=Math.max(1,n(targetFrameMs,16.67)*0.72*clamp(qualityScale,0.5,1.1)*pressureFactor),allocations=allocateGpuPassBudget(gpuBudget,weights),passSet=new Set(activePasses.map(String)),enabled=GPU_PASS_ORDER.filter(name=>passSet.has(name)&&allocations[name]>0),overBudget=n(estimatedGpuMs)>gpuBudget,shed=(overBudget?(['debug','effects','water','post'] as GpuPassName[]).filter(name=>enabled.includes(name)).reverse():[]);const reductions:Readonly<Record<GpuPassName,number>>={debug:.2,effects:.12,water:.16,post:.2,base:0,shadow:0,foliage:0};let estimatedAfter=Math.max(0,n(estimatedGpuMs));for(const name of shed)estimatedAfter*=1-reductions[name];return Object.freeze({gpuBudgetMs:Number(gpuBudget.toFixed(3)),estimatedGpuMs:Number(n(estimatedGpuMs).toFixed(3)),estimatedAfterSheddingMs:Number(estimatedAfter.toFixed(3)),overBudget,allocations,enabled:Object.freeze(enabled),shed:Object.freeze(shed)});}
export interface GpuPassBudgetController{readonly plan:(input?:GpuPassBudgetPlanInput)=>GpuPassBudgetPlan;readonly snapshot:()=>Readonly<{frame:number;last:GpuPassBudgetPlan|null;history:readonly GpuPassBudgetPlan[]}>;readonly reset:()=>void;readonly dispose:()=>void;}
export function createGpuPassBudgetController(options:GpuPassBudgetPlanInput={}):GpuPassBudgetController{let frame=0,disposed=false;let last:GpuPassBudgetPlan|null=null;const history:GpuPassBudgetPlan[]=[];return Object.freeze({plan(input:GpuPassBudgetPlanInput={}):GpuPassBudgetPlan{if(disposed)throw new Error('GPU_PASS_BUDGET_CONTROLLER_DISPOSED');frame+=1;last=Object.freeze({...buildGpuPassBudgetPlan({...options,...input}),frame}) as GpuPassBudgetPlan;history.push(last);while(history.length>16)history.shift();return last;},snapshot:()=>Object.freeze({frame,last,history:Object.freeze(history.slice(-6))}),reset:()=>{frame=0;last=null;history.length=0;},dispose:()=>{disposed=true;last=null;history.length=0;}});}
export function validateGpuPassBudgetPlan(plan:GpuPassBudgetPlan|null|undefined):boolean{return Boolean(plan&&plan.gpuBudgetMs>=0&&plan.estimatedGpuMs>=0&&plan.estimatedAfterSheddingMs>=0&&new Set(plan.enabled).size===plan.enabled.length&&plan.enabled.every(name=>GPU_PASS_ORDER.includes(name)));}
