export const GPU_RESOURCE_TIERS=Object.freeze(['compatibility','performance','balanced','high','ultra']);
export const GPU_RESOURCE_POLICY=Object.freeze({id:'gpu-resource-arbiter-r2-2026-09-16',maxTextureBytes:512*1024*1024,maxBufferBytes:256*1024*1024,maxTransientBytes:128*1024*1024,maxBatches:512,maxDrawCalls:2200,maxTriangles:6000000});
const freeze=Object.freeze;
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const int=(v,d=0)=>Math.max(0,Math.floor(num(v,d)));
const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,num(v,a)));
const text=(v,d='')=>String(v??d).trim()||d;
const rank=freeze(Object.fromEntries(GPU_RESOURCE_TIERS.map((v,i)=>[v,i])));
const factor=freeze({compatibility:.36,performance:.52,balanced:.68,high:.84,ultra:1});
export function normalizeGpuResourceDemand(raw={}){const tier=text(raw.tier,'balanced');return freeze({id:text(raw.id,'resource'),tier:rank[tier]!=null?tier:'balanced',textureBytes:int(raw.textureBytes),bufferBytes:int(raw.bufferBytes),transientBytes:int(raw.transientBytes),batches:int(raw.batches),drawCalls:int(raw.drawCalls),triangles:int(raw.triangles),streaming:clamp(raw.streaming),visibility:clamp(raw.visibility),critical:clamp(raw.critical),pinned:Boolean(raw.pinned),resident:Boolean(raw.resident)});}
export function normalizeGpuBudget(raw={}){const requested=text(raw.tier,'balanced');const tier=rank[requested]!=null?requested:'balanced';const f=factor[tier];return freeze({tier,textureBytes:Math.max(1,Math.floor(num(raw.textureBytes,GPU_RESOURCE_POLICY.maxTextureBytes)*f)),bufferBytes:Math.max(1,Math.floor(num(raw.bufferBytes,GPU_RESOURCE_POLICY.maxBufferBytes)*f)),transientBytes:Math.max(1,Math.floor(num(raw.transientBytes,GPU_RESOURCE_POLICY.maxTransientBytes)*f)),maxBatches:Math.max(1,Math.min(512,int(raw.maxBatches,Math.floor(512*f)))),maxDrawCalls:Math.max(64,Math.min(2200,int(raw.maxDrawCalls,Math.floor(2200*f)))),maxTriangles:Math.max(100000,Math.min(6000000,int(raw.maxTriangles,Math.floor(6000000*f))))});}
export function scoreGpuDemand(raw,budget){const d=normalizeGpuResourceDemand(raw);const p=c=>clamp(c/Math.max(1,budget));return Number(clamp(p(d.textureBytes/budget.textureBytes)*.2+p(d.bufferBytes/budget.bufferBytes)*.18+p(d.transientBytes/budget.transientBytes)*.12+p(d.drawCalls/budget.maxDrawCalls)*.2+p(d.triangles/budget.maxTriangles)*.2+d.critical*.06+d.streaming*.02+d.visibility*.02).toFixed(5));}
export function compareGpuDemand(a,b){if(b.score!==a.score)return b.score-a.score;if(b.critical!==a.critical)return b.critical-a.critical;if(b.pinned!==a.pinned)return Number(b.pinned)-Number(a.pinned);if(b.resident!==a.resident)return Number(b.resident)-Number(a.resident);return a.id.localeCompare(b.id);}
export function planGpuResources(resources=[],rawBudget={}){const budget=normalizeGpuBudget(rawBudget);const rankedResources=(Array.isArray(resources)?resources:[]).map(normalizeGpuResourceDemand).map(x=>freeze({...x,score:scoreGpuDemand(x,budget)})).sort(compareGpuDemand);let textureBytes=0,bufferBytes=0,transientBytes=0,batches=0,drawCalls=0,triangles=0;const accepted=[],deferred=[];for(const item of rankedResources){const fits=textureBytes+item.textureBytes<=budget.textureBytes&&bufferBytes+item.bufferBytes<=budget.bufferBytes&&transientBytes+item.transientBytes<=budget.transientBytes&&batches+item.batches<=budget.maxBatches&&drawCalls+item.drawCalls<=budget.maxDrawCalls&&triangles+item.triangles<=budget.maxTriangles;if(fits||item.critical>=.95||item.pinned){accepted.push(freeze({...item,reason:item.critical>=.95?'critical':item.pinned?'pinned':'within-budget'}));textureBytes+=item.textureBytes;bufferBytes+=item.bufferBytes;transientBytes+=item.transientBytes;batches+=item.batches;drawCalls+=item.drawCalls;triangles+=item.triangles;}else deferred.push(freeze({...item,reason:'budget-deferred'}));}const usage=freeze({textureBytes,bufferBytes,transientBytes,batches,drawCalls,triangles});return freeze({policyId:GPU_RESOURCE_POLICY.id,tier:budget.tier,budget,accepted:freeze(accepted),deferred:freeze(deferred),usage,utilization:freeze({texture:clamp(textureBytes/budget.textureBytes),buffer:clamp(bufferBytes/budget.bufferBytes),transient:clamp(transientBytes/budget.transientBytes),batches:clamp(batches/budget.maxBatches),drawCalls:clamp(drawCalls/budget.maxDrawCalls),triangles:clamp(triangles/budget.maxTriangles)})});}
export function validateGpuResourcePlan(plan){const e=[];if(plan?.policyId!==GPU_RESOURCE_POLICY.id)e.push('policyId');if(!Array.isArray(plan?.accepted)||!Array.isArray(plan?.deferred))e.push('arrays');for(const key of ['textureBytes','bufferBytes','transientBytes','batches','drawCalls','triangles'])if(!Number.isFinite(plan?.usage?.[key])||plan.usage[key]<0)e.push(`usage:${key}`);return freeze({valid:e.length===0,errors:freeze(e)});}
export function gpuResourcePlanDigest(plan){const payload=[plan?.tier??'',JSON.stringify(plan?.usage??{}),...(plan?.accepted??[]).map(x=>`${x.id}:${x.reason}:${x.score}`),...(plan?.deferred??[]).slice(0,64).map(x=>x.id)].join('|');let h=2166136261;for(const ch of payload){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return (h^(h>>>16)).toString(16).padStart(8,'0');}
export function buildGpuPressureSnapshot(plan){const u=plan?.utilization??{};return freeze({tier:plan?.tier??'balanced',residentCount:plan?.accepted?.length??0,deferredCount:plan?.deferred?.length??0,maxPressure:clamp(Math.max(u.texture??0,u.buffer??0,u.transient??0,u.batches??0,u.drawCalls??0,u.triangles??0)),criticalPinned:(plan?.accepted??[]).filter(x=>x.reason==='critical'||x.reason==='pinned').length});}
export function mergeGpuResourcePlans(a,b){const all=[...(a?.accepted??[]),...(b?.accepted??[])];const merged=Array.from(new Map(all.map(x=>[x.id,x])).values()).sort(compareGpuDemand);return freeze({accepted:freeze(merged),mergedCount:merged.length,sourceDigests:freeze([gpuResourcePlanDigest(a),gpuResourcePlanDigest(b)])});}
export function limitGpuResourceDemand(raw,budget){const d=normalizeGpuResourceDemand(raw);return freeze({...d,textureBytes:Math.min(d.textureBytes,budget.textureBytes),bufferBytes:Math.min(d.bufferBytes,budget.bufferBytes),transientBytes:Math.min(d.transientBytes,budget.transientBytes),batches:Math.min(d.batches,budget.maxBatches),drawCalls:Math.min(d.drawCalls,budget.maxDrawCalls),triangles:Math.min(d.triangles,budget.maxTriangles)});}
