#!/usr/bin/env node
'use strict';
const fs=require('fs'),http=require('http'),path=require('path');
const ROOT=process.cwd(),ARTIFACT_DIR=path.join(ROOT,'artifacts','run259-editor-micro-scale-final');
const MICRO=0.000001,PRE_SHRINK=0.000010;
function assert(v,m){if(!v)throw new Error(m)}function near(a,b,e=1e-12){return Math.abs(Number(a)-Number(b))<=e}
function pw(){for(const id of ['playwright','/opt/node22/lib/node_modules/playwright']){try{return require(id)}catch{}}return null}
function ct(f){const e=path.extname(f).toLowerCase();if(e==='.html')return'text/html; charset=utf-8';if(e==='.js'||e==='.mjs')return'text/javascript; charset=utf-8';if(e==='.css')return'text/css; charset=utf-8';if(e==='.json'||e==='.webmanifest')return'application/json; charset=utf-8';if(e==='.png')return'image/png';if(e==='.jpg'||e==='.jpeg')return'image/jpeg';if(e==='.webp')return'image/webp';if(e==='.glb')return'model/gltf-binary';if(e==='.gltf')return'model/gltf+json';if(e==='.fbx')return'application/octet-stream';return'application/octet-stream'}
function serve(){const s=http.createServer((q,r)=>{const c=decodeURIComponent(q.url.split('?')[0]);if(c==='/favicon.ico'){r.writeHead(204);r.end();return}const rel=c==='/'?'index.html':c.replace(/^\//,''),f=path.resolve(ROOT,rel),idx=path.join(f,'index.html');if(f.startsWith(ROOT+path.sep)&&fs.existsSync(f)&&fs.statSync(f).isDirectory()&&fs.existsSync(idx)){r.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});fs.createReadStream(idx).pipe(r);return}if(!f.startsWith(ROOT+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){r.writeHead(404);r.end('Not found');return}r.writeHead(200,{'content-type':ct(f),'cache-control':'no-store'});fs.createReadStream(f).pipe(r)});return new Promise(ok=>s.listen(0,'127.0.0.1',()=>ok(s)))}
(async()=>{const playwright=pw();assert(playwright,'Playwright unavailable');fs.mkdirSync(ARTIFACT_DIR,{recursive:true});const server=await serve(),browser=await playwright.chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(String(e)));
async function typeScale(id,value){const input=page.locator(`#${id}`);await input.click();await input.press('Control+A');await input.type(value,{delay:10});await input.press('Tab');await page.waitForTimeout(170)}async function typeAll(v){for(const id of ['we-scale-x','we-scale-y','we-scale-z'])await typeScale(id,v)}async function state(){return page.evaluate(()=>{const a=window.__WESTEROS_WORLD_EDITOR__,o=a?.getSelectedObject?.()||a?.editableObjects?.[0]||null;return{scale:o?.scale?.toArray?.()||null,values:['we-scale-x','we-scale-y','we-scale-z'].map(id=>document.getElementById(id)?.value??null),min:['we-scale-x','we-scale-y','we-scale-z'].map(id=>document.getElementById(id)?.min??null),step:['we-scale-x','we-scale-y','we-scale-z'].map(id=>document.getElementById(id)?.step??null),version:window.__WESTEROS_EDITOR_MICRO_SCALE__?.version??null,minimumScale:window.__WESTEROS_EDITOR_MICRO_SCALE__?.minimumScale??null,decimals:window.__WESTEROS_EDITOR_MICRO_SCALE__?.decimals??null}})}
try{await page.goto(`http://127.0.0.1:${server.address().port}/editor.html`,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__WESTEROS_WORLD_EDITOR__&&window.__WESTEROS_EDITOR_HISTORY__&&window.__WESTEROS_EDITOR_MICRO_SCALE__?.version===2&&window.__WESTEROS_WORLD_EDITOR__.editableObjects.length>=1,null,{timeout:120000});await page.locator('#we-hierarchy .we-hierarchy-item').first().click();const initial=await state();assert(initial.version===2&&near(initial.minimumScale,MICRO)&&initial.decimals===6,`policy mismatch ${JSON.stringify(initial)}`);assert(initial.min.every(v=>v==='0.000001')&&initial.step.every(v=>v==='0.000001'),`metadata mismatch ${JSON.stringify(initial)}`);
await typeAll('0.000001');const direct=await state();assert(direct.scale.every(v=>near(v,MICRO)),`direct scale failed ${JSON.stringify(direct)}`);assert(direct.values.every(v=>v==='0.000001'),`display failed ${JSON.stringify(direct)}`);const serialized=await page.evaluate(async()=>{const{serializeEditorScene}=await import('/src/3d/editor/EditorSceneSerializer.js'),a=window.__WESTEROS_WORLD_EDITOR__,s=serializeEditorScene(a.editableObjects,a.instanceManager.serialize(),a.getEditorState());return{scale:s.objects[0].transform.scale,json:JSON.stringify(s)}});assert(serialized.scale.every(v=>near(v,MICRO))&&serialized.json.includes('0.000001'),`serializer failed ${JSON.stringify(serialized.scale)}`);await page.screenshot({path:path.join(ARTIFACT_DIR,'01-direct-000001.png'),fullPage:true});
await typeAll('0.000010');const pre=await state();assert(pre.scale.every(v=>near(v,PRE_SHRINK)),`pre-shrink failed ${JSON.stringify(pre)}`);await page.click('#we-quick-shrink');await page.waitForFunction(x=>window.__WESTEROS_WORLD_EDITOR__.getSelectedObject?.()?.scale.toArray().every(v=>Math.abs(v-x)<1e-12),MICRO,{timeout:30000});const shrunk=await state();assert(shrunk.values.every(v=>v==='0.000001'),`quick shrink failed ${JSON.stringify(shrunk)}`);await page.screenshot({path:path.join(ARTIFACT_DIR,'02-quick-shrink-000001.png'),fullPage:true});await page.locator('#we-hierarchy .we-hierarchy-item').first().click();const reselected=await state();assert(reselected.scale.every(v=>near(v,MICRO))&&reselected.values.every(v=>v==='0.000001'),`reselection failed ${JSON.stringify(reselected)}`);await page.screenshot({path:path.join(ARTIFACT_DIR,'03-reselected-000001.png'),fullPage:true});assert(errors.length===0,`browser errors: ${errors.join(' | ')}`);console.log(`[checkRun259EditorMicroScaleBrowserFinal] PASS ${JSON.stringify({initial,direct,serializedScale:serialized.scale,pre,shrunk,reselected,screenshots:3})}`)}finally{await context.close();await browser.close();await new Promise(ok=>server.close(ok))}})().catch(e=>{console.error(`[checkRun259EditorMicroScaleBrowserFinal] FAIL: ${e.stack||e}`);process.exitCode=1});
