import assert from "node:assert/strict";
import { LIMITS, applyBoundedWaterMaterial, createAcceptanceManifest, deriveWaterResponse, isWaterSample, summarizeBatch } from "../src/3d/world/p0WaterSurfaceAdoptionV53.js";
const sample = (overrides = {}) => ({ x: 120, z: -80, waterClass: "lake", waterCoverage: 0.62, depth: 4.8, shorelineDistance: 3.4, waterConfidence: 0.98, cameraDistance: 32, ...overrides });
assert.equal(isWaterSample(sample()).accepted, true);
assert.equal(isWaterSample({ land: true, depth: 4 }).accepted, false);
assert.equal(isWaterSample({ waterCoverage: 0, waterClass: "lake" }).accepted, false);
assert.equal(isWaterSample({ waterClass: "unknown", depth: 0, coverage: 0 }).accepted, false);
const response = deriveWaterResponse(sample(), { seed: 41 });
assert.equal(response.accepted, true);
assert.equal(response.waterClass, "lake");
assert.ok(response.bands.deep > 0);
assert.ok(response.material.opacity >= LIMITS.minOpacity && response.material.opacity <= LIMITS.maxOpacity);
assert.ok(response.material.roughness >= LIMITS.minRoughness && response.material.roughness <= LIMITS.maxRoughness);
assert.ok(response.material.normalEnergy <= LIMITS.maxNormalEnergy);
assert.ok(response.material.foam <= LIMITS.maxFoam);
assert.ok(response.material.cyanSuppression <= LIMITS.maxCyan);
assert.equal(response.risk.rectangularWater, 0);
const repeatA = deriveWaterResponse(sample(), { seed: 41 });
const repeatB = deriveWaterResponse(sample(), { seed: 41 });
assert.deepEqual(repeatA, repeatB);
assert.notDeepEqual(repeatA.worldPhase, deriveWaterResponse(sample(), { seed: 42 }).worldPhase);
const shore = deriveWaterResponse(sample({ waterClass: "shore", depth: 0.2, shorelineDistance: 0.05, waterCoverage: 0.2 }), { seed: 41 });
assert.ok(shore.bands.wetEdge > 0 && shore.bands.foamCarrier > 0 && shore.material.foam > 0);
const deep = deriveWaterResponse(sample({ waterClass: "sea", depth: 30, shorelineDistance: 80, waterCoverage: 0.99 }), { seed: 41 });
assert.ok(deep.bands.deep > deep.bands.shallow);
assert.equal(deep.risk.rectangularWater, 1);
assert.equal(deriveWaterResponse({ x: "bad", depth: "bad", waterCoverage: "bad", waterConfidence: "bad" }).accepted, false);
const batch = summarizeBatch([sample(), sample({ waterClass: "river", depth: 0.8 }), sample({ waterCoverage: 0.99 }), { land: true }], { seed: 9, maxBatch: 3 });
assert.equal(batch.requested, 4);
assert.equal(batch.evaluated, 3);
assert.equal(batch.accepted, 3);
assert.equal(batch.riskCounts.rectangularWater, 1);
const target = {};
const applied = applyBoundedWaterMaterial(target, response);
assert.equal(applied.applied, true);
assert.equal(target.transparent, true);
assert.equal(target.opacity, response.material.opacity);
assert.equal(target.roughness, response.material.roughness);
assert.equal(target.userData.worldP0WaterAdoption.waterClass, "lake");
assert.equal(applyBoundedWaterMaterial(null, response).applied, false);
const manifest = createAcceptanceManifest({ seed: 41, maxBatch: 20 });
assert.equal(manifest.owner, "Buzul Muhafızı");
assert.equal(manifest.acceptance.resolution, "1536x1024");
assert.equal(manifest.acceptance.beforeAfterComparable, true);
assert.equal(manifest.editorRuntimeImport, false);
assert.equal(manifest.geometryCreation, false);
for (let index = 0; index < 160; index += 1) {
  const current = deriveWaterResponse(sample({ x: index * 13.7, z: -index * 4.3, depth: (index % 19) * 0.8, shorelineDistance: (index % 23) * 1.1, waterCoverage: (index % 10) / 10, waterClass: ["sea", "lake", "river"][index % 3] }), { seed: index });
  assert.equal(current.accepted, true);
  for (const value of Object.values(current.bands)) assert.ok(Number.isFinite(value));
  for (const value of Object.values(current.material)) assert.ok(Number.isFinite(value));
  assert.ok(current.material.opacity >= LIMITS.minOpacity && current.material.opacity <= LIMITS.maxOpacity);
  assert.ok(current.material.roughness >= LIMITS.minRoughness && current.material.roughness <= LIMITS.maxRoughness);
}
console.log("P0 water-surface adoption v53 checks passed");
