import assert from 'node:assert/strict';
import { TERRAIN_ENVIRONMENT_SPATIAL_POLICY, environmentSpatialNoise, distanceFalloff, forestCoreWeight, forestEcotoneWeight, groveOpeningWeight, moistureDistributionWeight, slopeDistributionWeight, rockExposureWeight, talusWeight, settlementEnvelopeWeight, snowDriftWeight, ecotoneComposition, sampleClusterPoint, deterministicSpatialOrdinal } from '../src/3d/world/terrainEnvironmentSpatialPolicy.js';
assert.equal(TERRAIN_ENVIRONMENT_SPATIAL_POLICY.deterministic,true);assert.equal(TERRAIN_ENVIRONMENT_SPATIAL_POLICY.noGeometryInstantiation,true);
assert.equal(distanceFalloff(0,0,10),1);assert.equal(distanceFalloff(20,0,10),0);assert.ok(distanceFalloff(5,0,10)>.4&&distanceFalloff(5,0,10)<.6);
assert.ok(forestCoreWeight(0,160)>forestCoreWeight(145,160));assert.ok(forestEcotoneWeight(145,160)>forestEcotoneWeight(0,160));
assert.notEqual(groveOpeningWeight(100,200,7),groveOpeningWeight(101,201,7));
assert.ok(moistureDistributionWeight({moisture:.8,biome:'wet-meadow',elevationMeters:20,waterDistanceMeters:5})>moistureDistributionWeight({moisture:.2,biome:'dry-upland',elevationMeters:240,waterDistanceMeters:80}));
assert.ok(slopeDistributionWeight({slopeDegrees:42,category:'rock'})>slopeDistributionWeight({slopeDegrees:5,category:'rock'}));assert.ok(slopeDistributionWeight({slopeDegrees:8,category:'tree'})>slopeDistributionWeight({slopeDegrees:50,category:'tree'}));
assert.ok(rockExposureWeight({slopeDegrees:62,ridgeWeight:.8,substrateRock:.8})>rockExposureWeight({slopeDegrees:5,ridgeWeight:0,substrateRock:0}));
assert.ok(talusWeight({slopeDegrees:34,heightMeters:180,distanceBelowRockFaceMeters:40,ridgeWeight:.7})>talusWeight({slopeDegrees:4,heightMeters:20,distanceBelowRockFaceMeters:200,ridgeWeight:0}));
assert.ok(settlementEnvelopeWeight({distanceMeters:60,roadDistanceMeters:8})>settlementEnvelopeWeight({distanceMeters:500,roadDistanceMeters:100}));
assert.ok(snowDriftWeight({snowWeight:.9,windward:.2,lee:.9,exposedRock:.1,slopeDegrees:35})>snowDriftWeight({snowWeight:.9,windward:.9,lee:.1,exposedRock:.8,slopeDegrees:65}));
const n1=environmentSpatialNoise(123.45,-67.89,19),n2=environmentSpatialNoise(123.45,-67.89,19);assert.deepEqual(n1,n2);
const pointA=sampleClusterPoint('tree-grove',100,200,20,160,7),pointB=sampleClusterPoint('tree-grove',100,200,20,160,7);assert.deepEqual(pointA,pointB);assert.notDeepEqual(pointA,sampleClusterPoint('tree-grove',100,200,20,160,8));
const tree=ecotoneComposition('tree',{worldX:100,worldZ:200,slopeDegrees:8,heightMeters:40,moisture:.64,waterDepth:0,biome:'forest',roadDistance:20,settlementDistance:320,distanceFromGroveCenterMeters:25,groveRadiusMeters:160,seed:19});
const edge=ecotoneComposition('tree',{worldX:1000,worldZ:1200,slopeDegrees:9,heightMeters:34,moisture:.64,waterDepth:0,biome:'forest-edge',roadDistance:20,settlementDistance:320,distanceFromGroveCenterMeters:150,groveRadiusMeters:160,seed:19});
assert.ok(tree.coreWeight>edge.coreWeight);assert.ok(edge.ecotoneWeight>tree.ecotoneWeight);assert.ok(tree.densityMultiplier>=0&&tree.densityMultiplier<=2.2);
assert.equal(deterministicSpatialOrdinal('birch',100,200,4),deterministicSpatialOrdinal('birch',100,200,4));
console.log(JSON.stringify({ok:true,policy:TERRAIN_ENVIRONMENT_SPATIAL_POLICY.id,deterministic:true}));
