import assert from 'node:assert/strict';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API } from '../src/3d/gameplay/settlementWorldCoverageTraversal.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_RISK_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalRisk.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ROUTE_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalRoute.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_MILESTONE_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalMilestones.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalPacing.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_REPLAY_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalReplay.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNALS_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalSignals.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_COORDINATOR_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalCoordinator.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalAccessibility.js';
import { SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIO_API } from '../src/3d/gameplay/settlementWorldCoverageTraversalScenarios.js';

const apis=[
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_RISK_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ROUTE_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_MILESTONE_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_REPLAY_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNALS_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_COORDINATOR_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_API,
  SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIO_API,
];
for(const api of apis){
  assert.equal(typeof api,'object');
  assert.equal(typeof api.version,'number');
  assert.ok(api.version>=1);
  assert.equal(Object.isFrozen(api),true);
}
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API.laneCount,10);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API.phaseCount,6);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_RISK_API.factorCount,10);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ROUTE_API.modes.length,5);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_MILESTONE_API.count,10);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_API.states.length,6);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_REPLAY_API.maxFrames,16);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNALS_API.maxPrimary,4);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_COORDINATOR_API.states.length,8);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_API.modes.length,5);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIO_API.count,70);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API.create);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API.select);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API.validate);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API.summary);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_API.replay);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_RISK_API.create);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_RISK_API.validate);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_RISK_API.summary);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ROUTE_API.create);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ROUTE_API.compare);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_MILESTONE_API.create);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_PACING_API.create);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_REPLAY_API.replay);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SIGNALS_API.create);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_COORDINATOR_API.create);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_ACCESSIBILITY_API.create);
assert.ok(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIO_API.find);
console.log('Settlement World Coverage Traversal APIs: PASS');
