import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { COMBAT_PRESENTATION_ASSETS, auditCombatPresentationAssets } from '../src/3d/nextgen/combatPresentationAssetsV1.ts';
import { CombatPresentationDirector, validateCombatPresentationFrame } from '../src/3d/nextgen/combatPresentationV1.ts';
import { CombatPresentationQueue } from '../src/3d/nextgen/combatPresentationQueueV1.ts';

const player = await readFile(new URL('../src/3d/nextgen/combatPresentationV1.ts', import.meta.url), 'utf8');
const queue = await readFile(new URL('../src/3d/nextgen/combatPresentationQueueV1.ts', import.meta.url), 'utf8');
const replay = await readFile(new URL('../src/3d/nextgen/combatPresentationReplayV1.ts', import.meta.url), 'utf8');
const accessibility = await readFile(new URL('../src/3d/nextgen/combatPresentationAccessibilityV1.ts', import.meta.url), 'utf8');
assert.match(player, /class CombatPresentationDirector/);
assert.match(player, /hitstopTicks/);
assert.match(player, /haptics/);
assert.match(player, /cameraShake/);
assert.match(queue, /maxDispatchPerFrame/);
assert.match(replay, /compareCombatPresentationRecordings/);
assert.match(accessibility, /projectCombatAccessibility/);
const audit = auditCombatPresentationAssets(COMBAT_PRESENTATION_ASSETS);
assert.ok(audit.total >= 10);
assert.ok(audit.missingCombatVfx > 0);
assert.ok(audit.missingCombatAudio > 0);
const director = new CombatPresentationDirector();
const event = { tick: 1, type: 'critical', sourceId: 1, targetId: 2, attackId: 'heavy-1', damage: 50, poiseDamage: 20 };
const frame = director.ingest([event], { states: [] });
assert.equal(validateCombatPresentationFrame(frame).valid, true);
const dispatchQueue = new CombatPresentationQueue();
assert.equal(dispatchQueue.enqueue(frame.cues, 'gamepad', frame.tick), 1);
assert.equal(dispatchQueue.dispatch(frame.tick).length, 1);
console.log(JSON.stringify({ pass: true, presentationVersion: 1, assetAudit: audit, cueCount: frame.cues.length, dispatchCount: 1 }));