import { strict as assert } from 'node:assert';
import { buildSettlementAccessibilityModel, buildSettlementFocusOrder, buildSettlementActionLabel, buildSettlementAriaAction, buildSettlementPanelSemantics, buildSettlementSectionLabels, buildSettlementLiveRegion, buildSettlementKeyboardHints, validateSettlementAccessibilityModel, cloneSettlementAccessibilityModel } from '../src/3d/gameplay/settlementCampaignAccessibility.js';
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks+=1;};const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
const view={version:1,contentVersion:2,revision:7,panel:'craft',activeService:{id:'blacksmith',label:'Demirci'},availableActions:['talk','trade','craft','equip'],feedback:{status:'blocked',action:'craft',message:'Malzeme eksik',code:'missing-material'}};
const model=buildSettlementAccessibilityModel(view);eq(model.version,1,'accessibility-version');ok(validateSettlementAccessibilityModel(model).ok,'accessibility-valid');eq(model.panel.title,'Demircilik ve Üretim','panel-title');ok(model.panel.headingId.length>0,'heading-id');ok(model.actions.some(v=>v.action==='craft'&&v.disabled),'disabled-craft');eq(model.liveRegion.role,'alert','error-live-region');eq(model.liveRegion.ariaLive,'assertive','assertive-live-region');ok(model.keyboard.some(v=>v.key==='Escape'),'escape-hint');
const order=buildSettlementFocusOrder(view.availableActions);eq(order.join('|'),'talk|trade|craft|equip','focus-order');eq(buildSettlementActionLabel('craft',{service:'blacksmith'}),'Üret · blacksmith','action-label');const aria=buildSettlementAriaAction('craft',{service:'Demirci',enabled:false});eq(aria.disabled,true,'aria-disabled');eq(aria.tabIndex,-1,'aria-tab-index');
const panels=buildSettlementPanelSemantics('travel',{service:'gate'});eq(panels.title,'Seyahat','travel-panel');ok(panels.regionLabelledBy.includes('travel'),'travel-region');const sections=buildSettlementSectionLabels(view.availableActions);ok(sections.some(v=>v.label==='Üretim'),'craft-section');ok(sections.some(v=>v.label==='Ekonomi'),'economy-section');const live=buildSettlementLiveRegion({status:'success',message:'Tamam'});eq(live.role,'status','success-live-region');eq(live.ariaLive,'polite','polite-live-region');eq(buildSettlementKeyboardHints().length,5,'keyboard-hint-count');
const cloned=cloneSettlementAccessibilityModel(view);ok(JSON.stringify(cloned)===JSON.stringify(buildSettlementAccessibilityModel(view)),'clone-deterministic');const ready=buildSettlementAccessibilityModel({...view,feedback:null});ok(ready.actions.every(v=>v.disabled===false),'ready-actions-enabled');ok(validateSettlementAccessibilityModel({...ready,actions:'bad'}).ok===false,'invalid-actions-rejected');
console.log(`SETTLEMENT_CAMPAIGN_ACCESSIBILITY_OK checks=${checks}`);
