import { strict as assert } from 'node:assert';
import { listSettlementEpisodes,getSettlementEpisode } from '../src/3d/gameplay/settlementEpisodeContent.js';
import { listSettlementEpisodeDialogue,getSettlementEpisodeDialogueScene } from '../src/3d/gameplay/settlementEpisodeDialogueContent.js';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';
import { buildSettlementEpisodePresentation } from '../src/3d/gameplay/settlementEpisodePresentationModel.js';
import { getSettlementEpisodeHandoffCase,getSettlementEpisodeHandoffCasesForEpisode,buildSettlementEpisodeHandoffManifest,validateSettlementEpisodeHandoffContract,resolveSettlementEpisodeHandoff,listSettlementEpisodeHandoffCases } from '../src/3d/gameplay/settlementEpisodeHandoffContract.js';

let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks+=1;};const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
const validation=validateSettlementEpisodeHandoffContract();ok(validation.ok,'contract-valid');eq(validation.errors.length,0,'contract-errors-zero');eq(validation.caseCount,48,'contract-case-count');eq(validation.episodeCount,6,'contract-episode-count');eq(validation.actionCount,13,'contract-action-count');
const manifest=buildSettlementEpisodeHandoffManifest();ok(Object.isFrozen(manifest),'manifest-frozen');eq(manifest.cases.length,48,'manifest-cases');eq(JSON.stringify(manifest),JSON.stringify(buildSettlementEpisodeHandoffManifest()),'manifest-deterministic');
eq(listSettlementEpisodeHandoffCases().length,48,'case-list');eq(new Set(listSettlementEpisodeHandoffCases()).size,48,'case-list-unique');
for(const episodeId of listSettlementEpisodes()){
 const episode=getSettlementEpisode(episodeId);const cases=getSettlementEpisodeHandoffCasesForEpisode(episodeId);eq(cases.length,8,`episode-cases:${episodeId}`);eq(cases.map((entry)=>entry.stepId).join('|'),episode.beats.map((beat)=>beat.stepId).join('|'),`episode-order:${episodeId}`);
 for(const entry of cases){
  const beat=episode.beats.find((item)=>item.stepId===entry.stepId);ok(beat,`beat-present:${entry.stepId}`);eq(entry.action,beat.action,`action-parity:${entry.stepId}`);eq(entry.service,beat.service,`service-parity:${entry.stepId}`);
  const handoff=resolveSettlementEpisodeHandoff(entry.stepId,{nodeId:entry.service,itemId:'iron_ore',recipeId:'iron_sword',routeId:'north_gate'});ok(handoff.ok,`handoff:${entry.stepId}`);eq(handoff.episodeId,episodeId,`handoff-episode:${entry.stepId}`);eq(handoff.panel,entry.panel,`handoff-panel:${entry.stepId}`);eq(handoff.runtimeAction,entry.runtimeAction,`handoff-action:${entry.stepId}`);
  const missing=entry.inputKey==='nodeId'?resolveSettlementEpisodeHandoff(entry.stepId,{nodeId:''}):entry.inputKey==='itemId'?resolveSettlementEpisodeHandoff(entry.stepId,{itemId:''}):entry.inputKey==='recipeId'?resolveSettlementEpisodeHandoff(entry.stepId,{recipeId:''}):resolveSettlementEpisodeHandoff(entry.stepId,{routeId:''});eq(missing.ok,false,`missing-input:${entry.stepId}`);eq(missing.reason,'required-input-missing',`missing-reason:${entry.stepId}`);
  const dialogue=getSettlementEpisodeDialogueScene(episodeId,entry.stepId);ok(dialogue,`dialogue-link:${entry.stepId}`);eq(dialogue.action,entry.action,`dialogue-action:${entry.stepId}`);eq(dialogue.choices.length,3,`dialogue-choices:${entry.stepId}`);
 }
}
const runtime={open(service,panel){return{ok:true,view:{activeService:service,panel,route:[service],history:[],feedback:null,lastAction:null}};},async execute(action,input){return{ok:true,action,nodeId:input.nodeId,view:{activeService:input.nodeId,panel:'overview',history:[],feedback:null,lastAction:{action,episodeId:input.episodeId,episodeStepId:input.episodeStepId}}};},view(){return{activeService:'blacksmith',panel:'quests',route:[],history:[],feedback:null,lastAction:null};},close(){return{ok:true};}};
const director=createSettlementEpisodeDirector({runtime,now:()=>10});director.openEpisode('iron_and_oath');const initial=director.snapshot();const presentation=buildSettlementEpisodePresentation(initial);ok(presentation.primary,'presentation-primary');const currentCase=getSettlementEpisodeHandoffCase('iron-01');eq(presentation.primary.action.id,currentCase.action,'presentation-action-parity');eq(presentation.primary.service.id,currentCase.service,'presentation-service-parity');
for(const stepId of ['iron-05','market-02','market-06','road_watch','watch-02']){const id=stepId==='road_watch'?'watch-01':stepId;const source=id.startsWith('market-')?'market_routes':id.startsWith('watch-')?'road_watch':'iron_and_oath';const beat=getSettlementEpisode(source).beats.find((entry)=>entry.stepId===id);if(!beat)continue;director.setCursor(getSettlementEpisode(source).beats.findIndex((entry)=>entry.stepId===id));const view=buildSettlementEpisodePresentation(director.snapshot());const contract=getSettlementEpisodeHandoffCase(id);eq(view.primary.action.id,contract.action,`ux-action:${id}`);eq(view.primary.service.id,contract.service,`ux-service:${id}`);}
const unknown=getSettlementEpisodeHandoffCase('not-a-real-step');eq(unknown,null,'unknown-case-null');const unknownResolve=resolveSettlementEpisodeHandoff('not-a-real-step',{});eq(unknownResolve.ok,false,'unknown-resolve');eq(unknownResolve.reason,'unknown-step','unknown-resolve-reason');
const dialogueIds=listSettlementEpisodeDialogue();eq(dialogueIds.length,6,'dialogue-contract-episodes');for(const id of dialogueIds)eq(getSettlementEpisode(id).beats.length,getSettlementEpisodeDialogueSafe(id).length,`dialogue-beat-parity:${id}`);
function getSettlementEpisodeDialogueSafe(id){return Array.isArray((()=>{const e=getSettlementEpisode(id);return e?.beats;})())?getSettlementEpisode(id).beats:[];}
console.log(`SETTLEMENT_EPISODE_HANDOFF_CONTRACT_OK checks=${checks} cases=48`);
