#!/usr/bin/env node
const { startStaticServer, loadPlaywright } = require('./devServerHelper.js');
function assert(v,m){if(!v)throw new Error(m);}
async function main(){
 const pw=loadPlaywright();if(!pw){console.error('[checkWindGrassContract] SKIP: Playwright unavailable.');process.exit(2);}const server=await startStaticServer();const {port}=server.address();const browser=await pw.chromium.launch({headless:true});
 try{const page=await browser.newPage({viewport:{width:1280,height:720}});await page.goto(`http://127.0.0.1:${port}/game3d.html`,{waitUntil:'domcontentloaded',timeout:15000});const result=await page.evaluate(async()=>{
  const THREE=await import('three');const {createWindGrassRun178}=await import('/src/3d/sceneManager.js');const {disposeVegetation}=await import('/src/3d/world/vegetation.js');const fail=(v,m)=>{if(!v)throw new Error(m);};
  const sampler=()=>20,seats=[{x:0,z:0}],roadEdges=[{points:[{x:-1000,z:0},{x:1000,z:0}]}],opts={sampleHeightMeters:sampler,seaLevelMeters:6,seed:1337,seats,roadEdges,isMobileClass:true,centerX:260,centerZ:260};
  const a=createWindGrassRun178(opts),b=createWindGrassRun178(opts),desktop=createWindGrassRun178({...opts,isMobileClass:false});fail(a.mesh.count>0&&a.mesh.count<=1200,`mobile count ${a.mesh.count}`);fail(desktop.mesh.count>a.mesh.count&&desktop.mesh.count<=4000,`desktop/mobile counts ${desktop.mesh.count}/${a.mesh.count}`);fail(a.group.children.length===1&&a.mesh.isInstancedMesh,'grass must be one InstancedMesh');fail(a.mesh.geometry.getAttribute('run178Flex')?.count>0,'flex attribute missing');fail(a.mesh.geometry.getAttribute('run178Phase')?.count>0,'phase attribute missing');
  const aa=Array.from(a.mesh.instanceMatrix.array.slice(0,a.mesh.count*16)),bb=Array.from(b.mesh.instanceMatrix.array.slice(0,b.mesh.count*16));fail(a.mesh.count===b.mesh.count&&aa.every((v,i)=>v===bb[i]),'same seed/cell grass is not bit-identical');
  const m=new THREE.Matrix4();for(let i=0;i<a.mesh.count;i++){a.mesh.getMatrixAt(i,m);const e=m.elements,x=e[12],z=e[14];fail(Math.hypot(x,z)>=100-1e-5,`seat exclusion failed ${x},${z}`);if(x>=-1000&&x<=1000)fail(Math.abs(z)>=10-1e-5,`road exclusion failed ${x},${z}`);}
  const shader={uniforms:{},vertexShader:'#include <common>\nvoid main(){\n#include <begin_vertex>\n}',fragmentShader:'#include <common>\nvoid main(){vec4 diffuseColor=vec4(1.0);\n#include <color_fragment>\n}'};a.mesh.material.onBeforeCompile(shader);for(const t of ['uRun178WindTime','run178Flex','run178Wave','vRun178GrassVariation'])fail(shader.vertexShader.includes(t),`vertex shader missing ${t}`);fail(shader.fragmentShader.includes('vRun178GrassVariation'),'fragment variation missing');const oldCell={...a.group.userData.run178WindGrass.centerCell};a.mesh.onBeforeRender(null,null,{position:new THREE.Vector3(720,100,720)});fail(shader.uniforms.uRun178WindTime.value>0,'wind time not advanced');fail(a.group.userData.run178WindGrass.centerCell.x!==oldCell.x||a.group.userData.run178WindGrass.centerCell.z!==oldCell.z,'camera recenter did not stream grass');
  const water=createWindGrassRun178({...opts,sampleHeightMeters:()=>6,centerX:0,centerZ:0});fail(water.mesh.count===0,`shore/water exclusion expected 0, got ${water.mesh.count}`);
  let gd=0,md=0;a.mesh.geometry.addEventListener('dispose',()=>gd++);a.mesh.material.addEventListener('dispose',()=>md++);const holder=new THREE.Group();holder.userData.run178GrassGroup=a.group;disposeVegetation(holder);fail(gd===1&&md===1,`grass teardown ${gd}/${md}`);for(const f of [b,desktop,water]){const h=new THREE.Group();h.userData.run178GrassGroup=f.group;disposeVegetation(h);}return{mobile:a.mesh.count,desktop:desktop.mesh.count,triangles:a.mesh.geometry.index.count/3,oldCell,newCell:a.group.userData.run178WindGrass.centerCell};
 });
 assert(result.mobile<=1200,'mobile cap');console.log(`[checkWindGrassContract] PASS: one InstancedMesh, mobile ${result.mobile}/1200 patches, desktop ${result.desktop}/4000, ${result.triangles} triangles/patch; deterministic road/seat/water exclusion, camera-cell streaming, GPU two-frequency wind + teardown PASS.`);
 }finally{await browser.close();await new Promise(r=>server.close(r));}}
main().catch(e=>{console.error(`[checkWindGrassContract] FAIL: ${e?.stack||e}`);process.exit(1);});