#!/usr/bin/env node
import assert from 'node:assert/strict';
import {applyRestorePlan,buildGameplaySnapshot,createRestorePlan,summarizeGameplaySnapshot,validateGameplaySnapshot} from '../src/3d/persistence/saveGameSnapshotAdapter.js';
const source={seed:77,unexpectedRenderer:{gl:true},player:{id:'hero',position:{x:1.23456,y:4.56789,z:-8.76543},health:999999,stamina:-5,level:7,experience:12345,inventory:Array.from({length:200},(_,i)=>({id:`item-${i}`,quantity:2})),equipment:{weapon:{id:'sword',renderer:{}}}},world:{day:3,timeOfDayMinutes:1500,currentSettlementId:'winterfell',visitedSettlementIds:['winterfell'],flags:{gateOpen:true,domNode:{}}},quests:Array.from({length:160},(_,i)=>({id:`quest-${i}`,state:'active',progress:i/100})),recentEvents:Array.from({length:50},(_,i)=>({id:`event-${i}`,type:'combat',at:i}))};
const snap=buildGameplaySnapshot(source,{capturedAtMs:1000});
assert.equal(snap.schema,'aapw.gameplay-snapshot');assert.equal(snap.version,2);assert.equal(snap.player.id,'hero');assert.deepEqual(snap.player.position,{x:1.235,y:4.568,z:-8.765});assert.equal(snap.player.health,100000);assert.equal(snap.player.stamina,0);assert.equal(snap.player.inventory.length,128);assert.equal(snap.quests.length,128);assert.equal(snap.recentEvents.length,32);assert.equal('unexpectedRenderer' in snap,false);assert.equal(snap.player.equipment.weapon,'sword');assert.equal(snap.world.timeOfDayMinutes,1439);assert.equal(validateGameplaySnapshot(snap).valid,true);
assert.equal(validateGameplaySnapshot(snap,{expectedSeed:77}).valid,true);assert.equal(validateGameplaySnapshot(snap,{expectedSeed:99}).reason,'SEED');assert.equal(validateGameplaySnapshot({...snap,version:999}).reason,'VERSION');
const plan=createRestorePlan(snap,{expectedSeed:77});const calls=[];const result=applyRestorePlan(plan,{player(v,s){calls.push(['player',v.level,s])},world(v){calls.push(['world',v.day])},quests(v){calls.push(['quests',v.length])},recentEvents(v){calls.push(['events',v.length])}});assert.equal(result.applied,4);assert.deepEqual(calls,[['player',7,77],['world',3],['quests',128],['events',32]]);
const failure=applyRestorePlan(createRestorePlan(buildGameplaySnapshot({seed:1,player:{},world:{}})),{player(){throw new Error('apply-failed')}});assert.equal(failure.reason,'apply-failed');assert.equal(summarizeGameplaySnapshot(snap).valid,true);assert.equal(summarizeGameplaySnapshot({}).valid,false);
console.log('Save gameplay snapshot adapter R1 acceptance passed.');
