import assert from 'node:assert/strict';
import { buildLivingWorldFaunaThreatSnapshot, writeLivingWorldFaunaThreatTelemetry } from '../src/3d/gameplay/livingWorldFaunaThreatTelemetry.js';

const make = (id, x, z, flags = {}) => ({ id, species: 'wolf', controller: { object3D: { position: { x, z }, userData: {} }, ...flags } });
const entries = [make('far', 30, 0), make('near-react', 3, 4, { isReacting: true }), make('near-flee', 1, 1, { isFleeing: true })];
const first = buildLivingWorldFaunaThreatSnapshot(entries, { x: 0, z: 0 }, { radiusMeters: 10 });
const second = buildLivingWorldFaunaThreatSnapshot(entries, { x: 0, z: 0 }, { radiusMeters: 10 });
assert.deepEqual(first, second);
assert.equal(first.counts.fleeing, 1);
assert.equal(first.counts.reacting, 1);
assert.equal(first.counts.threat, 2);
assert.equal(first.actors[0].id, 'near-flee');
assert.equal(first.actors[2].inRadius, false);
const bounded = buildLivingWorldFaunaThreatSnapshot(new Set(Array.from({ length: 200 }, (_, index) => make(String(index), index, 0))), { x: 0, z: 0 }, { maxSamples: 16 });
assert.equal(bounded.actors.length, 16);
assert.equal(bounded.truncated, true);
const object3D = { userData: {} };
assert.equal(writeLivingWorldFaunaThreatTelemetry(object3D, first), true);
assert.deepEqual(object3D.userData.livingWorldFaunaThreat, { version: 1, threatCount: 2, fleeingCount: 1, reactingCount: 1, truncated: false });
assert.equal(writeLivingWorldFaunaThreatTelemetry(null, first), false);
console.log('living-world fauna threat telemetry contract: PASS');
