import assert from 'node:assert/strict';
import { createPlayerLocomotionAnticipationReplayTape, validatePlayerLocomotionAnticipationReplayTape, replayPlayerLocomotionAnticipationTape, replayPlayerLocomotionAnticipationSamples, comparePlayerLocomotionAnticipationReplayRuns, diffPlayerLocomotionAnticipationFrame, buildPlayerLocomotionAnticipationReplayCorpus, comparePlayerLocomotionAnticipationCorpora, createPlayerLocomotionAnticipationReplayDigest, auditPlayerLocomotionAnticipationReplay } from '../src/3d/gameplay/playerLocomotionAnticipationReplay.js';

function sample(i){const angle=(i%8)*Math.PI/4;return{velocity:{x:Math.sin(angle),y:Math.cos(angle)},facing:{x:0,y:1},planarSpeedMps:1+(i%9),slopeDegrees:i%6*7,turnRateDegreesPerSecond:i%12*41,deltaSeconds:1/60,surfaceConfidence:(i%10)/10,surfaceSlip:(i%5)/5};}
assert.equal(auditPlayerLocomotionAnticipationReplay().valid,true);
const source=Array.from({length:96},(_,i)=>sample(i));
const tape=createPlayerLocomotionAnticipationReplayTape(source,{name:'contract',seed:'55'});
assert.equal(validatePlayerLocomotionAnticipationReplayTape(tape).ok,true);assert.equal(tape.sampleCount,96);assert.equal(tape.samples.length,96);assert.equal(tape.metadata.name,'contract');assert.equal(tape.metadata.seed,'55');assert.equal(Object.isFrozen(tape),true);assert.equal(Object.isFrozen(tape.samples),true);
const replay=replayPlayerLocomotionAnticipationTape(tape);const replayAgain=replayPlayerLocomotionAnticipationTape(tape);assert.equal(replay.valid,true);assert.equal(replay.profilesValid,true);assert.equal(replay.frames.length,96);assert.equal(replay.finalState.frameCount,96);assert.equal(replay.fingerprint,replayAgain.fingerprint);assert.equal(comparePlayerLocomotionAnticipationReplayRuns(replay,replayAgain).equal,true);assert.equal(createPlayerLocomotionAnticipationReplayDigest(replay).sampleCount,96);
const copied=replayPlayerLocomotionAnticipationSamples(source.map((s)=>({...s,velocity:{...s.velocity},facing:{...s.facing}})),{name:'contract',seed:'55'});assert.equal(copied.fingerprint,replay.fingerprint);
for(const mutation of [{speedDelta:0.5},{turnDelta:80},{slopeDelta:10},{confidenceDelta:-0.3},{slipDelta:0.5}]){const changed=source.slice();changed[40]={...changed[40],planarSpeedMps:(changed[40].planarSpeedMps??0)+(mutation.speedDelta??0),turnRateDegreesPerSecond:(changed[40].turnRateDegreesPerSecond??0)+(mutation.turnDelta??0),slopeDegrees:(changed[40].slopeDegrees??0)+(mutation.slopeDelta??0),surfaceConfidence:(changed[40].surfaceConfidence??1)+(mutation.confidenceDelta??0),surfaceSlip:(changed[40].surfaceSlip??0)+(mutation.slipDelta??0)};const changedReplay=replayPlayerLocomotionAnticipationSamples(changed,{name:'contract',seed:'55'});const comparison=comparePlayerLocomotionAnticipationReplayRuns(replay,changedReplay);assert.equal(comparison.equal,false);assert.ok(comparison.differences.includes(40));assert.equal(diffPlayerLocomotionAnticipationFrame(replay,changedReplay,40).equal,false);}
const scenarios=Array.from({length:8},(_,scenario)=>({metadata:{name:`case-${scenario}`},samples:Array.from({length:24},(_,i)=>sample(scenario*24+i))}));const corpusA=buildPlayerLocomotionAnticipationReplayCorpus(scenarios);const corpusB=buildPlayerLocomotionAnticipationReplayCorpus(scenarios);assert.equal(corpusA.count,8);assert.equal(comparePlayerLocomotionAnticipationCorpora(corpusA,corpusB).equal,true);
const badVersion={...tape,version:'old'};assert.equal(validatePlayerLocomotionAnticipationReplayTape(badVersion).ok,false);const badSamples={...tape,samples:null};assert.equal(validatePlayerLocomotionAnticipationReplayTape(badSamples).ok,false);const badCount={...tape,sampleCount:95};assert.equal(validatePlayerLocomotionAnticipationReplayTape(badCount).ok,false);const capped=createPlayerLocomotionAnticipationReplayTape(Array.from({length:800},(_,i)=>sample(i)));assert.equal(capped.sampleCount,600);assert.equal(capped.samples.length,600);
console.log('PLAYER_LOCOMOTION_ANTICIPATION_REPLAY_CONTRACT_PASS');
