import assert from 'node:assert/strict';
import { TERRAIN_SURFACE_FABRIC_POLICY } from '../src/3d/world/terrainSurfaceFabric.js';
import { TERRAIN_ENVIRONMENT_PROFILE_POLICY } from '../src/3d/world/terrainEnvironmentProfiles.js';
import { TERRAIN_ENVIRONMENT_SCENE_BRIDGE_POLICY } from '../src/3d/world/terrainEnvironmentSceneBridge.js';
import { TERRAIN_ENVIRONMENT_ASSET_SOURCE_POLICY } from '../src/3d/world/terrainEnvironmentAssetSourceAdapter.js';
import { TERRAIN_ENVIRONMENT_ASSET_GEOGRAPHY_POLICY } from '../src/3d/world/terrainEnvironmentAssetGeographyMatrix.js';
import { TERRAIN_ENVIRONMENT_DISTRIBUTION_PLANNER_POLICY } from '../src/3d/world/terrainEnvironmentDistributionPlanner.js';
assert.equal(TERRAIN_SURFACE_FABRIC_POLICY.renderOnly,true);
assert.equal(TERRAIN_SURFACE_FABRIC_POLICY.canonicalHeightUnchanged,true);
assert.equal(TERRAIN_ENVIRONMENT_PROFILE_POLICY.editorRuntimeImportAllowed,false);
assert.equal(TERRAIN_ENVIRONMENT_PROFILE_POLICY.proceduralPlaceholderAllowed,false);
assert.equal(TERRAIN_ENVIRONMENT_SCENE_BRIDGE_POLICY.noGeometryReplacement,true);
assert.equal(TERRAIN_ENVIRONMENT_ASSET_SOURCE_POLICY.authoredOnly,true);
assert.equal(TERRAIN_ENVIRONMENT_ASSET_SOURCE_POLICY.placeholderAllowed,false);
assert.equal(TERRAIN_ENVIRONMENT_ASSET_GEOGRAPHY_POLICY.authoredAssetOnly,true);
assert.equal(TERRAIN_ENVIRONMENT_DISTRIBUTION_PLANNER_POLICY.noTerrainMutation,true);
assert.equal(TERRAIN_ENVIRONMENT_DISTRIBUTION_PLANNER_POLICY.neverUniformGrid,true);
assert.ok(TERRAIN_ENVIRONMENT_DISTRIBUTION_PLANNER_POLICY.minimumSeparationMeters.tree>0);
assert.ok(TERRAIN_ENVIRONMENT_DISTRIBUTION_PLANNER_POLICY.densityCapsPerKm2.tree>0);
console.log(JSON.stringify({ok:true,policies:6}));
