import { strict as assert } from 'node:assert';
import { buildSettlementEpisodePresentation, buildSettlementEpisodeActionBar, buildSettlementEpisodeProgressStrip, buildSettlementEpisodeBlockedNotice, buildSettlementEpisodeResourcePanel, buildSettlementEpisodeConditionsPanel, buildSettlementEpisodePerkReward, createSettlementEpisodePresentationProjector } from '../src/3d/gameplay/settlementEpisodePresentationModel.js';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';

let checks=0; const ok=(v,m)=>{assert.ok(v,m);checks+=1;}; const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;}; const deep=(a,b,m)=>{assert.deepEqual(a,b,m);checks+=1;};
function runtime(){ let state={activeService:null,panel:'overview',route:[],history:[],feedback:null,lastAction:null}; return {open(service,panel){state={...state,activeService:service,panel};return {ok:true,view:{...state}};},async execute(action,input){state={...state,lastAction:{action,nodeId:input.nodeId},history:[...state.history,{type:'action',action,stepId:input.episodeStepId}],feedback:{status:'success',code:'ok',message:'Tamamlandı.',action}};return {ok:true,action,nodeId:input.nodeId,view:{...state}};},close(){state={...state,activeService:null,panel:'overview'};return {ok:true};},view(){return {...state};},exportState(){return {version:1,runtimeVersion:1,contentVersion:2,panel:state.panel,activeService:state.activeService,route:state.route,history:state.history,requestIds:[],lastAction:state.lastAction,revision:0};},importState(){return {ok:true};}}; }
const director=createSettlementEpisodeDirector({runtime:runtime(),now:()=>50});
director.openEpisode('iron_and_oath');
let model=buildSettlementEpisodePresentation(director.snapshot());
ok(model,'model-created'); eq(model.episode.id,'iron_and_oath','episode-id'); eq(model.episode.beatCount,8,'beat-count'); eq(model.progress.percent,0,'initial-percent'); eq(model.primary.id,'iron-01','first-primary'); eq(model.primary.action.id,'talk','first-action'); eq(model.primary.service.id,'blacksmith','first-service'); ok(model.primary.objective,'objective-visible'); eq(model.footer.panel,'quests','panel-from-director');
const actionBar=buildSettlementEpisodeActionBar(model); ok(actionBar.length>=1,'action-bar-present'); ok(actionBar[0].current,'current-action-first'); eq(actionBar[0].id,'talk','current-action-id');
const progress=buildSettlementEpisodeProgressStrip(model); eq(progress.completed,0,'progress-completed'); eq(progress.total,8,'progress-total'); eq(progress.remaining,8,'progress-remaining'); eq(progress.percent,0,'progress-percent');
eq(buildSettlementEpisodeBlockedNotice(model),null,'no-block-notice');
const resources=buildSettlementEpisodeResourcePanel(model); eq(resources.visible,false,'no-resource-first-talk');
const conditions=buildSettlementEpisodeConditionsPanel(model); ok(conditions.visible,'conditions-visible'); eq(conditions.count,1,'condition-count'); eq(conditions.rows[0].id,'flag_01','condition-id');
eq(buildSettlementEpisodePerkReward(model),null,'reward-hidden-until-complete');
const projector=createSettlementEpisodePresentationProjector({now:()=>123}); const projectedA=projector.project(director.snapshot()); const projectedB=projector.project(director.snapshot()); eq(projectedA.ok,true,'project-ok'); eq(projectedA.model.primary.id,projectedB.model.primary.id,'projection-stable'); eq(projectedA.digest,projectedB.digest,'projection-digest-stable'); ok(Object.isFrozen(projectedA),'projection-frozen');
await director.executeCurrent({requestId:'presentation-1'}); model=buildSettlementEpisodePresentation(director.snapshot()); eq(model.progress.completed,1,'progress-after-action'); eq(model.progress.percent,13,'progress-rounding'); eq(model.primary.id,'iron-02','next-primary'); eq(model.primary.action.id,'talk','next-action');
const runtimeAfter=director.snapshot(); runtimeAfter.feedback={status:'blocked',code:'insufficient-copper',message:'Yetersiz bakır.'}; const blockedModel=buildSettlementEpisodePresentation(runtimeAfter); const blocked=buildSettlementEpisodeBlockedNotice(blockedModel); ok(blocked.visible,'blocked-visible'); eq(blocked.severity,'warning','blocked-severity'); eq(blocked.title,'insufficient-copper','blocked-title'); eq(blocked.message,'Yetersiz bakır.','blocked-message');
const marketDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>1}); marketDirector.openEpisode('market_routes'); marketDirector.setCursor(1); const marketModel=buildSettlementEpisodePresentation(marketDirector.snapshot()); const marketResource=buildSettlementEpisodeResourcePanel(marketModel); ok(marketResource.visible,'market-resource-visible'); eq(marketResource.kind,'item','market-item-resource'); eq(marketResource.title,'Ekmek','market-item-title');
const craftDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>1}); craftDirector.openEpisode('winter_supply'); craftDirector.setCursor(3); const craftModel=buildSettlementEpisodePresentation(craftDirector.snapshot()); const craftResource=buildSettlementEpisodeResourcePanel(craftModel); eq(craftResource.kind,'recipe','craft-resource'); ok(craftResource.rows.some((row)=>row[0]==='Malzemeler'),'craft-ingredients');
const travelDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>1}); travelDirector.openEpisode('stable_master'); travelDirector.setCursor(4); const travelModel=buildSettlementEpisodePresentation(travelDirector.snapshot()); const travelResource=buildSettlementEpisodeResourcePanel(travelModel); eq(travelResource.kind,'route','travel-resource'); eq(travelResource.rows[0][0],'Hedef','travel-target');
const rewardDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>1}); rewardDirector.openEpisode('hearth_and_home'); rewardDirector.setCursor(8); const rewardModel=buildSettlementEpisodePresentation(rewardDirector.snapshot()); ok(rewardModel.progress.isComplete,'reward-complete'); ok(rewardModel.reward,'reward-visible'); const rewardPerk=buildSettlementEpisodePerkReward(rewardModel); ok(rewardPerk,'reward-perk'); eq(rewardPerk.id,'keepsake','keepsake-reward');
const missingSnapshot=buildSettlementEpisodePresentation({phase:'idle',episode:null,beat:null,cursor:0,feedback:null}); eq(missingSnapshot.episode,null,'missing-episode-safe'); eq(missingSnapshot.primary,null,'missing-primary-safe'); eq(missingSnapshot.progress.beatCount,0,'missing-progress-safe'); eq(buildSettlementEpisodeActionBar(missingSnapshot).length,0,'missing-actions-safe');
projector.dispose(); eq(projector.project(director.snapshot()).ok,false,'projector-disposed');
const mutated={phase:'ready',episode:{id:'x',title:'x',summary:'x',chapter:'x',beats:[{stepId:'x',action:'talk',service:'tavern',title:'x',prompt:'x',hints:[],tags:[]}]},beat:{stepId:'x',action:'talk',service:'tavern',title:'x',prompt:'x',hints:[],tags:[]},cursor:0,feedback:null,runtime:{activeService:'tavern',panel:'quests',history:[]},history:[]}; const frozen=buildSettlementEpisodePresentation(mutated); ok(Object.isFrozen(frozen),'model-frozen'); let failed=false; try{frozen.phase='blocked';}catch{failed=true;} ok(failed||frozen.phase==='ready','mutation-rejected');
console.log(`SETTLEMENT_EPISODE_PRESENTATION_OK checks=${checks}`);
