#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { createSyntheticCoveragePlan, createFullWorldCoverageManifest, createCoverageProbeIndex, createCoverageReplay, validateReplay, createRuntimeCoverageAdapter, createViewportCoverageSchedule, createOwnerEvidenceRequest, createSeamAudit, getWorldCoverageConstants } from '../src/3d/world/fullWorldCoverageDirector.js';
function assert(condition, message) { if (!condition) throw new Error(`[full-world-ownership] ${message}`); }
const root = path.resolve('.');
const directorSource = fs.readFileSync(path.join(root, 'src/3d/world/fullWorldCoverageDirector.js'), 'utf8');
const materialCoreSource = fs.readFileSync(path.join(root, 'src/3d/materials/MaterialAssignmentCore.js'), 'utf8');
const placementSource = fs.readFileSync(path.join(root, 'src/3d/world/WorldAssetPlacementPipeline.js'), 'utf8');
const constants = getWorldCoverageConstants();
for (const [actual, expected, label] of [[constants.WORLD_BOUNDS.xMax,9000,'world width'],[constants.WORLD_BOUNDS.yMax,7000,'world height'],[constants.DEFAULT_GRID.columns,36,'grid columns'],[constants.DEFAULT_GRID.rows,28,'grid rows'],[constants.DEFAULT_REQUIRED_FEATURES.length,9,'feature count'],[constants.REQUIRED_PHASES.length,10,'phase count']]) assert(actual===expected,`${label} drifted`);
assert(constants.MAX_HEIGHT_PARITY_METERS===1e-5,'height parity gate drifted'); assert(constants.MAX_UNASSESSED_RATIO===0,'unassessed tolerance drifted'); assert(constants.MAX_DETERMINISM_DRIFT===0,'determinism tolerance drifted');
const plan=createSyntheticCoveragePlan(), manifest=createFullWorldCoverageManifest(plan), probeIndex=createCoverageProbeIndex(plan), replay=createCoverageReplay(plan), replayCheck=validateReplay(plan,replay), adapter=createRuntimeCoverageAdapter(plan,{batchSize:24}), viewport=createViewportCoverageSchedule(plan,{samples:7}), ownerEvidence=createOwnerEvidenceRequest(plan,{owner:'buzul-muhafizi'}), seamAudit=createSeamAudit(plan);
assert(plan.cellCount===1008,'expected 1008 coverage cells'); assert(plan.coverageRatio===1,'coverage ratio is not complete'); assert(plan.unassessedRatio===0,'unassessed ratio is non-zero'); assert(manifest.cellCount===1008,'manifest cell count drifted'); assert(manifest.probeCount===plan.probeCount,'manifest probe count drifted'); assert(Object.keys(probeIndex).length>plan.cellCount,'probe index lacks boundary probes'); assert(replayCheck.equal,'coverage replay digest mismatch'); assert(adapter.readOnly===true&&adapter.createsGeometry===false&&adapter.mutatesCanonicalGeography===false&&adapter.importsEditorUi===false,'runtime adapter lost ownership guarantees'); assert(adapter.batchCount>0,'coverage batches empty'); assert(viewport.length===49,'viewport schedule count drifted'); assert(ownerEvidence.requiredChecks.includes('material-placement-contract'),'shared material contract omitted'); assert(ownerEvidence.requiredChecks.includes('asset-hydration'),'asset hydration evidence omitted'); assert(ownerEvidence.noPassClaimUntilObserved===true,'owner evidence allows unobserved pass'); assert(seamAudit.pairCount===1952,'seam pair count drifted'); assert(seamAudit.unresolvedCount===0,'self-seam pair found');
const boundaries={north:plan.boundaries.north.length,south:plan.boundaries.south.length,west:plan.boundaries.west.length,east:plan.boundaries.east.length}; assert(boundaries.north===36&&boundaries.south===36&&boundaries.west===28&&boundaries.east===28,'boundary coverage incomplete'); for(const p of ['determinism','parity','cross-seam']) assert(plan.evidence.some(e=>e.phase===p),`${p} evidence missing`);
for(const feature of constants.DEFAULT_REQUIRED_FEATURES) assert(Number.isFinite(plan.featureMatrix[feature]?.coverage),`${feature} coverage missing`);
for(const token of ['EditorMaterialStudio','MeshBasicMaterial','BoxGeometry','SphereGeometry','CylinderGeometry','CapsuleGeometry','PlaneGeometry','writeFileSync','appendFileSync','mkdirSync','git lfs pull --all']) assert(!directorSource.includes(token),`forbidden director token ${token}`);
assert(directorSource.includes('mutatesCanonicalGeography'),'read-only marker missing'); assert(directorSource.includes('createsGeometry'),'geometry marker missing'); assert(directorSource.includes('sharedMaterialPlacementAuthority'),'material authority marker missing'); assert(materialCoreSource.includes('Shared, DOM-free material pipeline'),'shared MaterialAssignmentCore marker missing'); assert(materialCoreSource.includes('validateMaterialAssignment'),'shared validation missing'); assert(placementSource.includes('autoAssignMaterials'),'placement bridge missing'); assert(placementSource.includes('../materials/MaterialAssignmentCore.js'),'placement pipeline not bound to core'); assert(!placementSource.includes('EditorMaterialStudio'),'placement pipeline imports editor UI');
const roundTrip=JSON.parse(JSON.stringify(manifest)); assert(roundTrip.deterministicDigest===manifest.deterministicDigest&&roundTrip.validation.ok===manifest.validation.ok,'manifest serialization drifted'); assert(Object.values(plan.risks).reduce((s,v)=>s+v,0)===0,'synthetic risks present'); assert(plan.gaps.length===0,'synthetic gaps present'); assert(plan.report.readyForRuntimeProof===true,'synthetic plan not runtime-ready');
console.log(`FULL_WORLD_COVERAGE_OWNERSHIP_OK checks=64 cells=${plan.cellCount} seams=${seamAudit.pairCount} probes=${plan.probeCount} digest=${manifest.deterministicDigest}`);
