import assert from 'node:assert/strict';
import { createSettlementWorldCoverageTraversalPlan, validateSettlementWorldCoverageTraversalPlan } from '../src/3d/gameplay/settlementWorldCoverageTraversal.js';
import { createSettlementWorldCoverageTraversalRisk, validateSettlementWorldCoverageTraversalRisk } from '../src/3d/gameplay/settlementWorldCoverageTraversalRisk.js';
import { createSettlementWorldCoverageTraversalRoute, validateSettlementWorldCoverageTraversalRoute } from '../src/3d/gameplay/settlementWorldCoverageTraversalRoute.js';
import { createSettlementWorldCoverageTraversalMilestones, validateSettlementWorldCoverageTraversalMilestones } from '../src/3d/gameplay/settlementWorldCoverageTraversalMilestones.js';
import { createSettlementWorldCoverageTraversalPacing, validateSettlementWorldCoverageTraversalPacing } from '../src/3d/gameplay/settlementWorldCoverageTraversalPacing.js';
import { createSettlementWorldCoverageTraversalSignals, validateSettlementWorldCoverageTraversalSignals } from '../src/3d/gameplay/settlementWorldCoverageTraversalSignals.js';
import { createSettlementWorldCoverageTraversalReplay, validateSettlementWorldCoverageTraversalReplay } from '../src/3d/gameplay/settlementWorldCoverageTraversalReplay.js';
import { createSettlementWorldCoverageTraversalCoordinator, validateSettlementWorldCoverageTraversalCoordinator } from '../src/3d/gameplay/settlementWorldCoverageTraversalCoordinator.js';
import { createSettlementWorldCoverageTraversalAccessibility, validateSettlementWorldCoverageTraversalAccessibility } from '../src/3d/gameplay/settlementWorldCoverageTraversalAccessibility.js';
import { validateSettlementWorldCoverageTraversalScenarios, SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS } from '../src/3d/gameplay/settlementWorldCoverageTraversalScenarios.js';

const base={settlement:{id:'winterfell-edge',regionId:'the-north',anchor:{x:512,y:0,z:768},entrance:{x:518,y:0,z:768},services:['gate','market','tavern','blacksmith','stable','house']},player:{position:{x:545,y:0,z:768},inSettlement:false,fatigue:15,health:100},surface:{biome:'north-temperate',layer:'road',slopeDegrees:2,isWater:false},seed:77,hour:15,weather:{type:'clear',intensity:.1,visibility:.95},roadClass:'gateway'};

function check(name,input){
  const plan=createSettlementWorldCoverageTraversalPlan(input);
  const risk=createSettlementWorldCoverageTraversalRisk(input);
  const route=createSettlementWorldCoverageTraversalRoute(input,'safe');
  const milestones=createSettlementWorldCoverageTraversalMilestones(input);
  const pacing=createSettlementWorldCoverageTraversalPacing(input);
  const signals=createSettlementWorldCoverageTraversalSignals(input);
  const replay=createSettlementWorldCoverageTraversalReplay(input);
  const coordinator=createSettlementWorldCoverageTraversalCoordinator(input);
  const accessibility=createSettlementWorldCoverageTraversalAccessibility(input,'standard');
  assert.equal(validateSettlementWorldCoverageTraversalPlan(plan).ok,true,name+':plan');
  assert.equal(validateSettlementWorldCoverageTraversalRisk(risk).ok,true,name+':risk');
  assert.equal(validateSettlementWorldCoverageTraversalRoute(route).ok,true,name+':route');
  assert.equal(validateSettlementWorldCoverageTraversalMilestones(milestones).ok,true,name+':milestones');
  assert.equal(validateSettlementWorldCoverageTraversalPacing(pacing).ok,true,name+':pacing');
  assert.equal(validateSettlementWorldCoverageTraversalSignals(signals).ok,true,name+':signals');
  assert.equal(validateSettlementWorldCoverageTraversalReplay(replay).ok,true,name+':replay');
  assert.equal(validateSettlementWorldCoverageTraversalCoordinator(coordinator).ok,true,name+':coordinator');
  assert.equal(validateSettlementWorldCoverageTraversalAccessibility(accessibility).ok,true,name+':accessibility');
  assert.ok(plan.lanes.length<=10,name+':lane-cap');
  assert.ok(risk.risk>=0&&risk.risk<=1,name+':risk-range');
  assert.ok(route.alternatives.length<=5,name+':route-cap');
  assert.ok(milestones.markers.length===10,name+':milestone-count');
  assert.ok(pacing.rate>=0&&pacing.rate<=1,name+':pacing-range');
  assert.ok(signals.primary.length<=4,name+':primary-cap');
  assert.ok(replay.frameCount<=16,name+':frame-cap');
  assert.ok(coordinator.confidence>=0&&coordinator.confidence<=1,name+':confidence');
  assert.equal(accessibility.ownership.readOnly,true,name+':accessibility-readonly');
}

check('baseline',base);
check('mobile',{...base,mobile:true});
check('threshold',{...base,player:{...base.player,position:{x:540,z:768}}});
check('inside',{...base,player:{...base.player,position:{x:512,z:768},inSettlement:true}});
check('departure',{...base,player:{...base.player,position:{x:512,z:768},inSettlement:true},routeMode:'return'});
check('fog',{...base,weather:{type:'fog',intensity:.8,visibility:.25}});
check('rain',{...base,weather:{type:'rain',intensity:.65,visibility:.68}});
check('snow',{...base,weather:{type:'snow',intensity:.7,visibility:.52},surface:{...base.surface,biome:'north-cold',layer:'snow',slopeDegrees:8}});
check('storm',{...base,weather:{type:'storm',intensity:.95,visibility:.32},player:{...base.player,fatigue:60}});
check('wet',{...base,surface:{...base.surface,isWater:true,layer:'shore'}});
check('steep',{...base,surface:{...base.surface,slopeDegrees:32}});
check('far',{...base,player:{...base.player,position:{x:760,z:768}}});
check('far-east',{...base,player:{...base.player,position:{x:900,z:768}}});
check('far-north',{...base,player:{...base.player,position:{x:512,z:1000}}});
check('far-south',{...base,player:{...base.player,position:{x:512,z:550}}});
check('fatigued',{...base,player:{...base.player,fatigue:85}});
check('low-health',{...base,player:{...base.player,health:1}});
check('defeated',{...base,player:{...base.player,health:0}});
check('closed',{...base,player:{...base.player,settlementOpen:false}});
check('closed-inside',{...base,player:{...base.player,inSettlement:true,settlementOpen:false}});
check('cold-night',{...base,hour:2,weather:{type:'snow',intensity:.5,visibility:.5},player:{...base.player,fatigue:72}});
check('dawn',{...base,hour:6});
check('midday',{...base,hour:12});
check('dusk',{...base,hour:19});
check('midnight',{...base,hour:24});
check('negative-hour',{...base,hour:-4});
check('large-hour',{...base,hour:53});
check('string-numeric',{...base,hour:'15',player:{...base.player,fatigue:'30'}});
check('nan-hour',{...base,hour:Number.NaN});
check('infinite-fatigue',{...base,player:{...base.player,fatigue:Number.POSITIVE_INFINITY}});
check('empty-surface',{...base,surface:null});
check('empty-player',{...base,player:null});
check('empty-settlement',{...base,settlement:null});
check('unknown-biome',{...base,surface:{...base.surface,biome:'unknown'} });
check('forest',{...base,surface:{...base.surface,biome:'forest-edge',layer:'forest'}});
check('woodland',{...base,surface:{...base.surface,biome:'woodland',layer:'woodland'}});
check('mountain',{...base,surface:{...base.surface,biome:'mountain-cold',layer:'alpine',slopeDegrees:15}});
check('moor',{...base,surface:{...base.surface,biome:'north-moor',layer:'moor'}});
check('river',{...base,surface:{...base.surface,biome:'north-river',layer:'river'}});
check('shore',{...base,surface:{...base.surface,biome:'shoreline',layer:'shore',isWater:false}});
check('service-market',{...base,player:{...base.player,inSettlement:true},routeMode:'service'});
check('service-tavern',{...base,player:{...base.player,inSettlement:true,fatigue:90},routeMode:'service'});
check('service-house',{...base,player:{...base.player,inSettlement:true,fatigue:75},routeMode:'service'});
check('service-craft',{...base,player:{...base.player,inSettlement:true},routeMode:'service'});
check('direct',{...base,routeMode:'direct'});
check('explore',{...base,routeMode:'explore'});
check('bad-route-mode',{...base,routeMode:'not-real'});
check('mobile-fog',{...base,mobile:true,weather:{type:'fog',intensity:.75,visibility:.3}});
check('mobile-snow',{...base,mobile:true,weather:{type:'snow',intensity:.7,visibility:.45}});
check('mobile-far',{...base,mobile:true,player:{...base.player,position:{x:900,z:900}}});

assert.equal(validateSettlementWorldCoverageTraversalScenarios().ok,true);
assert.equal(SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS.length,70);
assert.equal(createSettlementWorldCoverageTraversalPlan(base).fingerprint,createSettlementWorldCoverageTraversalPlan(JSON.parse(JSON.stringify(base))).fingerprint);
assert.equal(createSettlementWorldCoverageTraversalRisk(base).fingerprint,createSettlementWorldCoverageTraversalRisk(JSON.parse(JSON.stringify(base))).fingerprint);
assert.equal(createSettlementWorldCoverageTraversalRoute(base,'safe').fingerprint,createSettlementWorldCoverageTraversalRoute(JSON.parse(JSON.stringify(base)),'safe').fingerprint);
assert.equal(createSettlementWorldCoverageTraversalPacing(base).fingerprint,createSettlementWorldCoverageTraversalPacing(JSON.parse(JSON.stringify(base))).fingerprint);
assert.equal(createSettlementWorldCoverageTraversalSignals(base).fingerprint,createSettlementWorldCoverageTraversalSignals(JSON.parse(JSON.stringify(base))).fingerprint);
assert.equal(Object.isFrozen(createSettlementWorldCoverageTraversalPlan(base)),true);
assert.equal(Object.isFrozen(createSettlementWorldCoverageTraversalPlan(base).lanes),true);
console.log('Settlement World Coverage Traversal Acceptance: PASS');
console.log(JSON.stringify({ok:true,scenarios:SETTLEMENT_WORLD_COVERAGE_TRAVERSAL_SCENARIOS.length,baseline:createSettlementWorldCoverageTraversalPlan(base).fingerprint,risk:createSettlementWorldCoverageTraversalRisk(base).risk,topLane:createSettlementWorldCoverageTraversalRoute(base,'safe').chosenLane}));
