#!/usr/bin/env node
const fs=require('fs');const http=require('http');const path=require('path');
const ROOT=path.resolve(__dirname,'..');const OUT=path.join(ROOT,'artifacts','run277-pindex01-detail');
const assert=(v,m)=>{if(!v)throw new Error(m)};
function pw(){for(const id of['playwright','/opt/node22/lib/node_modules/playwright']){try{return require(id)}catch{}}return null}
function type(f){const e=path.extname(f).toLowerCase();if(e==='.html')return'text/html; charset=utf-8';if(e==='.js'||e==='.mjs')return'text/javascript; charset=utf-8';if(e==='.json')return'application/json; charset=utf-8';if(e==='.css')return'text/css; charset=utf-8';if(e==='.png')return'image/png';if(e==='.glb')return'model/gltf-binary';return'application/octet-stream'}
function server(){const s=http.createServer((req,res)=>{const clean=decodeURIComponent(req.url.split('?')[0]);const f=path.join(ROOT,clean==='/'?'index.html':clean.replace(/^\//,''));if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);res.end('Not found');return}res.writeHead(200,{'content-type':type(f)});fs.createReadStream(f).pipe(res)});return new Promise(r=>s.listen(0,'127.0.0.1',()=>r(s)))}
async function maskProof(page){return page.evaluate(async()=>{const THREE=await import('three');const{normalizedReferenceToMapCanvas}=await import('/src/3d/world/worldReferenceAlignment.js');const{mapCanvasToPlannedWorldXZ}=await import('/src/3d/world/worldReferenceMigrationPlan.js');const{WORLD_REFERENCE_BASE_SURFACE_MASK}=await import('/src/3d/world/worldReferenceSurfacePindexes.js');const{applyReferenceSurfaceToTerrainMesh}=await import('/src/3d/world/worldReferenceSurfaceTerrainVisual.js');const{applyPindex01DetailToTerrainMesh}=await import('/src/3d/world/worldReferencePindex01Detail.js');
function make(){const mask=WORLD_REFERENCE_BASE_SURFACE_MASK;const p=new Float32Array(mask.width*mask.height*3);let c=0;for(let y=0;y<mask.height;y++)for(let x=0;x<mask.width;x++){const m=normalizedReferenceToMapCanvas((x+.5)/mask.width,(y+.5)/mask.height);const w=mapCanvasToPlannedWorldXZ(m.x,m.y);p[c++]=w.x;p[c++]=0;p[c++]=w.z}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));const mat=new THREE.MeshStandardMaterial({color:0x516a49,roughness:1,metalness:0});const mesh=new THREE.Mesh(g,mat);applyReferenceSurfaceToTerrainMesh(mesh);return{mesh,g,mat}}
const a=make(),b=make();const before=Array.from(a.g.getAttribute('color').array);const s1=applyPindex01DetailToTerrainMesh(a.mesh);const s2=applyPindex01DetailToTerrainMesh(b.mesh);const after=Array.from(a.g.getAttribute('color').array),after2=Array.from(b.g.getAttribute('color').array);let changed=0,unchanged=0;for(let i=0;i<before.length;i+=3){const d=before[i]!==after[i]||before[i+1]!==after[i+1]||before[i+2]!==after[i+2];if(d)changed++;else unchanged++}const deterministic=after.every((v,i)=>v===after2[i]);a.g.dispose();a.mat.dispose();b.g.dispose();b.mat.dispose();return{s1,s2,changed,unchanged,deterministic,total:before.length/3}})}
async function main(){const p=pw();if(!p)throw new Error('Playwright unavailable');fs.mkdirSync(OUT,{recursive:true});const s=await server();const browser=await p.chromium.launch({headless:true});const errors=[];try{const ctx=await browser.newContext({serviceWorkers:'allow',viewport:{width:1440,height:900}});const page=await ctx.newPage();page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(String(e)));const url=`http://127.0.0.1:${s.address().port}/canonical-dev.html?worldSource=canonical-dev`;await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>document.body?.dataset?.run277Pindex01Ready==='true',null,{timeout:30000});const proof=await maskProof(page);assert(proof.s1.pindex===1&&proof.s1.touchedVertices>0,'Pindex-01 detail touched no vertices');assert(proof.s1.touchedVertices===proof.s2.touchedVertices,'deterministic touch count drifted');assert(proof.deterministic,'deterministic color output drifted');assert(proof.changed>0&&proof.unchanged>0,'detail must alter only a subset');assert(errors.length===0,`console/page errors: ${errors.join(' | ')}`);await page.screenshot({path:path.join(OUT,'pindex01-detail-online.png'),fullPage:true});await page.waitForFunction(()=>document.body?.dataset?.run201CacheReady==='true',null,{timeout:30000});await ctx.setOffline(true);await page.reload({waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>document.body?.dataset?.run277Pindex01Ready==='true',null,{timeout:30000});assert(errors.length===0,`offline console/page errors: ${errors.join(' | ')}`);await page.screenshot({path:path.join(OUT,'pindex01-detail-offline.png'),fullPage:true});fs.writeFileSync(path.join(OUT,'proof.json'),JSON.stringify({...proof,consoleErrors:errors.length},null,2)+'\n');console.log(`[Run277] Pindex-01 browser PASS ${JSON.stringify(proof)}`);await ctx.close()}finally{await browser.close();await new Promise(r=>s.close(r))}}
main().catch(e=>{console.error(`[Run277] FAIL: ${e.stack||e}`);process.exitCode=1});
