import assert from 'node:assert/strict';
import { V67_MANIFEST, V67_MANIFEST_CHECKS } from '../src/3d/world/environmentRuntimeV67Manifest.js';
import { V67_COVERAGE_MATRIX, coverageSummaryV67 } from '../src/3d/world/environmentRuntimeCoverageMatrixV67.js';
import { V67_SCENARIOS } from '../src/3d/world/environmentRuntimeScenarioLedgerV67.js';
import { buildEnvironmentRuntimeV67 } from '../src/3d/world/environmentRuntimeIntegrationV67.js';
import { buildReleaseGateV67, validateReleaseGateV67 } from '../src/3d/world/environmentRuntimeReleaseV67.js';
import { buildAuditReportV67, auditReleaseEvidenceV67 } from '../src/3d/world/environmentRuntimeAuditV67.js';
import { performanceSummaryV67 } from '../src/3d/world/environmentRuntimePerformanceV67.js';

const samples=V67_COVERAGE_MATRIX.slice(0,32);
const runtime=buildEnvironmentRuntimeV67({samples,clock:12,dayOfYear:180,seed:'final-v67'});
const performance=performanceSummaryV67(samples,'desktop');
const scenarios={evaluations:V67_SCENARIOS.map((scenario)=>({id:scenario.id,hash:scenario.id,runtime}))};
const gate=buildReleaseGateV67(runtime,{platform:'desktop',admitted:16,total:32});
const audit=buildAuditReportV67(runtime,scenarios,performance);
assert.equal(V67_MANIFEST.version,67);
assert.equal(V67_MANIFEST.deterministic,true);
assert.equal(V67_MANIFEST.noWorldMutation,true);
assert.equal(V67_MANIFEST.authorities.placement,'WorldAssetPlacementPipeline.js');
assert.equal(V67_MANIFEST.authorities.material,'MaterialAssignmentCore.js');
for(const [key,value] of Object.entries(V67_MANIFEST_CHECKS))assert.equal(value,true,key);
assert.equal(coverageSummaryV67().total,V67_COVERAGE_MATRIX.length);
assert.ok(coverageSummaryV67().edge>0);
assert.ok(coverageSummaryV67().biomes.length>=6);
assert.equal(runtime.contract.noWorldMutation,true);
assert.ok(runtime.digest.length===8);
assert.equal(gate.policy,'release-v67');
assert.equal(validateReleaseGateV67(gate).ok,true);
assert.ok(gate.evidenceScore>=.9);
assert.ok(gate.coverage===true);
assert.equal(audit.policy,'audit-v67');
assert.ok(audit.summary.score>=.9);
assert.equal(auditReleaseEvidenceV67(audit).p0,true);
assert.ok(performance.perSample>0);
assert.ok(performance.headroom>=0);
const runtimeAgain=buildEnvironmentRuntimeV67({samples,clock:12,dayOfYear:180,seed:'final-v67'});
assert.equal(runtimeAgain.digest,runtime.digest);
assert.deepEqual(runtimeAgain.events.events,runtime.events.events);
console.log('V67 final regression PASS');
