#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import devServerHelper from './devServerHelper.js';
import { buildG71Terrain3DNearDetailProbe, measureG71Terrain3DNearDetail } from '../godot/terrain-authoring/geocells/ne/g71_near_detail.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const arg=process.argv.find(v=>v.startsWith('--out-dir='));const OUT=path.resolve(ROOT,arg?arg.slice(10):'artifacts/ne-g71-near-detail-visual');const ok=(v,m)=>{if(!v)throw new Error(m)};const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const probe=buildG71Terrain3DNearDetailProbe(),authored=measureG71Terrain3DNearDetail();ok(authored.canonicalWaterCells===96&&authored.canonicalLandCells===0,'G71 sea drifted');ok(authored.maxHeightDelta===0&&authored.maxControlDelta===0&&authored.maxRoadPathDelta===0&&authored.maxFoliageDensity===0,'Near Detail changed prior layers');
const playwright=devServerHelper.loadPlaywright();ok(Boolean(playwright),'Playwright required');fs.mkdirSync(OUT,{recursive:true});const server=await devServerHelper.startStaticServer();const browser=await playwright.chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1536,height:1024}});const errors=[];page.on('pageerror',e=>errors.push(`page:${e.message}`));
try{const base=`http://127.0.0.1:${server.address().port}`;await page.goto(`${base}/scripts/fixtures/sw-g07-runtime-visual-harness.html`,{waitUntil:'load',timeout:30000});await page.evaluate(()=>{const map=document.createElement('script');map.type='importmap';map.textContent=JSON.stringify({imports:{three:'/src/3d/vendor/three/three.module.js','three/addons/':'/src/3d/vendor/three/addons/'}});document.head.append(map);});
 const local=await page.evaluate(async source=>{document.body.innerHTML='<canvas id="proof"></canvas>';const THREE=await import('/src/3d/vendor/three/three.module.js');const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('#proof'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.setSize(1536,1024,false);renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene();scene.background=new THREE.Color(0x071722);const camera=new THREE.PerspectiveCamera(48,1.5,1,5000),pos=[],col=[],idx=[];let minR=1,maxR=0;for(let y=0;y<129;y++)for(let x=0;x<129;x++){const s=source.rows[y][x];pos.push((x/128-.5)*1200,s[0]*8,(y/128-.5)*760);col.push(s[2],s[3],s[4]);minR=Math.min(minR,s[5]);maxR=Math.max(maxR,s[5]);}for(let y=0;y<128;y++)for(let x=0;x<128;x++){const a=y*129+x,b=a+1,c=a+129,d=c+1;idx.push(a,c,b,b,c,d);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('color',new THREE.Float32BufferAttribute(col,3));g.setIndex(idx);g.computeVertexNormals();const m=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.87,metalness:0,side:THREE.DoubleSide});scene.add(new THREE.Mesh(g,m));scene.add(new THREE.HemisphereLight(0xd8efff,0x10222a,2));const sun=new THREE.DirectionalLight(0xffefd4,2.2);sun.position.set(-420,720,-360);scene.add(sun);window.__g71Near={render:k=>{camera.position.set(k==='near'?-330:0,k==='near'?220:930,k==='near'?470:1280);camera.lookAt(0,-40,0);renderer.render(scene,camera)},dispose:()=>{g.dispose();m.dispose();renderer.dispose()}};window.__g71Near.render('near');return{vertices:pos.length/3,triangles:idx.length/3,minRoughness:minR,maxRoughness:maxR,evidenceClass:'terrain3d-authoring-source-preview'};},probe);ok(local.vertices===16641&&local.triangles===32768&&local.maxRoughness-local.minRoughness>.06,'Near Detail authoring preview drifted');const hashes={};for(const kind of ['near','far']){await page.evaluate(k=>window.__g71Near.render(k),kind);const png=await page.locator('#proof').screenshot();ok(png.length>4096,`${kind} PNG small`);fs.writeFileSync(path.join(OUT,`g71-near-detail-${kind}.png`),png);hashes[kind]=sha(png);}await page.evaluate(()=>window.__g71Near.dispose());
 const runtime=await page.evaluate(async()=>{document.body.innerHTML='<canvas id="world"></canvas>';const THREE=await import('/src/3d/vendor/three/three.module.js');const{createScene}=await import('/src/3d/sceneManager.js');const{WORLD_SCALE}=await import('/src/3d/config.js');const{CURRENT_TERRAIN_POLICY}=await import('/src/3d/world/terrain.js');const state=createScene(document.getElementById('world'));state.controls.enabled=false;state.scene.fog=null;state.sky.visible=false;state.stars.visible=false;state.renderer.setPixelRatio(1);state.renderer.setSize(1536,1024,false);state.chunkManager.loadSquare(0,0,12);const meshes=[...state.chunkManager.loaded.values()];const aspect=1.5,halfWidth=Math.max(WORLD_SCALE.WORLD_WIDTH_METERS/2,WORLD_SCALE.WORLD_DEPTH_METERS*aspect/2)*1.025,halfHeight=halfWidth/aspect;const full=new THREE.OrthographicCamera(-halfWidth,halfWidth,halfHeight,-halfHeight,1,30000);full.up.set(0,0,-1);full.position.set(0,13000,0);full.lookAt(0,0,0);state.renderer.render(state.scene,full);return{terrainMeshCount:meshes.length,missingSingleSource:meshes.filter(m=>m.userData.currentTerrainSingleSource!==true).length,fullOwnerMapCoverage:CURRENT_TERRAIN_POLICY.fullOwnerMapCoverage,resolution:[1536,1024],fullCamera:'THREE.OrthographicCamera',fullPitchDegrees:90,terrain3dRuntimeAdoptionClaimed:false,evidenceClass:'shipped-runtime-regression'};});ok(runtime.terrainMeshCount>=500&&runtime.missingSingleSource===0&&runtime.fullOwnerMapCoverage===true,'shipped runtime regression');const world=await page.locator('#world').screenshot();ok(world.length>4096,'full-world PNG small');fs.writeFileSync(path.join(OUT,'g71-near-detail-full-world.png'),world);hashes.fullWorld=sha(world);ok(new Set(Object.values(hashes)).size===3,'evidence images not distinct');ok(errors.length===0,errors.join(' | '));const report={authored,local,runtime,sha256:hashes,browserErrors:errors};fs.writeFileSync(path.join(OUT,'g71-near-detail-visual-metrics.json'),`${JSON.stringify(report,null,2)}\n`);console.log(`G71_NEAR_DETAIL_VISUAL_METRICS=${JSON.stringify(report)}`);console.log('NE_G71_NEAR_DETAIL_VISUAL_EVIDENCE_OK');}finally{await page.close();await browser.close();await new Promise(r=>server.close(r));}
