#!/usr/bin/env node
const fs = require('fs');
const http = require('http');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const ARTIFACT_DIR = path.join(ROOT, 'artifacts', 'run215');
const assert = (value, message) => { if (!value) throw new Error(message); };
function playwrightModule() { for (const id of ['playwright', '/opt/node22/lib/node_modules/playwright']) { try { return require(id); } catch {} } return null; }
function contentType(file) { const ext = path.extname(file).toLowerCase(); if (ext === '.html') return 'text/html; charset=utf-8'; if (ext === '.js' || ext === '.mjs') return 'text/javascript; charset=utf-8'; if (ext === '.css') return 'text/css; charset=utf-8'; if (ext === '.json' || ext === '.webmanifest') return ext === '.webmanifest' ? 'application/manifest+json' : 'application/json; charset=utf-8'; if (ext === '.png') return 'image/png'; if (ext === '.jpg' || ext === '.jpeg') return 'image/jpeg'; if (ext === '.glb') return 'model/gltf-binary'; if (ext === '.gltf') return 'model/gltf+json'; if (ext === '.fbx') return 'application/octet-stream'; return 'application/octet-stream'; }
function startServer() { const server = http.createServer((req, res) => { const clean = decodeURIComponent(req.url.split('?')[0]); const relative = clean === '/' ? 'index.html' : clean.replace(/^\//, ''); const file = path.resolve(ROOT, relative); if (!file.startsWith(ROOT + path.sep) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { res.writeHead(404); res.end('Not found'); return; } res.writeHead(200, { 'content-type': contentType(file), 'cache-control': 'no-store' }); fs.createReadStream(file).pipe(res); }); return new Promise(resolve => server.listen(0, '127.0.0.1', () => resolve(server))); }
function sourceProof() { const source = fs.readFileSync(path.join(ROOT, 'src/3d/editor/worldEditor.js'), 'utf8'); assert(source.includes("let transformMode = 'translate'"), 'translate default missing'); assert(source.includes("let transformSpace = 'world'"), 'world default missing'); assert(source.includes("if (key === 'w') setTransformMode('translate')"), 'W shortcut missing'); assert(source.includes("if (key === 'e') setTransformMode('rotate')"), 'E shortcut missing'); assert(source.includes("if (key === 'r') setTransformMode('scale')"), 'R shortcut missing'); assert(source.includes("if (key === 'q') setTransformSpace"), 'Q world/local shortcut missing'); assert(source.includes('editorState().snapEnabled'), 'Snap contract not reused'); assert(source.includes('writeInspector(object);'), 'gizmo -> Inspector sync missing'); assert(source.includes('transformSelectionObserver.disconnect();'), 'selection observer disposal missing'); assert(source.includes('handle.geometry.dispose();') && source.includes('handle.material.dispose();'), 'gizmo disposal missing'); return { shortcuts: 'W/E/R/Q', snap: 'editorState', disposal: true }; }
async function openEditor(playwright, base, options) { const browser = await playwright.chromium.launch({ headless: true }); const context = await browser.newContext(options); const page = await context.newPage(); const errors = []; page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); page.on('pageerror', error => errors.push(String(error))); await page.goto(`${base}/editor.html`, { waitUntil: 'domcontentloaded', timeout: 120000 }); await page.waitForFunction(() => document.querySelectorAll('.we-hierarchy-item').length >= 2 && document.querySelector('#we-transform-translate'), null, { timeout: 30000 }); return { browser, context, page, errors }; }
async function desktopProof(playwright, base) { const session = await openEditor(playwright, base, { viewport: { width: 1440, height: 900 } }); const { browser, context, page, errors } = session; try { assert(await page.isVisible('#we-transform-translate'), 'translate button missing'); assert(await page.isVisible('#we-transform-rotate'), 'rotate button missing'); assert(await page.isVisible('#we-transform-scale'), 'scale button missing'); assert((await page.textContent('#we-transform-space')).trim() === 'World', 'default space is not World'); assert((await page.textContent('#we-transform-mode')).includes('Taşı'), 'default mode is not translate'); await page.keyboard.press('e'); assert((await page.textContent('#we-transform-mode')).includes('Döndür'), 'E did not select rotate'); await page.keyboard.press('r'); assert((await page.textContent('#we-transform-mode')).includes('Ölçekle'), 'R did not select scale'); await page.keyboard.press('w'); assert((await page.textContent('#we-transform-mode')).includes('Taşı'), 'W did not select translate'); await page.keyboard.press('q'); assert((await page.textContent('#we-transform-space')).trim() === 'Local', 'Q did not select Local'); await page.keyboard.press('q'); assert((await page.textContent('#we-transform-space')).trim() === 'World', 'Q did not return to World'); assert(await page.isChecked('#we-snap-toggle'), 'Snap should default on'); assert(Number(await page.inputValue('#we-snap-size')) === 1, 'Snap should default to 1m'); const first = page.locator('.we-hierarchy-item').first(); await first.click(); assert(!(await page.locator('#we-inspector').isHidden()), 'normal object Inspector hidden'); await page.fill('#we-pos-x', '5.4'); await page.locator('#we-pos-x').dispatchEvent('change'); assert(Number(await page.inputValue('#we-pos-x')) === 5.4 || Number(await page.inputValue('#we-pos-x')) === 5, 'Inspector position input unusable'); assert(errors.length === 0, `desktop console/page errors: ${errors.join(' | ')}`); fs.mkdirSync(ARTIFACT_DIR, { recursive: true }); await page.screenshot({ path: path.join(ARTIFACT_DIR, 'desktop-transform-controls.png'), fullPage: true }); return { modes: true, worldLocal: true, snapMeters: 1, inspector: true }; } finally { await context.close(); await browser.close(); } }
async function mobileProof(playwright, base) { const session = await openEditor(playwright, base, { viewport: { width: 430, height: 932 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 }); const { browser, context, page, errors } = session; try { assert(await page.isVisible('#we-canvas'), 'mobile canvas missing'); assert(await page.isVisible('#we-transform-translate'), 'mobile transform controls missing'); await page.click('#we-transform-rotate'); assert((await page.textContent('#we-transform-mode')).includes('Döndür'), 'mobile rotate button failed'); await page.click('#we-transform-space'); assert((await page.textContent('#we-transform-space')).trim() === 'Local', 'mobile World/Local failed'); assert(errors.length === 0, `mobile console/page errors: ${errors.join(' | ')}`); fs.mkdirSync(ARTIFACT_DIR, { recursive: true }); await page.screenshot({ path: path.join(ARTIFACT_DIR, 'mobile-transform-controls.png'), fullPage: true }); return { responsive: true, controlsVisible: true }; } finally { await context.close(); await browser.close(); } }
async function main() { const source = sourceProof(); const playwright = playwrightModule(); if (!playwright) throw new Error('Playwright unavailable'); const server = await startServer(); const base = `http://127.0.0.1:${server.address().port}`; try { const desktop = await desktopProof(playwright, base); const mobile = await mobileProof(playwright, base); console.log(`[checkRun215WorldEditorTransformControls] PROOF: ${JSON.stringify({ source, desktop, mobile })}`); console.log('[checkRun215WorldEditorTransformControls] PASS: W/E/R, World/Local, 1m Snap contract, Inspector sync hooks, desktop/mobile controls and zero errors verified'); } finally { await new Promise(resolve => server.close(resolve)); } }
main().catch(error => { console.error(`[checkRun215WorldEditorTransformControls] FAIL: ${error.stack || error}`); process.exitCode = 1; });
