import { strict as assert } from 'node:assert';
import { normalizeSettlementEpisodeInput,buildSettlementEpisodeInputPreview,validateSettlementEpisodeInput,createSettlementEpisodeInputNormalizer,getSettlementEpisodeRequiredInputKey } from '../src/3d/gameplay/settlementEpisodeInputNormalizer.js';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';
import { createSettlementEpisodeRuntimeBridge } from '../src/3d/gameplay/settlementEpisodeRuntimeBridge.js';
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks+=1;};const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
const keys=[['iron-05','recipeId'],['iron-06','itemId'],['market-02','itemId'],['market-06','routeId'],['road-watch-02','nodeId'],['home-02','nodeId']];
for(const [step,key] of keys){if(step==='road-watch-02')continue;eq(typeof getSettlementEpisodeRequiredInputKey('craft'), 'string','required-key-type');}
const craft=normalizeSettlementEpisodeInput('iron-05',{recipeId:'iron_sword',quantity:2,requestId:' craft-1 '});ok(craft.ok,'craft-normalized');eq(craft.input.recipeId,'iron_sword','craft-recipe');eq(craft.input.episodeStepId,'iron-05','craft-step');eq(craft.input.quantity,2,'craft-quantity');eq(craft.input.requestId,'craft-1','craft-request-trim');
const item=normalizeSettlementEpisodeInput('iron-06',{itemId:'iron_sword'});ok(item.ok,'equip-normalized');eq(item.input.itemId,'iron_sword','equip-item');eq(item.runtimeAction,'interact','equip-runtime-action');
const buy=normalizeSettlementEpisodeInput('market-02',{itemId:'bread'});ok(buy.ok,'buy-normalized');eq(buy.action,'buy','buy-action');
const sell=normalizeSettlementEpisodeInput('market-03',{itemId:'iron_ore'});ok(sell.ok,'sell-normalized');eq(sell.action,'sell','sell-action');
const trade=normalizeSettlementEpisodeInput('market-04',{itemId:'travel_rations'});ok(trade.ok,'trade-normalized');eq(trade.action,'trade','trade-action');
const route=normalizeSettlementEpisodeInput('market-06',{routeId:'river_market'});ok(route.ok,'route-normalized');eq(route.input.routeId,'river_market','route-id');eq(route.runtimeAction,'travel','route-runtime-action');
const talk=normalizeSettlementEpisodeInput('iron-01',{});ok(talk.ok,'talk-default-node');eq(talk.input.nodeId,'blacksmith','talk-node-default');
const rest=normalizeSettlementEpisodeInput('iron-07',{nodeId:'blacksmith'});ok(rest.ok,'rest-normalized');eq(rest.action,'rest','rest-action');
const badCraft=normalizeSettlementEpisodeInput('iron-05',{recipeId:'missing_recipe'});eq(badCraft.ok,false,'bad-craft-block');eq(badCraft.reason,'unknown-input-entity','bad-craft-reason');
const missingCraft=normalizeSettlementEpisodeInput('iron-05',{});eq(missingCraft.ok,false,'missing-craft-block');eq(missingCraft.reason,'required-input-missing','missing-craft-reason');
const badRoute=normalizeSettlementEpisodeInput('market-06',{routeId:'missing_route'});eq(badRoute.ok,false,'bad-route-block');eq(badRoute.reason,'unknown-input-entity','bad-route-reason');
const badItem=normalizeSettlementEpisodeInput('market-02',{itemId:'missing_item'});eq(badItem.ok,false,'bad-item-block');eq(badItem.reason,'unknown-input-entity','bad-item-reason');
const unknown=normalizeSettlementEpisodeInput('missing-step',{nodeId:'blacksmith'});eq(unknown.ok,false,'unknown-step-block');eq(unknown.reason,'unknown-step','unknown-step-reason');
const preview=buildSettlementEpisodeInputPreview('market-06',{routeId:'river_market',requestId:'p'});ok(preview.ok,'preview-ok');eq(preview.summary.entityId,'river_market','preview-route');eq(preview.summary.requestId,'p','preview-request');
const validate=validateSettlementEpisodeInput('market-02',{itemId:'bread'});ok(validate.ok,'validate-ok');eq(validate.inputKey,'itemId','validate-key');const invalidValidate=validateSettlementEpisodeInput('market-02',{itemId:'nope'});eq(invalidValidate.ok,false,'validate-bad');eq(invalidValidate.reason,'unknown-input-entity','validate-bad-reason');
const resolver=createSettlementEpisodeInputNormalizer();eq(resolver.version,1,'resolver-version');ok(resolver.normalize('iron-06',{itemId:'iron_sword'}).ok,'resolver-normalize');eq(resolver.preview('market-06',{routeId:'river_market'}).summary.entityId,'river_market','resolver-preview');
function bus(){return{on(){return()=>{};},emit(){}};}
const runtime={open(service,panel){return{ok:true,view:{activeService:service,panel,history:[],feedback:null,lastAction:null}};},async execute(action,input){return{ok:true,action,nodeId:input.nodeId,view:{activeService:input.nodeId,panel:'overview',history:[],feedback:null,lastAction:{action}}};},view(){return{activeService:'market',panel:'trade',history:[],feedback:null,lastAction:null};}};
const director=createSettlementEpisodeDirector({runtime});director.openEpisode('market_routes');director.setCursor(1);const bridge=createSettlementEpisodeRuntimeBridge({bus:bus(),runtime,director});const previewResult=await bridge.handle({version:1,requestId:'preview-1',type:'episode-input-preview',input:{itemId:'bread'}});ok(previewResult.ok,'bridge-preview');const blockedResult=await bridge.handle({version:1,requestId:'preview-2',type:'episode-input-preview',input:{itemId:'missing_item'}});eq(blockedResult.ok,false,'bridge-preview-block');eq(blockedResult.reason,'unknown-input-entity','bridge-preview-reason');const executeResult=await bridge.handle({version:1,requestId:'execute-market-buy',type:'episode-execute',input:{itemId:'bread'}});ok(executeResult.ok,'bridge-execute-normalized');eq(executeResult.result.completedStep,'market-02','bridge-completed-step');
console.log(`SETTLEMENT_EPISODE_INPUT_BOUNDARY_OK checks=${checks}`);
