import { strict as assert } from 'node:assert';
import { createSettlementEpisodeRuntimeBridge, createSettlementEpisodeRequest } from '../src/3d/gameplay/settlementEpisodeRuntimeBridge.js';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';
import { createSettlementEpisodePresentationProjector } from '../src/3d/gameplay/settlementEpisodePresentationModel.js';
import { createSettlementEpisodeCheckpointAdapter } from '../src/3d/gameplay/settlementEpisodeCheckpoint.js';
let checks=0; const ok=(v,m)=>{assert.ok(v,m);checks+=1;}; const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
function bus(){const listeners=new Map();const events=[];return{events,on(name,fn){listeners.set(name,fn);return()=>listeners.delete(name);},emit(name,payload){events.push({name,payload});},async request(payload){const fn=listeners.get('aapw:settlement-episode:request');return fn?fn(payload):null;}};}
function runtime(){let state={activeService:null,panel:'overview',route:[],history:[],feedback:null,lastAction:null,revision:0};return{open(service,panel){state={...state,activeService:service,panel,route:[...state.route,service],revision:state.revision+1};return{ok:true,view:{...state}};},close(){state={...state,activeService:null,panel:'overview',revision:state.revision+1};return{ok:true,view:{...state}};},async execute(action,input){state={...state,lastAction:{action,episodeId:input.episodeId,episodeStepId:input.episodeStepId,nodeId:input.nodeId},feedback:{status:'success',code:'ok',message:'Tamamlandı.'},history:[...state.history,{type:'action',action}],revision:state.revision+1};return{ok:true,action,nodeId:input.nodeId,view:{...state}};},view(){return{...state};},exportState(){return{version:1,runtimeVersion:1,contentVersion:2,...state,requestIds:[]};},importState(next){state={...state,...next};return{ok:true};}};}
const eventBus=bus();const rt=runtime();const director=createSettlementEpisodeDirector({runtime:rt,now:()=>10});const projector=createSettlementEpisodePresentationProjector({now:()=>10});const checkpoint=createSettlementEpisodeCheckpointAdapter({director,runtime:rt});const bridge=createSettlementEpisodeRuntimeBridge({bus:eventBus,runtime:rt,director,projector,checkpoint,now:()=>10});
const request=createSettlementEpisodeRequest('episode-open',{requestId:'open-1',episodeId:'market_routes'});eq(request.version,1,'request-version');eq(request.type,'episode-open','request-type');const opened=await bridge.handle(request);ok(opened.ok,'open-ok');eq(opened.requestId,'open-1','open-request');eq(bridge.snapshot().director.episodeId,'market_routes','open-episode');ok(eventBus.events.some((e)=>e.name==='aapw:settlement-episode:response'),'response-event');ok(eventBus.events.some((e)=>e.name==='aapw:settlement-campaign:opened'),'campaign-open-event');
const prepared=await bridge.handle(createSettlementEpisodeRequest('episode-prepare',{requestId:'prep-1',input:{}}));ok(prepared.ok,'prepare-ok');const executed=await bridge.handle(createSettlementEpisodeRequest('episode-execute',{requestId:'exec-1',input:{}}));ok(executed.ok,'execute-ok');eq(bridge.snapshot().director.cursor,1,'cursor-advanced');ok(eventBus.events.some((e)=>e.name==='aapw:settlement-episode:model-requested'),'model-requested');
const duplicate=await bridge.handle(createSettlementEpisodeRequest('episode-execute',{requestId:'exec-1',input:{}}));eq(duplicate.ok,false,'duplicate-blocked');eq(duplicate.reason,'duplicate-request','duplicate-reason');const state=await bridge.handle(createSettlementEpisodeRequest('episode-state',{requestId:'state-1'}));ok(state.ok,'state-ok');eq(state.result.view.episodeId,'market_routes','state-episode');
const manifest=await bridge.handle(createSettlementEpisodeRequest('episode-manifest',{requestId:'manifest-1'}));ok(manifest.ok,'manifest-ok');ok(manifest.result.manifest.digest,'manifest-digest');const cp=await bridge.handle(createSettlementEpisodeRequest('episode-checkpoint-export',{requestId:'cp-1'}));ok(cp.ok,'checkpoint-export');ok(cp.result.checkpoint.checksum,'checkpoint-checksum');const restore=await bridge.handle(createSettlementEpisodeRequest('episode-checkpoint-restore',{requestId:'restore-1',input:{checkpoint:cp.result.checkpoint}}));ok(restore.ok,'checkpoint-restore');
const projected=bridge.project();ok(projected.ok,'bridge-project');ok(projected.model.primary,'bridge-primary');eq(projected.model.episode.id,'market_routes','bridge-project-episode');const reset=await bridge.handle(createSettlementEpisodeRequest('episode-reset',{requestId:'reset-1'}));ok(reset.ok,'reset-ok');eq(bridge.snapshot().director.phase,'idle','reset-idle');
const unknown=await bridge.handle(createSettlementEpisodeRequest('unknown',{requestId:'bad-1'}));eq(unknown.ok,false,'unknown-blocked');eq(unknown.reason,'unknown-request-type','unknown-reason');const missing=await bridge.handle({type:'episode-state',version:1});eq(missing.ok,false,'missing-request-blocked');eq(missing.reason,'missing-request-id','missing-id');
const disposed=bridge.dispose();ok(disposed.ok,'dispose-ok');const after=await bridge.handle(createSettlementEpisodeRequest('episode-state',{requestId:'after-1'}));eq(after.ok,false,'disposed-blocked');eq(after.reason,'disposed','disposed-reason');
console.log(`SETTLEMENT_EPISODE_RUNTIME_BRIDGE_OK checks=${checks}`);
