import assert from 'node:assert/strict';
import { resolvePlayerLocomotionAnticipationProfile, validatePlayerLocomotionAnticipationProfile } from '../src/3d/gameplay/playerLocomotionAnticipationPolicy.js';
import { resolvePlayerLocomotionAnimationRequest, validatePlayerLocomotionAnimationRequest } from '../src/3d/gameplay/playerLocomotionAnimationBridge.js';
import { resolvePlayerLocomotionFootContactPresentation, validatePlayerLocomotionFootContactPresentation } from '../src/3d/gameplay/playerLocomotionFootContactPolicy.js';
import { resolvePlayerLocomotionTemporalWindow, resolvePlayerLocomotionTemporalSample } from '../src/3d/gameplay/playerLocomotionTemporalTuning.js';
import { resolvePlayerLocomotionTransitionEnvelope, resolvePlayerLocomotionTransitionSample } from '../src/3d/gameplay/playerLocomotionTransitionWindows.js';
import { pushPlayerLocomotionVelocityHistory, createPlayerLocomotionVelocityHistory, resolvePlayerLocomotionHistoryPrediction } from '../src/3d/gameplay/playerLocomotionVelocityHistory.js';
import { buildPlayerLocomotionAnticipationTelemetryScenario, comparePlayerLocomotionAnticipationTelemetry } from '../src/3d/gameplay/playerLocomotionAnticipationTelemetry.js';
import { replayPlayerLocomotionAnticipationSamples, comparePlayerLocomotionAnticipationReplayRuns } from '../src/3d/gameplay/playerLocomotionAnticipationReplay.js';

function sample(i,variant=0){const angle=(i%64)*Math.PI/32;const speed=(Math.sin(i*.17+variant)+1)*3.1;const slope=Math.abs(Math.sin(i*.11+variant))*52;const turn=Math.abs(Math.cos(i*.07+variant))*535;const slip=(Math.sin(i*.23+variant)+1)/2;const confidence=(Math.cos(i*.19+variant)+1)/2;return{velocity:{x:Math.sin(angle),y:Math.cos(angle)},facing:{x:Math.cos(i*.031),y:Math.sin(i*.031)},planarSpeedMps:speed,slopeDegrees:slope,turnRateDegreesPerSecond:turn,deltaSeconds:.01+(i%6)*.012,previousPhase:(i*.037)%1,surfaceConfidence:confidence,surfaceSlip:slip,runIntent:i%23===0,guarding:i%37===0,attackKind:i%41===0?'heavy':i%29===0?'light':'none',dodgeRemaining:i%53===0?.12:0,hitStaggerRemaining:i%71===0?.18:0};}
function finiteTree(v){if(typeof v==='number')assert.equal(Number.isFinite(v),true);if(v&&typeof v==='object')for(const child of Object.values(v))finiteTree(child);}

for(let variant=0;variant<5;variant+=1){for(let i=0;i<500;i+=1){const input=sample(i,variant);const profile=resolvePlayerLocomotionAnticipationProfile(input);assert.equal(validatePlayerLocomotionAnticipationProfile(profile).ok,true);finiteTree(profile);const request=resolvePlayerLocomotionAnimationRequest(input);assert.equal(validatePlayerLocomotionAnimationRequest(request).ok,true);const foot=resolvePlayerLocomotionFootContactPresentation({phase:profile.phase,speedMps:profile.speedMps,playbackRate:profile.playbackRate,cadenceScale:profile.cadenceBias,surfaceConfidence:profile.surfaceConfidence,groundedConfidence:profile.contact.plant,surfaceSlip:profile.surfaceSlip});assert.equal(validatePlayerLocomotionFootContactPresentation(foot).ok,true);const window=resolvePlayerLocomotionTemporalWindow('cruise',profile.mode,{confidence:profile.confidence,groundRisk:profile.groundRisk,speedDeltaMps:profile.speedDeltaMps});const temporal=resolvePlayerLocomotionTemporalSample({elapsedSeconds:input.deltaSeconds,windowSeconds:window,mode:profile.mode,confidence:profile.confidence});assert.ok(temporal.progress>=0&&temporal.progress<=1);const transition=resolvePlayerLocomotionTransitionEnvelope('cruise',profile.mode,{surfaceSlip:profile.surfaceSlip,groundRisk:profile.groundRisk});const transitionSample=resolvePlayerLocomotionTransitionSample(transition,input.deltaSeconds);assert.ok(transitionSample.progress>=0&&transitionSample.progress<=1);}}

let history=createPlayerLocomotionVelocityHistory();for(let i=0;i<1400;i+=1){history=pushPlayerLocomotionVelocityHistory(history,sample(i));assert.ok(history.samples.length<=24);assert.ok(history.smoothedSpeed>=0&&history.smoothedSpeed<=12);assert.ok(history.smoothedTurnRate>=0&&history.smoothedTurnRate<=540);const prediction=resolvePlayerLocomotionHistoryPrediction(history,(i%30+5)/100);assert.ok(prediction.speedMps>=0&&prediction.speedMps<=12);assert.ok(prediction.distanceMeters>=0);}

const streamA=Array.from({length:240},(_,i)=>sample(i,3));const streamB=Array.from({length:240},(_,i)=>sample(i,3));const telemetryA=buildPlayerLocomotionAnticipationTelemetryScenario(streamA);const telemetryB=buildPlayerLocomotionAnticipationTelemetryScenario(streamB);assert.equal(comparePlayerLocomotionAnticipationTelemetry(telemetryA,telemetryB).equal,true);assert.equal(telemetryA.count,240);
const replayA=replayPlayerLocomotionAnticipationSamples(streamA,{name:'soak',seed:'3'});const replayB=replayPlayerLocomotionAnticipationSamples(streamB,{name:'soak',seed:'3'});assert.equal(comparePlayerLocomotionAnticipationReplayRuns(replayA,replayB).equal,true);assert.equal(replayA.frames.length,240);

for(let stride=1;stride<=25;stride+=1){const sequence=Array.from({length:120},(_,i)=>sample(i*stride,stride));const first=replayPlayerLocomotionAnticipationSamples(sequence,{name:`stride-${stride}`,seed:String(stride)});const second=replayPlayerLocomotionAnticipationSamples(sequence,{name:`stride-${stride}`,seed:String(stride)});assert.equal(first.fingerprint,second.fingerprint);assert.equal(comparePlayerLocomotionAnticipationReplayRuns(first,second).equal,true);}

for(let confidenceStep=0;confidenceStep<=10;confidenceStep+=1){for(let slipStep=0;slipStep<=10;slipStep+=1){const input=sample(confidenceStep*17+slipStep,{surfaceConfidence:confidenceStep/10,surfaceSlip:slipStep/10});const profile=resolvePlayerLocomotionAnticipationProfile(input);assert.ok(profile.confidence>=0&&profile.confidence<=1);assert.ok(profile.groundRisk>=0&&profile.groundRisk<=1);assert.ok(profile.contact.plant>=0&&profile.contact.plant<=1);const request=resolvePlayerLocomotionAnimationRequest(input);assert.equal(validatePlayerLocomotionAnimationRequest(request).ok,true);}}

for(let speedStep=0;speedStep<=48;speedStep+=1){for(let turnStep=0;turnStep<=18;turnStep+=1){const input=sample(speedStep+turnStep,{planarSpeedMps:speedStep/4,turnRateDegreesPerSecond:turnStep*30});const profile=resolvePlayerLocomotionAnticipationProfile(input);assert.ok(profile.playbackRate>=.72&&profile.playbackRate<=1.35);assert.ok(profile.cadenceBias>=.7&&profile.cadenceBias<=1.18);assert.ok(profile.stopDistanceMeters>=0&&profile.stopDistanceMeters<=8);}}

const modes=['idle','start','accelerate','cruise','brake','stop','strafe','reverse','pivot','recover','turn-in-place','combat-advance','combat-retreat','guard-walk','dodge-recover','stagger-recover'];for(const mode of modes){const input=sample(33,{planarSpeedMps:mode==='idle'?0:6,attackKind:mode==='combat-advance'?'heavy':'none',guarding:mode==='guard-walk',dodgeRemaining:mode==='dodge-recover'?.1:0,hitStaggerRemaining:mode==='stagger-recover'?.1:0});const profile=resolvePlayerLocomotionAnticipationProfile(input);assert.ok(typeof profile.mode==='string');const transition=resolvePlayerLocomotionTransitionEnvelope(mode,profile.mode,{groundRisk:profile.groundRisk,surfaceSlip:profile.surfaceSlip});assert.equal(typeof transition.interruptible,'boolean');}

for(let phaseStep=0;phaseStep<1000;phaseStep+=1){const phase=(phaseStep*.017)%1;const input=sample(phaseStep,{previousPhase:phase,planarSpeedMps:6});const profile=resolvePlayerLocomotionAnticipationProfile(input);assert.ok(profile.phase>=0&&profile.phase<1);const foot=resolvePlayerLocomotionFootContactPresentation({phase:profile.phase,speedMps:6,playbackRate:profile.playbackRate,cadenceScale:profile.cadenceBias,surfaceConfidence:.9,groundedConfidence:.9,surfaceSlip:.1});assert.ok(foot.confidence>=0&&foot.confidence<=1);}

console.log('PLAYER_LOCOMOTION_ANTICIPATION_SOAK_PASS');
