#!/usr/bin/env node
import assert from 'node:assert/strict';
import { normalizeGroundwaterEventType, clampEventIntensity, eventIsWetting, eventIsDrying, eventIsThermal, eventFamily, eventPriority, TERRAIN_GROUNDWATER_DETAIL_EVENT_HELPER_POLICY } from '../src/3d/world/terrainGroundwaterSurfaceDetailEventHelpers.js';
import { detailEventAudit, detailEventById, detailEventProfile, detailEventSequence } from '../src/3d/world/terrainGroundwaterSurfaceDetailEventCatalog.js';
let passed=0;
const check=(name,fn)=>{fn();passed+=1;console.log(`[groundwater-detail-event-helpers] PASS: ${name}`)};
check('policy render only',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_EVENT_HELPER_POLICY.renderOnly,true));
check('policy deterministic',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_EVENT_HELPER_POLICY.deterministic,true));
check('storm normalized',()=>assert.equal(normalizeGroundwaterEventType(' STORM '),'storm'));
check('drought normalized',()=>assert.equal(normalizeGroundwaterEventType('DROUGHT'),'drought'));
check('unknown normalized safely',()=>assert.equal(normalizeGroundwaterEventType('unknown'),'recovery'));
check('null normalized safely',()=>assert.equal(normalizeGroundwaterEventType(null),'recovery'));
check('zero intensity',()=>assert.equal(clampEventIntensity(0),0));
check('half intensity',()=>assert.equal(clampEventIntensity(.5),.5));
check('negative intensity',()=>assert.equal(clampEventIntensity(-4),0));
check('high intensity',()=>assert.equal(clampEventIntensity(4),1));
for(const key of ['storm','snowmelt','fog-dew','seepage'])check(`wetting-${key}`,()=>assert.equal(eventIsWetting(key),true));
for(const key of ['drought','evaporation','salt-flush'])check(`drying-${key}`,()=>assert.equal(eventIsDrying(key),true));
for(const key of ['freeze-thaw','thermal-spall'])check(`thermal-${key}`,()=>assert.equal(eventIsThermal(key),true));
for(const key of ['storm','snowmelt','fog-dew','seepage'])check(`family-wet-${key}`,()=>assert.equal(eventFamily(key),'wetting'));
for(const key of ['drought','evaporation','salt-flush'])check(`family-dry-${key}`,()=>assert.equal(eventFamily(key),'drying'));
for(const key of ['freeze-thaw','thermal-spall'])check(`family-thermal-${key}`,()=>assert.equal(eventFamily(key),'thermal'));
check('recovery family',()=>assert.equal(eventFamily('recovery'),'transition'));
check('storm priority',()=>assert.equal(eventPriority('storm'),90));
check('drought priority',()=>assert.equal(eventPriority('drought'),84));
check('freeze priority',()=>assert.equal(eventPriority('freeze-thaw'),82));
check('catalog audit',()=>assert.equal(detailEventAudit().ok,true));
check('catalog lookup storm',()=>assert.equal(detailEventById('storm').id,'storm'));
check('profile override',()=>assert.equal(detailEventProfile('storm',.37).intensity,.37));
check('profile override clamp low',()=>assert.equal(detailEventProfile('storm',-1).intensity,0));
check('profile override clamp high',()=>assert.equal(detailEventProfile('storm',2).intensity,1));
check('sequence frozen',()=>assert.ok(Object.isFrozen(detailEventSequence(['storm','drought']))));
check('sequence length',()=>assert.equal(detailEventSequence(['storm','drought','recovery']).length,3));
check('profile frozen',()=>assert.ok(Object.isFrozen(detailEventProfile('storm'))));
console.log(`[groundwater-detail-event-helpers] PASS: ${passed} checks`);
