#!/usr/bin/env node
const fs = require('fs');
const http = require('http');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const ARTIFACT_DIR = path.join(ROOT, 'artifacts', 'run214');
const assert = (value, message) => { if (!value) throw new Error(message); };
function playwrightModule() { for (const id of ['playwright', '/opt/node22/lib/node_modules/playwright']) { try { return require(id); } catch {} } return null; }
function contentType(file) { const ext = path.extname(file).toLowerCase(); if (ext === '.html') return 'text/html; charset=utf-8'; if (ext === '.js' || ext === '.mjs') return 'text/javascript; charset=utf-8'; if (ext === '.css') return 'text/css; charset=utf-8'; if (ext === '.json' || ext === '.webmanifest') return ext === '.webmanifest' ? 'application/manifest+json' : 'application/json; charset=utf-8'; if (ext === '.png') return 'image/png'; if (ext === '.jpg' || ext === '.jpeg') return 'image/jpeg'; if (ext === '.glb') return 'model/gltf-binary'; if (ext === '.gltf') return 'model/gltf+json'; return 'application/octet-stream'; }
function startServer() { const server = http.createServer((req, res) => { const clean = decodeURIComponent(req.url.split('?')[0]); const relative = clean === '/' ? 'index.html' : clean.replace(/^\//, ''); const file = path.resolve(ROOT, relative); if (!file.startsWith(ROOT + path.sep) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { res.writeHead(404); res.end('Not found'); return; } res.writeHead(200, { 'content-type': contentType(file), 'cache-control': 'no-store' }); fs.createReadStream(file).pipe(res); }); return new Promise(resolve => server.listen(0, '127.0.0.1', () => resolve(server))); }
async function openEditor(playwright, base, options) { const browser = await playwright.chromium.launch({ headless: true }); const context = await browser.newContext({ ...options, acceptDownloads: true }); const page = await context.newPage(); const errors = []; page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); page.on('pageerror', error => errors.push(String(error))); await page.goto(`${base}/editor.html`, { waitUntil: 'domcontentloaded', timeout: 120000 }); await page.waitForFunction(() => document.querySelectorAll('.we-hierarchy-item').length >= 2, null, { timeout: 30000 }); return { browser, context, page, errors }; }
async function desktopProof(playwright, base) { const session = await openEditor(playwright, base, { viewport: { width: 1440, height: 900 } }); const { browser, context, page, errors } = session; try { assert(await page.isChecked('#we-grid-toggle'), 'desktop: Grid başlangıçta açık değil'); assert(await page.isChecked('#we-snap-toggle'), 'desktop: Snap başlangıçta açık değil'); await page.uncheck('#we-grid-toggle'); assert(!(await page.isChecked('#we-grid-toggle')) && await page.isChecked('#we-snap-toggle'), 'desktop: Grid ve Snap bağımsız değil'); await page.check('#we-grid-toggle'); await page.click('#we-create-formation'); await page.waitForFunction(() => [...document.querySelectorAll('.we-hierarchy-item')].some(node => node.textContent.includes('×500')), null, { timeout: 30000 }); const downloadPromise = page.waitForEvent('download'); await page.click('#we-save'); const download = await downloadPromise; const savePath = await download.path(); const data = JSON.parse(fs.readFileSync(savePath, 'utf8')); assert(data.schemaVersion === 1, 'desktop: scene schemaVersion drift'); assert(data.editor.gridVisible === true && data.editor.snapEnabled === true && data.editor.snapSize === 1, 'desktop: Grid/Snap JSON kontratı drift'); assert(data.instanceGroups.length === 1 && data.instanceGroups[0].instances.length === 500, 'desktop: 500 instance serialize edilmedi'); assert(data.instanceGroups[0].id === 'formation-marker-soldier-0001', `desktop: deterministik formation id drift ${data.instanceGroups[0].id}`); assert(errors.length === 0, `desktop: console/page errors ${errors.join(' | ')}`); fs.mkdirSync(ARTIFACT_DIR, { recursive: true }); await page.screenshot({ path: path.join(ARTIFACT_DIR, 'desktop-world-editor.png'), fullPage: true }); return { objects: data.objects.length, instances: data.instanceGroups[0].instances.length, formationId: data.instanceGroups[0].id }; } finally { await context.close(); await browser.close(); } }
async function loadProof(playwright, base) { const session = await openEditor(playwright, base, { viewport: { width: 1280, height: 800 } }); const { browser, context, page, errors } = session; try { await page.setInputFiles('#we-load-file', path.join(ROOT, 'scenes', 'westeros-world.example.json')); await page.waitForFunction(() => [...document.querySelectorAll('.we-hierarchy-item')].some(node => node.textContent.includes('Winterfell Marker')), null, { timeout: 30000 }); assert(errors.length === 0, `load: console/page errors ${errors.join(' | ')}`); return { loaded: true }; } finally { await context.close(); await browser.close(); } }
async function mobileProof(playwright, base) { const session = await openEditor(playwright, base, { viewport: { width: 430, height: 932 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 }); const { browser, context, page, errors } = session; try { assert(await page.isVisible('#we-canvas'), 'mobile: editor canvas görünmüyor'); assert(await page.isVisible('#we-grid-toggle') && await page.isVisible('#we-snap-toggle'), 'mobile: Grid/Snap kontrolleri görünmüyor'); assert(errors.length === 0, `mobile: console/page errors ${errors.join(' | ')}`); fs.mkdirSync(ARTIFACT_DIR, { recursive: true }); await page.screenshot({ path: path.join(ARTIFACT_DIR, 'mobile-world-editor.png'), fullPage: true }); return { responsive: true }; } finally { await context.close(); await browser.close(); } }
async function main() { const playwright = playwrightModule(); if (!playwright) throw new Error('Playwright unavailable'); const server = await startServer(); const base = `http://127.0.0.1:${server.address().port}`; try { const desktop = await desktopProof(playwright, base); const load = await loadProof(playwright, base); const mobile = await mobileProof(playwright, base); console.log(`[checkRun214WorldEditorFoundation] PROOF: ${JSON.stringify({ desktop, load, mobile })}`); console.log('[checkRun214WorldEditorFoundation] PASS: editor desktop/mobile, Grid/Snap independence, JSON load/save, deterministic 500-instance formation and zero errors verified'); } finally { await new Promise(resolve => server.close(resolve)); } }
main().catch(error => { console.error(`[checkRun214WorldEditorFoundation] FAIL: ${error.stack || error}`); process.exitCode = 1; });
