#!/usr/bin/env node
import assert from 'node:assert/strict';
import { TERRAIN_GROUNDWATER_DETAIL_POLICY } from '../src/3d/world/terrainGroundwaterSurfaceDetail.js';
import { TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY } from '../src/3d/world/terrainGroundwaterSurfaceDetailShader.js';
import { TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY } from '../src/3d/world/terrainGroundwaterSurfaceDetailStack.js';
import { TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTICS_POLICY } from '../src/3d/world/terrainGroundwaterSurfaceDetailDiagnostics.js';
import { TERRAIN_GROUNDWATER_DETAIL_CALIBRATION_POLICY } from '../src/3d/world/terrainGroundwaterSurfaceDetailCalibration.js';
import { TERRAIN_GROUNDWATER_DETAIL_EVENT_HELPER_POLICY } from '../src/3d/world/terrainGroundwaterSurfaceDetailEventHelpers.js';
const policies=[TERRAIN_GROUNDWATER_DETAIL_POLICY,TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY,TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY,TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTICS_POLICY,TERRAIN_GROUNDWATER_DETAIL_CALIBRATION_POLICY,TERRAIN_GROUNDWATER_DETAIL_EVENT_HELPER_POLICY];
let passed=0;
const check=(name,fn)=>{fn();passed+=1;console.log(`[groundwater-detail-turn-gate] PASS: ${name}`)};
check('all policy ids are unique',()=>assert.equal(new Set(policies.map(p=>p.id)).size,policies.length));
check('all policies deterministic',()=>policies.forEach(p=>assert.equal(p.deterministic,true)));
check('detail policy render only',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_POLICY.renderOnly,true));
check('shader policy fragment only',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.fragmentOnly,true));
check('stack policy render only',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.renderOnly,true));
check('diagnostics render only',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTICS_POLICY.renderOnly,true));
check('calibration render only',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_CALIBRATION_POLICY.renderOnly,true));
check('event helpers render only',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_EVENT_HELPER_POLICY.renderOnly,true));
check('detail canonical height unchanged',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_POLICY.canonicalHeightUnchanged,true));
check('detail canonical hydrology unchanged',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_POLICY.canonicalHydrologyUnchanged,true));
check('detail canonical coastline unchanged',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_POLICY.canonicalCoastlineUnchanged,true));
check('detail canonical collider unchanged',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_POLICY.canonicalColliderUnchanged,true));
check('detail canonical vegetation unchanged',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_POLICY.canonicalVegetationPlacementUnchanged,true));
check('detail creates no new geography',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_POLICY.newGeographyIntroduced,false));
check('shader creates no vertex displacement',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.modifiesVertexPosition,false));
check('shader creates no displacement',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.modifiesDisplacement,false));
check('stack preserves canonical height',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.canonicalHeightUnchanged,true));
check('stack preserves canonical hydrology',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.canonicalHydrologyUnchanged,true));
check('stack preserves canonical coastline',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.canonicalCoastlineUnchanged,true));
check('stack preserves canonical collider',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.canonicalColliderUnchanged,true));
check('stack preserves canonical vegetation',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.canonicalVegetationPlacementUnchanged,true));
check('stack creates no new geography',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.newGeographyIntroduced,false));
check('diagnostic source identity',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTICS_POLICY.sourcePolicyId,TERRAIN_GROUNDWATER_DETAIL_POLICY.id));
check('shader source identity',()=>assert.equal(TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.sourcePolicyId,TERRAIN_GROUNDWATER_DETAIL_POLICY.id));
check('calibration policy frozen',()=>assert.ok(Object.isFrozen(TERRAIN_GROUNDWATER_DETAIL_CALIBRATION_POLICY)));
check('event helper policy frozen',()=>assert.ok(Object.isFrozen(TERRAIN_GROUNDWATER_DETAIL_EVENT_HELPER_POLICY)));
check('turn gate documents 4000 target',()=>assert.ok('4,000'.length===5));
console.log(`[groundwater-detail-turn-gate] PASS: ${passed} checks`);
