import assert from 'node:assert/strict';
import { V67_MANIFEST, V67_MANIFEST_CHECKS, manifestHasDomainV67 } from '../src/3d/world/environmentRuntimeV67Manifest.js';
import { V67_POLICY, contractSnapshotV67, hashV67 } from '../src/3d/world/environmentRuntimeV67.js';
import { buildEnvironmentRuntimeV67, validateEnvironmentRuntimeV67, immutableContractSnapshotV67 } from '../src/3d/world/environmentRuntimeIntegrationV67.js';
import { buildAuditReportV67, auditReleaseEvidenceV67 } from '../src/3d/world/environmentRuntimeAuditV67.js';
import { buildReleaseGateV67, validateReleaseGateV67 } from '../src/3d/world/environmentRuntimeReleaseV67.js';
import { performanceSummaryV67 } from '../src/3d/world/environmentRuntimePerformanceV67.js';
import { V67_COVERAGE_MATRIX } from '../src/3d/world/environmentRuntimeCoverageMatrixV67.js';
import { V67_SCENARIOS } from '../src/3d/world/environmentRuntimeScenarioLedgerV67.js';

assert.equal(V67_POLICY.version,67);
assert.equal(V67_POLICY.deterministic,true);
assert.equal(V67_POLICY.noWorldMutation,true);
assert.deepEqual(contractSnapshotV67(),contractSnapshotV67());
for(const key of ['deterministic','readOnly','sharedPlacementAuthority','sharedMaterialAuthority','scenarioCoverage','exactHeadValidation'])assert.equal(V67_MANIFEST_CHECKS[key],true,key);
for(const domain of ['hydrology','weather','surface','atmosphere','wildlife','hazards','navigation','vegetation','climate','ecology','events','geology','acoustics','resonance','continuity','shelter','visibility','weather-coupling','streaming','scenario-ledger','coverage-matrix','release-gate','quality-guard','ground','exposure','biome-transitions','resources','interaction','observability','performance','audit'])assert.equal(manifestHasDomainV67(domain),true,domain);
assert.equal(V67_MANIFEST.acceptance.projection,'orthographic');
assert.equal(V67_MANIFEST.acceptance.width,1536);
assert.equal(V67_MANIFEST.acceptance.height,1024);
assert.equal(V67_MANIFEST.acceptance.fovDegrees,90);
assert.equal(V67_MANIFEST.releaseEnvelope.minimumAddedLines,2850);
assert.equal(V67_MANIFEST.releaseEnvelope.maximumAddedLines,3000);
const samples=V67_COVERAGE_MATRIX.slice(0,28);
const runtime=buildEnvironmentRuntimeV67({samples,clock:12,dayOfYear:180,seed:'governance-v67'});
assert.equal(validateEnvironmentRuntimeV67(runtime).ok,true);
assert.equal(runtime.contract.noWorldMutation,true);
assert.equal(runtime.contract.placementAuthority,'WorldAssetPlacementPipeline.js');
assert.equal(runtime.contract.materialAuthority,'MaterialAssignmentCore.js');
assert.ok(runtime.digest===hashV67(JSON.stringify({...runtime,observability:runtime.observability}))); 
assert.ok(immutableContractSnapshotV67(runtime).noWorldMutation);
const performance=performanceSummaryV67(samples,'desktop');
const ledger={evaluations:V67_SCENARIOS.map(s=>({id:s.id,hash:s.id,runtime}))};
const gate=buildReleaseGateV67(runtime,{platform:'desktop',admitted:10,total:28});
assert.equal(validateReleaseGateV67(gate).ok,true);
assert.ok(gate.coverage);
assert.ok(gate.evidenceScore>=.9);
const audit=buildAuditReportV67(runtime,ledger,performance);
assert.ok(audit.summary.score>=.9);
assert.equal(auditReleaseEvidenceV67(audit).p0,true);
const replay=buildEnvironmentRuntimeV67({samples,clock:12,dayOfYear:180,seed:'governance-v67'});
assert.equal(replay.digest,runtime.digest);
assert.deepEqual(replay.runtime.samples,runtime.runtime.samples);
assert.deepEqual(replay.hazards,runtime.hazards);
assert.deepEqual(replay.resources,runtime.resources);
assert.deepEqual(replay.interactions,runtime.interactions);
assert.deepEqual(replay.events.events,runtime.events.events);
assert.equal(replay.observability.health.rate,runtime.observability.health.rate);
console.log('V67 governance regression PASS');
