import { strict as assert } from 'node:assert';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';
import { createSettlementEpisodeUXNavigator,buildSettlementEpisodeUXView } from '../src/3d/gameplay/settlementEpisodeUXNavigator.js';
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks+=1;};const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
function runtime(){let state={activeService:null,panel:'overview',route:[],history:[],feedback:null,lastAction:null};return{open(service,panel){state={...state,activeService:service,panel};return{ok:true,view:{...state}};},async execute(action,input){state={...state,lastAction:{action,nodeId:input.nodeId,episodeId:input.episodeId,episodeStepId:input.episodeStepId},feedback:{status:'success',code:'ok',message:'Tamamlandı.'},history:[...state.history,{type:'action',action}]};return{ok:true,action,nodeId:input.nodeId,view:{...state}};},close(){state={...state,activeService:null,panel:'overview'};return{ok:true};},view(){return{...state};},exportState(){return{version:1,runtimeVersion:1,contentVersion:2,...state,requestIds:[]};},importState(next){state={...state,...next};return{ok:true};}};}
const d=createSettlementEpisodeDirector({runtime:runtime(),now:()=>10});d.openEpisode('market_routes');const n=createSettlementEpisodeUXNavigator({now:()=>10});
let first=n.view(d.snapshot());ok(first.ok,'view-ok');eq(first.state.episodeId,'market_routes','episode-id');eq(first.state.stepId,'market-01','step-id');eq(first.state.panel,'dialogue','talk-panel');ok(first.state.dialogue,'dialogue-present');ok(first.state.journey,'journey-present');ok(first.state.handoff,'handoff-present');eq(first.state.handoff.runtimeAction,'talk','handoff-runtime-action');ok(first.state.targets.length>=2,'targets-present');eq(first.state.focusIndex,0,'focus-start');
const next=n.nextFocus(d.snapshot());ok(next.ok,'next-focus');eq(next.state.focusIndex,1,'next-focus-index');const previous=n.previousFocus(d.snapshot());ok(previous.ok,'previous-focus');eq(previous.state.focusIndex,0,'previous-focus-index');
const selected=n.setFocus(d.snapshot(),'service:market');ok(selected.ok,'focus-service');eq(selected.state.focusTarget.id,'service:market','service-focus');
const unknownFocus=n.setFocus(d.snapshot(),'not-a-target');ok(unknownFocus.ok,'unknown-focus-fallback');eq(unknownFocus.state.focusIndex,0,'unknown-focus-fallback-index');
const trade=d.setCursor(1);ok(trade.ok,'trade-step-set');const tradeView=buildSettlementEpisodeUXView(d.snapshot());eq(tradeView.panel,'trade','trade-panel');eq(tradeView.stepId,'market-02','trade-step');eq(tradeView.handoff.inputKey,'itemId','trade-input-key');
const craftDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>10});craftDirector.openEpisode('iron_and_oath');craftDirector.setCursor(4);const craftView=buildSettlementEpisodeUXView(craftDirector.snapshot());eq(craftView.panel,'craft','craft-panel');eq(craftView.handoff.inputKey,'recipeId','craft-input');
const travelDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>10});travelDirector.openEpisode('market_routes');travelDirector.setCursor(5);const travelView=buildSettlementEpisodeUXView(travelDirector.snapshot());eq(travelView.panel,'travel','travel-panel');eq(travelView.handoff.inputKey,'routeId','travel-input');
const saveDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>10});saveDirector.openEpisode('hearth_and_home');saveDirector.setCursor(1);const saveView=buildSettlementEpisodeUXView(saveDirector.snapshot());eq(saveView.panel,'overview','save-overview-panel');eq(saveView.handoff.runtimeAction,'save','save-runtime-action');
const restDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>10});restDirector.openEpisode('stable_master');restDirector.setCursor(2);const restView=buildSettlementEpisodeUXView(restDirector.snapshot());eq(restView.panel,'overview','rest-overview');eq(restView.handoff.runtimeAction,'rest','rest-runtime');
const focusEvents=[];const callbackNavigator=createSettlementEpisodeUXNavigator({now:()=>44,onNavigate:(state)=>focusEvents.push(state)});callbackNavigator.setFocus(d.snapshot(),0);callbackNavigator.nextFocus(d.snapshot());callbackNavigator.previousFocus(d.snapshot());ok(focusEvents.length>=3,'navigation-callbacks');ok(focusEvents.every((entry)=>entry.episodeId==='market_routes'),'navigation-episode-stable');
const reconciled=callbackNavigator.reconcile(d.snapshot());ok(reconciled.ok,'reconcile-ok');ok(reconciled.state.targets.length>0,'reconcile-targets');const reset=callbackNavigator.reset();ok(reset.ok,'reset-ok');eq(reset.focusIndex,0,'reset-focus');eq(reset.history.length,0,'reset-history');callbackNavigator.dispose();eq(callbackNavigator.view(d.snapshot()).ok,false,'dispose-view');
const noEpisode=buildSettlementEpisodeUXView({phase:'idle',episode:null,beat:null,cursor:0});eq(noEpisode.episodeId,'','no-episode-id');eq(noEpisode.stepId,'','no-step-id');eq(noEpisode.focusIndex,0,'no-focus');ok(noEpisode.targets.length===0,'no-targets');
for(const id of ['iron_and_oath','market_routes','road_watch','hearth_and_home','winter_supply','stable_master']){const dir=createSettlementEpisodeDirector({runtime:runtime(),now:()=>1});dir.openEpisode(id);const view=buildSettlementEpisodeUXView(dir.snapshot());ok(view.presentation,'presentation-'+id);ok(view.handoff,'handoff-'+id);ok(view.journey,'journey-'+id);ok(view.dialogue,'dialogue-'+id);eq(view.targets.length,4,`target-count-${id}`);}
console.log(`SETTLEMENT_EPISODE_UX_NAVIGATOR_OK checks=${checks}`);
