import assert from 'node:assert/strict';
import { createPlayerLocomotionAnticipationFacadeState, resolvePlayerLocomotionFacadeObservation, advancePlayerLocomotionAnticipationFacadeState, updatePlayerLocomotionAnticipationFacade, resolvePlayerLocomotionFacadeReadModel, createPlayerLocomotionAnticipationFacadeController, auditPlayerLocomotionAnticipationFacade } from '../src/3d/gameplay/playerLocomotionAnticipationRuntimeFacade.js';

function sample(index,overrides={}){const a=(index%16)*Math.PI/8;return{velocity:{x:Math.sin(a),y:Math.cos(a)},facing:{x:0,y:1},planarSpeedMps:(index%14)*.7,slopeDegrees:index%11*4,turnRateDegreesPerSecond:index%13*40,deltaSeconds:1/60,surfaceConfidence:(index%10)/10,surfaceSlip:(index%8)/8,...overrides};}
assert.equal(auditPlayerLocomotionAnticipationFacade().valid,true);assert.equal(auditPlayerLocomotionAnticipationFacade().hasAnimationFingerprint,true);
let state=createPlayerLocomotionAnticipationFacadeState();assert.equal(state.frameCount,0);assert.equal(state.mode,'idle');
for(let index=0;index<240;index+=1){const result=updatePlayerLocomotionAnticipationFacade(state,sample(index));state=result.state;const o=result.observation;const read=resolvePlayerLocomotionFacadeReadModel(o);assert.equal(read.frameCount,index+1);assert.ok(typeof read.mode==='string');assert.ok(typeof read.direction==='string');assert.ok(read.speedMps>=0&&read.speedMps<=12);assert.ok(read.confidence>=0&&read.confidence<=1);assert.ok(read.groundRisk>=0&&read.groundRisk<=1);assert.ok(read.temporalProgress>=0&&read.temporalProgress<=1);assert.ok(read.transitionProgress>=0&&read.transitionProgress<=1);assert.ok(read.footPhase>=0&&read.footPhase<=1);assert.ok(read.footConfidence>=0&&read.footConfidence<=1);assert.ok(read.animationFingerprint.length>=8);assert.ok(o.history.samples.length<=24);}
assert.equal(state.frameCount,240);assert.ok(state.history.samples.length<=24);
const controllerSeen=[];const controller=createPlayerLocomotionAnticipationFacadeController({onObservation:(o)=>controllerSeen.push(o.profile.mode)});for(let index=0;index<160;index+=1)controller.update(sample(index,{planarSpeedMps:index<30?0:index<90?7:1}));assert.equal(controller.read().frameCount,160);assert.ok(controllerSeen.length>0);controller.reset();assert.equal(controller.read().frameCount,0);
const malformed=[sample(1,{planarSpeedMps:Infinity,slopeDegrees:Infinity,turnRateDegreesPerSecond:NaN}),sample(2,{velocity:{x:Infinity,y:NaN},facing:{x:NaN,y:Infinity},surfaceConfidence:NaN,surfaceSlip:Infinity}),sample(3,{deltaSeconds:-100})];for(const input of malformed){const result=resolvePlayerLocomotionFacadeObservation(input,createPlayerLocomotionAnticipationFacadeState());assert.ok(Number.isFinite(result.profile.speedMps));assert.ok(result.profile.playbackRate>=.72&&result.profile.playbackRate<=1.35);assert.ok(result.prediction.speedMps>=0&&result.prediction.speedMps<=12);}
let direct=createPlayerLocomotionAnticipationFacadeState();for(let index=0;index<64;index+=1)direct=advancePlayerLocomotionAnticipationFacadeState(direct,sample(index));assert.equal(direct.frameCount,64);const final=resolvePlayerLocomotionFacadeReadModel(resolvePlayerLocomotionFacadeObservation(sample(65),direct));assert.equal(typeof final.animationFingerprint,'string');
assert.equal(Object.isFrozen(state),true);assert.equal(Object.isFrozen(state.history),true);assert.equal(Object.isFrozen(controller.read()),true);
console.log('PLAYER_LOCOMOTION_ANTICIPATION_FACADE_PASS');
