import { strict as assert } from 'node:assert';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';
import { listSettlementEpisodes,getSettlementEpisode,getSettlementEpisodeBeat } from '../src/3d/gameplay/settlementEpisodeContent.js';

let checks=0; const ok=(v,m)=>{assert.ok(v,m);checks+=1;}; const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;}; const deep=(a,b,m)=>{assert.deepEqual(a,b,m);checks+=1;};
function runtimeWithOutcome(outcome='success'){
 const calls=[]; let current={activeService:null,panel:'overview',route:[],history:[],feedback:null,lastAction:null};
 return {calls,open(service,panel){calls.push({kind:'open',service,panel}); current={...current,activeService:service,panel,route:[...current.route,service]}; return {ok:true,action:'open',nodeId:service,view:{...current}};},close(){calls.push({kind:'close'}); current={...current,activeService:null,panel:'overview'}; return {ok:true,action:'close',view:{...current}};},async execute(action,input){calls.push({kind:'execute',action,input}); if(outcome==='throw') throw new Error('simulated-handler-failure'); if(outcome==='reject') return {ok:false,reason:'handler-rejected',message:'İşlem reddedildi.'}; current={...current,lastAction:{action,nodeId:input.nodeId,episodeId:input.episodeId,episodeStepId:input.episodeStepId},feedback:{status:'success',code:'ok',action,message:'Tamamlandı.'},history:[...current.history,{type:'action',action}]}; return {ok:true,action,nodeId:input.nodeId,data:{accepted:true},view:{...current}};},view(){return {...current};},exportState(){return {version:1,runtimeVersion:1,contentVersion:2,panel:current.panel,activeService:current.activeService,route:current.route,history:current.history,requestIds:[],lastAction:current.lastAction,revision:0};},importState(state){current={...current,activeService:state.activeService??null,panel:state.panel??'overview',route:[...(state.route??[])],history:[...(state.history??[])],lastAction:state.lastAction??null}; return {ok:true};}};
}
const ids=listSettlementEpisodes(); eq(ids.length,6,'episode-count');
for(const id of ids){ const runtime=runtimeWithOutcome(); const events=[]; const director=createSettlementEpisodeDirector({runtime,now:()=>100,onEvent:(event)=>events.push(event)}); const opened=director.openEpisode(id); ok(opened.ok,`open:${id}`); eq(opened.view.episodeId,id,`episode:${id}`); eq(opened.view.cursor,0,`cursor:${id}`); const prepared=director.prepareCurrent(); ok(prepared.ok,`prepare:${id}`); eq(prepared.stepId,getSettlementEpisode(id).beats[0].stepId,`first-step:${id}`); const executed=await director.executeCurrent({requestId:`first-${id}`}); ok(executed.ok,`execute:${id}`); eq(executed.completedStep,prepared.stepId,`completed:${id}`); eq(director.snapshot().cursor,1,`advance:${id}`); ok(events.some((e)=>e.name==='episode-opened'),`opened-event:${id}`); ok(events.some((e)=>e.name==='action-succeeded'),`success-event:${id}`); }
const duplicateRuntime=runtimeWithOutcome(); const duplicateDirector=createSettlementEpisodeDirector({runtime:duplicateRuntime}); duplicateDirector.openEpisode('iron_and_oath'); const first=await duplicateDirector.executeCurrent({requestId:'same-1'}); ok(first.ok,'first-request'); const second=await duplicateDirector.executeCurrent({requestId:'same-1'}); eq(second.ok,false,'duplicate-fails'); eq(second.reason,'duplicate-request','duplicate-reason'); eq(duplicateDirector.snapshot().cursor,1,'duplicate-cursor-stable');
const rejectDirector=createSettlementEpisodeDirector({runtime:runtimeWithOutcome('reject')}); rejectDirector.openEpisode('market_routes'); const rejected=await rejectDirector.executeCurrent({requestId:'reject-1'}); eq(rejected.ok,false,'reject-propagates'); eq(rejected.phase,'blocked','reject-phase'); eq(rejected.nextStep,'market-01','reject-step-retained');
const throwDirector=createSettlementEpisodeDirector({runtime:runtimeWithOutcome('throw')}); throwDirector.openEpisode('road_watch'); const thrown=await throwDirector.executeCurrent({requestId:'throw-1'}); eq(thrown.ok,false,'throw-fails-closed'); eq(thrown.result.reason,'runtime-threw','throw-reason');
const noView={open(){return {ok:true,view:{activeService:'house',panel:'overview'}};},async execute(){return {ok:true};}}; const noViewDirector=createSettlementEpisodeDirector({runtime:noView}); const openNoView=noViewDirector.openEpisode('hearth_and_home'); ok(openNoView.ok,'no-view-open'); eq(openNoView.view.runtimeOk,false,'no-view-detected');
const closeRuntime=runtimeWithOutcome(); const closeDirector=createSettlementEpisodeDirector({runtime:closeRuntime}); closeDirector.openEpisode('stable_master'); const closed=closeDirector.closeService(); ok(closed.ok,'close-service'); eq(closeDirector.snapshot().activeService,'','close-active-service');
const manifestA=closeDirector.manifest(); const manifestB=closeDirector.manifest(); eq(manifestA.digest,manifestB.digest,'manifest-deterministic'); eq(manifestA.activeEpisodeId,'stable_master','manifest-episode');
const prior=closeDirector.setCursor(5); eq(prior.ok,true,'cursor-set'); eq(prior.view.cursor,5,'cursor-set-value'); const previous=closeDirector.previous(); eq(previous.ok,true,'previous-ok'); eq(previous.view.cursor,4,'previous-value'); const next=closeDirector.next(); eq(next.ok,true,'next-ok'); eq(next.view.cursor,5,'next-value');
for(const [id,stepId] of [['market_routes','market-06'],['winter_supply','winter-04'],['road_watch','watch-02'],['hearth_and_home','home-02'],['stable_master','stable-02'],['iron_and_oath','iron-06']]){ const d=createSettlementEpisodeDirector({runtime:runtimeWithOutcome()}); d.openEpisode(id); const index=d.snapshot().episode.beats.findIndex((b)=>b.stepId===stepId); d.setCursor(index); const p=d.prepareCurrent(); eq(p.action,getSettlementEpisodeBeat(id,stepId).action,`action:${stepId}`); ok(p.input.nodeId.length>0,`node:${stepId}`); }
const eventDirector=createSettlementEpisodeDirector({runtime:runtimeWithOutcome(),now:()=>123}); eventDirector.openEpisode('iron_and_oath'); await eventDirector.executeCurrent({requestId:'event-1'}); ok(eventDirector.snapshot().history.length>=3,'history-kept'); const reset=eventDirector.reset(); ok(reset.ok,'reset-ok'); eq(reset.view.phase,'idle','reset-idle'); eq(reset.view.episodeId,null,'reset-episode'); eventDirector.dispose(); eq(eventDirector.snapshot().phase,'disposed','dispose-phase'); const afterDispose=eventDirector.openEpisode('iron_and_oath'); eq(afterDispose.ok,false,'disposed-open-blocked'); eq(afterDispose.reason,'disposed','disposed-reason');
const conditionDirector=createSettlementEpisodeDirector({runtime:runtimeWithOutcome(),snapshot:()=>({skills:{smithing:4},inventory:{iron_ore:4}}),conditionEvaluator:(condition)=>({ok:condition==='item_03',condition})}); conditionDirector.openEpisode('iron_and_oath'); const preparedCondition=conditionDirector.prepareCurrent(); eq(preparedCondition.conditionView,null,'condition-eval-deferred');
console.log(`SETTLEMENT_EPISODE_DIRECTOR_OK checks=${checks} episodes=${ids.length}`);
