import { strict as assert } from 'node:assert';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';
import { buildSettlementEpisodePresentation } from '../src/3d/gameplay/settlementEpisodePresentationModel.js';
import { buildSettlementEpisodeCheckpoint, validateSettlementEpisodeCheckpoint, inspectSettlementEpisodeCheckpoint } from '../src/3d/gameplay/settlementEpisodeCheckpoint.js';
import { listSettlementEpisodes, getSettlementEpisode, getSettlementEpisodeBeat, buildSettlementEpisodeManifest } from '../src/3d/gameplay/settlementEpisodeContent.js';
let checks=0; const ok=(v,m)=>{assert.ok(v,m);checks+=1;}; const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
function makeRuntime(){let state={activeService:null,panel:'overview',route:[],history:[],feedback:null,lastAction:null};return{calls:[],open(service,panel){this.calls.push(['open',service,panel]);state={...state,activeService:service,panel,route:[...state.route,service]};return{ok:true,view:{...state}};},close(){this.calls.push(['close']);state={...state,activeService:null,panel:'overview'};return{ok:true,view:{...state}};},async execute(action,input){this.calls.push(['execute',action,input]);state={...state,lastAction:{action,nodeId:input.nodeId,episodeId:input.episodeId,episodeStepId:input.episodeStepId},feedback:{status:'success',code:'ok',message:'Tamamlandı.',action},history:[...state.history,{type:'action',action,stepId:input.episodeStepId}]};return{ok:true,action,nodeId:input.nodeId,view:{...state}};},view(){return{...state};},exportState(){return{version:1,runtimeVersion:1,contentVersion:2,...state,requestIds:[]};},importState(next){state={...state,...next};return{ok:true};}};}
const matrix={iron_and_oath:[['iron-01','talk','blacksmith'],['iron-02','talk','blacksmith'],['iron-03','collect','blacksmith'],['iron-04','collect','blacksmith'],['iron-05','craft','blacksmith'],['iron-06','equip','blacksmith'],['iron-07','rest','blacksmith'],['iron-08','talk','blacksmith']],market_routes:[['market-01','talk','market'],['market-02','buy','market'],['market-03','sell','market'],['market-04','trade','market'],['market-05','talk','market'],['market-06','travel','gate'],['market-07','sell','market'],['market-08','talk','market']],road_watch:[['watch-01','talk','barracks'],['watch-02','train','barracks'],['watch-03','equip','barracks'],['watch-04','talk','barracks'],['watch-05','travel','gate'],['watch-06','travel','gate'],['watch-07','talk','barracks'],['watch-08','travel','gate']],hearth_and_home:[['home-01','rest','house'],['home-02','save','house'],['home-03','interact','house'],['home-04','talk','house'],['home-05','rest','house'],['home-06','save','house'],['home-07','interact','house'],['home-08','talk','house']],winter_supply:[['winter-01','talk','farm'],['winter-02','collect','farm'],['winter-03','collect','farm'],['winter-04','craft','farm'],['winter-05','trade','farm'],['winter-06','rest','farm'],['winter-07','travel','gate'],['winter-08','talk','farm']],stable_master:[['stable-01','talk','stable'],['stable-02','trade','stable'],['stable-03','rest','stable'],['stable-04','talk','stable'],['stable-05','travel','gate'],['stable-06','travel','gate'],['stable-07','talk','stable'],['stable-08','travel','gate']]};
for(const [episodeId,beats] of Object.entries(matrix)){const runtime=makeRuntime();const director=createSettlementEpisodeDirector({runtime,now:()=>100});const opened=director.openEpisode(episodeId);ok(opened.ok,`open-${episodeId}`);eq(opened.view.episodeId,episodeId,`episode-${episodeId}`);eq(opened.view.cursor,0,`cursor-start-${episodeId}`);for(let index=0;index<beats.length;index+=1){const [stepId,action,service]=beats[index];const beat=getSettlementEpisodeBeat(episodeId,stepId);ok(beat,`beat-${stepId}`);eq(beat.action,action,`action-${stepId}`);eq(beat.service,service,`service-${stepId}`);const moved=director.setCursor(index);ok(moved.ok,`cursor-set-${stepId}`);eq(director.snapshot().cursor,index,`cursor-read-${stepId}`);const prepared=director.prepareCurrent({});eq(prepared.stepId,stepId,`prepared-step-${stepId}`);eq(prepared.action,action,`prepared-action-${stepId}`);eq(prepared.service,service,`prepared-service-${stepId}`);ok(prepared.input.nodeId,`node-${stepId}`);const model=buildSettlementEpisodePresentation(director.snapshot());eq(model.primary.id,stepId,`primary-${stepId}`);eq(model.primary.action.id,action,`primary-action-${stepId}`);eq(model.primary.service.id,service,`primary-service-${stepId}`);ok(model.primary.hints.length===3,`hints-${stepId}`);ok(model.cards.length===8,`cards-${stepId}`);ok(model.actions.length>=1,`actions-${stepId}`);const cp=buildSettlementEpisodeCheckpoint(director.snapshot(),runtime.exportState());ok(validateSettlementEpisodeCheckpoint(cp).ok,`checkpoint-${stepId}`);eq(inspectSettlementEpisodeCheckpoint(cp).cursor,index,`checkpoint-cursor-${stepId}`);}}
const manifestA=buildSettlementEpisodeManifest();const manifestB=buildSettlementEpisodeManifest();eq(JSON.stringify(manifestA),JSON.stringify(manifestB),'manifest-deterministic');eq(manifestA.episodes.length,6,'six-episodes');eq(manifestA.contract,'shared-material-placement-v1','shared-contract');
const failRuntime=makeRuntime();const failDirector=createSettlementEpisodeDirector({runtime:failRuntime});failDirector.openEpisode('iron_and_oath');failRuntime.execute=async()=>({ok:false,reason:'insufficient-copper',message:'Yetersiz bakır.'});const blocked=await failDirector.executeCurrent({requestId:'blocked-1'});eq(blocked.ok,false,'blocked-result');eq(blocked.phase,'blocked','blocked-phase');eq(failDirector.snapshot().cursor,0,'blocked-cursor');const blockedModel=buildSettlementEpisodePresentation(failDirector.snapshot());ok(blockedModel.primary,'blocked-primary');ok(buildSettlementEpisodePresentation({...failDirector.snapshot(),feedback:{status:'blocked',code:'insufficient-copper',message:'Yetersiz bakır.'}}),'blocked-presentation');
const duplicateRuntime=makeRuntime();const duplicateDirector=createSettlementEpisodeDirector({runtime:duplicateRuntime});duplicateDirector.openEpisode('market_routes');const success=await duplicateDirector.executeCurrent({requestId:'dup-1'});ok(success.ok,'duplicate-first');const duplicate=await duplicateDirector.executeCurrent({requestId:'dup-1'});eq(duplicate.ok,false,'duplicate-second');eq(duplicate.reason,'duplicate-request','duplicate-reason');
const navigation=makeRuntime();const navDirector=createSettlementEpisodeDirector({runtime:navigation});navDirector.openEpisode('stable_master');const atStart=navDirector.previous();ok(atStart.ok,'previous-at-start');eq(atStart.view.cursor,0,'previous-at-start-cursor');const advanced=navDirector.next();ok(advanced.ok,'next-from-start');eq(advanced.view.cursor,1,'next-from-start-cursor');const back=navDirector.previous();ok(back.ok,'previous-from-second');eq(back.view.cursor,0,'previous-from-second-cursor');const terminal=navDirector.setCursor(8);eq(terminal.complete,true,'terminal-set');eq(navDirector.snapshot().phase,'complete','terminal-phase');
for(const id of listSettlementEpisodes()){const episode=getSettlementEpisode(id);eq(episode.beats.length,8,`eight-beats-${id}`);ok(episode.entry.requires.includes('runtime-ready'),`runtime-ready-${id}`);ok(episode.completion.rewardSource==='settlementCampaignQuestChains',`owner-${id}`);}
console.log(`SETTLEMENT_EPISODE_FULL_MATRIX_OK checks=${checks} beats=48`);
