#!/usr/bin/env node
import crypto from 'node:crypto'; import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import devServerHelper from './devServerHelper.js';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'); const arg=process.argv.find(v=>v.startsWith('--out-dir='));
const OUT=path.resolve(ROOT,arg?arg.slice(10):'artifacts/ne-g60-road-path-visual'); const probePath=path.join(ROOT,'godot/terrain-authoring/.terrain3d-proof/g60-road-path-probe.json');
const ok=(v,m)=>{if(!v)throw new Error(m)}; const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
ok(fs.existsSync(probePath),'G60 Road/Path probe missing'); const probe=JSON.parse(fs.readFileSync(probePath,'utf8'));
ok(probe.geoCell==='G60'&&probe.layer==='Road/Path','unexpected probe'); ok(probe.crossingEdges.length===0,'runtime route crossed G60 guard');
ok(probe.rows.flat().every(s=>s[0]===-8&&s[1]===0&&s[2]===0&&s[3]===0&&s[4]===0),'probe contains route paint');
const playwright=devServerHelper.loadPlaywright(); ok(Boolean(playwright),'Playwright required'); fs.mkdirSync(OUT,{recursive:true});
const server=await devServerHelper.startStaticServer(); const {port}=server.address(); const browser=await playwright.chromium.launch({headless:true}); const hashes={};
try{
 const page=await browser.newPage({viewport:{width:960,height:640}}); const errors=[]; page.on('pageerror',e=>errors.push(String(e))); await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'domcontentloaded',timeout:20000});
 const local=await page.evaluate(async source=>{ const THREE=await import('/src/3d/vendor/three/three.module.js'); document.body.innerHTML='<canvas id="proof" width="960" height="640"></canvas>'; document.body.style.margin='0';
  const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('#proof'),antialias:true,preserveDrawingBuffer:true}); renderer.setSize(960,640,false); renderer.outputColorSpace=THREE.SRGBColorSpace;
  const scene=new THREE.Scene(); scene.background=new THREE.Color(0x071722); const camera=new THREE.PerspectiveCamera(48,1.5,1,5000); const pos=[],col=[],idx=[]; let maxRoute=0;
  for(let y=0;y<65;y++)for(let x=0;x<65;x++){const s=source.rows[y][x]; maxRoute=Math.max(maxRoute,Math.abs(s[1]),Math.abs(s[2]),Math.abs(s[3])); pos.push((x/64-.5)*1200,s[0]*8,(y/64-.5)*760); col.push(s[5],s[6],s[7]);}
  for(let y=0;y<64;y++)for(let x=0;x<64;x++){const a=y*65+x,b=a+1,c=a+65,d=c+1;idx.push(a,c,b,b,c,d);} const g=new THREE.BufferGeometry(); g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('color',new THREE.Float32BufferAttribute(col,3));g.setIndex(idx);g.computeVertexNormals();
  const m=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.86,metalness:0,side:THREE.DoubleSide});scene.add(new THREE.Mesh(g,m));scene.add(new THREE.HemisphereLight(0xd8efff,0x10222a,2));const sun=new THREE.DirectionalLight(0xffefd4,2.2);sun.position.set(-420,720,-360);scene.add(sun);
  window.__proof={render:k=>{camera.position.set(k==='near'?-330:0,k==='near'?220:930,k==='near'?470:1280);camera.lookAt(0,-40,0);renderer.render(scene,camera)},dispose:()=>{g.dispose();m.dispose();renderer.dispose()}};window.__proof.render('near');return{vertices:pos.length/3,triangles:idx.length/3,maxRoute,minHeight:-8,maxHeight:-8};},probe);
 ok(local.vertices===4225&&local.triangles===8192&&local.maxRoute===0,'local Road/Path proof drifted');
 for(const kind of ['near','far']){await page.evaluate(k=>window.__proof.render(k),kind);const png=await page.locator('#proof').screenshot();ok(png.length>1024,`${kind} PNG small`);fs.writeFileSync(path.join(OUT,`g60-road-path-${kind}.png`),png);hashes[kind]=sha(png);} await page.evaluate(()=>window.__proof.dispose());
 await page.setViewportSize({width:1200,height:800}); const topdown=await page.evaluate(async()=>{const {sampleReferencePindexQualityV2}=await import('/src/3d/world/worldReferenceSurfacePindexes.js');document.body.innerHTML='<canvas id="world" width="1200" height="800"></canvas>';const c=document.querySelector('#world'),ctx=c.getContext('2d',{alpha:false}),low=document.createElement('canvas');low.width=600;low.height=400;const q=low.getContext('2d',{alpha:false}),im=q.createImageData(600,400),pal={sea:[41,77,93],lake:[79,127,134],soil:[125,135,88],rock:[117,108,96],snow:[216,223,220]};let transitions=0,prev=null;
  for(let y=0;y<400;y++){const row=[];for(let x=0;x<600;x++){const s=sampleReferencePindexQualityV2((x+.5)/600,(y+.5)/400);row.push(s.dominantSurface);if(x&&row[x-1]!==row[x])transitions++;if(prev&&prev[x]!==row[x])transitions++;let r=0,g=0,b=0;for(const [n,p]of Object.entries(pal)){const w=s.surfaceWeights[n];r+=p[0]*w;g+=p[1]*w;b+=p[2]*w;}im.data.set([Math.round(r),Math.round(g),Math.round(b),255],(y*600+x)*4);}prev=row;}q.putImageData(im,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.filter='blur(4px)';ctx.drawImage(low,0,0,1200,800);ctx.filter='none';const px=ctx.getImageData(0,0,1200,800).data;let maxDelta=0;const cmp=(a,b)=>{for(let k=0;k<3;k++)maxDelta=Math.max(maxDelta,Math.abs(px[a+k]-px[b+k]))};for(let y=0;y<800;y++)for(let x=0;x<1200;x++){const i=(y*1200+x)*4;if(x)cmp(i,i-4);if(y)cmp(i,i-4800);}return{outputResolution:[1200,800],contextResolution:[600,400],transitionEdges:transitions,g60RoadPatchAlpha:0,gridOverlay:false,maxAdjacentChannelDelta:maxDelta,evidenceClass:'continuous-semantic-world-context'};});
 ok(topdown.transitionEdges>100,'world geography disappeared');ok(topdown.g60RoadPatchAlpha===0&&!topdown.gridOverlay,'G60 road square/grid appeared');ok(topdown.maxAdjacentChannelDelta<=16,`hard edge ${topdown.maxAdjacentChannelDelta}`);const world=await page.locator('#world').screenshot();ok(world.length>4096,'world PNG small');fs.writeFileSync(path.join(OUT,'g60-road-path-full-world.png'),world);hashes.fullWorld=sha(world);ok(new Set(Object.values(hashes)).size===3,'evidence images not distinct');ok(errors.length===0,`page errors: ${errors.join(' | ')}`);
 const out={sourceMapSha256:probe.sourceMapSha256,policyId:probe.policyId,runtimeRoadReferenceEnvelope:probe.runtimeRoadReferenceEnvelope,local,topdown,sha256:hashes};fs.writeFileSync(path.join(OUT,'g60-road-path-visual-metrics.json'),`${JSON.stringify(out,null,2)}\n`);console.log(`G60_ROAD_PATH_VISUAL_METRICS=${JSON.stringify(out)}`);console.log('NE_G60_ROAD_PATH_VISUAL_EVIDENCE_OK');
}finally{await browser.close();await new Promise(r=>server.close(r));}
