#!/usr/bin/env node
const fs = require('fs');
const http = require('http');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'artifacts', 'run212');
const assert = (v, m) => { if (!v) throw new Error(m); };
const playwright = (() => { for (const id of ['playwright','/opt/node22/lib/node_modules/playwright']) { try { return require(id); } catch {} } return null; })();
function type(file){const e=path.extname(file).toLowerCase();return ({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.glb':'model/gltf-binary','.gltf':'model/gltf+json'})[e]||'application/octet-stream';}
function serve(){const s=http.createServer((req,res)=>{const clean=decodeURIComponent(req.url.split('?')[0]);const rel=clean==='/'?'index.html':clean.replace(/^\//,'');const f=path.resolve(ROOT,rel);if(!f.startsWith(ROOT+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);res.end('Not found');return;}res.writeHead(200,{'content-type':type(f),'cache-control':'no-store'});fs.createReadStream(f).pipe(res);});return new Promise(r=>s.listen(0,'127.0.0.1',()=>r(s)));}
async function prove(browser,base,mobile,errors){const context=await browser.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2}:{viewport:{width:1440,height:900}});const page=await context.newPage();const label=mobile?'mobile':'desktop';page.on('console',m=>{if(m.type()==='error')errors.push(`${label} console: ${m.text()}`);});page.on('pageerror',e=>errors.push(`${label} pageerror: ${String(e)}`));try{await page.goto(`${base}/rts.html`,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForSelector('body[data-rts-ready="true"]',{timeout:180000});await page.waitForFunction(()=>window.__WESTEROS_RTS_RALLY__?.getSnapshot&&window.__WESTEROS_RTS_SURFACE__?.status==='ready',null,{timeout:60000});const box=await page.locator('#rts-canvas').boundingBox();assert(box,`${label} canvas missing`);await page.mouse.click(box.x+box.width*.61,box.y+box.height*.57,{button:'right'});await page.waitForFunction(()=>window.__WESTEROS_RTS_RALLY__.getSnapshot().visible===true,null,{timeout:10000});const active=await page.evaluate(()=>({marker:window.__WESTEROS_RTS_RALLY__.getSnapshot(),rts:window.__WESTEROS_RTS__.getSnapshot(),status:document.getElementById('rts-status')?.textContent||''}));assert(active.marker.opacity>.1,`${label} marker opacity too low`);assert(Number.isFinite(active.marker.position.y),`${label} marker Y non-finite`);assert(active.status.includes('asker hedefe ilerliyor'),`${label} command ownership/status drifted`);assert(active.rts.selectedCount===48,`${label} selection drifted`);assert(active.rts.drawCalls<(mobile?500:2500),`${label} draw calls exceeded`);assert(active.rts.triangles<(mobile?500000:5000000),`${label} triangles exceeded`);await page.screenshot({path:path.join(OUT,`${label}-rally-marker.png`),fullPage:true});const initialRemaining=active.marker.remainingSeconds;await page.waitForFunction(initial=>{const s=window.__WESTEROS_RTS_RALLY__.getSnapshot();return s.remainingSeconds<initial-.15;},initialRemaining,{timeout:30000});await page.waitForFunction(()=>window.__WESTEROS_RTS_RALLY__.getSnapshot().visible===false,null,{timeout:60000});const expired=await page.evaluate(()=>window.__WESTEROS_RTS_RALLY__.getSnapshot());assert(expired.remainingSeconds===0,`${label} marker expiry remaining=${expired.remainingSeconds}`);return {active,expired};}finally{await context.close();}}
(async()=>{if(!playwright)throw new Error('Playwright unavailable');fs.mkdirSync(OUT,{recursive:true});const s=await serve();const browser=await playwright.chromium.launch({headless:true});const errors=[];const base=`http://127.0.0.1:${s.address().port}`;try{const desktop=await prove(browser,base,false,errors);const mobile=await prove(browser,base,true,errors);assert(errors.length===0,`console/page errors: ${errors.join(' | ')}`);const proof={desktop,mobile,errors,visualEvidence:['desktop-rally-marker.png','mobile-rally-marker.png']};fs.writeFileSync(path.join(OUT,'proof.json'),JSON.stringify(proof,null,2));console.log(`[checkRun212RtsRallyMarkerRuntime] PROOF: ${JSON.stringify(proof)}`);console.log('[checkRun212RtsRallyMarkerRuntime] PASS: runtime-time expiry, command ownership, desktop/mobile budgets and console are clean');}finally{await browser.close();await new Promise(r=>s.close(r));}})().catch(e=>{console.error(`[checkRun212RtsRallyMarkerRuntime] FAIL: ${e.stack||e}`);process.exitCode=1;});