import { strict as assert } from 'node:assert';
import { listSettlementEpisodeDialogue,getSettlementEpisodeDialogue,getSettlementEpisodeDialogueScene,validateSettlementEpisodeDialogue,buildSettlementEpisodeDialogueManifest,resolveSettlementEpisodeDialogueChoice,createSettlementEpisodeDialogueResolver } from '../src/3d/gameplay/settlementEpisodeDialogueContent.js';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';
import { createSettlementEpisodeDialoguePresenter,buildSettlementEpisodeDialogueView,resolveSettlementEpisodeDialogueSelection } from '../src/3d/gameplay/settlementEpisodeDialoguePresenter.js';
import { getSettlementEpisode } from '../src/3d/gameplay/settlementEpisodeContent.js';

let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks+=1;};const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
const validation=validateSettlementEpisodeDialogue();ok(validation.ok,'dialogue-validation');eq(validation.errors.length,0,'dialogue-errors-zero');
const ids=listSettlementEpisodeDialogue();eq(ids.length,6,'dialogue-episode-count');const manifestA=buildSettlementEpisodeDialogueManifest();const manifestB=buildSettlementEpisodeDialogueManifest();eq(JSON.stringify(manifestA),JSON.stringify(manifestB),'dialogue-manifest-deterministic');eq(manifestA.sceneCount,48,'dialogue-scene-count');
const resolver=createSettlementEpisodeDialogueResolver();ok(resolver.valid,'resolver-valid');eq(resolver.version,1,'resolver-version');
for(const episodeId of ids){
 const scenes=getSettlementEpisodeDialogue(episodeId);ok(scenes,'scenes-present:'+episodeId);eq(scenes.length,8,'scene-count:'+episodeId);eq(new Set(scenes.map((s)=>s.stepId)).size,8,'unique-steps:'+episodeId);
 const authored=getSettlementEpisode(episodeId);eq(authored.beats.length,8,'beat-parity:'+episodeId);
 for(const scene of scenes){
  ok(scene.speaker.length>0,'speaker:'+scene.stepId);ok(scene.line.length>0,'line:'+scene.stepId);eq(scene.choices.length,3,'choice-count:'+scene.stepId);eq(new Set(scene.choices.map((choice)=>choice.id)).size,3,'choice-ids:'+scene.stepId);ok(scene.ux.showSpeaker===true,'speaker-ux:'+scene.stepId);ok(scene.ux.showChoices===true,'choice-ux:'+scene.stepId);ok(scene.tags.length>=4,'tags:'+scene.stepId);
  const beat=authored.beats.find((entry)=>entry.stepId===scene.stepId);ok(beat,'beat-exists:'+scene.stepId);eq(scene.action,beat.action,'action-parity:'+scene.stepId);
  for(const choice of scene.choices){const selected=resolveSettlementEpisodeDialogueChoice(episodeId,scene.stepId,choice.id);ok(selected.ok,'choice:'+scene.stepId+':'+choice.id);eq(selected.episodeId,episodeId,'choice-episode:'+scene.stepId+':'+choice.id);eq(selected.stepId,scene.stepId,'choice-step:'+scene.stepId+':'+choice.id);eq(selected.input.episodeStepId,scene.stepId,'dispatch-step:'+scene.stepId+':'+choice.id);eq(selected.input.dialogueChoiceId,choice.id,'dispatch-choice:'+scene.stepId+':'+choice.id);eq(selected.dispatch.action,scene.action,'dispatch-action:'+scene.stepId+':'+choice.id);}
  const bad=resolveSettlementEpisodeDialogueChoice(episodeId,scene.stepId,'missing');eq(bad.ok,false,'bad-choice:'+scene.stepId);eq(bad.reason,'unknown-choice','bad-choice-reason:'+scene.stepId);
 }
}
const runtime={open(service,panel){return{ok:true,service,panel};},async execute(action,input){return{ok:true,action,nodeId:input.nodeId,view:{activeService:input.nodeId,panel:'quests'}};},view(){return{activeService:'tavern',panel:'quests',history:[],feedback:null};},close(){return{ok:true};}};
const director=createSettlementEpisodeDirector({runtime});director.openEpisode('iron_and_oath');const dialogueModel=buildSettlementEpisodeDialogueView(director.snapshot());ok(dialogueModel.ok,'presenter-view-ok');eq(dialogueModel.episodeId,'iron_and_oath','presenter-episode');eq(dialogueModel.stepId,'iron-01','presenter-step');eq(dialogueModel.choices.length,3,'presenter-choices');eq(dialogueModel.speaker,'Usta Boran','presenter-speaker');
const selection=resolveSettlementEpisodeDialogueSelection(director.snapshot(),dialogueModel.choices[1].id);ok(selection.ok,'selection-ok');eq(selection.choiceId,dialogueModel.choices[1].id,'selection-choice');eq(selection.input.episodeId,'iron_and_oath','selection-episode');eq(selection.input.episodeStepId,'iron-01','selection-step');
const callbacks=[];const presenter=createSettlementEpisodeDialoguePresenter({onSelect:(value)=>callbacks.push(value)});const selected=await presenter.select(director.snapshot(),'accept');ok(selected.ok,'presenter-select');eq(callbacks.length,1,'presenter-callback');const view=presenter.view(director.snapshot());ok(view.ok,'presenter-direct-view');eq(view.choices.length,3,'presenter-view-choice-count');presenter.dispose();eq(presenter.view(director.snapshot()).ok,false,'presenter-disposed');
const unknownScene=buildSettlementEpisodeDialogueView({episodeId:'iron_and_oath',beat:{stepId:'missing'},phase:'ready'});eq(unknownScene.ok,false,'unknown-scene-safe');eq(unknownScene.reason,'dialogue-scene-missing','unknown-scene-reason');const noDialogue=buildSettlementEpisodeDialogueView({episodeId:null,beat:null});eq(noDialogue.ok,false,'no-dialogue-safe');eq(noDialogue.reason,'no-current-dialogue','no-dialogue-reason');
const knownScene=getSettlementEpisodeDialogueScene('market_routes','market-06');ok(knownScene,'known-travel-scene');eq(knownScene.action,'travel','travel-dialogue-action');eq(knownScene.choices.length,3,'travel-choice-count');const routeChoice=resolveSettlementEpisodeDialogueChoice('market_routes','market-06','route');eq(routeChoice.dispatch.action,'travel','travel-dispatch');
const farmScene=getSettlementEpisodeDialogueScene('winter_supply','winter-04');eq(farmScene.action,'craft','farm-craft-dialogue');const farmChoice=resolveSettlementEpisodeDialogueChoice('winter_supply','winter-04','craft');eq(farmChoice.input.dialogueChoiceId,'craft','farm-craft-choice');
const homeScene=getSettlementEpisodeDialogueScene('hearth_and_home','home-02');eq(homeScene.action,'save','home-save-dialogue');const homeChoice=resolveSettlementEpisodeDialogueChoice('hearth_and_home','home-02','save');eq(homeChoice.dispatch.action,'save','home-save-dispatch');
const barracksScene=getSettlementEpisodeDialogueScene('road_watch','watch-02');eq(barracksScene.action,'train','barracks-train-dialogue');const stableScene=getSettlementEpisodeDialogueScene('stable_master','stable-08');eq(stableScene.action,'travel','stable-travel-dialogue');
console.log(`SETTLEMENT_EPISODE_DIALOGUE_OK checks=${checks} scenes=48 choices=144`);
