import { strict as assert } from 'node:assert';
import { listSettlementEpisodes, getSettlementEpisode, getSettlementEpisodeBeat, getSettlementEpisodeForChain, buildSettlementEpisodeManifest, validateSettlementEpisodeContent, createSettlementEpisodeContentResolver } from '../src/3d/gameplay/settlementEpisodeContent.js';
import { getSettlementQuestChain, getSettlementQuestChainStep, getSettlementQuestChainReward } from '../src/3d/gameplay/settlementCampaignQuestChains.js';
import { getSettlementService, getSettlementQuestObjective, getSettlementDialogueCondition, getSettlementRecipe, getSettlementRoute, getSettlementItem } from '../src/3d/gameplay/settlementCampaignContent.js';
let checks=0; const ok=(v,m)=>{assert.ok(v,m);checks+=1;}; const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
const EXPECTED={iron_and_oath:{service:'blacksmith',actions:['talk','talk','collect','collect','craft','equip','rest','talk'],steps:['iron-01','iron-02','iron-03','iron-04','iron-05','iron-06','iron-07','iron-08']},market_routes:{service:'market',actions:['talk','buy','sell','trade','talk','travel','sell','talk'],steps:['market-01','market-02','market-03','market-04','market-05','market-06','market-07','market-08']},road_watch:{service:'barracks',actions:['talk','train','equip','talk','travel','travel','talk','travel'],steps:['watch-01','watch-02','watch-03','watch-04','watch-05','watch-06','watch-07','watch-08']},hearth_and_home:{service:'house',actions:['rest','save','interact','talk','rest','save','interact','talk'],steps:['home-01','home-02','home-03','home-04','home-05','home-06','home-07','home-08']},winter_supply:{service:'farm',actions:['talk','collect','collect','craft','trade','rest','travel','talk'],steps:['winter-01','winter-02','winter-03','winter-04','winter-05','winter-06','winter-07','winter-08']},stable_master:{service:'stable',actions:['talk','trade','rest','talk','travel','travel','talk','travel'],steps:['stable-01','stable-02','stable-03','stable-04','stable-05','stable-06','stable-07','stable-08']}};
const validation=validateSettlementEpisodeContent(); ok(validation.ok,'valid'); eq(validation.errors.length,0,'errors-zero'); const resolver=createSettlementEpisodeContentResolver(); ok(resolver.valid,'resolver-valid'); eq(resolver.version,1,'resolver-version'); const manifest=buildSettlementEpisodeManifest(); eq(manifest.episodes.length,6,'manifest-episodes'); eq(manifest.contract,'shared-material-placement-v1','manifest-contract');
for(const [id,expected] of Object.entries(EXPECTED)){
 const episode=getSettlementEpisode(id); ok(episode,`episode:${id}`); eq(episode.id,id,`id:${id}`); eq(episode.chainId,id,`chain:${id}`); eq(episode.service,expected.service,`service:${id}`); eq(episode.beats.length,8,`beats:${id}`); eq(episode.beats.map((b)=>b.action).join('|'),expected.actions.join('|'),`actions:${id}`); eq(episode.beats.map((b)=>b.stepId).join('|'),expected.steps.join('|'),`steps:${id}`); ok(getSettlementEpisodeForChain(id),`for-chain:${id}`);
 for(let i=0;i<8;i+=1){ const beat=episode.beats[i]; const step=getSettlementQuestChainStep(id,beat.stepId); ok(step,`step:${beat.stepId}`); eq(beat.action,step.action,`action-parity:${beat.stepId}`); ok(getSettlementQuestObjective(step.objective),`objective:${beat.stepId}`); for(const condition of step.conditions??[]) ok(getSettlementDialogueCondition(condition),`condition:${beat.stepId}:${condition}`); if(step.recipe) ok(getSettlementRecipe(step.recipe),`recipe:${beat.stepId}`); if(step.route) ok(getSettlementRoute(step.route),`route:${beat.stepId}`); if(step.target) ok(getSettlementItem(step.target),`item:${beat.stepId}`); const resolved=getSettlementEpisodeBeat(id,beat.stepId); ok(resolved,`resolved:${beat.stepId}`); eq(resolved.stepId,beat.stepId,`resolved-id:${beat.stepId}`); }
 const reward=getSettlementQuestChainReward(id); ok(reward,`reward:${id}`); ok(reward.xp>0,`reward-xp:${id}`); ok(reward.copper>0,`reward-copper:${id}`); const service=getSettlementService(expected.service); ok(service,`service-def:${id}`); ok(Array.isArray(service.actions),`service-actions:${id}`);
}
const actionSet=new Set(); const serviceSet=new Set(); for(const id of listSettlementEpisodes()){ const episode=getSettlementEpisode(id); serviceSet.add(episode.service); for(const beat of episode.beats) actionSet.add(beat.action); }
for(const action of ['talk','collect','buy','sell','trade','craft','equip','rest','train','travel','save','interact']) ok(actionSet.has(action),`action:${action}`);
for(const service of ['blacksmith','market','barracks','house','farm','stable']) ok(serviceSet.has(service),`service:${service}`);
const titles=listSettlementEpisodes().flatMap((id)=>getSettlementEpisode(id).beats.map((b)=>b.title)); eq(new Set(titles).size,48,'unique-titles'); eq(titles.length,48,'all-titles');
const snapshots=listSettlementEpisodes().map((id)=>{const e=resolver.get(id);return {id:e.id,service:e.service,beats:e.beats.map((b)=>({stepId:b.stepId,action:b.action,prompt:b.prompt}))};}); const repeat=listSettlementEpisodes().map((id)=>{const e=resolver.get(id);return {id:e.id,service:e.service,beats:e.beats.map((b)=>({stepId:b.stepId,action:b.action,prompt:b.prompt}))};}); eq(JSON.stringify(snapshots),JSON.stringify(repeat),'repeatable');
const malformed=resolver.resolve('unknown','missing'); eq(malformed.ok,false,'unknown-ok'); eq(malformed.reason,'unknown-beat','unknown-reason');
for(const [id,stepId] of [['iron_and_oath','iron-05'],['market_routes','market-06'],['road_watch','watch-02'],['hearth_and_home','home-02'],['winter_supply','winter-04'],['stable_master','stable-02']]){ const beat=resolver.resolve(id,stepId); ok(beat.ok,`resolve:${stepId}`); ok(beat.quest,`quest:${stepId}`); ok(beat.service,`service:${stepId}`); eq(beat.stepId,stepId,`step-id:${stepId}`); }
const chainDigest=JSON.stringify(manifest); const chainRepeat=JSON.stringify(buildSettlementEpisodeManifest()); eq(chainDigest,chainRepeat,'manifest-repeat');
console.log(`SETTLEMENT_EPISODE_CATALOG_OK checks=${checks} episodes=${listSettlementEpisodes().length} beats=${titles.length}`);
