import { strict as assert } from 'node:assert';
import { listSettlementAssetRoots, getSettlementPlacementOrder, classifySettlementAssetPath, buildAssetSourceEvidence, buildMaterialPlacementEvidence, validateSettlementAssetEvidence, createSettlementAssetPlacementManifest, summarizeAssetPlacementManifest } from '../src/3d/gameplay/settlementCampaignAssetEvidence.js';
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks+=1;};const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
eq(listSettlementAssetRoots().length,8,'asset-roots');eq(getSettlementPlacementOrder().at(0),'source-asset','placement-order-source');eq(getSettlementPlacementOrder().at(-1),'scene-attachment','placement-order-end');
const model=classifySettlementAssetPath('assets/models/settlements/blacksmith.glb');ok(model.valid&&model.kind==='model','model-classification');const texture=classifySettlementAssetPath('assets/textures/settlement/roof.webp');ok(texture.valid&&texture.kind==='texture','texture-classification');ok(!classifySettlementAssetPath('src/editor/fake.glb').valid,'foreign-path-rejected');
const source=buildAssetSourceEvidence({assetPath:'assets/models/settlements/blacksmith.glb',lfsPointer:'',lfsHydrationStatus:'not-needed',selectiveHydration:true,derivedAsset:'derived/blacksmith.glb'});ok(source.ok&&source.sourcePreserved,'source-evidence');const hydrated=buildAssetSourceEvidence({assetPath:'assets/models/fbx/house.fbx',lfsPointer:'oid sha256:test',lfsHydrationStatus:'hydrated',selectiveHydration:true});ok(hydrated.ok,'hydrated-lfs-evidence');
const evidence=buildMaterialPlacementEvidence({assetPath:'assets/models/settlements/blacksmith.glb',selectiveHydration:true,materialContract:'MaterialAssignmentCore',placementContract:'WorldAssetPlacementPipeline',manifestId:'mat-place-1',slotCount:5,palette:['wall','roof','wood','metal','stone'],pbr:true,textureSizes:[2048,2048,1024],groundAligned:true,slopeCompatible:true,naturalScale:true,spacingValid:true,orientation:'canonical',sceneAttached:true});ok(validateSettlementAssetEvidence(evidence).ok,'full-placement-evidence');const manifest=createSettlementAssetPlacementManifest(evidence,{id:'blacksmith-proof'});ok(manifest.ok,'placement-manifest');const summary=summarizeAssetPlacementManifest(manifest);eq(summary.id,'blacksmith-proof','manifest-summary-id');eq(summary.paletteCount,5,'palette-count');ok(summary.pbr&&summary.groundAligned&&summary.sceneAttached,'manifest-proof');
const bad=buildMaterialPlacementEvidence({assetPath:'assets/models/settlements/bad.glb',slotCount:1,palette:[],pbr:false,groundAligned:false,slopeCompatible:false,naturalScale:false,spacingValid:false});ok(!validateSettlementAssetEvidence(bad).ok,'bad-evidence-rejected');
console.log(`SETTLEMENT_CAMPAIGN_ASSET_EVIDENCE_OK checks=${checks}`);
