import { strict as assert } from 'node:assert';
import { createSettlementEpisodeDirector } from '../src/3d/gameplay/settlementEpisodeDirector.js';
import { buildSettlementEpisodeRuntimeSnapshot,buildSettlementEpisodeRuntimeSnapshotDigest,validateSettlementEpisodeRuntimeSnapshot,buildSettlementEpisodeRuntimeSnapshotProof,createSettlementEpisodeRuntimeSnapshotResolver } from '../src/3d/gameplay/settlementEpisodeRuntimeSnapshot.js';
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks+=1;};const eq=(a,b,m)=>{assert.equal(a,b,m);checks+=1;};
function runtime(){let state={activeService:null,panel:'overview',route:[],history:[],feedback:null,lastAction:null};return{open(service,panel){state={...state,activeService:service,panel,route:[...state.route,service]};return{ok:true,view:{...state}};},async execute(action,input){state={...state,lastAction:{action,nodeId:input.nodeId,episodeId:input.episodeId,episodeStepId:input.episodeStepId},history:[...state.history,{type:'action',action}]};return{ok:true,action,nodeId:input.nodeId,view:{...state}};},close(){state={...state,activeService:null,panel:'overview'};return{ok:true};},view(){return{...state};},exportState(){return{version:1,runtimeVersion:1,contentVersion:2,...state,requestIds:[]};},importState(next){state={...state,...next};return{ok:true};}};}
const rt=runtime();const director=createSettlementEpisodeDirector({runtime:rt,now:()=>100});director.openEpisode('iron_and_oath');const snap=director.snapshot();
const snapshotA=buildSettlementEpisodeRuntimeSnapshot({directorSnapshot:snap,runtimeView:rt.view(),runtimeExportState:rt.exportState(),questSnapshot:{quests:{}}});const snapshotB=buildSettlementEpisodeRuntimeSnapshot({directorSnapshot:snap,runtimeView:rt.view(),runtimeExportState:rt.exportState(),questSnapshot:{quests:{}}});
ok(snapshotA,'snapshot-created');eq(JSON.stringify(snapshotA),JSON.stringify(snapshotB),'snapshot-deterministic');eq(snapshotA.episodeId,'iron_and_oath','snapshot-episode');eq(snapshotA.stepId,'iron-01','snapshot-step');eq(snapshotA.phase,'entered','snapshot-phase');ok(snapshotA.presentation,'presentation');ok(snapshotA.dialogue,'dialogue');ok(snapshotA.journey,'journey');ok(snapshotA.progression,'progression');ok(snapshotA.save,'save');ok(snapshotA.handoff,'handoff');ok(snapshotA.checkpoint.available,'checkpoint-available');ok(snapshotA.ownership.threeDAssetAdded===false,'asset-proof-false');eq(snapshotA.ownership.runtimeOwner,'settlementCampaignRuntime','runtime-owner');eq(snapshotA.ownership.questOwner,'settlementCampaignQuestChains','quest-owner');eq(snapshotA.ownership.worldPlacementContract,'shared-material-placement-v1','placement-contract');
const digestA=buildSettlementEpisodeRuntimeSnapshotDigest(snapshotA);eq(digestA,snapshotA.digest,'digest-parity');eq(digestA,buildSettlementEpisodeRuntimeSnapshotDigest(snapshotB),'digest-stable');ok(validateSettlementEpisodeRuntimeSnapshot(snapshotA).ok,'snapshot-valid');ok(buildSettlementEpisodeRuntimeSnapshotProof(snapshotA).ok,'snapshot-proof-valid');
const tampered={...snapshotA,stepId:'iron-02'};eq(validateSettlementEpisodeRuntimeSnapshot(tampered).ok,false,'tamper-step');ok(validateSettlementEpisodeRuntimeSnapshot(tampered).errors.length>0,'tamper-errors');const digestTampered={...snapshotA,digest:'deadbeef'};eq(validateSettlementEpisodeRuntimeSnapshot(digestTampered).ok,false,'tamper-digest');
const movedDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>100});movedDirector.openEpisode('market_routes');const moved=movedDirector.setCursor(5);ok(moved.ok,'moved');const movedSnapshot=buildSettlementEpisodeRuntimeSnapshot({directorSnapshot:movedDirector.snapshot(),runtimeView:movedDirector.runtime?.view?.()??{},runtimeExportState:null,questSnapshot:{quests:{}}});eq(movedSnapshot.stepId,'market-06','moved-step');eq(movedSnapshot.handoff.runtimeAction,'travel','moved-runtime-action');eq(movedSnapshot.handoff.inputKey,'routeId','moved-input');eq(movedSnapshot.save.prompt.visible,true,'moved-save-visible');
const completeDirector=createSettlementEpisodeDirector({runtime:runtime(),now:()=>100});completeDirector.openEpisode('hearth_and_home');completeDirector.setCursor(8);const completeSnapshot=buildSettlementEpisodeRuntimeSnapshot({directorSnapshot:completeDirector.snapshot(),runtimeView:{activeService:'house',panel:'overview'},runtimeExportState:null,questSnapshot:{quests:{hearth_and_home:{state:'completed'}}}});eq(completeSnapshot.progression.episodes[0].status,'available','progression-independent');eq(completeSnapshot.phase,'complete','complete-phase');eq(completeSnapshot.save.prompt.reason,'episode-completion','complete-save');
const resolver=createSettlementEpisodeRuntimeSnapshotResolver();eq(resolver.version,1,'resolver-version');ok(resolver.validate(snapshotA).ok,'resolver-validation');eq(resolver.digest(snapshotA),snapshotA.digest,'resolver-digest');ok(resolver.proof(snapshotA).ok,'resolver-proof');
const noRuntime=buildSettlementEpisodeRuntimeSnapshot({directorSnapshot:snap,runtimeView:null,runtimeExportState:null,questSnapshot:{quests:{}}});eq(noRuntime.runtime.activeService,'','no-runtime-service');eq(noRuntime.checkpoint.available,false,'no-runtime-checkpoint');ok(validateSettlementEpisodeRuntimeSnapshot(noRuntime).ok,'no-runtime-valid');
console.log(`SETTLEMENT_EPISODE_RUNTIME_SNAPSHOT_OK checks=${checks}`);
