#!/usr/bin/env node
import assert from 'node:assert/strict';
import { buildGroundwaterSurfaceDetailDiagnostic, diagnosticBatch, diagnosticBatchSummary, diagnosticFailureHistogram, diagnosticChannelExtrema, diagnosticOwnershipSummary, diagnosticEnvelopeSummary, diagnosticQuickCheck, diagnosticRunManifest } from '../src/3d/world/terrainGroundwaterSurfaceDetailDiagnostics.js';
import { TERRAIN_GROUNDWATER_DETAIL_SCENARIOS } from '../src/3d/world/terrainGroundwaterSurfaceDetailScenarioCatalog.js';
const inputs=TERRAIN_GROUNDWATER_DETAIL_SCENARIOS.slice(0,40).map(c=>({worldX:c.worldX,worldZ:c.worldZ,heightMeters:c.height,slopeDegrees:c.slope,moisture:c.moisture,rainfall:c.rain,runoff:c.runoff,soilDepth:c.soil,permeability:c.perm,waterDistanceMeters:c.water,groundwaterDepthMeters:c.table,wetDays:c.wetDays,dryDays:c.dryDays,temperatureC:c.temp,drainage:c.drain,windExposure:c.wind,dayOfYear:c.day}));
let passed=0;
const check=(name,fn)=>{fn();passed+=1;console.log(`[groundwater-detail-diagnostics] PASS: ${name}`)};
const material={color:{r:.42,g:.36,b:.3},roughness:.86,normalStrength:0,wetness:0};
check('diagnostic manifest has stages',()=>assert.ok(diagnosticRunManifest(40).stages.length>=10));
check('single diagnostic passes',()=>assert.equal(buildGroundwaterSurfaceDetailDiagnostic(inputs[0],material).ok,true));
check('single quick check passes',()=>assert.equal(diagnosticQuickCheck(inputs[0]).ok,true));
check('single diagnostic has identity',()=>assert.equal(buildGroundwaterSurfaceDetailDiagnostic(inputs[0]).stages.identity.ok,true));
check('single diagnostic has shader',()=>assert.equal(buildGroundwaterSurfaceDetailDiagnostic(inputs[0]).stages.shader.ok,true));
check('single diagnostic has calibration',()=>assert.equal(buildGroundwaterSurfaceDetailDiagnostic(inputs[0]).stages.calibration.ok,true));
check('single diagnostic has preset',()=>assert.equal(buildGroundwaterSurfaceDetailDiagnostic(inputs[0]).stages.preset.ok,true));
check('single diagnostic has stack',()=>assert.equal(buildGroundwaterSurfaceDetailDiagnostic(inputs[0],material).stages.stack.ok,true));
const reports=diagnosticBatch(inputs,material);
check('batch preserves count',()=>assert.equal(reports.length,inputs.length));
check('batch reports pass',()=>assert.ok(reports.every(r=>r.ok)));
check('batch summary passes',()=>{const s=diagnosticBatchSummary(reports);assert.equal(s.count,inputs.length);assert.equal(s.failed,0);assert.equal(s.passRate,1)});
check('failure histogram is empty',()=>assert.deepEqual(diagnosticFailureHistogram(reports),{}));
check('channel extrema cover channels',()=>assert.ok(Object.keys(diagnosticChannelExtrema(reports.map(r=>r.stages.channel?{channels:r.stages.channel.values}:r))).length>=14));
check('ownership summary is clean',()=>{const s=diagnosticOwnershipSummary(reports);assert.equal(s.canonicalFailures,0);assert.equal(s.zeroMutation,true);assert.equal(s.noNewGeography,true);assert.equal(s.heightPreserved,true);assert.equal(s.hydrologyPreserved,true)});
check('envelope summary is clean',()=>{const s=diagnosticEnvelopeSummary(reports);assert.equal(s.boundsFailures,0);assert.equal(s.allBounded,true)});
check('diagnostics are deterministic',()=>assert.deepEqual(buildGroundwaterSurfaceDetailDiagnostic(inputs[4],material),buildGroundwaterSurfaceDetailDiagnostic(inputs[4],material)));
check('diagnostic report is frozen',()=>assert.ok(Object.isFrozen(buildGroundwaterSurfaceDetailDiagnostic(inputs[2],material))));
check('diagnostic stages are frozen',()=>assert.ok(Object.isFrozen(buildGroundwaterSurfaceDetailDiagnostic(inputs[2],material).stages)));
check('diagnostic summary is frozen',()=>assert.ok(Object.isFrozen(buildGroundwaterSurfaceDetailDiagnostic(inputs[2],material).summary)));
check('diagnostic batch is frozen',()=>assert.ok(Object.isFrozen(reports)));
check('diagnostic batch handles empty',()=>assert.deepEqual(diagnosticBatch([]),[]));
check('diagnostic histogram handles empty',()=>assert.deepEqual(diagnosticFailureHistogram([]),{}));
check('diagnostic batch summary handles empty',()=>assert.deepEqual(diagnosticBatchSummary([]),{count:0,passed:0,failed:0,passRate:1,classes:{},tiers:{}}));
check('diagnostic channel extrema handles empty',()=>assert.equal(Object.keys(diagnosticChannelExtrema([])).length,14));
check('diagnostic ownership handles empty',()=>{const s=diagnosticOwnershipSummary([]);assert.equal(s.count,0);assert.equal(s.canonicalFailures,0);assert.equal(s.zeroMutation,true);assert.equal(s.noNewGeography,true)});
check('diagnostic envelope handles empty',()=>{const s=diagnosticEnvelopeSummary([]);assert.equal(s.count,0);assert.equal(s.boundsFailures,0);assert.equal(s.allBounded,true)});
check('diagnostic quick check keeps summary',()=>{const q=diagnosticQuickCheck(inputs[8]);assert.ok(q.summary);assert.ok(q.failures)});
check('diagnostic identities are stable',()=>{const a=buildGroundwaterSurfaceDetailDiagnostic(inputs[9]);const b=buildGroundwaterSurfaceDetailDiagnostic({...inputs[9]});assert.equal(a.stages.identity.ok,true);assert.equal(a.stages.identity.policyId,b.stages.identity.policyId)});
console.log(`[groundwater-detail-diagnostics] PASS: ${passed} checks over ${inputs.length} inputs`);
