import { writeFile } from 'node:fs/promises';

const domains = Object.freeze([
  'signals', 'lighting', 'weather', 'safety', 'traffic', 'services', 'resources',
  'navigation', 'shelter', 'activity', 'visibility', 'ground', 'ecology', 'exposure',
  'culture', 'commerce', 'travel', 'incidents', 'comfort', 'maintenance',
]);

const rows = [];
for (const domain of domains) {
  for (let slot = 1; slot <= 210; slot += 1) {
    const priority = (slot % 5) + 1;
    const capacity = (slot % 7) + 1;
    const threshold = Number((0.1 + ((slot * 7) % 90) / 100).toFixed(2));
    const persistence = (slot % 9) + 1;
    const response = (slot + domains.indexOf(domain)) % 4;
    rows.push(`  { id: '${domain}-${slot}', domain: '${domain}', slot: ${slot}, priority: ${priority}, capacity: ${capacity}, threshold: ${threshold}, persistence: ${persistence}, response: ${response} },`);
  }
}

const output = `/** Generated by scripts/generateSettlementDecisionRuntimeV69.mjs. */
export const V69_POLICY = Object.freeze({ version: 69, deterministic: true, noWorldMutation: true, catalogCount: 4200 });
export const V69_DOMAINS = Object.freeze(${JSON.stringify(domains)});
export const V69_CATALOG = Object.freeze([\n${rows.join('\n')}\n]);
`;

if (rows.length !== 4200) throw new Error(`expected 4200 rows, received ${rows.length}`);
await writeFile('src/3d/world/settlementDecisionRuntimeV69Generated.js', output, 'utf8');
console.log(`generated ${rows.length} settlement decision rows`);
