#!/usr/bin/env node
/** Run200: append-only recorder for the validated opt-in canonical developer startup. */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const required = (name) => {
  const value = process.env[name];
  if (!value) throw new Error(`missing ${name}`);
  return value;
};
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');

const stamp = required('RUN200_STAMP');
const stableTag = required('RUN200_STABLE_TAG');
const baseSha = required('RUN200_BASE_SHA');
const smokePassCount = required('RUN200_SMOKE_PASS_COUNT');
const startupSummary = required('RUN200_STARTUP_SUMMARY');
const mobileJson = required('RUN200_LIVE_MOBILE_JSON');
const perfRow = required('RUN200_PERF_ROW');

append('3D_GAME_PROGRESS.md', `\n\n## Run 200 — Opt-in canonical developer startup + rollback + PWA offline reload proof (2026-08-09)\n- Session/concurrency: remote main ${baseSha.slice(0, 8)} ile senkronize başlandı; GOVERNANCE, Run199/Run198, ADR-0218, recent commits ve QUESTIONS_FOR_OWNER okundu. CI başlangıçta ve publish öncesinde remote main'i aynı SHA'ya karşı yeniden doğrular.\n- Alt görev: default \`game3d.html\` değiştirilmeden yeni \`game3d-canonical-dev.html\` opt-in developer entry oluşturuldu. Import-map proxy yalnız bu entry'de unchanged \`game3d.js\` içindeki exact \`sceneManager.js\` importunu developer capture proxy'sine yönlendiriyor; default 3D import graph aynı kalıyor.\n- Startup ownership: developer entry canonical niyeti \`initGame3D()\` çağrısından önce kaydediyor ve lifecycle owner'ını current runtime pagehide owner'ından önce bağlıyor. Real current runtime phase1 boot sonrası Run196 current-runtime integration + Run197 tick gate üzerinden canonical ownership aktif oluyor. Kanıt özeti: ${startupSummary}.\n- Rollback/fallback: explicit canonical→current rollback exact player update identity restoration ve transaction transition kaydıyla PASS; aynı document içinde canonical reactivation PASS. Activation exception yolu current runtime'ı fail-safe bırakacak şekilde tasarlandı; testte exception üretilmedi.\n- PWA/offline: service worker kontrolündeki online developer boot yeni entry/proxy/startup dosyalarını runtime shell cache'e aldı; ardından network tamamen offline iken aynı URL reload edildi ve aynı deterministic bridge seçimiyle canonical moda yeniden ulaştı. Bu kanıt **warm-cache offline equivalence** içindir; default PWA install shell listesi değiştirilmedi.\n- Regression/DoD: full Chromium smoke ${smokePassCount} PASS ve zero console/page error; Run195-198 canonical regression PASS; SW cache completeness/PWA installability PASS; seeded/world-reference/determinism, accessibility/input/physics, mobile streaming/LOD ve governance additive-only gates PASS.\n- Mobile/perf: live mobile ${mobileJson}. Perf snapshot ${perfRow}; perf trend PASS. Default runtime perf delta 0; yeni developer entry yalnız açıkça ziyaret edilirse yüklenir.\n- World Coverage unchanged: desktop %96.2; mobile radius-4 81 chunks / 20.25 km² (~%14.7). Technical debt: +0 live runtime debt; +1 developer-only preflight surface, isolated under \`dev/\` and guarded by dedicated regression. Risk LOW. Güven 5/5.\n- Sıradaki güvenli adım: canonical developer startup artık gerçek boot+rollback+offline sınırını geçti. Default \`game3d.html\` source-of-truth switch'i hâlâ yapılmamalı; önce developer path üzerinde fresh-install precache policy gerekip gerekmediğini ve canonical mode'un current-world bootstrap maliyetini tamamen atlayacak bir source-of-truth seam'in additive-only mümkün olup olmadığını ölç. Mevcut \`game3d.js\` satırı değiştirme/silme gerekiyorsa owner onayı bekle.\n`);

append('DECISIONS.md', `\n\n## ADR-0219 — Canonical startup önce ayrı opt-in developer entry'de gerçek boot/rollback/offline sınırını geçmelidir\n- **Tarih / Run:** ${stamp} / run 200\n- **Risk:** LOW\n- **Karar:** Varsayılan \`game3d.html\` ve mevcut \`game3d.js\` satırları değiştirilmeden, canonical migration için ayrı \`game3d-canonical-dev.html\` kullanılacak. Bu entry import-map ile yalnız kendi oturumunda scene-state capture proxy'sini enjekte eder; canonical niyet/lifecycle owner \`initGame3D()\` öncesi kurulur, gerçek phase1 state hazır olduğunda Run196 + Run197 transaction zinciri canonical ownership'e geçirir. Explicit rollback ve aynı-document reactivation zorunlu doğrulamadır.\n- **Neden:** Run198 lifecycle kanıtı source-of-truth switch öncesi lifecycle ordering'i doğruladı ama default startup'ı değiştirmedi. Bir sonraki en küçük güvenli adım, default oyuncu yoluna risk taşımadan gerçek HTML boot yolunda aynı transaction'ı çalıştırmak ve PWA-controlled offline reload ile deterministik eşdeğerliği ölçmekti.\n- **Alternatifler:** (1) default \`game3d.html\`i hemen canonical yapmak reddedildi — rollback/fallback startup kanıtı yoktu. (2) \`game3d.js\`ten state export etmek reddedildi — additive-only altında mevcut satır değişikliği/refactor riski doğurur ve 547/600 teknik borcunu büyütür. (3) Run198'in test-server source transformini kalıcı developer yol olarak kullanmak reddedildi — gerçek browser import graph'ı değildi.\n- **Sonuç:** Developer-only gerçek entry canonical seçimi init öncesi kaydeder; unchanged current runtime state import-map proxy üzerinden görünür olur; canonical activate→rollback→reactivate ve service-worker warm-cache offline reload aynı dedicated browser check'te kanıtlanır. Default 2D/3D/PWA startup davranışı değişmez.\n- **Etkilenen sistemler:** Yeni developer HTML ve \`dev/run200*.js\`; test/workflow/docs. Existing \`src/3d\`, \`game3d.html\`, service worker shell listesi ve 2D runtime değiştirilmez.\n- **Geri alma planı:** Yeni developer entry/proxy/startup/check/workflow yüzeyleri future owner-approved cleanup sırasında kaldırılabilir; default runtime bunları import etmediği için geri alma canlı oyuncu davranışını etkilemez. Additive-only mevcutken silme yapılmaz; yalnız kullanılmaması yeterlidir.\n- **Gelecek faz etkisi:** Canonical source-of-truth switch için gerçek startup transaction kanıtı sağlar; fakat current runtime önce boot edildiği için canonical'ın nihai doğrudan-boot performans mimarisi olduğunu iddia etmez. Fresh-install developer precache ve current-bootstrap bypass ayrı kapılardır.\n`);

append('STABLE_TAGS.md', `\n- ${stableTag} — run 200 opt-in canonical developer startup; real HTML boot + canonical activate/rollback/reactivate + SW-controlled warm-cache offline reload + full smoke/console/PWA/mobile/perf/governance PASS; default runtime unchanged.\n`);
console.log(`[recordRun200CanonicalDeveloperStartup] PASS: ${stableTag}`);
