#!/usr/bin/env node
/** Run202 validated-checkpoint recorder. Appends documentation only after the workflow's full DoD passes. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const required = (name) => { const value = process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp = required('RUN202_STAMP');
const tag = required('RUN202_STABLE_TAG');
const base = required('RUN202_BASE_SHA');
const smoke = required('RUN202_SMOKE_PASS_COUNT');
const proof = JSON.parse(required('RUN202_PROOF_JSON'));
const mobile = JSON.parse(required('RUN202_LIVE_MOBILE_JSON'));
const perf = required('RUN202_PERF_ROW');
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');
const perfFields = perf.split(',');
if (perfFields.length < 8 || perfFields[1] !== 'run202') throw new Error(`unexpected perf row: ${perf}`);
const [, , fps, drawCalls, triangles, geometries, textures, heap] = perfFields;
const finalCycle = proof.cycles[proof.cycles.length - 1];

append('3D_GAME_PROGRESS.md', `\n\n## Run 202 — Canonical developer fallback matrix + pagehide/offline lifecycle retention proof\n\n- **Validated:** ${stamp}; base main \`${base}\`.\n- No live/default runtime source changed. Run202 adds only a browser proof, CI workflow and post-DoD recorder around the existing Run201 developer-only surface.\n- Real Chromium proves three non-opt-in requests (default, explicit \`worldSource=current\`, unknown source) all remain \`current\`; explicit \`worldSource=canonical-dev\` remains the only canonical path.\n- After online canonical cache warm, three same-tab network-offline canonical navigations cross real \`pagehide\` boundaries and reopen the same deterministic bridge \`${proof.onlineCanonical.bridge}\`. Every active document has one canvas, prior pagehide timer/interval/RAF counts remain zero, disposal hook tokens remain present, post-GC document/node/listener retention stays bounded, and console/page errors=${proof.consoleErrors}. Final DOM counters: documents=${finalCycle.dom.documents}, nodes=${finalCycle.dom.nodes}, listeners=${finalCycle.dom.jsEventListeners}.\n- Full browser smoke: **${smoke}+ PASS**, default 3D boot zero console/page errors; Run195-201 canonical migration/offline regressions PASS; seeded/world-reference contracts PASS; PWA cache/installability PASS.\n- Mobile live budget: **${mobile.drawCalls} draw calls / ${mobile.triangles} triangles / ${mobile.geometries} geometries / ${mobile.textures} textures**, inside <500/<500000. Coverage unchanged: desktop **96.2%**; mobile radius-4 **81 chunks / 20.25 km² (~14.7%)**.\n- Perf snapshot: **fps ${fps}, ${drawCalls} draw calls, ${triangles} triangles, ${geometries} geometries, ${textures} textures, ${heap} MB heap**; trend guard reports no sustained upward heap drift.\n- Technical debt: **no new live-runtime debt**. Existing structural warnings and owner-gated decisions remain untouched. Risk **LOW**, confidence **5/5**.\n- **Next safe step (Run203):** keep default startup unchanged and prove a developer launcher can select current/canonical explicitly without duplicating runtime ownership or changing PWA/default navigation; do not promote canonical to player default without a separate migration gate.\n`);

append('DECISIONS.md', `\n\n## ADR-0221 — Require fallback and disposal-retention proof before any wider canonical developer launcher\n\n- **Decision:** Keep canonical startup developer-only and add a real-browser gate covering default/current/unknown fallback plus repeated pagehide→offline canonical reopen, bounded DOM/listener retention and zero outstanding page-owned timeout/interval/RAF handles at the disposal boundary.\n- **Why:** Run201 proved one online→offline canonical reload, but did not jointly prove that non-opt-in inputs stay current or that repeated document boundaries do not accumulate browser-owned surface state. This is the smallest safe migration proof before any broader developer launcher is considered.\n- **Alternatives:** promote canonical to default now (rejected: migration evidence remains intentionally developer-scoped); modify Run201 live developer boot for extra observability (rejected: unnecessary runtime delta); rely only on synthetic selector tests (rejected: misses real service-worker/document lifecycle behavior).\n- **Result:** three fallback forms resolve to current, explicit canonical survives repeated offline reopens on a deterministic bridge, one canvas remains active, timer/RAF counts are zero at pagehide capture, post-GC document/node/listener counts remain bounded, and console/page errors remain zero.\n- **Affected systems:** CI/test/documentation only. 2D, default 3D, gameplay/world code, service worker source, manifest and live mobile/desktop/PWA behavior remain unchanged.\n- **Rollback:** the Run202 test/workflow files are inert outside CI and may be removed only in a future owner-approved non-additive cleanup.\n- **Risk:** LOW.\n`);

append('STABLE_TAGS.md', `\n- \`${tag}\` — Run202 developer fallback + pagehide/offline lifecycle-retention proof; ${smoke}+ smoke PASS, canonical regressions/PWA/mobile/perf/additive/concurrency gates PASS; live/default runtime delta 0.\n`);

console.log(`[recordRun202CanonicalDevLifecycle] appended Run202 progress, ADR-0221 and stable checkpoint ${tag}`);