#!/usr/bin/env node
/** Run205 validated-checkpoint recorder. Appends documentation only after the workflow's full DoD passes. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const required = name => { const value = process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp = required('RUN205_STAMP');
const tag = required('RUN205_STABLE_TAG');
const base = required('RUN205_BASE_SHA');
const smoke = required('RUN205_SMOKE_PASS_COUNT');
const proof = JSON.parse(required('RUN205_PROOF_JSON'));
const mobile = JSON.parse(required('RUN205_LIVE_MOBILE_JSON'));
const perf = required('RUN205_PERF_ROW');
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');
const fields = perf.split(',');
if (fields.length < 8 || fields[1] !== 'run205') throw new Error(`unexpected perf row: ${perf}`);
const [, , fps, drawCalls, triangles, geometries, textures, heap] = fields;
append('3D_GAME_PROGRESS.md', `\n\n## Run 205 — Isolated developer standalone PWA shell proof\n\n- **Validated:** ${stamp}; base main \`${base}\`.\n- Added only a developer-scoped PWA shell under \`/canonical-dev-pwa/\`; production \`manifest.json\`, root \`service-worker.js\`, default 2D/3D startup and live runtime sources remain byte-unchanged.\n- Real Chromium proves a dedicated \`display=standalone\` developer manifest, a dedicated service-worker controller scoped only to \`/canonical-dev-pwa/\`, exactly ${proof.cachedEntries} cached developer-shell entries all inside that subtree, and a clean offline shell reload with canvas=${proof.canvas} and console/page errors=${proof.consoleErrors}.\n- Current/Canonical links intentionally remain outside the developer PWA scope and continue targeting the existing explicit developer runtime URLs; no default-player navigation is widened.\n- Full browser smoke: **${smoke}+ PASS**; Run195-204 canonical regressions PASS; production PWA cache/installability PASS.\n- Mobile live budget: **${mobile.drawCalls} draw calls / ${mobile.triangles} triangles / ${mobile.geometries} geometries / ${mobile.textures} textures**, within <500/<500000. Coverage unchanged: desktop **96.2%**; mobile radius-4 **81 chunks / 20.25 km² (~14.7%)**.\n- Perf snapshot: **fps ${fps}, ${drawCalls} draw calls, ${triangles} triangles, ${geometries} geometries, ${textures} textures, ${heap} MB heap**; trend guard PASS.\n- Technical debt: **no new live-runtime debt**. Developer-only maintenance surface +1 isolated PWA subtree. Risk **LOW**, confidence **5/5**.\n- **Next safe step (Run206):** keep production startup unchanged and prove the isolated developer standalone shell's out-of-scope Current/Canonical launches cannot capture or replace the production service-worker controller; verify controller ownership before/after return navigation, including offline recovery.\n`);
append('DECISIONS.md', `\n\n## ADR-0224 — Isolate standalone developer installability in its own service-worker scope\n\n- **Decision:** Add a developer-only PWA shell under \`/canonical-dev-pwa/\` with its own manifest, icon and service worker scoped to that subtree; keep Current/Canonical runtime targets outside that scope.\n- **Why:** Run204 proved offline history ownership but did not prove a standalone/installable developer shell. A narrow subtree scope provides that proof without modifying the production manifest, root service worker, default startup or live runtime.\n- **Alternatives:** extend the production manifest/root service worker (rejected: widens live PWA scope); make canonical startup the production start URL (rejected: owner-visible behavior change); skip standalone proof (rejected: leaves Run204's next gate open).\n- **Result:** Chromium sees \`display=standalone\`; the developer SW controls only \`/canonical-dev-pwa/\`; all developer precache entries remain inside that subtree; offline shell reload succeeds with zero runtime canvas and zero console/page errors.\n- **Affected systems:** new developer-only PWA subtree, CI/test/documentation. 2D, default 3D, gameplay/world sources, production service worker/manifest and player navigation unchanged.\n- **Rollback:** new Run205 files are inert unless the developer subtree is opened directly and may be removed only in a future owner-approved non-additive cleanup.\n- **Risk:** LOW.\n`);
append('STABLE_TAGS.md', `\n- \`${tag}\` — Run205 isolated developer standalone PWA proof; ${smoke}+ smoke PASS, canonical regressions/production-PWA/mobile/perf/additive/concurrency gates PASS; live/default runtime delta 0.\n`);
console.log(`[recordRun205DeveloperStandalonePwa] appended Run205 progress, ADR-0224 and stable checkpoint ${tag}`);
