import fs from 'node:fs';

const stamp = process.env.RUN167_STAMP;
const stableTag = process.env.RUN167_STABLE_TAG;
const perfRow = process.env.RUN167_PERF_ROW;
const smokeCount = process.env.RUN167_SMOKE_PASS_COUNT;

if (!stamp || !stableTag || !perfRow || !smokeCount) {
  throw new Error('Run167 governance environment is incomplete.');
}

const progress = `\n\n## Run 167 — Determinism policy CI repair (${stamp})\n- Alt görev: seeded-random politikasını otomatikleştiren run 167 guard'ının ilk main koşusunda ortaya çıkan false-positive CI kırığı düzeltildi. Guard artık proje-owned \`src/3d\` kodunda executable \`Math.random()\` çağrılarını engellerken yorum metinlerini ve üçüncü taraf \`vendor/\` ağacını politika ihlali saymıyor. Workflow \`src/3d/**\` değişikliklerinde ve pull request'lerde de çalışıyor.\n- Root Cause: ilk guard ham satır metnine regex uyguluyor ve tüm alt dizinleri aynı sahiplik alanı kabul ediyordu; bu nedenle yorumlardaki API adı ile vendored Three.js içindeki üçüncü taraf çağrılar project-owned runtime ihlali gibi raporlandı. Prevention: comment-aware tarama + vendor ownership boundary + pozitif/negatif regression fixture.\n- Additive-only: mevcut kaynak satırı silinmedi; nihai PR diff'i 0 deletion. Runtime/gameplay/world kodu değiştirilmedi.\n- DoD: node --check PASS; determinism baseline + injected-call regression fixture PASS; assets/PWA/cache, terrain-seat ve road-network güvenlik kapıları PASS; browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; World Event Determinism Guard PASS; additive-only PASS.\n- Görsel doğrulama: runtime görsel deltası yok; yine de gerçek 390x844 mobile Chromium yakın + F4 uzak iki render kanıtı üretildi ve console/page error 0 doğrulandı.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime nesnesi, listener, timer, geometry, material veya asset eklenmedi; CI-only değişiklik.\n- Teknik borç: 1 (önceden var olan game3d.js yapısal borcu; run 167 yeni runtime borcu eklemedi). Risk LOW. Güven 5/5.\n- ADR: ADR-0189. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; determinism regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak prosedürel regresyonların main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan governance öncelik sırasındaki bağımsız terrain/road/visual kalite işine, zorunlu pre/post safety + F4 kanıt zinciriyle dönmek; başlamadan remote main ve paralel ajan değişiklikleri yeniden kontrol edilmeli.\n`;

const adr = `\n\n## ADR-0189 — Determinism policy scans project-owned executable code, not vendored/comment text (run 167)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkSeededRandomPolicy.js\`, \`src/3d\` altında project-owned JavaScript'te executable \`Math.random()\` çağrılarını reddeder; \`vendor/\` dizinini sahiplik sınırının dışında tutar ve line/block comment içindeki salt dokümantasyon metnini tarama kararından çıkarır. CI aynı politikayı \`src/3d/**\` değişikliklerinde ve pull request'lerde çalıştırır.\n\n**Neden:** İlk run 167 uygulaması doğru determinism niyetini otomatikleştirdi ancak ham-text taraması nedeniyle yorumlar ve vendored Three.js yanlış pozitif üreterek kendi ilk main koşusunu kırdı. Bir politika kapısının project-owned executable davranışı ölçmesi, üçüncü taraf kaynak metnini veya dokümantasyon sözcüklerini ölçmesinden daha doğru ve sürdürülebilirdir.\n\n**Alternatifler:** (1) Tüm \`Math.random\` metnini yasaklamak — false positive ve vendor bakım maliyeti nedeniyle reddedildi. (2) Vendor dosyalarını değiştirmek — üçüncü taraf koduna müdahale ve lisans/upgrade riski nedeniyle reddedildi. (3) Guard'ı kaldırmak — GOVERNANCE determinism sözleşmesini yeniden manuel kontrole düşüreceği için reddedildi. (4) Tam AST parser bağımlılığı eklemek — mevcut dar politika için gereksiz dependency/cache yüzeyi; ihtiyaç büyürse ileride değerlendirilebilir.\n\n**Sonuç:** Project-owned runtime'da doğrudan unseeded random kullanımına karşı fail-fast CI korunur; yorumlar ve vendored kod false positive üretmez. Regression fixture hem kabul edilmesi gereken comment/vendor örneklerini hem de reddedilmesi gereken executable çağrıyı her koşuda doğrular.\n\n**Etkilenen sistemler:** \`scripts/checkSeededRandomPolicy.js\`, \`.github/workflows/run167-determinism-policy.yml\`, CI determinism/pull-request kalite kapısı ve governance kayıtları. Runtime, 2D oyun, 3D dünya üretimi, asset/PWA import grafiği değişmez.\n\n**Geri alma planı:** Politika gelecekte AST tabanlı analizörle genişletilirse yeni analizör additive bir script olarak eklenip workflow ikinci kapı olarak çalıştırılabilir; mevcut guard satırlarını silmeye gerek yoktur.\n`;

const stable = `\n- ${stableTag} — run 167 determinism policy CI repair (ADR-0189); ${smokeCount}/34+ browser smoke, comment/vendor + injected-call regression fixture, PWA/world/determinism gates PASS; runtime delta 0.\n`;

fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);

console.log(`Run167 governance records appended for ${stableTag}.`);
