#!/usr/bin/env node
/** Run207 validated-checkpoint recorder. Appends documentation only after the workflow's full DoD passes. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const required = name => { const value = process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp = required('RUN207_STAMP');
const tag = required('RUN207_STABLE_TAG');
const base = required('RUN207_BASE_SHA');
const smoke = required('RUN207_SMOKE_PASS_COUNT');
const proof = JSON.parse(required('RUN207_PROOF_JSON'));
const mobile = JSON.parse(required('RUN207_LIVE_MOBILE_JSON'));
const perf = required('RUN207_PERF_ROW');
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');
const fields = perf.split(',');
if (fields.length < 8 || fields[1] !== 'run207-rts') throw new Error(`unexpected perf row: ${perf}`);
const [, , fps, drawCalls, triangles, geometries, textures, heap] = fields;
const desktop = proof.desktopAfterCommand || proof.desktopInitial;
const rtsMobile = proof.mobileAfterCommand || proof.mobileInitial;
append('3D_GAME_PROGRESS.md', `\n\n## Run 207 — Visible RTS command surface / high-camera army control\n\n- **Validated:** ${stamp}; base main \`${base}\`.\n- Development priority pivoted from background canonical/PWA migration to the player's visible game surface. The existing 2D game and character-driven 3D mode remain intact; \`rts.html\` is a new additive command surface and \`game3d.html\` gains only an RTS entry link.\n- Added a character-independent high command camera and a deterministic **${desktop.unitCount}-soldier** instanced army. Soldiers support single selection, Shift additive selection, drag-box selection, Select All, desktop right-click formation movement, touch Move Command, WASD/arrow camera pan, zoom and army focus.\n- Reuses the established world rather than duplicating it: real castle GLBs (**${desktop.realCastleCount} roots loaded in proof**), terrain/grass/vegetation, roads, water/lakes/rivers, configured animals (**${desktop.animalCount}**) and dragon (**${desktop.dragonCount}**) render together with the controllable army.\n- Real Chromium visual proof: desktop overview + command view + mobile command screenshots; console/page errors **${proof.consoleErrors}**. Desktop after-command render: **${desktop.drawCalls} draw calls / ${desktop.triangles} triangles** (<2500/<5M). RTS mobile render: **${rtsMobile.drawCalls} draw calls / ${rtsMobile.triangles} triangles** (<500/<500000).\n- Full legacy browser smoke: **${smoke}+ PASS**; seeded/world-reference/terrain/road regressions PASS; production PWA cache/installability PASS. Existing mobile live budget: **${mobile.drawCalls} draw calls / ${mobile.triangles} triangles / ${mobile.geometries} geometries / ${mobile.textures} textures**.\n- World Coverage unchanged: desktop **96.2%**; mobile radius-4 **81 chunks / 20.25 km² (~14.7%)**. Perf snapshot: **fps ${fps}, ${drawCalls} draw calls, ${triangles} triangles, ${geometries} geometries, ${textures} textures, ${heap} MB heap**; trend guard PASS.\n- Technical debt: the first controllable army deliberately uses lightweight procedural/instanced soldier geometry rather than the heavier authored human FBX roster; the initial overview camera is functionally readable but still wider/darker than the intended Age-of-Empires-style presentation; per-frame instance transform scratch allocation is a future GC optimization target. No debt was added to the legacy character/2D runtimes. Risk **LOW-MEDIUM**, confidence **4/5**.\n- **Next safe visible step (Run208):** stay on the visible RTS track: improve AoE-style camera framing/readability and daylight presentation, introduce visually richer licensed/reused human/guard populations with LOD/instancing discipline, add destination/formation feedback, and prove the richer scene stays inside desktop/mobile budgets. Background canonical migration remains paused unless the owner reprioritizes it.\n`);
append('DECISIONS.md', `\n\n## ADR-0226 — Add a separate high-camera RTS surface instead of replacing the existing character runtime\n\n- **Decision:** Introduce \`rts.html\` + \`src/3d/rts/\` as an additive command surface that reuses the established deterministic world and gameplay creatures while leaving \`game3d.html\`'s player-character runtime operational. Expose the RTS mode from the existing 3D page with one additive navigation link.\n- **Why:** The owner explicitly reprioritized visible gameplay toward Age-of-Empires-style group control and away from single-character attachment, while the permanent rules still forbid deleting/changing existing source lines and require 2D/3D/PWA regressions to remain intact. A sibling surface gives a playable RTS immediately without destabilizing the proven character runtime.\n- **Alternatives:** replace \`game3d.js\` startup (rejected: non-additive/high regression risk); retrofit the existing player loop with mode branches (deferred: requires touching a near-600-line orchestrator and couples RTS ownership to the avatar); build a second world implementation (rejected: duplicates terrain/roads/water/castles and threatens determinism).\n- **Result:** a deterministic 48-unit selectable army, formation movement, high camera, real castles, vegetation/roads/water, animals and dragon coexist in one visible RTS surface; desktop/mobile browser proofs stay within budgets and legacy smoke/PWA checks remain green.\n- **Affected systems:** new RTS HTML/CSS/controller/army/test/CI surfaces; one additive navigation line in \`game3d.html\`; additive service-worker cache registration for the RTS shell. Existing player/gameplay/world source lines and the 2D runtime are unchanged.\n- **Rollback:** the RTS files and additive navigation/cache registrations are isolated; a future owner-approved non-additive cleanup can remove the sibling surface without changing the legacy world/runtime architecture.\n- **Future-phase impact:** this establishes a safe visible-game seam for richer troops/civilians, formations, selection feedback and eventual RTS combat/economy without forcing canonical-world migration to become the player's default startup.\n- **Risk:** LOW-MEDIUM.\n`);
append('STABLE_TAGS.md', `\n- \`${tag}\` — Run207 first visible RTS command surface; ${desktop.unitCount} selectable soldiers, real castles/roads/water/animals/dragon, desktop+mobile visual proofs, ${smoke}+ legacy smoke, PWA/perf/additive/concurrency gates PASS.\n`);
console.log(`[recordRun207VisibleRtsSurface] appended Run207 progress, ADR-0226 and stable checkpoint ${tag}`);
