#!/usr/bin/env node
/** Run201 validated-checkpoint recorder. Appends documentation only after the workflow's full DoD passes. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const required = (name) => { const value = process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp = required('RUN201_STAMP');
const tag = required('RUN201_STABLE_TAG');
const base = required('RUN201_BASE_SHA');
const smoke = required('RUN201_SMOKE_PASS_COUNT');
const proof = JSON.parse(required('RUN201_PROOF_JSON'));
const mobile = JSON.parse(required('RUN201_LIVE_MOBILE_JSON'));
const perf = required('RUN201_PERF_ROW');
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');
const perfFields = perf.split(',');
if (perfFields.length < 8 || perfFields[1] !== 'run201') throw new Error(`unexpected perf row: ${perf}`);
const [, , fps, drawCalls, triangles, geometries, textures, heap] = perfFields;

append('3D_GAME_PROGRESS.md', `\n\n## Run 201 — Opt-in canonical developer startup + real offline reload proof\n\n- **Validated:** ${stamp}; base main \`${base}\`.\n- Added developer-only \`canonical-dev.html\` + \`scripts/run201CanonicalDevBoot.mjs\`; default \`game3d.html\`, 2D shell, \`src/3d\`, service-worker source, manifest and assets remain byte-unchanged. Live/default runtime delta: **0**.\n- Explicit \`?worldSource=canonical-dev\` boots the Run200 canonical ownership path on deterministic bridge \`${proof.online.bridge}\`; first online load warms only the developer surface/module URLs into the existing shell cache, then a real Chromium network-offline reload reboots canonical successfully. Online active=\`${proof.online.active}\`, offline active=\`${proof.offline.active}\`, deterministic bridge=${proof.deterministicBridge}, console/page errors=${proof.consoleErrors}.\n- Full browser smoke: **${smoke}+ PASS**, default 3D boot zero console/page errors; Run195-200 migration/ownership/tick/lifecycle regressions PASS; seeded/world-reference contracts PASS; PWA cache/installability PASS.\n- Mobile live budget: **${mobile.drawCalls} draw calls / ${mobile.triangles} triangles / ${mobile.geometries} geometries / ${mobile.textures} textures**, inside <500/<500000. Coverage unchanged: desktop **96.2%**; mobile radius-4 **81 chunks / 20.25 km² (~14.7%)**.\n- Perf snapshot: **fps ${fps}, ${drawCalls} draw calls, ${triangles} triangles, ${geometries} geometries, ${textures} textures, ${heap} MB heap**; trend guard reports no sustained upward heap drift.\n- Technical debt: **no new live-runtime debt**. Existing structural warnings remain: \`game3d.js\` 547/600 and \`worldReferenceSceneShadowAdapter.js\` 562/600; owner-gated radius-5/game3d split/world-event-fixture decisions remain untouched. Risk **LOW**, confidence **5/5**.\n- **Next safe step (Run202):** keep default startup unchanged and extend the real developer-document proof to explicit current/unknown-source fallback plus pagehide→offline reopen disposal/leak assertions; only after that consider any wider developer launcher integration.\n`);

append('DECISIONS.md', `\n\n## ADR-0220 — Canonical startup remains opt-in; developer-only surface may warm itself into the existing PWA shell cache\n\n- **Decision:** Add a separate developer-only document that invokes the already-proven Run200 selector only when explicitly opened, and let that document cache its own HTML/boot/selector URLs after a successful online service-worker registration. Do not change \`game3d.html\`, the 2D entry, service-worker source/version, or default startup ownership.\n- **Why:** Run200 proved explicit source selection/fallback/rollback but not a real document surviving an offline reopen. Reusing the existing network-first shell cache proves actual PWA behavior without making canonical the player default or changing the service-worker contract.\n- **Alternatives:** modify default \`game3d.html\` (rejected: migration gate not mature enough); edit/bump \`service-worker.js\` to precache the dev page globally (rejected: unnecessary default-PWA surface change); keep a synthetic harness only (rejected: does not prove document + service-worker offline reopen).\n- **Result:** real Chromium online→offline reload keeps requested/active source canonical on the same deterministic bridge, with zero console/page errors; default runtime remains untouched.\n- **Affected systems:** developer validation surface and CI only; existing canonical shadow modules are consumed, not changed. 2D, default 3D, gameplay, world, mobile runtime and PWA shell behavior are unchanged unless this developer page is explicitly opened.\n- **Rollback:** remove the newly added Run201 developer files/workflow in a future owner-approved non-additive cleanup; until then they are inert because no default surface links/imports them.\n- **Risk:** LOW.\n`);

append('STABLE_TAGS.md', `\n- \`${tag}\` — Run201 opt-in canonical developer startup + real online→offline reload proof; ${smoke}+ smoke PASS, canonical regressions/PWA/mobile/perf/additive/concurrency gates PASS; default runtime delta 0.\n`);

console.log(`[recordRun201CanonicalDevOffline] appended Run201 progress, ADR-0220 and stable checkpoint ${tag}`);
