import fs from 'node:fs';

const stamp = process.env.RUN180_STAMP;
const stableTag = process.env.RUN180_STABLE_TAG;
const perfRow = process.env.RUN180_PERF_ROW;
const smokeCount = process.env.RUN180_SMOKE_PASS_COUNT;
const integrationSummary = process.env.RUN180_INTEGRATION_SUMMARY || 'first-frame grass integration PASS';
const mobileBudgetSummary = process.env.RUN180_MOBILE_BUDGET_SUMMARY || 'mobile render budget PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run180 governance environment is incomplete.');

const progress = `\n\n## Run 180 — Wind-grass first-frame visibility / real-render integration hardening (${stamp})\n- Run179'un pre-PR senior incelemesinde izole grass kontratı PASS olmasına rağmen gerçek mobil F2 örneğinin hâlâ baseline 34 draw call / 171,929 triangle göstermesi araştırıldı. Kök neden: \`createScene()\` grass'ı bootstrap kamera hücresinde üretirken \`game3d.js\` async player load sonrası kamerayı kilometrelerce uzaktaki oyuncu spawn'ına taşıyor; grass recenter yalnız mesh \`onBeforeRender\` içindeydi. Eski hücre yeni frustum dışında kalırsa Three.js mesh'i callback'ten önce cull edebilir ve grass kendi recenter callback'ini hiç çalıştıramazdı.\n- Fix additive-only: Run179'un tek, bounded grass InstancedMesh'i için \`frustumCulled=false\` işaretlendi. Bu bir world-resident milyonlarca blade politikası değildir: yalnız bir mesh her frame submit adaydır ve kendi \`onBeforeRender\` callback'i aynı bounded instance buffer'ını anında güncel kamera hücresine taşır. Game loop/game3d.js wiring'i büyütülmedi.\n- Canlı entegrasyon: ${integrationSummary}\n- Gerçek oyun mobil bütçesi: ${mobileBudgetSummary}\n- Additive-only: mevcut source satırı silinmedi/değiştirilmedi; \`sceneManager.js\` yalnız sona Run180 safety wrapper'ı aldı. Run179 grass algoritması/density/exclusion/shader değerleri değiştirilmedi.\n- DoD: node --check PASS; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; isolated grass + first-frame real-scene integration, canonical world map, medieval roads, terrain/vegetation/water/sky/fog/lighting/stars/camera, determinism, assets, accessibility/input/physics, mobile streaming/LOD/culling/perf, PWA/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: gerçek 390x844 mobile Chromium yakın + F4 uzak screenshot artifact üretildi; grass shader gerçek game boot render yolunda compile edildi ve console/page error 0.\n- Performans: ${perfRow}. Grass maliyeti artık renderer sayaçlarında gerçekten görünür; tek draw-call bounded InstancedMesh dışında yeni texture/material/geometry kopyası yok. Heap trend ayrıca kontrol edildi.\n- Memory leak checklist: yeni listener/timer/DOM yok; Run180 yeni resource yaratmıyor. Run179 grass'ın tek geometry/material dispose zinciri ve aynı instance-buffer recenter davranışı entegrasyon testinde doğrulanıyor.\n- Teknik borç: 1 (mevcut \`game3d.js\` yapısal borcu). Risk LOW. Güven 5/5. ADR: ADR-0201. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: grass görünürlük/recenter güvenilirliği +1; grass density/alan/yol/terrain/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1. Oyuncu farkı: EVET — oyuncu spawn'ına kamera taşındıktan sonraki ilk frame'de çimenin kaybolma ihtimali kapatıldı.\n- Sıradaki güvenli adım: §30 sırasına dönerek canonical worldReferenceMap relief/biome verisiyle deterministik taş/kaya kümeleri; dağ relief değişimi ancak ayrı Arazi Değişiklik Güvenlik Kontrolü run'ında.\n`;

const adr = `\n\n## ADR-0201 — Camera-local grass bypasses frustum culling to guarantee its own recenter callback (run 180)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** Run179'un tek bounded grass InstancedMesh'i \`frustumCulled=false\` kullanır. Grass'ın mevcut camera-cell streaming'i mesh \`onBeforeRender\` callback'inde kalır; callback world-seed deterministik instance buffer'ını gerektiğinde yeni 120m hücreye yeniden doldurur. Run180 başka density/radius/shader/exclusion sabiti değiştirmez.\n\n**Neden:** Scene bootstrap kamerası oyuncu yaratılmadan önce \`(0,700,1200)\` civarındadır; \`game3d.js\` player load tamamlanınca aynı kamerayı oyuncu spawn'ına birkaç kilometre taşır. Run179 mesh'i eski bootstrap cell çevresinde kaldığında normal frustum culling, \`onBeforeRender\` çağrısından önce mesh'i eleme hakkına sahiptir. Böyle bir durumda recenter mekanizması kendi kendini tetikleyemez. İlk Run179 CI'ın gerçek mobile F2 sayaçlarının grass eklendiği halde baseline'da kalması bu entegrasyon boşluğunu görünür kıldı.\n\n**Alternatifler:** (1) Grass recenter'ı \`game3d.js\` tick loop'a taşımak: 547/600 owner-blocked yapısal borcu büyütür ve grass lifecycle'ını iki dosyaya böler. (2) Bootstrap'ta grass'ı oyuncu spawn'ına tahmin ederek üretmek: sceneManager oyuncu spawn lifecycle'ını sahiplenmemeli ve gelecekteki spawn/respawn davranışıyla drift eder. (3) Devasa bounding sphere ile frustum'u kandırmak: gerçek bounded alanı yanlış temsil eder. (4) Sorunu görmezden gelmek: isolated checker yeşil kalırken kullanıcı grass görmeyebilir. Tek bounded mesh için culling'i kapatmak en dar ve ölçülebilir düzeltmedir.\n\n**Sonuç:** Kamera kilometrelerce taşınsa bile grass mesh ilk render submission'a girer, callback güncel hücreye recenter eder ve sonraki frame'lerde aynı bounded mesh çalışır. Mobilde beklenen maliyet yalnız +1 draw call ve gerçek patch sayısı × 20 triangle'dır; yeni resource, timer veya gameplay state yoktur.\n\n**Etkilenen sistemler:** additive append ile \`src/3d/sceneManager.js\`, yeni \`scripts/checkWindGrassSceneIntegrationRun180.js\`, Run180 CI/governance kayıtları. Run179 placement/shader, \`game3d.js\`, canonical world map, terrain, road, 2D, PWA import grafiği ve world seed değişmez.\n\n**Geri alma planı:** Gelecekte grass streaming ayrı bir dedicated per-frame world-decoration manager'a taşınırsa yeni manager kendi pre-cull recenter/update sözleşmesini kanıtlayıp versioned ADR ile bu bypass'ı supersede edebilir; mevcut source satırlarını sessizce değiştirmek yerine additive migration uygulanır.\n`;

const stable = `\n- ${stableTag} — run 180 wind-grass first-frame real-render integration hardening (ADR-0201); ${smokeCount}/34+ smoke + integrated grass/mobile/PWA/determinism gates PASS.\n`;

fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run180 governance records appended for ${stableTag}.`);
