import fs from 'node:fs';

const stamp = process.env.RUN169_STAMP;
const stableTag = process.env.RUN169_STABLE_TAG;
const perfRow = process.env.RUN169_PERF_ROW;
const smokeCount = process.env.RUN169_SMOKE_PASS_COUNT;
const contractSummary = process.env.RUN169_VEGETATION_CONTRACT_SUMMARY || 'live vegetation render contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run169 governance environment is incomplete.');

const progress = `\n\n## Run 169 — Vegetation visual geometry regression contract (${stamp})\n- Alt görev: run 168'in sıradaki güvenli terrain/vegetation/visual kalite yönüne uygun olarak gerçek \`createVegetation()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkVegetationVisualContract.js\` eklendi. Kontrat iki türün trunk/foliage InstancedMesh eşleşmesini, deterministik instance transformlarını, mevcut material/geometry imzalarını, static instance buffer kullanımını ve teardown zincirini doğruluyor.\n- Runtime/2D/PWA davranışı değiştirilmedi; yeni iş yalnız regresyon kapsamı ekliyor. Owner kararı bekleyen radius-5, game3d.js yapısal borcu ve world-event checksum maddelerine dokunulmadı.\n- Additive-only: yalnız yeni checker, yeni run workflow'u ve yeni governance recorder eklendi; mevcut source satırı silinmedi/değiştirilmedi.\n- DoD: node --check PASS; ${contractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat, road-network/road-visual, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; runtime görseli değişmediği için no-delta regresyon kanıtıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; yeni checker \`disposeVegetation()\` için 4 geometry + 4 material dispose olayını canlı doğruluyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 169 yeni runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0191. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: orman km²/yol/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; vegetation visual regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak ağaç mesh/material/instance/dispose regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan bağımsız terrain/vegetation/visual kalite adaylarını güncel main üzerinde yeniden sırala; başlamadan ve yayınlamadan önce eşzamanlılık kapısını uygula.\n`;
const adr = `\n\n## ADR-0191 — Rendered vegetation has a live InstancedMesh contract (run 169)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkVegetationVisualContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`createVegetation()\` fonksiyonunu iki kez aynı seed/input ile çağırır; dört InstancedMesh'ten oluşan iki tür trunk/foliage yapısını, deterministic instance matrislerini, geometry attribute sonluluğunu, MeshStandardMaterial renk/roughness/metalness imzasını, StaticDrawUsage kullanımını ve \`disposeVegetation()\` teardown davranışını fail-fast regresyon sözleşmesi olarak doğrular. Runtime kaynağı değiştirilmez.\n\n**Neden:** mevcut smoke/mobile testleri placement, LOD, culling ve mobil bütçeyi koruyor; fakat desktop render tarafında tür-pair eşleşmesi, material drift'i, instance buffer kullanımının değişmesi, non-finite geometry/transform veya dispose zincirinin bozulması ayrı bir canlı sözleşmeyle pinlenmemişti. Run 168'in sıradaki güvenli yönü vegetation/visual kalite olduğu için en düşük riskli anlamlı adım çalışan davranışı değiştirmek yerine onu otomatik korumaktır.\n\n**Alternatifler:** piksel-snapshot karşılaştırması renderer kırılganlığı taşır; kaynak regex'i gerçek Three.js nesnelerini ölçmez; vegetation runtime refactor'u çalışan sistemde gereksiz additive-only riski yaratır; hiç guard eklememek mevcut render kapsam boşluğunu açık bırakır.\n\n**Sonuç:** desktop vegetation render yapısı ve teardown zinciri CI'da canlı modül üzerinde korunur; runtime maliyeti sıfırdır. Bilinçli sanat yönü değişiklikleri ileride yeni versioned checker/ADR ile sürümlenebilir.\n\n**Etkilenen sistemler:** yeni \`scripts/checkVegetationVisualContract.js\`, run 169 CI workflow'u ve governance kayıtları. \`src/3d/world/vegetation.js\`, 2D oyun, dünya seed'i, asset seti ve PWA import grafiği değişmez.\n\n**Geri alma planı:** vegetation render sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede eder; mevcut runtime veya tarihsel guard satırlarını silmek gerekmez.\n`;
const stable = `\n- ${stableTag} — run 169 vegetation visual geometry contract (ADR-0191); ${smokeCount}/34+ browser smoke, vegetation InstancedMesh/material/disposal, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run169 governance records appended for ${stableTag}.`);
