import fs from 'node:fs';

const stamp = process.env.RUN166_STAMP;
const stableTag = process.env.RUN166_STABLE_TAG;
const perfRow = process.env.RUN166_PERF_ROW;
const smokeCount = process.env.RUN166_SMOKE_PASS_COUNT;
const mobileLayout = process.env.RUN166_MOBILE_LAYOUT;

if (!stamp || !stableTag || !perfRow || !smokeCount || !mobileLayout) {
	throw new Error('Run166 governance environment is incomplete.');
}

const progress = `\n\n## Run 166 — Mobile jump control / FAZ 4 input parity (${stamp})\n- Alt görev: FAZ 4'ün masaüstünde Space ile çalışan mevcut edge-trigger zıplaması mobil/coarse-pointer oyunculara da açıldı. Mevcut \`TouchJoystick\` kendi yaşam döngüsü içinde 64px, native-button semantiğine sahip Türkçe \`Zıpla\` düğmesi oluşturuyor; tek dokunuş tek \`consumeJumpRequested()\` edge'i üretiyor. \`game3d.js\` yalnız iki additive satırla bu edge'i mevcut \`keyboardAxes.jumpRequested\` yoluna OR ediyor; player/physics runtime sözleşmesi değiştirilmedi.\n- Additive-only: mevcut kaynak satırı silinmedi/değiştirilmedi. \`touchJoystick.js\`, \`game3d.js\`, \`controlsHelp.js\`, \`game3d.css\` ve mevcut joystick regresyonuna yalnız yeni satırlar eklendi; yeni runtime modülü olmadığı için PWA precache listesi değişmedi.\n- DoD: node --check PASS; güncellenmiş touch-joystick + keyboard + jump-arc + health + EventBus kontratları PASS; yeni gerçek-mobile jump layout/click guard PASS; checkpoint/uniqueness, world-event determinism/catalog/diversity, PWA/cache, assets/dialogue, terrain/road, mobil streaming/LOD/culling/perf ve mevcut a11y regresyonları PASS; browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; additive-only PASS.\n- Görsel doğrulama: gerçek 390x844 mobile Chromium'da yakın + F4 uzak iki screenshot artifact üretildi; \`Zıpla\` butonu iki görünümde de joystick ve yardım düğmesinden ayrı, viewport/safe-area içinde kaldı. Layout guard: ${mobileLayout}.\n- Performans: ${perfRow}\n- Memory leak checklist: yeni timer/geometry/material yok; jump click listener \`TouchJoystick.dispose()\` içinde kaldırılıyor, pending edge temizleniyor ve jump DOM'u kaldırılıyor.\n- Teknik borç: 1 (\`game3d.js\` 547/600; owner yapısal kararını bekleyen mevcut borç, bu özellik zorunlu entegrasyonu yalnız 2 additive satır büyüttü). Risk LOW. Güven 5/5.\n- ADR: ADR-0188. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; mobil oyuncu kontrol kabiliyeti +1. Oyuncu farkı: EVET — telefonda oyuncu artık sağ alttaki \`Zıpla\` düğmesiyle masaüstündeki aynı ~1.2m fizik zıplamasını yapabiliyor.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan bağımsız gameplay/core/UI kalite veya kullanıcı-değeri işi; başlamadan remote main ve paralel ajan branch'leri yeniden kontrol edilmeli.\n`;

const adr = `\n\n## ADR-0188 — Mobile jump control uses TouchJoystick-owned edge-trigger button (run 166)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** Mobil/coarse-pointer input için ayrı bir yeni global input sistemi kurmak yerine mevcut \`TouchJoystick\`, aynı container'a 64px native \`button\` olarak \`Zıpla\` kontrolünü ekler ve \`consumeJumpRequested()\` ile tek-okumalık edge-trigger verir. \`game3d.js\` bu edge'i, zaten \`player.update(..., jumpRequested)\` çağrısına giden mevcut \`keyboardAxes.jumpRequested\` boolean'ına OR eder. Masaüstü Space yolu, \`integrateJumpArc\`, player movement ve joystick eksen sözleşmesi aynen korunur.\n\n**Neden:** Repo ve \`game3d.js\` açıkça zıplamanın yalnız masaüstü klavyesinde olduğunu belgeliyordu; mobil kontrol paritesi eksikti. Zıplama fiziği run 36'dan beri mevcut ve run 165'te ayrı kontratla korunuyor, dolayısıyla mobil için yeni fizik/animasyon üretmek yerine aynı edge'i ikinci bir giriş yüzeyinden beslemek en küçük ve en az riskli davranış değişikliğidir. \`TouchJoystick\` zaten yalnız coarse-pointer cihazlarda oluşturulup dispose edildiği için butonun yaşam döngüsü ve platform gate'i için ikinci bir sahip yaratılmaz.\n\n**Alternatifler:** (1) Yeni \`TouchJumpButton\` runtime modülü + ayrı game3d import/state/dispose wiring'i — gereksiz dosya/PWA-precache yükü ve \`game3d.js\`'de daha fazla satır. (2) Sentetik Space KeyboardEvent dispatch etmek — touch UI'yi klavye implementasyon ayrıntısına bağlayan dolaylı bir coupling, reddedildi. (3) Mobil zıplamayı kapalı tutmak — masaüstü/mobil gameplay kabiliyet eşitsizliğini sürdürür. (4) \`combineAxes\` sözleşmesini jump ile genişletmek — mevcut joystick \`getAxes()\` hareket-only sözleşmesini gereksiz yere değiştirir; ayrı edge consumer daha açık.\n\n**Sonuç:** Mobil oyuncu artık native, erişilebilir ve en az 44px hedefi aşan bir butonla mevcut zıplama mekaniğini kullanır. Tek dokunuş bir kez tüketilir; basılı tutma zincir-zıplama üretmez. Masaüstü, 2D oyun, seed/determinism, dünya üretimi ve PWA import grafiği değişmez. \`game3d.js\` 545→547 satır olur; 600 tavanı aşılmaz ve yeni teknik borç sayacı açılmaz.\n\n**Etkilenen sistemler:** \`src/3d/ui/touchJoystick.js\`, \`src/3d/game3d.js\`, \`src/3d/ui/controlsHelp.js\`, \`game3d.css\`, \`scripts/checkTouchJoystickInputContract.js\`, yeni \`scripts/checkMobileJumpControl.js\`, run166 CI/governance kayıtları.\n\n**Geri alma planı:** İleride mobil jump farklı bir input katmanına taşınırsa yeni katman eski edge consumer'ı additive bir feature gate ile no-op bırakabilir; mevcut satırların silinmesi/değiştirilmesi gerekmez.\n`;

const stable = `\n- ${stableTag} — run 166 mobile jump control / FAZ 4 input parity (ADR-0188); ${smokeCount}/34+ browser smoke, real-mobile layout/click, additive-only/PWA/mobile/core-input gates PASS.\n`;

fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);

console.log(`Run166 governance records appended for ${stableTag}.`);
