#!/usr/bin/env node
/** Run208 validated-checkpoint recorder. Appends documentation only after the workflow's full DoD passes. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const required = name => { const value = process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp = required('RUN208_STAMP');
const tag = required('RUN208_STABLE_TAG');
const base = required('RUN208_BASE_SHA');
const smoke = required('RUN208_SMOKE_PASS_COUNT');
const proof = JSON.parse(required('RUN208_PROOF_JSON'));
const mobile = JSON.parse(required('RUN208_LIVE_MOBILE_JSON'));
const perf = required('RUN208_PERF_ROW');
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');
const fields = perf.split(',');
if (fields.length < 8 || fields[1] !== 'run208-rts-feedback') throw new Error(`unexpected perf row: ${perf}`);
const [, , fps, drawCalls, triangles, geometries, textures, heap] = fields;
const desktop = proof.desktopSnapshot;
const rtsMobile = proof.mobileSnapshot;
append('3D_GAME_PROGRESS.md', `\n\n## Run 208 — RTS destination-command visual feedback\n\n- **Validated:** ${stamp}; base main \`${base}\`.\n- Added a strictly additive, self-contained destination marker to \`rts.html\`: desktop right-click movement and touch Move Command now show a short gold command-cross at the issued screen position without changing the army controller, deterministic formation logic, legacy character runtime or 2D game.\n- The feedback is inline in the already-cached RTS shell, so no new runtime asset or service-worker cache dependency is introduced. It owns one DOM marker, one timeout and two canvas listeners, all disposed on \`pagehide\`.\n- Real Chromium visual proof: two desktop views plus one mobile command screenshot; console/page errors **${proof.consoleErrors}**. Desktop render during feedback: **${desktop.drawCalls} draw calls / ${desktop.triangles} triangles** (<2500/<5M). RTS mobile render: **${rtsMobile.drawCalls} draw calls / ${rtsMobile.triangles} triangles** (<500/<500000).\n- Full legacy browser smoke: **${smoke}+ PASS**; seeded/world-reference/terrain/road regressions PASS; production PWA cache/installability PASS. Existing mobile live budget: **${mobile.drawCalls} draw calls / ${mobile.triangles} triangles / ${mobile.geometries} geometries / ${mobile.textures} textures**.\n- World Coverage unchanged: desktop **96.2%**; mobile radius-4 **81 chunks / 20.25 km² (~14.7%)**. Perf snapshot: **fps ${fps}, ${drawCalls} draw calls, ${triangles} triangles, ${geometries} geometries, ${textures} textures, ${heap} MB heap**; trend guard PASS.\n- Technical debt: command feedback is intentionally screen-space and does not yet persist as a world-space formation/rally decal; that richer feedback can be added later without coupling it to the current marker. No new live-runtime architectural debt outside this isolated overlay. Risk **LOW**, confidence **5/5**.\n- **Next safe visible step (Run209):** keep the visible RTS track and improve camera/daylight readability with additive overrides or introduce richer reused guard/human silhouettes under LOD/instancing discipline, while preserving current budgets and deterministic commands.\n`);
append('DECISIONS.md', `\n\n## ADR-0227 — Keep first RTS destination feedback screen-space and isolated\n\n- **Decision:** Add destination-command feedback as an inline, screen-space DOM marker in \`rts.html\` instead of changing \`rtsGame.js\`, \`rtsArmy.js\`, world geometry, or service-worker cache lists.\n- **Why:** Run207's next safe step explicitly calls for destination/formation feedback, while the permanent additive-only rule forbids changing existing source lines. A screen-space marker gives immediate player-visible command acknowledgement on desktop and touch without touching deterministic movement or adding a cache dependency.\n- **Alternatives:** world-space Three.js decal/ring (deferred: stronger coupling to camera/raycast/world lifecycle); modify \`rtsArmy.commandMove\` to emit feedback state (rejected for this run: requires editing established runtime code); external feedback module (rejected: creates a new offline precache obligation for a tiny isolated behavior).\n- **Result:** desktop right-click and mobile Move Command both display visible short-lived command feedback; browser proof covers two desktop views and mobile, with zero console/page errors and unchanged render budgets.\n- **Affected systems:** \`rts.html\` UI overlay only, plus Run208 test/CI/documentation. Army movement, world generation, PWA shell membership, 2D and character-mode code remain unchanged.\n- **Rollback:** the additive inline module block is isolated and can be removed only in a future owner-approved non-additive cleanup; leaving it disabled is not necessary because it has no gameplay-state ownership.\n- **Future-phase impact:** a later world-space rally/formation visualization can coexist with or supersede this acknowledgement layer without changing command determinism.\n- **Risk:** LOW.\n`);
append('STABLE_TAGS.md', `\n- \`${tag}\` — Run208 RTS destination-command feedback; desktop+mobile visual proof, ${smoke}+ legacy smoke, PWA/perf/additive/concurrency gates PASS.\n`);
console.log(`[recordRun208RtsCommandFeedback] appended Run208 progress, ADR-0227 and stable checkpoint ${tag}`);
