#!/usr/bin/env node
/** Run206 validated-checkpoint recorder. Appends documentation only after the workflow's full DoD passes. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const required = name => { const value = process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp = required('RUN206_STAMP');
const tag = required('RUN206_STABLE_TAG');
const base = required('RUN206_BASE_SHA');
const smoke = required('RUN206_SMOKE_PASS_COUNT');
const proof = JSON.parse(required('RUN206_PROOF_JSON'));
const mobile = JSON.parse(required('RUN206_LIVE_MOBILE_JSON'));
const perf = required('RUN206_PERF_ROW');
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');
const fields = perf.split(',');
if (fields.length < 8 || fields[1] !== 'run206') throw new Error(`unexpected perf row: ${perf}`);
const [, , fps, drawCalls, triangles, geometries, textures, heap] = fields;
append('3D_GAME_PROGRESS.md', `\n\n## Run 206 — Developer/production service-worker ownership boundary proof\n\n- **Validated:** ${stamp}; base main \`${base}\`.\n- Added only a browser proof + CI/recorder; production/default runtime, 2D game, manifests and service workers remain byte-unchanged.\n- Real Chromium proves the production service worker stays rooted at \`${proof.productionScope}\`, the developer standalone worker stays narrowed to \`${proof.developerScope}\`, and opening either Current or Canonical from the developer shell is controlled by the production worker rather than the developer worker.\n- Returning to the developer shell restores the narrow developer controller; offline shell reload and offline Canonical recovery both succeed without controller capture, runtime-canvas leakage or console/page errors. Deterministic bridge remains \`${proof.deterministicBridge}\`.\n- Full browser smoke: **${smoke}+ PASS**; Run195-205 canonical regressions PASS; production PWA cache/installability PASS.\n- Mobile live budget: **${mobile.drawCalls} draw calls / ${mobile.triangles} triangles / ${mobile.geometries} geometries / ${mobile.textures} textures**, within <500/<500000. Coverage unchanged: desktop **96.2%**; mobile radius-4 **81 chunks / 20.25 km² (~14.7%)**.\n- Perf snapshot: **fps ${fps}, ${drawCalls} draw calls, ${triangles} triangles, ${geometries} geometries, ${textures} textures, ${heap} MB heap**; trend guard PASS.\n- Technical debt: **no new live-runtime debt**. Risk **LOW**, confidence **5/5**.\n- **Next safe step (Run207):** keep production startup unchanged and prove repeated offline Current/Canonical round-trips cannot accumulate service-worker registrations, caches, clients, timers/listeners or canvases across multiple navigation cycles.\n`);
append('DECISIONS.md', `\n\n## ADR-0225 — Preserve service-worker ownership by URL scope across developer runtime launches\n\n- **Decision:** Keep the Run205 developer worker confined to \`/canonical-dev-pwa/\`; Current/Canonical runtime documents remain outside that scope and therefore stay under the existing production root service worker. Add a real Chromium ownership regression proof rather than changing runtime/service-worker code.\n- **Why:** A nested developer PWA is safe only if its narrower worker cannot capture root runtime documents or replace the production registration during online/offline navigation.\n- **Alternatives:** widen the developer worker scope (rejected: risks production capture); move runtime documents under the developer subtree (rejected: changes ownership/navigation semantics); alter the root service worker (rejected: unnecessary live-PWA risk).\n- **Result:** production registration remains present at scope \`/\`; developer registration remains at \`/canonical-dev-pwa/\`; Current/Canonical use the production controller, shell uses the developer controller, and offline recovery preserves the same separation with zero console/page errors.\n- **Affected systems:** CI/test/documentation only. Production service worker/manifest, developer service worker/manifest, 2D, default 3D and live gameplay/world code unchanged.\n- **Rollback:** Run206 files are inert unless executed by CI and may be removed only in a future owner-approved non-additive cleanup.\n- **Risk:** LOW.\n`);
append('STABLE_TAGS.md', `\n- \`${tag}\` — Run206 service-worker ownership boundary proof; ${smoke}+ smoke PASS, canonical/PWA/mobile/perf/additive/concurrency gates PASS; live/default runtime delta 0.\n`);
console.log(`[recordRun206ServiceWorkerOwnership] appended Run206 progress, ADR-0225 and stable checkpoint ${tag}`);