import fs from 'node:fs';

const stamp = process.env.RUN168_STAMP;
const stableTag = process.env.RUN168_STABLE_TAG;
const perfRow = process.env.RUN168_PERF_ROW;
const smokeCount = process.env.RUN168_SMOKE_PASS_COUNT;
const roadContractSummary = process.env.RUN168_ROAD_CONTRACT_SUMMARY || 'live road ribbon geometry/material/disposal contract PASS';

if (!stamp || !stableTag || !perfRow || !smokeCount) {
  throw new Error('Run168 governance environment is incomplete.');
}

const progress = `\n\n## Run 168 — Road visual geometry regression contract (${stamp})\n- Alt görev: run 167'nin sıradaki güvenli terrain/road/visual kalite yönüne uygun olarak, gerçek \`buildRoadNetwork()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkRoadVisualContract.js\` eklendi. Kontrat yol ağının tek merged mesh olarak kalmasını, ribbon topolojisini, 8m genişliği, 0.4m terrain lift'ini, dirt vertex color/material ayarlarını, finite normal/index verisini ve geometry/material disposal zincirini doğruluyor.\n- Kapsam ayrımı: mevcut \`roadNetworkSafetyCheck.js\` topology/eğim/dağdan kaçınma/nehir güvenliğini korumaya devam ediyor; yeni guard yalnız rendered-road görsel geometri sözleşmesini kapatıyor. Runtime, 2D oyun, dünya üretimi ve mevcut yol kodu değiştirilmedi.\n- Additive-only: yalnız yeni checker, yeni run workflow'u ve yeni governance recorder eklendi; mevcut kaynak satırı silinmedi/değiştirilmedi. Nihai source diff 0 deletion.\n- DoD: node --check PASS; ${roadContractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; seeded-random/world-event determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat, road-network, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: gerçek 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; yeni iş runtime görselini değiştirmediği için bu kanıt regresyon/no-delta doğrulamasıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; ayrıca yeni kontrat \`disposeRoadNetwork()\` çağrısında road geometry ve material için birer \`dispose\` olayı bekleyerek mevcut teardown sözleşmesini canlı doğruluyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu; run 168 yeni runtime borcu eklemedi). Risk LOW. Güven 5/5.\n- ADR: ADR-0190. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: yol km 0; orman km² 0; kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; road visual regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak yol genişliği/z-fighting/material/draw-call ve teardown regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan bağımsız terrain/vegetation/visual kalite adaylarını güncel main üzerinde yeniden sırala; başlamadan ve yayınlamadan önce eşzamanlılık kapısını yine uygula.\n`;

const adr = `\n\n## ADR-0190 — Rendered road ribbon has a live visual geometry contract (run 168)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkRoadVisualContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`buildRoadNetwork()\` fonksiyonunu çağırır ve rendered road ağının tek merged mesh/topoloji, 8m ribbon genişliği, terrain üzerinde 0.4m lift, dirt vertex-color + MeshStandardMaterial özellikleri, finite normal/index verisi ve \`disposeRoadNetwork()\` teardown davranışını fail-fast bir regresyon sözleşmesi olarak doğrular. Mevcut runtime kaynağı değiştirilmez.\n\n**Neden:** \`roadNetworkSafetyCheck.js\` yolun nereye gittiğini ve dünya güvenliğini güçlü biçimde doğruluyor; ancak görsel mesh'in yanlışlıkla daralması/genişlemesi, terrain içine gömülmesiyle z-fighting üretmesi, birleşik tek draw-call yapısının parçalanması, material özelliğinin kayması veya dispose zincirinin bozulması aynı safety testinden kaçabilir. Run 167'nin sıradaki güvenli yönü bağımsız terrain/road/visual kalite olduğu için en düşük riskli anlamlı adım mevcut çalışan davranışı değiştirmek yerine bu görünür sözleşmeyi otomatik korumaktır.\n\n**Alternatifler:** (1) Yalnız ekran görüntüsü karşılaştırması — headless renderer/piksel farklarına kırılgan ve geometry nedenini izole etmiyor. (2) \`roads.js\` kaynak metnini regex ile taramak — uygulama detayına bağımlı, gerçek render çıktısını ölçmüyor. (3) Yol runtime'ını refactor edip sabitleri export etmek — mevcut davranışta arıza yokken gereksiz kapsam ve additive-only riski. (4) Hiç guard eklememek — mevcut world-safety testinin görsel geometri boşluğunu açık bırakıyor.\n\n**Sonuç:** Yol renderer'ının kullanıcıya görünen temel geometrisi, tek-mesh bütçesi ve teardown davranışı CI'da canlı modül üzerinde korunur; runtime maliyeti sıfırdır. İleride bilinçli bir yol sanat yönü değişikliği yapılırsa yeni değerler yeni additive test/ADR ile açıkça sürümlenir.\n\n**Etkilenen sistemler:** yeni \`scripts/checkRoadVisualContract.js\`, yeni run 168 CI workflow'u ve governance kayıtları. \`src/3d/world/roads.js\`, 2D oyun, PWA runtime/import grafiği, dünya seed'i ve asset seti değişmez.\n\n**Geri alma planı:** Yol renderer sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede edebilir; mevcut kaynak veya tarihsel guard satırlarını silmek gerekmez.\n`;

const stable = `\n- ${stableTag} — run 168 road visual geometry contract (ADR-0190); ${smokeCount}/34+ browser smoke, road ribbon geometry/material/disposal, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;

fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);

console.log(`Run168 governance records appended for ${stableTag}.`);
