import fs from 'node:fs';

const stamp = process.env.RUN175_STAMP;
const stableTag = process.env.RUN175_STABLE_TAG;
const perfRow = process.env.RUN175_PERF_ROW;
const smokeCount = process.env.RUN175_SMOKE_PASS_COUNT;
const contractSummary = process.env.RUN175_STARFIELD_CONTRACT_SUMMARY || 'live starfield visual contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run175 governance environment is incomplete.');

const progress = `\n\n## Run 175 — Starfield visual/shader regression contract (${stamp})\n- Alt görev: gerçek \`createStarfield()\` / \`updateStarfield()\` / \`disposeStarfield()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkStarfieldVisualContract.js\` eklendi. Kontrat 1200 yıldızlı deterministik THREE.Points dome geometrisini, 1850m radius + horizon-height sınırını, phase/frequency buffer'larını, sabit 2.2px ShaderMaterial/color/depth/fog/render-order imzasını, same-seed bit-identical davranışı, farklı-seed ayrışmasını, kamera takip + time/night uniform güncellemesini ve geometry/material teardown zincirini doğruluyor.\n- Runtime/2D/PWA davranışı değiştirilmedi; \`src/3d/stars.js\`, owner playtest'i bekleyen twinkle hız/genlik sabitleri, lighting/sky/fog/water/terrain, mobil radius/LOD ve owner kalibrasyon değerlerine dokunulmadı. Owner kararı bekleyen radius-5, game3d.js yapısal borcu ve world-event checksum maddeleri aynen bırakıldı.\n- Additive-only: yayınlanan dal yalnız yeni checker, yeni run workflow'u ve yeni governance recorder ekledi; mevcut source satırı silinmedi/değiştirilmedi.\n- DoD: node --check PASS; ${contractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat/terrain-visual, road-network/road-visual, vegetation-visual, water-visual, sky-visual, fog-visual, lighting-visual, starfield-visual, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; runtime görseli değişmediği için no-delta regresyon kanıtıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; checker \`disposeStarfield()\` için geometry + material üzerinde birer gerçek dispose olayı doğruluyor ve testte oluşturduğu üç starfield instance'ını temizliyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 175 yeni runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0197. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: stars/lighting/fog/sky/water/terrain/yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; starfield visual regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak yıldız dome dağılımı, shader/material, deterministik twinkle buffer'ları, kamera takibi ve teardown regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan camera/free-camera veya scene/render lifecycle gibi kalan bağımsız kontrat boşluklarını güncel main üzerinde yeniden sırala; başlamadan ve yayınlamadan önce eşzamanlılık kapısını uygula.\n`;
const adr = `\n\n## ADR-0197 — Starfield has a live deterministic Points-dome/shader/update contract (run 175)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkStarfieldVisualContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`createStarfield()\` / \`updateStarfield()\` / \`disposeStarfield()\` fonksiyonlarını çağırır; 1200 yıldızlı BufferGeometry/Points yapısını, tüm yıldızların ~1850m upper-dome yarıçapını ve en az 0.05 height-factor sınırını, aPhase/aFreq attribute şekil ve aralıklarını, same-seed position/phase/frequency buffer'larının bit-identical olmasını, farklı seed'in ayrışmasını, ShaderMaterial transparent/depthWrite/fog + fixed-size/color + shader-output imzasını, frustum/render-order politikasını, camera-follow + uTime/uNightFactor güncellemelerini ve geometry/material dispose olaylarını fail-fast regresyon sözleşmesi olarak doğrular. Runtime kaynağı değiştirilmez.\n\n**Neden:** mevcut smoke check star twinkle'ın seeded phase/frequency ve update uniform davranışını koruyor, fakat rendered THREE.Points dome'unun star count/radius/horizon sınırı, material/render-order/fixed-size imzası, position determinism'i ve teardown'u tek açıklayıcı canlı render kontratında pinlemiyor. Run 172-174 sky/fog/lighting atmosfer zincirinden sonra starfield aynı katmandaki kalan düşük-riskli render boşluğudur.\n\n**Alternatifler:** piksel snapshot GPU/headless farklarına kırılgandır; yalnız kaynak regex'i BufferGeometry/ShaderMaterial gerçek nesnelerini ve dispose zincirini ölçmez; mevcut smoke testini büyütmek dolu smoke registry'sine gereksiz kapsam ekler; çalışan \`stars.js\` runtime'ını refactor etmek additive-only altında gereksiz risk taşır.\n\n**Sonuç:** yıldız dome topolojisi, deterministik dağılım/twinkle buffer'ları, görünüm material/shader sözleşmesi, kamera takip güncellemesi ve teardown davranışı CI'da canlı modül üzerinde korunur; runtime maliyeti sıfırdır. Owner'ın run 87 playtest sorusundaki twinkle tuning değerleri yalnız mevcut davranış olarak test edilir, yeniden kalibre edilmez.\n\n**Etkilenen sistemler:** yeni \`scripts/checkStarfieldVisualContract.js\`, run 175 CI workflow'u ve governance kayıtları. \`src/3d/stars.js\`, 2D oyun, lighting/sky/fog/water/terrain runtime'ı, world seed, mobil streaming/LOD, asset seti ve PWA import grafiği değişmez.\n\n**Geri alma planı:** starfield sanat/shader/twinkle sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede eder; mevcut runtime veya tarihsel guard satırlarını silmek gerekmez.\n`;
const stable = `\n- ${stableTag} — run 175 starfield visual contract (ADR-0197); ${smokeCount}/34+ browser smoke, star Points/shader/update/disposal, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run175 governance records appended for ${stableTag}.`);
