#!/usr/bin/env node
/** Run209 validated-checkpoint recorder. Appends documentation only after the workflow's full DoD passes. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const required = name => { const value = process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp = required('RUN209_STAMP');
const tag = required('RUN209_STABLE_TAG');
const base = required('RUN209_BASE_SHA');
const smoke = required('RUN209_SMOKE_PASS_COUNT');
const proof = JSON.parse(required('RUN209_PROOF_JSON'));
const mobile = JSON.parse(required('RUN209_LIVE_MOBILE_JSON'));
const perf = required('RUN209_PERF_ROW');
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');
const fields = perf.split(',');
if (fields.length < 8 || fields[1] !== 'run209-rts-selection-readability') throw new Error(`unexpected perf row: ${perf}`);
const [, , fps, drawCalls, triangles, geometries, textures, heap] = fields;
const desktop = proof.desktopSnapshot;
const rtsMobile = proof.mobileSnapshot;
append('3D_GAME_PROGRESS.md', `\n\n## Run 209 — RTS selection readability HUD\n\n- **Validated:** ${stamp}; base main \`${base}\`.\n- Added a strictly additive, DOM-only \`Komuta Hazırlığı\` meter to \`rts.html\`. It mirrors the existing selection count through a \`MutationObserver\`, so no new gameplay state, movement rule or deterministic path is introduced.\n- Desktop browser proof covers all-selected and none-selected states; mobile proof covers the touch/coarse-pointer layout. Console/page errors **${proof.consoleErrors}**. Desktop render: **${desktop.drawCalls} draw calls / ${desktop.triangles} triangles**. RTS mobile: **${rtsMobile.drawCalls} draw calls / ${rtsMobile.triangles} triangles**.\n- Full legacy browser smoke: **${smoke}+ PASS**; seeded/world-reference/terrain/road regressions PASS; production PWA cache/installability PASS. Existing mobile live budget: **${mobile.drawCalls} draw calls / ${mobile.triangles} triangles / ${mobile.geometries} geometries / ${mobile.textures} textures**.\n- World Coverage unchanged: desktop **96.2%**; mobile radius-4 **81 chunks / 20.25 km² (~14.7%)**. Perf snapshot: **fps ${fps}, ${drawCalls} draw calls, ${triangles} triangles, ${geometries} geometries, ${textures} textures, ${heap} MB heap**; trend guard PASS.\n- Memory-leak checklist: one MutationObserver + one DOM node; observer disconnects and node is removed on \`pagehide\`. No timers, geometry, material or persistent renderer resource added.\n- Technical debt: meter derives selection totals from the already-rendered HUD text rather than a dedicated event API; acceptable for this isolated additive-only layer, but a future owner-approved refactor could expose selection events directly. Risk **LOW**, confidence **5/5**.\n- **Next safe visible step (Run210):** improve RTS camera/daylight readability with an additive presentation layer, or add world-space formation/rally visualization without changing command determinism.\n`);
append('DECISIONS.md', `\n\n## ADR-0228 — Mirror RTS selection state from the existing HUD instead of changing the army API\n\n- **Decision:** Add the Run209 selection-readability meter as an inline DOM layer that observes \`#rts-selection-count\`, rather than editing \`rtsArmy.js\` or \`rtsGame.js\`.\n- **Why:** the permanent additive-only guard forbids modifying established source lines, while the visible RTS surface benefits from stronger selection feedback on desktop and mobile. The existing HUD text is already the authoritative rendered selection count.\n- **Alternatives:** expose a new selection event from the army/controller (rejected for this run because it requires modifying established runtime code); create a new external runtime module (rejected because the tiny feature would add an unnecessary offline-cache dependency); infer selection from scene colors (rejected as brittle and rendering-coupled).\n- **Result:** a visible percentage meter stays synchronized through select-all, clear-selection and normal selection HUD updates, with zero new gameplay state and zero Three.js draw calls.\n- **Affected systems:** \`rts.html\` UI only, plus Run209 test/CI/documentation. 2D, character mode, army movement, world generation and PWA cache lists remain unchanged.\n- **Rollback:** the isolated additive module can be disabled by a future owner-approved cleanup; no persisted state migration is required.\n- **Future-phase impact:** a later event-driven command UI can replace the observation adapter without changing army behavior or saved data.\n- **Risk:** LOW.\n`);
append('STABLE_TAGS.md', `\n- \`${tag}\` — Run209 RTS selection-readability HUD; desktop/mobile visual proof, ${smoke}+ legacy smoke, PWA/perf/additive/concurrency gates PASS.\n`);
console.log(`[recordRun209RtsSelectionReadability] appended Run209 progress, ADR-0228 and stable checkpoint ${tag}`);
