import fs from 'node:fs';

const stamp = process.env.RUN177_STAMP;
const stableTag = process.env.RUN177_STABLE_TAG;
const perfRow = process.env.RUN177_PERF_ROW;
const smokeCount = process.env.RUN177_SMOKE_PASS_COUNT;
const roadSummary = process.env.RUN177_ROAD_SUMMARY || 'medieval road surface contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run177 governance environment is incomplete.');

const progress = `\n\n## Run 177 — Owner world-art directive + medieval road surface (${stamp})\n- Owner direktifi kalıcılaştırıldı: \`GOVERNANCE.md\` sonuna §30 Fiziksel Dünya / Sanat Yönü append edildi. Ortaçağ yol ağı, deterministik çimen+rüzgâr, taş/kaya/dağ, büyük mağaralar, vahşi ejderha habitatları ve Dragonstone altında eğitimli ejderha mağarası artık owner-onaylı ürün hedefleridir; her biri ayrı DoD/ADR ile uygulanacaktır.\n- İlk fiziksel-görsel alt görev: mevcut 14/14 kingdom-seat slope-aware MST yol topolojisi ve 8m ribbon geometrisi bozulmadan yol yüzeyi ortaçağ toprak/at-arabası karakterine yükseltildi. Additive wrapper mevcut tek road meshine \`roadSide\` attribute'u ve deterministik shader katmanı ekler: iki teker izi, aşınmış omuz, merkez crown, yerel çamur patch'i ve seyrek taş varyasyonu. Yeni texture/asset/mesh yoktur.\n- ${roadSummary}\n- Additive-only: mevcut source satırı silinmedi/değiştirilmedi; \`src/3d/world/roads.js\` ve \`GOVERNANCE.md\` yalnız sona append edildi. Eski road topology/geometry/material sözleşmesi yaşamaya devam eder.\n- DoD: node --check PASS; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; road-network safety + eski road-visual + yeni medieval-road surface, determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain/vegetation/water/sky/fog/lighting/starfield/camera, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: gerçek 390x844 mobile Chromium yakın + F4 uzak iki screenshot artifact üretildi; shader gerçek oyun render yolunda compile edildi, console/page error 0.\n- Performans: ${perfRow}\n- Memory leak checklist: yeni runtime listener/timer/DOM/texture/geometry/material/mesh oluşturulmadı; yalnız mevcut road geometry'ye tek Float32 attribute ve mevcut material'e shader hook eklendi. Road teardown mevcut geometry/material dispose zincirini korur.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 177 yeni yapısal runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0199. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: yol uzunluğu 0 km (topoloji aynı 20.24 km), road visual quality +1, governance world-art directive +1; orman/terrain/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1. Oyuncu farkı: EVET — mevcut yollar artık düz tek-renk ribbon yerine teker izli, çamurlu/taşlı, aşınmış ortaçağ toprak yolu olarak render edilir.\n- Sıradaki güvenli adım: §30 sırasına göre deterministik instanced çimen + GPU rüzgâr salınımı; yol/su/kale exclusion, mobile LOD/culling ve yakın+uzak görsel kanıt zorunlu.\n`;

const adr = `\n\n## ADR-0199 — Medieval road realism is a zero-extra-mesh procedural surface layer (run 177)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** Owner'ın fiziksel dünya talebi \`GOVERNANCE.md\` §30 olarak kalıcılaştırılır. İlk uygulama olarak mevcut \`buildRoadNetwork()\` topolojisi/geometrisi değiştirilmez; run-177 additive wrapper gerçek tek merged road meshine bir \`roadSide\` vertex attribute ekler ve mevcut \`MeshStandardMaterial.onBeforeCompile\` yoluyla deterministic fragment variation uygular. İki normalize teker izi, merkez crown, shoulder wear, düşük frekanslı çamur patch'i ve seyrek taş tonu dünya/road pozisyonundan saf hash ile üretilir. Texture, ikinci mesh veya ek draw call yoktur; 14 koltuğun 13-edge slope-aware MST bağlantısı aynen kalır.\n\n**Neden:** Kullanıcı görünür fiziksel kaliteyi artık öncelik yaptı. Mevcut yol ağı topolojik olarak zaten tamam ve safety guard'ları güçlü; onu yeniden kurmak gereksiz regresyon riski. Buna karşılık tek-renk dirt ribbon ortaçağ yol hissini vermiyor. Aynı mesh/material üzerinde procedural yüzey, Game-of-Thrones-esintili aşınmış cart-road görünümünü hemen artırırken mobil draw-call/triangle bütçesini değiştirmiyor ve additive-only kuralına uyuyor.\n\n**Alternatifler:** (1) Yeni PBR yol texture seti: daha yüksek sanat kalitesi mümkün ama yeni asset/lisans/cache/texture-memory maliyeti getirir; ilk adım için gereksiz. (2) Yol kenarına ayrı taş/çimen meshleri: daha güçlü silhouette fakat draw-call/triangle ve dispose kapsamını büyütür; çimen/kaya zaten §30'da ayrı alt görev. (3) 13 yolu ayrı mesh yapmak: materyal çeşitliliği kolaylaşır ama mevcut tek-draw-call kontratını gereksiz bozar. (4) Topolojiyi complete graph'a çevirmek: gerçekçi değil, 91 bağlantı üretir ve mevcut slope-aware MST'nin amaçladığı okunabilir yol ağını bozar.\n\n**Sonuç:** 20.24 km mevcut yol ağının ulaşılabilirliği, genişliği, terrain lift'i ve safety davranışı korunurken görünen yüzey deterministic teker izi/çamur/taş/aşınma detayına kavuşur. Runtime'a yeni asset yükleme veya ek draw-call yoktur. Gelecek çimen/kaya görevleri yol çevresini ayrıca fiziksel olarak zenginleştirebilir.\n\n**Etkilenen sistemler:** \`GOVERNANCE.md\` §30, additive append ile \`src/3d/world/roads.js\`, yeni \`scripts/checkMedievalRoadSurface.js\`, run177 applicator/CI ve governance kayıtları. 2D oyun, road pathfinder/topology, terrain height sampler, settlement coordinates, PWA import grafiği, world seed ve dragon AI değişmez.\n\n**Geri alma planı:** Bilinçli yeni yol sanat yönü gelirse yeni versioned additive surface wrapper/ADR mevcut run177 katmanını supersede edebilir. Topoloji değişimi ayrı alt görevdir; eski road safety/visual guard'ları sessizce gevşetilmez.\n`;

const stable = `\n- ${stableTag} — run 177 owner world-art §30 + medieval road surface (ADR-0199); ${smokeCount}/34+ browser smoke, road safety/visual/surface + PWA/determinism/mobile gates PASS.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run177 governance records appended for ${stableTag}.`);
