import fs from 'node:fs';

const stamp = process.env.RUN172_STAMP;
const stableTag = process.env.RUN172_STABLE_TAG;
const perfRow = process.env.RUN172_PERF_ROW;
const smokeCount = process.env.RUN172_SMOKE_PASS_COUNT;
const contractSummary = process.env.RUN172_SKY_CONTRACT_SUMMARY || 'live sky render contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run172 governance environment is incomplete.');

const progress = `\n\n## Run 172 — Aurora sky visual/shader regression contract (${stamp})\n- Alt görev: gerçek \`createAuroraSky()\` / \`updateAuroraSky()\` / \`disposeAuroraSky()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkSkyVisualContract.js\` eklendi. Kontrat 1900m sky sphere topolojisini, BackSide/depth/fog/render-order imzasını, procedural aurora shader/uniform paletini, day/night gradient aktarımını, kamera takip güncellemesini, Three.js pole UV seam padding davranışını, deterministik geometry buffer'larını ve teardown zincirini doğruluyor.\n- İlk unmerged denemede test UV'yi hatalı biçimde yalnız [0,1] kabul ederek Three.js SphereGeometry'nin kutup seam düzeltmesini false-positive saydı; runtime değişmedi. İkinci temiz dal gerçek 32-segment yarım-texel pole padding'ini (±0.015625) ölçerek bu test varsayımını düzeltti.\n- Runtime/2D/PWA davranışı değiştirilmedi; sky shader, day/night sabitleri, fog, terrain, mobil radius/LOD ve owner kalibrasyon değerlerine dokunulmadı. Owner kararı bekleyen radius-5, game3d.js yapısal borcu ve world-event checksum maddeleri aynen bırakıldı.\n- Additive-only: yayınlanan dal yalnız yeni checker, yeni run workflow'u ve yeni governance recorder ekledi; mevcut source satırı silinmedi/değiştirilmedi.\n- DoD: node --check PASS; ${contractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat/terrain-visual, road-network/road-visual, vegetation-visual, water-visual, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; runtime görseli değişmediği için no-delta regresyon kanıtıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; checker \`disposeAuroraSky()\` için 1 geometry + 1 material dispose olayını canlı doğruluyor ve testte oluşturduğu iki sky meshini temizliyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 172 yeni runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0194. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: sky/water/terrain/yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; sky visual regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak gökyüzü sphere çözünürlüğü, shader/palet, day-night güncellemesi ve teardown regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan bağımsız world/render kalite adaylarını güncel main üzerinde yeniden sırala; fog/lighting gibi kalan sistemler mevcut smoke kapsamına göre tekrar değerlendirilir.\n`;
const adr = `\n\n## ADR-0194 — Rendered aurora sky has a live sphere/shader/update contract (run 172)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkSkyVisualContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`createAuroraSky()\` fonksiyonunu iki kez çağırır; 1900m radius / 32x16 segment SphereGeometry'nin 561 vertex / 2880 index topolojisini, finite unit normals, standart V aralığını ve Three.js'in kutup seam'i için uyguladığı yarım-segment U padding'ini (0.5/32 = 0.015625), BackSide ShaderMaterial / depthWrite=false / fog=false imzasını, frustum-culling kapalı + renderOrder=-1 kamera-surround davranışını, dusk horizon/zenith + aurora renkleri + time/night uniformlarını, procedural hash/value-noise ve night-masked aurora shader imzasını, deterministik geometry buffer'larını, \`updateAuroraSky()\` kamera kopyalama + zaman + day/night gradient aktarımını ve \`disposeAuroraSky()\` teardown olaylarını fail-fast regresyon sözleşmesi olarak doğrular. Runtime kaynağı değiştirilmez.\n\n**Neden:** mevcut full smoke sky'ı dolaylı render ediyor; sphere çözünürlüğü/radius'u, inside-render material yönü, day/night uniform aktarımı, aurora shader imzası veya dispose zinciri drift ederse açıklayıcı sistem-seviyesi kontrat yok. İlk test denemesi UV'yi yalnız [0,1] kabul ederek Three.js'in pole seam UV offset'ini yanlışlıkla hata saydı; runtime yerine test varsayımının düzeltilmesi gerektiği logla doğrulandı ve başarısız dal merge edilmedi.\n\n**Alternatifler:** piksel snapshot GPU farklarına kırılgandır; yalnız shader regex'i geometry/update/dispose zincirini ölçmez; çalışan sky runtime'ını refactor etmek gereksiz additive-only riski taşır; yanlış UV beklentisini zorlamak gerçek SphereGeometry davranışını test etmek yerine implementasyona ters bir sözleşme yaratır.\n\n**Sonuç:** sky sphere topolojisi, gerçek pole UV seam davranışı, inside-render material ayarları, procedural aurora görünüm sözleşmesi, day/night + camera-follow update'i ve teardown davranışı CI'da canlı modül üzerinde korunur; runtime maliyeti sıfırdır.\n\n**Etkilenen sistemler:** yeni \`scripts/checkSkyVisualContract.js\`, run 172 CI workflow'u ve governance kayıtları. \`src/3d/sky.js\`, 2D oyun, lighting/fog runtime'ı, terrain/world seed, mobil streaming/LOD, asset seti ve PWA import grafiği değişmez.\n\n**Geri alma planı:** sky render sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede eder; mevcut runtime veya tarihsel guard satırlarını silmek gerekmez.\n`;
const stable = `\n- ${stableTag} — run 172 aurora sky visual sphere/shader/update contract (ADR-0194); ${smokeCount}/34+ browser smoke, sky render/disposal, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run172 governance records appended for ${stableTag}.`);
