import fs from 'node:fs';

const stamp = process.env.RUN171_STAMP;
const stableTag = process.env.RUN171_STABLE_TAG;
const perfRow = process.env.RUN171_PERF_ROW;
const smokeCount = process.env.RUN171_SMOKE_PASS_COUNT;
const contractSummary = process.env.RUN171_WATER_CONTRACT_SUMMARY || 'live water render contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run171 governance environment is incomplete.');

const progress = `\n\n## Run 171 — Water visual/shader regression contract (${stamp})\n- Alt görev: run 170 sonrası owner bloklarına girmeden world/visual kalite dizisini sürdürmek için gerçek \`createWater()\` / \`updateWater()\` / \`disposeWater()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkWaterVisualContract.js\` eklendi. Kontrat tek düz su meshinin 4000m PlaneGeometry topolojisini, ShaderMaterial/fog/uniform imzasını, fragment-only ripple sözleşmesini, kamera takip güncellemesini, deterministik geometry buffer'larını ve teardown zincirini doğruluyor.\n- Runtime/2D/PWA davranışı değiştirilmedi; su seviyesi, shader kaynakları, terrain, mobil radius/LOD ve owner kalibrasyon sabitlerine dokunulmadı. Owner kararı bekleyen radius-5, game3d.js yapısal borcu ve world-event checksum maddeleri aynen bırakıldı.\n- Additive-only: yalnız yeni checker, yeni run workflow'u ve yeni governance recorder eklendi; mevcut source satırı silinmedi/değiştirilmedi.\n- DoD: node --check PASS; ${contractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat/terrain-visual, road-network/road-visual, vegetation-visual, water-static-shader, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; runtime görseli değişmediği için no-delta regresyon kanıtıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; yeni checker \`disposeWater()\` için 1 geometry + 1 material dispose olayını canlı doğruluyor ve testte oluşturduğu iki water meshini temizliyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 171 yeni runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0193. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: water/terrain/yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; water visual regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak su mesh çözünürlüğü, fog/shader imzası, kamera-follow ve teardown regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan bağımsız world/render kalite adaylarını güncel main üzerinde yeniden sırala; başlamadan ve yayınlamadan önce eşzamanlılık kapısını uygula.\n`;
const adr = `\n\n## ADR-0193 — Rendered water has a live plane/shader/update contract (run 171)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkWaterVisualContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`createWater()\` fonksiyonunu iki kez çağırır; 4000m x 4000m / 128x128 segment düz PlaneGeometry'nin 16641 vertex / 98304 index topolojisini, yukarı bakan finite normal ve UV aralığını, ShaderMaterial transparent/depthWrite/fog imzasını, shallow/deep color + sun/camera/time ve fog uniformlarını, vertex aşamasında zaman/trigonometri bulunmaması invariantını, fragment-only ripple/fog/output imzasını, aynı girdide deterministik geometry buffer'larını, \`updateWater()\` kamera-XZ + zaman + kamera-uniform kopyalama davranışını ve \`disposeWater()\` teardown olaylarını fail-fast regresyon sözleşmesi olarak doğrular. Runtime kaynağı değiştirilmez.\n\n**Neden:** mevcut smoke suite ADR-0048'i korumak için yalnız water vertex shader'ında \`uTime\`/\`sin\`/\`cos\` bulunmamasını doğruluyor; bu çok önemli ama su düzleminin topolojisi, material/fog/uniform sözleşmesi, fragment ripple yolu, camera-follow update'i veya dispose zinciri drift ederse aynı test bunu yakalamaz. Run 168-170 road/vegetation/terrain render boşluklarını canlı kontratlarla kapattığı için aynı dünya-render katmanının su tarafını runtime değişikliği yapmadan güvenceye almak düşük riskli ve anlamlı devam adımıdır.\n\n**Alternatifler:** piksel snapshot karşılaştırması headless/GPU farklarına kırılgandır; yalnız shader-source regex'i geometry/update/dispose zincirini ölçmez; mevcut smoke check'i büyütmek dolu smoke modüllerinde gereksiz satır-bütçesi baskısı yaratır; çalışan water runtime'ını refactor etmek additive-only altında gereksiz risk taşır.\n\n**Sonuç:** water plane topolojisi, düz-yüzey invariantı, fog/shader görünüm sözleşmesi, camera-follow update'i ve teardown davranışı CI'da canlı modül üzerinde korunur; runtime maliyeti sıfırdır. Bilinçli su sanat/shader değişiklikleri ileride yeni versioned checker/ADR ile açıkça sürümlenir.\n\n**Etkilenen sistemler:** yeni \`scripts/checkWaterVisualContract.js\`, run 171 CI workflow'u ve governance kayıtları. \`src/3d/world/water.js\`, 2D oyun, terrain/world seed, mobil streaming/LOD, asset seti ve PWA import grafiği değişmez.\n\n**Geri alma planı:** water render sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede eder; mevcut runtime veya tarihsel guard satırlarını silmek gerekmez.\n`;
const stable = `\n- ${stableTag} — run 171 water visual plane/shader/update contract (ADR-0193); ${smokeCount}/34+ browser smoke, water render/disposal, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run171 governance records appended for ${stableTag}.`);
