#!/usr/bin/env node
/** Run200: append validated progress/ADR/stable records after every DoD gate passes. */
const fs=require('fs'); const path=require('path'); const ROOT=path.resolve(__dirname,'..');
const req=(name)=>{const v=process.env[name]; if(!v) throw new Error(`${name} is required`); return v;};
const stamp=req('RUN200_STAMP'), tag=req('RUN200_STABLE_TAG'), summary=req('RUN200_SUMMARY'), smoke=req('RUN200_SMOKE_PASS_COUNT'), mobile=req('RUN200_LIVE_MOBILE_JSON'), perf=req('RUN200_PERF_ROW');
fs.appendFileSync(path.join(ROOT,'3D_GAME_PROGRESS.md'),`\n\n## Run 200 — Opt-in canonical developer startup + production-SW offline rollback equivalence\n\n- **Validated:** ${stamp}. Added dormant \`developer/canonicalDeveloperStartup.js\`; it requires an explicit bridge id and composes the proven Run196 current-runtime ownership transaction with Run197's reversible real-tick freeze. Default game3d imports/startup remain unchanged and no owner policy is inferred.\n- **Browser proof:** ${summary}. Online activation, rollback, production service-worker controlled boot, fully offline current boot, and offline canonical activation/disposal passed. The unchanged production service worker dynamically cached the developer module through its existing network-first same-origin path.\n- **Regression/DoD:** full Chromium smoke ${smoke} PASS; canonical Run195–198 chain, world/determinism/visual contracts, PWA/cache/installability, accessibility/input/physics, mobile streaming/LOD/perf, additive-only and final concurrency gates PASS.\n- **Performance:** live mobile ${mobile}; perf snapshot \`${perf}\`. Dormant developer module adds zero default-runtime frame cost.\n- **Coverage:** desktop 132.25/137.5 km² = **96.2%**; mobile radius-4 resident footprint 81 chunks / 20.25 km² ≈ **14.7%**.\n- **Technical debt:** delta **0**; owner-blocked radius-5, game3d.js split, and world-event checksum decisions untouched. **Risk:** LOW.\n- **Next safe step:** prove a no-source-transform live-state handoff seam for this developer controller without touching default startup; if additive-only blocks that seam, record the blocker rather than altering existing lines.\n`,'utf8');
fs.appendFileSync(path.join(ROOT,'DECISIONS.md'),`\n\n## ADR-0219 — Canonical developer startup stays explicit, dormant, reversible, and production-SW offline-equivalent\n\n- **Decision:** keep the reusable opt-in composition outside \`src/3d\` at \`developer/canonicalDeveloperStartup.js\`. It accepts an already-created current runtime state plus an explicit bridge id, composes Run196 + Run197, and never enters the default \`game3d.html\`/\`game3d.js\` import graph.\n- **Why:** Run198 proved lifecycle ownership but assembled it inline. A reusable developer boundary reduces duplication while preserving zero-risk default startup. Keeping it outside \`src/3d\` avoids changing the strict precache inventory; the existing production service worker already runtime-caches explicitly requested same-origin files.\n- **Rejected:** default canonical startup (migration gate incomplete); inferred bridge choice (owner policy); modifying existing initGame3D lines (additive-only violation); editing service-worker EOF solely for precache registration (Git records its no-newline EOF as a deletion, so additive guard correctly rejects it).\n- **Result/Rollback:** explicit developer/preflight callers gain one deterministic reversible entry point; stop importing the dormant module to roll back. 2D, default 3D, desktop/mobile/PWA navigation, world generation and gameplay defaults are unchanged. **Risk:** LOW.\n`,'utf8');
fs.appendFileSync(path.join(ROOT,'STABLE_TAGS.md'),`\n${tag} | run200 | opt-in canonical developer startup + production-SW offline equivalence | ${stamp}\n`,'utf8');
console.log('[recordRun200CanonicalDeveloperStartup] PASS: appended progress, ADR-0219, stable checkpoint');
