import fs from 'node:fs';

const stamp = process.env.RUN173_STAMP;
const stableTag = process.env.RUN173_STABLE_TAG;
const perfRow = process.env.RUN173_PERF_ROW;
const smokeCount = process.env.RUN173_SMOKE_PASS_COUNT;
const contractSummary = process.env.RUN173_FOG_CONTRACT_SUMMARY || 'live fog/day-night contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run173 governance environment is incomplete.');

const progress = `\n\n## Run 173 — Distance fog/day-night visual regression contract (${stamp})\n- Alt görev: gerçek \`createFog()\` / \`updateFog()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkFogVisualContract.js\` eklendi. Kontrat \`THREE.FogExp2\` tipini, 0.0004→0.00055 day/night density interpolasyonunu, horizon-color copy semantiğini, bağımsız fog instance durumunu ve 500/1000/2000m temsilî atmosferik falloff bantlarını doğruluyor.\n- Runtime/2D/PWA davranışı değiştirilmedi; \`src/3d/fog.js\`, lighting/day-night sabitleri, sky/water/terrain, mobil radius/LOD ve owner kalibrasyon değerlerine dokunulmadı. Owner kararı bekleyen radius-5, game3d.js yapısal borcu ve world-event checksum maddeleri aynen bırakıldı.\n- Additive-only: yayınlanan dal yalnız yeni checker, yeni run workflow'u ve yeni governance recorder ekledi; mevcut source satırı silinmedi/değiştirilmedi.\n- DoD: node --check PASS; ${contractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat/terrain-visual, road-network/road-visual, vegetation-visual, water-visual, sky-visual, fog-visual, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; runtime görseli değişmediği için no-delta regresyon kanıtıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; FogExp2 disposable GPU kaynağı taşımaz, checker iki bağımsız fog instance'ının mutable Color state paylaşmadığını doğruluyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 173 yeni runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0195. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: fog/sky/water/terrain/yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; fog visual regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak fog tipi, day/night yoğunluk rampası, sky-horizon renk senkronizasyonu ve mesafe falloff regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan lighting/day-night gibi kalan bağımsız world/render kontrat boşluklarını güncel main üzerinde yeniden sırala; başlamadan ve yayınlamadan önce eşzamanlılık kapısını uygula.\n`;
const adr = `\n\n## ADR-0195 — Distance fog has a live day/night density and horizon-color contract (run 173)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkFogVisualContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`createFog()\` / \`updateFog()\` fonksiyonlarını çağırır; FogExp2 tipini, başlangıç 0.0004 yoğunluğunu, day/night 0.0004→0.00055 doğrusal interpolasyonunu (0/0.25/0.5/1 örnekleri), horizon renginin \`Color.copy\` ile kopyalanmasını, iki fog instance'ının mutable state paylaşmamasını ve Three.js FogExp2 formülündeki 500/1000/2000m gündüz/gece temsilî visibility bantlarını fail-fast regresyon sözleşmesi olarak doğrular. Runtime kaynağı değiştirilmez.\n\n**Neden:** mevcut full smoke fog'u sahne içinde dolaylı kullanıyor; fog tipinin, day/night density uçlarının/interpolasyonunun veya horizon renk senkronizasyonunun drift etmesi halinde açıklayıcı sistem-seviyesi bir kontrat yoktu. Bu parametreler terrain ile sky arasındaki uzak-mesafe görsel birleşimini doğrudan etkiliyor.\n\n**Alternatifler:** yalnız kaynak metni/regex kontrolü gerçek Three.js nesne tipini ve mutable Color semantiğini ölçmez; piksel snapshot GPU/render-driver farklarına kırılgandır; çalışan \`fog.js\` runtime'ını refactor etmek additive-only riski taşır.\n\n**Sonuç:** fog nesne tipi, bağımsız instance davranışı, sky-horizon renk aktarımı ve day/night mesafe görünürlüğü CI'da canlı modül üzerinde korunur; runtime maliyeti sıfırdır.\n\n**Etkilenen sistemler:** yeni \`scripts/checkFogVisualContract.js\`, run 173 CI workflow'u ve governance kayıtları. \`src/3d/fog.js\`, 2D oyun, lighting/sky/water/terrain runtime'ı, dünya seed'i, mobil streaming/LOD, asset seti ve PWA import grafiği değişmez.\n\n**Geri alma planı:** fog render sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede eder; mevcut runtime veya tarihsel guard satırlarını silmek gerekmez.\n`;
const stable = `\n- ${stableTag} — run 173 distance fog/day-night visual contract (ADR-0195); ${smokeCount}/34+ browser smoke, fog behavior, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run173 governance records appended for ${stableTag}.`);
