import fs from 'node:fs';

const stamp = process.env.RUN176_STAMP;
const stableTag = process.env.RUN176_STABLE_TAG;
const perfRow = process.env.RUN176_PERF_ROW;
const smokeCount = process.env.RUN176_SMOKE_PASS_COUNT;
const contractSummary = process.env.RUN176_CAMERA_CONTRACT_SUMMARY || 'live OrbitControls/camera-collision contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run176 governance environment is incomplete.');

const progress = `\n\n## Run 176 — Orbit/chase camera lifecycle + collision regression contract (${stamp})\n- Alt görev: gerçek \`createOrbitCamera()\` ve \`resolveCameraCollision()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkCameraContract.js\` eklendi. Kontrat OrbitControls target/damping/default ve custom distance sınırlarını, ground-safe polar limitini, DOM listener yaşam döngüsü + dispose temizliğini, boş/zero-distance fast-path kimliğini, gerçek Three.js box ray-hit pull-in davranışını, margin + minimum-distance clamp semantiğini, desiredPosition immutability'sini ve desired ray ötesindeki collider'ın reddini doğruluyor.\n- Runtime/2D/PWA davranışı değiştirilmedi; \`src/3d/camera.js\`, player chase-camera ayarları, F4 debug davranışı, terrain/settlement collider üretimi, mobil radius/LOD ve owner kalibrasyon değerlerine dokunulmadı. Owner kararı bekleyen radius-5, game3d.js yapısal borcu ve world-event checksum maddeleri aynen bırakıldı.\n- Additive-only: yayınlanan dal yalnız yeni checker, yeni run workflow'u ve yeni governance recorder ekledi; mevcut source satırı silinmedi/değiştirilmedi.\n- DoD: node --check PASS; ${contractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat/terrain-visual, road-network/road-visual, vegetation-visual, water-visual, sky-visual, fog-visual, lighting-visual, starfield-visual, camera-contract, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; runtime görseli değişmediği için no-delta regresyon kanıtıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; checker yeni bir DOM hedefinde OrbitControls'un 4 temel listener'ını gerçek add/remove takibiyle doğrulayıp dispose sonrası 0 aktif listener bekliyor; test box geometry/material kaynakları da checker içinde dispose ediliyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 176 yeni runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0198. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: camera/stars/lighting/fog/sky/water/terrain/yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; camera lifecycle/collision regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak kamera zoom/orbit sınırı, pointer/wheel cleanup ve duvar-arazi clipping önleme regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan sceneManager/renderer lifecycle veya F4 free-camera gibi kalan bağımsız kontrat boşluklarını güncel main üzerinde yeniden sırala; başlamadan ve yayınlamadan önce eşzamanlılık kapısını uygula.\n`;
const adr = `\n\n## ADR-0198 — Orbit/chase camera has a live controls-lifecycle and collision contract (run 176)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkCameraContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`createOrbitCamera()\` ve \`resolveCameraCollision()\` fonksiyonlarını çağırır. OrbitControls'un origin target, damping 0.08, mevcut 20-1800m varsayılan distance politikası, custom distance override'ları, ground-safe maxPolarAngle ve touch-action davranışı canlı nesne üzerinde doğrulanır. Teste özel boş bir DOM hedefinde contextmenu/pointerdown/pointercancel/wheel listener'ları izlenir ve \`dispose()\` sonrası sıfır aktif listener beklenir. Collision tarafında gerçek Three.js BoxGeometry ray hit'i ile target→desiredPosition hattı, margin pull-in, minimum-distance clamp, raycaster far sınırı, desiredPosition immutability ve ray menzili dışındaki collider'ın yok sayılması fail-fast doğrulanır. Runtime kaynağı değiştirilmez.\n\n**Neden:** mevcut full smoke kamera ile oyunu gerçekten açıyor ve tarihsel FAZ 4 kontrolleri chase-camera davranışını dolaylı kapsıyor; fakat camera.js'in OrbitControls konfigürasyonu, event-listener teardown'u ve wall-avoidance fonksiyonunun gerçek Raycaster geometrisi üzerindeki matematiksel sözleşmesi tek açıklayıcı canlı kontratta korunmuyordu. Run 172-175 render/atmosfer kontratlarından sonra progress tracker'ın açıkça işaret ettiği camera lifecycle boşluğu düşük-riskli sıradaki bağımsız alandır.\n\n**Alternatifler:** yalnız kaynak regex'i OrbitControls'un gerçek DOM listener yaşam döngüsünü veya Three.js ray hit mesafesini ölçmez; piksel snapshot kamera matematiği için açıklayıcı değildir ve GPU/headless farklarına kırılgandır; mevcut smoke suite'i büyütmek genel registry'yi kamera iç detaylarıyla gereksiz şişirir; çalışan \`camera.js\` runtime'ını refactor etmek additive-only altında gereksiz risk taşır.\n\n**Sonuç:** orbit/chase kamera sınırları, damping, listener cleanup, çarpışma pull-in/min-clamp ve immutable desired-position semantiği CI'da gerçek browser/Three.js nesneleri üzerinde korunur; runtime maliyeti sıfırdır. Testte kullanılan margin/min-distance sayıları ürün kalibrasyonu değildir, yalnız mevcut fonksiyonun parametre semantiğini doğrulayan fixture değerleridir.\n\n**Etkilenen sistemler:** yeni \`scripts/checkCameraContract.js\`, run 176 CI workflow'u ve governance kayıtları. \`src/3d/camera.js\`, \`src/3d/game3d.js\`, player/physics, F4 debug/free-camera, terrain/settlement runtime'ı, mobil streaming/LOD, asset seti ve PWA import grafiği değişmez.\n\n**Geri alma planı:** kamera kontrolleri veya collision sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede eder; mevcut runtime veya tarihsel guard satırlarını silmek gerekmez.\n`;
const stable = `\n- ${stableTag} — run 176 Orbit/chase camera contract (ADR-0198); ${smokeCount}/34+ browser smoke, controls listener lifecycle + collision math, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run176 governance records appended for ${stableTag}.`);
