import fs from 'node:fs';

const stamp = process.env.RUN170_STAMP;
const stableTag = process.env.RUN170_STABLE_TAG;
const perfRow = process.env.RUN170_PERF_ROW;
const smokeCount = process.env.RUN170_SMOKE_PASS_COUNT;
const contractSummary = process.env.RUN170_TERRAIN_CONTRACT_SUMMARY || 'live terrain render contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run170 governance environment is incomplete.');

const progress = `\n\n## Run 170 — Terrain visual geometry regression contract (${stamp})\n- Alt görev: run 169 sonrası bağımsız terrain/visual kalite boşluğunu kapatmak için gerçek \`createTerrainChunk()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkTerrainVisualContract.js\` eklendi. Kontrat desktop terrain PlaneGeometry topolojisini, gerçek height sampler ile vertex yüksekliği eşleşmesini, mevcut grass→rock vertex-color eğrisini, MeshStandardMaterial imzasını, komşu chunk sınırındaki yükseklik/renk sürekliliğini, deterministik aynı-seed çıktısını, metadata ve teardown zincirini doğruluyor.\n- Runtime/2D/PWA davranışı değiştirilmedi; height sampler, macro relief, flatten-pad, mobil terrain LOD ve owner kalibrasyon sabitlerine dokunulmadı. Owner kararı bekleyen radius-5, game3d.js yapısal borcu ve world-event checksum maddeleri aynen bırakıldı.\n- Additive-only: yalnız yeni checker, yeni run workflow'u ve yeni governance recorder eklendi; mevcut source satırı silinmedi/değiştirilmedi.\n- DoD: node --check PASS; ${contractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat, road-network/road-visual, vegetation-visual, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; runtime görseli değişmediği için no-delta regresyon kanıtıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; yeni checker \`disposeTerrainChunk()\` için 1 geometry + 1 material dispose olayını canlı doğruluyor ve testte oluşturduğu üç terrain meshini temizliyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 170 yeni runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0192. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: terrain alanı/yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; terrain visual regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak terrain mesh çözünürlüğü, renk eğrisi, seam, sampler-bake ve teardown regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan bağımsız world/visual kalite adaylarını güncel main üzerinde yeniden sırala; başlamadan ve yayınlamadan önce eşzamanlılık kapısını uygula.\n`;
const adr = `\n\n## ADR-0192 — Rendered terrain has a live geometry/color/seam contract (run 170)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkTerrainVisualContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`createTerrainChunk()\` fonksiyonunu aynı seed/input ile tekrarlı çağırır ve bir komşu chunk üretir; desktop PlaneGeometry'nin 64x64 segment / 4225 vertex / 24576 index topolojisini, her render vertex yüksekliğinin gerçek \`createHeightSampler()\` ile eşleşmesini, mevcut grass→rock vertex-color eğrisini, MeshStandardMaterial vertexColors/roughness/metalness imzasını, aynı-seed deterministik position/normal/color/index verisini, doğu-batı chunk sınırında 65 vertex boyunca yükseklik+renk sürekliliğini, chunk metadata'sını ve \`disposeTerrainChunk()\` teardown davranışını fail-fast regresyon sözleşmesi olarak doğrular. Runtime kaynağı değiştirilmez.\n\n**Neden:** mevcut \`terrainSeatSafetyCheck.js\` height-field'in 14 koltuk için su/eğim güvenliğini, smoke suite flatten-pad davranışını, \`checkMobileTerrainLod.js\` ise mobil segment halkalarını koruyor. Bunlar desktop'ta gerçekten bake edilen terrain meshinin topolojisi/material/renk eğrisi, sampler↔vertex uyumu, komşu chunk seam sürekliliği veya dispose olayını tek bir canlı sözleşmede pinlemiyor. Road ve vegetation render boşlukları run 168-169'da kapatıldığı için aynı dünya katmanının terrain tarafını runtime değişikliği yapmadan güvenceye almak en düşük riskli anlamlı devam adımıdır.\n\n**Alternatifler:** piksel snapshot karşılaştırması GPU/headless farklarına kırılgandır; yalnız kaynak regex'i gerçek Three.js BufferGeometry sonucunu ölçmez; height sampler testini genişletmek rendered material/color/seam zincirini kapsamaz; çalışan terrain runtime'ını refactor etmek additive-only altında gereksiz risk yaratır.\n\n**Sonuç:** desktop terrain render topolojisi, renk/material görünümü, sampler-bake eşleşmesi, komşu chunk seam'i ve teardown davranışı CI'da canlı modül üzerinde korunur; runtime maliyeti sıfırdır. Bilinçli terrain sanat/LOD değişiklikleri ileride yeni versioned checker/ADR ile açıkça sürümlenir.\n\n**Etkilenen sistemler:** yeni \`scripts/checkTerrainVisualContract.js\`, run 170 CI workflow'u ve governance kayıtları. \`src/3d/world/terrain.js\`, 2D oyun, world seed, mobil LOD politikası, asset seti ve PWA import grafiği değişmez.\n\n**Geri alma planı:** terrain render sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede eder; mevcut runtime veya tarihsel guard satırlarını silmek gerekmez.\n`;
const stable = `\n- ${stableTag} — run 170 terrain visual geometry/color/seam contract (ADR-0192); ${smokeCount}/34+ browser smoke, terrain render/disposal, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run170 governance records appended for ${stableTag}.`);
