#!/usr/bin/env node
/** Append validated Run200 records after every CI/DoD gate has passed. */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const env = process.env;
const required = ['RUN200_STAMP', 'RUN200_STABLE_TAG', 'RUN200_BASE_SHA', 'RUN200_SMOKE_PASS_COUNT', 'RUN200_LIVE_MOBILE_JSON', 'RUN200_PERF_ROW'];
for (const name of required) {
	if (!env[name]) throw new Error(`${name} is required`);
}

const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');

append('DECISIONS.md', `\n\n## ADR-0219 — Canonical developer startup must be explicit, deterministic, and fail closed to current runtime\n- **Karar:** Future developer-only canonical startup selection uses the pure Run200 policy contract: default/unknown requests stay on current runtime; canonical is selected only by explicit \`?worldSource=canonical\` plus ready prerequisites; offline canonical additionally requires confirmed cached prerequisites. Any unmet prerequisite deterministically falls back to current.\n- **Neden:** Run198 proved lifecycle rollback/re-init safety, but a boot source-of-truth switch still needs a stable decision boundary before wiring. Encoding that boundary as a side-effect-free module prevents URL/offline/fallback semantics from being guessed independently by later boot code.\n- **Alternatifler:** (1) make canonical the implicit default — rejected because migration is not yet ready; (2) throw when canonical is unavailable — rejected because developer/offline boot must retain a safe current-runtime escape hatch; (3) inspect network/global state inside the policy — rejected because it would make the decision non-deterministic and hard to regression-test.\n- **Sonuç:** \`src/3d/world/worldReferenceCanonicalStartupPolicy.js\` is added but is not imported by default player runtime. Run200 proves eight explicit/default/offline/fallback cases and repeated deterministic equality. Real developer entry wiring remains a later task and must supply readiness/cache facts rather than letting this policy discover them itself.\n- **Etkilenen sistemler:** migration policy/test surface only; default \`game3d.html\`, current runtime, 2D game, PWA shell/cache list, scene/gameplay code and deterministic world generation remain unchanged.\n- **Geri alma planı:** module/test/workflow can be removed as an isolated opt-in preflight surface before adoption; no live runtime rollback is required because nothing imports it by default.\n- **Risk:** LOW.\n`);

append('3D_GAME_PROGRESS.md', `\n\n## Run 200 — Deterministic canonical startup selection policy preflight (${env.RUN200_STAMP})\n- Session/concurrency: started from remote main ${env.RUN200_BASE_SHA.slice(0, 8)} after re-reading GOVERNANCE, Run199/ADR-0218 migration context, recent commits and QUESTIONS_FOR_OWNER. Final CI concurrency gates re-fetch remote main immediately before recording and push.\n- Alt görev: added a new developer-only, currently unimported startup source-selection policy plus deterministic regression check. Default/unknown requests stay current; explicit canonical requires canonical readiness; offline canonical additionally requires cached readiness; every unmet prerequisite fails closed to current. No existing source line was changed or deleted.\n- Validation: additive-only guard PASS; Run200 policy cases PASS; full Chromium smoke PASS count ${env.RUN200_SMOKE_PASS_COUNT} with zero console/page errors; canonical Run195-198 regression gates PASS; service-worker cache + PWA installability PASS; seeded/world-reference and input/physics gates PASS.\n- Mobile/perf: live mobile sample ${env.RUN200_LIVE_MOBILE_JSON}. Perf snapshot ${env.RUN200_PERF_ROW}. Existing exclusive budgets remain drawCalls<500 and triangles<500000; perf trend PASS.\n- Runtime impact: new policy module is not imported by default game3d.html/current runtime, so live player delta 0 and PWA cache surface unchanged. 2D architecture untouched.\n- Technical debt: new live runtime debt 0; migration design debt reduced by making startup/fallback/offline semantics executable instead of prose-only. Risk LOW. Güven 5/5.\n- World Coverage unchanged: desktop %96.2; mobile radius-4 81 chunks / 20.25 km² (~%14.7). World Evolution Report: canonical startup policy readiness +1; live world delta 0. Oyuncu farkı: HAYIR.\n- Sıradaki güvenli adım: create a separate opt-in developer HTML/bootstrap that consumes this policy and supplies real canonicalReady/cachedCanonicalReady facts while preserving current rollback. Do not modify default game3d.html; if obtaining the live state requires changing an existing game3d.js line rather than a purely additive seam, stop and escalate instead of guessing.\n`);

append('STABLE_TAGS.md', `\n\n- ${env.RUN200_STABLE_TAG} — run 200 deterministic canonical developer-startup selection policy preflight (ADR-0219); explicit opt-in + current fallback + offline-cache semantics + full smoke/console/PWA/mobile/perf/canonical regression PASS; live runtime delta 0.\n`);

console.log('[recordRun200CanonicalStartupPolicy] appended validated Run200 progress/ADR/stable records.');
