import fs from 'node:fs';

const stamp = process.env.RUN180_STAMP;
const stableTag = process.env.RUN180_STABLE_TAG;
const perfRow = process.env.RUN180_PERF_ROW;
const smokeCount = process.env.RUN180_SMOKE_PASS_COUNT;
const grassSummary = process.env.RUN180_GRASS_SUMMARY || 'wind-grass contract PASS';
const integrationSummary = process.env.RUN180_INTEGRATION_SUMMARY || 'real-scene integration PASS';
const mobileSummary = process.env.RUN180_MOBILE_BUDGET_SUMMARY || 'mobile render budget PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run180 governance environment incomplete.');

fs.appendFileSync('3D_GAME_PROGRESS.md', `\n\n## Run 180 — Deterministic physical grass + natural GPU wind (${stamp})\n- GOVERNANCE §30 owner sanat sırasının çimen+rüzgâr adımı uygulandı. Canonical map §31 ve run179 coastline/water-mask verisi korunur; bu run harita koordinat hizasını tahmin etmez veya terrain/water runtime'ını değiştirmez.\n- ${grassSummary}\n- Gerçek scene bootstrap entegrasyonu: ${integrationSummary}\n- Placement: world seed + 120m camera-cell için deterministik; yol koridoru, 100m settlement/kale çevresi, water/shore ve >38° eğim dışlanır. Desktop 350m/4000 patch, mobile 260m/1200 patch. Her patch 10 blade / 20 triangle.\n- Rüzgâr: vertex shader iki frekanslı sway/gust, blade-tip flex ve world-position phase kullanır. Time yalnız görsel uniformdur; gameplay/world seed/checksum etkilenmez.\n- İlk-frame güvenliği: tek bounded grass InstancedMesh frustum-culling dışıdır; böylece async player load sonrası kamera kilometrelerce taşındığında onBeforeRender kesin çalışıp aynı bounded instance buffer'ını güncel camera-cell'e recenter eder.\n- ${mobileSummary}\n- Additive-only: sceneManager.js ve vegetation.js yalnız sona append edildi; mevcut source satırı silinmedi/değiştirilmedi. Yeni model/texture/CDN/runtime module yok.\n- DoD: node --check PASS; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; isolated+real-scene grass, canonical map+water mask, medieval roads, terrain/vegetation/water/sky/fog/lighting/starfield/camera, determinism, assets, a11y/input/physics, mobile streaming/LOD/culling/perf, PWA/cache ve additive-only kapıları PASS.\n- Görsel kanıt: gerçek 390x844 mobile Chromium yakın + F4 uzak iki screenshot artifact, console/page error 0.\n- Performans: ${perfRow}. Heap trend ayrıca kontrol edildi; grass tek bounded InstancedMesh ve teardown geometry/material dispose zinciri canlı doğrulandı.\n- Teknik borç: 1 (mevcut game3d.js yapısal borcu). Risk LOW. Güven 5/5. ADR: ADR-0201. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report: fiziksel grass/wind +1; road/terrain relief/castle/NPC/event/animal/coverage/asset/dialogue 0; ADR +1. Oyuncu farkı: EVET — açık arazide fiziksel çimen görünür ve doğal rüzgârla salınır.\n- Sıradaki güvenli adım: §30 sırasıyla canonical worldReferenceMap relief/biome verisini kullanabilen deterministik taş/kaya kümeleri; makro dağ relief'i ayrı §8.4 terrain-safety run'ı olacaktır.\n`);

fs.appendFileSync('DECISIONS.md', `\n\n## ADR-0201 — Grass is one bounded deterministic InstancedMesh with shader wind and first-frame-safe recenter (run 180)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** Fiziksel grass, sceneManager'ın additive katmanında tek InstancedMesh olarak üretilir. World seed + 120m quantized camera-cell determinism'i kullanılır; desktop 350m/4000, mobile 260m/1200 patch tavanıdır. Road, settlement, shore ve dik-yüzey exclusion zorunludur. Her patch 10 low-poly blade/20 triangle taşır. MeshStandardMaterial vertex shader'ına iki frekanslı zaman tabanlı sway eklenir. Tek bounded mesh `frustumCulled=false` kullanır; çünkü createScene bootstrap kamerası ile async player-spawn kamerası kilometrelerce ayrılabilir ve recenter callback'i `onBeforeRender` içindedir.\n\n**Neden:** World-resident milyonlarca blade mobil RAM/triangle maliyetini büyütür; CPU per-blade animasyonu gereksizdir. Camera-local bounded field + GPU wind görünür fiziksel detay üretirken maliyeti kesin sınırlar. Frustum bypass yalnız bu tek bounded mesh içindir ve callback'in ilk player-camera render'ında çalışmasını garanti eder; aksi halde eski bootstrap-cell bounds yeni frustum dışında kalıp grass kendi recenter callback'ine ulaşamayabilir.\n\n**Alternatifler:** texture-only grass fiziksel salınım vermez; milyonlarca world-resident blade bütçe riski taşır; game3d tick wiring'i 547/600 yapısal borcu büyütür; devasa bounding sphere gerçek bounds'u yanlış temsil eder; canonical water-mask/biome verisini aynı run'da density tuning'e bağlamak koordinat hizası kanıtlanmadan §31'e aykırıdır.\n\n**Sonuç:** Grass gerçek render yolunda +1 draw-call bounded maliyetle görünür; aynı-seed/cell bit-identical placement, doğal shader sway, first-frame camera teleport recenter ve teardown CI'da canlı korunur. Canonical map/water mask, 2D, terrain relief, roads topology, gameplay ve world-event checksum değişmez.\n`);

fs.appendFileSync('STABLE_TAGS.md', `\n- ${stableTag} — run 180 deterministic physical wind grass (ADR-0201); ${smokeCount}/34+ smoke + canonical-map/water-mask/mobile/PWA/determinism gates PASS.\n`);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run180 governance appended for ${stableTag}.`);
