import fs from 'node:fs';

const stamp = process.env.RUN174_STAMP;
const stableTag = process.env.RUN174_STABLE_TAG;
const perfRow = process.env.RUN174_PERF_ROW;
const smokeCount = process.env.RUN174_SMOKE_PASS_COUNT;
const contractSummary = process.env.RUN174_LIGHTING_CONTRACT_SUMMARY || 'live day/night lighting contract PASS';
if (!stamp || !stableTag || !perfRow || !smokeCount) throw new Error('Run174 governance environment is incomplete.');

const progress = `\n\n## Run 174 — Day/night lighting visual regression contract (${stamp})\n- Alt görev: gerçek \`createDayNightLighting()\` / \`updateDayNightLighting()\` / \`disposeDayNightLighting()\` çıktısını tarayıcı içinde doğrulayan additive-only \`scripts/checkLightingVisualContract.js\` eklendi. Kontrat DirectionalLight + HemisphereLight oluşturma/sahne üyeliğini, mevcut day/night keyframe renk-intensity interpolasyonunu, nightFactor + horizon/zenith senkronunu, 500m güneş yörüngesini, pozitif/negatif zaman wraparound'unu, bağımsız lighting instance durumunu ve teardown zincirini doğruluyor.\n- Runtime/2D/PWA davranışı değiştirilmedi; \`src/3d/lighting.js\`, day/night keyframe sabitleri, sky/fog/water/terrain, mobil radius/LOD ve owner kalibrasyon değerlerine dokunulmadı. Owner kararı bekleyen radius-5, game3d.js yapısal borcu ve world-event checksum maddeleri aynen bırakıldı.\n- Additive-only: yayınlanan dal yalnız yeni checker, yeni run workflow'u ve yeni governance recorder ekledi; mevcut source satırı silinmedi/değiştirilmedi.\n- DoD: node --check PASS; ${contractSummary}; baseline + after browser smoke ${smokeCount}/34+ PASS; 3D console/page error 0; determinism, assets, accessibility, input/physics, mobile streaming/LOD/perf, terrain-seat/terrain-visual, road-network/road-visual, vegetation-visual, water-visual, sky-visual, fog-visual, lighting-visual, PWA installability/cache ve additive-only kapıları PASS.\n- Görsel doğrulama: 390x844 mobile Chromium yakın + F4 uzak render kanıtı artifact olarak üretildi; runtime görseli değişmediği için no-delta regresyon kanıtıdır.\n- Performans: ${perfRow}\n- Memory leak checklist: runtime allocation eklenmedi; DirectionalLight/HemisphereLight geometry/texture/shadow-map taşımıyor ve checker dispose sonrası iki light node'un da scene parent'ından ayrıldığını doğruluyor.\n- Teknik borç: 1 (önceden var olan \`game3d.js\` yapısal borcu); run 174 yeni runtime borcu eklemedi. Risk LOW. Güven 5/5.\n- ADR: ADR-0196. World Coverage: desktop %96.2, mobil resident ~%14.7 (81 chunk / 20.25 km²) — değişmedi.\n- World Evolution Report delta: lighting/fog/sky/water/terrain/yol/orman/kale/NPC/event/hayvan/coverage/asset/diyalog 0; ADR +1; day/night lighting regression coverage +1. Oyuncu farkı: doğrudan HAYIR; dolaylı olarak güneş/hemisphere ışık tipi, keyframe renk-intensity geçişleri, sun-orbit ve sky-gradient senkron regresyonlarının main'e sızma riski azaldı.\n- Sıradaki güvenli adım: owner bloklarını zorlamadan stars/camera gibi kalan bağımsız world/render kontrat boşluklarını güncel main üzerinde yeniden sırala; başlamadan ve yayınlamadan önce eşzamanlılık kapısını uygula.\n`;
const adr = `\n\n## ADR-0196 — Day/night lighting has a live keyframe, sun-orbit and sky-sync contract (run 174)\n\n**Risk Seviyesi:** LOW\n\n**Karar:** \`scripts/checkLightingVisualContract.js\`, gerçek tarayıcı/import-map ortamında mevcut \`createDayNightLighting()\` / \`updateDayNightLighting()\` / \`disposeDayNightLighting()\` fonksiyonlarını çağırır; DirectionalLight + HemisphereLight tip/sahne üyeliğini, mevcut 0.00/0.22/0.27/0.50/0.73/0.78/1.00 keyframe sözleşmesini ve ara interpolasyonlarını, nightFactor'dan türeyen horizon/zenith gradientini, 500m XY + 200m Z sun-orbit matematiğini, pozitif/negatif zaman wraparound'unu, output Color bağımsızlığını, iki lighting instance'ının mutable state izolasyonunu ve scene teardown davranışını fail-fast regresyon sözleşmesi olarak doğrular. Runtime kaynağı değiştirilmez.\n\n**Neden:** full browser smoke lighting sistemini dolaylı çalıştırıyor, sky/fog kontratları ise onun çıktısını tüketen katmanları koruyor; ancak light tipleri, dawn/noon/dusk keyframe değerleri, güneş yörüngesi veya sky-gradient üretimi drift ettiğinde hangi sınırın bozulduğunu açıklayan doğrudan canlı lighting kontratı yoktu. Run 172-173 sky/fog zincirinden sonra bu, world/render katmanındaki en küçük bağımsız kapsam boşluğudur.\n\n**Alternatifler:** yalnız kaynak regex'i Three.js light nesnelerini, Color interpolasyonunu ve scene teardown'u ölçmez; piksel snapshot GPU/render-driver farklarına kırılgandır; çalışan \`lighting.js\` runtime'ını refactor etmek additive-only altında gereksiz risk taşır.\n\n**Sonuç:** day/night light nesneleri, keyframe geçişleri, time wrapping, sun-orbit ve sky-gradient senkronu CI'da canlı modül üzerinde korunur; runtime maliyeti sıfırdır.\n\n**Etkilenen sistemler:** yeni \`scripts/checkLightingVisualContract.js\`, run 174 CI workflow'u ve governance kayıtları. \`src/3d/lighting.js\`, 2D oyun, sky/fog/water/terrain runtime'ı, world seed, mobil streaming/LOD, asset seti ve PWA import grafiği değişmez.\n\n**Geri alma planı:** lighting/day-night sanat veya zaman sözleşmesi bilinçli olarak değişirse yeni bir versioned checker/ADR mevcut kontratı supersede eder; mevcut runtime veya tarihsel guard satırlarını silmek gerekmez.\n`;
const stable = `\n- ${stableTag} — run 174 day/night lighting visual contract (ADR-0196); ${smokeCount}/34+ browser smoke, lighting behavior, PWA/world/determinism/mobile gates PASS; runtime delta 0.\n`;
fs.appendFileSync('3D_GAME_PROGRESS.md', progress);
fs.appendFileSync('DECISIONS.md', adr);
fs.appendFileSync('STABLE_TAGS.md', stable);
fs.appendFileSync('perf_log.csv', `\n${perfRow}`);
console.log(`Run174 governance records appended for ${stableTag}.`);
