#!/usr/bin/env node
/** Run209 validated-checkpoint recorder. Appends documentation only after the workflow's full DoD passes. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const required = name => { const value = process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp = required('RUN209_STAMP');
const tag = required('RUN209_STABLE_TAG');
const base = required('RUN209_BASE_SHA');
const smoke = required('RUN209_SMOKE_PASS_COUNT');
const proof = JSON.parse(required('RUN209_PROOF_JSON'));
const mobile = JSON.parse(required('RUN209_LIVE_MOBILE_JSON'));
const perf = required('RUN209_PERF_ROW');
const append = (file, text) => fs.appendFileSync(path.join(ROOT, file), text, 'utf8');
const fields = perf.split(',');
if (fields.length < 8 || fields[1] !== 'run209-rts-camera') throw new Error(`unexpected perf row: ${perf}`);
const [, , fps, drawCalls, triangles, geometries, textures, heap] = fields;
const close = proof.closeSnapshot;
const overview = proof.overviewSnapshot;
const rtsMobile = proof.mobileSnapshot;
append('3D_GAME_PROGRESS.md', `\n\n## Run 209 — RTS close/overview camera framing presets\n\n- **Validated:** ${stamp}; base main \`${base}\`.\n- Added two strictly additive RTS camera framing controls to \`rts.html\`: **Yakın Komuta** focuses the selected army then applies bounded OrbitControls zoom-in steps; **Genel Görünüm** applies bounded zoom-out steps. Keyboard shortcuts \`1\`/\`2\` mirror the buttons.\n- The implementation reuses the already-exposed \`window.__WESTEROS_RTS__.focusArmy()\` seam and the canvas' existing wheel/OrbitControls path; no army, world-generation, deterministic movement, 2D, character runtime, service-worker cache list, or asset manifest changes were made. Listeners/buttons are disposed on \`pagehide\`.\n- Real Chromium visual proof: desktop close + desktop overview + mobile close screenshots; console/page errors **${proof.consoleErrors}**. Desktop close render: **${close.drawCalls} draw calls / ${close.triangles} triangles**; desktop overview: **${overview.drawCalls} / ${overview.triangles}** (<2500/<5M). RTS mobile close: **${rtsMobile.drawCalls} / ${rtsMobile.triangles}** (<500/<500000).\n- Full legacy browser smoke: **${smoke}+ PASS**; seeded/world-reference/terrain/road regressions PASS; production PWA cache/installability PASS. Existing mobile live budget: **${mobile.drawCalls} draw calls / ${mobile.triangles} triangles / ${mobile.geometries} geometries / ${mobile.textures} textures**.\n- World Coverage unchanged: desktop **96.2%**; mobile radius-4 **81 chunks / 20.25 km² (~14.7%)**. Perf snapshot: **fps ${fps}, ${drawCalls} draw calls, ${triangles} triangles, ${geometries} geometries, ${textures} textures, ${heap} MB heap**; trend guard PASS.\n- Technical debt: preset zoom intentionally delegates to OrbitControls' existing wheel-event semantics rather than exposing camera distance through a new runtime API. This keeps the change isolated/additive but couples the preset to the established input seam; browser regression coverage now protects that contract. Risk **LOW**, confidence **5/5**.\n- **Next safe visible step (Run210):** stay on visible RTS work and improve daylight/contrast readability or add richer reused human/guard silhouettes with LOD/instancing, without touching owner-gated mobile radius/world-event constraints.\n`);
append('DECISIONS.md', `\n\n## ADR-0228 — Add RTS camera presets through the existing focus/zoom input seam\n\n- **Decision:** Implement close/overview RTS framing as additive UI controls in \`rts.html\`, reusing \`window.__WESTEROS_RTS__.focusArmy()\` plus the canvas' existing wheel-driven OrbitControls zoom path.\n- **Why:** Run208 identified camera/readability as the next safe visible track. The additive-only rule forbids rewriting established camera code, while the RTS runtime already exposes a safe focus seam and a proven zoom input path.\n- **Alternatives:** edit \`rtsGame.js\` camera constants (rejected: modifies existing source lines); expose a new camera-distance API in the RTS runtime (deferred: requires established-module changes); CSS-only readability polish (rejected for this run because it would not materially improve tactical framing).\n- **Result:** players can switch between a closer army-centric tactical view and a wider battlefield view on desktop/mobile, with 1/2 keyboard shortcuts on desktop; deterministic army/world state is untouched.\n- **Affected systems:** \`rts.html\` additive UI/input overlay plus Run209 test/CI/documentation only. 2D, character-mode, army movement, world generation and PWA cache membership remain unchanged.\n- **Rollback:** the appended camera-preset module is isolated and can be removed only in a future owner-approved non-additive cleanup; no persistent state migration exists.\n- **Future-phase impact:** a later explicit camera-controller API may supersede this input seam, but current presets provide immediate AoE-style framing without blocking that architecture.\n- **Risk:** LOW.\n`);
append('STABLE_TAGS.md', `\n- \`${tag}\` — Run209 RTS close/overview camera presets; desktop+mobile visual proof, ${smoke}+ legacy smoke, PWA/perf/additive/concurrency gates PASS.\n`);
console.log(`[recordRun209RtsCameraPresets] appended Run209 progress, ADR-0228 and stable checkpoint ${tag}`);
