#!/usr/bin/env node
/** Run200 append-only recorder for the startup-source selector preflight. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const need = (name) => { const value=process.env[name]; if (!value) throw new Error(`missing ${name}`); return value; };
const stamp=need('RUN200_STAMP'); const stableTag=need('RUN200_STABLE_TAG'); const baseSha=need('RUN200_BASE_SHA'); const summary=need('RUN200_SUMMARY'); const proof=need('RUN200_PROOF_JSON'); const smoke=need('RUN200_SMOKE_PASS_COUNT'); const mobile=need('RUN200_LIVE_MOBILE_JSON'); const perf=need('RUN200_PERF_ROW');
const append=(file,text)=>fs.appendFileSync(path.join(ROOT,file),text,'utf8');
append('3D_GAME_PROGRESS.md', `\n\n## Run 200 — Explicit canonical startup-source selector preflight (${stamp})\n- Session/concurrency: started from remote main ${baseSha.slice(0,8)} after reading GOVERNANCE, Run199, recent ADRs/commits and QUESTIONS_FOR_OWNER; owner-blocked items were not guessed. Final remote-main equality is rechecked immediately before branch publication.\n- Alt görev: default game3d.html/runtime değiştirilmeden, scripts/run200CanonicalStartupSelectorShadow.mjs ile startup source seçimini simulation handoff öncesine taşıyan opt-in preflight seam eklendi. No query/default => current; yalnız worldSource=canonical-dev => canonical request; bilinmeyen değer => current.\n- Failure/rollback: canonical activation failure current runtimeı koruyor; başarılı canonical activation aynı Run195-198 integration boundary üzerinden current collider/root ownership'a geri alınabiliyor. Proof ${proof}. Summary: ${summary}.\n- PWA/offline boundary: live src ve service-worker import graph değişmedi; yeni seam scripts/ altında preflight-only kaldığı için default PWA shell/cache bütünü aynen korunuyor ve checkServiceWorkerCache + checkPwaInstallability PASS. Gerçek cached developer entry point henüz eklenmedi.\n- DoD/regression: full browser smoke ${smoke}+ PASS, zero console/page errors; canonical Run195-198 regressions, seeded/world-reference, PWA/cache, mobile streaming/LOD/perf, additive-only ve governance gates PASS.\n- Mobile/perf: ${mobile}; perf ${perf}; trend PASS. World Coverage unchanged: desktop %96.2; mobile radius-4 81 chunks / 20.25 km² (~%14.7).\n- Technical debt: new live-runtime debt 0; preflight-only selector +1 architecture proof. Risk LOW. Güven 5/5. Oyuncu farkı: HAYIR.\n- Sıradaki güvenli adım: bu selector seam'i ayrı opt-in developer document/boot surface'ine bağla ve o entry pointin service-worker cache/offline bootunu gerçek browser install+offline turunda kanıtla. Default game3d.html canonical yapılmaz; current fallback ve lifecycle rollback korunmadan ilerleme yok.\n`);
append('DECISIONS.md', `\n\n## ADR-0219 — Startup source selection must be explicit and reversible before a developer canonical entry point exists\n**Karar:** Run200, default runtimea bağlanmayan preflight-only startup selector ekler. Varsayılan kaynak current kalır; canonical yalnız açık \`worldSource=canonical-dev\` isteğiyle seçilebilir. Canonical activation başarısızsa selector current runtimeı korur; başarılı activation rollback ile current ownership'a döner.\n\n**Neden:** Run195-198 replacement, tick ve lifecycle sınırlarını kanıtladı; fakat doğrudan default startup switch yapmak bu kanıtı boot policy kararıyla karıştırırdı. Önce seçim semantiğinin deterministik ve fail-closed/current-fallback olması ayrı doğrulanmalıdır.\n\n**Alternatifler:** (1) Default game3d.html'i canonical yapmak: reddedildi, owner kararı ve offline lifecycle kanıtı yok. (2) Bilinmeyen query değerlerini canonical saymak: reddedildi, tahmin yasağına aykırı. (3) Activation hatasında bootu tamamen düşürmek: reddedildi, mevcut çalışan current dünya güvenli fallback.\n\n**Sonuç:** Developer entry point bir sonraki bağımsız adım olabilir; live runtime/PWA graph bu ADR'de değişmez.\n\n**Etkilenen sistemler:** yalnız scripts/ preflight ve CI kayıtları; live 2D/3D/PWA kaynakları yok.\n\n**Geri alma planı:** Run200 yeni preflight dosyalarını kullanmayı bırak; default runtime zaten değişmediği için oyuncu rollback'i gerekmez.\n\n**Risk:** LOW.\n`);
append('STABLE_TAGS.md', `\n- ${stableTag} — run 200 explicit canonical startup-source selector preflight; default current + explicit canonical opt-in + invalid-request current fallback + rollback + full smoke/PWA/mobile/perf gates PASS; live runtime delta 0.\n`);
console.log(`[recordRun200CanonicalStartupSelector] PASS: ${stableTag}`);
