import type { Disposable } from './coreTypes.ts';
export type InputDeviceKind = 'keyboard' | 'pointer' | 'touch' | 'gamepad' | 'wheel' | 'virtual';
export type InputAction = 'move' | 'look' | 'jump' | 'sprint' | 'crouch' | 'interact' | 'attack' | 'block' | 'pause' | 'confirm' | 'cancel' | 'inventory';
export type InputPhase = 'pressed' | 'released' | 'held' | 'repeat';
export interface InputSample { readonly device: InputDeviceKind; readonly code: string; readonly phase: InputPhase; readonly value: number; readonly x?: number; readonly y?: number; readonly timeMs: number; readonly sequence: number; }
export interface ActionBinding { readonly action: InputAction; readonly device: InputDeviceKind; readonly code: string; readonly scale: number; readonly deadzone: number; readonly priority: number; readonly contexts?: readonly string[]; }
export interface ActionState { readonly action: InputAction; readonly value: number; readonly pressed: boolean; readonly released: boolean; readonly held: boolean; readonly source: string | null; }
export interface InputContext { readonly id: string; readonly priority: number; readonly enabled: boolean; readonly capturesPointer: boolean; readonly capturesKeyboard: boolean; }
const ACTIONS: readonly InputAction[] = ['move','look','jump','sprint','crouch','interact','attack','block','pause','confirm','cancel','inventory'];
const clamp = (v: number, min: number, max: number): number => Math.min(max, Math.max(min, Number.isFinite(v) ? v : min));
const deadzone = (v: number, d: number): number => { const m = Math.abs(v); if (m <= d) return 0; return Math.sign(v) * clamp((m - d) / Math.max(0.000001, 1 - d), 0, 1); };
export class InputBindingRegistry {
  #bindings: ActionBinding[] = []; #contexts = new Map<string, InputContext>();
  register(binding: ActionBinding): void { const normalized = Object.freeze({ ...binding, code: binding.code.trim(), scale: Number.isFinite(binding.scale) ? binding.scale : 1, deadzone: clamp(binding.deadzone, 0, 0.95), priority: Math.trunc(binding.priority), contexts: Object.freeze([...(binding.contexts ?? [])]) }); this.#bindings.push(normalized); this.#bindings.sort((a,b) => b.priority-a.priority || a.action.localeCompare(b.action) || a.device.localeCompare(b.device) || a.code.localeCompare(b.code)); }
  unregister(action: InputAction, device: InputDeviceKind, code: string): number { const before=this.#bindings.length; this.#bindings=this.#bindings.filter(b=>!(b.action===action&&b.device===device&&b.code===code)); return before-this.#bindings.length; }
  bindings(): readonly ActionBinding[] { return Object.freeze(this.#bindings.slice()); }
  setContext(context: InputContext): void { this.#contexts.set(context.id, Object.freeze({...context})); }
  removeContext(id: string): boolean { return this.#contexts.delete(id); }
  contexts(): readonly InputContext[] { return Object.freeze([...this.#contexts.values()].sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id))); }
  matches(binding: ActionBinding, sample: InputSample, active: ReadonlySet<string>): boolean { if(binding.device!==sample.device||binding.code!==sample.code)return false; return !binding.contexts?.length || binding.contexts.some(c=>active.has(c)); }
}
export class InputActionRouter implements Disposable {
  readonly registry: InputBindingRegistry; #states=new Map<InputAction,ActionState>(); #active=new Set<string>(); #previous=new Map<InputAction,number>(); #sequence=0; #disposed=false;
  constructor(registry=new InputBindingRegistry()){this.registry=registry;this.resetStates();}
  activateContext(id:string):void{this.ensureLive();this.#active.add(id);} deactivateContext(id:string):void{this.ensureLive();this.#active.delete(id);} setActiveContexts(ids:readonly string[]):void{this.ensureLive();this.#active=new Set(ids);} activeContexts():readonly string[]{return Object.freeze([...this.#active].sort());}
  ingest(sample:Omit<InputSample,'sequence'>):readonly ActionState[]{this.ensureLive();const s=Object.freeze({...sample,value:clamp(sample.value,-1,1),sequence:this.#sequence++});const matched=this.registry.bindings().filter(b=>this.registry.matches(b,s,this.#active));for(const binding of matched){const value=clamp(deadzone(s.value,binding.deadzone)*binding.scale,-1,1);const previous=this.#previous.get(binding.action)??0;const pressed=s.phase==='pressed'||(previous===0&&value!==0);const released=s.phase==='released'||(previous!==0&&value===0);const held=s.phase==='held'||(value!==0&&!pressed);if(matched[0]===binding||this.#states.get(binding.action)?.value===0||pressed)this.#states.set(binding.action,Object.freeze({action:binding.action,value,pressed,released,held,source:`${binding.device}:${binding.code}`}));this.#previous.set(binding.action,value);}return Object.freeze(ACTIONS.map(a=>this.#states.get(a)!));}
  consumeFrame():readonly ActionState[]{this.ensureLive();const out=ACTIONS.map(a=>this.#states.get(a)!);this.#states=new Map(ACTIONS.map(a=>{const s=out[ACTIONS.indexOf(a)]!;return [a,Object.freeze({...s,pressed:false,released:false,held:s.value!==0})] as const;}));return Object.freeze(out);}
  state(action:InputAction):ActionState{this.ensureLive();return this.#states.get(action)!;} reset():void{this.ensureLive();this.resetStates();this.#active.clear();this.#previous.clear();} dispose():void{if(this.#disposed)return;this.#disposed=true;this.#states.clear();this.#active.clear();this.#previous.clear();}
  private resetStates():void{this.#states=new Map(ACTIONS.map(action=>[action,Object.freeze({action,value:0,pressed:false,released:false,held:false,source:null})] as const));}
  private ensureLive():void{if(this.#disposed)throw new Error('input router disposed');}
}
export interface InputBufferEntry{readonly action:InputAction;readonly value:number;readonly createdTick:number;readonly expiresTick:number;readonly sequence:number;}
export class InputBuffer{#entries:InputBufferEntry[]=[];#sequence=0;readonly maxEntries:number;constructor(maxEntries=64){this.maxEntries=Math.max(8,Math.min(256,Math.trunc(maxEntries)));}push(action:InputAction,value:number,tick:number,ttl=6):InputBufferEntry{const e=Object.freeze({action,value:clamp(value,-1,1),createdTick:Math.trunc(tick),expiresTick:Math.trunc(tick)+Math.max(1,Math.trunc(ttl)),sequence:this.#sequence++});this.#entries.push(e);if(this.#entries.length>this.maxEntries)this.#entries.shift();return e;}expire(tick:number):void{this.#entries=this.#entries.filter(e=>e.expiresTick>tick);}consume(action:InputAction,tick:number):InputBufferEntry|null{this.expire(tick);const i=this.#entries.findIndex(e=>e.action===action&&e.expiresTick>tick);return i<0?null:this.#entries.splice(i,1)[0]??null;}peek(action:InputAction,tick:number):InputBufferEntry|null{this.expire(tick);return this.#entries.find(e=>e.action===action&&e.expiresTick>tick)??null;}entries():readonly InputBufferEntry[]{return Object.freeze(this.#entries.slice());}clear():void{this.#entries.length=0;}}
export interface AnalogVector{readonly x:number;readonly y:number;readonly magnitude:number;readonly angle:number;}
export const normalizeAnalog=(x:number,y:number,d=0.15):AnalogVector=>{const sx=clamp(x,-1,1),sy=clamp(y,-1,1),m=Math.hypot(sx,sy);if(m<=d)return Object.freeze({x:0,y:0,magnitude:0,angle:0});const n=clamp((Math.min(1,m)-d)/Math.max(0.000001,1-d),0,1);return Object.freeze({x:sx/Math.max(m,0.000001)*n,y:sy/Math.max(m,0.000001)*n,magnitude:n,angle:Math.atan2(sy,sx)});};
export interface GestureSample{readonly pointerId:number;readonly x:number;readonly y:number;readonly timeMs:number;readonly pressure:number;}
export interface GestureResult{readonly type:'tap'|'drag'|'swipe'|'pinch'|'none';readonly dx:number;readonly dy:number;readonly distance:number;readonly durationMs:number;readonly scale:number;}
export const recognizeGesture=(samples:readonly GestureSample[],maxTapDistance=12,maxTapDurationMs=280):GestureResult=>{if(samples.length<2)return Object.freeze({type:'none',dx:0,dy:0,distance:0,durationMs:0,scale:1});const first=samples[0]!,last=samples.at(-1)!,dx=last.x-first.x,dy=last.y-first.y,distance=Math.hypot(dx,dy),durationMs=Math.max(0,last.timeMs-first.timeMs);const type=distance<=maxTapDistance&&durationMs<=maxTapDurationMs?'tap':distance>80&&durationMs<900?'swipe':'drag';return Object.freeze({type,dx,dy,distance,durationMs,scale:1});};
