import type { Disposable, Result, Tick } from './coreTypes.ts';
import { err, ok } from './coreTypes.ts';

export type ReplicationChannel = 'reliable' | 'unreliable' | 'state';
export type ReplicationRole = 'authority' | 'proxy' | 'spectator';
export type DeliveryState = 'pending' | 'acked' | 'expired' | 'rejected';

export interface SequenceWindow { readonly newest: number; readonly bits: number; }
export const isSequenceNewer = (candidate: number, reference: number): boolean => { const a = candidate >>> 0; const b = reference >>> 0; const delta = (a - b) >>> 0; return delta !== 0 && delta < 0x80000000; };
export const sequenceDistance = (candidate: number, reference: number): number => (candidate - reference) >>> 0;
export const sequenceWindowAccepts = (window: SequenceWindow, sequence: number): boolean => { const value = sequence >>> 0; if (value === window.newest) return false; if (isSequenceNewer(value, window.newest)) return true; const distance = sequenceDistance(window.newest, value); return distance <= 32 && ((window.bits >>> (distance - 1)) & 1) === 0; };
export const advanceSequenceWindow = (window: SequenceWindow, sequence: number): SequenceWindow => { const value = sequence >>> 0; if (value === window.newest) return window; if (isSequenceNewer(value, window.newest)) { const shift = Math.min(32, sequenceDistance(value, window.newest)); return Object.freeze({ newest: value, bits: shift >= 32 ? 0 : ((window.bits << shift) | (1 << (shift - 1))) >>> 0 }); } const distance = sequenceDistance(window.newest, value); if (distance < 1 || distance > 32) return window; return Object.freeze({ newest: window.newest, bits: (window.bits | (1 << (distance - 1))) >>> 0 }); };

export interface ReplicationEntityState { readonly id: string; readonly revision: number; readonly owner: string; readonly position?: readonly [number, number, number]; readonly rotation?: readonly [number, number, number, number]; readonly velocity?: readonly [number, number, number]; readonly flags?: number; readonly components?: Readonly<Record<string, unknown>>; }
export interface ReplicationEntityDelta { readonly id: string; readonly revision: number; readonly changed: Readonly<Record<string, unknown>>; readonly removed: readonly string[]; }
const equalValue = (left: unknown, right: unknown): boolean => { if (Object.is(left, right)) return true; if (Array.isArray(left) && Array.isArray(right)) return left.length === right.length && left.every((value, index) => equalValue(value, right[index])); if (left && right && typeof left === 'object' && typeof right === 'object') { const a = left as Record<string, unknown>; const b = right as Record<string, unknown>; const keys = Object.keys(a); return keys.length === Object.keys(b).length && keys.every((key) => Object.prototype.hasOwnProperty.call(b, key) && equalValue(a[key], b[key])); } return false; };
export const diffEntityState = (previous: ReplicationEntityState | null, next: ReplicationEntityState): ReplicationEntityDelta => { const before = previous ? { ...previous, components: previous.components ?? {} } : {}; const after = { ...next, components: next.components ?? {} }; const changed: Record<string, unknown> = {}; const removed: string[] = []; for (const [key, value] of Object.entries(after)) if (!equalValue((before as Record<string, unknown>)[key], value)) changed[key] = value; for (const key of Object.keys(before)) if (!Object.prototype.hasOwnProperty.call(after, key)) removed.push(key); return Object.freeze({ id: next.id, revision: next.revision, changed: Object.freeze(changed), removed: Object.freeze(removed.sort()) }); };
export const applyEntityDelta = (previous: ReplicationEntityState | null, delta: ReplicationEntityDelta): Result<ReplicationEntityState, string> => { if (!delta.id) return err('replication delta id is required'); if (previous && delta.revision < previous.revision) return err('stale replication delta'); const base: Record<string, unknown> = previous ? { ...previous } : { id: delta.id, revision: 0, owner: '' }; for (const key of delta.removed) delete base[key]; Object.assign(base, delta.changed); base.id = delta.id; base.revision = delta.revision; return ok(Object.freeze(base as ReplicationEntityState)); };

export interface ReplicationPacket<T = unknown> { readonly protocol: 1; readonly channel: ReplicationChannel; readonly sequence: number; readonly tick: Tick; readonly sender: string; readonly target: string | null; readonly payload: T; readonly checksum: string; }
const hashText = (text: string): string => { let hash = 2166136261 >>> 0; for (let index = 0; index < text.length; index += 1) { hash ^= text.charCodeAt(index); hash = Math.imul(hash, 16777619) >>> 0; } return (hash >>> 0).toString(16).padStart(8, '0'); };
export const packetChecksum = <T>(packet: Omit<ReplicationPacket<T>, 'checksum'>): string => hashText(JSON.stringify(packet));
export const makePacket = <T>(input: Omit<ReplicationPacket<T>, 'checksum'>): ReplicationPacket<T> => Object.freeze({ ...input, checksum: packetChecksum(input) });
export const validatePacket = <T>(packet: ReplicationPacket<T>): boolean => packet.protocol === 1 && packet.sequence >= 0 && packet.tick >= 0 && packet.checksum === packetChecksum({ protocol: packet.protocol, channel: packet.channel, sequence: packet.sequence, tick: packet.tick, sender: packet.sender, target: packet.target, payload: packet.payload });

export interface AckTrackerSnapshot { readonly highest: number; readonly pending: number; readonly expired: number; }
interface PendingPacket { readonly sequence: number; readonly createdTick: Tick; readonly expiresTick: Tick; state: DeliveryState; }
export class AckTracker implements Disposable {
  #pending = new Map<number, PendingPacket>(); #highestAck = 0; #expired = 0; #disposed = false;
  track(sequence: number, createdTick: Tick, ttlTicks: number): void { this.ensureLive(); const normalized = sequence >>> 0; this.#pending.set(normalized, { sequence: normalized, createdTick, expiresTick: createdTick + Math.max(1, Math.trunc(ttlTicks)), state: 'pending' }); }
  ack(sequence: number): boolean { this.ensureLive(); const normalized = sequence >>> 0; const pending = this.#pending.get(normalized); if (!pending || pending.state !== 'pending') return false; pending.state = 'acked'; this.#pending.delete(normalized); this.#highestAck = normalized; return true; }
  expire(currentTick: Tick): readonly number[] { this.ensureLive(); const expired: number[] = []; for (const [sequence, pending] of this.#pending) if (currentTick >= pending.expiresTick) { pending.state = 'expired'; this.#pending.delete(sequence); this.#expired += 1; expired.push(sequence); } return Object.freeze(expired.sort((a, b) => a - b)); }
  snapshot(): AckTrackerSnapshot { return Object.freeze({ highest: this.#highestAck, pending: this.#pending.size, expired: this.#expired }); }
  dispose(): void { if (this.#disposed) return; this.#disposed = true; this.#pending.clear(); }
  private ensureLive(): void { if (this.#disposed) throw new Error('ack tracker disposed'); }
}

export interface RemoteClockEstimate { readonly offsetMs: number; readonly drift: number; readonly confidence: number; readonly sampleCount: number; }
export class RemoteClockEstimator {
  #offsetMs = 0; #drift = 0; #confidence = 0; #samples = 0; #lastLocal = 0; #lastRemote = 0;
  sample(localSendMs: number, localReceiveMs: number, remoteMs: number): RemoteClockEstimate { const roundTrip = Math.max(0, localReceiveMs - localSendMs); const midpoint = localSendMs + roundTrip * 0.5; const observedOffset = remoteMs - midpoint; const weight = this.#samples === 0 ? 1 : 0.15; this.#offsetMs += (observedOffset - this.#offsetMs) * weight; if (this.#samples > 0) { const localDelta = localReceiveMs - this.#lastLocal; const remoteDelta = remoteMs - this.#lastRemote; if (localDelta > 1) this.#drift += ((remoteDelta / localDelta) - 1 - this.#drift) * 0.1; } this.#lastLocal = localReceiveMs; this.#lastRemote = remoteMs; this.#samples += 1; this.#confidence = Math.min(1, this.#confidence + 0.1) * (roundTrip < 100 ? 1 : 0.9); return this.snapshot(); }
  remoteFromLocal(localMs: number): number { return localMs + this.#offsetMs + (localMs - this.#lastLocal) * this.#drift; }
  localFromRemote(remoteMs: number): number { return remoteMs - this.#offsetMs; }
  snapshot(): RemoteClockEstimate { return Object.freeze({ offsetMs: this.#offsetMs, drift: this.#drift, confidence: this.#confidence, sampleCount: this.#samples }); }
  reset(): void { this.#offsetMs = 0; this.#drift = 0; this.#confidence = 0; this.#samples = 0; this.#lastLocal = 0; this.#lastRemote = 0; }
}

export interface InterestSource { readonly id: string; readonly x: number; readonly y: number; readonly z: number; readonly radius: number; }
export interface InterestTarget { readonly id: string; readonly x: number; readonly y: number; readonly z: number; readonly importance: number; }
export interface InterestSet { readonly sourceId: string; readonly ids: readonly string[]; }
export const buildInterestSet = (source: InterestSource, targets: readonly InterestTarget[], maxDistance: number, maxEntities: number): InterestSet => { const limit = Math.max(0, maxDistance); const candidates = targets.map((target) => { const dx = target.x - source.x; const dy = target.y - source.y; const dz = target.z - source.z; const distanceSquared = dx * dx + dy * dy + dz * dz; return { target, distanceSquared, score: target.importance / Math.max(1, Math.sqrt(distanceSquared)) }; }).filter((item) => item.distanceSquared <= (limit + source.radius) ** 2); candidates.sort((a, b) => b.score - a.score || a.distanceSquared - b.distanceSquared || a.target.id.localeCompare(b.target.id)); return Object.freeze({ sourceId: source.id, ids: Object.freeze(candidates.slice(0, Math.max(1, Math.trunc(maxEntities))).map((item) => item.target.id)) }); };

export interface SnapshotEnvelope { readonly tick: Tick; readonly revision: number; readonly entities: readonly ReplicationEntityState[]; }
export interface SnapshotDelta { readonly tick: Tick; readonly revision: number; readonly added: readonly ReplicationEntityState[]; readonly changed: readonly ReplicationEntityDelta[]; readonly removed: readonly string[]; }
export const diffSnapshot = (previous: SnapshotEnvelope | null, next: SnapshotEnvelope): SnapshotDelta => { const before = new Map((previous?.entities ?? []).map((entity) => [entity.id, entity])); const after = new Map(next.entities.map((entity) => [entity.id, entity])); const added: ReplicationEntityState[] = []; const changed: ReplicationEntityDelta[] = []; const removed: string[] = []; for (const entity of next.entities) { const prior = before.get(entity.id); if (!prior) added.push(entity); else if (entity.revision > prior.revision) changed.push(diffEntityState(prior, entity)); } for (const entity of previous?.entities ?? []) if (!after.has(entity.id)) removed.push(entity.id); return Object.freeze({ tick: next.tick, revision: next.revision, added: Object.freeze(added), changed: Object.freeze(changed), removed: Object.freeze(removed.sort()) }); };
export const applySnapshotDelta = (previous: SnapshotEnvelope | null, delta: SnapshotDelta): Result<SnapshotEnvelope, string> => { const entities = new Map((previous?.entities ?? []).map((entity) => [entity.id, entity])); for (const id of delta.removed) entities.delete(id); for (const entity of delta.added) entities.set(entity.id, entity); for (const item of delta.changed) { const result = applyEntityDelta(entities.get(item.id) ?? null, item); if (!result.ok) return err(result.error); entities.set(item.id, result.value); } return ok(Object.freeze({ tick: delta.tick, revision: delta.revision, entities: Object.freeze([...entities.values()].sort((a, b) => a.id.localeCompare(b.id))) })); };

export interface ReplicationBudget { readonly maxEntitiesPerTick: number; readonly maxPacketsPerTick: number; readonly maxBytesPerTick: number; readonly maxResends: number; }
export const deriveReplicationBudget = (frameMs: number, packetLoss: number, entityCount: number): ReplicationBudget => { const quality = frameMs > 25 ? 0.65 : frameMs > 18 ? 0.82 : 1; const reliability = Math.max(0.4, 1 - Math.min(0.6, Math.max(0, packetLoss))); const maxEntitiesPerTick = Math.max(8, Math.min(2048, Math.trunc(entityCount * 0.15 * quality))); const maxPacketsPerTick = Math.max(4, Math.min(256, Math.trunc(64 * reliability * quality))); const maxBytesPerTick = Math.max(4096, Math.min(262144, Math.trunc(65536 * reliability * quality))); const maxResends = Math.max(0, Math.min(64, Math.trunc(12 * reliability))); return Object.freeze({ maxEntitiesPerTick, maxPacketsPerTick, maxBytesPerTick, maxResends }); };
