import type { ActorSnapshot, Stimulus, Vec3 } from './types.js';

export interface AdversarialCase {readonly id:string;readonly description:string;readonly actorHealth:number;readonly actorStamina:number;readonly danger:number;readonly stimulusCount:number;readonly expectedIntent:string;readonly expectedTier:'critical'|'high'|'normal'|'low'|'sleeping';readonly mustFailClosed:boolean;}

export const ADVERSARIAL_CASES:readonly AdversarialCase[]=Object.freeze([
 {id:'case-001',description:'zero-health actor with hostile stimulus',actorHealth:0,actorStamina:0,danger:1,stimulusCount:1,expectedIntent:'defend',expectedTier:'critical',mustFailClosed:false},
 {id:'case-002',description:'negative-health poison boundary',actorHealth:-1,actorStamina:40,danger:.7,stimulusCount:2,expectedIntent:'defend',expectedTier:'critical',mustFailClosed:true},
 {id:'case-003',description:'over-max-health imported save',actorHealth:130,actorStamina:50,danger:.1,stimulusCount:0,expectedIntent:'wait',expectedTier:'low',mustFailClosed:false},
 {id:'case-004',description:'NaN health payload',actorHealth:Number.NaN,actorStamina:50,danger:.4,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-005',description:'infinite stamina payload',actorHealth:50,actorStamina:Number.POSITIVE_INFINITY,danger:.2,stimulusCount:1,expectedIntent:'wait',expectedTier:'low',mustFailClosed:true},
 {id:'case-006',description:'critical danger and empty senses',actorHealth:60,actorStamina:60,danger:1,stimulusCount:0,expectedIntent:'flee',expectedTier:'critical',mustFailClosed:false},
 {id:'case-007',description:'critical danger with stale memory',actorHealth:60,actorStamina:60,danger:.98,stimulusCount:0,expectedIntent:'flee',expectedTier:'critical',mustFailClosed:false},
 {id:'case-008',description:'low danger with rich resources',actorHealth:90,actorStamina:80,danger:.1,stimulusCount:8,expectedIntent:'gather',expectedTier:'normal',mustFailClosed:false},
 {id:'case-009',description:'hostile faction at minimum range',actorHealth:80,actorStamina:60,danger:.82,stimulusCount:3,expectedIntent:'flee',expectedTier:'critical',mustFailClosed:false},
 {id:'case-010',description:'single audio cue beyond nominal range',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:1,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-011',description:'visual cue with occlusion',actorHealth:80,actorStamina:70,danger:.3,stimulusCount:4,expectedIntent:'investigate',expectedTier:'low',mustFailClosed:false},
 {id:'case-012',description:'damage stimulus dominates ambience',actorHealth:80,actorStamina:70,danger:.5,stimulusCount:6,expectedIntent:'defend',expectedTier:'high',mustFailClosed:false},
 {id:'case-013',description:'death stimulus near ally',actorHealth:70,actorStamina:70,danger:.45,stimulusCount:5,expectedIntent:'investigate',expectedTier:'high',mustFailClosed:false},
 {id:'case-014',description:'movement storm with low confidence',actorHealth:80,actorStamina:90,danger:.2,stimulusCount:32,expectedIntent:'investigate',expectedTier:'normal',mustFailClosed:false},
 {id:'case-015',description:'maximum configured stimuli flood',actorHealth:80,actorStamina:90,danger:.4,stimulusCount:128,expectedIntent:'investigate',expectedTier:'high',mustFailClosed:false},
 {id:'case-016',description:'negative stimulus count from hostile caller',actorHealth:80,actorStamina:90,danger:.4,stimulusCount:-8,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-017',description:'very high danger with zero stamina',actorHealth:75,actorStamina:0,danger:.9,stimulusCount:2,expectedIntent:'flee',expectedTier:'critical',mustFailClosed:false},
 {id:'case-018',description:'very low health but zero danger',actorHealth:4,actorStamina:70,danger:0,stimulusCount:0,expectedIntent:'rest',expectedTier:'low',mustFailClosed:false},
 {id:'case-019',description:'full health and full stamina in calm world',actorHealth:100,actorStamina:100,danger:0,stimulusCount:0,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-020',description:'full resources but hostile memory',actorHealth:100,actorStamina:100,danger:.8,stimulusCount:1,expectedIntent:'flee',expectedTier:'critical',mustFailClosed:false},
 {id:'case-021',description:'exactly threshold danger',actorHealth:60,actorStamina:50,danger:.78,stimulusCount:1,expectedIntent:'flee',expectedTier:'critical',mustFailClosed:false},
 {id:'case-022',description:'just below threshold danger',actorHealth:60,actorStamina:50,danger:.779,stimulusCount:1,expectedIntent:'defend',expectedTier:'high',mustFailClosed:false},
 {id:'case-023',description:'exactly minimum intent score',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'investigate',expectedTier:'low',mustFailClosed:false},
 {id:'case-024',description:'fractional tick payload',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'low',mustFailClosed:true},
 {id:'case-025',description:'negative tick payload',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-026',description:'huge safe integer tick',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'normal',mustFailClosed:false},
 {id:'case-027',description:'duplicate stimulus identifiers',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:10,expectedIntent:'investigate',expectedTier:'high',mustFailClosed:false},
 {id:'case-028',description:'expired stimulus set',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:10,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-029',description:'all stimuli identical intensity',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:16,expectedIntent:'investigate',expectedTier:'normal',mustFailClosed:false},
 {id:'case-030',description:'intensity above one',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:4,expectedIntent:'investigate',expectedTier:'high',mustFailClosed:true},
 {id:'case-031',description:'intensity below zero',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:4,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-032',description:'empty faction relation map',actorHealth:80,actorStamina:60,danger:.6,stimulusCount:2,expectedIntent:'defend',expectedTier:'high',mustFailClosed:false},
 {id:'case-033',description:'unknown faction reference',actorHealth:80,actorStamina:60,danger:.6,stimulusCount:2,expectedIntent:'wait',expectedTier:'low',mustFailClosed:true},
 {id:'case-034',description:'actor missing faction tag',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:1,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-035',description:'actor missing identifier',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:1,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-036',description:'null-like source identifier',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:1,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-037',description:'extreme position coordinates',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:2,expectedIntent:'investigate',expectedTier:'low',mustFailClosed:false},
 {id:'case-038',description:'NaN position coordinate',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-039',description:'infinite position coordinate',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-040',description:'zero-radius interest query',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:1,expectedIntent:'interact',expectedTier:'low',mustFailClosed:false},
 {id:'case-041',description:'negative-radius interest query',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:1,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-042',description:'massive-interest candidate flood',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:512,expectedIntent:'interact',expectedTier:'high',mustFailClosed:false},
 {id:'case-043',description:'all interest points unavailable',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:64,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-044',description:'critical interest within eight meters',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:8,expectedIntent:'interact',expectedTier:'critical',mustFailClosed:false},
 {id:'case-045',description:'resource-rich region with no actors',actorHealth:80,actorStamina:60,danger:.1,stimulusCount:12,expectedIntent:'gather',expectedTier:'normal',mustFailClosed:false},
 {id:'case-046',description:'resource-poor region at night',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:0,expectedIntent:'rest',expectedTier:'low',mustFailClosed:false},
 {id:'case-047',description:'full quest journal but blocked prerequisite',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:3,expectedIntent:'investigate',expectedTier:'normal',mustFailClosed:false},
 {id:'case-048',description:'completed objective receives duplicate event',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:1,expectedIntent:'interact',expectedTier:'low',mustFailClosed:false},
 {id:'case-049',description:'quest event with missing target id',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:1,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-050',description:'encounter at participant cap',actorHealth:80,actorStamina:60,danger:.55,stimulusCount:4,expectedIntent:'hunt',expectedTier:'high',mustFailClosed:false},
 {id:'case-051',description:'encounter beyond participant cap',actorHealth:80,actorStamina:60,danger:.55,stimulusCount:4,expectedIntent:'hunt',expectedTier:'high',mustFailClosed:false},
 {id:'case-052',description:'encounter cooldown exact boundary',actorHealth:80,actorStamina:60,danger:.55,stimulusCount:4,expectedIntent:'hunt',expectedTier:'normal',mustFailClosed:false},
 {id:'case-053',description:'encounter cooldown one tick early',actorHealth:80,actorStamina:60,danger:.55,stimulusCount:4,expectedIntent:'wait',expectedTier:'low',mustFailClosed:false},
 {id:'case-054',description:'unknown encounter definition',actorHealth:80,actorStamina:60,danger:.55,stimulusCount:4,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-055',description:'event journal duplicate id',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'investigate',expectedTier:'normal',mustFailClosed:true},
 {id:'case-056',description:'event journal over retention horizon',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-057',description:'event payload with unknown primitive',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'investigate',expectedTier:'low',mustFailClosed:true},
 {id:'case-058',description:'subscription with zero radius',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'investigate',expectedTier:'low',mustFailClosed:false},
 {id:'case-059',description:'subscription with invalid id',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-060',description:'blackboard stale write after newer write',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'investigate',expectedTier:'normal',mustFailClosed:false},
 {id:'case-061',description:'blackboard expired key read',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-062',description:'blackboard empty key',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-063',description:'memory store zero capacity request',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'investigate',expectedTier:'normal',mustFailClosed:false},
 {id:'case-064',description:'memory store negative decay rate',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'investigate',expectedTier:'low',mustFailClosed:true},
 {id:'case-065',description:'memory record missing subject',actorHealth:80,actorStamina:60,danger:.3,stimulusCount:2,expectedIntent:'investigate',expectedTier:'low',mustFailClosed:false},
 {id:'case-066',description:'goal prerequisite array with unknown key',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:3,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-067',description:'goal duration zero',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:3,expectedIntent:'wait',expectedTier:'low',mustFailClosed:true},
 {id:'case-068',description:'goal duration negative',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:3,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-069',description:'goal priority above one hundred',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:3,expectedIntent:'investigate',expectedTier:'normal',mustFailClosed:true},
 {id:'case-070',description:'goal priority below zero',actorHealth:80,actorStamina:60,danger:.2,stimulusCount:3,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-071',description:'faction hostile relation with peaceful goal',actorHealth:90,actorStamina:90,danger:.6,stimulusCount:2,expectedIntent:'protect',expectedTier:'high',mustFailClosed:false},
 {id:'case-072',description:'faction preferred goal collision',actorHealth:90,actorStamina:90,danger:.4,stimulusCount:2,expectedIntent:'patrol',expectedTier:'normal',mustFailClosed:false},
 {id:'case-073',description:'faction relation unknown actor faction',actorHealth:90,actorStamina:90,danger:.4,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-074',description:'actor disabled stance',actorHealth:90,actorStamina:90,danger:.4,stimulusCount:2,expectedIntent:'defend',expectedTier:'critical',mustFailClosed:false},
 {id:'case-075',description:'actor fleeing stance',actorHealth:40,actorStamina:20,danger:.9,stimulusCount:5,expectedIntent:'flee',expectedTier:'critical',mustFailClosed:false},
 {id:'case-076',description:'actor fearful stance with calm environment',actorHealth:80,actorStamina:60,danger:.05,stimulusCount:0,expectedIntent:'rest',expectedTier:'low',mustFailClosed:false},
 {id:'case-077',description:'actor hostile stance with ally-only nearby list',actorHealth:80,actorStamina:60,danger:.05,stimulusCount:0,expectedIntent:'patrol',expectedTier:'normal',mustFailClosed:false},
 {id:'case-078',description:'actor curious stance with discovery event',actorHealth:90,actorStamina:80,danger:.15,stimulusCount:1,expectedIntent:'investigate',expectedTier:'high',mustFailClosed:false},
 {id:'case-079',description:'actor calm stance with weather threat',actorHealth:90,actorStamina:80,danger:.15,stimulusCount:1,expectedIntent:'investigate',expectedTier:'normal',mustFailClosed:false},
 {id:'case-080',description:'weather signal at invalid intensity',actorHealth:90,actorStamina:80,danger:.15,stimulusCount:1,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-081',description:'snapshot restore with unknown actor',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'low',mustFailClosed:false},
 {id:'case-082',description:'snapshot restore with duplicate actor id',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-083',description:'snapshot restore malformed tick',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-084',description:'disposed runtime tick',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-085',description:'disposed blackboard write',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-086',description:'disposed interest broker publish',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-087',description:'disposed event journal append',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-088',description:'disposed quest manager update',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-089',description:'disposed encounter director evaluate',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-090',description:'large actor set bounded by config',actorHealth:90,actorStamina:80,danger:.2,stimulusCount:4,expectedIntent:'patrol',expectedTier:'normal',mustFailClosed:false},
 {id:'case-091',description:'large actor set with duplicate positions',actorHealth:90,actorStamina:80,danger:.6,stimulusCount:4,expectedIntent:'defend',expectedTier:'high',mustFailClosed:false},
 {id:'case-092',description:'large actor set with duplicate identifiers',actorHealth:90,actorStamina:80,danger:.6,stimulusCount:4,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:true},
 {id:'case-093',description:'simultaneous quest and combat events',actorHealth:60,actorStamina:50,danger:.75,stimulusCount:6,expectedIntent:'defend',expectedTier:'critical',mustFailClosed:false},
 {id:'case-094',description:'simultaneous resource and weather events',actorHealth:90,actorStamina:80,danger:.25,stimulusCount:6,expectedIntent:'gather',expectedTier:'normal',mustFailClosed:false},
 {id:'case-095',description:'simultaneous faction and death events',actorHealth:80,actorStamina:80,danger:.65,stimulusCount:6,expectedIntent:'investigate',expectedTier:'high',mustFailClosed:false},
 {id:'case-096',description:'decision interval skipped tick',actorHealth:80,actorStamina:80,danger:.4,stimulusCount:2,expectedIntent:'patrol',expectedTier:'normal',mustFailClosed:false},
 {id:'case-097',description:'decision interval exact tick',actorHealth:80,actorStamina:80,danger:.4,stimulusCount:2,expectedIntent:'investigate',expectedTier:'high',mustFailClosed:false},
 {id:'case-098',description:'maximum memory decay age',actorHealth:80,actorStamina:80,danger:.4,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-099',description:'maximum event retention age',actorHealth:80,actorStamina:80,danger:.4,stimulusCount:2,expectedIntent:'wait',expectedTier:'sleeping',mustFailClosed:false},
 {id:'case-100',description:'fully saturated world intelligence budget',actorHealth:80,actorStamina:80,danger:.9,stimulusCount:1024,expectedIntent:'flee',expectedTier:'critical',mustFailClosed:false},
]);

export function countFailClosedCases():number{return ADVERSARIAL_CASES.filter(c=>c.mustFailClosed).length;}
export function scenarioIds():readonly string[]{return Object.freeze(ADVERSARIAL_CASES.map(c=>c.id));}
export function validateScenarioMatrix():readonly string[]{const errors:string[]=[];const ids=new Set<string>();for(const c of ADVERSARIAL_CASES){if(ids.has(c.id))errors.push(`duplicate:${c.id}`);ids.add(c.id);if(!c.id||!c.description)errors.push(`identity:${c.id}`);if(c.actorHealth>100&&c.mustFailClosed===false&&c.actorHealth!==130)errors.push(`health-policy:${c.id}`);if(c.danger<0||c.danger>1)errors.push(`danger:${c.id}`);if(c.stimulusCount<0&&c.mustFailClosed===false)errors.push(`stimulus-policy:${c.id}`);}return Object.freeze(errors);}

export interface MinimalActorInput{readonly id:string;readonly health:number;readonly stamina:number;readonly maxHealth:number;readonly maxStamina:number;readonly alive:boolean;readonly faction:string;readonly stance:ActorSnapshot['stance'];readonly position:Vec3;}
export function sanitizeActorInput(input:MinimalActorInput):MinimalActorInput{const finite=(v:number,f:number)=>Number.isFinite(v)?v:f;return Object.freeze({...input,id:input.id.trim(),health:Math.max(0,Math.min(finite(input.health,0),Math.max(1,input.maxHealth))),stamina:Math.max(0,Math.min(finite(input.stamina,0),Math.max(1,input.maxStamina))),maxHealth:Math.max(1,finite(input.maxHealth,1)),maxStamina:Math.max(1,finite(input.maxStamina,1)),position:Object.freeze({x:finite(input.position.x,0),y:finite(input.position.y,0),z:finite(input.position.z,0)})});}
export function sanitizeStimulus(input:Stimulus):Stimulus{const finite=(v:number,f:number)=>Number.isFinite(v)?v:f;return Object.freeze({...input,radius:Math.max(0,finite(input.radius,0)),intensity:Math.min(1,Math.max(0,finite(input.intensity,0))),position:Object.freeze({x:finite(input.position.x,0),y:finite(input.position.y,0),z:finite(input.position.z,0)})});}
