import type { ActorSnapshot, EncounterCandidate, EncounterDefinition, Vec3 } from './types.js';
import { clamp01, distanceSq } from './types.js';
import { DeterministicRng, asSeed } from '../types/determinism.js';

export interface EncounterContext{readonly tick:number;readonly biomeTags:readonly string[];readonly factionTags:readonly string[];readonly weather:string;readonly danger:number;readonly population:number;readonly nearby:readonly ActorSnapshot[];readonly center:Vec3;}
export interface EncounterPolicy{readonly maxCandidates:number;readonly maxActive:number;readonly minimumScore:number;readonly densityRadius:number;readonly levelVariance:number;readonly seed:number;}
export interface ActiveEncounter{readonly id:string;readonly definitionId:string;readonly createdTick:number;readonly center:Vec3;readonly participants:readonly string[];readonly expiresTick:number;readonly intensity:number;}
export const defaultEncounterPolicy=():EncounterPolicy=>Object.freeze({maxCandidates:16,maxActive:8,minimumScore:.18,densityRadius:48,levelVariance:6,seed:1337});
const overlap=(a:readonly string[],b:readonly string[]):number=>{if(!a.length||!b.length)return 0;let hits=0;for(const x of a)if(b.includes(x))hits+=1;return hits/Math.max(a.length,b.length);};
const definitionScore=(d:EncounterDefinition,c:EncounterContext,level:number):number=>{const levelFit=1-clamp01(Math.abs(level-(d.minLevel+d.maxLevel)/2)/Math.max(1,(d.maxLevel-d.minLevel)/2+2));const biome=overlap(d.biomeTags,c.biomeTags);const faction=overlap(d.factionTags,c.factionTags);const dangerFit=d.id.includes('ambush')?c.danger:d.id.includes('peace')?1-c.danger:.5;const density=1-clamp01(c.population/Math.max(1,d.maxParticipants*2));return clamp01(levelFit*.35+biome*.25+faction*.15+dangerFit*.15+density*.1);};
export function scoreEncounters(definitions:readonly EncounterDefinition[],context:EncounterContext,level:number,policy=defaultEncounterPolicy()):readonly EncounterCandidate[]{const rng=new DeterministicRng(asSeed(policy.seed));return Object.freeze([...definitions].map((d,i)=>{const score=definitionScore(d,context,level)+rng.fork(`${d.id}:${i}`).float(0,.0001);return Object.freeze({id:`encounter-candidate:${d.id}:${i}`,position:context.center,definitionId:d.id,score,reason:`level=${level};biome=${overlap(d.biomeTags,context.biomeTags).toFixed(2)};faction=${overlap(d.factionTags,context.factionTags).toFixed(2)}`});}).filter(c=>c.score>=policy.minimumScore).sort((a,b)=>b.score-a.score||a.definitionId.localeCompare(b.definitionId)).slice(0,policy.maxCandidates));}
export class EncounterDirector{
 readonly #definitions=new Map<string,EncounterDefinition>();readonly #active=new Map<string,ActiveEncounter>();readonly #cooldowns=new Map<string,number>();readonly #policy:EncounterPolicy;#disposed=false;
 constructor(definitions:readonly EncounterDefinition[]=[],policy=defaultEncounterPolicy()){this.#policy=Object.freeze({...policy});for(const d of definitions)this.register(d);}
 register(d:EncounterDefinition):void{if(this.#disposed)return;if(this.#definitions.has(d.id))throw new Error(`Encounter exists: ${d.id}`);this.#definitions.set(d.id,Object.freeze({...d,biomeTags:Object.freeze([...d.biomeTags]),factionTags:Object.freeze([...d.factionTags]),weights:Object.freeze({...d.weights})}));}
 evaluate(context:EncounterContext,level:number):readonly EncounterCandidate[]{if(this.#disposed)return [];return scoreEncounters(this.#available(),context,level,this.#policy);}
 spawn(candidate:EncounterCandidate,tick:number,participants:readonly ActorSnapshot[],durationTicks=180):ActiveEncounter|undefined{if(this.#disposed||this.#active.size>=this.#policy.maxActive)return undefined;const d=this.#definitions.get(candidate.definitionId);if(!d||Number(this.#cooldowns.get(d.id)??0)>tick)return undefined;const chosen=participants.filter(a=>a.alive).sort((a,b)=>distanceSq(a.position,candidate.position)-distanceSq(b.position,candidate.position)||String(a.id).localeCompare(String(b.id))).slice(0,d.maxParticipants);const id=`${candidate.definitionId}:${tick}:${this.#active.size}`;const encounter=Object.freeze({id,definitionId:d.id,createdTick:tick,center:candidate.position,participants:Object.freeze(chosen.map(a=>String(a.id))),expiresTick:tick+Math.max(1,durationTicks),intensity:clamp01(candidate.score)});this.#active.set(id,encounter);this.#cooldowns.set(d.id,tick+Math.max(0,d.cooldownTicks));return encounter;}
 expire(tick:number):number{let n=0;for(const [id,e] of this.#active)if(tick>=e.expiresTick){this.#active.delete(id);n+=1;}return n;}
 get active():readonly ActiveEncounter[]{return Object.freeze([...this.#active.values()].sort((a,b)=>a.id.localeCompare(b.id)));}
 remove(id:string):boolean{return this.#active.delete(id);}
 dispose():void{this.#disposed=true;this.#definitions.clear();this.#active.clear();this.#cooldowns.clear();}
 #available():EncounterDefinition[]{return [...this.#definitions.values()].filter(d=>!this.#cooldowns.has(d.id));}
}
export function selectEncounterParticipants(actors:readonly ActorSnapshot[],center:Vec3,max:number,preferredFaction?:string):readonly ActorSnapshot[]{return Object.freeze([...actors].filter(a=>a.alive&&(!preferredFaction||String(a.faction)===preferredFaction)).sort((a,b)=>distanceSq(a.position,center)-distanceSq(b.position,center)||String(a.id).localeCompare(String(b.id))).slice(0,Math.max(0,max)));}
export function encounterPressure(active:readonly ActiveEncounter[],position:Vec3):number{let value=0;for(const e of active){const d=Math.sqrt(distanceSq(e.center,position));if(d>64)continue;value+=e.intensity*(1-d/64);}return clamp01(value);}
