export const POLICY_MATRIX = Object.freeze([
  { id:'runtime-001', domain:'perception', name:'distance-clamp', limit:96, fallback:0, priority:10 },
  { id:'runtime-002', domain:'perception', name:'stimulus-cap', limit:32, fallback:0, priority:10 },
  { id:'runtime-003', domain:'perception', name:'confidence-floor', limit:.08, fallback:0, priority:9 },
  { id:'runtime-004', domain:'perception', name:'occlusion-fallback', limit:1, fallback:.65, priority:8 },
  { id:'runtime-005', domain:'perception', name:'memory-half-life', limit:32, fallback:32, priority:7 },
  { id:'runtime-006', domain:'decision', name:'goal-cap', limit:8, fallback:4, priority:10 },
  { id:'runtime-007', domain:'decision', name:'intent-cap', limit:4, fallback:1, priority:10 },
  { id:'runtime-008', domain:'decision', name:'intent-floor', limit:.12, fallback:.12, priority:9 },
  { id:'runtime-009', domain:'decision', name:'emergency-danger', limit:.78, fallback:.78, priority:10 },
  { id:'runtime-010', domain:'decision', name:'interrupt-margin', limit:.2, fallback:.2, priority:8 },
  { id:'runtime-011', domain:'interest', name:'candidate-cap', limit:24, fallback:8, priority:9 },
  { id:'runtime-012', domain:'interest', name:'radius', limit:96, fallback:64, priority:9 },
  { id:'runtime-013', domain:'interest', name:'critical-radius', limit:18, fallback:12, priority:8 },
  { id:'runtime-014', domain:'interest', name:'heat-cap', limit:256, fallback:64, priority:6 },
  { id:'runtime-015', domain:'events', name:'event-cap', limit:1024, fallback:128, priority:10 },
  { id:'runtime-016', domain:'events', name:'per-tick-cap', limit:64, fallback:16, priority:10 },
  { id:'runtime-017', domain:'events', name:'retention', limit:720, fallback:180, priority:7 },
  { id:'runtime-018', domain:'events', name:'payload-key-cap', limit:24, fallback:12, priority:8 },
  { id:'runtime-019', domain:'quests', name:'quest-cap', limit:128, fallback:32, priority:8 },
  { id:'runtime-020', domain:'quests', name:'objective-floor', limit:1, fallback:1, priority:7 },
  { id:'runtime-021', domain:'encounters', name:'candidate-cap', limit:16, fallback:8, priority:8 },
  { id:'runtime-022', domain:'encounters', name:'active-cap', limit:8, fallback:4, priority:9 },
  { id:'runtime-023', domain:'encounters', name:'participant-cap', limit:12, fallback:4, priority:9 },
  { id:'runtime-024', domain:'encounters', name:'minimum-score', limit:.18, fallback:.18, priority:6 },
  { id:'runtime-025', domain:'runtime', name:'actor-cap', limit:128, fallback:64, priority:10 },
  { id:'runtime-026', domain:'runtime', name:'memory-cap', limit:256, fallback:64, priority:10 },
  { id:'runtime-027', domain:'runtime', name:'goal-cap', limit:16, fallback:8, priority:8 },
  { id:'runtime-028', domain:'runtime', name:'decision-interval', limit:6, fallback:6, priority:8 },
  { id:'runtime-029', domain:'runtime', name:'event-retention', limit:720, fallback:180, priority:7 },
  { id:'runtime-030', domain:'safety', name:'nan-fallback', limit:0, fallback:0, priority:10 },
  { id:'runtime-031', domain:'safety', name:'infinity-fallback', limit:1, fallback:0, priority:10 },
  { id:'runtime-032', domain:'safety', name:'negative-radius', limit:0, fallback:0, priority:10 },
  { id:'runtime-033', domain:'safety', name:'stale-tick', limit:0, fallback:0, priority:10 },
  { id:'runtime-034', domain:'safety', name:'duplicate-id', limit:0, fallback:0, priority:10 },
  { id:'runtime-035', domain:'safety', name:'disposed-write', limit:0, fallback:0, priority:10 },
  { id:'runtime-036', domain:'safety', name:'disposed-read', limit:0, fallback:0, priority:9 },
  { id:'runtime-037', domain:'safety', name:'disposed-publish', limit:0, fallback:0, priority:9 },
  { id:'runtime-038', domain:'safety', name:'disposed-event', limit:0, fallback:0, priority:9 },
  { id:'runtime-039', domain:'safety', name:'disposed-quest', limit:0, fallback:0, priority:9 },
  { id:'runtime-040', domain:'safety', name:'disposed-encounter', limit:0, fallback:0, priority:9 },
  { id:'runtime-041', domain:'replay', name:'sorted-events', limit:1, fallback:1, priority:8 },
  { id:'runtime-042', domain:'replay', name:'stable-ids', limit:1, fallback:1, priority:9 },
  { id:'runtime-043', domain:'replay', name:'snapshot-order', limit:1, fallback:1, priority:10 },
  { id:'runtime-044', domain:'replay', name:'rng-seed', limit:4294967295, fallback:1, priority:9 },
  { id:'runtime-045', domain:'replay', name:'replay-tick', limit:Number.MAX_SAFE_INTEGER, fallback:0, priority:10 },
  { id:'runtime-046', domain:'performance', name:'interest-scan', limit:512, fallback:64, priority:8 },
  { id:'runtime-047', domain:'performance', name:'event-scan', limit:1024, fallback:128, priority:8 },
  { id:'runtime-048', domain:'performance', name:'actor-scan', limit:128, fallback:64, priority:10 },
  { id:'runtime-049', domain:'performance', name:'stimulus-scan', limit:256, fallback:64, priority:10 },
  { id:'runtime-050', domain:'performance', name:'quest-scan', limit:128, fallback:32, priority:8 },
]);

export function normalizePolicyValue(policyId:string,value:number):number{const policy=POLICY_MATRIX.find(p=>p.id===policyId);if(!policy)return 0;if(!Number.isFinite(value))return Number(policy.fallback);return Math.max(0,Math.min(Number(policy.limit),value));}
export function enabledPolicies(domain:string):readonly string[]{return Object.freeze(POLICY_MATRIX.filter(p=>p.domain===domain).sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id)).map(p=>p.id));}
export function validatePolicyMatrix():readonly string[]{const errors:string[]=[];const ids=new Set<string>();for(const p of POLICY_MATRIX){if(ids.has(p.id))errors.push(`duplicate:${p.id}`);ids.add(p.id);if(!p.domain||!p.name)errors.push(`identity:${p.id}`);if(!Number.isFinite(p.priority))errors.push(`priority:${p.id}`);if(typeof p.limit!=='number'||typeof p.fallback!=='number')errors.push(`numeric:${p.id}`);}return Object.freeze(errors);}
