import { describe, expect, it } from 'vitest';
import { WorldIntelligence, createEvent, createStimulus, normalizeConfig, type ActorSnapshot, type FactionProfile, type Goal } from './worldIntelligence.js';

const actor=(id:string,faction='wardens'):ActorSnapshot=>Object.freeze({id:id as never,position:{x:0,y:0,z:0},health:80,maxHealth:100,stamina:75,maxStamina:100,faction:faction as never,stance:'calm',alive:true,level:10,tags:['road']});
const faction:FactionProfile=Object.freeze({id:'wardens' as never,name:'Wardens',power:90,relations:{raiders:'hostile'},preferredGoals:['protect','patrol'],territoryTags:['road']});
const goals:readonly Goal[]=Object.freeze([{id:'protect',kind:'protect',priority:80,durationTicks:10,prerequisites:[],cooldownTicks:5,interruptible:true},{id:'flee',kind:'flee',priority:50,durationTicks:6,prerequisites:[],cooldownTicks:3,interruptible:true},{id:'investigate',kind:'investigate',priority:60,durationTicks:8,prerequisites:[],cooldownTicks:3,interruptible:true}]);

describe('world intelligence runtime',()=>{
 it('normalizes hostile configuration safely',()=>{const c=normalizeConfig({actorCap:-4,stimulusCap:Number.NaN,decisionInterval:0,memoryHalfLife:-2});expect(c.actorCap).toBeGreaterThan(0);expect(c.stimulusCap).toBeGreaterThan(0);expect(c.decisionInterval).toBeGreaterThan(0);expect(c.memoryHalfLife).toBeGreaterThan(0);});
 it('returns a deterministic result for identical inputs',()=>{const first=new WorldIntelligence({seed:42});const second=new WorldIntelligence({seed:42});first.registerFaction(faction);second.registerFaction(faction);first.registerActor(actor('a'),goals);second.registerActor(actor('a'),goals);const stimulus=createStimulus('s','damage',6,{x:4,y:0,z:0},.8,8,['combat']);const a=first.tick({tick:6,actors:[actor('a'),actor('b','raiders')],stimuli:[stimulus],events:[createEvent('e','combat',6,{x:4,y:0,z:0},8,.8,{outcome:'defeat'},['combat'])]});const b=second.tick({tick:6,actors:[actor('a'),actor('b','raiders')],stimuli:[stimulus],events:[createEvent('e','combat',6,{x:4,y:0,z:0},8,.8,{outcome:'defeat'},['combat'])]});expect(JSON.stringify(a)).toBe(JSON.stringify(b));});
 it('caps hot-path actor processing',()=>{const runtime=new WorldIntelligence({actorCap:2});runtime.registerFaction(faction);const actors=[actor('a1'),actor('a2'),actor('a3'),actor('a4')];for(const a of actors)runtime.registerActor(a,goals);const result=runtime.tick({tick:6,actors,stimuli:[]});expect(result.metrics.actors).toBe(2);expect(result.metrics.budgetDrops).toBe(2);});
 it('deduplicates event ids',()=>{const runtime=new WorldIntelligence();runtime.registerFaction(faction);runtime.addEvent(createEvent('same','combat',1,{x:0,y:0,z:0},2,.5));runtime.addEvent(createEvent('same','combat',1,{x:0,y:0,z:0},2,.5));expect(runtime.getEvents().size).toBe(1);});
 it('fails closed after disposal',()=>{const runtime=new WorldIntelligence();runtime.registerFaction(faction);runtime.registerActor(actor('a'),goals);runtime.dispose();const result=runtime.tick({tick:1,actors:[actor('a')],stimuli:[]});expect(result.intents).toEqual([]);expect(result.interests).toEqual([]);});
 it('expires stale memories by confidence decay',()=>{const runtime=new WorldIntelligence({memoryHalfLife:2});runtime.registerFaction(faction);runtime.registerActor(actor('a'),goals);const stimulus=createStimulus('old','visual',1,{x:2,y:0,z:0},.2,10);runtime.tick({tick:1,actors:[actor('a')],stimuli:[stimulus]});for(let t=2;t<20;t+=1)runtime.tick({tick:t,actors:[actor('a')],stimuli:[]});const snapshot=runtime.snapshot();expect(snapshot.actors).toHaveLength(1);});
 it('keeps interest output bounded and stable',()=>{const runtime=new WorldIntelligence({interestCap:4});runtime.registerFaction(faction);runtime.registerActor(actor('a'),goals);for(let i=0;i<20;i+=1)runtime.addInterest({id:`p${i}`,position:{x:i,y:0,z:0},importance:1-i/40,tags:['road'],available:true});const result=runtime.tick({tick:6,actors:[actor('a')],stimuli:[]});expect(result.interests.length).toBeLessThanOrEqual(4);expect(result.interests.map(x=>x.id)).toEqual([...result.interests].map(x=>x.id));});
});
