/** Typed deterministic day/night lighting and celestial presentation owner. */
import * as THREE from 'three';
import {installNightVisualEnhancement,updateNightVisualEnhancement} from './nightVisualEnhancement.ts';
import {AssetLoader} from './assetLoader.js';
import {publishCelestialLightState,type CelestialLightState} from './celestialLightState.ts';
import {GEOGRAPHIC_REFERENCE_PALETTE_POLICY} from './world/geographicReferencePalette.js';
interface Keyframe{readonly ratio:number;readonly sunColor:number;readonly sunIntensity:number;readonly hemiSky:number;readonly hemiGround:number;readonly hemiIntensity:number;readonly nightFactor:number;}
const KEYFRAMES:readonly Keyframe[]=Object.freeze([
 {ratio:0,sunColor:0x233a66,sunIntensity:0,hemiSky:0x101b38,hemiGround:0x080b13,hemiIntensity:.28,nightFactor:1},
 {ratio:.22,sunColor:0x344b70,sunIntensity:.03,hemiSky:0x142244,hemiGround:0x0a0d16,hemiIntensity:.3,nightFactor:1},
 {ratio:.27,sunColor:0xffb366,sunIntensity:.9,hemiSky:0x8b6b59,hemiGround:0x302117,hemiIntensity:.62,nightFactor:.35},
 {ratio:.5,sunColor:0xfff2d8,sunIntensity:1.4,hemiSky:0xb9d8ed,hemiGround:0x413a2a,hemiIntensity:1.1,nightFactor:0},
 {ratio:.73,sunColor:0xff8c52,sunIntensity:.85,hemiSky:0x9b6655,hemiGround:0x301b12,hemiIntensity:.58,nightFactor:.35},
 {ratio:.78,sunColor:0x344b70,sunIntensity:.03,hemiSky:0x142244,hemiGround:0x0a0d16,hemiIntensity:.3,nightFactor:1},
 {ratio:1,sunColor:0x233a66,sunIntensity:0,hemiSky:0x101b38,hemiGround:0x080b13,hemiIntensity:.28,nightFactor:1},
]);
const SKY_DAY={horizon:new THREE.Color(0xaed7ee),zenith:new THREE.Color(0x2f72ad)},SKY_NIGHT={horizon:new THREE.Color(0x263752),zenith:new THREE.Color(0x071127)},SKY_TWILIGHT={horizon:new THREE.Color(0xe59a6d),zenith:new THREE.Color(0x4d6086)};
const ORBIT_RADIUS_METERS=900,CELESTIAL_VISUAL_SCALE=18,NIGHT_READABILITY_LIGHT_NAME='Game Night Readability Fill',NIGHT_READABILITY_DAY_INTENSITY=.05,NIGHT_READABILITY_NIGHT_INTENSITY=.36,MOON_MAX_INTENSITY=.55,CELESTIAL_HORIZON_FADE_METERS=25,CELESTIAL_FULL_ALTITUDE_METERS=ORBIT_RADIUS_METERS*.22,TWILIGHT_FULL_ALTITUDE_METERS=ORBIT_RADIUS_METERS*.3;
export const CELESTIAL_ASSET_POLICY=Object.freeze({id:'celestial-asset-policy-2026-08-22-v2',moonRepositoryPath:'assets/models/Ay/Moon 2K.fbx',moonAssetUrl:'assets/models/Ay/Moon%202K.fbx',moonTargetDiameterMeters:CELESTIAL_VISUAL_SCALE*2,moonLightingAltitudeModulated:true,sunLightingAltitudeModulated:true,twilightSkyAltitudeModulated:true});
export const CELESTIAL_GEOGRAPHIC_RESPONSE_POLICY=Object.freeze({id:'celestial-geographic-response-2026-08-28-v1',referencePalettePolicyId:GEOGRAPHIC_REFERENCE_PALETTE_POLICY.id,eastZenithWestSunOrbit:true,oppositeMoonOrbit:true,altitudeModulatedIllumination:true,waterNightResponsePublished:true,materialAuthorityUnchanged:true});
export interface DayNightLighting{readonly sun:THREE.DirectionalLight;readonly moon:THREE.DirectionalLight;readonly hemisphere:THREE.HemisphereLight;readonly sunVisual:THREE.Group;readonly moonVisual:THREE.Group;readonly moonAssetReady:Promise<CelestialAssetStatus>;}
export interface CelestialAssetStatus{readonly policy:string;readonly assetUrl:string;readonly status:string;readonly meshCount?:number;readonly error?:string;}
export interface DayNightLightingUpdate{readonly timeRatio:number;readonly nightFactor:number;readonly twilightFactor:number;readonly sunAltitudeFactor:number;readonly moonAltitudeFactor:number;readonly celestialKey:CelestialLightState;readonly horizonColor:THREE.Color;readonly zenithColor:THREE.Color;}
function smoothstep(edge0:number,edge1:number,value:number):number{if(edge0===edge1)return value>=edge1?1:0;const t=Math.max(0,Math.min(1,(value-edge0)/(edge1-edge0)));return t*t*(3-2*t);}
export function celestialAltitudeWeightFromY(worldY:number):number{return smoothstep(-CELESTIAL_HORIZON_FADE_METERS,CELESTIAL_FULL_ALTITUDE_METERS,worldY);}
function twilightWeightFromSunY(sunY:number):number{return 1-smoothstep(0,TWILIGHT_FULL_ALTITUDE_METERS,Math.abs(sunY));}
function findKeyframeSegment(ratio:number):{readonly a:Keyframe;readonly b:Keyframe;readonly t:number}{for(let i=0;i<KEYFRAMES.length-1;i+=1){const a=KEYFRAMES[i],b=KEYFRAMES[i+1];if(ratio>=a.ratio&&ratio<=b.ratio){const span=b.ratio-a.ratio;return{a,b,t:span>0?(ratio-a.ratio)/span:0};}}return{a:KEYFRAMES[0],b:KEYFRAMES[0],t:0};}
const scratchColorA=new THREE.Color(),scratchColorB=new THREE.Color();
function makeCelestialSphere(name:string,color:number,scale=CELESTIAL_VISUAL_SCALE):THREE.Mesh<THREE.SphereGeometry,THREE.MeshBasicMaterial>{const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),new THREE.MeshBasicMaterial({color,toneMapped:false,fog:false}));mesh.name=name;mesh.scale.setScalar(scale);mesh.frustumCulled=false;mesh.renderOrder=-10;return mesh;}
function fitObjectToDiameter(object:THREE.Object3D,diameter:number):boolean{const box=new THREE.Box3().setFromObject(object),size=new THREE.Vector3();box.getSize(size);const largest=Math.max(size.x,size.y,size.z);if(!(largest>1e-6))return false;object.scale.multiplyScalar(diameter/largest);object.updateMatrixWorld(true);box.setFromObject(object);object.position.sub(box.getCenter(new THREE.Vector3()));object.updateMatrixWorld(true);return true;}
function setMoonAssetStatus(moonAnchor:THREE.Group,status:string,detail:Record<string,unknown>={}):CelestialAssetStatus{const value:CelestialAssetStatus=Object.freeze({policy:CELESTIAL_ASSET_POLICY.id,assetUrl:CELESTIAL_ASSET_POLICY.moonAssetUrl,status,...detail});moonAnchor.userData.celestialAsset=value;return value;}
interface LoadedFbx extends THREE.Object3D{readonly animations?:readonly THREE.AnimationClip[];readonly userData:Record<string,unknown>;}
function installMoonAssetAsync(moonAnchor:THREE.Group):Promise<CelestialAssetStatus>{const loader=new AssetLoader();setMoonAssetStatus(moonAnchor,'loading');return(loader.loadFBXModel(CELESTIAL_ASSET_POLICY.moonAssetUrl,{fallbackColor:0xdbe8ff,fallbackSize:2}) as Promise<LoadedFbx>).then(model=>{if(!moonAnchor.parent)return setMoonAssetStatus(moonAnchor,'detached');if(model.userData?.isPlaceholder)return setMoonAssetStatus(moonAnchor,'fallback-placeholder');if(!fitObjectToDiameter(model,CELESTIAL_ASSET_POLICY.moonTargetDiameterMeters))return setMoonAssetStatus(moonAnchor,'fallback-empty-model');let meshCount=0;model.traverse(node=>{if(!node.isMesh)return;meshCount+=1;node.castShadow=false;node.receiveShadow=false;});if(meshCount===0)return setMoonAssetStatus(moonAnchor,'fallback-empty-model');moonAnchor.clear();moonAnchor.add(model);return setMoonAssetStatus(moonAnchor,'active',{meshCount});}).catch((error:unknown)=>setMoonAssetStatus(moonAnchor,'fallback-error',{error:error instanceof Error?error.message:String(error)}));}
export function createDayNightLighting(scene:THREE.Scene):DayNightLighting{const sun=new THREE.DirectionalLight(0xffffff,1);sun.name='Sun Directional Light';sun.userData.altitudeModulated=true;sun.userData.geographicResponsePolicyId=CELESTIAL_GEOGRAPHIC_RESPONSE_POLICY.id;const moon=new THREE.DirectionalLight(0xc8dcff,0);moon.name='Moon Directional Light';moon.userData.altitudeModulated=true;moon.userData.geographicResponsePolicyId=CELESTIAL_GEOGRAPHIC_RESPONSE_POLICY.id;const hemisphere=new THREE.HemisphereLight(0xffffff,0x000000,1),sunVisual=new THREE.Group(),moonVisual=new THREE.Group();sunVisual.name='Sun Visual';sunVisual.add(makeCelestialSphere('Sun Disc',0xffe2a1));moonVisual.name='Moon Visual';moonVisual.add(makeCelestialSphere('Moon Fallback Disc',0xdbe8ff,CELESTIAL_VISUAL_SCALE*.72));scene.add(sun,moon,hemisphere,sunVisual,moonVisual);const readability=new THREE.HemisphereLight(0xaed9ff,0x465366,NIGHT_READABILITY_DAY_INTENSITY);readability.name=NIGHT_READABILITY_LIGHT_NAME;readability.userData.gameNightReadability=true;hemisphere.add(readability);installNightVisualEnhancement(hemisphere);const moonAssetReady=installMoonAssetAsync(moonVisual);return Object.freeze({sun,moon,hemisphere,sunVisual,moonVisual,moonAssetReady});}
export function updateDayNightLighting(lights:DayNightLighting,elapsedSeconds:number,dayLengthSeconds:number,startRatio:number):DayNightLightingUpdate{const safeDayLength=Math.max(.001,Number(dayLengthSeconds)||1),timeRatio=((elapsedSeconds/safeDayLength+startRatio)%1+1)%1,{a,b,t}=findKeyframeSegment(timeRatio);scratchColorA.set(a.sunColor);scratchColorB.set(b.sunColor);lights.sun.color.copy(scratchColorA).lerp(scratchColorB,t);const baseSunIntensity=a.sunIntensity+(b.sunIntensity-a.sunIntensity)*t;scratchColorA.set(a.hemiSky);scratchColorB.set(b.hemiSky);lights.hemisphere.color.copy(scratchColorA).lerp(scratchColorB,t);scratchColorA.set(a.hemiGround);scratchColorB.set(b.hemiGround);lights.hemisphere.groundColor.copy(scratchColorA).lerp(scratchColorB,t);lights.hemisphere.intensity=a.hemiIntensity+(b.hemiIntensity-a.hemiIntensity)*t;const nightFactor=a.nightFactor+(b.nightFactor-a.nightFactor)*t,smoothNightFactor=nightFactor*nightFactor*(3-2*nightFactor),readability=lights.hemisphere.getObjectByName(NIGHT_READABILITY_LIGHT_NAME);if(readability?.isHemisphereLight)readability.intensity=NIGHT_READABILITY_DAY_INTENSITY+(NIGHT_READABILITY_NIGHT_INTENSITY-NIGHT_READABILITY_DAY_INTENSITY)*smoothNightFactor;updateNightVisualEnhancement(lights.hemisphere,nightFactor);const angle=(timeRatio-.25)*Math.PI*2,sunX=Math.cos(angle)*ORBIT_RADIUS_METERS,sunY=Math.sin(angle)*ORBIT_RADIUS_METERS,sunZ=Math.sin(angle*.35)*ORBIT_RADIUS_METERS*.12,sunAltitudeFactor=celestialAltitudeWeightFromY(sunY);lights.sun.position.set(sunX,sunY,sunZ);lights.sun.intensity=baseSunIntensity*sunAltitudeFactor;lights.sun.userData.baseIntensity=baseSunIntensity;lights.sun.userData.altitudeFactor=sunAltitudeFactor;lights.sunVisual.position.copy(lights.sun.position);const moonY=-sunY,moonAltitudeFactor=celestialAltitudeWeightFromY(moonY);lights.moon.position.set(-sunX,moonY,-sunZ);lights.moon.intensity=MOON_MAX_INTENSITY*smoothNightFactor*moonAltitudeFactor;lights.moon.userData.altitudeFactor=moonAltitudeFactor;lights.moonVisual.position.set(-sunX,moonY,-sunZ);lights.moonVisual.visible=moonY>-CELESTIAL_HORIZON_FADE_METERS&&smoothNightFactor>.08;lights.sunVisual.visible=sunY>-CELESTIAL_HORIZON_FADE_METERS;const celestialKey=publishCelestialLightState({sunPosition:lights.sun.position,sunColor:lights.sun.color,sunIntensity:lights.sun.intensity,moonPosition:lights.moon.position,moonColor:lights.moon.color,moonIntensity:lights.moon.intensity,nightFactor});const twilightFactor=twilightWeightFromSunY(sunY),daylightFactor=1-smoothNightFactor,horizonColor=SKY_NIGHT.horizon.clone().lerp(SKY_DAY.horizon,daylightFactor).lerp(SKY_TWILIGHT.horizon,twilightFactor*.68),zenithColor=SKY_NIGHT.zenith.clone().lerp(SKY_DAY.zenith,daylightFactor).lerp(SKY_TWILIGHT.zenith,twilightFactor*.24);return Object.freeze({timeRatio,nightFactor,twilightFactor,sunAltitudeFactor,moonAltitudeFactor,celestialKey,horizonColor,zenithColor});}
export function disposeDayNightLighting(scene:THREE.Scene,lights:DayNightLighting):void{for(const node of [lights.sun,lights.moon,lights.hemisphere,lights.sunVisual,lights.moonVisual]){scene.remove(node);node.traverse(child=>{child.geometry?.dispose?.();if(Array.isArray(child.material))child.material.forEach(material=>material.dispose?.());else child.material?.dispose?.();});}}
