import type { Disposable, InputBinding, InputFrame, PointerState } from './types';
import { asTimestampMs } from './types';
interface ActionState { pressed: boolean; justPressed: boolean; justReleased: boolean; value: number; }
interface StoredPointer extends PointerState { lastDown: boolean; }

export class InputManager implements Disposable {
  private readonly target: Window | HTMLElement | null; private readonly actions = new Map<string, ActionState>(); private readonly bindings: InputBinding[] = []; private readonly keys = new Set<string>(); private readonly pointers = new Map<number, StoredPointer>(); private readonly abort = new AbortController(); private disposed = false;
  public constructor(target: Window | HTMLElement | null = typeof window !== 'undefined' ? window : null) { this.target = target; this.attach(); }
  public bind(binding: InputBinding): Disposable { this.ensureActive(); const copy: InputBinding = binding.keys ? { ...binding, keys: binding.keys.map(normalizeKey) } : { ...binding }; this.bindings.push(copy); if (!this.actions.has(copy.action)) this.actions.set(copy.action, { pressed:false, justPressed:false, justReleased:false, value:0 }); return { dispose: () => { const index = this.bindings.indexOf(copy); if (index >= 0) this.bindings.splice(index,1); } }; }
  public action(name: string): Readonly<ActionState> { return Object.freeze({ ...(this.actions.get(name) ?? { pressed:false, justPressed:false, justReleased:false, value:0 }) }); }
  public axis(name: string): number { return this.actions.get(name)?.value ?? 0; }
  public beginFrame(): void { for (const action of this.actions.values()) { action.justPressed=false; action.justReleased=false; } for (const [id,p] of this.pointers) this.pointers.set(id,{...p,lastDown:p.down}); }
  public snapshot(timestamp = Date.now()): InputFrame { this.recompute(); return Object.freeze({ timestamp: asTimestampMs(timestamp), axes: Object.fromEntries([...this.actions].map(([k,v])=>[k,v.value])), buttons: Object.fromEntries([...this.actions].map(([k,v])=>[k,v.pressed])), pointers: [...this.pointers.values()].map(({lastDown:_unused,...p})=>p) }); }
  private recompute(): void { for (const binding of this.bindings) { const state=this.actions.get(binding.action); if(!state) continue; const held=(binding.keys ?? []).some(k=>this.keys.has(normalizeKey(k))); const previous=state.pressed; state.pressed=held; state.value=held?(binding.sensitivity ?? 1):0; state.justPressed=state.pressed&&!previous; state.justReleased=!state.pressed&&previous; } }
  private attach(): void { if(!this.target) return; const options={signal:this.abort.signal}; this.target.addEventListener('keydown',this.onKeyDown as EventListener,options); this.target.addEventListener('keyup',this.onKeyUp as EventListener,options); this.target.addEventListener('blur',this.onBlur as EventListener,options); this.target.addEventListener('pointerdown',this.onPointerDown as EventListener,options); this.target.addEventListener('pointermove',this.onPointerMove as EventListener,options); this.target.addEventListener('pointerup',this.onPointerUp as EventListener,options); this.target.addEventListener('pointercancel',this.onPointerUp as EventListener,options); }
  private onKeyDown=(event:KeyboardEvent):void=>{this.keys.add(normalizeKey(event.key));}; private onKeyUp=(event:KeyboardEvent):void=>{this.keys.delete(normalizeKey(event.key));}; private onBlur=():void=>{this.keys.clear(); for(const [id,p] of this.pointers) this.pointers.set(id,{...p,down:false});};
  private pointer(event:PointerEvent,down:boolean,lastDown=false):StoredPointer{return {id:event.pointerId,x:event.clientX,y:event.clientY,pressure:event.pressure||0,down,lastDown};}
  private onPointerDown=(e:PointerEvent):void=>{this.pointers.set(e.pointerId,this.pointer(e,true));}; private onPointerMove=(e:PointerEvent):void=>{const p=this.pointers.get(e.pointerId);this.pointers.set(e.pointerId,this.pointer(e,p?.down??false,p?.lastDown??false));}; private onPointerUp=(e:PointerEvent):void=>{const p=this.pointers.get(e.pointerId);this.pointers.set(e.pointerId,this.pointer(e,false,p?.lastDown??false));};
  public clear():void{this.keys.clear();this.pointers.clear();for(const a of this.actions.values())Object.assign(a,{pressed:false,justPressed:false,justReleased:false,value:0});} private ensureActive():void{if(this.disposed)throw new Error('INPUT_MANAGER_DISPOSED');} public dispose():void{if(this.disposed)return;this.abort.abort();this.clear();this.bindings.length=0;this.disposed=true;}
}
const normalizeKey=(value:string):string=>value.toLowerCase();
export interface AccessibilityPreferenceState{readonly reducedMotion:boolean;readonly contrast:boolean;readonly coarsePointer:boolean;readonly forcedColors:boolean;}
export const readAccessibilityPreferences=():AccessibilityPreferenceState=>{if(typeof matchMedia==='undefined')return{reducedMotion:false,contrast:false,coarsePointer:false,forcedColors:false};return{reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,contrast:matchMedia('(prefers-contrast: more)').matches,coarsePointer:matchMedia('(pointer: coarse)').matches,forcedColors:matchMedia('(forced-colors: active)').matches};};
