import type { EntityId, Vector3Like } from './types';
export interface NavCell { readonly key:string;readonly x:number;readonly y:number;readonly walkable:boolean;readonly cost:number; }
export interface NavGridOptions { readonly width:number;readonly height:number;readonly cellSize?:number;readonly diagonal?:boolean; }
export interface NavPath { readonly ids:readonly string[];readonly points:readonly Vector3Like[];readonly cost:number;readonly complete:boolean; }

/** Deterministic grid navigation for NPCs and fauna, independent from rendering. */
export class NavigationGrid {
 readonly width:number;readonly height:number;readonly cellSize:number;readonly diagonal:boolean;private readonly cells=new Map<string,NavCell>();private disposed=false;
 constructor(options:NavGridOptions){this.width=Math.max(1,Math.floor(options.width));this.height=Math.max(1,Math.floor(options.height));this.cellSize=Math.max(.1,options.cellSize??1);this.diagonal=options.diagonal??true;for(let y=0;y<this.height;y+=1)for(let x=0;x<this.width;x+=1)this.cells.set(this.key(x,y),{key:this.key(x,y),x,y,walkable:true,cost:1});}
 public setWalkable(x:number,y:number,walkable:boolean,cost=1):void{this.ensure();const key=this.key(x,y),cell=this.cells.get(key);if(!cell)throw new RangeError('NAV_CELL_OUT_OF_BOUNDS');this.cells.set(key,{...cell,walkable,cost:Math.max(.01,cost)});}
 public worldToCell(point:Vector3Like):{x:number;y:number}|null{const x=Math.floor(point.x/this.cellSize),y=Math.floor(point.z/this.cellSize);return this.cells.has(this.key(x,y))?{x,y}:null;}
 public cellToWorld(x:number,y:number):Vector3Like{return{x:(x+.5)*this.cellSize,y:0,z:(y+.5)*this.cellSize};}
 public findPath(start:Vector3Like,end:Vector3Like,maxNodes=20000):NavPath{this.ensure();const from=this.worldToCell(start),to=this.worldToCell(end);if(!from||!to)return{ids:[],points:[],cost:0,complete:false};const startKey=this.key(from.x,from.y),goalKey=this.key(to.x,to.y);const open=new Set<string>([startKey]),came=new Map<string,string>();const g=new Map<string,number>([[startKey,0]]),f=new Map<string,number>([[startKey,this.heuristic(from.x,from.y,to.x,to.y)]]);let explored=0;while(open.size&&explored<maxNodes){explored+=1;const current=[...open].sort((a,b)=>(f.get(a)??Infinity)-(f.get(b)??Infinity)||a.localeCompare(b))[0]!;if(current===goalKey)return this.buildPath(came,current,g.get(current)??0);open.delete(current);const currentCell=this.cells.get(current)!;for(const [neighbor,cost] of this.neighbors(currentCell)){const n=this.cells.get(neighbor);if(!n?.walkable)continue;const tentative=(g.get(current)??Infinity)+n.cost*cost;if(tentative<(g.get(neighbor)??Infinity)){came.set(neighbor,current);g.set(neighbor,tentative);const[x,y]=this.parseKey(neighbor);f.set(neighbor,tentative+this.heuristic(x,y,to.x,to.y));open.add(neighbor);}}}return{ids:[],points:[],cost:0,complete:false};}
 public nearestWalkable(point:Vector3Like,radius=8):Vector3Like|null{const cell=this.worldToCell(point);if(!cell)return null;let best:{d:number;p:Vector3Like}|null=null;const r=Math.ceil(radius/this.cellSize);for(let y=cell.y-r;y<=cell.y+r;y+=1)for(let x=cell.x-r;x<=cell.x+r;x+=1){const c=this.cells.get(this.key(x,y));if(!c?.walkable)continue;const p=this.cellToWorld(x,y),d=Math.hypot(p.x-point.x,p.z-point.z);if(d<=radius&&(!best||d<best.d))best={d,p};}return best?.p??null;}
 public blockedRatio():number{let blocked=0;for(const c of this.cells.values())if(!c.walkable)blocked+=1;return blocked/Math.max(1,this.cells.size);}
 public size():number{return this.cells.size;}public clear():void{for(const[key,cell]of this.cells)this.cells.set(key,{...cell,walkable:true,cost:1});}
 private neighbors(cell:NavCell):readonly [string,number][]{const dirs:readonly[number[]]=this.diagonal?[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]]:[[-1,0],[1,0],[0,-1],[0,1]];return dirs.map(([dx,dy])=>{const key=this.key(cell.x+(dx??0),cell.y+(dy??0));return[this.cells.has(key)?key:'',dx!==0&&dy!==0?1.41421356237:1] as [string,number];}).filter(([key])=>key!=='');}
 private buildPath(came:Map<string,string>,current:string,cost:number):NavPath{const ids=[current];let node=current;while(came.has(node)){node=came.get(node)!;ids.push(node);}ids.reverse();return{ids,points:ids.map(k=>{const[x,y]=this.parseKey(k);return this.cellToWorld(x,y);}),cost,complete:true};}
 private heuristic(ax:number,ay:number,bx:number,by:number):number{const dx=Math.abs(ax-bx),dy=Math.abs(ay-by);return this.diagonal?Math.max(dx,dy)+.41421356237*Math.min(dx,dy):dx+dy;}
 private key(x:number,y:number):string{return`${x}|${y}`;}private parseKey(key:string):[number,number]{const parts=key.split('|').map(Number);return[parts[0]??0,parts[1]??0];}private ensure():void{if(this.disposed)throw new Error('NAVIGATION_GRID_DISPOSED');}public dispose():void{if(this.disposed)return;this.cells.clear();this.disposed=true;}
}
export interface SteeringAgent { readonly id:EntityId;readonly position:Vector3Like;readonly velocity:Vector3Like;readonly maxSpeed:number;readonly acceleration:number; }
export interface SteeringTarget { readonly position:Vector3Like;readonly radius:number; }
export const seekVelocity=(agent:SteeringAgent,target:SteeringTarget):Vector3Like=>{const dx=target.position.x-agent.position.x,dz=target.position.z-agent.position.z,len=Math.hypot(dx,dz);if(len<=Math.max(.001,target.radius))return{x:0,y:agent.velocity.y,z:0};const scale=agent.maxSpeed/len;return{x:dx*scale,y:agent.velocity.y,z:dz*scale};};
export const accelerateToward=(current:Vector3Like,target:Vector3Like,acceleration:number,deltaSeconds:number):Vector3Like=>{const limit=Math.max(0,acceleration)*Math.max(0,deltaSeconds),dx=target.x-current.x,dz=target.z-current.z,len=Math.hypot(dx,dz);if(len<=limit)return{...target};const scale=limit/Math.max(.0001,len);return{x:current.x+dx*scale,y:current.y,z:current.z+dz*scale};};
