import type { RuntimeHealthV4, RuntimeId, TickId } from './runtimeContractsV4';
import { tickId, runtimeId } from './runtimeContractsV4';
import { type TypedCameraRuntimeV6 } from './typedCameraRuntimeV6';
import { type TypedInputRuntimeV6 } from './typedInputRuntimeV6';
import { type TypedPlayerRuntimeV6 } from './typedPlayerRuntimeV6';
import { type TypedRenderLoopV6 } from './typedRenderLoopV6';
import { type TypedWorldRuntimeV6 } from './typedWorldRuntimeV6';
import { type SceneFrameV6, type SceneDiagnosticV6, frameId, type RenderBudgetV6, type SceneChunkV6 } from './typedSceneContractsV6';

export type ScenePhaseV6='boot'|'loading'|'ready'|'running'|'paused'|'recovering'|'stopping'|'stopped'|'failed';
export interface SceneCoordinatorOptionsV6{readonly runtimeId?:string;readonly now?:()=>number;readonly maxDiagnostics?:number;readonly maxFrameHistory?:number;readonly targetFrameMs?:number;}
export interface SceneCoordinatorHooksV6{readonly onPhase?:(phase:ScenePhaseV6)=>void;readonly onDiagnostic?:(diagnostic:SceneDiagnosticV6)=>void;readonly onFrame?:(frame:SceneFrameV6)=>void;readonly onRecovery?:(reason:string)=>void;}
export interface SceneCoordinatorMetricsV6{readonly frames:number;readonly ticks:number;readonly phaseChanges:number;readonly recoveries:number;readonly failures:number;readonly diagnostics:number;readonly droppedDiagnostics:number;readonly frameErrors:number;readonly maxFrameMs:number;readonly avgFrameMs:number;readonly lastTick:TickId;}
export interface SceneRuntimeSnapshotV6{readonly version:6;readonly runtime:RuntimeId;readonly phase:ScenePhaseV6;readonly frame:number;readonly tick:TickId;readonly camera:ReturnType<TypedCameraRuntimeV6['state']>;readonly player:ReturnType<TypedPlayerRuntimeV6['state']>;readonly world:ReturnType<TypedWorldRuntimeV6['metrics']>;readonly budget:RenderBudgetV6;readonly health:RuntimeHealthV4;readonly diagnostics:readonly SceneDiagnosticV6[];readonly checksum:string;}

const digest=(value:unknown):string=>{const text=JSON.stringify(value);let hash=2166136261;for(let i=0;i<text.length;i+=1){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(16).padStart(8,'0');};
const finite=(v:unknown,f=0):number=>typeof v==='number'&&Number.isFinite(v)?v:f;

export class TypedSceneCoordinatorV6{
 readonly id:RuntimeId;readonly input:TypedInputRuntimeV6;readonly camera:TypedCameraRuntimeV6;readonly player:TypedPlayerRuntimeV6;readonly world:TypedWorldRuntimeV6;readonly loop:TypedRenderLoopV6;
 #now:()=>number;#phase:ScenePhaseV6='boot';#hooks:SceneCoordinatorHooksV6={};#diagnostics:SceneDiagnosticV6[]=[];#history:SceneFrameV6[]=[];#metrics:SceneCoordinatorMetricsV6=Object.freeze({frames:0,ticks:0,phaseChanges:0,recoveries:0,failures:0,diagnostics:0,droppedDiagnostics:0,frameErrors:0,maxFrameMs:0,avgFrameMs:0,lastTick:0 as TickId});#maxDiagnostics:number;#maxHistory:number;#sceneRuntimeStarted=false;#inFrame=false;#lastSnapshot:SceneRuntimeSnapshotV6|null=null;
 constructor(deps:{input:TypedInputRuntimeV6;camera:TypedCameraRuntimeV6;player:TypedPlayerRuntimeV6;world:TypedWorldRuntimeV6;loop:TypedRenderLoopV6},options:SceneCoordinatorOptionsV6={}){this.id=runtimeId(options.runtimeId??`scene-v6-${Math.trunc(this.#safeNow())}`);this.input=deps.input;this.camera=deps.camera;this.player=deps.player;this.world=deps.world;this.loop=deps.loop;this.#now=options.now??(()=>performance.now());this.#maxDiagnostics=Math.max(16,Math.trunc(options.maxDiagnostics??256));this.#maxHistory=Math.max(8,Math.trunc(options.maxFrameHistory??120));}
 phase():ScenePhaseV6{return this.#phase;}
 setHooks(hooks:SceneCoordinatorHooksV6):void{this.#hooks=hooks;}
 start():void{if(this.#phase==='running')return;if(this.#phase==='failed'||this.#phase==='stopped')throw new Error(`cannot start scene from ${this.#phase}`);this.#setPhase('loading');this.#sceneRuntimeStarted=true;this.loop.start(this.#safeNow());this.#setPhase('ready');this.#setPhase('running');}
 pause(reason='manual'):boolean{if(this.#phase!=='running')return false;this.#diag('info','SCENE_PAUSED',`Scene paused: ${reason}`,{reason});this.loop.pause();this.#setPhase('paused');return true;}
 resume():boolean{if(this.#phase!=='paused')return false;this.loop.resume(this.#safeNow());this.#setPhase('running');return true;}
 stop():boolean{if(this.#phase==='stopped'||this.#phase==='stopping')return false;this.#setPhase('stopping');this.loop.pause();this.#setPhase('stopped');return true;}
 recover(reason='manual'):boolean{if(this.#phase==='stopped')return false;this.#metrics=Object.freeze({...this.#metrics,recoveries:this.#metrics.recoveries+1});this.#setPhase('recovering');this.#diag('warn','SCENE_RECOVERY',`Recovery requested: ${reason}`,{reason});this.#hooks.onRecovery?.(reason);this.input.clear();this.world.updateStreaming();this.loop.resume(this.#safeNow());this.#setPhase('running');return true;}
 async frame(deltaSeconds:number):Promise<SceneFrameV6|null>{if(this.#phase!=='running'||this.#inFrame)return null;this.#inFrame=true;const started=this.#safeNow();try{const now=this.#safeNow();const tick=tickId(Number(this.loop.tick())+1);this.world.setPlayerPosition(this.player.state().position);this.world.updateStreaming();const result=await this.loop.step(async(context)=>{const visible=this.world.nearest(this.player.state().position,this.camera.state().distance*2,this.world.metrics().objects);return Object.freeze({frame:context.frame,submitted:true,drawCalls:Math.min(context.budget.drawCalls,visible.length),triangles:Math.min(context.budget.triangles,visible.length*900),visible:visible.length,culled:Math.max(0,this.world.metrics().objects-visible.length),cpuMs:Math.max(0,this.#safeNow()-started),budgetMs:context.budget.targetMs,quality:this.loop.quality()});},async()=>{const input=this.input.consume(tick,this.loop.frame() as number);this.player.tick(input,Math.max(0,finite(deltaSeconds,1/60)),tick);this.camera.update(Math.max(1,finite(deltaSeconds,1/60)*1000));});if(!result)return null;const objects=this.world.nearest(this.player.state().position,this.camera.state().distance*2,result.visible);const frame=this.loop.createSceneFrame(this.id,this.camera.state(),this.player.state(),this.world.chunks(),objects.map((object)=>object.id),this.#health());this.#history=[...this.#history,frame].slice(-this.#maxHistory);const frameMs=Math.max(0,this.#safeNow()-started);this.#metrics=Object.freeze({...this.#metrics,frames:this.#metrics.frames+1,ticks:Number(this.loop.tick()),lastTick:tick,maxFrameMs:Math.max(this.#metrics.maxFrameMs,frameMs),avgFrameMs:((this.#metrics.avgFrameMs*Math.max(0,this.#metrics.frames-1))+frameMs)/Math.max(1,this.#metrics.frames)});this.#hooks.onFrame?.(frame);return frame;}catch(cause){this.#metrics=Object.freeze({...this.#metrics,frameErrors:this.#metrics.frameErrors+1,failures:this.#metrics.failures+1});this.#diag('error','SCENE_FRAME_FAILED',cause instanceof Error?cause.message:'Scene frame failed',{});return null;}finally{this.#inFrame=false;}}
 history():readonly SceneFrameV6[]{return Object.freeze(this.#history.slice());}
 diagnostics():readonly SceneDiagnosticV6[]{return Object.freeze(this.#diagnostics.slice());}
 metrics():SceneCoordinatorMetricsV6{return this.#metrics;}
 snapshot():SceneRuntimeSnapshotV6{const body={version:6 as const,runtime:this.id,phase:this.#phase,frame:frameId(this.#metrics.frames),tick:this.loop.tick(),camera:this.camera.state(),player:this.player.state(),world:this.world.metrics(),budget:this.loop.budget(),health:this.#health(),diagnostics:this.diagnostics()};const snapshot=Object.freeze({...body,checksum:digest(body)});this.#lastSnapshot=snapshot;return snapshot;}
 restore(snapshot:SceneRuntimeSnapshotV6):boolean{const body={version:snapshot.version,runtime:snapshot.runtime,phase:snapshot.phase,frame:snapshot.frame,tick:snapshot.tick,camera:snapshot.camera,player:snapshot.player,world:snapshot.world,budget:snapshot.budget,health:snapshot.health,diagnostics:snapshot.diagnostics};if(digest(body)!==snapshot.checksum||snapshot.version!==6||snapshot.runtime!==this.id)return false;this.camera.setTarget(snapshot.camera.target);this.camera.setDistance(snapshot.camera.distance);this.player.spawn(snapshot.player.position);if(snapshot.phase==='paused')this.pause('snapshot');else this.start();this.#lastSnapshot=snapshot;return true;}
 lastSnapshot():SceneRuntimeSnapshotV6|null{return this.#lastSnapshot;}
 fail(code:string,message:string,context:Readonly<Record<string,unknown>>={}):void{this.#metrics=Object.freeze({...this.#metrics,failures:this.#metrics.failures+1});this.#setPhase('failed');this.#diag('fatal',code,message,context);}
 #diag(severity:SceneDiagnosticV6['severity'],code:string,message:string,context:Readonly<Record<string,unknown>>):void{const diagnostic:Object&SceneDiagnosticV6=Object.freeze({id:`${this.id}:${this.#metrics.diagnostics+1}`,timestamp:this.#safeNow(),severity,code,message:message.slice(0,500),context:Object.freeze({...context})});this.#diagnostics=[...this.#diagnostics,diagnostic];let dropped=this.#metrics.droppedDiagnostics;if(this.#diagnostics.length>this.#maxDiagnostics){this.#diagnostics.shift();dropped+=1;}this.#metrics=Object.freeze({...this.#metrics,diagnostics:this.#metrics.diagnostics+1,droppedDiagnostics:dropped});this.#hooks.onDiagnostic?.(diagnostic);}
 #setPhase(phase:ScenePhaseV6):void{if(this.#phase===phase)return;this.#phase=phase;this.#metrics=Object.freeze({...this.#metrics,phaseChanges:this.#metrics.phaseChanges+1});this.#hooks.onPhase?.(phase);}
 #health():RuntimeHealthV4{const m=this.#metrics;const score=Math.max(0,100-m.frameErrors*10-m.failures*5-m.droppedDiagnostics*0.5);return Object.freeze({phase:this.#phase==='running'?'running':this.#phase==='paused'?'paused':'boot',score,errors:m.frameErrors+m.failures,warnings:m.droppedDiagnostics,stalled:m.maxFrameMs>100,memoryPressure:0,networkPressure:0,renderPressure:Math.min(1,m.maxFrameMs/33),simulationDrift:0});}
 #safeNow():number{return this.#now();}
}
