const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,Number(value)||0));
export const V66_ACOUSTICS_POLICY=Object.freeze({id:'environment-runtime-acoustics-v66-2026-09-15',version:66,deterministic:true,mutation:false,maxZones:24});
export const normalizeAcousticSampleV66=(sample={})=>({x:Number(sample.x)||0,z:Number(sample.z)||0,waterDistance:Math.max(0,Number(sample.waterDistance)||99999),vegetation:clamp(sample.vegetationCover??sample.vegetation),slope:clamp(sample.slope,0,90),wind:clamp(sample.wind),biome:sample.biome||'grassland',enclosure:clamp(sample.enclosure),settlementDistance:Math.max(0,Number(sample.settlementDistance)||99999)});
export const classifyAcousticZoneV66=(sample={})=>{const s=normalizeAcousticSampleV66(sample);const water=clamp(1-s.waterDistance/120);const cover=s.vegetation;const enclosure=s.enclosure;const wind=s.wind;const human=clamp(1-s.settlementDistance/180);let zone='open-ground';if(water>.72)zone='shore';else if(s.biome==='forest'||s.biome==='taiga')zone=cover>.64?'deep-woodland':'woodland-edge';else if(s.biome==='alpine'||s.biome==='tundra')zone='mountain-pass';else if(enclosure>.7)zone='enclosed-valley';return{zone,water,cover,enclosure,wind,human,occlusion:clamp(cover*.54+enclosure*.46),reverb:clamp(.12+enclosure*.58+water*.18),windBed:clamp(wind*.72+(1-cover)*.28)};};
export const buildAcousticFieldV66=({samples=[],seed=66}={})=>samples.map((sample,index)=>{const zone=classifyAcousticZoneV66(sample);const phase=((Math.imul(seed+index,2654435761)>>>0)%1000)/1000;return{index,...zone,stereoSpread:Number(clamp(.42+phase*.34-zone.occlusion*.28).toFixed(4)),wildlifeGain:Number(clamp((1-zone.human)*(.54+zone.cover*.46)).toFixed(4)),waterGain:Number((zone.water*(.62+zone.reverb*.38)).toFixed(4))};});
export const buildWeatherAcousticsV66=(weather={})=>{const rain=clamp(weather.precipitation),wind=clamp(weather.wind),humidity=clamp(weather.humidity);return{rainGain:Number((rain*.78).toFixed(4)),windGain:Number((wind*.72).toFixed(4)),dampening:Number((humidity*.5+rain*.34).toFixed(4)),lowFrequencyBoost:Number((.12+wind*.18+rain*.1).toFixed(4))};};
export const validateAcousticRuntimeV66=(runtime)=>{const errors=[];if(runtime?.policy!==V66_ACOUSTICS_POLICY.id)errors.push('policy');if(runtime?.deterministic!==true)errors.push('determinism');if((runtime?.field?.length||0)>V66_ACOUSTICS_POLICY.maxZones)errors.push('zone-cap');for(const item of runtime?.field||[])if(item.reverb<0||item.reverb>1||item.stereoSpread<0||item.stereoSpread>1)errors.push('range');return{ok:errors.length===0,errors};};
export const acousticsTelemetryV66=(runtime)=>({zones:runtime?.field?.length||0,meanOcclusion:runtime?.field?.length?Number((runtime.field.reduce((sum,item)=>sum+item.occlusion,0)/runtime.field.length).toFixed(4)):0,meanReverb:runtime?.field?.length?Number((runtime.field.reduce((sum,item)=>sum+item.reverb,0)/runtime.field.length).toFixed(4)):0});
export const getV66AcousticsSummary=()=>Object.freeze({contract:V66_ACOUSTICS_POLICY,features:['zone-classification','weather-bed','wildlife-gain','water-gain'],authority:'read-only-audio-intent'});
