const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,Number(value)||0));
export const V66_GEOLOGY_POLICY=Object.freeze({id:'environment-runtime-geology-v66-2026-09-15',version:66,deterministic:true,mutation:false,maximumTalusSlope:62});
export const normalizeGeologySampleV66=(sample={})=>({x:Number(sample.x)||0,z:Number(sample.z)||0,elevation:Number(sample.elevation)||0,slope:clamp(sample.slope,0,90),rockExposure:clamp(sample.rockExposure),soilDepth:clamp(sample.soilDepth??.5),moisture:clamp(sample.moisture),freezeThaw:clamp(sample.freezeThaw),biome:sample.biome||'grassland',waterDistance:Math.max(0,Number(sample.waterDistance)||99999)});
export const classifyGeologyFaceV66=(sample={})=>{const s=normalizeGeologySampleV66(sample);const cliff=clamp((s.slope-28)/34);const talus=clamp((s.slope-42)/20)*(.6+s.rockExposure*.4);const soil=clamp(s.soilDepth*(1-cliff*.8));const frost=clamp(s.freezeThaw*.64+(1-s.moisture)*.14+cliff*.22);return{class:cliff>.78?'cliff':talus>.38?'talus':s.rockExposure>.56?'bedrock':s.soilDepth<.2?'thin-soil':'mixed-ground',cliff,talus,soil,frost,rockNeed:clamp(s.rockExposure*.56+cliff*.32+frost*.12)};};
export const buildTalusEnvelopeV66=({samples=[],seed=66}={})=>samples.map((sample,index)=>{const s=normalizeGeologySampleV66(sample);const g=classifyGeologyFaceV66(s);const phase=((Math.imul(seed+index,2246822519)>>>0)%1000)/1000;return{index,x:s.x,z:s.z,family:g.class,rockAmount:Number(clamp(g.rockNeed+phase*.08).toFixed(4)),fragmentScale:Number((.35+g.talus*.7+phase*.18).toFixed(4)),settleBias:Number(clamp((1-g.cliff)*.52+g.talus*.48).toFixed(4)),snowCatch:Number(clamp(g.cliff*.42+g.frost*.58).toFixed(4))};});
export const buildRockFaceResponseV66=(sample={},weather={})=>{const s=normalizeGeologySampleV66(sample);const g=classifyGeologyFaceV66(s);const wet=clamp(weather.humidity??0);return{roughness:clamp(.62+g.rockNeed*.24),normalStrength:clamp(.34+g.cliff*.48),wetDarkening:clamp(wet*.32+s.moisture*.18),screeProbability:clamp(g.talus*.72+(1-s.soilDepth)*.28),iceLatch:clamp(g.frost*.46+(1-s.moisture)*.18)};};
export const validateGeologyRuntimeV66=(runtime)=>{const errors=[];if(runtime?.policy!==V66_GEOLOGY_POLICY.id)errors.push('policy');if(runtime?.deterministic!==true)errors.push('determinism');for(const item of runtime?.envelope||[])if(item.rockAmount<0||item.rockAmount>1||item.snowCatch<0||item.snowCatch>1)errors.push('range');return{ok:errors.length===0,errors};};
export const geologyTelemetryV66=(runtime)=>({samples:runtime?.envelope?.length||0,rockMean:runtime?.envelope?.length?Number((runtime.envelope.reduce((sum,item)=>sum+item.rockAmount,0)/runtime.envelope.length).toFixed(4)):0,talusCount:runtime?.envelope?.filter((item)=>item.family==='talus').length||0,cliffCount:runtime?.envelope?.filter((item)=>item.family==='cliff').length||0});
export const getV66GeologySummary=()=>Object.freeze({contract:V66_GEOLOGY_POLICY,features:['face-classification','talus','rock-response','snow-catch']});
