const clamp=(v,min=0,max=1)=>Math.max(min,Math.min(max,Number(v)||0));
export const V66_CONTINUITY_POLICY=Object.freeze({id:'environment-runtime-continuity-v66-2026-09-15',version:66,deterministic:true,mutation:false,maxGap:120});
export const normalizeContinuityNodeV66=(n={})=>({id:String(n.id??''),x:Number(n.x)||0,z:Number(n.z)||0,elevation:Number(n.elevation)||0,biome:n.biome||'grassland',material:n.material||'ground',confidence:clamp(n.confidence??1),waterDistance:Math.max(0,Number(n.waterDistance)||99999)});
export const buildContinuityLinkV66=(a,b)=>{const A=normalizeContinuityNodeV66(a),B=normalizeContinuityNodeV66(b);const distance=Math.hypot(A.x-B.x,A.z-B.z);const elevationDelta=Math.abs(A.elevation-B.elevation);const biomeMatch=A.biome===B.biome?1:0;const materialMatch=A.material===B.material?1:0;const confidence=Math.min(A.confidence,B.confidence);const gap=clamp(distance/V66_CONTINUITY_POLICY.maxGap);return{from:A.id,to:B.id,distance,elevationDelta,biomeMatch,materialMatch,confidence,continuity:clamp(.34*(1-gap)+.2*biomeMatch+.2*materialMatch+.26*confidence),valid:distance>0&&distance<=V66_CONTINUITY_POLICY.maxGap}};
export const buildContinuityFieldV66=({nodes=[],seed=66}={})=>{const normalized=nodes.map(normalizeContinuityNodeV66);return normalized.map((node,index)=>{const candidates=normalized.map((other,otherIndex)=>({other,otherIndex,distance:Math.hypot(node.x-other.x,node.z-other.z)})).filter(item=>item.otherIndex!==index&&item.distance>0).sort((a,b)=>a.distance-b.distance).slice(0,3);const links=candidates.map(item=>buildContinuityLinkV66(node,item.other));return{index,node,links,meanContinuity:links.length?links.reduce((s,l)=>s+l.continuity,0)/links.length:1,seedPhase:((Math.imul(seed+index,1103515245)>>>0)%1000)/1000};});};
export const healContinuityV66=(field=[])=>field.map(item=>({...item,healed:item.meanContinuity<.62,blendStrength:Number(clamp(.22+(1-item.meanContinuity)*.58).toFixed(4))}));
export const validateContinuityRuntimeV66=(runtime)=>{const errors=[];if(runtime?.policy!==V66_CONTINUITY_POLICY.id)errors.push('policy');if(runtime?.deterministic!==true)errors.push('determinism');for(const item of runtime?.field||[])if(item.meanContinuity<0||item.meanContinuity>1)errors.push('range');return{ok:errors.length===0,errors};};
export const continuityTelemetryV66=(runtime)=>({nodes:runtime?.field?.length||0,meanContinuity:runtime?.field?.length?Number((runtime.field.reduce((s,i)=>s+i.meanContinuity,0)/runtime.field.length).toFixed(4)):1,healed:runtime?.field?.filter(i=>i.healed).length||0});
export const getV66ContinuitySummary=()=>Object.freeze({contract:V66_CONTINUITY_POLICY,features:['link-analysis','gap-detection','continuity-healing','terrain-blend']});
