/**
 * Buzul Muhafızı — Environment Visual Acceptance Runtime v61
 * Read-only, caller-owned plan for shipped createScene observations.
 */
const VERSION = 'v61';
const DEFAULT_CAMERA = Object.freeze({ width: 1536, height: 1024, orthoDegrees: 90, profiles: Object.freeze(['full-world','far','terrain-near','northwest-near']) });
const LIMITS = Object.freeze({ maxSamples: 256, maxInstances: 2048, maxFog: 0.92, maxNormalEnergy: 1.35, minSkyLuminance: 0.08 });
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number.isFinite(v)?v:min));
const n=(v,f=0)=>Number.isFinite(v)?v:f;
const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a||1),0,1);return t*t*(3-2*t);};
const sum=o=>Object.values(o).reduce((a,b)=>a+b,0);
const normalize=o=>{const s=sum(o)||1;return Object.fromEntries(Object.entries(o).map(([k,v])=>[k,v/s]));};
const hash=(s)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');};
const stable=(v)=>JSON.stringify(v,Object.keys(v).sort());
function finiteSample(raw={}){const s=raw.surface||raw;return {x:n(raw.x),z:n(raw.z),canonicalY:n(raw.canonicalY),renderedY:n(raw.renderedY),colliderY:n(raw.colliderY),slope:clamp(n(s.slope),0,1),elevation:clamp(n(s.elevation),0,1),moisture:clamp(n(s.moisture),0,1),snow:clamp(n(s.snow),0,1),waterDepth:Math.max(0,n(s.waterDepth)),waterDistance:Math.max(0,n(s.waterDistance,9999)),biome:String(s.biome||'temperate'),waterClass:String(s.waterClass||'land'),roadDistance:Math.max(0,n(s.roadDistance,9999)),settlementDistance:Math.max(0,n(s.settlementDistance,9999)),assetReady:raw.assetReady!==false,confidence:clamp(n(raw.confidence,1),0,1),tileEdgeDistance:Math.max(0,n(raw.tileEdgeDistance,9999)),cameraDistance:Math.max(0,n(raw.cameraDistance))};}
function slopeFall(v){return smooth(0.28,0.82,v);}
function surfaceWeights(s){const alpine=s.snow>0.35||s.elevation>0.72,wet=s.moisture>0.72,steep=s.slope>0.62,shore=s.waterDistance<12&&s.waterClass!=='land';const w={grass:(1-slopeFall(s.slope))*(1-s.snow)*(1-s.waterDepth),soil:(1-slopeFall(s.slope))*(1-s.snow)*0.8,mud:wet*(1-s.snow)*0.9,sand:shore*(1-s.slope)*0.7,rock:steep*0.9+alpine*0.25,scree:steep*0.8+alpine*0.45,snow:s.snow*0.95,wetEdge:shore*wet*0.8,foam:shore*s.waterDepth>0?Math.min(0.4,shore*0.5):0};return normalize(Object.fromEntries(Object.entries(w).map(([k,v])=>[k,clamp(v,0,1)])));}
function geology(s){const relief=clamp(s.slope*0.7+s.elevation*0.3,0,1);return {cliffExposure:clamp(s.slope*s.elevation,0,1),talus:clamp((s.slope-0.45)*1.8,0,1),ridgeBreakup:clamp(relief*0.85,0,1),snowlineBand:clamp(Math.abs(s.elevation-0.7)*3,0,1),microRelief:clamp(0.18+s.slope*0.42+s.moisture*0.16,0,1)};}
function water(s){const shore=clamp(1-s.waterDistance/18,0,1),deep=clamp(s.waterDepth/8,0,1),shallow=shore*(1-deep);return {deep,shallow,shore,wetEdge:clamp(shallow*0.85+s.moisture*0.2,0,1),foam:clamp(shallow*0.55,0,0.55),cyanSuppression:clamp(0.65+shallow*0.3,0,1),moireRisk:clamp((1-shore)*0.1+(s.tileEdgeDistance<2?0.9:0),0,1),rectangularCoverageRisk:clamp((s.waterClass!=='land'&&s.waterDistance<1)?0.95:0,0,1)};}
function placement(s){const blocked=!s.assetReady||s.confidence<0.65||s.waterClass!=='land'||s.waterDepth>0.05||s.slope>0.78||s.snow>0.92||s.roadDistance<2.5||s.settlementDistance<3;return {eligible:!blocked,reason:blocked?'context-blocked':'grounded',density:blocked?0:clamp((1-s.slope)*(1-s.snow)*s.confidence,0,1),ecotone:clamp(1-Math.abs(s.moisture-0.55)*1.4,0,1),yawJitter:clamp(0.18+s.moisture*0.22,0.18,0.4),scaleJitter:clamp(0.08+s.slope*0.16,0.08,0.24),lod:s.cameraDistance<40?'near':s.cameraDistance<140?'cluster':'impostor',instanceGroup:s.biome+'::'+(s.slope>0.6?'rocky':'ground')};}
function atmosphere(obs={}){const luminance=clamp(n(obs.backgroundLuminance,0.3),0,1);return {skyLuminance:Math.max(LIMITS.minSkyLuminance,luminance),fogNear:clamp(n(obs.fogNear,80),8,500),fogFar:clamp(n(obs.fogFar,900),120,5000),exposure:clamp(n(obs.exposure,1),0.65,1.35),cameraRelativeSky:true,blackSkyRisk:luminance<LIMITS.minSkyLuminance};}
function parity(s){const d=Math.max(Math.abs(s.renderedY-s.canonicalY),Math.abs(s.colliderY-s.canonicalY));return {maxHeightDelta:d,withinTolerance:d<=0.35,sameCoordinate:true};}
function classify(raw){const s=finiteSample(raw),w=surfaceWeights(s),g=geology(s),wa=water(s),p=placement(s),pa=parity(s);return {sample:{x:s.x,z:s.z,biome:s.biome},surface:w,geology:g,water:wa,placement:p,parity:pa};}
export function createEnvironmentVisualAcceptancePlan(input={}){const raw=Array.isArray(input.samples)?input.samples.slice(0,LIMITS.maxSamples):[],samples=raw.map(classify),riskCounts={seam:samples.filter(x=>x.water.moireRisk>0.8).length,rectangularWater:samples.filter(x=>x.water.rectangularCoverageRisk>0.8).length,parity:samples.filter(x=>!x.parity.withinTolerance).length,blackSky:atmosphere(input.atmosphere).blackSkyRisk?1:0,invalidPlacement:samples.filter(x=>!x.placement.eligible&&x.placement.reason==='context-blocked').length};const plan={version:VERSION,limits:LIMITS,camera:DEFAULT_CAMERA,samples,atmosphere:atmosphere(input.atmosphere),riskCounts,targets:{visibleSeams:0,visibleRectangularWater:0,visibleMoire:0,floatingAssets:0,blackSkyFailures:0,materialMismatch:0},capabilities:{groundQuery:true,waterQuery:true,slopeQuery:true,biomeQuery:true,placementQuery:true,assetHydration:'caller-owned',sharedMaterialPlacement:'merged-590-authority'},digest:hash(stable({samples,riskCounts}))};return deepFreeze(plan);}
function deepFreeze(o){Object.freeze(o);for(const v of Object.values(o)){if(v&&typeof v==='object'&&!Object.isFrozen(v))deepFreeze(v);}return o;}
export function applyEnvironmentVisualAcceptancePlan(plan,target={}){if(!plan||!target||typeof target!=='object')return false;target.environmentVisualAcceptance={version:plan.version,digest:plan.digest,riskCounts:plan.riskCounts,camera:plan.camera,targets:plan.targets};return true;}
export const environmentVisualAcceptanceV61={createEnvironmentVisualAcceptancePlan,applyEnvironmentVisualAcceptancePlan};
export default environmentVisualAcceptanceV61;
