import { clamp01, finiteV67, meanV67, normalizeSampleV67 } from './environmentRuntimeV67.js';
import { floodDepthV67 } from './environmentRuntimeHydrologyV67.js';
import { fogDensityV67 } from './environmentRuntimeAtmosphereV67.js';
export const HAZARDS_V67=Object.freeze({id:'hazards-v67',version:67,deterministic:true,noWorldMutation:true});
export const rockfallRiskV67=(sample={})=>{const s=normalizeSampleV67(sample);return clamp01(s.slope*.7+clamp01(sample.rockLoose??.25)*.3);};
export const iceRiskV67=(sample={})=>{const s=normalizeSampleV67(sample);return clamp01((0-s.temperature)/14)*(.45+s.moisture*.55);};
export const windRiskV67=(sample={})=>clamp01(normalizeSampleV67(sample).wind*.82);
export const heatRiskV67=(sample={})=>clamp01((finiteV67(sample.temperature,12)-28)/18);
export const fogHazardV67=(sample={})=>clamp01(fogDensityV67(sample)*.8);
export const compoundHazardV67=(sample={})=>clamp01(rockfallRiskV67(sample)*.2+iceRiskV67(sample)*.17+floodDepthV67(sample)*.29+windRiskV67(sample)*.14+heatRiskV67(sample)*.09+fogHazardV67(sample)*.11);
export const hazardClassV67=(risk=0)=>risk>=.8?'critical':risk>=.58?'high':risk>=.35?'moderate':'low';
export const safeMarginV67=(risk=0)=>clamp01(1-clamp01(risk));
export const buildHazardSampleV67=(sample={})=>{const s=normalizeSampleV67(sample);const risk=compoundHazardV67(s);return{id:s.id,risk,class:hazardClassV67(risk),safe:risk<.58,margin:safeMarginV67(risk),drivers:{rockfall:rockfallRiskV67(s),ice:iceRiskV67(s),flood:floodDepthV67(s),wind:windRiskV67(s),heat:heatRiskV67(s),fog:fogHazardV67(s)}};};
export const buildHazardFieldV67=(samples=[])=>samples.map(buildHazardSampleV67);
export const hazardSummaryV67=(field=[])=>({samples:field.length,mean:meanV67(field.map(x=>x.risk)),critical:field.filter(x=>x.class==='critical').length,high:field.filter(x=>x.class==='high').length,unsafe:field.filter(x=>!x.safe).length});
export const validateHazardsV67=(field=[])=>{const errors=[];if(!Array.isArray(field))errors.push('field');if(field.some(x=>x.risk<0||x.risk>1))errors.push('risk');if(field.some(x=>typeof x.safe!=='boolean'))errors.push('safe');return{ok:errors.length===0,errors};};
export const hazardTelemetryV67=(field=[])=>({policy:HAZARDS_V67.id,valid:validateHazardsV67(field).ok,summary:hazardSummaryV67(field)});
export const hazardBandV67=(field=[])=>field.map(x=>({id:x.id,band:x.class,margin:x.margin}));
export const hazardEscalationV67=(before=0,after=0)=>({delta:clamp01(after)-clamp01(before),escalated:after>before+.12,deescalated:before>after+.12});
export const hazardScenarioV67=(sample={},modifiers={})=>{const scaled={...sample,rain:clamp01((sample.rain??0)+finiteV67(modifiers.rain)),wind:clamp01((sample.wind??0)+finiteV67(modifiers.wind)/50),temperature:finiteV67(sample.temperature,12)+finiteV67(modifiers.temperature)};return buildHazardSampleV67(scaled);};
export const hazardRoutePenaltyV67=(risk=0)=>risk>=.8?Infinity:1+clamp01(risk)*3.6;
