/**
 * Shared render-only palette calibrated from the owner's photogrammetry references and the
 * repository's dirt-road / rocky-terrain assets. Numeric world authority is deliberately absent:
 * terrain height, hydrology, routes, collision and the day clock remain owned by their existing
 * systems. Keeping the colours here prevents each material from inventing a different geography.
 * @module world/geographicReferencePalette
 */

export const GEOGRAPHIC_REFERENCE_PALETTE_POLICY = Object.freeze({
	id: 'geographic-reference-palette-2026-09-04-v122-weathered-material-depth',
	renderOnly: true,
	deterministic: true,
	heightAuthorityUnchanged: true,
	hydrologyAuthorityUnchanged: true,
	routeAuthorityUnchanged: true,
	ecotoneContrastRaised: true,
	wetDryValueSeparationRaised: true,
	rockValueCompressionReduced: true,
	waterDepthHierarchyRaised: true,
	aerialChromaRecovery: true,
	aerialLowlandMaterialSeparationRaised: true,
	aerialLowlandDepthRaised: true,
	aerialRockSoilSeparationRaised: true,
	aerialLithologyDepthRaised: true,
	openWaterValueSeparationRaised: true,
	coastalGreenCastReduced: true,
	deepMarineBlackCrushReduced: true,
	legacyRoadBaseContractPreserved: true,
	exposedRockSeparationRaised: true,
	fullWorldLowlandStrataRaised: true,
	lowlandEcotoneDepthRaised: true,
	lowlandOliveCompressionReduced: true,
	mineralVegetationHueSeparationRaised: true,
	aerialEcologicalContrastRaised: true,
	lowlandChromaDepthRaised: true,
	weatheredLithologySeparationRaised: true,
	fullWorldLowlandMaterialSeparationRaised: true,
	lowlandAerialValueDecorrelationRaised: true,
	aerialStructuralContrastRaised: true,
	lowlandAerialRecoveryRaised: true,
	lowlandEcotoneRecoveryRaised: true,
	fullWorldVegetationReadabilityRaised: true,
	aerialEcotoneClarityRaised: true,
	fullWorldLowlandDomainRecoveryRaised: true,
	lowlandBiomeDomainSeparationRaised: true,
	fullWorldLowlandValueSeparationRaised: true,
	directionalDomainReadabilityRaised: true,
	materialDomainDepthRaised: true,
	wetLithicSeparationRaised: true,
	lowlandAerialDomainContrastRaised: true,
	lowlandDistanceReadabilityRaised: true,
	aerialMaterialContrastRaised: true,
	fullWorldDomainClarityRaised: true,
	naturalPigmentCalibration: true,
	highDistanceChannelExtremesReduced: true,
	coastalCyanBalanceRaised: true,
	naturalLowlandValueSeparationRaised: true,
	wetVegetationShadowDepthRaised: true,
	dryMineralHighlightSeparationRaised: true,
	lowlandMaterialReliefRaised: true,
	distantLowlandContrastRaised: true,
	naturalWaterDepthHierarchyRaised: true,
	lakeRiverOpticalSeparationRaised: true,
	openSeaSlateDepthRaised: true,
	aerialWaterSeparationRaised: true,
	roadMaterialHierarchyRaised: true,
	roadDustOrangeCastReduced: true,
	roadStoneRutSeparationRaised: true,
	riverReachValueSeparationRaised: true,
	waterfallAerationContrastRaised: true,
	plungePoolDepthRaised: true,
	fullWorldTerrainMaterialHierarchyRaised: true,
	meadowDrylandValueSeparationRaised: true,
	lithologyShadowSeparationRaised: true,
	shallowSedimentOpticalSeparationRaised: true,
	lakeMarineHueDecorrelationRaised: true,
	riverPoolRapidEnergySeparationRaised: true,
	waterfallPlungeFoamValueRangeRaised: true,
	aerialOpenWaterMidtoneRaised: true,
	openWaterFabricVisibilityRaised: true,
	weatheredStoneNeutralityRaised: true,
	wetGroundBlackCrushReduced: true,
	dryGroundOrangeCastReduced: true,
	lowlandWetDryLumaGapRaised: true,
	vegetationMineralHueGapRaised: true,
	aerialWaterNormalReadabilitySupported: true,
	openSeaMidtoneHeadroomRaised: true,
	terrainWaterValueCollisionReduced: true,
	fullWorldGreyBeigeCompressionReduced: true,
	openSeaAerialBlackCrushReduced: true,
	lowlandSoilStoneValueGapRaised: true,
	wetOrganicCoolBiasRaised: true,
	dryHeatherDustCastReduced: true,
	lowlandMaterialReliefContrastRaised: true,
	lithologyAerialRangeRaised: true,
	lowlandAerialSeparationRaised: true,
	wetDryMineralDistanceGapRaised: true,
	rockShadowBlackCrushReduced: true,
	weatheredRockWarmthRaised: true,
	lowlandMineralNeutralityRaised: true,
	fullWorldKhakiCompressionReduced: true,
	weatheredRockMidtoneRecoveryRaised: true,
	lowlandVegetationEarthHueGapRaised: true,
	weatheredRockFacetRangeRaised: true,
	wetBasaltSpecularHeadroomRaised: true,
	roadCompactionRutDepthRaised: true,
	roadDustStoneHueDecorrelationRaised: true,
	fullWorldLowlandDomainDepthRaised: true,
	lowlandWetDryMineralTriadRaised: true,
	distantMeadowEarthSeparationRaised: true,
	aerialMeadowShadowDepthRaised: true,
	dryHeathMineralWarmthRaised: true,
	weatheredGraniteFacetClarityRaised: true,
	deepSeaMesoFabricHeadroomRaised: true,
	weatheredMaterialDepthRaised: true,
	roadRutMoistureDepthRaised: true,
	riverRapidFoamSeparationRaised: true,
	coastalShallowSedimentReadabilityRaised: true,
	assetReferences: Object.freeze([
		'assets/models/fbx/dirt_road_test.glb',
		'assets/models/fbx/road_terrain.glb',
		'assets/models/fbx/rocky_terrain_low_poly.glb',
		'assets/models/fbx/rugged_mountain_landscape.glb',
	]),
	calibration: Object.freeze({
		terrain: 'v122 keeps v121 lowland separation while shifting exposed earth and weathered rock toward a broader neutral mineral interval so cliffs and stony plains retain facet depth without beige compression. Existing deterministic world-space micro/meso normal and roughness remain the lighting breakup authority; canonical terrain, hydrology and collider authority are unchanged.',
		water: 'v122 separates shallow sediment, river pools and aerated rapid water more clearly while preserving the deep-sea slate headroom from v121. Canonical depth, coverage, offshore connectivity and shoreline ownership are unchanged.',
		road: 'v122 deepens moist ruts and slightly lightens embedded stone relative to compacted earth so road wear reads as material structure rather than one brown ribbon. Route topology, width, terrain sampling and water exclusion are unchanged.',
		celestial: 'v122 preserves restrained dawn/noon/sunset/moon calibration and does not alter the day clock or lighting authority.',
	}),
});

export const GEOGRAPHIC_REFERENCE_PALETTE = Object.freeze({
	terrain: Object.freeze({
		mossShadow: 0x142f25,
		meadow: 0x47763a,
		dryHeather: 0x816c52,
		wetEarth: 0x102126,
		exposedEarth: 0xb29a7d,
		graniteShadow: 0x46504f,
		graniteSunlit: 0xbeb9af,
		basaltWet: 0x243b42,
		quartz: 0xd7d3ca,
	}),
	road: Object.freeze({
		compacted: 0x6b5c50,
		rut: 0x202322,
		dust: 0x8d867a,
		stone: 0x7a807f,
		mossEdge: 0x38563f,
	}),
	water: Object.freeze({
		shoreClear: 0x709993,
		lakeClear: 0x3a6d7c,
		riverPool: 0x2d5d68,
		rapid: 0x97b3b4,
		deepSea: 0x28556a,
		abyss: 0x0b2738,
		plunge: 0x427486,
		splash: 0xe8f1ee,
		foam: 0xf4f9f6,
	}),
	celestial: Object.freeze({
		dawn: 0xffae63,
		noon: 0xffefd6,
		sunset: 0xff8750,
		moon: 0xc6d8f6,
	}),
});

export function hexToLinearTriplet(hex) {
	const channel = (shift) => ((hex >> shift) & 0xff) / 255;
	const linear = (value) => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
	return Object.freeze([linear(channel(16)), linear(channel(8)), linear(channel(0))]);
}

export function relativeLuminanceFromHex(hex) {
	const [r, g, b] = hexToLinearTriplet(hex);
	return r * 0.2126 + g * 0.7152 + b * 0.0722;
}
