/**
 * Shared render-only palette calibrated from the owner's photogrammetry references and the
 * repository's dirt-road / rocky-terrain assets. Numeric world authority is deliberately absent:
 * terrain height, hydrology, routes, collision and the day clock remain owned by their existing
 * systems. Keeping the colours here prevents each material from inventing a different geography.
 * @module world/geographicReferencePalette
 */

export const GEOGRAPHIC_REFERENCE_PALETTE_POLICY = Object.freeze({
	id: 'geographic-reference-palette-2026-09-04-v125-distant-material-depth',
	renderOnly: true,
	deterministic: true,
	heightAuthorityUnchanged: true,
	hydrologyAuthorityUnchanged: true,
	routeAuthorityUnchanged: true,
	ecotoneContrastRaised: true,
	wetDryValueSeparationRaised: true,
	rockValueCompressionReduced: true,
	waterDepthHierarchyRaised: true,
	aerialChromaRecovery: true,
	aerialLowlandMaterialSeparationRaised: true,
	aerialLowlandDepthRaised: true,
	aerialRockSoilSeparationRaised: true,
	aerialLithologyDepthRaised: true,
	openWaterValueSeparationRaised: true,
	coastalGreenCastReduced: true,
	deepMarineBlackCrushReduced: true,
	legacyRoadBaseContractPreserved: true,
	exposedRockSeparationRaised: true,
	fullWorldLowlandStrataRaised: true,
	lowlandEcotoneDepthRaised: true,
	lowlandOliveCompressionReduced: true,
	mineralVegetationHueSeparationRaised: true,
	aerialEcologicalContrastRaised: true,
	lowlandChromaDepthRaised: true,
	weatheredLithologySeparationRaised: true,
	fullWorldLowlandMaterialSeparationRaised: true,
	lowlandAerialValueDecorrelationRaised: true,
	aerialStructuralContrastRaised: true,
	lowlandAerialRecoveryRaised: true,
	lowlandEcotoneRecoveryRaised: true,
	fullWorldVegetationReadabilityRaised: true,
	aerialEcotoneClarityRaised: true,
	fullWorldLowlandDomainRecoveryRaised: true,
	lowlandBiomeDomainSeparationRaised: true,
	fullWorldLowlandValueSeparationRaised: true,
	directionalDomainReadabilityRaised: true,
	materialDomainDepthRaised: true,
	wetLithicSeparationRaised: true,
	lowlandAerialDomainContrastRaised: true,
	lowlandDistanceReadabilityRaised: true,
	aerialMaterialContrastRaised: true,
	fullWorldDomainClarityRaised: true,
	naturalPigmentCalibration: true,
	highDistanceChannelExtremesReduced: true,
	coastalCyanBalanceRaised: true,
	naturalLowlandValueSeparationRaised: true,
	wetVegetationShadowDepthRaised: true,
	dryMineralHighlightSeparationRaised: true,
	lowlandMaterialReliefRaised: true,
	distantLowlandContrastRaised: true,
	naturalWaterDepthHierarchyRaised: true,
	lakeRiverOpticalSeparationRaised: true,
	openSeaSlateDepthRaised: true,
	aerialWaterSeparationRaised: true,
	roadMaterialHierarchyRaised: true,
	roadDustOrangeCastReduced: true,
	roadStoneRutSeparationRaised: true,
	riverReachValueSeparationRaised: true,
	waterfallAerationContrastRaised: true,
	plungePoolDepthRaised: true,
	fullWorldTerrainMaterialHierarchyRaised: true,
	meadowDrylandValueSeparationRaised: true,
	lithologyShadowSeparationRaised: true,
	shallowSedimentOpticalSeparationRaised: true,
	lakeMarineHueDecorrelationRaised: true,
	riverPoolRapidEnergySeparationRaised: true,
	waterfallPlungeFoamValueRangeRaised: true,
	aerialOpenWaterMidtoneRaised: true,
	openWaterFabricVisibilityRaised: true,
	weatheredStoneNeutralityRaised: true,
	wetGroundBlackCrushReduced: true,
	dryGroundOrangeCastReduced: true,
	lowlandWetDryLumaGapRaised: true,
	vegetationMineralHueGapRaised: true,
	aerialWaterNormalReadabilitySupported: true,
	openSeaMidtoneHeadroomRaised: true,
	terrainWaterValueCollisionReduced: true,
	fullWorldGreyBeigeCompressionReduced: true,
	openSeaAerialBlackCrushReduced: true,
	lowlandSoilStoneValueGapRaised: true,
	wetOrganicCoolBiasRaised: true,
	dryHeatherDustCastReduced: true,
	lowlandMaterialReliefContrastRaised: true,
	lithologyAerialRangeRaised: true,
	lowlandAerialSeparationRaised: true,
	wetDryMineralDistanceGapRaised: true,
	rockShadowBlackCrushReduced: true,
	weatheredRockWarmthRaised: true,
	lowlandMineralNeutralityRaised: true,
	fullWorldKhakiCompressionReduced: true,
	weatheredRockMidtoneRecoveryRaised: true,
	lowlandVegetationEarthHueGapRaised: true,
	weatheredRockFacetRangeRaised: true,
	wetBasaltSpecularHeadroomRaised: true,
	roadCompactionRutDepthRaised: true,
	roadDustStoneHueDecorrelationRaised: true,
	fullWorldLowlandDomainDepthRaised: true,
	lowlandWetDryMineralTriadRaised: true,
	distantMeadowEarthSeparationRaised: true,
	aerialMeadowShadowDepthRaised: true,
	dryHeathMineralWarmthRaised: true,
	weatheredGraniteFacetClarityRaised: true,
	deepSeaMesoFabricHeadroomRaised: true,
	weatheredMaterialDepthRaised: true,
	roadRutMoistureDepthRaised: true,
	riverRapidFoamSeparationRaised: true,
	coastalShallowSedimentReadabilityRaised: true,
	fullWorldWeatheredSeparationRaised: true,
	lowlandMineralHighlightHeadroomRaised: true,
	roadWearValueRangeRaised: true,
	riverAerationValueRangeRaised: true,
	distantWaterMesoReadabilityRaised: true,
	openSeaLakeHueGapRaised: true,
	riverPlungeEnergyReadabilityRaised: true,
	weatheredRoadNeutralityRaised: true,
	distantTerrainReliefSeparationRaised: true,
	lowlandKhakiCollapseReduced: true,
	openWaterDepthGradientRaised: true,
	roadEarthStoneDistanceGapRaised: true,
	assetReferences: Object.freeze([
		'assets/models/fbx/dirt_road_test.glb',
		'assets/models/fbx/road_terrain.glb',
		'assets/models/fbx/rocky_terrain_low_poly.glb',
		'assets/models/fbx/rugged_mountain_landscape.glb',
	]),
	calibration: Object.freeze({
		terrain: 'v125 deepens meadow/wet-earth separation, neutralizes dry heath and increases granite/basalt facet range so existing deterministic world-space micro/meso normal and roughness read more clearly at full-world distance. Canonical terrain, hydrology and collider authority remain unchanged.',
		water: 'v125 increases lake/open-sea depth separation while retaining a dark abyss and bright rapid/plunge aeration, preserving existing current, shear, foam and normal fabric without inventing water coverage.',
		road: 'v125 keeps the compacted base neutral while widening rut, dust and embedded-stone distance separation; route topology, width, terrain sampling and water exclusion are unchanged.',
		celestial: 'v125 preserves restrained dawn/noon/sunset/moon calibration and does not alter the day clock or lighting authority.',
	}),
});

export const GEOGRAPHIC_REFERENCE_PALETTE = Object.freeze({
	terrain: Object.freeze({
		mossShadow: 0x122c24,
		meadow: 0x477a3a,
		dryHeather: 0x7c705c,
		wetEarth: 0x0b2025,
		exposedEarth: 0xc5a47d,
		graniteShadow: 0x3a4548,
		graniteSunlit: 0xcac4b9,
		basaltWet: 0x203c43,
		quartz: 0xd9d5cc,
	}),
	road: Object.freeze({
		compacted: 0x62584f,
		rut: 0x171c1c,
		dust: 0x96918a,
		stone: 0x89908f,
		mossEdge: 0x36553e,
	}),
	water: Object.freeze({
		shoreClear: 0x82aaa1,
		lakeClear: 0x477b88,
		riverPool: 0x2c6473,
		rapid: 0xb0c8c8,
		deepSea: 0x315f75,
		abyss: 0x092638,
		plunge: 0x467f90,
		splash: 0xeff6f3,
		foam: 0xf5faf7,
	}),
	celestial: Object.freeze({
		dawn: 0xffae63,
		noon: 0xffefd6,
		sunset: 0xff8750,
		moon: 0xc6d8f6,
	}),
});

export function hexToLinearTriplet(hex) {
	const channel = (shift) => ((hex >> shift) & 0xff) / 255;
	const linear = (value) => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
	return Object.freeze([linear(channel(16)), linear(channel(8)), linear(channel(0))]);
}

export function relativeLuminanceFromHex(hex) {
	const [r, g, b] = hexToLinearTriplet(hex);
	return r * 0.2126 + g * 0.7152 + b * 0.0722;
}
