/**
 * Shared render-only palette calibrated from the owner's photogrammetry references and the
 * repository's dirt-road / rocky-terrain assets. Numeric world authority is deliberately absent:
 * terrain height, hydrology, routes, collision and the day clock remain owned by their existing
 * systems. Keeping the colours here prevents each material from inventing a different geography.
 * @module world/geographicReferencePalette
 */

export const GEOGRAPHIC_REFERENCE_PALETTE_POLICY = Object.freeze({
	id: 'geographic-reference-palette-2026-09-04-v146-broad-plain-material-separation',
	renderOnly: true,
	deterministic: true,
	heightAuthorityUnchanged: true,
	hydrologyAuthorityUnchanged: true,
	routeAuthorityUnchanged: true,
	ecotoneContrastRaised: true,
	wetDryValueSeparationRaised: true,
	rockValueCompressionReduced: true,
	waterDepthHierarchyRaised: true,
	aerialChromaRecovery: true,
	aerialLowlandMaterialSeparationRaised: true,
	aerialLowlandDepthRaised: true,
	aerialRockSoilSeparationRaised: true,
	aerialLithologyDepthRaised: true,
	openWaterValueSeparationRaised: true,
	coastalGreenCastReduced: true,
	deepMarineBlackCrushReduced: true,
	legacyRoadBaseContractPreserved: true,
	exposedRockSeparationRaised: true,
	fullWorldLowlandStrataRaised: true,
	lowlandEcotoneDepthRaised: true,
	lowlandOliveCompressionReduced: true,
	mineralVegetationHueSeparationRaised: true,
	aerialEcologicalContrastRaised: true,
	lowlandChromaDepthRaised: true,
	weatheredLithologySeparationRaised: true,
	fullWorldLowlandMaterialSeparationRaised: true,
	lowlandAerialValueDecorrelationRaised: true,
	aerialStructuralContrastRaised: true,
	lowlandAerialRecoveryRaised: true,
	lowlandEcotoneRecoveryRaised: true,
	fullWorldVegetationReadabilityRaised: true,
	aerialEcotoneClarityRaised: true,
	fullWorldLowlandDomainRecoveryRaised: true,
	lowlandBiomeDomainSeparationRaised: true,
	fullWorldLowlandValueSeparationRaised: true,
	directionalDomainReadabilityRaised: true,
	materialDomainDepthRaised: true,
	wetLithicSeparationRaised: true,
	lowlandAerialDomainContrastRaised: true,
	lowlandDistanceReadabilityRaised: true,
	aerialMaterialContrastRaised: true,
	fullWorldDomainClarityRaised: true,
	naturalPigmentCalibration: true,
	highDistanceChannelExtremesReduced: true,
	coastalCyanBalanceRaised: true,
	naturalLowlandValueSeparationRaised: true,
	wetVegetationShadowDepthRaised: true,
	dryMineralHighlightSeparationRaised: true,
	lowlandMaterialReliefRaised: true,
	distantLowlandContrastRaised: true,
	naturalWaterDepthHierarchyRaised: true,
	lakeRiverOpticalSeparationRaised: true,
	openSeaSlateDepthRaised: true,
	aerialWaterSeparationRaised: true,
	roadMaterialHierarchyRaised: true,
	roadDustOrangeCastReduced: true,
	roadStoneRutSeparationRaised: true,
	riverReachValueSeparationRaised: true,
	waterfallAerationContrastRaised: true,
	plungePoolDepthRaised: true,
	fullWorldTerrainMaterialHierarchyRaised: true,
	meadowDrylandValueSeparationRaised: true,
	lithologyShadowSeparationRaised: true,
	shallowSedimentOpticalSeparationRaised: true,
	lakeMarineHueDecorrelationRaised: true,
	riverPoolRapidEnergySeparationRaised: true,
	waterfallPlungeFoamValueRangeRaised: true,
	aerialOpenWaterMidtoneRaised: true,
	openWaterFabricVisibilityRaised: true,
	weatheredStoneNeutralityRaised: true,
	wetGroundBlackCrushReduced: true,
	dryGroundOrangeCastReduced: true,
	lowlandWetDryLumaGapRaised: true,
	vegetationMineralHueGapRaised: true,
	aerialWaterNormalReadabilitySupported: true,
	openSeaMidtoneHeadroomRaised: true,
	terrainWaterValueCollisionReduced: true,
	fullWorldGreyBeigeCompressionReduced: true,
	openSeaAerialBlackCrushReduced: true,
	lowlandSoilStoneValueGapRaised: true,
	wetOrganicCoolBiasRaised: true,
	dryHeatherDustCastReduced: true,
	lowlandMaterialReliefContrastRaised: true,
	lithologyAerialRangeRaised: true,
	lowlandAerialSeparationRaised: true,
	wetDryMineralDistanceGapRaised: true,
	rockShadowBlackCrushReduced: true,
	weatheredRockWarmthRaised: true,
	lowlandMineralNeutralityRaised: true,
	fullWorldKhakiCompressionReduced: true,
	weatheredRockMidtoneRecoveryRaised: true,
	lowlandVegetationEarthHueGapRaised: true,
	weatheredRockFacetRangeRaised: true,
	wetBasaltSpecularHeadroomRaised: true,
	roadCompactionRutDepthRaised: true,
	roadDustStoneHueDecorrelationRaised: true,
	fullWorldLowlandDomainDepthRaised: true,
	lowlandWetDryMineralTriadRaised: true,
	distantMeadowEarthSeparationRaised: true,
	aerialMeadowShadowDepthRaised: true,
	dryHeathMineralWarmthRaised: true,
	weatheredGraniteFacetClarityRaised: true,
	deepSeaMesoFabricHeadroomRaised: true,
	weatheredMaterialDepthRaised: true,
	roadRutMoistureDepthRaised: true,
	riverRapidFoamSeparationRaised: true,
	coastalShallowSedimentReadabilityRaised: true,
	fullWorldWeatheredSeparationRaised: true,
	lowlandMineralHighlightHeadroomRaised: true,
	roadWearValueRangeRaised: true,
	riverAerationValueRangeRaised: true,
	distantWaterMesoReadabilityRaised: true,
	openSeaLakeHueGapRaised: true,
	riverPlungeEnergyReadabilityRaised: true,
	weatheredRoadNeutralityRaised: true,
	distantTerrainReliefSeparationRaised: true,
	lowlandKhakiCollapseReduced: true,
	openWaterDepthGradientRaised: true,
	roadEarthStoneDistanceGapRaised: true,
	lowlandOpticalDepthRaised: true,
	wetMeadowMineralContrastRaised: true,
	distantRockFacetClarityRaised: true,
	weatheredDomainDepthRaised: true,
	lowlandWetDryHueDecorrelationRaised: true,
	rockSoilMidtoneCollisionReduced: true,
	fullWorldAerialDomainSeparationRaised: true,
	meadowMineralHueGapRaised: true,
	weatheredRockValueRangeRaised: true,
	weatheredGroundHueDecorrelationRaised: true,
	distantLithologyMidtoneGapRaised: true,
	aerialKhakiSuppressionRaised: true,
	distantMeadowHeathHueGapRaised: true,
	distantWeatheredSurfaceSeparationRaised: true,
	waterLandMidtoneCollisionReduced: true,
	biomePigmentDistanceDepthRaised: true,
	weatheredLithologyCoolWarmRangeRaised: true,
	roadWearNeutralValueDepthRaised: true,
	openWaterSlateHierarchyRefined: true,
	aerialBiomePigmentRangeRaised: true,
	weatheredRockFacetDistanceRangeRaised: true,
	openWaterAerialValueRangeRaised: true,
	lowlandPigmentCompressionReduced: true,
	wetStoneMineralValueGapRaised: true,
	broadPlainMaterialDepthRaised: true,
	broadPlainKhakiCollapseReduced: true,
	broadPlainOpticalDepthRaised: true,
	broadPlainWetDryLumaGapRaised: true,
	broadPlainLithologySeparationRaised: true,
	broadPlainRockSoilMidtoneGapRaised: true,
	broadPlainWetOrganicDepthRaised: true,
	broadPlainDistanceMaterialReadRaised: true,
	broadPlainMeadowShadowDepthRaised: true,
	broadPlainWeatheredRockRangeRaised: true,
	broadPlainNaturalValueDepthRaised: true,
	broadPlainWetMineralHueGapRaised: true,
	broadPlainPigmentDepthRaised: true,
	broadPlainHeathNeutralityRaised: true,
	broadPlainRockFacetMidtoneRangeRaised: true,
	assetReferences: Object.freeze([
		'assets/models/fbx/dirt_road_test.glb',
		'assets/models/fbx/road_terrain.glb',
		'assets/models/fbx/rocky_terrain_low_poly.glb',
		'assets/models/fbx/rugged_mountain_landscape.glb',
	]),
	calibration: Object.freeze({
		terrain: 'v146 keeps canonical geography untouched and responds to the opened v144/v145 full-world artifacts: meadow shadow is slightly deeper and cooler, weathered heath is moved away from the grey-khaki midpoint, wet organic earth gains cool readable depth, exposed mineral soil loses chalky brightness, and granite/basalt facets preserve coherent luminance ordering while retaining a broader weathered midtone range. World-space normal/roughness remains the physical relief authority.',
		water: 'v146 retains the v136 shore/lake/river/open-sea hierarchy; coverage, bathymetry, hydrology and foam authority are unchanged.',
		road: 'v146 keeps compacted earth, moist ruts, dust and embedded stone neutral and separated at distance; route topology, width, terrain sampling and water exclusion are unchanged.',
		celestial: 'v146 preserves restrained dawn/noon/sunset/moon calibration and does not alter the day clock or lighting authority.',
	}),
});

export const GEOGRAPHIC_REFERENCE_PALETTE = Object.freeze({
	terrain: Object.freeze({
		mossShadow: 0x082b20,
		meadow: 0x073825,
		dryHeather: 0x65635c,
		wetEarth: 0x173832,
		exposedEarth: 0xb49f7d,
		graniteShadow: 0x324b5b,
		graniteSunlit: 0xc7c0b5,
		basaltWet: 0x22464d,
		quartz: 0xdedbd2,
	}),
	road: Object.freeze({
		compacted: 0x584f48,
		rut: 0x252e2b,
		dust: 0x918d87,
		stone: 0x9fa19f,
		mossEdge: 0x34533c,
	}),
	water: Object.freeze({
		shoreClear: 0x729d98,
		lakeClear: 0x3c7688,
		riverPool: 0x2f6979,
		rapid: 0xb5cdcd,
		deepSea: 0x2e657f,
		abyss: 0x092a3e,
		plunge: 0x4a8496,
		splash: 0xf0f7f4,
		foam: 0xf6fbf8,
	}),
	celestial: Object.freeze({
		dawn: 0xffae63,
		noon: 0xffefd6,
		sunset: 0xff8750,
		moon: 0xc6d8f6,
	}),
});

export function hexToLinearTriplet(hex) {
	const channel = (shift) => ((hex >> shift) & 0xff) / 255;
	const linear = (value) => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
	return Object.freeze([linear(channel(16)), linear(channel(8)), linear(channel(0))]);
}

export function relativeLuminanceFromHex(hex) {
	const [r, g, b] = hexToLinearTriplet(hex);
	return r * 0.2126 + g * 0.7152 + b * 0.0722;
}
