const EPSILON = 1e-6;
const LIMITS = Object.freeze({ minOpacity: 0.22, maxOpacity: 0.92, minRoughness: 0.08, maxRoughness: 0.72, maxNormalEnergy: 0.42, maxFoam: 0.38, maxCyan: 0.68, maxMicroScale: 0.075, maxRefreshBatch: 48 });
const WATER_CLASSES = new Set(["sea", "lake", "river", "water", "shore"]);
const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
const finite = (v, f = 0) => Number.isFinite(Number(v)) ? Number(v) : f;
const positive = (v, f = 0) => Math.max(0, finite(v, f));
const smoothstep = (a, b, v) => { const t = clamp((v - a) / Math.max(EPSILON, b - a), 0, 1); return t * t * (3 - 2 * t); };
const stableNumber = (v, d = 6) => Number(finite(v).toFixed(d));
function hash2D(x, y, seed = 0) { let h = 2166136261 ^ (seed | 0); h ^= Math.floor(finite(x) * 4096); h = Math.imul(h, 16777619); h ^= Math.floor(finite(y) * 4096); h = Math.imul(h, 16777619); h ^= h >>> 13; h = Math.imul(h, 1274126177); h ^= h >>> 16; return (h >>> 0) / 0xffffffff; }
function normalizeClass(v) { const n = String(v ?? "").trim().toLowerCase(); return WATER_CLASSES.has(n) ? n : "unknown"; }
function isWaterSample(sample = {}) { const klass = normalizeClass(sample.waterClass ?? sample.bodyClass); const coverage = clamp(finite(sample.waterCoverage, finite(sample.coverage)), 0, 1); const depth = positive(sample.depth, positive(sample.waterDepth)); const confidence = clamp(finite(sample.waterConfidence, finite(sample.confidence, 1)), 0, 1); const dry = sample.isWater === false || sample.land === true || finite(sample.waterCoverage, NaN) === 0; const candidate = klass !== "unknown" || sample.isWater === true || depth > EPSILON || coverage > EPSILON; return { accepted: candidate && !dry && confidence >= 0.45, klass, coverage, depth, confidence }; }
function classifyDepth(depth, shorelineDistance, coverage) { const shore = smoothstep(0, 7, positive(shorelineDistance)); const shallow = smoothstep(0.02, 1.8, depth) * (1 - shore * 0.35); const deep = smoothstep(2, 12, depth) * (0.72 + coverage * 0.28); const wetEdge = (1 - smoothstep(0, 2.5, positive(shorelineDistance))) * (1 - deep * 0.4); const foamCarrier = clamp((1 - smoothstep(0.2, 5, positive(shorelineDistance))) * (0.18 + shallow * 0.55), 0, 1); const sum = Math.max(EPSILON, shore + shallow + deep + wetEdge); return { shore: shore / sum, shallow: shallow / sum, deep: deep / sum, wetEdge: wetEdge / sum, foamCarrier }; }
function computeWorldPhase(sample, seed = 17) { const x = finite(sample.x, finite(sample.position?.x)); const z = finite(sample.z, finite(sample.position?.z, finite(sample.y))); const a = hash2D(x * 0.018, z * 0.013, seed); const b = hash2D(x * 0.031 + 19.7, z * 0.021 - 7.3, seed + 101); const c = hash2D(x * 0.047 - 11.3, z * 0.029 + 5.9, seed + 211); return { phaseA: stableNumber(a), phaseB: stableNumber(b), phaseC: stableNumber(c), rotationA: stableNumber((a * Math.PI * 2) % Math.PI), rotationB: stableNumber((b * Math.PI * 2) % Math.PI), rotationC: stableNumber((c * Math.PI * 2) % Math.PI) }; }
function deriveWaterResponse(sample = {}, options = {}) { const state = isWaterSample(sample); if (!state.accepted) return Object.freeze({ accepted: false, reason: "not-proven-water", waterClass: state.klass, coverage: stableNumber(state.coverage), confidence: stableNumber(state.confidence), risk: Object.freeze({ rectangularWater: 0, hardShoreline: 0, moire: 0, cyanCast: 0 }) }); const shorelineDistance = positive(sample.shorelineDistance, positive(sample.distanceToShore)); const bands = classifyDepth(state.depth, shorelineDistance, state.coverage); const distance = positive(options.cameraDistance, positive(sample.cameraDistance, 24)); const cameraFade = 1 - smoothstep(70, 420, distance); const worldPhase = computeWorldPhase(sample, finite(options.seed, 17)); const antiMoiré = clamp(0.56 + 0.17 * worldPhase.phaseA + 0.13 * worldPhase.phaseB + 0.11 * worldPhase.phaseC, 0.56, 0.95); const normalEnergy = clamp((0.13 + bands.shallow * 0.12 + bands.foamCarrier * 0.09) * cameraFade, 0.035, LIMITS.maxNormalEnergy); const roughness = clamp(0.2 + bands.deep * 0.24 + bands.wetEdge * 0.12 - bands.foamCarrier * 0.06, LIMITS.minRoughness, LIMITS.maxRoughness); const opacity = clamp(0.48 + bands.deep * 0.26 + bands.shallow * 0.06 - bands.wetEdge * 0.08, LIMITS.minOpacity, LIMITS.maxOpacity); const cyanSuppression = clamp(0.42 + bands.shore * 0.18 + bands.shallow * 0.24, 0, LIMITS.maxCyan); const foam = clamp(bands.foamCarrier * 0.42, 0, LIMITS.maxFoam); const microScale = clamp(LIMITS.maxMicroScale * (0.55 + antiMoiré * 0.4) * (0.5 + cameraFade * 0.5), 0.01, LIMITS.maxMicroScale); return Object.freeze({ accepted: true, waterClass: state.klass === "unknown" ? "water" : state.klass, coverage: stableNumber(state.coverage), confidence: stableNumber(state.confidence), depth: stableNumber(state.depth), shorelineDistance: stableNumber(shorelineDistance), bands: Object.freeze(Object.fromEntries(Object.entries(bands).map(([k, v]) => [k, stableNumber(v)]))), material: Object.freeze({ opacity: stableNumber(opacity), roughness: stableNumber(roughness), normalEnergy: stableNumber(normalEnergy), cyanSuppression: stableNumber(cyanSuppression), foam: stableNumber(foam), microScale: stableNumber(microScale), antiMoiré: stableNumber(antiMoiré) }), worldPhase: Object.freeze(worldPhase), risk: Object.freeze({ rectangularWater: state.coverage >= 0.96 ? 1 : 0, hardShoreline: shorelineDistance <= 0.25 && bands.shore < 0.18 ? 1 : 0, moire: antiMoiré < 0.61 ? 1 : 0, cyanCast: cyanSuppression >= LIMITS.maxCyan ? 1 : 0 }) }); }
function stableStringify(value) { if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${stableStringify(value[k])}`).join(",")}}`; return JSON.stringify(value); }
function digest(value) { const text = stableStringify(value); let hash = 2166136261; for (let i = 0; i < text.length; i += 1) { hash ^= text.charCodeAt(i); hash = Math.imul(hash, 16777619); } return `water-p0-${(hash >>> 0).toString(16).padStart(8, "0")}`; }
function applyBoundedWaterMaterial(material, response) { if (!material || !response?.accepted) return { applied: false, reason: "missing-material-or-response" }; const before = { opacity: finite(material.opacity, 1), roughness: finite(material.roughness, 0.5), normalScale: finite(material.normalScale?.x, finite(material.normalEnergy, 0.1)) }; material.transparent = true; material.opacity = response.material.opacity; material.roughness = response.material.roughness; if (material.normalScale && typeof material.normalScale.set === "function") material.normalScale.set(response.material.normalEnergy, response.material.normalEnergy); else if ("normalEnergy" in material) material.normalEnergy = response.material.normalEnergy; material.userData = { ...(material.userData ?? {}), worldP0WaterAdoption: { digest: digest(response), waterClass: response.waterClass, antiMoiré: response.material.antiMoiré, cyanSuppression: response.material.cyanSuppression } }; return { applied: true, before, after: { opacity: stableNumber(material.opacity), roughness: stableNumber(material.roughness), normalEnergy: stableNumber(material.normalEnergy, response.material.normalEnergy) }, digest: digest(response) }; }
function summarizeBatch(samples, options = {}) { const list = Array.isArray(samples) ? samples : []; const max = clamp(Math.floor(finite(options.maxBatch, LIMITS.maxRefreshBatch)), 1, LIMITS.maxRefreshBatch); const selected = list.slice(0, max); const responses = selected.map(s => deriveWaterResponse(s, options)); const risks = responses.reduce((acc, r) => { for (const key of Object.keys(acc)) acc[key] += r.risk?.[key] ?? 0; return acc; }, { rectangularWater: 0, hardShoreline: 0, moire: 0, cyanCast: 0 }); const accepted = responses.filter(r => r.accepted).length; return Object.freeze({ requested: list.length, evaluated: selected.length, accepted, rejected: selected.length - accepted, riskCounts: Object.freeze(risks), targetBreaches: Object.freeze({ visibleRectangularWater: risks.rectangularWater, visibleHardShoreline: risks.hardShoreline, visibleWaterMoire: risks.moire, visibleCyanCast: risks.cyanCast }), responses: Object.freeze(responses), digest: digest({ responses, risks, evaluated: selected.length }) }); }
function createAcceptanceManifest(options = {}) { const manifest = { owner: "Buzul Muhafızı", scope: "P0 water-surface adoption", source: "shipped createScene() caller-owned water observations", contract: "MaterialAssignmentCore + WorldAssetPlacementPipeline remains authoritative for model-bearing placement", editorRuntimeImport: false, geometryCreation: false, canonicalHydrologyMutation: false, acceptance: { resolution: "1536x1024", camera: "orthographic-90-degree", views: ["full-world", "far", "terrain-level-near", "coast", "mountain"], beforeAfterComparable: true, visibleTargets: { rectangularWater: 0, seam: 0, moire: 0, blackSky: 0, floatingAsset: 0 } }, limits: LIMITS, options: { seed: finite(options.seed, 17), maxBatch: clamp(Math.floor(finite(options.maxBatch, LIMITS.maxRefreshBatch)), 1, LIMITS.maxRefreshBatch) } }; return Object.freeze({ ...manifest, digest: digest(manifest) }); }
export { LIMITS, applyBoundedWaterMaterial, classifyDepth, createAcceptanceManifest, deriveWaterResponse, digest, isWaterSample, summarizeBatch };
