import { resolveTerrainSedimentState, resolveTerrainSedimentMaterialResponse } from './terrainSurfaceSediment.js';
import { resolveSeasonalErosionState, seasonalErosionMaterialResponse, TERRAIN_SEASONAL_CYCLE_SCHEMA, TERRAIN_SEASONAL_CYCLE_CANONICAL_INVARIANTS } from './terrainSeasonalErosionCycle.js';
const f=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d; const c=v=>Math.max(0,Math.min(1,f(v))); const z=v=>Object.freeze(v);
export const TERRAIN_SEASONAL_EROSION_ADAPTER_POLICY=z({id:'terrain-seasonal-erosion-adapter-2026-09-15-v1',renderOnly:true,deterministic:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,preservesSedimentState:true,preservesBaseMaterial:true,materialKey:'terrain-seasonal-erosion-adapter-v1'});
function mix(a,b,t){const q=c(t);return z({r:a.r+(b.r-a.r)*q,g:a.g+(b.g-a.g)*q,b:a.b+(b.b-a.b)*q});}
export function resolveTerrainSeasonalErosionStack(input={}){const base=input.baseColor??{r:.5,g:.45,b:.38},rough=f(input.baseRoughness,.86),sediment=resolveTerrainSedimentState(input),seasonal=resolveSeasonalErosionState(input),sm=resolveTerrainSedimentMaterialResponse({state:sediment,baseColor:base,baseRoughness:rough}),ym=seasonalErosionMaterialResponse({state:seasonal,baseColor:base,baseRoughness:rough}),weight=c(.32+seasonal.seasonalAge*.44+seasonal.frostWear*.14+seasonal.erosion*.10),color1=mix(base,ym.color,weight),color=mix(color1,sm.color,c(weight*.72)),material=z({color,roughness:c(rough+(ym.roughness-rough)*weight+(sm.roughness-rough)*Math.min(1,weight*.65)),normalStrength:c(f(input.baseNormalStrength)+ym.normalStrength*weight+sm.normalStrength*Math.min(1,weight*.72)),specularDamping:c(ym.specularDamping*weight)});return z({sediment,seasonal,sedimentMaterial:sm,seasonalMaterial:ym,material,visualWeight:weight,policyId:TERRAIN_SEASONAL_EROSION_ADAPTER_POLICY.id,schemaVersion:TERRAIN_SEASONAL_CYCLE_SCHEMA.version,canonicalInvariants:TERRAIN_SEASONAL_CYCLE_CANONICAL_INVARIANTS});}
export const resolveTerrainSeasonalErosionMaterial=input=>resolveTerrainSeasonalErosionStack(input).material;
export function seasonalErosionCacheKey(input={}){return `${TERRAIN_SEASONAL_EROSION_ADAPTER_POLICY.materialKey}|${f(input.worldX).toFixed(2)}|${f(input.worldZ).toFixed(2)}|${Math.floor(f(input.dayOfYear,180))}|${c(input.moisture).toFixed(3)}|${c(input.windExposure).toFixed(3)}|${Math.floor(f(input.profileIndex))}`;}
export function seasonalErosionDeterministicProbe(input={}){const a=resolveTerrainSeasonalErosionStack(input),b=resolveTerrainSeasonalErosionStack(input),k=seasonalErosionCacheKey(input);return z({stable:JSON.stringify(a.material)===JSON.stringify(b.material)&&k===seasonalErosionCacheKey(input),cacheKey:k,material:a.material,seasonalAge:a.seasonal.seasonalAge});}
export function validateTerrainSeasonalErosionIntegration(result){const e=[];if(!result?.seasonal?.canonicalTerrainUntouched)e.push('seasonal-boundary-missing');if(result?.policyId!==TERRAIN_SEASONAL_EROSION_ADAPTER_POLICY.id)e.push('adapter-policy-mismatch');if(result?.schemaVersion!==1)e.push('schema-version-mismatch');if(!Array.isArray(result?.canonicalInvariants)||result.canonicalInvariants.length<5)e.push('canonical-invariants-missing');return z({ok:e.length===0,errors:z(e)});}
export function buildSeasonalErosionMaterialCatalog(points=[]){return z(points.map(point=>{const r=resolveTerrainSeasonalErosionStack(point);return z({cacheKey:seasonalErosionCacheKey(point),point:z({worldX:f(point.worldX),worldZ:f(point.worldZ),dayOfYear:Math.floor(f(point.dayOfYear,180))}),material:r.material,seasonal:z({season:r.seasonal.season,erosion:r.seasonal.erosion,frostWear:r.seasonal.frostWear,seasonalAge:r.seasonal.seasonalAge})});}));}
export function compareSeasonalMaterialBeforeAfter(before,after){const keys=['roughness','normalStrength','specularDamping'],deltas={},maxScalar=keys.reduce((m,k)=>{const d=f(after?.[k])-f(before?.[k]);deltas[k]=d;return Math.max(m,Math.abs(d));},0),maxColor=Math.max(...['r','g','b'].map(k=>Math.abs(f(after?.color?.[k])-f(before?.color?.[k]))));return z({scalarDelta:z(deltas),maxScalar,maxColor,changed:maxScalar>.0001||maxColor>.0001});}
export const TERRAIN_SEASONAL_EROSION_ADAPTER_SCHEMA=z({version:1,requiredInput:z(['worldX','worldZ','dayOfYear','heightMeters','slopeDegrees']),optionalInput:z(['moisture','rainfall','snowWeight','windExposure','drainage','canopy','climate','temperatureC','substrate','profileIndex','frozenDays','dryDays']),outputs:z(['sediment','seasonal','sedimentMaterial','seasonalMaterial','material','visualWeight'])});
