/** Macro geographic anchor system for environment distribution. Anchors never instantiate assets or mutate terrain. */
import { environmentSpatialNoise, deterministicSpatialOrdinal } from './terrainEnvironmentSpatialPolicy.js';
import { geologyResponseAtWorld } from './terrainEnvironmentGeologyResponse.js';
import { seasonalGeometryEnvelope } from './terrainEnvironmentSeasonalGeography.js';
const freeze=(v)=>Object.freeze(v); const norm=(v)=>String(v??'').trim().toLowerCase(); const finite=(v,f=0)=>Number.isFinite(v)?v:f; const clamp01=(v)=>Math.max(0,Math.min(1,finite(v)));
export const TERRAIN_ENVIRONMENT_GEOGRAPHIC_ANCHOR_POLICY=freeze({id:'terrain-environment-geographic-anchors-2026-09-08-v2',deterministic:true,worldSpace:true,authoredOnly:true,noGeometryCreation:true,noTerrainMutation:true,noHydrologyMutation:true,noColliderMutation:true,anchorFamilies:freeze(['forest-core','forest-edge','meadow-basin','heath-ridge','tundra-shelf','alpine-scarp','dry-rock','wetland-margin','settlement-buffer','water-margin']),minimumAnchorSpacingMeters:180,maximumInfluenceMeters:920});
const ANCHOR_PROFILES=freeze({'forest-core':freeze({tree:1,deadTree:.18,shrub:.46,grass:.62,rock:.20,slopeMin:2,slopeMax:29,moistureMin:.42,moistureMax:.92}),'forest-edge':freeze({tree:.66,deadTree:.24,shrub:.60,grass:.76,rock:.42,slopeMin:3,slopeMax:38,moistureMin:.28,moistureMax:.84}),'meadow-basin':freeze({tree:.22,deadTree:.08,shrub:.36,grass:1,rock:.08,slopeMin:0,slopeMax:18,moistureMin:.32,moistureMax:.88}),'heath-ridge':freeze({tree:.30,deadTree:.28,shrub:.70,grass:.62,rock:.64,slopeMin:6,slopeMax:41,moistureMin:.12,moistureMax:.66}),'tundra-shelf':freeze({tree:.06,deadTree:.56,shrub:.22,grass:.40,rock:.72,slopeMin:0,slopeMax:42,moistureMin:.12,moistureMax:.76}),'alpine-scarp':freeze({tree:.02,deadTree:.42,shrub:.08,grass:.14,rock:1,slopeMin:18,slopeMax:64,moistureMin:.04,moistureMax:.72}),'dry-rock':freeze({tree:.04,deadTree:.20,shrub:.24,grass:.22,rock:.94,slopeMin:4,slopeMax:58,moistureMin:.01,moistureMax:.48}),'wetland-margin':freeze({tree:.18,deadTree:.22,shrub:.66,grass:.86,rock:.10,slopeMin:0,slopeMax:12,moistureMin:.68,moistureMax:1}),'settlement-buffer':freeze({tree:.28,deadTree:.10,shrub:.34,grass:.58,rock:.16,slopeMin:0,slopeMax:20,moistureMin:.12,moistureMax:.82}),'water-margin':freeze({tree:.12,deadTree:.16,shrub:.46,grass:.72,rock:.28,slopeMin:0,slopeMax:26,moistureMin:.54,moistureMax:1})});
function anchorCenters(worldWidthMeters,worldDepthMeters,seed,count=24){const centers=[];const columns=Math.max(3,Math.ceil(Math.sqrt(count*worldWidthMeters/Math.max(1,worldDepthMeters))));const rows=Math.max(3,Math.ceil(count/columns));for(let row=0;row<rows;row++){for(let column=0;column<columns;column++){if(centers.length>=count)break;const jx=(environmentSpatialNoise(column*.41+seed*.001,row*.37+seed*.002)-.5)*.72;const jz=(environmentSpatialNoise(column*.27+seed*.003,row*.59+seed*.004)-.5)*.72;centers.push(freeze({index:centers.length,nx:clamp01((column+.5+jx)/columns),nz:clamp01((row+.5+jz)/rows)}));}}return freeze(centers);}
export function buildGeographicAnchors({worldWidthMeters=9000,worldDepthMeters=7000,seed=20260908,count=30}={}){return freeze(anchorCenters(worldWidthMeters,worldDepthMeters,seed,count).map((center)=>{const x=(center.nx-.5)*worldWidthMeters,z=(center.nz-.5)*worldDepthMeters,n=environmentSpatialNoise(x*.0017+seed,z*.0017-seed),selector=environmentSpatialNoise(x*.00073-seed,z*.00113+seed);const family=selector<.18?'forest-core':selector<.32?'forest-edge':selector<.48?'meadow-basin':selector<.60?'heath-ridge':selector<.72?'tundra-shelf':selector<.83?'alpine-scarp':selector<.91?'dry-rock':selector<.96?'wetland-margin':selector<.985?'settlement-buffer':'water-margin';return freeze({index:center.index,family,x,z,radiusMeters:260+n*520,strength:.52+n*.48,profile:ANCHOR_PROFILES[family]});}));}
function radialInfluence(anchor,x,z){return clamp01(1-Math.hypot(x-anchor.x,z-anchor.z)/anchor.radiusMeters)**1.7*anchor.strength;}
export function sampleGeographicAnchorField({x=0,z=0,anchors=[]}={}){const contributions=anchors.map((anchor)=>({anchor,influence:radialInfluence(anchor,x,z)})).filter((entry)=>entry.influence>.025).sort((a,b)=>b.influence-a.influence),top=contributions.slice(0,5),totals={tree:0,deadTree:0,shrub:0,grass:0,rock:0};let totalInfluence=0;for(const entry of top){totalInfluence+=entry.influence;for(const [key,value] of Object.entries(entry.anchor.profile))if(key in totals)totals[key]+=value*entry.influence;}const scale=totalInfluence>0?1/totalInfluence:0;return freeze({x:finite(x),z:finite(z),dominantFamily:top[0]?.anchor?.family??null,dominantInfluence:top[0]?.influence??0,totalInfluence:clamp01(totalInfluence),density:freeze(Object.fromEntries(Object.entries(totals).map(([key,value])=>[key,clamp01(value*scale)]))),contributors:freeze(top.map((entry)=>freeze({family:entry.anchor.family,influence:entry.influence,radiusMeters:entry.anchor.radiusMeters})))});}
export function buildAnchorAwareEnvironmentSample({x=0,z=0,sample={},anchors=[]}={}){const anchorField=sampleGeographicAnchorField({x,z,anchors});const geology=geologyResponseAtWorld({worldX:x,worldZ:z,sample});const season=seasonalGeometryEnvelope({season:sample.season??'spring',biome:sample.biome??anchorField.dominantFamily,category:sample.category??'tree',sample});const category=norm(sample.category||'tree');const anchorDensity=['rock','cliff','scree'].includes(category)?anchorField.density.rock:category==='dead-tree'?anchorField.density.deadTree:category==='shrub'?anchorField.density.shrub:category==='grass'?anchorField.density.grass:anchorField.density.tree;return freeze({anchorField,geology,season,category,density:clamp01(anchorDensity*.56+geology.density*.26+season.densityFactor*.18),deterministicOrdinal:deterministicSpatialOrdinal(category,x,z)});}
export function rankAnchorFamiliesAtWorld({x=0,z=0,sample={},anchors=[]}={}){return freeze(anchors.map((anchor)=>({anchor,influence:radialInfluence(anchor,x,z)})).filter((entry)=>entry.influence>0).sort((a,b)=>b.influence-a.influence||a.anchor.family.localeCompare(b.anchor.family)).map((entry)=>freeze({family:entry.anchor.family,influence:entry.influence,compatibility:clamp01(entry.influence*(entry.anchor.profile.moistureMin<=finite(sample.moisture,.5)&&entry.anchor.profile.moistureMax>=finite(sample.moisture,.5)?1:.34))})));}
export function geographicAnchorManifest(options={}){const anchors=buildGeographicAnchors(options);return freeze({policyId:TERRAIN_ENVIRONMENT_GEOGRAPHIC_ANCHOR_POLICY.id,count:anchors.length,anchors});}
export function validateGeographicAnchors(options={}){const anchors=buildGeographicAnchors(options),errors=[];if(!anchors.length)errors.push('no-anchors');for(const anchor of anchors){if(!ANCHOR_PROFILES[anchor.family])errors.push(`unknown-family:${anchor.family}`);if(!Number.isFinite(anchor.x)||!Number.isFinite(anchor.z))errors.push(`non-finite-anchor:${anchor.index}`);if(anchor.radiusMeters<TERRAIN_ENVIRONMENT_GEOGRAPHIC_ANCHOR_POLICY.minimumAnchorSpacingMeters*.75)errors.push(`anchor-radius-too-small:${anchor.index}`);}return freeze({ok:errors.length===0,errors:freeze(errors),count:anchors.length,policyId:TERRAIN_ENVIRONMENT_GEOGRAPHIC_ANCHOR_POLICY.id});}
