const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):0));
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const freeze=v=>Object.freeze(v);
const smooth=(a,b,v)=>{const t=clamp((finite(v)-a)/Math.max(1e-6,b-a));return t*t*(3-2*t);};
const mix=(a,b,t)=>a+(b-a)*t;
const hash=(x,z,s=0x7711)=>{let h=Math.imul((x|0)^s,0x45d9f3b)^Math.imul((z|0)+s,0x119de1f3);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return(h>>>0)/4294967296;};
const noise=(x,z,s=0x7712)=>{const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,u=fx*fx*(3-2*fx),v=fz*fz*(3-2*fz);return mix(mix(hash(ix,iz,s),hash(ix+1,iz,s),u),mix(hash(ix,iz+1,s),hash(ix+1,iz+1,s),u),v);};
const fbm=(x,z,s=0x7713,n=4)=>{let out=0,w=0,a=.55;for(let i=0;i<n;i++){out+=noise(x,z,s+i*97)*a;w+=a;x=x*2.01+13.7;z=z*2.03-9.1;a*=.48;}return out/Math.max(1e-6,w);};
const ridge=(x,z,s)=>1-Math.abs(fbm(x,z,s)*2-1);
export const TERRAIN_GROUNDWATER_POLICY=freeze({id:'terrain-groundwater-surface-2026-09-15-v1',deterministic:true,renderOnly:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,depthMeters:84,capillaryMeters:11,seepageBandMeters:8,springBandMeters:5,materialKey:'terrain-groundwater-surface-v1'});
export const TERRAIN_GROUNDWATER_CANONICAL_INVARIANTS=freeze(['canonicalHeightUnchanged','canonicalHydrologyUnchanged','canonicalCoastlineUnchanged','canonicalColliderUnchanged','canonicalVegetationPlacementUnchanged','newGeographyIntroduced:false']);
export const TERRAIN_GROUNDWATER_SUBSTRATES=freeze({granite:freeze({storage:.38,permeability:.31,capillary:.18,fracture:.22,retention:.46}),limestone:freeze({storage:.44,permeability:.62,capillary:.21,fracture:.54,retention:.39}),sandstone:freeze({storage:.58,permeability:.71,capillary:.26,fracture:.37,retention:.33}),shale:freeze({storage:.47,permeability:.18,capillary:.49,fracture:.28,retention:.58}),schist:freeze({storage:.41,permeability:.33,capillary:.31,fracture:.43,retention:.49}),clay:freeze({storage:.72,permeability:.12,capillary:.68,fracture:.10,retention:.74}),silt:freeze({storage:.66,permeability:.36,capillary:.57,fracture:.16,retention:.63}),sand:freeze({storage:.52,permeability:.82,capillary:.17,fracture:.08,retention:.29}),gravel:freeze({storage:.48,permeability:.91,capillary:.09,fracture:.05,retention:.22}),peat:freeze({storage:.81,permeability:.24,capillary:.76,fracture:.07,retention:.86}),alluvium:freeze({storage:.69,permeability:.67,capillary:.43,fracture:.11,retention:.62}),colluvium:freeze({storage:.55,permeability:.49,capillary:.35,fracture:.18,retention:.51}),tuff:freeze({storage:.46,permeability:.29,capillary:.38,fracture:.47,retention:.52}),mudstone:freeze({storage:.63,permeability:.16,capillary:.61,fracture:.15,retention:.68}),marl:freeze({storage:.59,permeability:.28,capillary:.53,fracture:.22,retention:.61}),chalk:freeze({storage:.43,permeability:.75,capillary:.24,fracture:.48,retention:.35})});
const substrateKey=v=>String(v??'alluvium').trim().toLowerCase().replace(/[^a-z]/g,'');
const substrateAt=v=>TERRAIN_GROUNDWATER_SUBSTRATES[substrateKey(v)]??TERRAIN_GROUNDWATER_SUBSTRATES.alluvium;
export function normalizedGroundwaterSample(input={}){return freeze({worldX:finite(input.worldX),worldZ:finite(input.worldZ),heightMeters:finite(input.heightMeters),slopeDegrees:clamp(input.slopeDegrees,0,90),moisture:clamp(input.moisture,.5),rainfall:clamp(input.rainfall,.5),runoff:clamp(input.runoff),soilDepth:clamp(input.soilDepth,.5),waterDistance:Math.max(0,finite(input.waterDistance,99999)),waterElevation:finite(input.waterElevation,-99999),substrate:substrateKey(input.substrate),vegetationCover:clamp(input.vegetationCover,.5),canopy:clamp(input.canopy,.4),temperatureC:finite(input.temperatureC,11),windExposure:clamp(input.windExposure,.5),snowWeight:clamp(input.snowWeight),confidence:clamp(input.confidence,1)});}
export function rechargePotential(sample={},weather={}){const s=normalizedGroundwaterSample(sample),sub=substrateAt(s.substrate),rain=clamp(weather.rainfall??s.rainfall),storm=clamp(weather.stormPulse),slope=smooth(1.5,42,s.slopeDegrees),cover=s.vegetationCover,soil=s.soilDepth,rock=1-sub.storage,retained=clamp(rain*(.58+storm*.42)*(1-slope*.46)*(soil*.62+sub.capillary*.38));return freeze({rain,storm,slope,retained,infiltration:clamp((sub.permeability*.61+soil*.24+(1-rock)*.15)*(1-slope*.34)),recharge:clamp(retained*(sub.permeability*.58+sub.storage*.42)*(1-cover*.16)),surfaceRunoff:clamp(rain*(.52+storm*.48)*(slope*.68+rock*.32))});}
export function waterTableDepth({sample={},recharge={},regionalBaseMeters=38}={}){const s=normalizedGroundwaterSample(sample),sub=substrateAt(s.substrate),r=rechargePotential(s,recharge),terrainBand=smooth(0,TERRAIN_GROUNDWATER_POLICY.depthMeters,s.heightMeters),waterSignal=clamp(.28+s.moisture*.24+r.recharge*.34+(1-surfaceDistanceFactor(s))* .14),storage=clamp(sub.storage*.54+sub.retention*.28+sub.capillary*.18),depth=clamp((regionalBaseMeters+(terrainBand*.26))*(1-waterSignal*.56)*(1-storage*.22),2,TERRAIN_GROUNDWATER_POLICY.depthMeters);return freeze({depthMeters:depth,headMeters:s.heightMeters-depth,storage,waterSignal,recharge:r,reliable:r.recharge>.22});}
function surfaceDistanceFactor(s){return smooth(3,120,Math.min(s.waterDistance,120));}
export function capillaryRise({waterTable={},sample={}}={}){const s=normalizedGroundwaterSample(sample),sub=substrateAt(s.substrate),depth=finite(waterTable.depthMeters,40),porosity=clamp(sub.capillary*.66+sub.retention*.34),rise=clamp((1-smooth(0,TERRAIN_GROUNDWATER_POLICY.depthMeters,depth))*(0.26+porosity*.74));return freeze({rise,bandMeters:TERRAIN_GROUNDWATER_POLICY.capillaryMeters*rise,porosity,shallow:depth<18,visible:rise>.42});}
export function seepagePotential({sample={},waterTable={},recharge={}}={}){const s=normalizedGroundwaterSample(sample),sub=substrateAt(s.substrate),table=waterTable.depthMeters==null?waterTableDepth({sample:s,recharge}):waterTable,rise=capillaryRise({waterTable:table,sample:s}),slope=smooth(1.5,42,s.slopeDegrees),fracture=clamp(sub.fracture),perched=clamp((s.moisture*.42+table.recharge.recharge*.36+(1-slope)*.22)*(1-sub.permeability*.24));const band=clamp(rise.rise*.44+fracture*.31+perched*.25);return freeze({band,perched,seepage:clamp(band*(.38+sub.permeability*.34+(1-slope)*.28)),fracture,pathBias:clamp(fracture*.62+slope*.12),saturated:band>.58});}
export function springPotential({sample={},waterTable={},seepage={}}={}){const s=normalizedGroundwaterSample(sample),sub=substrateAt(s.substrate),table=waterTable.depthMeters==null?waterTableDepth({sample:s}):waterTable,sp=seepage.seepage==null?seepagePotential({sample:s,waterTable:table}):seepage,grade=clamp((1-smooth(6,52,s.slopeDegrees))*.38+sp.fracture*.24+sp.seepage*.38),elevationBias=clamp(1-smooth(-4,230,s.heightMeters)),source=clamp(grade*.58+elevationBias*.12+sub.fracture*.17+(1-table.depthMeters/84)*.13);return freeze({source,emergence:clamp(source*sp.seepage),flow:clamp(source*(.45+sp.pathBias*.55)),coolness:clamp((1-source)*.18+sp.seepage*.34),confidence:clamp(s.confidence*(.58+sub.storage*.42))});}
export function wetSurfaceResponse({sample={},waterTable={},seepage={},rainfall=null}={}){const s=normalizedGroundwaterSample(sample),table=waterTable.depthMeters==null?waterTableDepth({sample:s}):waterTable,sp=seepage.seepage==null?seepagePotential({sample:s,waterTable:table}):seepage,rain=rainfall==null?s.rainfall:clamp(rainfall),wet=clamp(s.moisture*.38+sp.seepage*.38+rain*.14+(1-table.depthMeters/84)*.10),sheen=clamp(wet*.42+sp.saturated*.38),mud=clamp(wet*(.32+(1-substrateAt(s.substrate).permeability)*.48)),standing=clamp(sp.perched*.42+(1-s.slopeDegrees/90)*.23+rain*.18),return freeze({wet,sheen,mud,standing,seepage:sp.seepage,waterTableDepth:table.depthMeters});}
export function groundwaterMaterialResponse({state,baseColor={r:.48,g:.42,b:.34},baseRoughness=.86}={}){if(!state)throw new TypeError('groundwater state required');const w=state.surface.wet,sh=state.surface.sheen,m=state.surface.mud,s=state.seepage.seepage,sp=state.spring.emergence,color=freeze({r:clamp(baseColor.r-m*.08+sh*.012+s*.004),g:clamp(baseColor.g-m*.045+sh*.018+sp*.006),b:clamp(baseColor.b+m*.018+sh*.042+sp*.035)}),roughness=clamp(baseRoughness-m*.10-sh*.04+s*.018),normalStrength=clamp(s*.028+m*.016+state.seasonalMemory*.018),waterline=clamp(w*.36+s*.42+sp*.22);return freeze({color,roughness,normalStrength,waterline,sheen:sh,mud:m,wet:w});}
export function resolveTerrainGroundwaterState(input={}){const s=normalizedGroundwaterSample(input),recharge=rechargePotential(s,input.weather??{}),table=waterTableDepth({sample:s,recharge,regionalBaseMeters:finite(input.regionalBaseMeters,38)}),capillary=capillaryRise({waterTable:table,sample:s}),seepage=seepagePotential({sample:s,waterTable:table,recharge}),spring=springPotential({sample:s,waterTable:table,seepage}),surface=wetSurfaceResponse({sample:s,waterTable:table,seepage,rainfall:input.weather?.rainfall??s.rainfall}),seasonalMemory=clamp(s.moisture*.42+recharge.recharge*.23+(1-surface.wet)*.21+capillary.rise*.14);return freeze({sample:s,recharge,waterTable:table,capillary,seepage,spring,surface,seasonalMemory,canonicalTerrainUntouched:true,policyId:TERRAIN_GROUNDWATER_POLICY.id});}
export function groundwaterSignature(input={}){const s=resolveTerrainGroundwaterState(input);return freeze({substrate:s.sample.substrate,depth:+s.waterTable.depthMeters.toFixed(6),recharge:+s.recharge.recharge.toFixed(6),seepage:+s.seepage.seepage.toFixed(6),spring:+s.spring.emergence.toFixed(6),wet:+s.surface.wet.toFixed(6),standing:+s.surface.standing.toFixed(6)});}
export function compareGroundwaterStates(a,b){const keys=['waterTable','recharge','seepage','spring','wetSurface'];const av={depth:a?.waterTable?.depthMeters??0,recharge:a?.recharge?.recharge??0,seepage:a?.seepage?.seepage??0,spring:a?.spring?.emergence??0,wetSurface:a?.surface?.wet??0};const bv={depth:b?.waterTable?.depthMeters??0,recharge:b?.recharge?.recharge??0,seepage:b?.seepage?.seepage??0,spring:b?.spring?.emergence??0,wetSurface:b?.surface?.wet??0};const deltas=freeze(Object.fromEntries(Object.entries(av).map(([k,v])=>[k: bv[k]-v])));return freeze({keys,deltas,maxAbs:Math.max(...Object.values(deltas).map(Math.abs)),materiallyDifferent:Math.max(...Object.values(deltas).map(Math.abs))>.08});}
export function validateGroundwaterState(state){const errors=[];for(const k of ['recharge','seepage','spring','surface']){if(state?.[k]==null)errors.push(`${k}-missing`);}for(const [k,v] of Object.entries({recharge:state?.recharge?.recharge,seepage:state?.seepage?.seepage,spring:state?.spring?.emergence,wet:state?.surface?.wet})){if(!(Number.isFinite(v)&&v>=0&&v<=1))errors.push(`${k}-range`);}if(!(Number.isFinite(state?.waterTable?.depthMeters)&&state.waterTable.depthMeters>=2&&state.waterTable.depthMeters<=84))errors.push('water-table-range');if(state?.canonicalTerrainUntouched!==true)errors.push('canonical-boundary');return freeze({ok:errors.length===0,errors:freeze(errors),policyId:TERRAIN_GROUNDWATER_POLICY.id});}
export function buildGroundwaterScenario(input={}){const state=resolveTerrainGroundwaterState(input);const material=groundwaterMaterialResponse({state,baseColor:input.baseColor??{r:.48,g:.42,b:.34},baseRoughness:input.baseRoughness??.86});return freeze({id:String(input.id??`gw-${state.sample.worldX}-${state.sample.worldZ}`),state,material,validation:validateGroundwaterState(state)});}
export function buildGroundwaterCatalog({substrates=Object.keys(TERRAIN_GROUNDWATER_SUBSTRATES),days=[1,46,91,136,181,226,271,316],slopes=[2,8,18,32],moistures=[.18,.38,.58,.78]}={}){const rows=[];for(const substrate of substrates)for(const dayOfYear of days)for(const slopeDegrees of slopes)for(const moisture of moistures){rows.push(groundwaterSignature({worldX:Math.imul(rows.length+17,97)%8000-4000,worldZ:Math.imul(rows.length+31,131)%8000-4000,heightMeters:48+(rows.length%11)*9,slopeDegrees,moisture,rainfall:.34+(rows.length%7)*.08,substrate,weather:{rainfall:.42+(dayOfYear%5)*.07,stormPulse:(dayOfYear%4)*.08}}));}return freeze(rows);}
export function groundwaterPolicySnapshot(){return freeze({policy:TERRAIN_GROUNDWATER_POLICY,substrates:Object.keys(TERRAIN_GROUNDWATER_SUBSTRATES),invariants:TERRAIN_GROUNDWATER_CANONICAL_INVARIANTS});}
export const TERRAIN_GROUNDWATER_GLSL=String.raw`float terrainGwHash(vec2 p){vec3 q=fract(vec3(p.xyx)*vec3(.1031,.0973,.113));q+=dot(q,q.yzx+33.33);return fract((q.x+q.y)*q.z);}float terrainGwNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);float a=terrainGwHash(i),b=terrainGwHash(i+vec2(1,0)),c=terrainGwHash(i+vec2(0,1)),d=terrainGwHash(i+vec2(1,1));return mix(mix(a,b,f.x),mix(c,d,f.x),f.y);}float terrainGwFbm(vec2 p){float v=0.,w=0.,a=.55;for(int i=0;i<4;i++){v+=terrainGwNoise(p)*a;w+=a;p=p*2.01+vec2(13.7,-9.1);a*=.48;}return v/w;}void terrainGroundwaterApplyColor(){vec2 p=vTerrainLowWorldPosition.xz;float seep=smoothstep(.44,.78,terrainGwFbm(p/120.));float wet=smoothstep(.35,.72,terrainGwFbm(p/76.));diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.28,.38,.40),seep*.035);diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.24,.30,.30),wet*.018);}void terrainGroundwaterApplyRoughness(){vec2 p=vTerrainLowWorldPosition.xz;float wet=smoothstep(.35,.75,terrainGwFbm(p/76.));roughnessFactor=clamp(roughnessFactor-wet*.045,.42,1.);}`;
export function installTerrainGroundwater(material){if(!material)throw new TypeError('terrain groundwater response requires material');if(material.userData?.terrainGroundwaterInstalled)return material;const previous=material.onBeforeCompile?.bind(material);material.onBeforeCompile=(shader,renderer)=>{previous?.(shader,renderer);shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\n${TERRAIN_GROUNDWATER_GLSL}`);shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nterrainGroundwaterApplyColor();');shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nterrainGroundwaterApplyRoughness();');};const previousKey=material.customProgramCacheKey?.bind(material);material.customProgramCacheKey=()=>`${previousKey?previousKey():''}|${TERRAIN_GROUNDWATER_POLICY.materialKey}`;material.userData={...material.userData,terrainGroundwaterInstalled:true,terrainGroundwaterPolicyId:TERRAIN_GROUNDWATER_POLICY.id,terrainGroundwaterRenderOnly:true,terrainGroundwaterCanonicalTerrainUntouched:true};return material;}
