/**
 * Deterministic surface-weathering response.
 * Render-only proxy for frost cracking, oxidation, salt scaling, friable rims and durable rock faces.
 */
const clamp01=v=>Math.max(0,Math.min(1,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const smoothstep=(a,b,v)=>{const t=clamp01((v-a)/Math.max(1e-9,b-a));return t*t*(3-2*t);};
function hash2D(ix,iz,seed){let h=Math.imul((ix|0)^seed,0x45d9f3b)^Math.imul((iz|0)+seed,0x119de1f3);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return(h>>>0)/4294967296;}
function noise(x,z,seed){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,ux=fx*fx*(3-2*fx),uz=fz*fz*(3-2*fz),a=hash2D(ix,iz,seed),b=hash2D(ix+1,iz,seed),c=hash2D(ix,iz+1,seed),d=hash2D(ix+1,iz+1,seed);return lerp(lerp(a,b,ux),lerp(c,d,ux),uz);}
function fbm(x,z,seed,n=5){let v=0,w=0,a=.55;for(let i=0;i<n;i+=1){v+=noise(x,z,seed+i*97)*a;w+=a;x=x*2.04+6.1;z=z*2.01-5.2;a*=.47;}return v/Math.max(1e-9,w);}
function ridge(x,z,seed){return 1-Math.abs(fbm(x,z,seed)*2-1);}
export const TERRAIN_WEATHERING_POLICY=Object.freeze({id:'terrain-surface-weathering-2026-09-15-v1',renderOnly:true,deterministic:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,newGeographyIntroduced:false,macroScaleMeters:720,fractureScaleMeters:Object.freeze([96,31,9]),oxidationScaleMeters:Object.freeze([210,58,17]),saltScaleMeters:Object.freeze([64,18,5]),friableScaleMeters:Object.freeze([42,12]),rockHeightMeters:Object.freeze([140,2400]),maxAlbedoShift:.082,maxRoughnessShift:.071,maxNormalStrength:.064,materialKey:'terrain-surface-weathering-v1'});
export const TERRAIN_WEATHERING_CANONICAL_INVARIANTS=Object.freeze(['canonicalHeightUnchanged','canonicalHydrologyUnchanged','canonicalCoastlineUnchanged','canonicalColliderUnchanged','canonicalVegetationPlacementUnchanged','newGeographyIntroduced:false']);
function rockSignal(height,slope,color){const l=clamp01(color.r*.2126+color.g*.7152+color.b*.0722);const chroma=clamp01(Math.max(color.r,Math.max(color.g,color.b))-Math.min(color.r,Math.min(color.g,color.b)));return clamp01(smoothstep(125,260,height)*.38+smoothstep(12,42,slope)*.26+(1-l)*.18+(1-chroma)*.18);}
export function resolveTerrainWeatheringState({worldX,worldZ,heightMeters,slopeDegrees=0,moisture=.5,baseColor={r:.36,g:.34,b:.30}}){const x=Number(worldX)||0,z=Number(worldZ)||0,h=Number(heightMeters)||0,s=Math.max(0,Number(slopeDegrees)||0),m=clamp01(Number(moisture)||0),rock=rockSignal(h,s,baseColor),broad=fbm(x/720,z/720,0x6110,5),fracture=clamp01(ridge(x/96,z/31,0x6111)*.62+noise(x/9,z/9,0x6112)*.38),joint=clamp01(ridge(x/31,z/18,0x6120)*.58+fbm(x/120,z/42,0x6121)*.42),oxidation=clamp01(rock*(.44+broad*.18+noise(x/17,z/17,0x6130)*.38)*(1-m*.34)),saltScaling=clamp01(rock*(1-m)*(.40+ridge(x/64,z/18,0x6140)*.36+noise(x/5,z/5,0x6141)*.24)),wetRim=clamp01(rock*m*(.40+ridge(x/42,z/12,0x6150)*.60)),friableRim=clamp01(rock*(joint*.48+fracture*.32+saltScaling*.20)),durableFace=clamp01(rock*(1-fracture*.28-joint*.20)*(1-smoothstep(0,9,s)*.12)),exfoliation=clamp01(fractionalBand(x,z,h,s)*rock),microCracks=clamp01(fracture*(.46+joint*.28+noise(x/4,z/4,0x6160)*.26)),debrisTone=clamp01(friableRim*.55+saltScaling*.20+oxidation*.25),stress=clamp01(fracture*.36+joint*.22+saltScaling*.18+oxidation*.14+wetRim*.10);return Object.freeze({rock,broad,fracture,joint,oxidation,saltScaling,wetRim,friableRim,durableFace,exfoliation,microCracks,debrisTone,stress});}
function fractionalBand(x,z,h,s){const thermal=smoothstep(250,1100,h),ridgeSignal=ridge(x/42,z/11,0x6170),slope=smoothstep(8,34,s);return clamp01(thermal*(.36+ridgeSignal*.42+slope*.22));}
export function resolveTerrainWeatheringMaterialResponse({state,baseColor,baseRoughness=.86}){const oxide=state.oxidation*.028,salt=state.saltScaling*.022,fine=state.microCracks*.018,rim=state.wetRim*.014;const color=Object.freeze({r:clamp01(baseColor.r+oxide*.90+salt*.45-rim*.18),g:clamp01(baseColor.g+oxide*.62+salt*.28-rim*.10),b:clamp01(baseColor.b+oxide*.32+salt*.20+rim*.12)});const roughness=clamp01(baseRoughness+state.stress*.045+state.durableFace*.018-state.wetRim*.026);const normalStrength=clamp01(fine*.032+state.fracture*.020+state.exfoliation*.016);return Object.freeze({color,roughness,normalStrength,oxide,salt,fine,rim});}
export const TERRAIN_WEATHERING_GLSL=String.raw`
float terrainWeatherHash(vec2 p){vec3 q=fract(vec3(p.xyx)*vec3(.1031,.103,.0973));q+=dot(q,q.yzx+33.33);return fract((q.x+q.y)*q.z);}float terrainWeatherNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);float a=terrainWeatherHash(i),b=terrainWeatherHash(i+vec2(1,0)),c=terrainWeatherHash(i+vec2(0,1)),d=terrainWeatherHash(i+vec2(1,1));return mix(mix(a,b,f.x),mix(c,d,f.x),f.y);}float terrainWeatherFbm(vec2 p){float v=0.,w=0.,a=.55;for(int i=0;i<5;i++){v+=terrainWeatherNoise(p)*a;w+=a;p=p*2.04+vec2(6.1,-5.2);a*=.47;}return v/w;}float terrainWeatherRidge(vec2 p){return 1.-abs(terrainWeatherFbm(p)*2.-1.);}void terrainWeatheringApplyColor(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;vec3 n=normalize(vTerrainLowWorldNormal);float slope=1.-clamp(abs(n.y),0.,1.);float rock=clamp(smoothstep(125.,260.,h)*.38+smoothstep(.21,.67,slope)*.26+(1.-diffuseColor.r)*.18,0.,1.);float broad=terrainWeatherFbm(p/720.);float fracture=clamp(terrainWeatherRidge(p/vec2(96.,31.))*.62+terrainWeatherNoise(p/9.)*.38,0.,1.);float joint=clamp(terrainWeatherRidge(p/vec2(31.,18.))*.58+terrainWeatherFbm(p/vec2(120.,42.))*.42,0.,1.);float oxidation=rock*(.44+broad*.18+terrainWeatherNoise(p/17.)*.38);float salt=rock*(1.-smoothstep(.24,.70,diffuseColor.g))*(.40+terrainWeatherRidge(p/64.)*.36+terrainWeatherNoise(p/5.)*.24);float rim=rock*(smoothstep(.20,.76,diffuseColor.b))*(.40+terrainWeatherRidge(p/42.)*.60);float mask=smoothstep(.10,.74,rock);diffuseColor.rgb+=vec3(.028,.019,.010)*oxidation*.55*mask;diffuseColor.rgb+=vec3(.022,.017,.012)*salt*.38*mask;diffuseColor.rgb+=vec3(.004,.006,.008)*rim*.22*mask;diffuseColor.rgb=clamp(diffuseColor.rgb,vec3(.008),vec3(.92));}
void terrainWeatheringApplyRoughness(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;float slope=1.-clamp(abs(normalize(vTerrainLowWorldNormal).y),0.,1.);float rock=smoothstep(125.,260.,h);float fracture=terrainWeatherRidge(p/vec2(96.,31.));float joint=terrainWeatherRidge(p/vec2(31.,18.));float salt=(1.-smoothstep(.20,.72,diffuseColor.g))*rock;roughnessFactor=clamp(roughnessFactor+rock*(fracture*.038+joint*.022)+salt*.026-smoothstep(.20,.72,diffuseColor.b)*.021,0.42,1.0);}
void terrainWeatheringApplyNormal(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;float mask=smoothstep(125.,260.,h);float a=terrainWeatherNoise(p/8.+vec2(2.3,-4.1)),b=terrainWeatherNoise(p/8.+vec2(3.0,-3.4));float c=terrainWeatherRidge(p/26.+vec2(-7.2,4.8));vec2 g=vec2(b-a,c-.5);normal=normalize(normal+mat3(viewMatrix)*vec3(-g.x,0.,-g.y)*mask*.062);}
`;
export function installTerrainWeathering(material){if(!material)throw new TypeError('terrain weathering requires a material');if(material.userData?.terrainWeatheringInstalled)return material;const previous=material.onBeforeCompile.bind(material);material.onBeforeCompile=(shader,renderer)=>{previous(shader,renderer);shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\n${TERRAIN_WEATHERING_GLSL}`);shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nterrainWeatheringApplyColor();');shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nterrainWeatheringApplyRoughness();');shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nterrainWeatheringApplyNormal();');};const previousKey=material.customProgramCacheKey?.bind(material);material.customProgramCacheKey=()=>`${previousKey?previousKey():''}|${TERRAIN_WEATHERING_POLICY.materialKey}`;material.userData={...material.userData,terrainWeatheringInstalled:true,terrainWeatheringPolicyId:TERRAIN_WEATHERING_POLICY.id,terrainWeatheringRenderOnly:true,terrainWeatheringCanonicalHeightUnchanged:true,terrainWeatheringCanonicalHydrologyUnchanged:true,terrainWeatheringCanonicalCoastlineUnchanged:true,terrainWeatheringCanonicalColliderUnchanged:true,terrainWeatheringCanonicalVegetationPlacementUnchanged:true};material.needsUpdate=true;return material;}
export function weatheringPolicySnapshot(){return Object.freeze({id:TERRAIN_WEATHERING_POLICY.id,scales:Object.freeze({macro:TERRAIN_WEATHERING_POLICY.macroScaleMeters,fracture:TERRAIN_WEATHERING_POLICY.fractureScaleMeters,oxidation:TERRAIN_WEATHERING_POLICY.oxidationScaleMeters,salt:TERRAIN_WEATHERING_POLICY.saltScaleMeters}),renderOnly:true,deterministic:true,invariants:TERRAIN_WEATHERING_CANONICAL_INVARIANTS});}
