/**
 * Deterministic aeolian dust and fine-sediment surface response.
 * Render-only proxy for windward deposition, lee accumulation, dust veil and exposed substrate.
 */
const clamp01=v=>Math.max(0,Math.min(1,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const smoothstep=(a,b,v)=>{const t=clamp01((v-a)/Math.max(1e-9,b-a));return t*t*(3-2*t);};
function hash2D(ix,iz,seed){let h=Math.imul((ix|0)^seed,0x45d9f3b)^Math.imul((iz|0)+seed,0x119de1f3);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return(h>>>0)/4294967296;}
function noise(x,z,seed){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,ux=fx*fx*(3-2*fx),uz=fz*fz*(3-2*fz),a=hash2D(ix,iz,seed),b=hash2D(ix+1,iz,seed),c=hash2D(ix,iz+1,seed),d=hash2D(ix+1,iz+1,seed);return lerp(lerp(a,b,ux),lerp(c,d,ux),uz);}
function fbm(x,z,seed,n=4){let v=0,w=0,a=.55;for(let i=0;i<n;i+=1){v+=noise(x,z,seed+i*89)*a;w+=a;x=x*2.02+5.3;z=z*2.04-7.7;a*=.48;}return v/Math.max(1e-9,w);}
function ridge(x,z,seed){return 1-Math.abs(fbm(x,z,seed)*2-1);}
function rotate(x,z,a){const c=Math.cos(a),s=Math.sin(a);return{x:x*c-z*s,z:x*s+z*c};}
export const TERRAIN_AEOLIAN_DUST_POLICY=Object.freeze({id:'terrain-surface-aeolian-dust-2026-09-15-v1',renderOnly:true,deterministic:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,newGeographyIntroduced:false,windBearingRadians:2.31,macroScaleMeters:980,depositScaleMeters:Object.freeze([260,88,24,7]),leeScaleMeters:Object.freeze([180,46,13]),dustSourceScaleMeters:Object.freeze([1400,420]),maxAlbedoShift:.065,maxRoughnessShift:.052,maxNormalStrength:.045,materialKey:'terrain-surface-aeolian-dust-v1'});
export const TERRAIN_AEOLIAN_CANONICAL_INVARIANTS=Object.freeze(['canonicalHeightUnchanged','canonicalHydrologyUnchanged','canonicalCoastlineUnchanged','canonicalColliderUnchanged','canonicalVegetationPlacementUnchanged','newGeographyIntroduced:false']);
export function resolveTerrainAeolianDustState({worldX,worldZ,heightMeters,slopeDegrees=0,moisture=.5,baseColor={r:.35,g:.43,b:.25}}){const x=Number(worldX)||0,z=Number(worldZ)||0,h=Number(heightMeters)||0,s=Math.max(0,Number(slopeDegrees)||0),m=clamp01(Number(moisture)||0),r=rotate(x,z,TERRAIN_AEOLIAN_DUST_POLICY.windBearingRadians),source=clamp01(fbm(x/1400,z/1400,0x5d01,5)*.7+fbm(x/420,z/420,0x5d02,3)*.3),windward=clamp01(fbm(r.x/260,r.z/88,0x5d10)*.55+ridge(r.x/88,r.z/24,0x5d11)*.45),lee=clamp01(fbm(r.x/180,r.z/46,0x5d20)*.52+ridge(r.x/46,r.z/13,0x5d21)*.48),grain=clamp01(noise(r.x/7,r.z/7,0x5d30)*.45+ridge(r.x/24,r.z/7,0x5d31)*.55),aridity=clamp01((1-m)*.68+source*.22+(1-windward)*.10),lowRelief=1-smoothstep(180,640,h),highExposure=smoothstep(180,900,h),shelter=smoothstep(.18,.78,lee),slopeExposure=smoothstep(2,18,s),transport=clamp01(aridity*(.46+source*.30+windward*.24)),deposition=clamp01(transport*(.35+lee*.55+shelter*.10)*(1-slopeExposure*.18)),veil=clamp01(deposition*(.46+grain*.34+lowRelief*.20)),exposedSubstrate=clamp01((1-deposition*.52)*(slopeExposure*.42+highExposure*.23+(1-source)*.17+grain*.18)),windShear=clamp01((.44+windward*.56)*(1-shelter*.32)*(0.55+slopeExposure*.45)),fineFilm=clamp01(veil*(.54+grain*.46));const baseLuma=clamp01(baseColor.r*.2126+baseColor.g*.7152+baseColor.b*.0722);return Object.freeze({source,windward,lee,grain,aridity,lowRelief,highExposure,shelter,slopeExposure,transport,deposition,veil,exposedSubstrate,windShear,fineFilm,baseLuma});}
export function resolveTerrainAeolianDustMaterialResponse({state,baseColor,baseRoughness=.86}){const dust=state.fineFilm*.032+state.deposition*.018,substrate=state.exposedSubstrate*.012;const color=Object.freeze({r:clamp01(baseColor.r+dust*.82+substrate*.22),g:clamp01(baseColor.g+dust*.70+substrate*.16),b:clamp01(baseColor.b+dust*.50+substrate*.11)});const roughness=clamp01(baseRoughness+state.deposition*.034+state.exposedSubstrate*.022-state.fineFilm*.046);const normalStrength=clamp01(state.windShear*.022+state.grain*.018+state.exposedSubstrate*.015);return Object.freeze({color,roughness,normalStrength,dust,substrate});}
export const TERRAIN_AEOLIAN_DUST_GLSL=String.raw`
float terrainDustHash(vec2 p){vec3 q=fract(vec3(p.xyx)*vec3(.1031,.103,.0973));q+=dot(q,q.yzx+33.33);return fract((q.x+q.y)*q.z);}float terrainDustNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);float a=terrainDustHash(i),b=terrainDustHash(i+vec2(1,0)),c=terrainDustHash(i+vec2(0,1)),d=terrainDustHash(i+vec2(1,1));return mix(mix(a,b,f.x),mix(c,d,f.x),f.y);}float terrainDustFbm(vec2 p){float v=0.,w=0.,a=.55;for(int i=0;i<5;i++){v+=terrainDustNoise(p)*a;w+=a;p=p*2.02+vec2(5.3,-7.7);a*=.48;}return v/w;}float terrainDustRidge(vec2 p){return 1.-abs(terrainDustFbm(p)*2.-1.);}void terrainAeolianDustApplyColor(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;vec3 n=normalize(vTerrainLowWorldNormal);float slope=1.-clamp(abs(n.y),0.,1.);float source=clamp(terrainDustFbm(p/1400.)*.7+terrainDustFbm(p/420.+vec2(-4.2,8.1))*.3,0.,1.);float lee=clamp(terrainDustFbm(p/180.+vec2(11.2,-6.4))*.52+terrainDustRidge(p/46.+vec2(4.6,13.1))*.48,0.,1.);float grain=clamp(terrainDustNoise(p/7.)*.45+terrainDustRidge(p/24.+vec2(-3.7,8.2))*.55,0.,1.);float aridity=clamp(.40+(1.-source)*.22+(1.-smoothstep(.12,.60,dot(diffuseColor.rgb,vec3(.2126,.7152,.0722))))*.10,0.,1.);float transport=clamp(aridity*(.46+source*.30+(1.-lee)*.24),0.,1.);float deposition=clamp(transport*(.35+lee*.55+.10)*(1.-smoothstep(.04,.34,slope)*.18),0.,1.);float veil=clamp(deposition*(.46+grain*.34+(1.-smoothstep(180.,640.,h))*.20),0.,1.);float mask=1.-smoothstep(.58,.88,dot(diffuseColor.rgb,vec3(.2126,.7152,.0722)));diffuseColor.rgb+=vec3(.030,.024,.018)*veil*.70*mask;diffuseColor.rgb+=vec3(.008,.006,.004)*deposition*.35*mask;}
void terrainAeolianDustApplyRoughness(){vec2 p=vTerrainLowWorldPosition.xz;vec3 n=normalize(vTerrainLowWorldNormal);float slope=1.-clamp(abs(n.y),0.,1.);float grain=terrainDustRidge(p/24.+vec2(-3.7,8.2));float lee=terrainDustRidge(p/46.+vec2(4.6,13.1));float deposition=clamp((.28+lee*.60)*(1.-slope*.16),0.,1.);roughnessFactor=clamp(roughnessFactor+deposition*.032+grain*.018-lee*.020,0.42,1.0);}
void terrainAeolianDustApplyNormal(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;float g=terrainDustNoise(p/7.+vec2(2.4,-7.1))-terrainDustNoise(p/7.+vec2(3.2,-6.4));float mask=1.-smoothstep(160.,900.,h)*.45;normal=normalize(normal+mat3(viewMatrix)*vec3(-g,0.,g*.65)*mask*.032);}
`;
export function installTerrainAeolianDust(material){if(!material)throw new TypeError('terrain aeolian dust requires a material');if(material.userData?.terrainAeolianDustInstalled)return material;const previous=material.onBeforeCompile.bind(material);material.onBeforeCompile=(shader,renderer)=>{previous(shader,renderer);shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\n${TERRAIN_AEOLIAN_DUST_GLSL}`);shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nterrainAeolianDustApplyColor();');shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nterrainAeolianDustApplyRoughness();');shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nterrainAeolianDustApplyNormal();');};const previousKey=material.customProgramCacheKey?.bind(material);material.customProgramCacheKey=()=>`${previousKey?previousKey():''}|${TERRAIN_AEOLIAN_DUST_POLICY.materialKey}`;material.userData={...material.userData,terrainAeolianDustInstalled:true,terrainAeolianDustPolicyId:TERRAIN_AEOLIAN_DUST_POLICY.id,terrainAeolianDustRenderOnly:true};material.needsUpdate=true;return material;}
export function aeolianDustPolicySnapshot(){return Object.freeze({id:TERRAIN_AEOLIAN_DUST_POLICY.id,windBearingRadians:TERRAIN_AEOLIAN_DUST_POLICY.windBearingRadians,scales:TERRAIN_AEOLIAN_DUST_POLICY.depositScaleMeters,renderOnly:true,deterministic:true,invariants:TERRAIN_AEOLIAN_CANONICAL_INVARIANTS});}
