/** Fragment-only groundwater surface detail shader. */
import { TERRAIN_GROUNDWATER_DETAIL_POLICY } from './terrainGroundwaterSurfaceDetail.js';
const freeze=Object.freeze;
export const TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY=freeze({id:'terrain-groundwater-surface-detail-shader-2026-09-15-v1',sourcePolicyId:TERRAIN_GROUNDWATER_DETAIL_POLICY.id,materialKey:TERRAIN_GROUNDWATER_DETAIL_POLICY.materialKey,renderOnly:true,deterministic:true,fragmentOnly:true,modifiesVertexPosition:false,modifiesDisplacement:false,maxNormalStrength:TERRAIN_GROUNDWATER_DETAIL_POLICY.maxNormalStrength});
export const TERRAIN_GROUNDWATER_DETAIL_SHADER_INVARIANTS=freeze(['fragment-only-material-adjustment','no-vertex-position-write','no-height-map-write','no-hydrology-topology-write','no-collider-write','no-vegetation-placement-write','deterministic-world-space-cues']);
export const TERRAIN_GROUNDWATER_DETAIL_GLSL=String.raw`
float terrainGwDetailHash(vec2 p){vec3 q=fract(vec3(p.xyx)*vec3(.1031,.103,.0973));q+=dot(q,q.yzx+33.33);return fract((q.x+q.y)*q.z);}
float terrainGwDetailNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(terrainGwDetailHash(i),terrainGwDetailHash(i+vec2(1.,0.)),f.x),mix(terrainGwDetailHash(i+vec2(0.,1.)),terrainGwDetailHash(i+vec2(1.,1.)),f.x),f.y);}
float terrainGwDetailFbm(vec2 p){float v=0.,w=0.,a=.55;for(int i=0;i<5;i++){v+=terrainGwDetailNoise(p)*a;w+=a;p=p*2.03+vec2(7.4,-11.8);a*=.48;}return v/max(w,.0001);}
float terrainGwDetailRidge(vec2 p){return 1.-abs(terrainGwDetailFbm(p)*2.-1.);}
float terrainGwDetailWet(vec2 p,float slope,float h){float basin=1.-smoothstep(2.,9.5,slope);float low=1.-smoothstep(18.,150.,h);float t=terrainGwDetailFbm(p/52.+vec2(3.1,-17.));return clamp(basin*.40+t*.34+low*.14,0.,1.);}
float terrainGwDetailCapillary(vec2 p,float slope){float local=terrainGwDetailFbm(p/18.+vec2(-4.,8.));float shallow=1.-smoothstep(2.,28.,slope);return clamp(local*.58+shallow*.25,0.,1.);}
float terrainGwDetailSeepage(vec2 p,float slope){float r=terrainGwDetailRidge(p/9.+vec2(11.,-9.));float band=smoothstep(4.,23.,slope)*(1.-smoothstep(23.,46.,slope));return clamp(r*band,0.,1.);}
float terrainGwDetailPuddle(vec2 p,float slope,float h){float flat=1.-smoothstep(1.4,8.5,slope);float low=1.-smoothstep(10.,130.,h);float t=terrainGwDetailRidge(p/19.);return clamp(flat*.50+low*.18+t*.18,0.,1.);}
float terrainGwDetailEvaporation(vec2 p,float slope,float h){float d=terrainGwDetailFbm(p/64.+vec2(-8.,2.7));float high=smoothstep(35.,420.,h);float flat=1.-smoothstep(4.,34.,slope);return clamp((.24+d*.46)*high*flat,0.,1.);}
float terrainGwDetailCrust(vec2 p,float slope,float h){float edge=smoothstep(.28,.82,terrainGwDetailRidge(p/27.+vec2(5.5,-3.8)));float high=smoothstep(30.,240.,h);float flat=1.-smoothstep(6.,31.,slope);return clamp(edge*high*flat,0.,1.);}
float terrainGwDetailFine(vec2 p,float slope){return clamp(terrainGwDetailWet(p,slope,40.)*.46+terrainGwDetailFbm(p/13.+vec2(1.8,9.3))*.34,0.,1.);}
float terrainGwDetailFreeze(vec2 p,float slope,float h){float cold=terrainGwDetailFbm(p/210.+vec2(8.,-4.));float elevated=smoothstep(90.,1800.,h);float band=smoothstep(3.,36.,slope);return clamp(cold*.42+elevated*.28+band*.10,0.,1.);}
void terrainGwDetailApplyColor(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;float s=degrees(acos(clamp(abs(normalize(vTerrainLowWorldNormal).y),0.,1.)));float wet=terrainGwDetailWet(p,s,h);float cap=terrainGwDetailCapillary(p,s);float seep=terrainGwDetailSeepage(p,s);float puddle=terrainGwDetailPuddle(p,s,h);float evap=terrainGwDetailEvaporation(p,s,h);float crust=terrainGwDetailCrust(p,s,h);float fine=terrainGwDetailFine(p,s);float freeze=terrainGwDetailFreeze(p,s,h);float marsh=(1.-smoothstep(20.,120.,h))*(.42+wet*.38);float rim=clamp(wet*(1.-wet)*2.7+puddle*.24,0.,1.);float dark=seep*.42+cap*.16;diffuseColor.rgb+=vec3(-.012,-.009,.008)*wet;diffuseColor.rgb+=vec3(-.008,-.006,.003)*dark;diffuseColor.rgb+=vec3(-.005,-.004,-.002)*puddle;diffuseColor.rgb+=vec3(.009,.006,.002)*crust;diffuseColor.rgb+=vec3(.004,.003,.002)*evap;diffuseColor.rgb+=vec3(.001,.002,.004)*marsh;diffuseColor.rgb+=vec3(-.003,-.002,-.001)*fine;diffuseColor.rgb+=vec3(-.002,-.002,-.001)*freeze*.25;diffuseColor.rgb+=vec3(.002,.001,.001)*rim*.28;}
void terrainGwDetailApplyRoughness(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;float s=degrees(acos(clamp(abs(normalize(vTerrainLowWorldNormal).y),0.,1.)));float wet=terrainGwDetailWet(p,s,h);float puddle=terrainGwDetailPuddle(p,s,h);float crust=terrainGwDetailCrust(p,s,h);float freeze=terrainGwDetailFreeze(p,s,h);float evap=terrainGwDetailEvaporation(p,s,h);roughnessFactor=clamp(roughnessFactor-wet*.042-puddle*.034+crust*.030+freeze*.018+evap*.010,.42,1.);}
void terrainGwDetailApplyNormal(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;float s=degrees(acos(clamp(abs(normalize(vTerrainLowWorldNormal).y),0.,1.)));float film=terrainGwDetailWet(p,s,h);float seep=terrainGwDetailSeepage(p,s);float puddle=terrainGwDetailPuddle(p,s,h);float freeze=terrainGwDetailFreeze(p,s,h);float a=terrainGwDetailFbm(p/11.+vec2(1.9,-3.6));float b=terrainGwDetailFbm(p/11.+vec2(2.7,-2.9));float c=terrainGwDetailRidge(p/48.+vec2(-6.2,11.1));vec2 g=vec2(b-a,c-.5);float strength=clamp(film*.030+seep*.020+puddle*.014+freeze*.011,0.,.055);normal=normalize(normal+mat3(viewMatrix)*vec3(-g.x,0.,-g.y)*strength);}
`;
export function groundwaterSurfaceDetailShaderReplacements(){return freeze({common:TERRAIN_GROUNDWATER_DETAIL_GLSL.length>0,color:TERRAIN_GROUNDWATER_DETAIL_GLSL.includes('terrainGwDetailApplyColor();'),roughness:TERRAIN_GROUNDWATER_DETAIL_GLSL.includes('terrainGwDetailApplyRoughness();'),normal:TERRAIN_GROUNDWATER_DETAIL_GLSL.includes('terrainGwDetailApplyNormal();'),vertexDisplacement:!TERRAIN_GROUNDWATER_DETAIL_GLSL.includes('position +='),heightWrite:!TERRAIN_GROUNDWATER_DETAIL_GLSL.includes('vTerrainLowWorldPosition.y +=')});}
export function installTerrainGroundwaterSurfaceDetailShader(material){if(!material)throw new TypeError('groundwater surface detail shader requires a material');if(material.userData?.terrainGroundwaterSurfaceDetailShaderInstalled)return material;const previous=typeof material.onBeforeCompile==='function'?material.onBeforeCompile.bind(material):()=>{};material.onBeforeCompile=(shader,renderer)=>{previous(shader,renderer);shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\n${TERRAIN_GROUNDWATER_DETAIL_GLSL}`).replace('#include <color_fragment>','#include <color_fragment>\nterrainGwDetailApplyColor();').replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nterrainGwDetailApplyRoughness();').replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nterrainGwDetailApplyNormal();');};const previousKey=typeof material.customProgramCacheKey==='function'?material.customProgramCacheKey.bind(material):null;material.customProgramCacheKey=()=>`${previousKey?previousKey():''}|${TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.materialKey}`;material.userData={...material.userData,terrainGroundwaterSurfaceDetailShaderInstalled:true,terrainGroundwaterSurfaceDetailShaderPolicyId:TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.id,terrainGroundwaterSurfaceDetailRenderOnly:true,terrainGroundwaterSurfaceDetailVertexDisplacementUnchanged:true};material.needsUpdate=true;return material;}
export function shaderInvariantReport(){const r=groundwaterSurfaceDetailShaderReplacements();return freeze({policyId:TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.id,replacements:r,invariants:TERRAIN_GROUNDWATER_DETAIL_SHADER_INVARIANTS,ok:Object.values(r).every(Boolean)});}
