const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):a));
const unit=(v,f=.5)=>clamp(Number.isFinite(Number(v))?Number(v):f);
const freeze=v=>Object.freeze(v);
const smooth=(a,b,v)=>{const t=clamp((finite(v)-a)/Math.max(1e-6,b-a));return t*t*(3-2*t);};
const lerp=(a,b,t)=>a+(b-a)*t;
const hash=(x,z,s=0x7c31)=>{let h=Math.imul((x|0)^s,0x45d9f3b)^Math.imul((z|0)+s,0x119de1f3);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return(h>>>0)/4294967296;};
const noise=(x,z,s=0x7c32)=>{const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,ux=fx*fx*(3-2*fx),uz=fz*fz*(3-2*fz);return lerp(lerp(hash(ix,iz,s),hash(ix+1,iz,s),ux),lerp(hash(ix,iz+1,s),hash(ix+1,iz+1,s),ux),uz);};
const fbm=(x,z,s=0x7c33,n=4)=>{let v=0,w=0,a=.55;for(let i=0;i<n;i++){v+=noise(x,z,s+i*101)*a;w+=a;x=x*2.02+12.1;z=z*1.99-8.3;a*=.49;}return v/Math.max(1e-6,w);};
export const TERRAIN_GROUNDWATER_V2_POLICY=freeze({id:'terrain-groundwater-surface-v2-2026-09-15',deterministic:true,renderOnly:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,waterTableDepthMeters:[2,84],capillaryBandMeters:12,seepageThreshold:.42,springThreshold:.56,materialKey:'terrain-groundwater-surface-v2'});
export const TERRAIN_GROUNDWATER_V2_SUBSTRATE=freeze({granite:[.38,.31,.18,.22,.46],limestone:[.44,.62,.21,.54,.39],sandstone:[.58,.71,.26,.37,.33],shale:[.47,.18,.49,.28,.58],schist:[.41,.33,.31,.43,.49],clay:[.72,.12,.68,.10,.74],silt:[.66,.36,.57,.16,.63],sand:[.52,.82,.17,.08,.29],gravel:[.48,.91,.09,.05,.22],peat:[.81,.24,.76,.07,.86],alluvium:[.69,.67,.43,.11,.62],colluvium:[.55,.49,.35,.18,.51],tuff:[.46,.29,.38,.47,.52],mudstone:[.63,.16,.61,.15,.68],marl:[.59,.28,.53,.22,.61],chalk:[.43,.75,.24,.48,.35]});
export function normalizeGroundwaterV2(input={}){return freeze({x:finite(input.worldX),z:finite(input.worldZ),height:finite(input.heightMeters),slope:clamp(input.slopeDegrees,0,90),moisture:unit(input.moisture),rainfall:unit(input.rainfall),runoff:unit(input.runoff,0),soilDepth:unit(input.soilDepth),vegetation:unit(input.vegetationCover),canopy:unit(input.canopy,.4),wind:unit(input.windExposure),snow:unit(input.snowWeight,0),distance:Math.max(0,finite(input.waterDistance,99999)),substrate:String(input.substrate??'alluvium').toLowerCase().replace(/[^a-z]/g,''),confidence:unit(input.confidence,1)});}
function substrate(s){return TERRAIN_GROUNDWATER_V2_SUBSTRATE[s]??TERRAIN_GROUNDWATER_V2_SUBSTRATE.alluvium;}
export function rechargeV2(sample={},weather={}){const s=normalizeGroundwaterV2(sample),p=substrate(s.substrate),rain=unit(weather.rainfall,s.rainfall),storm=unit(weather.stormPulse,0),slope=smooth(1.5,42,s.slope),retained=clamp(rain*(.58+storm*.42)*(1-slope*.46)*(s.soilDepth*.64+p[2]*.36));return freeze({rain,storm,retained,infiltration:clamp((p[1]*.62+s.soilDepth*.24+p[0]*.14)*(1-slope*.31)),recharge:clamp(retained*(p[1]*.58+p[0]*.42)*(1-s.vegetation*.14)),runoff:clamp(rain*(.5+storm*.5)*(slope*.71+(1-p[0])*.29))});}
export function waterTableV2(sample={},recharge={}){const s=normalizeGroundwaterV2(sample),p=substrate(s.substrate),r=recharge.recharge==null?rechargeV2(s):recharge,lowland=1-smooth(-4,170,s.height),distance=smooth(3,180,s.distance),storage=clamp(p[0]*.52+p[4]*.28+p[2]*.20),wet=clamp(s.moisture*.28+r.recharge*.42+lowland*.12+(1-distance)*.18),depth=clamp(42-(wet*21)-(storage*9)+(s.slope/90)*12,2,84);return freeze({depthMeters:depth,headMeters:s.height-depth,wet,storage,recharge:r});}
export function capillaryV2(sample={},table={}){const s=normalizeGroundwaterV2(sample),p=substrate(s.substrate),d=finite(table.depthMeters,42),rise=clamp((1-smooth(5,84,d))*(.24+p[2]*.34+p[4]*.42));return freeze({rise,bandMeters:12*rise,visible:rise>=.42});}
export function seepageV2(sample={},table={},capillary={}){const s=normalizeGroundwaterV2(sample),p=substrate(s.substrate),t=table.depthMeters==null?waterTableV2(s):table,c=capillary.rise==null?capillaryV2(s,t):capillary,fracture=p[3],slope=smooth(1.5,42,s.slope),perched=clamp(s.moisture*.4+t.recharge.recharge*.34+(1-slope)*.26)*(1-p[1]*.23),strength=clamp(c.rise*.45+fracture*.28+perched*.27);return freeze({strength,seepage:clamp(strength*(.42+p[1]*.31+(1-slope)*.27)),perched,fracture,pathBias:clamp(fracture*.65+slope*.1),saturated:strength>.58});}
export function springV2(sample={},table={},seepage={}){const s=normalizeGroundwaterV2(sample),p=substrate(s.substrate),t=table.depthMeters==null?waterTableV2(s):table,e=seepage.seepage==null?seepageV2(s,t):seepage,low=smooth(4,46,s.height),gentle=1-smooth(6,48,s.slope),source=clamp(e.seepage*.43+e.fracture*.24+gentle*.19+low*.14);return freeze({source,emergence:clamp(source*e.seepage),flow:clamp(source*(.48+e.pathBias*.52)),confidence:clamp(s.confidence*(.6+p[0]*.4))});}
export function surfaceWaterV2(sample={},table={},seepage={},rainfall=null){const s=normalizeGroundwaterV2(sample),t=table.depthMeters==null?waterTableV2(s):table,e=seepage.seepage==null?seepageV2(s,t):seepage,rain=rainfall==null?s.rainfall:unit(rainfall),wet=clamp(s.moisture*.37+e.seepage*.39+rain*.13+(1-t.depthMeters/84)*.11),sheen=clamp(wet*.46+e.saturated*.36),mud=clamp(wet*(.28+(1-substrate(s.substrate)[1])*.5)),standing=clamp(e.perched*.47+(1-s.slope/90)*.2+rain*.17);return freeze({wet,sheen,mud,standing,waterTableDepth:t.depthMeters});}
export function materialWaterV2(state,baseColor={r:.48,g:.42,b:.34},baseRoughness=.86){const s=state.surface,se=state.seepage,sp=state.spring,color=freeze({r:clamp(baseColor.r-s.mud*.07+s.sheen*.012),g:clamp(baseColor.g-s.mud*.042+s.sheen*.018+sp.emergence*.006),b:clamp(baseColor.b+s.mud*.018+s.sheen*.045+sp.emergence*.028)});return freeze({color,roughness:clamp(baseRoughness-s.wet*.04-s.sheen*.025+s.mud*.05),normalStrength:clamp(se.seepage*.03+s.standing*.012),waterline:clamp(s.wet*.38+se.seepage*.42+sp.emergence*.2)});}
export function resolveGroundwaterV2(input={}){const sample=normalizeGroundwaterV2(input),recharge=rechargeV2(sample,input.weather??{}),waterTable=waterTableV2(sample,recharge),capillary=capillaryV2(sample,waterTable),seepage=seepageV2(sample,waterTable,capillary),spring=springV2(sample,waterTable,seepage),surface=surfaceWaterV2(sample,waterTable,seepage,input.weather?.rainfall??sample.rainfall);return freeze({sample,recharge,waterTable,capillary,seepage,spring,surface,canonicalTerrainUntouched:true,policyId:TERRAIN_GROUNDWATER_V2_POLICY.id});}
export function groundwaterSignatureV2(input={}){const s=resolveGroundwaterV2(input);return freeze({x:s.sample.x,z:s.sample.z,substrate:s.sample.substrate,depth:+s.waterTable.depthMeters.toFixed(5),recharge:+s.recharge.recharge.toFixed(5),seepage:+s.seepage.seepage.toFixed(5),spring:+s.spring.emergence.toFixed(5),wet:+s.surface.wet.toFixed(5)});}
export function validateGroundwaterV2(state){const errors=[];for(const k of ['waterTable','recharge','capillary','seepage','spring','surface'])if(!state?.[k])errors.push(`${k}-missing`);for(const [k,v] of Object.entries({recharge:state?.recharge?.recharge,seepage:state?.seepage?.seepage,spring:state?.spring?.emergence,wet:state?.surface?.wet})){if(!(Number.isFinite(v)&&v>=0&&v<=1))errors.push(`${k}-range`);}if(!(state?.waterTable?.depthMeters>=2&&state?.waterTable?.depthMeters<=84))errors.push('depth-range');if(state?.canonicalTerrainUntouched!==true)errors.push('boundary');return freeze({ok:errors.length===0,errors:freeze(errors),policyId:TERRAIN_GROUNDWATER_V2_POLICY.id});}
export const TERRAIN_GROUNDWATER_V2_SCHEMA=freeze({version:2,stateFields:freeze(['sample','recharge','waterTable','capillary','seepage','spring','surface','canonicalTerrainUntouched']),materialFields:freeze(['color','roughness','normalStrength','waterline']),boundaries:TERRAIN_GROUNDWATER_V2_POLICY});
