const freeze=(v)=>Object.freeze(v);const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export const TERRAIN_ENVIRONMENT_SNOWLINE_POLICY=freeze({id:'terrain-environment-snowline-2026-09-07-v1',snowStartMeters:145,snowFullMeters:430,rockStartSlopeDegrees:18,rockFullSlopeDegrees:52,renderOnly:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true});
const smooth=(a,b,v)=>{const t=clamp((Number(v||0)-a)/Math.max(.0001,b-a));return t*t*(3-2*t);};
export function snowCoverage({heightMeters=0,snowWeight=0,slopeDegrees=0,moisture=.5,windward=.5,lee=.5}={}){const horizon=smooth(TERRAIN_ENVIRONMENT_SNOWLINE_POLICY.snowStartMeters,TERRAIN_ENVIRONMENT_SNOWLINE_POLICY.snowFullMeters,heightMeters);const source=clamp(snowWeight);const slope=smooth(0,64,slopeDegrees);const wet=clamp(moisture);const exposure=smooth(TERRAIN_ENVIRONMENT_SNOWLINE_POLICY.rockStartSlopeDegrees,TERRAIN_ENVIRONMENT_SNOWLINE_POLICY.rockFullSlopeDegrees,slopeDegrees);const retention=clamp(.78+wet*.14+clamp(lee)*.13-clamp(windward)*.1-exposure*.34-slope*.12);return freeze({coverage:clamp(source*.58+horizon*.52)*retention,horizon,retention,rockExposure:exposure});}
export function snowDriftField(worldX=0,worldZ=0,windDirectionRadians=0){const x=Number(worldX)||0,z=Number(worldZ)||0,w=Number(windDirectionRadians)||0,wx=Math.cos(w),wz=Math.sin(w),leeX=-wx,leeZ=-wz;const broad=Math.sin((x*leeX+z*leeZ)/110)*.5+.5;const cross=Math.cos((x*leeZ-z*leeX)/78)*.5+.5;const fine=Math.sin((x-z)/28)*.5+.5;return freeze({broad,cross,fine,leeBias:clamp(.45+broad*.45+cross*.16+fine*.06)});}
export function snowEcotoneBlend(options={}){const coverage=snowCoverage(options);const drift=snowDriftField(options.worldX,options.worldZ,options.windDirectionRadians);const rock=clamp(options.rockWeight)+coverage.rockExposure*.24;const snow=clamp(coverage.coverage*(.72+drift.leeBias*.28)*(1-rock*.42));return freeze({snow,rock:clamp(rock),ecotone:clamp(Math.min(snow,rock)*.92+(1-Math.abs(snow-rock))*.18),drift,coverage});}
export function winterAssetPlacementWeight(options={}){const blend=snowEcotoneBlend(options);const cold=['tundra','alpine-bare','glacier','tundra-edge'].includes(String(options.biome??'').toLowerCase());return freeze({score:clamp(blend.snow*.7+blend.ecotone*.15+(cold?.15:0)),blend,coldBiome:cold});}
export function snowlineTransitionBand(heightMeters=0){return freeze({below:smooth(-20,145,heightMeters),transition:1-Math.abs(smooth(145,430,heightMeters)*2-1),above:smooth(430,600,heightMeters)});}
export function validateSnowlineVisual(sample={}){const r=winterAssetPlacementWeight(sample);const errors=[];if(sample.rectangularSnowOverlay===true)errors.push('rectangular-snow-overlay');if(sample.uniformWhiteSurface===true)errors.push('uniform-snow-surface');if(r.blend.ecotone>1||r.score>1)errors.push('snow-range');return freeze({ok:errors.length===0,errors:freeze(errors),report:r});}
export function buildSnowlineManifest(samples=[]){const reports=samples.map(validateSnowlineVisual);const errors=reports.flatMap((r)=>r.errors);return freeze({version:1,policyId:TERRAIN_ENVIRONMENT_SNOWLINE_POLICY.id,reports,errors:freeze(errors),acceptance:freeze({ok:errors.length===0,errorCount:errors.length})});}
