import { TERRAIN_SEDIMENT_PROFILES, sedimentProfileIndex } from './terrainSurfaceSedimentProfiles.js';
import { TERRAIN_SEDIMENT_CALIBRATION, sedimentCalibrationAt } from './terrainSurfaceSedimentCalibration.js';
import { TERRAIN_BIOGENIC_GLSL, TERRAIN_BIOGENIC_POLICY, installTerrainBiogenic } from './terrainSurfaceBiogenic.js';
import { TERRAIN_RUNOFF_PATH_POLICY, installTerrainRunoffPaths } from './terrainSurfaceRunoffPaths.js';
import { TERRAIN_SOIL_STRUCTURE_POLICY, installTerrainSoilStructure } from './terrainSurfaceSoilStructure.js';
import { TERRAIN_SEASONAL_POLICY, installTerrainSeasonal } from './terrainSurfaceSeasonality.js';
const clamp01=v=>Math.max(0,Math.min(1,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const smoothstep=(a,b,v)=>{const t=clamp01((v-a)/Math.max(1e-9,b-a));return t*t*(3-2*t);};
export const TERRAIN_SEDIMENT_POLICY=Object.freeze({id:'terrain-surface-sediment-2026-09-15-v3-calibrated-surface-stack',renderOnly:true,deterministic:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,newGeographyIntroduced:false,broadScaleMeters:760,mesoScaleMeters:190,basinScaleMeters:96,rillScaleMeters:31,aggregateScaleMeters:13,poreScaleMeters:4.2,filmScaleMeters:52,profileCount:TERRAIN_SEDIMENT_PROFILES.length,calibrationCount:TERRAIN_SEDIMENT_CALIBRATION.length,rainBearingRadians:1.12,basinSlopeDegrees:Object.freeze([1.5,9.5]),washSlopeDegrees:Object.freeze([4,31]),strongWashSlopeDegrees:Object.freeze([18,44]),lowlandHeightMeters:Object.freeze([-2,170]),dryHeightMeters:Object.freeze([45,520]),maxAlbedoShift:.19,maxRoughnessShift:.13,maxNormalStrength:.095,materialKey:'terrain-surface-sediment-rainwash-v3'});
function hash2D(ix,iz,seed){let h=Math.imul((ix|0)^seed,0x45d9f3b)^Math.imul((iz|0)+seed,0x119de1f3);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return(h>>>0)/4294967296;}
function valueNoise(x,z,seed){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,ux=fx*fx*(3-2*fx),uz=fz*fz*(3-2*fz);return lerp(lerp(hash2D(ix,iz,seed),hash2D(ix+1,iz,seed),ux),lerp(hash2D(ix,iz+1,seed),hash2D(ix+1,iz+1,seed),ux),uz);}
function fbm(x,z,seed,n=4){let v=0,w=0,a=.55;for(let i=0;i<n;i++){v+=valueNoise(x,z,seed+i*73)*a;w+=a;x=x*2.03+11.2;z=z*2.03-7.9;a*=.48;}return v/Math.max(1e-9,w);}
function ridge(x,z,seed){return 1-Math.abs(fbm(x,z,seed)*2-1);}
function rotate(x,z,a){const c=Math.cos(a),s=Math.sin(a);return{x:x*c-z*s,z:x*s+z*c};}
function profileField(x,z){return clamp01(fbm(x/5200,z/5200,0x3101,5)*.45+fbm(x/760,z/760,0x3102)*.35+fbm(x/190,z/190,0x3103)*.2);}
function profileAt(x,z){const field=profileField(x,z),index=sedimentProfileIndex(field),next=(index+1)%TERRAIN_SEDIMENT_PROFILES.length,blend=smoothstep(.35,.88,valueNoise(x/240,z/240,0x3104)),a=TERRAIN_SEDIMENT_PROFILES[index],b=TERRAIN_SEDIMENT_PROFILES[next],cal=sedimentCalibrationAt(Math.floor((index/TERRAIN_SEDIMENT_PROFILES.length)*TERRAIN_SEDIMENT_CALIBRATION.length));return Object.freeze({index,field,blend,deposit:lerp(a.deposit,b.deposit,blend)*cal.deposit,wash:lerp(a.wash,b.wash,blend)*cal.wash,film:lerp(a.film,b.film,blend)*cal.film,crust:lerp(a.crust,b.crust,blend)*cal.crust,aggregate:lerp(a.aggregate,b.aggregate,blend),cool:lerp(a.cool,b.cool,blend)*cal.cool});}
function basinSignal(x,z,h,s){const broad=fbm(x/760,z/760,0x4210,5),meso=fbm(x/190,z/190,0x4211),pocket=ridge(x/96,z/96,0x4212),low=1-smoothstep(95,240,h),gentle=1-smoothstep(1.5,9.5,s);return clamp01((gentle*.48+low*.18+(1-broad)*.18+pocket*.16)*(.58+meso*.42));}
function rainwashSignal(x,z,s,b){const a=rotate(x,z,1.12),d=fbm(a.x/31,a.z/31,0x4310),c=fbm(a.z/53,a.x/23,0x4311,3),lane=smoothstep(.55,.86,ridge(x/31,z/83,0x4312)*.55+d*.3+c*.15),ws=smoothstep(4,31,s),strong=smoothstep(18,44,s);return clamp01(ws*(.3+b*.44+lane*.44)+strong*.16);}
function aggregateSignal(x,z){return clamp01(ridge(x/13,z/21,0x4410)*.68+fbm(x/37,z/37,0x4411,3)*.32);}
function filmSignal(x,z,b,s){return clamp01(b*(.28+fbm(x/52,z/52,0x4510)*.5+valueNoise(x/28,z/28,0x4511)*.22)*(1-smoothstep(3,24,s)));}
function crustSignal(x,z,h,b,w){return clamp01((1-b*.72)*smoothstep(45,520,h)*(1-w*.74)*(.62+fbm(x/410,z/410,0x4610)*.38));}
function poreSignal(x,z){return clamp01(valueNoise(x/4.2,z/4.2,0x4710)*.55+ridge(x/7.5,z/5.8,0x4711)*.45);}
function resolveInternal(x,z,h,s){const basin=basinSignal(x,z,h,s),catchment=clamp01(basin*.72+(1-fbm(x/1200,z/1200,0x4810))*.28),wash=rainwashSignal(x,z,s,catchment),aggregate=aggregateSignal(x,z),film=filmSignal(x,z,basin,s),crust=crustSignal(x,z,h,catchment,wash),pore=poreSignal(x,z),profile=profileAt(x,z),sedimentLoad=clamp01(catchment*.4+wash*.35+profile.deposit*.15+aggregate*.1),mineralDeposit=clamp01(catchment*.36+wash*.18+profile.deposit*.24+aggregate*.22),muddyFilm=clamp01(film*.74+catchment*.17+profile.film*.09),washBleach=clamp01(wash*.52+aggregate*.2+profile.wash*.28),dryCrust=clamp01(crust*.78+profile.crust*.22),poreRoughness=clamp01(pore*.63+aggregate*.37),transient=clamp01(muddyFilm*.64+dryCrust*.18+film*.18);return Object.freeze({basin,catchment,wash,aggregate,film,crust,pore,profile,sedimentLoad,mineralDeposit,muddyFilm,washBleach,dryCrust,poreRoughness,transient});}
export function resolveTerrainSedimentState({worldX,worldZ,heightMeters,slopeDegrees=0}){return resolveInternal(Number(worldX)||0,Number(worldZ)||0,Number(heightMeters)||0,Number(slopeDegrees)||0);}
export function resolveTerrainSedimentMaterialResponse({state,baseColor,baseRoughness=.86}){const p=state.profile,d=state.mineralDeposit*(.72+p.deposit*.28),w=state.muddyFilm*(.76+p.film*.24),q=state.washBleach*(.76+p.wash*.24),c=state.dryCrust*(.78+p.crust*.22),a=state.poreRoughness*(.78+p.aggregate*.22);return Object.freeze({color:Object.freeze({r:clamp01(baseColor.r+d*.045+q*.02+c*.018-w*.022),g:clamp01(baseColor.g+d*.034+q*.012+c*.014-w*.03),b:clamp01(baseColor.b+d*.019+w*.027-q*.006)}),roughness:clamp01(baseRoughness+a*.065+c*.032-w*.085),normalStrength:clamp01(state.wash*.048+a*.031+state.film*.016)*(.76+p.wash*.24)});}
export function sedimentRegionSignature(x,z){const s=resolveInternal(Number(x)||0,Number(z)||0,70,8);return Object.freeze({profileIndex:s.profile.index,basin:Number(s.basin.toFixed(6)),wash:Number(s.wash.toFixed(6)),film:Number(s.film.toFixed(6)),crust:Number(s.crust.toFixed(6)),aggregate:Number(s.aggregate.toFixed(6))});}
export const TERRAIN_SEDIMENT_CANONICAL_INVARIANTS=Object.freeze(['canonicalHeightUnchanged','canonicalHydrologyUnchanged','canonicalCoastlineUnchanged','canonicalColliderUnchanged','canonicalVegetationPlacementUnchanged','newGeographyIntroduced:false']);
export const TERRAIN_SEDIMENT_GLSL=String.raw`float terrainSedHash(vec2 p){vec3 q=fract(vec3(p.xyx)*vec3(.1031,.103,.0973));q+=dot(q,q.yzx+33.33);return fract((q.x+q.y)*q.z);}float terrainSedNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);float a=terrainSedHash(i),b=terrainSedHash(i+vec2(1,0)),c=terrainSedHash(i+vec2(0,1)),d=terrainSedHash(i+vec2(1,1));return mix(mix(a,b,f.x),mix(c,d,f.x),f.y);}float terrainSedFbm(vec2 p){float v=0.,w=0.,a=.55;for(int i=0;i<5;i++){v+=terrainSedNoise(p)*a;w+=a;p=p*2.03+vec2(11.2,-7.9);a*=.48;}return v/w;}float terrainSedRidge(vec2 p){return 1.-abs(terrainSedFbm(p)*2.-1.);}void terrainSedimentApplyColor(){vec2 p=vTerrainLowWorldPosition.xz;float slope=1.-clamp(abs(normalize(vTerrainLowWorldNormal).y),0.,1.);float basin=1.-smoothstep(1.5,9.5,slope);float wash=smoothstep(4.,31.,slope);float film=basin*(1.-smoothstep(3.,24.,slope))*(.28+terrainSedFbm(p/52.+vec2(-2.4,15.6))*.72);float crust=(1.-basin*.72)*smoothstep(45.,520.,vTerrainLowWorldPosition.y)*(1.-wash*.74);float aggregate=terrainSedRidge(p/13.+vec2(2.2,18.1));diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.38,.30,.22),basin*.10);diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.30,.36,.38),film*.06);diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.53,.48,.39),wash*.032);diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.47,.39,.28),crust*.025);diffuseColor.rgb+=vec3(.008,.006,.003)*aggregate;}
void terrainSedimentApplyRoughness(){vec2 p=vTerrainLowWorldPosition.xz;float slope=1.-clamp(abs(normalize(vTerrainLowWorldNormal).y),0.,1.);float film=(1.-smoothstep(1.5,9.5,slope))*(1.-smoothstep(3.,24.,slope))*terrainSedFbm(p/52.+vec2(-2.4,15.6));float wash=smoothstep(4.,31.,slope);float aggregate=terrainSedRidge(p/13.+vec2(2.2,18.1));roughnessFactor=clamp(roughnessFactor+aggregate*.048+wash*.055-film*.105,0.42,1.0);}
void terrainSedimentApplyNormal(){vec2 p=vTerrainLowWorldPosition.xz;vec3 n=normalize(vTerrainLowWorldNormal);float slope=1.-clamp(abs(n.y),0.,1.);float wash=smoothstep(4.,31.,slope);float a=terrainSedFbm(p/29.+vec2(2.4,-5.2));float b=terrainSedFbm(p/29.+vec2(3.1,-4.4));float c=terrainSedRidge(p/118.+vec2(-8.7,12.1));vec2 g=vec2(b-a,c-.5);normal=normalize(normal+mat3(viewMatrix)*vec3(-g.x,0.,-g.y)*(wash*.42)*.085);}`;
export function installTerrainSediment(material){if(!material)throw new TypeError('terrain sediment response requires a material');if(material.userData?.terrainSedimentSurfaceInstalled)return material;const previous=material.onBeforeCompile.bind(material);material.onBeforeCompile=(shader,renderer)=>{previous(shader,renderer);shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\n${TERRAIN_SEDIMENT_GLSL}`);shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nterrainSedimentApplyColor();');shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nterrainSedimentApplyRoughness();');shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nterrainSedimentApplyNormal();');};const previousKey=material.customProgramCacheKey?.bind(material);material.customProgramCacheKey=()=>`${previousKey?previousKey():''}|${TERRAIN_SEDIMENT_POLICY.materialKey}|${TERRAIN_BIOGENIC_POLICY.materialKey}|${TERRAIN_RUNOFF_PATH_POLICY.materialKey}|${TERRAIN_SOIL_STRUCTURE_POLICY.materialKey}|${TERRAIN_SEASONAL_POLICY.materialKey}`;material.userData={...material.userData,terrainSedimentSurfaceInstalled:true,terrainSedimentPolicyId:TERRAIN_SEDIMENT_POLICY.id,terrainSedimentRenderOnly:true,terrainSedimentCanonicalHeightUnchanged:true,terrainSedimentCanonicalHydrologyUnchanged:true,terrainSedimentCanonicalCoastlineUnchanged:true,terrainSedimentCanonicalColliderUnchanged:true,terrainSedimentCanonicalVegetationPlacementUnchanged:true,terrainBiogenicPolicyId:TERRAIN_BIOGENIC_POLICY.id,terrainRunoffPolicyId:TERRAIN_RUNOFF_PATH_POLICY.id,terrainSoilStructurePolicyId:TERRAIN_SOIL_STRUCTURE_POLICY.id,terrainSeasonalPolicyId:TERRAIN_SEASONAL_POLICY.id};material.needsUpdate=true;installTerrainBiogenic(material);installTerrainRunoffPaths(material);installTerrainSoilStructure(material);installTerrainSeasonal(material);return material;}
export function sedimentPolicySnapshot(){return Object.freeze({id:TERRAIN_SEDIMENT_POLICY.id,profileCount:TERRAIN_SEDIMENT_POLICY.profileCount,calibrationCount:TERRAIN_SEDIMENT_POLICY.calibrationCount,scales:Object.freeze([TERRAIN_SEDIMENT_POLICY.broadScaleMeters,TERRAIN_SEDIMENT_POLICY.mesoScaleMeters,TERRAIN_SEDIMENT_POLICY.basinScaleMeters,TERRAIN_SEDIMENT_POLICY.rillScaleMeters,TERRAIN_SEDIMENT_POLICY.aggregateScaleMeters,TERRAIN_SEDIMENT_POLICY.poreScaleMeters,TERRAIN_SEDIMENT_POLICY.filmScaleMeters]),renderOnly:true,deterministic:true,invariants:TERRAIN_SEDIMENT_CANONICAL_INVARIANTS});}
