import { analyzeMaterialSurfaces, buildRecommendedLayerRecipe, applyMaterialRecipe, validateMaterialAssignment, createMaterialManifest } from '../materials/MaterialAssignmentCore.js';
import { prepareWorldAssetForPlacement, attachPreparedWorldAsset, auditWorldAssetPlacement } from './WorldAssetPlacementPipeline.js';
import { TERRAIN_ENVIRONMENT_CONTRACT, analyzeTerrainSurfaceForEnvironment, prepareTerrainEnvironmentAssetContext, assertTerrainEnvironmentAttachReady } from './terrainEnvironmentContract.js';
import { resolveTerrainEnvironmentProfile } from './terrainEnvironmentProfiles.js';
import { findVerifiedEnvironmentAsset, validateVerifiedEnvironmentAsset } from './terrainEnvironmentAssetRegistry.js';
import { ecotoneComposition, deterministicSpatialOrdinal } from './terrainEnvironmentSpatialPolicy.js';
const freeze = (v) => Object.freeze(v);
const finite = (v, fallback=0) => Number.isFinite(Number(v)) ? Number(v) : fallback;
export const TERRAIN_ENVIRONMENT_DIRECTOR_POLICY = freeze({ id:'buzul-muhafizi-environment-director-2026-09-07-v1', contractId:TERRAIN_ENVIRONMENT_CONTRACT.id, materialAuthority:TERRAIN_ENVIRONMENT_CONTRACT.canonicalAuthorities.material, placementAuthority:TERRAIN_ENVIRONMENT_CONTRACT.canonicalAuthorities.placement, attachOnlyAfterValidation:true, placeholderAllowed:false, editorRuntimeImportAllowed:false });
function importedSurfaceExists(root) { return analyzeMaterialSurfaces(root).surfaces.some((surface) => surface.material && !surface.material.userData?.generatedByTextureFactory && !surface.material.userData?.layeredMaterial); }
export function createEnvironmentDirectorContext(asset, options={}) {
  const category=options.category??asset?.category, x=finite(options.worldX), z=finite(options.worldZ), profile=resolveTerrainEnvironmentProfile(category,asset??{});
  const source=asset?.src||asset?.id ? findVerifiedEnvironmentAsset(asset.src??asset.id) : asset;
  const registry=validateVerifiedEnvironmentAsset(source,{category,sample:options.sample??{}});
  const surface=analyzeTerrainSurfaceForEnvironment({...options.sample??{},worldX:x,worldZ:z});
  const context=prepareTerrainEnvironmentAssetContext(source,{category,worldX:x,worldZ:z,seedOrdinal:options.seedOrdinal??0,biome:options.biome??options.sample?.biome??'',climate:options.climate??'',winter:Boolean(options.winter),sample:options.sample??{}});
  return freeze({policyId:TERRAIN_ENVIRONMENT_DIRECTOR_POLICY.id,contractId:TERRAIN_ENVIRONMENT_CONTRACT.id,asset:source??null,profile,registry,surface,context,spatial:ecotoneComposition(category,{...options.sample??{},worldX:x,worldZ:z,seed:options.seed??0x51f15e}),attachGate:assertTerrainEnvironmentAttachReady(context)});
}
export function auditEnvironmentAssetForDirector(root,metadata={}) { const material=validateMaterialAssignment(root); const registry=validateVerifiedEnvironmentAsset({id:metadata.id,src:metadata.src,category:metadata.category,placeholder:root?.userData?.isPlaceholder===true},{category:metadata.category,sample:metadata.sample??{}}); const errors=[...material.errors,...registry.errors]; if(root?.userData?.editorMaterialRecipe&&metadata.runtime===true)errors.push('editor-recipe-runtime-leak'); return freeze({ok:errors.length===0,errors:freeze(errors),material,registry}); }
export function prepareEnvironmentAsset(root,{asset={},category=asset.category,worldX=root?.position?.x??0,worldZ=root?.position?.z??0,seedOrdinal=0,biome='',climate='',winter=false,sample={},surfaceQuery=null,placementPolicy=null,preferLayers=true,scale=null,rotation=null,requireGeneratedTexture=true}={}) {
  if(!root)return {ok:false,error:'missing-object'}; if(root.userData?.isPlaceholder)return {ok:false,error:'placeholder-model'};
  const director=createEnvironmentDirectorContext(asset,{category,worldX,worldZ,seedOrdinal,biome,climate,winter,sample}); if(!director.registry.verified||!director.registry.ok)return {ok:false,error:'asset-registry-validation-failed',director}; if(!director.context.attachAllowed)return {ok:false,error:'terrain-environment-context-rejected',director};
  let material={ok:true,mode:'preserve'};
  if(!importedSurfaceExists(root)) { const recipe=preferLayers?buildRecommendedLayerRecipe(root,{metadata:{...asset,category},textureSize:256}):null; if(!recipe)return {ok:false,error:'no-shared-material-recipe',director}; material=applyMaterialRecipe(root,recipe,{metadata:{...asset,category,src:asset.src}}); if(!material.ok)return {ok:false,error:`material:${material.error??'failed'}`,director}; }
  const transform=director.context.transform, s=scale??transform.scale, r=rotation??{x:transform.pitchRadians,y:transform.yawRadians,z:transform.rollRadians};
  const placement=prepareWorldAssetForPlacement(root,{metadata:{...asset,category,src:asset.src},materialRecipe:null,position:{x:worldX,y:root.position?.y??0,z:worldZ},rotation:r,scale:{x:s,y:s,z:s},surfaceQuery,placementPolicy,requireSurfaceContext:true,snapToGround:true,footprintGrounding:'auto',requireGeneratedTexture});
  if(!placement.ok)return {ok:false,error:placement.error??'shared-placement-rejected',director,material};
  const validation=validateMaterialAssignment(root,{requireGeneratedTexture}); if(!validation.ok)return {ok:false,error:validation.errors.join(','),director,material,validation};
  const manifest=createMaterialManifest(root,{metadata:{...asset,category,src:asset.src},placement:{position:{x:root.position.x,y:root.position.y,z:root.position.z},rotation:{x:root.rotation.x,y:root.rotation.y,z:root.rotation.z},scale:{x:root.scale.x,y:root.scale.y,z:root.scale.z}}}); root.userData ||= {}; root.userData.buzulMuhafiziEnvironment=freeze({policyId:TERRAIN_ENVIRONMENT_DIRECTOR_POLICY.id,contractId:TERRAIN_ENVIRONMENT_CONTRACT.id,assetId:asset.id??'',materialMode:material.mode,deterministicSeed:deterministicSpatialOrdinal(asset.id??category,worldX,worldZ,seedOrdinal),surfaceManifest:director.surface.manifest,materialManifest:manifest}); return {ok:true,object:root,director,material,placement,validation,manifest};
}
export function attachEnvironmentAsset(scene,prepared){ if(!scene||!prepared?.ok)return {ok:false,error:'asset-not-prepared'}; const attached=attachPreparedWorldAsset(scene,prepared.placement); if(!attached.ok)return attached; const audit=auditWorldAssetPlacement(prepared.object); if(!audit.ok){scene.remove(prepared.object);return {ok:false,error:`post-attach-audit:${audit.errors.join(',')}`,audit};} prepared.object.userData.buzulMuhafiziEnvironmentAttached=true; return freeze({ok:true,object:prepared.object,manifest:prepared.manifest,audit}); }
export function buildEnvironmentDirectorTelemetry(prepared){ return freeze({policyId:TERRAIN_ENVIRONMENT_DIRECTOR_POLICY.id,assetId:prepared?.director?.asset?.id??'',category:prepared?.director?.profile?.category??'',substrate:prepared?.director?.surface?.substrate??'',attached:Boolean(prepared?.object?.userData?.buzulMuhafiziEnvironmentAttached),placementReady:Boolean(prepared?.ok),manifestPresent:Boolean(prepared?.manifest)}); }
