const freeze=(v)=>Object.freeze(v);const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
export const TERRAIN_ENVIRONMENT_VISUAL_SAMPLING_POLICY=freeze({id:'terrain-environment-visual-sampling-2026-09-07-v2',deterministic:true,canonicalTerrainAuthority:'src/3d/world/terrain.js',canonicalWaterAuthority:'src/3d/world/water.js',noGeometryMutation:true,worldSpace:true});
function normalizeSample(sample={}){return {worldX:finite(sample.worldX),worldZ:finite(sample.worldZ),heightMeters:finite(sample.heightMeters),heightAboveSeaMeters:finite(sample.heightAboveSeaMeters),slopeDegrees:clamp(finite(sample.slopeDegrees),0,90),rockWeight:clamp(finite(sample.rockWeight)),snowWeight:clamp(finite(sample.snowWeight)),waterWeight:clamp(finite(sample.waterWeight)),moisture:sample.moisture==null?null:clamp(finite(sample.moisture)),biome:String(sample.biome??''),waterDepth:Math.max(0,finite(sample.waterDepth)),concavityMeters:finite(sample.concavityMeters)};}
export function buildVisualSample(sample={}){const s=normalizeSample(sample);const coastal=clamp(1-s.heightAboveSeaMeters/24);const steep=clamp(s.slopeDegrees/55);const exposedRock=clamp(Math.max(s.rockWeight,steep*.72));const snowEdge=clamp(s.snowWeight*(1-steep));const ecologicalMoisture=s.moisture==null?clamp(.48+s.waterWeight*.32-s.heightAboveSeaMeters*.0007+s.concavityMeters*.018):s.moisture;return freeze({...s,coastal,steep,exposedRock,snowEdge,ecologicalMoisture});}
export function compareVisualSamples(a={},b={}){const x=buildVisualSample(a),y=buildVisualSample(b);return freeze({delta:freeze({heightMeters:x.heightMeters-y.heightMeters,slopeDegrees:x.slopeDegrees-y.slopeDegrees,rockWeight:x.rockWeight-y.rockWeight,snowWeight:x.snowWeight-y.snowWeight,waterWeight:x.waterWeight-y.waterWeight,moisture:finite(x.ecologicalMoisture)-finite(y.ecologicalMoisture)}),a:x,b:y});}
export function terrainAssetEnvelope({sample={},category='',profile=null,spatial=null}={}){const s=buildVisualSample(sample);const p=profile??{};const eco=spatial??{};const slopeMin=finite(p.minSlopeDegrees,0),slopeMax=finite(p.maxSlopeDegrees,90);const allowedSlope=s.slopeDegrees>=slopeMin&&s.slopeDegrees<=slopeMax;const aboveMin=s.heightAboveSeaMeters>=finite(p.minHeightMeters,-Infinity);const belowMax=s.heightAboveSeaMeters<=finite(p.maxHeightMeters,Infinity);const waterAllowed=s.waterDepth<=finite(p.maxWaterDepthMeters,0);const biomeOk=!p.allowedBiomes?.length||p.allowedBiomes.includes('any')||p.allowedBiomes.includes(s.biome);const density=clamp(finite(eco.densityMultiplier,1));return freeze({category,allowed:allowedSlope&&aboveMin&&belowMax&&waterAllowed&&biomeOk,ground:{heightMeters:s.heightMeters,slopeDegrees:s.slopeDegrees,waterDepth:s.waterDepth},surface:{rockWeight:s.rockWeight,snowWeight:s.snowWeight,moisture:s.ecologicalMoisture},spatial:{densityMultiplier:density,coreWeight:clamp(finite(eco.coreWeight)),ecotoneWeight:clamp(finite(eco.ecotoneWeight)),groveOpeningWeight:clamp(finite(eco.groveOpeningWeight))}});}
export function validateVisualSample(sample={}){const s=buildVisualSample(sample);const errors=[];if(!Number.isFinite(s.heightMeters))errors.push('non-finite-height');if(s.slopeDegrees<0||s.slopeDegrees>90)errors.push('slope-range');if(s.waterDepth<0)errors.push('negative-water-depth');if(s.snowWeight<0||s.snowWeight>1)errors.push('snow-range');if(s.rockWeight<0||s.rockWeight>1)errors.push('rock-range');if(!Number.isFinite(s.snowEdge))errors.push('invalid-snow-edge');return freeze({ok:errors.length===0,errors:freeze(errors),sample:s});}
export function buildVisualSamplingManifest(samples=[]){const reports=samples.map(validateVisualSample),errors=reports.flatMap(r=>r.errors);return freeze({version:1,policyId:TERRAIN_ENVIRONMENT_VISUAL_SAMPLING_POLICY.id,reports,errors:freeze(errors),acceptance:freeze({ok:errors.length===0,errorCount:errors.length})});}
