import { TERRAIN_SURFACE_FABRIC_POLICY, buildTerrainSurfaceManifest, terrainSurfaceReliefContext, terrainSurfaceColorMultiplier, terrainSurfaceRoughness, terrainSurfaceNormalGain, chooseTerrainSubstrate } from './terrainSurfaceFabric.js';
import { TERRAIN_ENVIRONMENT_PROFILE_POLICY, resolveTerrainEnvironmentProfile, environmentSurfaceScore, validateTerrainEnvironmentPlacement, deterministicAssetTransform, makeEnvironmentAssetManifest } from './terrainEnvironmentProfiles.js';
import { ENVIRONMENT_ASSET_REGISTRY_POLICY, findVerifiedEnvironmentAsset, selectVerifiedEnvironmentCandidates, environmentAssetPlacementPlan, validateVerifiedEnvironmentAsset, deterministicEnvironmentSeed } from './terrainEnvironmentAssetRegistry.js';
import { buildSpatialDistributionManifest, ecotoneComposition } from './terrainEnvironmentSpatialPolicy.js';
const freeze = (v) => Object.freeze(v);
export const TERRAIN_ENVIRONMENT_CONTRACT = freeze({ id:'buzul-muhafizi-terrain-environment-contract-2026-09-07-v2', sequence:freeze(['asset-hydrate','surface-analysis','material-recipe','material-validation','ground-transform','placement-manifest','scene-attach']), canonicalAuthorities:freeze({height:'src/3d/world/terrain.js',hydrology:'map/Pindex hydrology',material:'src/3d/materials/MaterialAssignmentCore.js',placement:'src/3d/world/WorldAssetPlacementPipeline.js'}), forbiddenShortcuts:freeze(['procedural-placeholder','editor-runtime-import','attach-before-material-validation','attach-before-ground-validation','visual-fabric-modifies-height','visual-fabric-modifies-hydrology']) });
export function analyzeTerrainSurfaceForEnvironment(sample={}) { const context=terrainSurfaceReliefContext(sample); return freeze({contractId:TERRAIN_ENVIRONMENT_CONTRACT.id,substrate:chooseTerrainSubstrate(context),context,response:freeze({colorMultiplier:terrainSurfaceColorMultiplier(context),roughness:terrainSurfaceRoughness(context),normalGain:terrainSurfaceNormalGain(context)}),manifest:buildTerrainSurfaceManifest({sample,materialPolicyId:TERRAIN_SURFACE_FABRIC_POLICY.id,sourceMapPolicyId:sample.sourceMapPolicyId??null})}); }
export function queryTerrainEnvironmentAssetFamily(category,context={}) { const profile=resolveTerrainEnvironmentProfile(category,context.metadata??{}); return freeze({contractId:TERRAIN_ENVIRONMENT_CONTRACT.id,category:profile?.category??null,profile,requirement:environmentAssetPlacementPlan({},{category}),candidates:selectVerifiedEnvironmentCandidates(category,{biome:context.biome,winter:Boolean(context.winter),context:context.context})}); }
export function prepareTerrainEnvironmentAssetContext(asset,{category=asset?.category,worldX=0,worldZ=0,seedOrdinal=0,biome='',climate='',winter=false,sample={}}={}) { const profile=resolveTerrainEnvironmentProfile(category,asset??{}); const registryAsset=asset?.src||asset?.id?findVerifiedEnvironmentAsset(asset.src??asset.id):null; const chosen=registryAsset??asset??null; const validation=validateVerifiedEnvironmentAsset(chosen,{category,sample}); const placementValidation=validateTerrainEnvironmentPlacement(profile,sample); const surfaceScore=environmentSurfaceScore(profile,{slopeDegrees:sample.slopeDegrees??sample.slope,heightMeters:sample.heightMeters??sample.height,moisture:sample.moisture,waterDepth:sample.waterDepth,biome:sample.biome,roadDistance:sample.roadDistance,settlementDistance:sample.settlementDistance}); const deterministicSeed=deterministicEnvironmentSeed(chosen?.id??category,worldX,worldZ); const transform=deterministicAssetTransform(deterministicSeed,seedOrdinal,profile); const plan=environmentAssetPlacementPlan(chosen??{},{category,worldX,worldZ,biome,climate,winter,sample}); const spatial=buildSpatialDistributionManifest({category,seed:deterministicSeed,worldX,worldZ,sample}); return freeze({contractId:TERRAIN_ENVIRONMENT_CONTRACT.id,asset:chosen,profile,registry:freeze({verified:Boolean(registryAsset),validation}),surface:freeze({score:surfaceScore,validation:placementValidation,analysis:analyzeTerrainSurfaceForEnvironment({...sample,worldX,worldZ})}),transform,plan,spatial,attachAllowed:Boolean(chosen&&registryAsset&&validation.ok&&placementValidation.ok&&surfaceScore>0&&plan.material?.required&&plan.placement?.manifestRequired)}); }
export function finalizeTerrainEnvironmentManifest(context,{materialManifest=null,placementManifest=null}={}) { if(!context||typeof context!=='object') return null; return makeEnvironmentAssetManifest({asset:context.asset??{},profile:context.profile??null,sample:context.surface?.analysis?.context??{},transform:context.transform??null,materialManifest,placementManifest}); }
export function assertTerrainEnvironmentAttachReady(context) { const errors=[]; if(!context?.asset)errors.push('missing-asset'); if(!context?.registry?.verified)errors.push('asset-not-verified'); if(!context?.registry?.validation?.ok)errors.push('asset-validation-failed'); if(!context?.surface?.validation?.ok)errors.push('surface-placement-failed'); if(!(context?.surface?.score>0))errors.push('surface-score-zero'); if(!context?.plan?.material?.required)errors.push('material-contract-missing'); if(!context?.plan?.placement?.required)errors.push('placement-contract-missing'); if(!context?.plan?.placement?.manifestRequired)errors.push('placement-manifest-missing'); return freeze({ok:errors.length===0,errors:freeze(errors)}); }
export function environmentContextForOtherOwners(category,sample={},asset={}) { const context=prepareTerrainEnvironmentAssetContext(asset,{category,worldX:sample.worldX,worldZ:sample.worldZ,biome:sample.biome,climate:sample.climate,winter:sample.winter,sample}); return freeze({queryOnly:true,contractId:TERRAIN_ENVIRONMENT_CONTRACT.id,gate:assertTerrainEnvironmentAttachReady(context),asset:context.asset,profile:context.profile,surfaceScore:context.surface.score,deterministicTransform:context.transform,spatial:ecotoneComposition(category,{...sample,seed:sample.seed}),heightAuthority:TERRAIN_ENVIRONMENT_CONTRACT.canonicalAuthorities.height,materialAuthority:TERRAIN_ENVIRONMENT_CONTRACT.canonicalAuthorities.material,placementAuthority:TERRAIN_ENVIRONMENT_CONTRACT.canonicalAuthorities.placement}); }
export function validateTerrainEnvironmentContract() { const errors=[]; if(TERRAIN_ENVIRONMENT_CONTRACT.sequence.join('>')!=='asset-hydrate>surface-analysis>material-recipe>material-validation>ground-transform>placement-manifest>scene-attach')errors.push('operation-sequence'); if(TERRAIN_SURFACE_FABRIC_POLICY.canonicalHeightUnchanged!==true)errors.push('surface-height-bypass'); if(TERRAIN_SURFACE_FABRIC_POLICY.canonicalHydrologyUnchanged!==true)errors.push('surface-hydrology-bypass'); if(ENVIRONMENT_ASSET_REGISTRY_POLICY.placeholderAllowed!==false)errors.push('placeholder-policy-open'); if(TERRAIN_ENVIRONMENT_PROFILE_POLICY.editorRuntimeImportAllowed!==false)errors.push('editor-runtime-import-open'); return freeze({ok:errors.length===0,errors,contractId:TERRAIN_ENVIRONMENT_CONTRACT.id}); }
