import { TERRAIN_SEASONAL_EROSION_POLICY, seasonalErosionProfileAt, seasonalErosionProfileByClimate } from './terrainSeasonalErosionProfiles.js';
const freeze=v=>Object.freeze(v); const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f; const c01=v=>Math.max(0,Math.min(1,finite(v))); const lerp=(a,b,t)=>a+(b-a)*t; const smooth=(a,b,v)=>{const t=c01((finite(v)-a)/Math.max(1e-6,b-a));return t*t*(3-2*t);};
export const TERRAIN_SEASONAL_CYCLE_POLICY=freeze({id:'terrain-seasonal-erosion-cycle-2026-09-15-v1',deterministic:true,renderOnly:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,dayCount:360,seasonLengthDays:90,memoryDays:28,moistureHalfLifeDays:11,frostHalfLifeDays:7,dryingHalfLifeDays:16,materialKey:'terrain-seasonal-erosion-cycle-v1'});
const SEASONS=freeze(['spring','summer','autumn','winter']); const MONTH_TO_SEASON=freeze(['winter','winter','spring','spring','spring','summer','summer','summer','autumn','autumn','autumn','winter']);
function hash2D(x,z,seed=0x5131){let h=Math.imul((x|0)^seed,0x45d9f3b)^Math.imul((z|0)+seed,0x119de1f3);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return(h>>>0)/4294967296;}
function noise(x,z,seed=0x5132){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,ux=fx*fx*(3-2*fx),uz=fz*fz*(3-2*fz),a=hash2D(ix,iz,seed),b=hash2D(ix+1,iz,seed),d=hash2D(ix+1,iz+1,seed),e=hash2D(ix,iz+1,seed);return lerp(lerp(a,b,ux),lerp(e,d,ux),uz);}
function fbm(x,z,seed,n=4){let v=0,w=0,a=.55;for(let i=0;i<n;i++){v+=noise(x,z,seed+i*79)*a;w+=a;x=x*2.03+17.1;z=z*2.01-11.7;a*=.48;}return v/Math.max(1e-6,w);} const ridge=(x,z,s)=>1-Math.abs(fbm(x,z,s)*2-1);
export function normalizeDayOfYear(day=1){const n=Math.floor(finite(day,1));return((n-1)%360+360)%360+1;}
export function seasonAtDay(day=1){return SEASONS[Math.min(3,Math.floor((normalizeDayOfYear(day)-1)/90))];}
export function seasonalForcingAtDay(day=1){const phase=(normalizeDayOfYear(day)-.5)/360,a=phase*Math.PI*2,warm=.5+.5*Math.sin(a-Math.PI/2),thaw=smooth(.18,.44,warm)*smooth(.18,.72,1-warm*.52),rain=c01(.56+Math.sin(a+.9)*.24),dry=c01(.56+Math.sin(a-1.5)*.32),frost=smooth(.52,.18,warm),snowmelt=smooth(.18,.46,warm)*(1-smooth(.58,.88,warm));return freeze({season:seasonAtDay(day),phase,warmth:warm,thaw,rain,dry,frost,snowmelt});}
export function seasonalTemperatureC({dayOfYear=1,meanC=11,amplitudeC=9}={}){const f=seasonalForcingAtDay(dayOfYear);return meanC+(f.warmth-.5)*amplitudeC*2;}
export function seasonalPrecipitationMultiplier({dayOfYear=1,annualMean=1}={}){return annualMean*c01(.62+seasonalForcingAtDay(dayOfYear).rain*.42);}
export function snowpackState({dayOfYear=1,snowfall=.5,temperatureC=null}={}){const f=seasonalForcingAtDay(dayOfYear),t=temperatureC==null?seasonalTemperatureC({dayOfYear}):finite(temperatureC),frozen=smooth(2.5,-3.5,t),melt=c01(f.snowmelt*(1-frozen*.35)),pack=c01(snowfall*(frozen*.88+(1-frozen)*.22));return freeze({pack,frozen,melt,runoffPulse:c01(melt*pack*1.35)});}
export function freezeThawState({temperatureC=4,humidity=.6,substrate='granite'}={}){const t=finite(temperatureC,4),wet=c01(humidity),near=1-smooth(-5,2,Math.abs(t)),below=smooth(2,-6,t),above=smooth(-1,7,t),cycle=c01(near*(.55+wet*.45)),raw=c01(cycle*below*(.62+wet*.38)),brittle=/schist|shale|slate|mudstone|tuff|talus/i.test(substrate);return freeze({nearFreeze:near,below,above,cycle,crack:brittle?c01(raw*1.18):raw,relax:c01(above*(1-below)*.18),brittle});}
export function soilMoistureMemory({current=.5,rainfall=.5,runoff=.3,evaporation=.2,days=1}={}){const c=c01(current),r=c01(rainfall),flow=c01(runoff),ev=c01(evaporation),dt=Math.max(.001,finite(days,1)),memory=1-Math.exp(-dt/11),target=c01(c*.46+r*.42+(1-flow)*.08-ev*.28),value=lerp(c,target,memory);return freeze({previous:c,target,value,memory,rainfall:r,runoff:flow,evaporation:ev});}
export function droughtMemory({moisture=.5,daysDry=0}={}){const wet=c01(moisture),days=Math.max(0,finite(daysDry)),signal=1-Math.exp(-days/16);return freeze({signal,stress:c01(signal*(1-wet)*1.15),dryDays:days});}
export function frostMemory({ice=.3,cycles=0}={}){const frozen=c01(ice),count=Math.max(0,finite(cycles)),signal=1-Math.exp(-count/7);return freeze({signal,wear:c01(signal*frozen),cycles:count,ice:frozen});}
export function runoffPulse({rainfall=.5,slopeDegrees=8,drainage=.5,snowmelt=0}={}){const rain=c01(rainfall),slope=smooth(1.5,31,finite(slopeDegrees,8)),drain=c01(drainage),melt=c01(snowmelt),concentrated=c01((rain*.67+melt*.51)*(.35+slope*.65)),retention=c01((1-drain)*(1-slope*.42)),rill=c01(concentrated*(.48+slope*.42));return freeze({concentrated,retention,rill,sheet:c01(concentrated*(1-slope*.58)),pulse:c01(concentrated+retention*.17)});}
export function windDrying({windExposure=.5,canopy=.4,humidity=.6}={}){const wind=c01(windExposure),cover=c01(canopy),moisture=c01(humidity),vent=c01(wind*(.56+(1-cover)*.44)),dry=c01(vent*(.58+(1-moisture)*.42));return freeze({ventilation:vent,dry,shelter:c01(1-vent),canopy:cover,humidity:moisture});}
export function annualErosionForcing({dayOfYear=1,profileIndex=0}={}){const p=seasonalErosionProfileAt(profileIndex),f=seasonalForcingAtDay(dayOfYear),rain=c01(f.rain*p.rainfallMm/1200),snow=c01(f.snowmelt*p.snowfallMm/900),frost=c01(f.frost*p.freezeCycles/140),wet=c01(p.saturation*(.56+f.rain*.44)),dryness=c01(p.crust*(.32+f.dry*.68));return freeze({rain,snowmelt:snow,frost,wet,dryness,erosivity:c01(p.erosion*(.46+rain*.34+snow*.22)),frostWear:c01(p.frostWear*(.32+frost*.68)),dryCrust:dryness,mudTint:c01(p.mudTint*(.35+wet*.65))});}
export function resolveSeasonalErosionState(input={}){const x=finite(input.worldX),z=finite(input.worldZ),day=normalizeDayOfYear(input.dayOfYear??180),forcing=seasonalForcingAtDay(day),profiles=seasonalErosionProfileByClimate(input.climate??'temperate'),profile=(profiles.length?profiles[Math.abs(Math.floor(finite(input.profileIndex)))%profiles.length]:seasonalErosionProfileAt(input.profileIndex??0)),slope=finite(input.slopeDegrees,8),moisture=c01(input.moisture,.5),rainfall=c01(input.rainfall,.5),local=c01(fbm(x/1200,z/1200,0x5a11,5)*.62+ridge(x/280,z/280,0x5a12)*.38),rills=c01(ridge(x/46,z/67,0x5a13)*.7+fbm(x/90,z/90,0x5a14,3)*.3),frostPockets=c01(fbm(x/31,z/27,0x5a15,4)*.72+(1-rills)*.28),temp=input.temperatureC==null?seasonalTemperatureC({dayOfYear:day}):finite(input.temperatureC,5),snow=snowpackState({dayOfYear:day,snowfall:input.snowWeight??0,temperatureC:temp}),thaw=freezeThawState({temperatureC:temp,humidity:moisture,substrate:input.substrate??profile.substrate}),pulse=runoffPulse({rainfall,slopeDegrees:slope,drainage:input.drainage??profile.drainage,snowmelt:snow.runoffPulse}),drying=windDrying({windExposure:input.windExposure??profile.exposure,canopy:input.canopy??.4,humidity:moisture}),memory=soilMoistureMemory({current:moisture,rainfall,runoff:pulse.pulse,evaporation:drying.dry}),drought=droughtMemory({moisture:memory.value,daysDry:input.dryDays??0}),frost=frostMemory({ice:c01(snow.pack+thaw.cycle*.34),cycles:input.frozenDays??0}),annual=annualErosionForcing({dayOfYear:day,profileIndex:input.profileIndex??0}),profileFactor=c01(profile.erosion*.58+annual.erosivity*.42),erosion=c01(profileFactor*(.28+pulse.rill*.45+local*.16+thaw.crack*.11)),frostWear=c01(profile.frostWear*(.22+frost.wear*.47+frostPockets*.19+thaw.crack*.12)),deposition=c01((1-pulse.rill)*memory.value*profile.mossRetention*.37+(1-drying.dry)*profile.dustRetention*.24),mud=c01(profile.mudTint*(memory.value*.64+pulse.retention*.22+snow.melt*.14)),crust=c01(profile.crust*(drying.dry*.62+drought.stress*.28+(1-memory.value)*.10)),seasonalAge=c01((erosion*.42+frostWear*.36+crust*.22)*(.58+forcing.rain*.18+forcing.frost*.24));return freeze({worldX:x,worldZ:z,dayOfYear:day,season:forcing.season,seasonPhase:forcing.phase,temperatureC:temp,profile,local,rills,frostPockets,snow,thaw,pulse,drying,moisture:memory,drought,frost,annual,erosion,frostWear,deposition,mud,crust,seasonalAge,heightMeters:finite(input.heightMeters),slopeDegrees:slope,canonicalTerrainUntouched:true});}
export function seasonalErosionMaterialResponse({state,baseColor={r:.5,g:.45,b:.38},baseRoughness=.86}={}){if(!state)throw new TypeError('seasonal erosion material response requires state');const wet=state.moisture.value,dry=state.drying.dry,mud=state.mud,erosion=state.erosion,frost=state.frostWear,crust=state.crust,deposition=state.deposition,age=state.seasonalAge,color=freeze({r:c01(baseColor.r-mud*.072+crust*.041+deposition*.018+frost*.006),g:c01(baseColor.g-mud*.051+crust*.031+deposition*.029-erosion*.013),b:c01(baseColor.b+mud*.021+frost*.017-crust*.012)}),roughness=c01(baseRoughness+crust*.082+frost*.066+erosion*.028-wet*.091-dry*.018),normalStrength=c01(erosion*.067+frost*.061+state.rills*.035+age*.021);return freeze({color,roughness,normalStrength,specularDamping:c01(mud*.22+wet*.11+frost*.07),wet,dry,erosion,frostWear:frost,crust,deposition,seasonalAge:age});}
export function seasonalErosionSignature(input={}){const s=resolveSeasonalErosionState(input);return freeze({season:s.season,profileId:s.profile.id,erosion:+s.erosion.toFixed(6),frostWear:+s.frostWear.toFixed(6),deposition:+s.deposition.toFixed(6),mud:+s.mud.toFixed(6),crust:+s.crust.toFixed(6),seasonalAge:+s.seasonalAge.toFixed(6)});}
export function validateSeasonalErosionState(state){const errors=[];for(const key of ['erosion','frostWear','deposition','mud','crust','seasonalAge'])if(!(Number.isFinite(state?.[key])&&state[key]>=0&&state[key]<=1))errors.push(`${key}-range`);if(state?.canonicalTerrainUntouched!==true)errors.push('canonical-terrain-boundary');return freeze({ok:errors.length===0,errors:freeze(errors),policyId:TERRAIN_SEASONAL_CYCLE_POLICY.id});}
export function buildSeasonalErosionCatalog({climates=['temperate','subarctic','wet-temperate','dry-temperate','highland','alpine','mediterranean','volcanic'],days=[15,105,195,285]}={}){const rows=[];for(const climate of climates)for(const dayOfYear of days)rows.push(seasonalErosionSignature({climate,dayOfYear,rainfall:.64,moisture:.58,slopeDegrees:9,snowWeight:climate==='alpine'?.88:.22}));return freeze(rows);}
export function compareSeasonalErosionStates(a,b){const keys=['erosion','frostWear','deposition','mud','crust','seasonalAge'],deltas={},max=keys.reduce((m,k)=>{const d=finite(b?.[k])-finite(a?.[k]);deltas[k]=d;return Math.max(m,Math.abs(d));},0);return freeze({deltas:freeze(deltas),maxAbsDelta:max,materiallyDifferent:max>.08});}
export const TERRAIN_SEASONAL_CYCLE_CANONICAL_INVARIANTS=freeze(['canonicalHeightUnchanged','canonicalHydrologyUnchanged','canonicalCoastlineUnchanged','canonicalColliderUnchanged','canonicalVegetationPlacementUnchanged','newGeographyIntroduced:false']);
export const TERRAIN_SEASONAL_CYCLE_SCHEMA=freeze({version:1,stateFields:freeze(['season','seasonPhase','temperatureC','profile','erosion','frostWear','deposition','mud','crust','seasonalAge']),materialFields:freeze(['color','roughness','normalStrength','specularDamping']),boundaryFields:TERRAIN_SEASONAL_CYCLE_CANONICAL_INVARIANTS});
export function seasonalMonthToDay(month=1,day=15){const m=Math.max(1,Math.min(12,Math.floor(finite(month,1)))),d=Math.max(1,Math.min(30,Math.floor(finite(day,15))));return(m-1)*30+d;}
export function seasonAtMonth(month=1){const m=Math.max(1,Math.min(12,Math.floor(finite(month,1))));return MONTH_TO_SEASON[m-1];}
export function seasonTransitionBlend(day=1){const local=(normalizeDayOfYear(day)-1)%90,edge=Math.min(local,89-local),core=smooth(0,21,edge);return freeze({season:seasonAtDay(day),day:normalizeDayOfYear(day),transition:1-core,core});}
export function seasonalAgeAccumulator(history=[]){let age=0;for(const sample of history)age=c01(age*.92+c01(sample?.erosion)*.05+c01(sample?.frostWear)*.04+c01(sample?.crust)*.03);return age;}
export function applySurfaceMemory(previous,current,deltaDays=1){const dt=Math.max(.001,finite(deltaDays,1)),alpha=1-Math.exp(-dt/28),prev=previous??current;return freeze({erosion:lerp(finite(prev?.erosion),finite(current?.erosion),alpha),frostWear:lerp(finite(prev?.frostWear),finite(current?.frostWear),alpha),deposition:lerp(finite(prev?.deposition),finite(current?.deposition),alpha),mud:lerp(finite(prev?.mud),finite(current?.mud),alpha),crust:lerp(finite(prev?.crust),finite(current?.crust),alpha),seasonalAge:lerp(finite(prev?.seasonalAge),finite(current?.seasonalAge),alpha),alpha,deltaDays:dt});}
