const freeze=v=>Object.freeze(v);
const e=(id,trigger,expected,reason)=>freeze({id,trigger,expected,reason});
export const TERRAIN_SEASONAL_EROSION_EDGE_CASES=freeze([
 e('E001','day=0','winter-boundary','normalize authored calendar without creating a second year'),
 e('E002','day=361','spring-boundary','wrap back to day one deterministically'),
 e('E003','day=-1','winter-tail','negative input remains inside authored cycle'),
 e('E004','day=720','winter-boundary','two authored years collapse to final winter day'),
 e('E005','moisture=undefined','default-moisture','runtime uses explicit 0.5 fallback'),
 e('E006','rainfall=undefined','default-rain','runtime uses explicit 0.5 fallback'),
 e('E007','wind=undefined','profile-exposure','profile provides exposure fallback'),
 e('E008','drainage=undefined','profile-drainage','profile provides drainage fallback'),
 e('E009','temperature=-20','frost-cap','normalized frost output remains bounded'),
 e('E010','temperature=40','drying-cap','high heat does not escape material bounds'),
 e('E011','slope=0','sheet-flow','zero slope cannot create maximal rill response'),
 e('E012','slope=90','steep-flow','extreme slope remains finite and bounded'),
 e('E013','humidity=0','dry-limit','dryness remains normalized'),
 e('E014','humidity=1','wet-limit','wetness remains normalized'),
 e('E015','canopy=0','wind-exposed','wind drying receives full exposure contribution'),
 e('E016','canopy=1','wind-sheltered','canopy reduces ventilation contribution'),
 e('E017','snow=0','no-pack','zero snow cannot emit pack beyond zero'),
 e('E018','snow=1','full-pack','full normalized snow input remains bounded'),
 e('E019','frozenDays=0','no-frost-memory','frost memory remains zero'),
 e('E020','frozenDays=365','frost-memory-cap','long memory approaches one without overflow'),
 e('E021','dryDays=0','no-drought-memory','drought stress remains zero'),
 e('E022','dryDays=365','drought-memory-cap','long dry spell remains normalized'),
 e('E023','worldX=0,worldZ=0','stable-origin','origin produces deterministic spatial response'),
 e('E024','worldX=1,worldZ=0','x-separation','one-meter x shift changes hash domain'),
 e('E025','worldX=0,worldZ=1','z-separation','one-meter z shift changes hash domain'),
 e('E026','worldX=100000,worldZ=-100000','large-world','large coordinates remain finite'),
 e('E027','climate=unknown','profile-fallback','unknown climate falls back to default profile'),
 e('E028','substrate=unknown','substrate-default','unknown substrate still yields valid state'),
 e('E029','profileIndex=-2','index-clamp','negative profile index resolves safely'),
 e('E030','profileIndex=9999','index-wrap','large profile index resolves within climate set'),
 e('E031','baseRoughness=-1','roughness-clamp','material response clamps lower bound'),
 e('E032','baseRoughness=2','roughness-clamp','material response clamps upper bound'),
 e('E033','baseColor<-0','color-clamp','color channels remain normalized'),
 e('E034','baseColor>1','color-clamp','color channels remain normalized'),
 e('E035','rapid-day-step','continuity','daily changes remain within acceptance envelope'),
 e('E036','season-edge-90','spring-summer','quarter boundary is deterministic'),
 e('E037','season-edge-180','summer-autumn','quarter boundary is deterministic'),
 e('E038','season-edge-270','autumn-winter','quarter boundary is deterministic'),
 e('E039','season-edge-360','winter-spring','cycle remains closed'),
 e('E040','near-freeze','frost-window','freeze-thaw activates around threshold'),
 e('E041','far-below-freeze','frozen','cold state remains finite'),
 e('E042','far-above-freeze','thaw','warm state remains finite'),
 e('E043','brittle-schist','amplified-crack','brittle response is intentional'),
 e('E044','brittle-shale','amplified-crack','brittle response is intentional'),
 e('E045','brittle-tuff','amplified-crack','brittle response is intentional'),
 e('E046','brittle-talus','amplified-crack','coarse alpine material gets frost cue'),
 e('E047','dense-granite','restrained-crack','dense rock avoids exaggerated break-up'),
 e('E048','dense-basalt','restrained-crack','dense rock avoids exaggerated break-up'),
 e('E049','wet-peat','saturation','organic wetland retains moisture'),
 e('E050','wet-clay','saturation','fine soil retains moisture'),
 e('E051','dry-gravel','drainage','coarse material drains quickly'),
 e('E052','dry-limestone','crust','dry mineral crust can appear'),
 e('E053','mediterranean-summer','seasonal-dry','summer dryness remains seasonal'),
 e('E054','mediterranean-autumn','storm-pulse','autumn storm can restore wetness'),
 e('E055','alpine-spring','snowmelt','melt dominates shoulder season'),
 e('E056','alpine-winter','freeze-thaw','winter frost dominates'),
 e('E057','highland-autumn','freeze-thaw','upland cooling increases frost'),
 e('E058','highland-summer','runoff','slope and rain drive wash'),
 e('E059','volcanic-ash-wind','dust-deposition','fine ash retains transported fines'),
 e('E060','volcanic-scoria-wind','dust-deposition','open pores capture fines'),
 e('E061','oceanic-winter','rain','mild wet winter avoids forced snow'),
 e('E062','oceanic-autumn','saturation','persistent humidity keeps wetness'),
 e('E063','wetland-wind','shelter','canopy suppresses wind drying'),
 e('E064','dryland-wind','drying','exposure accelerates surface drying'),
 e('E065','storm-high-slope','rill','concentrated runoff increases rill cue'),
 e('E066','storm-low-slope','sheet','low slope retains sheet-flow response'),
 e('E067','snowmelt-high-slope','rill','melt concentrates down steep faces'),
 e('E068','snowmelt-low-slope','wet-film','melt mostly increases wetness'),
 e('E069','repeated-identical-input','stable','same input must return equal state'),
 e('E070','same-world-different-day','seasonal-change','day is a material-relevant key'),
 e('E071','same-day-different-world','spatial-change','world coordinate is material-relevant'),
 e('E072','same-world-different-climate','profile-change','climate changes baseline response'),
 e('E073','same-world-different-substrate','material-change','substrate changes frost/erosion behavior'),
 e('E074','same-input-different-object','stable','object identity must not enter hash'),
 e('E075','frame-repeat','stable','frame number must not perturb deterministic state'),
 e('E076','night-to-day','smooth-transition','runtime phase changes continuously'),
 e('E077','chunk-recenter','stable-world-space','same world position keeps same spatial field'),
 e('E078','cache-hit','same-material','cache identity preserves material equivalence'),
 e('E079','cache-miss-new-day','new-material-key','day-specific output gets distinct cache key'),
 e('E080','shader-reinstall','idempotent','install hook does not duplicate itself'),
 e('E081','shader-null-material','throw','invalid install input fails explicitly'),
 e('E082','shader-no-height-write','boundary','shader never changes vertex height'),
 e('E083','shader-no-hydrology-write','boundary','shader never changes water topology'),
 e('E084','shader-no-vegetation-write','boundary','shader never moves vegetation'),
 e('E085','material-color-bounds','normalized','shader CPU response remains clamped'),
 e('E086','material-roughness-bounds','normalized','shader CPU response remains clamped'),
 e('E087','material-normal-bounds','normalized','normal strength remains bounded'),
 e('E088','specular-damping-bounds','normalized','specular damping remains bounded'),
 e('E089','long-grid-signatures','non-collapsed','distant coordinates remain distinguishable'),
 e('E090','profile-lookup-case','case-insensitive','climate and substrate lookup is normalized'),
]);
export const TERRAIN_SEASONAL_EROSION_EDGE_CASE_POLICY=freeze({id:'terrain-seasonal-erosion-edge-cases-2026-09-15-v1',count:TERRAIN_SEASONAL_EROSION_EDGE_CASES.length,deterministic:true,renderOnly:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true});
export function edgeCaseById(id){return TERRAIN_SEASONAL_EROSION_EDGE_CASES.find(row=>row.id===String(id??''))??null;}
export function edgeCasesByExpected(expected){const target=String(expected??'').toLowerCase();return TERRAIN_SEASONAL_EROSION_EDGE_CASES.filter(row=>row.expected.toLowerCase()===target);}
export function validateEdgeCaseCatalog(){const errors=[];const ids=new Set();for(const row of TERRAIN_SEASONAL_EROSION_EDGE_CASES){if(ids.has(row.id))errors.push(`${row.id}:duplicate`);ids.add(row.id);for(const key of ['id','trigger','expected','reason'])if(!row[key])errors.push(`${row.id}:${key}`);}return freeze({ok:errors.length===0,errors:freeze(errors),count:TERRAIN_SEASONAL_EROSION_EDGE_CASES.length});}
