import { TERRAIN_GROUNDWATER_DETAIL_CHANNELS, detailEnvelope, detailCanonicalAudit, detailSignature, detailHydroBalance, detailRenderTier, detailWeightedWetness, detailDrynessRisk, classifySurfaceDetail, resolveGroundwaterSurfaceDetail } from './terrainGroundwaterSurfaceDetail.js';
import { TERRAIN_GROUNDWATER_DETAIL_POLICY } from './terrainGroundwaterSurfaceDetail.js';
import { TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY, shaderInvariantReport } from './terrainGroundwaterSurfaceDetailShader.js';
import { TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY, detailStackAudit, detailStackHealth, detailStackStatistics, resolveGroundwaterDetailStack } from './terrainGroundwaterSurfaceDetailStack.js';
import { calibrationAudit } from './terrainGroundwaterSurfaceDetailCalibration.js';
import { presetAudit } from './terrainGroundwaterSurfaceDetailPresets.js';
const freeze=Object.freeze;
const finite=v=>Number.isFinite(Number(v));
const bounded=v=>finite(v)&&Number(v)>=0&&Number(v)<=1;
const clamp01=v=>Math.max(0,Math.min(1,finite(v)?Number(v):0));

export const TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTICS_POLICY=freeze({id:'terrain-groundwater-surface-detail-diagnostics-2026-09-15-v1',sourcePolicyId:TERRAIN_GROUNDWATER_DETAIL_POLICY.id,shaderPolicyId:TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.id,stackPolicyId:TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.id,renderOnly:true,deterministic:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,newGeographyIntroduced:false});
export const TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTIC_STAGES=freeze(['input-normalization','state-resolution','channel-bounds','canonical-ownership','material-response','shader-contract','stack-composition','calibration','preset','signature','classification','render-tier']);

export function diagnosticChannelReport(detail){const values={};const failures=[];for(const key of TERRAIN_GROUNDWATER_DETAIL_CHANNELS){const value=Number(detail?.channels?.[key]);values[key]=freeze({value,finite:finite(value),bounded:bounded(value)});if(!finite(value))failures.push(`${key}:not-finite`);else if(!bounded(value))failures.push(`${key}:out-of-range`);}return freeze({ok:failures.length===0,values:freeze(values),failures:freeze(failures)});}
export function diagnosticCanonicalReport(detail){const audit=detailCanonicalAudit(detail);return freeze({ok:audit.ok,mutationCount:audit.mutationCount,failures:audit.failures,heightUnchanged:detail?.canonical?.heightUnchanged===true,hydrologyUnchanged:detail?.canonical?.hydrologyUnchanged===true,coastlineUnchanged:detail?.canonical?.coastlineUnchanged===true,colliderUnchanged:detail?.canonical?.colliderUnchanged===true,vegetationPlacementUnchanged:detail?.canonical?.vegetationPlacementUnchanged===true,newGeographyIntroduced:detail?.canonical?.newGeographyIntroduced===false});}
export function diagnosticClimateReport(detail){const sample=detail?.state?.sample??{};const keys=['moisture','rainfall','runoff','temperatureC','drainage','windExposure'];const values=freeze(Object.fromEntries(keys.map(k=>[k,{value:Number(sample[k]),finite:finite(sample[k])}])));return freeze({ok:Object.values(values).every(v=>v.finite),values});}
export function diagnosticHydroReport(detail){const balance=detailHydroBalance(detail);return freeze({wetness:clamp01(balance.wetness),dryness:clamp01(balance.dryness),net:Math.max(-1,Math.min(1,Number(balance.net))),wetComponent:clamp01(detailWeightedWetness(detail)),dryComponent:clamp01(detailDrynessRisk(detail))});}
export function diagnosticClassificationReport(detail){const classification=classifySurfaceDetail(detail),allowed=['puddle-core','marsh-transition','seepage-band','evaporative-crust','capillary-damp','freeze-wet-edge','drying-front','wet-rim','neutral'];return freeze({ok:allowed.includes(classification),classification,allowed:freeze(allowed)});}
export function diagnosticRenderReport(detail){const tier=detailRenderTier(detail);return freeze({ok:['suppressed','low','medium','high'].includes(tier),tier,confidence:clamp01(detail?.channels?.surfaceConfidence),wetness:clamp01(detailWeightedWetness(detail)),dryness:clamp01(detailDrynessRisk(detail))});}
export function diagnosticSignatureReport(detail){const signature=detailSignature(detail);return freeze({ok:Object.keys(signature).length===TERRAIN_GROUNDWATER_DETAIL_CHANNELS.length,signature});}
export function diagnosticIdentityReport(detail){return freeze({policyId:detail?.policyId??null,sourcePolicyId:detail?.sourcePolicyId??null,expectedPolicyId:TERRAIN_GROUNDWATER_DETAIL_POLICY.id,ok:detail?.policyId===TERRAIN_GROUNDWATER_DETAIL_POLICY.id&&detail?.sourcePolicyId===TERRAIN_GROUNDWATER_DETAIL_POLICY.sourcePolicyId});}
export function diagnosticStackReport(input={},baseMaterial={}){const stack=resolveGroundwaterDetailStack(input,baseMaterial);return freeze({ok:detailStackAudit(stack).ok,policyId:stack.policyId,audit:detailStackAudit(stack),health:detailStackHealth(stack),statistics:detailStackStatistics([stack])});}
export function diagnosticShaderReport(){const report=shaderInvariantReport();return freeze({ok:report.ok,policyId:report.policyId,replacements:report.replacements,invariants:report.invariants});}
export function diagnosticCalibrationReport(){return calibrationAudit();}
export function diagnosticPresetReport(){return presetAudit();}
export function diagnosticDeterminismReport(input={}){const a=resolveGroundwaterSurfaceDetail(input),b=resolveGroundwaterSurfaceDetail({...input});const first=detailSignature(a),second=detailSignature(b);return freeze({ok:JSON.stringify(first)===JSON.stringify(second),first,second});}

export function buildGroundwaterSurfaceDetailDiagnostic(input={},baseMaterial={}){const detail=resolveGroundwaterSurfaceDetail(input);const channel=diagnosticChannelReport(detail),canonical=diagnosticCanonicalReport(detail),climate=diagnosticClimateReport(detail),hydro=diagnosticHydroReport(detail),classification=diagnosticClassificationReport(detail),render=diagnosticRenderReport(detail),signature=diagnosticSignatureReport(detail),identity=diagnosticIdentityReport(detail),determinism=diagnosticDeterminismReport(input),shader=diagnosticShaderReport(),calibration=diagnosticCalibrationReport(),preset=diagnosticPresetReport(),stack=diagnosticStackReport(input,baseMaterial);const stages={channel,canonical,climate,hydro,classification,render,signature,identity,determinism,shader,calibration,preset,stack};const failures=Object.entries(stages).filter(([,v])=>v.ok!==true).map(([k])=>k);return freeze({policyId:TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTICS_POLICY.id,sourcePolicyId:TERRAIN_GROUNDWATER_DETAIL_POLICY.id,stages:freeze(stages),failures:freeze(failures),ok:failures.length===0,summary:freeze({classification:classification.classification,tier:render.tier,wetness:hydro.wetness,dryness:hydro.dryness,net:hydro.net,confidence:render.confidence})});}

export function diagnosticBatch(inputs=[],baseMaterial={}){if(!Array.isArray(inputs))throw new TypeError('diagnostic batch requires array');return freeze(inputs.map(input=>buildGroundwaterSurfaceDetailDiagnostic(input,baseMaterial)));}
export function diagnosticBatchSummary(reports=[]){if(!Array.isArray(reports)||!reports.length)return freeze({count:0,passed:0,failed:0,passRate:1,classes:freeze({}),tiers:freeze({})});const classes={},tiers={};let passed=0;for(const report of reports){if(report.ok)passed+=1;classes[report.summary.classification]=(classes[report.summary.classification]??0)+1;tiers[report.summary.tier]=(tiers[report.summary.tier]??0)+1;}return freeze({count:reports.length,passed,failed:reports.length-passed,passRate:passed/reports.length,classes:freeze(classes),tiers:freeze(tiers)});}
export function diagnosticFailureHistogram(reports=[]){const histogram={};for(const report of Array.isArray(reports)?reports:[]){for(const failure of report.failures??[])histogram[failure]=(histogram[failure]??0)+1;}return freeze(histogram);}
export function diagnosticChannelExtrema(details=[]){const extrema=Object.fromEntries(TERRAIN_GROUNDWATER_DETAIL_CHANNELS.map(k=>[k,{min:1,max:0,mean:0}]));if(!Array.isArray(details)||!details.length)return freeze(extrema);for(const detail of details){for(const key of TERRAIN_GROUNDWATER_DETAIL_CHANNELS){const v=clamp01(detail.channels?.[key]);extrema[key].min=Math.min(extrema[key].min,v);extrema[key].max=Math.max(extrema[key].max,v);extrema[key].mean+=v;}}for(const key of TERRAIN_GROUNDWATER_DETAIL_CHANNELS)extrema[key]=freeze({...extrema[key],mean:extrema[key].mean/details.length});return freeze(Object.fromEntries(Object.entries(extrema).map(([k,v])=>[k,freeze(v)])));}
export function diagnosticOwnershipSummary(reports=[]){const rows=Array.isArray(reports)?reports:[];const failures=rows.filter(r=>r.stages?.canonical?.ok!==true).length;return freeze({count:rows.length,canonicalFailures:failures,zeroMutation:rows.every(r=>r.stages?.canonical?.mutationCount===0),noNewGeography:rows.every(r=>r.stages?.canonical?.newGeographyIntroduced===false),heightPreserved:rows.every(r=>r.stages?.canonical?.heightUnchanged===true),hydrologyPreserved:rows.every(r=>r.stages?.canonical?.hydrologyUnchanged===true)});}
export function diagnosticEnvelopeSummary(reports=[]){const rows=Array.isArray(reports)?reports:[];const failures=rows.filter(r=>r.stages?.channel?.ok!==true).length;return freeze({count:rows.length,boundsFailures:failures,allBounded:failures===0});}
export function diagnosticRunManifest(inputCount=0){return freeze({policyId:TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTICS_POLICY.id,sourcePolicyId:TERRAIN_GROUNDWATER_DETAIL_POLICY.id,shaderPolicyId:TERRAIN_GROUNDWATER_DETAIL_SHADER_POLICY.id,stackPolicyId:TERRAIN_GROUNDWATER_DETAIL_STACK_POLICY.id,stages:TERRAIN_GROUNDWATER_DETAIL_DIAGNOSTIC_STAGES,inputCount:Math.max(0,Math.floor(inputCount)),renderOnly:true,deterministic:true});}
export function diagnosticQuickCheck(input={}){const report=buildGroundwaterSurfaceDetailDiagnostic(input);return freeze({ok:report.ok,failures:report.failures,summary:report.summary});}
