import { resolveTerrainGroundwaterState, TERRAIN_GROUNDWATER_POLICY } from './terrainGroundwaterRegime.js';
const freeze=Object.freeze;
const clamp01=v=>Math.max(0,Math.min(1,Number.isFinite(Number(v))?Number(v):0));
const safe=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const lerp=(a,b,t)=>a+(b-a)*t;
const smooth=(a,b,v)=>{const t=clamp01((safe(v)-a)/Math.max(1e-9,b-a));return t*t*(3-2*t)};
export const TERRAIN_GROUNDWATER_DETAIL_POLICY=freeze({id:'terrain-groundwater-surface-detail-2026-09-15-v1',sourcePolicyId:TERRAIN_GROUNDWATER_POLICY.id,renderOnly:true,deterministic:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,newGeographyIntroduced:false,maxWetRim:.9,maxDryFront:.78,maxCrust:.72,maxMicroRelief:.34,maxNormalStrength:.055,materialKey:'terrain-groundwater-surface-detail-v1'});
export const TERRAIN_GROUNDWATER_DETAIL_CHANNELS=freeze(['wetRim','capillaryDamp','seepageDarkening','puddleCore','puddleEdge','evaporationFront','mineralCrust','fineSedimentFilm','recoveryHalo','freezeWetEdge','marshTransition','dryingContrast','microRelief','surfaceConfidence']);
const stateOf=i=>resolveTerrainGroundwaterState(i);
const fieldOf=s=>{const f=s?.field??{};return freeze({regional:clamp01(f.regional),local:clamp01(f.local),capillary:clamp01(f.capillary),seepage:clamp01(f.seepage),contour:clamp01(f.contour),combined:clamp01(f.combined)})};
export const wetRimSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),w=clamp01(s.surfaceFilm),p=clamp01(s.puddlePersistence),q=clamp01(s.waterTableProximity),f=fieldOf(s),r=smooth(.34,.75,w)*(1-smooth(.76,.96,w));return clamp01(r*.48+p*.22+q*.18+f.local*.12)};
export const capillaryDampSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),c=clamp01(s.capillaryRise),r=clamp01(s.dryingResistance),m=clamp01(s.sample?.moisture),sh=1-smooth(2.5,9.5,safe(s.sample?.slopeDegrees));return clamp01(c*.52+r*.25+m*.13+sh*.1)};
export const seepageDarkeningSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),p=clamp01(s.seepageFace),a=clamp01(s.surfaceSaturation),sl=safe(s.sample?.slopeDegrees),b=smooth(4,24,sl)*(1-smooth(24,48,sl));return clamp01(p*.58+a*.22+b*.2)};
export const puddleCoreSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),p=clamp01(s.puddlePersistence),f=clamp01(s.surfaceFilm),flat=1-smooth(1.5,9,safe(s.sample?.slopeDegrees));return clamp01(p*.58+f*.22+flat*.2)};
export const puddleEdgeSignal=(i,c=.5)=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),core=puddleCoreSignal(s),rim=wetRimSignal(s);return clamp01((1-core)*rim*.52+clamp01(c)*rim*.48)};
export const evaporationFrontSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),m=s.mineralMobilization??{},salt=clamp01(m.saltRing),d=clamp01(1-s.dryingResistance),film=clamp01(s.surfaceFilm),t=smooth(8,34,safe(s.sample?.temperatureC,12));return clamp01(t*d*(1-film)*.54+salt*.31+d*.15)};
export const mineralCrustSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),m=s.mineralMobilization??{},salt=clamp01(m.saltRing),seep=clamp01(s.seepageFace),d=clamp01(1-s.dryingResistance),flat=1-smooth(4,32,safe(s.sample?.slopeDegrees));return clamp01(salt*.55+seep*.14+d*.21+flat*.1)};
export const fineSedimentFilmSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),m=s.mineralMobilization??{},fine=clamp01(m.fineTransport),film=clamp01(s.surfaceFilm),runoff=clamp01(s.sample?.runoff);return clamp01(fine*.55+film*.27+runoff*.18)};
export const recoveryHaloSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),m=clamp01(s.saturationMemory),d=clamp01(s.dryingResistance),f=clamp01(s.surfaceFilm);return clamp01(m*.46+d*.34+f*.2)};
export const freezeWetEdgeSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),stress=clamp01(s.stress?.freezeStress),wet=clamp01(s.surfaceSaturation),t=1-smooth(0,6,safe(s.sample?.temperatureC,12));return clamp01(stress*.54+wet*.31+t*.15)};
export const marshTransitionSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),m=clamp01(s.marshEdgeFactor),w=clamp01(s.surfaceSaturation),low=1-smooth(20,120,safe(s.sample?.heightMeters));return clamp01(m*.48+w*.34+low*.18)};
export const dryingContrastSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),d=clamp01(1-s.dryingResistance),e=evaporationFrontSignal(s),m=clamp01(s.saturationMemory);return clamp01(d*.48+e*.37+(1-m)*.15)};
export const microReliefSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),f=fieldOf(s),sl=clamp01(safe(s.sample?.slopeDegrees)/89),fine=fineSedimentFilmSignal(s);return clamp01(f.capillary*.3+f.seepage*.24+fine*.24+sl*.08+f.local*.14)};
export const surfaceConfidenceSignal=i=>{const s=i.policyId===TERRAIN_GROUNDWATER_POLICY.id?i:stateOf(i),sample=s.sample??{},keys=['worldX','worldZ','heightMeters','slopeDegrees','moisture','rainfall','runoff','soilDepth','permeability','waterDistanceMeters','groundwaterDepthMeters','wetDays','dryDays','dayOfYear','temperatureC','drainage','windExposure'];const present=keys.reduce((sum,k)=>sum+(Number.isFinite(Number(sample[k]))?1:0),0);return clamp01((present/keys.length)*.64+fieldOf(s).combined*.36)};
export function resolveGroundwaterSurfaceDetail(i={}){const s=stateOf(i),c=freeze({wetRim:wetRimSignal(s),capillaryDamp:capillaryDampSignal(s),seepageDarkening:seepageDarkeningSignal(s),puddleCore:puddleCoreSignal(s),puddleEdge:puddleEdgeSignal(s,i.localContrast??.5),evaporationFront:evaporationFrontSignal(s),mineralCrust:mineralCrustSignal(s),fineSedimentFilm:fineSedimentFilmSignal(s),recoveryHalo:recoveryHaloSignal(s),freezeWetEdge:freezeWetEdgeSignal(s),marshTransition:marshTransitionSignal(s),dryingContrast:dryingContrastSignal(s),microRelief:microReliefSignal(s),surfaceConfidence:surfaceConfidenceSignal(s)});return freeze({policyId:TERRAIN_GROUNDWATER_DETAIL_POLICY.id,sourcePolicyId:TERRAIN_GROUNDWATER_POLICY.id,state:s,channels:c,canonical:freeze({heightUnchanged:true,hydrologyUnchanged:true,coastlineUnchanged:true,colliderUnchanged:true,vegetationPlacementUnchanged:true,newGeographyIntroduced:false})})}
export function blendSurfaceDetail(a,b,m=.5){const t=clamp01(m),c={};for(const k of TERRAIN_GROUNDWATER_DETAIL_CHANNELS)c[k]=lerp(clamp01(a.channels?.[k]),clamp01(b.channels?.[k]),t);return freeze({policyId:TERRAIN_GROUNDWATER_DETAIL_POLICY.id,sourcePolicyId:TERRAIN_GROUNDWATER_POLICY.id,channels:freeze(c),canonical:freeze({heightUnchanged:true,hydrologyUnchanged:true,coastlineUnchanged:true,colliderUnchanged:true,vegetationPlacementUnchanged:true,newGeographyIntroduced:false})})}
export function detailMaterialResponse(d,baseColor={r:.42,g:.36,b:.28},baseRoughness=.86){const c=d.channels,w=c.wetRim*.012+c.seepageDarkening*.009+c.puddleCore*.006,cr=c.mineralCrust*.01+c.evaporationFront*.004,f=c.fineSedimentFilm*.006,color=freeze({r:clamp01(baseColor.r-w*.72+cr*.82+f*.35),g:clamp01(baseColor.g-w*.54+cr*.58+f*.24),b:clamp01(baseColor.b+w*.31+cr*.18+f*.16)});return freeze({color,roughness:clamp01(baseRoughness-c.puddleCore*.044-c.wetRim*.021+c.mineralCrust*.033+c.dryingContrast*.018),normalStrength:clamp01(c.microRelief*.024+c.puddleEdge*.016+c.freezeWetEdge*.015+c.fineSedimentFilm*.01),wetness:clamp01(c.puddleCore*.42+c.wetRim*.26+c.capillaryDamp*.2+c.marshTransition*.12)})}
export function detailEventDelta(d,e={}){const c=d.channels,t=typeof e.type==='string'?e.type:'neutral',i=clamp01(e.intensity??.5),o={color:0,roughness:0,normal:0,wetness:0};if(t==='storm'){o.color-=c.wetRim*.008*i;o.roughness-=c.puddleCore*.031*i;o.normal+=c.seepageDarkening*.021*i;o.wetness+=.06*i}if(t==='drought'){o.color+=c.mineralCrust*.007*i;o.roughness+=c.evaporationFront*.034*i;o.normal+=c.dryingContrast*.01*i;o.wetness-=.06*i}if(t==='freeze-thaw'){o.color-=c.freezeWetEdge*.003*i;o.roughness+=c.freezeWetEdge*.024*i;o.normal+=c.microRelief*.026*i}if(t==='snowmelt'){o.color-=c.capillaryDamp*.004*i;o.roughness-=c.wetRim*.021*i;o.normal+=c.puddleEdge*.01*i;o.wetness+=.08*i}if(t==='recovery'){o.color-=c.recoveryHalo*.002*i;o.roughness-=c.recoveryHalo*.014*i;o.wetness+=c.recoveryHalo*.025*i}return freeze(o)}
export function applyDetailEvent(m,e={}){const b=m??{color:{r:.42,g:.36,b:.28},roughness:.86,normalStrength:0,wetness:0},d=e;return freeze({color:freeze({r:clamp01(safe(b.color?.r,.42)+safe(d.color)*.72),g:clamp01(safe(b.color?.g,.36)+safe(d.color)*.56),b:clamp01(safe(b.color?.b,.28)+safe(d.color)*.34)}),roughness:clamp01(safe(b.roughness,.86)+safe(d.roughness)),normalStrength:clamp01(safe(b.normalStrength)+safe(d.normal)),wetness:clamp01(safe(b.wetness)+safe(d.wetness))})}
export function detailCanonicalAudit(d){const c=d?.canonical??{},f=[];if(c.heightUnchanged!==true)f.push('height');if(c.hydrologyUnchanged!==true)f.push('hydrology');if(c.coastlineUnchanged!==true)f.push('coastline');if(c.colliderUnchanged!==true)f.push('collider');if(c.vegetationPlacementUnchanged!==true)f.push('vegetation');if(c.newGeographyIntroduced!==false)f.push('new-geography');return freeze({ok:f.length===0,failures:freeze(f),mutationCount:0})}
export function detailSignature(d){return freeze(Object.fromEntries(TERRAIN_GROUNDWATER_DETAIL_CHANNELS.map(k=>[k,Number(clamp01(d.channels[k]).toFixed(6))])))}
export function compareSurfaceDetails(a,b){return freeze(Object.fromEntries(TERRAIN_GROUNDWATER_DETAIL_CHANNELS.map(k=>[k,Number((clamp01(b.channels?.[k])-clamp01(a.channels?.[k])).toFixed(6))])))}
export function surfaceDetailDistance(a,b){let t=0;for(const k of TERRAIN_GROUNDWATER_DETAIL_CHANNELS){const d=clamp01(a.channels?.[k])-clamp01(b.channels?.[k]);t+=d*d}return Math.sqrt(t/TERRAIN_GROUNDWATER_DETAIL_CHANNELS.length)}
export function classifySurfaceDetail(d){const c=d.channels;if(c.puddleCore>.72&&c.wetRim>.58)return'puddle-core';if(c.marshTransition>.72)return'marsh-transition';if(c.seepageDarkening>.66)return'seepage-band';if(c.mineralCrust>.64&&c.evaporationFront>.56)return'evaporative-crust';if(c.capillaryDamp>.62)return'capillary-damp';if(c.freezeWetEdge>.61)return'freeze-wet-edge';if(c.dryingContrast>.72)return'drying-front';if(c.wetRim>.48)return'wet-rim';return'neutral'}
export function detailEnvelope(d){const e=[];for(const k of TERRAIN_GROUNDWATER_DETAIL_CHANNELS){const v=Number(d.channels?.[k]);if(!Number.isFinite(v))e.push(`${k}:not-finite`);else if(v<0||v>1)e.push(`${k}:out-of-range`)}return freeze({ok:e.length===0,errors:freeze(e)})}
export function detailWeightedWetness(d){const c=d.channels;return clamp01(c.puddleCore*.28+c.wetRim*.18+c.capillaryDamp*.18+c.seepageDarkening*.14+c.marshTransition*.1+c.recoveryHalo*.07+c.freezeWetEdge*.05)}
export function detailDrynessRisk(d){const c=d.channels;return clamp01(c.dryingContrast*.43+c.evaporationFront*.26+c.mineralCrust*.13+(1-c.recoveryHalo)*.18)}
export function detailHydroBalance(d){const w=detailWeightedWetness(d),r=detailDrynessRisk(d);return freeze({wetness:w,dryness:r,net:Number((w-r).toFixed(6))})}
export function detailRenderTier(d){const c=clamp01(d.channels.surfaceConfidence),w=detailWeightedWetness(d),r=detailDrynessRisk(d);if(c<.35)return'suppressed';if(Math.max(w,r)>=.76)return'high';if(Math.max(w,r)>=.52)return'medium';return'low'}
export function detailTelemetry(i={}){const d=resolveGroundwaterSurfaceDetail(i);return freeze({policyId:TERRAIN_GROUNDWATER_DETAIL_POLICY.id,sourcePolicyId:TERRAIN_GROUNDWATER_POLICY.id,signature:detailSignature(d),classification:classifySurfaceDetail(d),tier:detailRenderTier(d),envelope:detailEnvelope(d),canonical:detailCanonicalAudit(d),hydroBalance:detailHydroBalance(d)})}
export function detailGrid({originX=0,originZ=0,columns=5,rows=5,spacing=24,sample={}}={}){const r=[],cols=Math.max(1,Math.min(40,Math.floor(columns))),rowsN=Math.max(1,Math.min(40,Math.floor(rows)));for(let z=0;z<rowsN;z+=1)for(let x=0;x<cols;x+=1){const worldX=safe(originX)+x*safe(spacing),worldZ=safe(originZ)+z*safe(spacing),d=resolveGroundwaterSurfaceDetail({...sample,worldX,worldZ});r.push(freeze({x:worldX,z:worldZ,classification:classifySurfaceDetail(d),wetness:detailWeightedWetness(d),dryness:detailDrynessRisk(d)}))}return freeze(r)}
export function detailNeighborhoodStats(ds=[]){if(!Array.isArray(ds)||!ds.length)return freeze({count:0,wetMean:0,wetMin:0,wetMax:0,dryMean:0,dryMin:0,dryMax:0,contrast:0});const w=ds.map(detailWeightedWetness),r=ds.map(detailDrynessRisk),wm=w.reduce((s,v)=>s+v,0)/w.length,rm=r.reduce((s,v)=>s+v,0)/r.length,wmin=Math.min(...w),wmax=Math.max(...w),rmin=Math.min(...r),rmax=Math.max(...r);return freeze({count:ds.length,wetMean:wm,wetMin:wmin,wetMax:wmax,dryMean:rm,dryMin:rmin,dryMax:rmax,contrast:Math.max(wmax-wmin,rmax-rmin)})}
export const TERRAIN_GROUNDWATER_DETAIL_CANONICAL_INVARIANTS=freeze(['canonicalHeightUnchanged','canonicalHydrologyUnchanged','canonicalCoastlineUnchanged','canonicalColliderUnchanged','canonicalVegetationPlacementUnchanged','newGeographyIntroduced:false']);