import { deterministicSpatialOrdinal } from './terrainEnvironmentSpatialPolicy.js';
import { resolveEnvironmentLod, shouldCullEnvironment } from './terrainEnvironmentLodPolicy.js';
import { biomeTransitionWeights, seasonalAssetWeights } from './terrainEnvironmentClimateTransitions.js';
const freeze=(v)=>Object.freeze(v);const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
export const TERRAIN_ENVIRONMENT_DISTRIBUTION_POLICY=freeze({id:'terrain-environment-distribution-planner-2026-09-07-v2',deterministic:true,noGeometryInstantiation:true,worldSpace:true,minimumSeparationMeters:{tree:8,shrub:3,grass:.7,rock:12,snowPatch:18,house:45,bridge:55},edgeJitterMeters:{tree:14,shrub:7,grass:2,rock:18,snowPatch:24},densityCaps:{tree:320,shrub:520,grass:1400,rock:130,snowPatch:70,house:28,bridge:14},neverUniformGrid:true});
function hashPair(x,z,seed){let h=deterministicSpatialOrdinal(String(seed),x,z,0);h=Math.imul(h^0x9e3779b9,0x85ebca6b);h^=h>>>13;return (h>>>0)/4294967296;}
function categoryJitter(category,worldX,worldZ,seed){const r1=hashPair(worldX,worldZ,`${category}:x:${seed}`);const r2=hashPair(worldX+53.7,worldZ-19.1,`${category}:z:${seed}`);const max=TERRAIN_ENVIRONMENT_DISTRIBUTION_POLICY.edgeJitterMeters[category]??4;return freeze({x:(r1-.5)*max*2,z:(r2-.5)*max*2,rotation:(r1+r2)*Math.PI*2});}
export function distributionDensity(category,{biome='',moisture=.5,elevationMeters=0,slopeDegrees=0,rockWeight=0,snowWeight=0,waterDepth=0,temperatureC=12,windExposure=.5,season='summer'}={}){const c=String(category).toLowerCase();if(waterDepth>.05&&c!=='bridge')return 0;const b=biomeTransitionWeights({biome,moisture,elevationMeters,slopeDegrees,temperatureC});const s=seasonalAssetWeights({season,snowWeight,temperatureC,biome,moisture,windExposure});const slope=clamp(slopeDegrees/65);const rock=clamp(rockWeight);const wet=clamp(moisture);let value=0;if(c==='tree')value=.35+b.forest*.52+b.wetForest*.18-slope*.42-rock*.18+(s.deciduous?.18:0);else if(c==='shrub')value=.34+b.forest*.28+b.heath*.26+b.wetland*.22+(1-slope)*.12;else if(c==='grass')value=.42+b.meadow*.26+b.wetland*.22+b.heath*.12+wet*.10-slope*.15;else if(c==='rock')value=.12+rock*.62+slope*.34+b.alpine*.12;else if(c==='snowPatch')value=.08+clamp(snowWeight)*.72+b.tundra*.16+s.winterVegetation*.12;else if(c==='house')value=.18+clamp(1-slope)*.36+(1-clamp(wet*.62+rock*.28))*.24;else if(c==='bridge')value=.26+(waterDepth>.01?.42:0)+clamp(1-slope)*.18;else value=.1;return clamp(value);}
export function spacingEnvelope(category,{distanceMeters=0,density=1,visibility=1}={}){const base=TERRAIN_ENVIRONMENT_DISTRIBUTION_POLICY.minimumSeparationMeters[category]??5;const d=Math.max(0,finite(distanceMeters));const distanceMultiplier=d<80?.75:d<350?1:d<1100?1.35:1.8;const visibilityMultiplier=clamp(visibility,.35,1.15);return freeze({category,baseMeters:base,separationMeters:base*distanceMultiplier/Math.sqrt(Math.max(.2,finite(density,1)))*visibilityMultiplier});}
export function environmentPointCandidate({category='',worldX=0,worldZ=0,seed=0,biome='',moisture=.5,elevationMeters=0,slopeDegrees=0,rockWeight=0,snowWeight=0,waterDepth=0,temperatureC=12,windExposure=.5,season='summer',distanceMeters=0,visibility=1,ordinal=0}={}){const density=distributionDensity(category,{biome,moisture,elevationMeters,slopeDegrees,rockWeight,snowWeight,waterDepth,temperatureC,windExposure,season});const lod=resolveEnvironmentLod(category,distanceMeters);const jitter=categoryJitter(category,worldX,worldZ,`${seed}:${ordinal}`);const spacing=spacingEnvelope(category,{distanceMeters,density,visibility});const weights=biomeTransitionWeights({biome,moisture,elevationMeters,slopeDegrees,temperatureC});const centeredX=finite(worldX)+jitter.x;const centeredZ=finite(worldZ)+jitter.z;const ordinalSeed=deterministicSpatialOrdinal(`${category}:${biome}`,centeredX,centeredZ,ordinal);const acceptance=freeze({densityAccepted:density>.08,culled:shouldCullEnvironment(category,distanceMeters),lod:lod.level,minimumSpacingMeters:spacing.separationMeters,waterAccepted:waterDepth<=.05||category==='bridge'});return freeze({category,sourceWorld:{x:finite(worldX),z:finite(worldZ)},candidateWorld:{x:centeredX,z:centeredZ},rotationY:jitter.rotation,seed:ordinalSeed,density,transition:freeze({forest:weights.forest,wetForest:weights.wetForest,meadow:weights.meadow,heath:weights.heath,tundra:weights.tundra,wetland:weights.wetland,alpine:weights.alpine}),spacing,lod,acceptance});}
export function planEnvironmentCluster({category='',centerX=0,centerZ=0,radiusMeters=100,count=24,seed=0,context={}}={}){const requested=Math.max(0,Math.floor(finite(count,0)));const cap=TERRAIN_ENVIRONMENT_DISTRIBUTION_POLICY.densityCaps[category]??requested;const total=Math.min(requested,cap);const points=[];const golden=2.399963229728653;for(let i=0;i<total;i+=1){const radial=Math.sqrt((i+.5)/Math.max(1,total))*Math.max(0,finite(radiusMeters));const angle=i*golden+hashPair(centerX,centerZ,`${seed}:${category}:angle`)*Math.PI*2;const point=environmentPointCandidate({category,worldX:finite(centerX)+Math.cos(angle)*radial,worldZ:finite(centerZ)+Math.sin(angle)*radial,seed,ordinal:i,...context});if(point.acceptance.densityAccepted&&!point.acceptance.culled&&point.acceptance.waterAccepted)points.push(point);}const filtered=applyClusterSeparation(points);return freeze({version:1,policyId:TERRAIN_ENVIRONMENT_DISTRIBUTION_POLICY.id,category,center:{x:finite(centerX),z:finite(centerZ)},requested,planned:filtered.length,cap,points:freeze(filtered),acceptance:freeze({ok:true,uniformGrid:false,separationEnforced:true})});}
function applyClusterSeparation(points){const accepted=[];for(const point of points){let close=false;for(const prior of accepted){const dx=point.candidateWorld.x-prior.candidateWorld.x,dz=point.candidateWorld.z-prior.candidateWorld.z;const minDistance=Math.max(point.spacing.separationMeters,prior.spacing.separationMeters);if(dx*dx+dz*dz<minDistance*minDistance){close=true;break;}}if(!close)accepted.push(point);}return accepted;}
export function planBiomeClusterSet({regions=[],category='tree',seed=0}={}){const clusters=regions.map((region,index)=>planEnvironmentCluster({category,centerX:region.centerX,centerZ:region.centerZ,radiusMeters:region.radiusMeters,count:region.count,seed:`${seed}:${index}`,context:region.context??{}}));const total=clusters.reduce((sum,c)=>sum+c.planned,0);return freeze({policyId:TERRAIN_ENVIRONMENT_DISTRIBUTION_POLICY.id,category,clusters,summary:freeze({regions:clusters.length,total}),acceptance:freeze({ok:clusters.every(c=>c.acceptance.ok),uniformGrid:false})});}
export function distributionAudit(cluster){const errors=[];const points=cluster?.points??[];if(cluster?.acceptance?.uniformGrid)errors.push('uniform-grid');for(const point of points){if(point.acceptance?.culled)errors.push('culled-point-present');if(point.density<=0)errors.push('zero-density-point');if(point.candidateWorld?.x==null||point.candidateWorld?.z==null)errors.push('missing-world-position');}return freeze({ok:errors.length===0,errors:freeze(errors),count:points.length});}
