/** Deterministic render-only micro-wind exposure and shelter response. */
const clamp01=v=>Math.max(0,Math.min(1,v));
const lerp=(a,b,t)=>a+(b-a)*t;
function hash(x,z,s){let h=Math.imul((x|0)^s,0x45d9f3b)^Math.imul((z|0)+s,0x119de1f3);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return(h>>>0)/4294967296;}
function noise(x,z,s){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,u=fx*fx*(3-2*fx),v=fz*fz*(3-2*fz);return lerp(lerp(hash(ix,iz,s),hash(ix+1,iz,s),u),lerp(hash(ix,iz+1,s),hash(ix+1,iz+1,s),u),v);}
function fbm(x,z,s,n=4){let v=0,w=0,a=.58;for(let i=0;i<n;i+=1){v+=noise(x,z,s+i*71)*a;w+=a;x=x*2.01+3.7;z=z*2.03-4.6;a*=.49;}return v/w;}
function ridge(x,z,s){return 1-Math.abs(fbm(x,z,s)*2-1);}
export const TERRAIN_WIND_EXPOSURE_POLICY=Object.freeze({id:'terrain-surface-wind-exposure-2026-09-15-v1',renderOnly:true,deterministic:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,newGeographyIntroduced:false,windBearingRadians:2.31,macroScaleMeters:980,exposureScaleMeters:Object.freeze([280,92,28,8]),shelterScaleMeters:Object.freeze([420,120,34]),gustScaleMeters:Object.freeze([64,17,5]),maxAlbedoShift:.052,maxRoughnessShift:.061,maxNormalStrength:.041,materialKey:'terrain-surface-wind-exposure-v1'});
export const TERRAIN_WIND_CANONICAL_INVARIANTS=Object.freeze(['canonicalHeightUnchanged','canonicalHydrologyUnchanged','canonicalCoastlineUnchanged','canonicalColliderUnchanged','canonicalVegetationPlacementUnchanged','newGeographyIntroduced:false']);
function rotate(x,z,a){const c=Math.cos(a),s=Math.sin(a);return{x:x*c-z*s,z:x*s+z*c};}
export function resolveTerrainWindExposureState({worldX,worldZ,heightMeters,slopeDegrees=0,moisture=.5}){const x=Number(worldX)||0,z=Number(worldZ)||0,h=Number(heightMeters)||0,s=Math.max(0,Number(slopeDegrees)||0),m=clamp01(Number(moisture)||0),p=rotate(x,z,TERRAIN_WIND_EXPOSURE_POLICY.windBearingRadians),macro=fbm(x/980,z/980,0x6701,5),exposure=clamp01(fbm(p.x/280,p.z/92,0x6702)*.56+ridge(p.x/92,p.z/28,0x6703)*.44),shelter=clamp01(fbm(-p.x/420,p.z/120,0x6704)*.62+ridge(p.x/120,p.z/34,0x6705)*.38),gust=clamp01(ridge(p.x/64,p.z/17,0x6706)*.58+noise(p.x/5,p.z/5,0x6707)*.42),heightBoost=clamp01(.26+smoothstep(120,1600,h)*.44),slopeBoost=clamp01(.32+smoothstep(3,28,s)*.44),windward=clamp01((.38+exposure*.62)*(1-shelter*.38)*heightBoost),lee=clamp01(shelter*(.44+macro*.24+gust*.32)),abrasion=clamp01(windward*(.42+slopeBoost*.28+gust*.30)*(1-m*.22)),dustLift=clamp01(windward*(.46+gust*.34+macro*.20)*(1-m*.30)),surfaceShelter=clamp01(shelter*(.58+(.22+m*.22))),calmPocket=clamp01(surfaceShelter*(1-slopeBoost*.26)*(1-windward*.32)),driftMask=clamp01(dustLift*(.52+lee*.48));return Object.freeze({macro,exposure,shelter,gust,heightBoost,slopeBoost,windward,lee,abrasion,dustLift,surfaceShelter,calmPocket,driftMask});}
function smoothstep(a,b,v){const t=clamp01((v-a)/Math.max(1e-9,b-a));return t*t*(3-2*t);}
export function resolveTerrainWindMaterialResponse({state,baseColor,baseRoughness=.86}){const abrasion=state.abrasion*.025,dust=state.driftMask*.020,calm=state.calmPocket*.012;return Object.freeze({color:Object.freeze({r:clamp01(baseColor.r+dust*.74-abrasion*.30),g:clamp01(baseColor.g+dust*.62-abrasion*.24),b:clamp01(baseColor.b+dust*.48-abrasion*.18)}),roughness:clamp01(baseRoughness+abrasion*.042+state.gust*.018-calm*.035),normalStrength:clamp01(state.gust*.021+state.abrasion*.026)});}
export const TERRAIN_WIND_EXPOSURE_GLSL=String.raw`
float terrainWindHash(vec2 p){vec3 q=fract(vec3(p.xyx)*vec3(.1031,.103,.0973));q+=dot(q,q.yzx+33.33);return fract((q.x+q.y)*q.z);}float terrainWindNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(terrainWindHash(i),terrainWindHash(i+vec2(1,0)),f.x),mix(terrainWindHash(i+vec2(0,1)),terrainWindHash(i+vec2(1,1)),f.x),f.y);}float terrainWindFbm(vec2 p){float v=0.,w=0.,a=.58;for(int i=0;i<5;i++){v+=terrainWindNoise(p)*a;w+=a;p=p*2.01+vec2(3.7,-4.6);a*=.49;}return v/w;}float terrainWindRidge(vec2 p){return 1.-abs(terrainWindFbm(p)*2.-1.);}void terrainWindExposureApplyColor(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;float slope=1.-clamp(abs(normalize(vTerrainLowWorldNormal).y),0.,1.);float expv=clamp(terrainWindFbm(p/vec2(280.,92.))*.56+terrainWindRidge(p/vec2(92.,28.))*.44,0.,1.);float shelter=clamp(terrainWindFbm(p/vec2(420.,120.))*.62+terrainWindRidge(p/vec2(120.,34.))*.38,0.,1.);float gust=terrainWindRidge(p/vec2(64.,17.));float windward=clamp((.38+expv*.62)*(1.-shelter*.38)*(.26+smoothstep(120.,1600.,h)*.44),0.,1.);float dust=clamp(windward*(.46+gust*.34)*(.70+smoothstep(.05,.55,1.-dot(diffuseColor.rgb,vec3(.2126,.7152,.0722)))*.30),0.,1.);diffuseColor.rgb+=vec3(.020,.016,.012)*dust*.55-dust*vec3(.003,.002,.001);}
void terrainWindExposureApplyRoughness(){vec2 p=vTerrainLowWorldPosition.xz;float shelter=terrainWindRidge(p/vec2(120.,34.));float gust=terrainWindRidge(p/vec2(64.,17.));float abrasion=clamp((.32+gust*.48)*(1.-shelter*.26),0.,1.);roughnessFactor=clamp(roughnessFactor+abrasion*.038-shelter*.024,0.42,1.0);}
void terrainWindExposureApplyNormal(){vec2 p=vTerrainLowWorldPosition.xz;float gust=terrainWindRidge(p/vec2(64.,17.));float a=terrainWindNoise(p/8.+vec2(1.4,-3.2)),b=terrainWindNoise(p/8.+vec2(2.1,-2.6));normal=normalize(normal+mat3(viewMatrix)*vec3(-(b-a),0.,(b-a)*.55)*gust*.034);}
`;
export function installTerrainWindExposure(material){if(!material)throw new TypeError('terrain wind exposure requires a material');if(material.userData?.terrainWindExposureInstalled)return material;const previous=material.onBeforeCompile.bind(material);material.onBeforeCompile=(shader,renderer)=>{previous(shader,renderer);shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\n${TERRAIN_WIND_EXPOSURE_GLSL}`).replace('#include <color_fragment>','#include <color_fragment>\nterrainWindExposureApplyColor();').replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nterrainWindExposureApplyRoughness();').replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nterrainWindExposureApplyNormal();');};const previousKey=material.customProgramCacheKey?.bind(material);material.customProgramCacheKey=()=>`${previousKey?previousKey():''}|${TERRAIN_WIND_EXPOSURE_POLICY.materialKey}`;material.userData={...material.userData,terrainWindExposureInstalled:true,terrainWindExposurePolicyId:TERRAIN_WIND_EXPOSURE_POLICY.id,terrainWindExposureRenderOnly:true};material.needsUpdate=true;return material;}
export function windExposurePolicySnapshot(){return Object.freeze({id:TERRAIN_WIND_EXPOSURE_POLICY.id,windBearingRadians:TERRAIN_WIND_EXPOSURE_POLICY.windBearingRadians,scales:TERRAIN_WIND_EXPOSURE_POLICY.exposureScaleMeters,renderOnly:true,deterministic:true,invariants:TERRAIN_WIND_CANONICAL_INVARIANTS});}
