/** Deterministic render-only thermal microclimate response. */
const clamp01=v=>Math.max(0,Math.min(1,v));
const lerp=(a,b,t)=>a+(b-a)*t;
function hash(x,z,s){let h=Math.imul((x|0)^s,0x45d9f3b)^Math.imul((z|0)+s,0x119de1f3);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return(h>>>0)/4294967296;}
function noise(x,z,s){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,u=fx*fx*(3-2*fx),v=fz*fz*(3-2*fz);return lerp(lerp(hash(ix,iz,s),hash(ix+1,iz,s),u),lerp(hash(ix,iz+1,s),hash(ix+1,iz+1,s),u),v);}
function fbm(x,z,s,n=4){let v=0,w=0,a=.56;for(let i=0;i<n;i+=1){v+=noise(x,z,s+i*79)*a;w+=a;x=x*2.02+4.4;z=z*2.01-6.3;a*=.48;}return v/w;}
function smoothstep(a,b,v){const t=clamp01((v-a)/Math.max(1e-9,b-a));return t*t*(3-2*t);}
export const TERRAIN_THERMAL_MICROCLIMATE_POLICY=Object.freeze({id:'terrain-surface-thermal-microclimate-2026-09-15-v1',renderOnly:true,deterministic:true,canonicalHeightUnchanged:true,canonicalHydrologyUnchanged:true,canonicalCoastlineUnchanged:true,canonicalColliderUnchanged:true,canonicalVegetationPlacementUnchanged:true,newGeographyIntroduced:false,insolationScaleMeters:Object.freeze([620,180,42]),coldPoolScaleMeters:Object.freeze([780,240,68]),thermalScaleMeters:Object.freeze([360,94,24]),shadeScaleMeters:Object.freeze([150,38,9]),maxAlbedoShift:.048,maxRoughnessShift:.055,maxNormalStrength:.038,materialKey:'terrain-surface-thermal-microclimate-v1'});
export const TERRAIN_THERMAL_CANONICAL_INVARIANTS=Object.freeze(['canonicalHeightUnchanged','canonicalHydrologyUnchanged','canonicalCoastlineUnchanged','canonicalColliderUnchanged','canonicalVegetationPlacementUnchanged','newGeographyIntroduced:false']);
export function resolveTerrainThermalMicroclimateState({worldX,worldZ,heightMeters,slopeDegrees=0,moisture=.5,baseColor={r:.35,g:.42,b:.30}}){const x=Number(worldX)||0,z=Number(worldZ)||0,h=Number(heightMeters)||0,s=Math.max(0,Number(slopeDegrees)||0),m=clamp01(Number(moisture)||0),luma=clamp01(baseColor.r*.2126+baseColor.g*.7152+baseColor.b*.0722),insolation=clamp01(fbm(x/620,z/620,0x6801,5)*.54+fbm(x/180,z/180,0x6802,3)*.26+noise(x/42,z/42,0x6803)*.20),coldPool=clamp01(fbm(x/780,z/780,0x6810,5)*.64+fbm(x/240,z/240,0x6811,3)*.36),thermal=clamp01(fbm(x/360,z/360,0x6820,4)*.60+noise(x/24,z/24,0x6821)*.40),shade=clamp01(1-insolation*.54+fbm(x/38,z/38,0x6830)*.46),elevation=clamp01(smoothstep(120,1900,h)),slopeCooling=clamp01(smoothstep(4,34,s)),drying=clamp01(insolation*(.48+(1-m)*.32+(1-luma)*.20)),radiativeCooling=clamp01((1-insolation)*.46+(1-m)*.18+coldPool*.36+slopeCooling*.10),freezeRisk=clamp01(elevation*.38+radiativeCooling*.34+m*.18+thermal*.10),heatLoad=clamp01(insolation*.50+elevation*.18+(1-m)*.18+thermal*.14),dewRetention=clamp01(m*.58+(1-insolation)*.22+coldPool*.20),surfaceRange=clamp01(.20+thermal*.28+heatLoad*.26+radiativeCooling*.26),microShade=clamp01(shade*(.58+coldPool*.22+dewRetention*.20));return Object.freeze({insolation,coldPool,thermal,shade,elevation,slopeCooling,drying,radiativeCooling,freezeRisk,heatLoad,dewRetention,surfaceRange,microShade});}
export function resolveTerrainThermalMaterialResponse({state,baseColor,baseRoughness=.86}){const heat=state.heatLoad*.018,cold=state.radiativeCooling*.017,dew=state.dewRetention*.012;return Object.freeze({color:Object.freeze({r:clamp01(baseColor.r+heat*.42-cold*.20-dew*.06),g:clamp01(baseColor.g+heat*.25+cold*.10),b:clamp01(baseColor.b-cold*.12+dew*.10)}),roughness:clamp01(baseRoughness+state.surfaceRange*.032+state.freezeRisk*.022-state.dewRetention*.028),normalStrength:clamp01(state.surfaceRange*.018+state.freezeRisk*.020)});}
export const TERRAIN_THERMAL_MICROCLIMATE_GLSL=String.raw`
float terrainThermalHash(vec2 p){vec3 q=fract(vec3(p.xyx)*vec3(.1031,.103,.0973));q+=dot(q,q.yzx+33.33);return fract((q.x+q.y)*q.z);}float terrainThermalNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(terrainThermalHash(i),terrainThermalHash(i+vec2(1,0)),f.x),mix(terrainThermalHash(i+vec2(0,1)),terrainThermalHash(i+vec2(1,1)),f.x),f.y);}float terrainThermalFbm(vec2 p){float v=0.,w=0.,a=.56;for(int i=0;i<5;i++){v+=terrainThermalNoise(p)*a;w+=a;p=p*2.02+vec2(4.4,-6.3);a*=.48;}return v/w;}void terrainThermalApplyColor(){vec2 p=vTerrainLowWorldPosition.xz;float h=vTerrainLowWorldPosition.y;float ins=clamp(terrainThermalFbm(p/180.)*.70+terrainThermalNoise(p/42.)*.30,0.,1.);float cold=clamp(terrainThermalFbm(p/vec2(780.,240.))*.64+terrainThermalFbm(p/vec2(240.,68.))*.36,0.,1.);float slope=1.-clamp(abs(normalize(vTerrainLowWorldNormal).y),0.,1.);float freeze=clamp(smoothstep(120.,1900.,h)*.42+(1.-ins)*.26+cold*.24+smoothstep(.08,.42,slope)*.08,0.,1.);float heat=clamp(ins*.58+smoothstep(120.,1900.,h)*.16+(1.-dot(diffuseColor.rgb,vec3(.2126,.7152,.0722)))*.16,0.,1.);diffuseColor.rgb+=vec3(.009,.006,.003)*heat*.60-vec3(.005,.006,.008)*freeze*.42;}
void terrainThermalApplyRoughness(){vec2 p=vTerrainLowWorldPosition.xz;float ins=terrainThermalFbm(p/180.);float cold=terrainThermalFbm(p/vec2(780.,240.));roughnessFactor=clamp(roughnessFactor+ins*.024+cold*.018-ins*cold*.030,0.42,1.0);}
void terrainThermalApplyNormal(){vec2 p=vTerrainLowWorldPosition.xz;float a=terrainThermalNoise(p/9.+vec2(1.2,-2.8)),b=terrainThermalNoise(p/9.+vec2(2.0,-2.1));float h=smoothstep(120.,1900.,vTerrainLowWorldPosition.y);normal=normalize(normal+mat3(viewMatrix)*vec3(-(b-a),0.,(b-a)*.44)*h*.032);}
`;
export function installTerrainThermalMicroclimate(material){if(!material)throw new TypeError('terrain thermal microclimate requires a material');if(material.userData?.terrainThermalMicroclimateInstalled)return material;const previous=material.onBeforeCompile.bind(material);material.onBeforeCompile=(shader,renderer)=>{previous(shader,renderer);shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\n${TERRAIN_THERMAL_MICROCLIMATE_GLSL}`).replace('#include <color_fragment>','#include <color_fragment>\nterrainThermalApplyColor();').replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nterrainThermalApplyRoughness();').replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nterrainThermalApplyNormal();');};const previousKey=material.customProgramCacheKey?.bind(material);material.customProgramCacheKey=()=>`${previousKey?previousKey():''}|${TERRAIN_THERMAL_MICROCLIMATE_POLICY.materialKey}`;material.userData={...material.userData,terrainThermalMicroclimateInstalled:true,terrainThermalMicroclimatePolicyId:TERRAIN_THERMAL_MICROCLIMATE_POLICY.id,terrainThermalMicroclimateRenderOnly:true};material.needsUpdate=true;return material;}
export function thermalMicroclimatePolicySnapshot(){return Object.freeze({id:TERRAIN_THERMAL_MICROCLIMATE_POLICY.id,scales:Object.freeze({insolation:TERRAIN_THERMAL_MICROCLIMATE_POLICY.insolationScaleMeters,coldPool:TERRAIN_THERMAL_MICROCLIMATE_POLICY.coldPoolScaleMeters,thermal:TERRAIN_THERMAL_MICROCLIMATE_POLICY.thermalScaleMeters}),renderOnly:true,deterministic:true,invariants:TERRAIN_THERMAL_CANONICAL_INVARIANTS});}
