/** Shared LOD/instancing/culling budget for authored environment families. */
const freeze=(v)=>Object.freeze(v);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const TERRAIN_ENVIRONMENT_LOD_POLICY=freeze({id:'terrain-environment-lod-instancing-2026-09-07-v2',deterministic:true,instancePreferred:true,cullingRequired:true,placeholderAllowed:false,budgets:freeze({mobile:{drawCalls:180,visibleInstances:1100,textureMB:180},desktop:{drawCalls:420,visibleInstances:4200,textureMB:700}})});
export const ENVIRONMENT_LOD_FAMILIES=freeze({
 tree:freeze({levels:freeze([{maxDistance:85,detail:'hero'},{maxDistance:350,detail:'near'},{maxDistance:1100,detail:'mid'},{maxDistance:2300,detail:'cluster'}]),instanceable:true,shadowDistance:350}),
 shrub:freeze({levels:freeze([{maxDistance:45,detail:'hero'},{maxDistance:180,detail:'near'},{maxDistance:550,detail:'mid'},{maxDistance:1150,detail:'impostor'}]),instanceable:true,shadowDistance:120}),
 grass:freeze({levels:freeze([{maxDistance:14,detail:'blade'},{maxDistance:55,detail:'clump'},{maxDistance:240,detail:'cluster'},{maxDistance:900,detail:'ground'}]),instanceable:true,shadowDistance:35}),
 rock:freeze({levels:freeze([{maxDistance:80,detail:'hero'},{maxDistance:300,detail:'near'},{maxDistance:1200,detail:'mid'},{maxDistance:2900,detail:'cluster'}]),instanceable:true,shadowDistance:650}),
 cliff:freeze({levels:freeze([{maxDistance:160,detail:'hero'},{maxDistance:650,detail:'near'},{maxDistance:1900,detail:'mid'},{maxDistance:4300,detail:'far'}]),instanceable:true,shadowDistance:1200}),
 scree:freeze({levels:freeze([{maxDistance:40,detail:'fragment'},{maxDistance:160,detail:'near'},{maxDistance:700,detail:'cluster'},{maxDistance:1700,detail:'field'}]),instanceable:true,shadowDistance:200}),
 snowPatch:freeze({levels:freeze([{maxDistance:70,detail:'edge'},{maxDistance:280,detail:'near'},{maxDistance:1100,detail:'mid'},{maxDistance:3100,detail:'far'}]),instanceable:true,shadowDistance:650}),
 house:freeze({levels:freeze([{maxDistance:180,detail:'hero'},{maxDistance:700,detail:'near'},{maxDistance:2100,detail:'mid'},{maxDistance:4300,detail:'far'}]),instanceable:false,shadowDistance:1600}),
 bridge:freeze({levels:freeze([{maxDistance:150,detail:'hero'},{maxDistance:620,detail:'near'},{maxDistance:1600,detail:'mid'},{maxDistance:2700,detail:'far'}]),instanceable:false,shadowDistance:900}),
});
export function resolveEnvironmentLod(category,distanceMeters){const family=ENVIRONMENT_LOD_FAMILIES[category]??ENVIRONMENT_LOD_FAMILIES.rock;const d=Math.max(0,Number(distanceMeters)||0);const found=family.levels.findIndex((entry)=>d<=entry.maxDistance);const level=found<0?family.levels.length-1:found;return freeze({category,level,detail:family.levels[level].detail,distanceMeters:d,instanceable:family.instanceable,castShadow:d<=family.shadowDistance});}
export function shouldCullEnvironment(category,distanceMeters){const family=ENVIRONMENT_LOD_FAMILIES[category]??ENVIRONMENT_LOD_FAMILIES.rock;return Number(distanceMeters)>family.levels.at(-1).maxDistance;}
export function instanceBatchKey({assetId='',materialKey='',lod=0,season='default',substrate='default'}={}){return `${assetId}|${materialKey}|lod:${lod}|season:${season}|substrate:${substrate}`;}
export function estimateEnvironmentBatchCost(instances=0,trianglesPerInstance=0,materialSlots=1){const n=Math.max(0,Number(instances)||0),t=Math.max(0,Number(trianglesPerInstance)||0),m=Math.max(1,Number(materialSlots)||1);return freeze({instances:n,triangles:n*t,materialSlots:m,drawCalls:m,relativeGpuCost:clamp((n*t)/1600000*.62+m/8*.38,0,10)});}
export function environmentCullingScore({distanceMeters=0,screenAreaRatio=.01,importance=1,ecotoneWeight=0}={}){const d=Math.max(0,Number(distanceMeters)||0),area=clamp(Number(screenAreaRatio)||0,0,1),imp=clamp(Number(importance)||0,0,4),eco=clamp(Number(ecotoneWeight)||0,0,1);return clamp(imp*.26+area*2.6+(1-clamp(d/4500))*0.18+eco*.11,0,3.1);}
export function buildLodManifest(samples=[]){const entries=samples.map((s)=>{const lod=resolveEnvironmentLod(s.category,s.distanceMeters);return {category:s.category,distanceMeters:s.distanceMeters,lod,culled:shouldCullEnvironment(s.category,s.distanceMeters),batchKey:instanceBatchKey({assetId:s.assetId,materialKey:s.materialKey,lod:lod.level,season:s.season,substrate:s.substrate})};});return freeze({version:2,policyId:TERRAIN_ENVIRONMENT_LOD_POLICY.id,entries,acceptance:freeze({cullingDefined:true,instancePreferred:true,substrateAwareBatching:true})});}
export function validateLodPolicy(){const errors=[];for(const [category,family] of Object.entries(ENVIRONMENT_LOD_FAMILIES)){for(let i=1;i<family.levels.length;i+=1)if(family.levels[i].maxDistance<=family.levels[i-1].maxDistance)errors.push(`non-monotonic:${category}`);if(family.levels.length<3)errors.push(`insufficient-lod:${category}`);if(category==='grass'&&family.shadowDistance>50)errors.push('grass-shadow-budget');}return freeze({ok:errors.length===0,errors:freeze(errors),policyId:TERRAIN_ENVIRONMENT_LOD_POLICY.id});}
